objects/Associate__c.object
<CustomObject>
    <description>All associates used for Course Bookings</description>
    <fields>
        <fullName>Associate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Associate name lookup to contact</description>
        <label>Associate</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Associate and other Costs (Associate)</relationshipLabel>
        <relationshipName>Associates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date_Invoiced_Received__c</fullName>
        <description>Date associate invoice received</description>
        <inlineHelpText>This field should contain the date the Project related expense was incurred.</inlineHelpText>
        <label>Date Incurred</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>ProjectObject__c</referenceTo>
        <relationshipLabel>Associate and other Costs</relationshipLabel>
        <relationshipName>Associates</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Rechargeable__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Is this associate or other cost rechargeable to the client?</inlineHelpText>
        <label>Rechargeable</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Total_Invoice_Amount__c</fullName>
        <formula>Value__c +  Expenses__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Invoice Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Associate and other Cost</label>
    <nameField>
        <displayFormat>T{00000}</displayFormat>
        <label>T Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Associate and other Costs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Project_Invoice__c.object
<CustomObject>
    <description>Represents the invoice generated for the Time &amp; Expenses of a Project.</description>
    <fields>
        <fullName>End_Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <inlineHelpText>Select the End Date upto which the amount to be billed is calculated</inlineHelpText>
        <label>Invoice End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <description>Project to which this invoice belongs</description>
        <label>Project</label>
        <referenceTo>ProjectObject__c</referenceTo>
        <relationshipLabel>Invoice Requests</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <inlineHelpText>Select the start date from which the amount to be invoiced is calculated</inlineHelpText>
        <label>Invoice Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Invoice Request Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>In Progress</fullName>
                    <default>true</default>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>Submitted for Processing</fullName>
                </value>
                <value>
                    <fullName>Processed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Total_Invoice_Amount__c</fullName>
        <label>Total Service Amount</label>
        <summarizedField>Invoice_Billing_Detail__c.Total_Amount__c</summarizedField>
        <summaryForeignKey>Invoice_Billing_Detail__c.Invoice_Request__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Invoice Request</label>
    <nameField>
        <displayFormat>Inv{000000}</displayFormat>
        <label>Invoice Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/Associate_Manager.cls
public class Associate_Manager{
    
    // This method results in adding Associate records in a list when Date Invoice Received, Rechargeable,CurrencyISo code and Total Invoice amount fields are getting updated.
    public static void Associate_AfterUpdateChecks(List<Associate__c> AssociateNewList, List<Associate__c> AssociateOldList){
        List<Associate__c> associates =  new List<Associate__c>();
        for(integer i=0;i<AssociateNewList.size();i++){ 
          if (AssociateNewList[i].Date_Invoiced_Received__c != AssociateOldList[i].Date_Invoiced_Received__c || AssociateNewList[i].Rechargeable__c != AssociateOldList[i].Rechargeable__c
              || AssociateNewList[i].CurrencyIsoCode != AssociateOldList[i].CurrencyIsoCode || AssociateNewList[i].Total_Invoice_Amount__c != AssociateOldList[i].Total_Invoice_Amount__c){
                    associates.add(AssociateOldList[i]);
                    associates.add(AssociateNewList[i]);
              }   
        }
        updateRelatedInvoices(associates);
    }
    
    // To get related invoices of Associates
    public static Project_Invoice__c[] getRelatedInvoices(Associate__c[] associates){
        //Intialize the list of related invoices.
        List<Project_Invoice__c> invoices = new List<Project_Invoice__c>();
        Map<Id,Project_Invoice__c> invoicesMap = new Map<Id,Project_Invoice__c>();     
        //Loop through each of the expenses if it is bulk update of more than one expenses.
        for(Associate__c selectedAssociate: associates){ 
            //Loop through each of the invoices which need to be updated against this associate.
            for(Project_Invoice__c invoice: [SELECT Id, Start_Date__c, End_Date__c, Project__c,CurrencyIsoCode
                                                FROM Project_Invoice__c 
                                                WHERE Project__c= :selectedAssociate.Project__c 
                                                AND Start_Date__c<= :selectedAssociate.Date_Invoiced_Received__c 
                                                AND End_Date__c>= :selectedAssociate.Date_Invoiced_Received__c
                                                AND Status__c= :'In Progress'])
            {
                 if(!invoicesMap.containsKey(invoice.id)){
                    invoicesMap.put(invoice.id, invoice);
                    invoices.add(invoice);
                 }
            }
         }    
        return invoices;
    }
    
    // Method To update related invoices
    public static void updateRelatedInvoices(Associate__c[] associates){
         //Prepare a list of invoices to be updated.
        List<Project_Invoice__c> invoices = new List<Project_Invoice__c>();
        for(Project_Invoice__c relatedInvoice: getRelatedInvoices(associates))
            invoices.add(ProjectInvoice_Manager.getInvoiceWithUpdatedAmounts(relatedInvoice, false, false, true));        
        //If there are any invoice to be updated
        if(invoices.size()>0)
            update invoices;
    }
       
}