objects/Associate__c.object
<CustomObject>
    <description>All associates used for Course Bookings</description>
    <fields>
        <fullName>Associate_Type__c</fullName>
        <label>Cost Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Actor</fullName>
                </value>
                <value>
                    <fullName>Airfare</fullName>
                </value>
                <value>
                    <fullName>Airfare &amp; Train</fullName>
                </value>
                <value>
                    <fullName>Associate Consultant</fullName>
                </value>
                <value>
                    <fullName>Courier</fullName>
                </value>
                <value>
                    <fullName>Development Team</fullName>
                </value>
                <value>
                    <fullName>External Partner</fullName>
                </value>
                <value>
                    <fullName>Hotels</fullName>
                </value>
                <value>
                    <fullName>LBU</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Product Consumption</fullName>
                </value>
                <value>
                    <fullName>Taxi</fullName>
                </value>
                <value>
                    <fullName>Venue Cost</fullName>
                </value>
                <value>
                    <fullName>Volunteer</fullName>
                </value>
                <value>
                    <fullName>Cross-Border Delivery</fullName>
                </value>
                <value>
                    <fullName>Localisation</fullName>
                </value>
                <value>
                    <fullName>Multimedia Costs</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Associate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Associate name lookup to contact</description>
        <label>Associate</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Associate and other Costs (Associate)</relationshipLabel>
        <relationshipName>Associates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date_Invoiced_Received__c</fullName>
        <description>Date associate invoice received</description>
        <inlineHelpText>This field should contain the date the Project related expense was incurred.</inlineHelpText>
        <label>Date Incurred</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>ProjectObject__c</referenceTo>
        <relationshipLabel>Associate and other Costs</relationshipLabel>
        <relationshipName>Associates</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Rechargeable__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Is this associate or other cost rechargeable to the client?</inlineHelpText>
        <label>Rechargeable</label>
        <type>Checkbox</type>
    </fields>
    <label>Associate and other Cost</label>
    <nameField>
        <displayFormat>T{00000}</displayFormat>
        <label>T Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Associate and other Costs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ProjectObject__c.object
<CustomObject>
    <description>Used for PSA work</description>
    <label>Project</label>
    <nameField>
        <displayFormat>P{000000}</displayFormat>
        <label>Project Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/Associate_TriggerTester.cls
@isTest(seeAllData=true)
public class Associate_TriggerTester 
{
    @isTest
    static void testAssociateTriggers()
    {
        testBasicMethods(null);
        //testSpecialMethods(null);
    }
    
    
    public static  void testBasicMethods(String projectId)
    {
        List<Associate__c> associates;
        
        associates = insertAssociates(projectId);
                        
        updateAssociates(associates);
        
        deleteAssociates(associates);
    }
    
   
    public static List<Associate__c> insertAssociates(String projectId)
     {
        system.debug('Associate: Insert Started');
        if(projectId==null)
            projectId = [SELECT Id from ProjectObject__c LIMIT 1].Id; 
        
        String userId = [SELECT Id from User LIMIT 1].Id; 
        
        List<Associate__c> associates = new List<Associate__c>();
        
        for(Integer i=0;i<3;i++)
        {
            Associate__c associate = new Associate__c();
            associate.Project__c = projectId;
            associate.Rechargeable__c = true;
            associate.Date_Invoiced_Received__c = Date.newInstance(2008,4+i,21);
          
            associate.Associate_Type__c = 'Actor';
            associates.add(associate);
        }
        
        insert associates;
        system.debug('Associate: Insert Completed');
        
        return associates;
     }
     
    
     public static void updateAssociates(List<Associate__c> insertedAssociates)
     {
        system.debug('Associate: Update Started');
        List<Associate__c> associates = new List<Associate__c>();
        
        for(Associate__c insertedAssociate: insertedAssociates)
        {
            Associate__c associate = new Associate__c(id=insertedAssociate.id);
            associate.Date_Invoiced_Received__c = Date.Today();
            associates.add(associate);
        }
    
        update associates;
        Associate_Manager.Associate_AfterUpdateChecks(associates,associates);
        system.debug('Associate: Update Completed');
     }
     
    
     public static void deleteAssociates(List<Associate__c> insertedAssociates)
     {
        system.debug('Associate: Delete Started');
        delete insertedAssociates;
        system.debug('Associate: Delete Completed');
     }
     
}