objects/Bureau_Candidate__c.object
<CustomObject>
    <description>Managed Services module</description>
    <fields>
        <fullName>Bureau_Job__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Managed Services Job</label>
        <referenceTo>Job__c</referenceTo>
        <relationshipLabel>Managed Services Candidates</relationshipLabel>
        <relationshipName>Bureau_Candidates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Managed Services Candidate</label>
    <nameField>
        <displayFormat>BC{000000000}</displayFormat>
        <label>Candidate Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Managed Services Candidates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Job__c.object
<CustomObject>
    <description>The entity used to identify a work request from a client to the Bureau.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Looks up existing SFDC accounts</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>R00N20000000oB15EAE</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Candidate_Username_Prefix__c</fullName>
        <description>This field is meant for specifying a 4-character text that shall be used as a prefix of the usernames generated for the candidates of a Job.</description>
        <inlineHelpText>Specify the username prefix for all candidates of this Job.</inlineHelpText>
        <label>Candidate Username Prefix</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Do_Not_Send_Survey__c</fullName>
        <defaultValue>false</defaultValue>
        <description>It is used to capture if Qualtrics Survey needs to be send or not</description>
        <label>Do Not Send Survey</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <description>This field represents the date on which the Project Job shall end</description>
        <inlineHelpText>This project shall end on this date</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>External_Contact_Other_Email_Address__c</fullName>
        <label>External Contact (Others) Email Address</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>External_Contact_Others__c</fullName>
        <description>This field is meant for entering the External Contact if it does not exist on the system</description>
        <inlineHelpText>If the external contact exists on Salesforce, then select the contact from External Contact field above otherwise enter the Contact name in this field as it is mandatory to enter the External Contact.</inlineHelpText>
        <label>External Contact (Others)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Generic_BS_Field_One__c</fullName>
        <label>Generic Bureau Field One</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Generic_Field_MS_One__c</fullName>
        <label>Generic Field MS One</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Generic_Field_Pipeline_One__c</fullName>
        <label>Generic Field Pipeline One</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>InternalContact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is meant for looking a Salesforce User who is the internal contact for this project.</description>
        <inlineHelpText>Select the Salesforce User who shall be the Internal Contact for this project.</inlineHelpText>
        <label>Internal Contact</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Is_Redirect_To_Task__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is used to redirect user to Task tab when user create a new Job for the first time.</description>
        <label>Is Redirect To Task</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Job_Type__c</fullName>
        <description>To be selected when a Job is added</description>
        <label>Job Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Bureau Task</fullName>
                </value>
                <value>
                    <fullName>Express Bureau</fullName>
                </value>
                <value>
                    <fullName>Offline Express</fullName>
                </value>
                <value>
                    <fullName>Offline Project</fullName>
                </value>
                <value>
                    <fullName>Offline Task</fullName>
                </value>
                <value>
                    <fullName>OLB</fullName>
                    <default>true</default>
                    <label>OLB</label>
                </value>
                <value>
                    <fullName>Online Express</fullName>
                </value>
                <value>
                    <fullName>Online Task</fullName>
                </value>
                <value>
                    <fullName>Premier Bureau</fullName>
                </value>
                <value>
                    <fullName>Project - 360</fullName>
                </value>
                <value>
                    <fullName>Project - 360 Managed Serv</fullName>
                </value>
                <value>
                    <fullName>Project - Managed Serv</fullName>
                </value>
                <value>
                    <fullName>Project - Other</fullName>
                </value>
                <value>
                    <fullName>Offline</fullName>
                </value>
                <value>
                    <fullName>Online</fullName>
                </value>
                <value>
                    <fullName>SHL Online</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MS_Line_of_Business__c</fullName>
        <description>This field stores the MS- Line of business selected by the user</description>
        <label>MS - Line of Business</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>TA - Corporate</fullName>
                </value>
                <value>
                    <fullName>TA - Credentialing</fullName>
                </value>
                <value>
                    <fullName>Talent Management</fullName>
                </value>
                <value>
                    <fullName>Talent Management (Dashboards)</fullName>
                </value>
                <value>
                    <fullName>TA - Vocational (Analytics)</fullName>
                </value>
                <value>
                    <fullName>TA - Vocational (Batch)</fullName>
                </value>
                <value>
                    <fullName>TA - Vocational (School)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Preferred_Language__c</fullName>
        <description>This field is used to capture Preferred Language for Qualtrics Survey</description>
        <label>Preferred Language</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>English</fullName>
                </value>
                <value>
                    <fullName>Chinese</fullName>
                </value>
                <value>
                    <fullName>Danish</fullName>
                </value>
                <value>
                    <fullName>Dutch</fullName>
                </value>
                <value>
                    <fullName>Finnish</fullName>
                </value>
                <value>
                    <fullName>French</fullName>
                </value>
                <value>
                    <fullName>German</fullName>
                </value>
                <value>
                    <fullName>Italian</fullName>
                </value>
                <value>
                    <fullName>Norwegian</fullName>
                </value>
                <value>
                    <fullName>Swedish</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PurchaseOrderNo__c</fullName>
        <label>Purchase Order Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ShortFall_Customer__c</fullName>
        <description>This field represents the Shortfall Parameter for the rater type &apos;Internal/External Customer&apos;</description>
        <inlineHelpText>This field represents the Shortfall Parameter for the rater type &apos;Internal/External Customer&apos;</inlineHelpText>
        <label>Internal/External Customer</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ShortFall_Manager__c</fullName>
        <description>This field represents the Shortfall Parameter for the rater type &apos;Manager/Supervisor&apos;</description>
        <inlineHelpText>Specify the Shortfall parameter for the rater type &apos;Manager/Supervisor&apos;</inlineHelpText>
        <label>Manager/Supervisor</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ShortFall_Other__c</fullName>
        <description>This field represents the Shortfall Parameter for the rater type &apos;Stakeholder/Other/Others&apos;</description>
        <inlineHelpText>Specify the Shortfall parameter for the rater type &apos;Stakeholder/Other/Others&apos;</inlineHelpText>
        <label>Stakeholder/Other</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Shortfall_Client__c</fullName>
        <description>This field represents the Shortfall Parameter for the rater type &apos;Internal/External Client&apos;</description>
        <inlineHelpText>Specify the Shortfall parameter for the rater type &apos;Internal/External Client&apos;</inlineHelpText>
        <label>Internal/External Client</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Shortfall_Peer__c</fullName>
        <description>This field represents the Shortfall Parameter for the rater type &apos;Peer/Colleague&apos;</description>
        <inlineHelpText>Specify the Shortfall parameter for the rater type &apos;Peer/Colleague&apos;</inlineHelpText>
        <label>Peer/Colleague</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Shortfall_Subordinate__c</fullName>
        <description>This field represents the Shortfall Parameter for the rater type &apos;DirectReport/Report/Subordinate&apos;</description>
        <inlineHelpText>Specify the Shortfall parameter for the rater type &apos;Direct Report/Report/Subordinate&apos;</inlineHelpText>
        <label>Direct Report/Report/Subordinate</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>This field represents the date on which the Project Job is started</description>
        <inlineHelpText>This project started on this date</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>System_Used__c</fullName>
        <description>For bureau job record</description>
        <label>System Used</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>TalentCentral+</fullName>
                </value>
                <value>
                    <fullName>MFS</fullName>
                </value>
                <value>
                    <fullName>Insights</fullName>
                </value>
                <value>
                    <fullName>VADC</fullName>
                </value>
                <value>
                    <fullName>Dashboard</fullName>
                </value>
                <value>
                    <fullName>SHL ONLINE</fullName>
                </value>
                <value>
                    <fullName>NSDC-MIS</fullName>
                </value>
                <value>
                    <fullName>TalentCentral</fullName>
                </value>
                <value>
                    <fullName>iAssess</fullName>
                </value>
                <value>
                    <fullName>OFFLINE</fullName>
                </value>
                <value>
                    <fullName>DSPS</fullName>
                </value>
                <value>
                    <fullName>Client System</fullName>
                </value>
                <value>
                    <fullName>WPS</fullName>
                </value>
                <value>
                    <fullName>Manufacturing Toolbox - MTB</fullName>
                </value>
                <value>
                    <fullName>Scansys</fullName>
                </value>
                <value>
                    <fullName>DM Desktop Profiler</fullName>
                </value>
                <value>
                    <fullName>Online Competency Profiler</fullName>
                </value>
                <value>
                    <fullName>JCF Creator</fullName>
                </value>
                <value>
                    <fullName>Career Guidance</fullName>
                </value>
                <value>
                    <fullName>OnDemand</fullName>
                </value>
                <value>
                    <fullName>S2P System</fullName>
                </value>
                <value>
                    <fullName>Tableau Dashboard</fullName>
                </value>
                <value>
                    <fullName>Automation</fullName>
                </value>
                <value>
                    <fullName>IGB</fullName>
                </value>
                <value>
                    <fullName>OA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Job</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Job Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <recordTypes>
        <fullName>Managed_Service_Commenced</fullName>
        <active>true</active>
        <label>Managed Service Commenced</label>
    </recordTypes>
    <recordTypes>
        <fullName>Managed_Service_Pipeline</fullName>
        <active>true</active>
        <label>Managed Service Pipeline</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/RevertIsExportedOnCandidate_Test.cls
@isTest(seeAllData = true)
public class RevertIsExportedOnCandidate_Test {
    
     @isTest
    public static void updateCandidatesTest(){
        Test.startTest();
        System.Test.setMock(HttpCalloutMock.class, new CandidateUploadControllerMock());
        Account accountRecord = TestDataUtility.getAccount();
        INSERT accountRecord;
        
        Contact contactRecord = TestDataUtility.getContact(accountRecord.Id);
        INSERT contactRecord;
        Id RecordTypeIdJob1 = Schema.SObjectType.Job__c.getRecordTypeInfosByDeveloperName().get('Managed_Service_Pipeline').getRecordTypeId();
        Id RecordTypeIdJob2 = Schema.SObjectType.Job__c.getRecordTypeInfosByDeveloperName().get('Managed_Service_Commenced').getRecordTypeId();
        
        Job__c job = new Job__c();
        job.Account__c = accountRecord.Id;
        job.MS_Line_of_Business__c = 'Talent Management';
        job.Job_Type__c = 'Project - 360';
        job.Start_Date__c = System.today();
        job.End_Date__c = System.today().addDays(30);
        job.InternalContact__c = UserInfo.getUserId();
        job.External_Contact_Others__c = 'External Contact';
        job.External_Contact_Other_Email_Address__c='test@test.com';
        job.Candidate_Username_Prefix__c = 'CAND';
        job.ShortFall_Manager__c = 1;
        job.Shortfall_Peer__c = 2;
        job.Shortfall_Subordinate__c = 3;
        job.ShortFall_Customer__c = 2;
        job.Shortfall_Client__c = 2;
        job.ShortFall_Other__c = 2;
        job.PurchaseOrderNo__c='rtertr';
        job.Generic_BS_Field_One__c='Bureau Service';
        job.Generic_Field_MS_One__c='Managed Service';
        job.Generic_Field_Pipeline_One__c = 'MS Pipeline';
        job.Is_Redirect_To_Task__c=true;
        job.System_Used__c = 'MFS;SODA / MFS;SODA / S2P;SODA / PD360;SHL ONLINE;';
        job.System_Used__c ='SHL ONLINE';
        job.RecordTypeId = RecordTypeIdJob2;
        job.Do_Not_Send_Survey__c = True;
        job.Preferred_Language__c = 'English';
        insert job;
        
        Bureau_Candidate__c candidate = new Bureau_Candidate__c();
        candidate.First_Name__c = 'Test';
        candidate.Last_Name__c = 'Candidate 1';
        candidate.Bureau_Job__c = job.Id;
        candidate.Email__c = 'testemail12345@test.com';
        candidate.Reports_Status__c = 'Unsent';
        candidate.isExported__c=true;
        
        RevertIsExportedOnCandidate rvrtExport=new RevertIsExportedOnCandidate(job);
        Database.executeBatch(rvrtExport);
        Test.stopTest();
    }

}