objects/Bureau_Candidate__c.object
<CustomObject>
    <description>Managed Services module</description>
    <fields>
        <fullName>Bureau_Job__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Managed Services Job</label>
        <referenceTo>Job__c</referenceTo>
        <relationshipLabel>Managed Services Candidates</relationshipLabel>
        <relationshipName>Bureau_Candidates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Full_Name__c</fullName>
        <formula>First_Name__c + &quot; &quot; +  Last_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Full Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reports_Status__c</fullName>
        <description>This field represents the status of the Reports for this Participant</description>
        <inlineHelpText>Specify the status of the Reports for this Participant</inlineHelpText>
        <label>Reports Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Unsent</fullName>
                    <default>true</default>
                    <label>Unsent</label>
                </value>
                <value>
                    <fullName>Ready to be Generated</fullName>
                </value>
                <value>
                    <fullName>Generated</fullName>
                </value>
                <value>
                    <fullName>Partially Sent</fullName>
                </value>
                <value>
                    <fullName>Sent</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>IF( Total_Ratings__c ==  Ratings_Completed__c ,&quot;Completed&quot;,IF(Ratings_Completed__c&gt;0 ||  Ratings_In_Progress__c&gt;0,&quot;In Progress&quot;, &quot;Not Started&quot;))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <label>Managed Services Candidate</label>
    <nameField>
        <displayFormat>BC{000000000}</displayFormat>
        <label>Candidate Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Managed Services Candidates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/objects/Bureau_Rating__c.object
<CustomObject>
    <description>This object represents a self rating or a respondent rating for a Bureau Project Job.</description>
    <fields>
        <fullName>Bureau_Job__c</fullName>
        <formula>CASESAFEID(Participant__r.Bureau_Job__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Managed Services_Job</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Deadline__c</fullName>
        <label>Deadline</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>File_Name__c</fullName>
        <label>File Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Insights_Status__c</fullName>
        <label>Insights Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Recalled</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MFS_Report_Sent__c</fullName>
        <inlineHelpText>To capture the status of MFS platform report sent to customer.</inlineHelpText>
        <label>MFS Report Sent</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Sent</fullName>
                </value>
                <value>
                    <fullName>Sent</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MFS_Status__c</fullName>
        <label>MFS Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Ready to Submit</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Overall_Status__c</fullName>
        <formula>if(TEXT(MFS_Status__c) = null &amp;&amp; TEXT(TC_Status__c)= null,null,
if(TEXT(MFS_Status__c)!= null &amp;&amp; TEXT(TC_Status__c)= null,TEXT(MFS_Status__c),
If(TEXT(MFS_Status__c)= null &amp;&amp; TEXT(TC_Status__c)!= null,TEXT(TC_Status__c),
if(TEXT(MFS_Status__c)= &apos;Not Started&apos; &amp;&amp; TEXT(TC_Status__c)= &apos;Not Started&apos;,&apos;Not Started&apos;,
if(TEXT(MFS_Status__c)= &apos;Not Started&apos; &amp;&amp; TEXT(TC_Status__c)= &apos;In Progress&apos;,&apos;In Progress&apos;,
if(TEXT(MFS_Status__c)= &apos;Not Started&apos; &amp;&amp; TEXT(TC_Status__c)= &apos;Completed&apos;,&apos;In Progress&apos;,
if(TEXT(MFS_Status__c)= &apos;In Progress&apos; &amp;&amp; TEXT(TC_Status__c)= &apos;Not Started&apos;,&apos;In Progress&apos;,
if(TEXT(MFS_Status__c)= &apos;In Progress&apos; &amp;&amp; TEXT(TC_Status__c)= &apos;In Progress&apos;,&apos;In Progress&apos;,
if(TEXT(MFS_Status__c)= &apos;In Progress&apos; &amp;&amp; TEXT(TC_Status__c)= &apos;Completed&apos;,&apos;In Progress&apos;,
if(TEXT(MFS_Status__c)= &apos;Ready to Submit&apos; &amp;&amp; TEXT(TC_Status__c)= &apos;Not Started&apos;,&apos;In Progress&apos;,
if(TEXT(MFS_Status__c)= &apos;Ready to Submit&apos; &amp;&amp; TEXT(TC_Status__c)= &apos;In Progress&apos;,&apos;In Progress&apos;,
if(TEXT(MFS_Status__c)= &apos;Ready to Submit&apos; &amp;&amp; TEXT(TC_Status__c)= &apos;Completed&apos;,&apos;Ready to Submit&apos;,
if(TEXT(MFS_Status__c)= &apos;Completed&apos; &amp;&amp; TEXT(TC_Status__c)= &apos;Not Started&apos;,&apos;In Progress&apos;,
if(TEXT(MFS_Status__c)= &apos;Completed&apos; &amp;&amp; TEXT(TC_Status__c)= &apos;In Progress&apos;,&apos;In Progress&apos;,
if(TEXT(MFS_Status__c)= &apos;Completed&apos; &amp;&amp; TEXT(TC_Status__c)= &apos;Completed&apos;,&apos;Completed&apos;,null))))))))))))))
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Overall Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Participant__c</fullName>
        <description>This field represents the Bureau Candidate who shall be acting as a participant and shall be rated by the Respondent.</description>
        <inlineHelpText>Specify the Bureau Candidate to be rated</inlineHelpText>
        <label>Participant</label>
        <referenceTo>Bureau_Candidate__c</referenceTo>
        <relationshipName>Bureau_Ratings_As_Participant</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Rater_String__c</fullName>
        <label>Rater String</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Rater_Type__c</fullName>
        <label>Rater Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Self</fullName>
                </value>
                <value>
                    <fullName>Manager</fullName>
                </value>
                <value>
                    <fullName>Colleagues</fullName>
                </value>
                <value>
                    <fullName>Others</fullName>
                </value>
                <value>
                    <fullName>Direct Reports</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Reminder__c</fullName>
        <formula>IF(
    TEXT(Rater_Type__c) = &apos;Self&apos;,
    IF(
        OR(
            AND(ISBLANK(TEXT(MFS_Report_Sent__c)), TEXT(TC_Report_Sent__c) = &apos;Sent&apos;),
            AND(TEXT(MFS_Report_Sent__c) = &apos;Sent&apos;, TEXT(TC_Report_Sent__c) = &apos;Sent&apos;),
            Overall_Status__c = &apos;Completed&apos;
        ),
        &apos;Not Eligible&apos;,
        &apos;Eligible&apos;
    ),
    Reminder_1__c
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Reminder</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Report_Ready__c</fullName>
        <label>Report Ready</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Ready</fullName>
                    <default>true</default>
                    <label>Not Ready</label>
                </value>
                <value>
                    <fullName>Can be Generated</fullName>
                </value>
                <value>
                    <fullName>Can not be generated</fullName>
                </value>
                <value>
                    <fullName>100% Completed</fullName>
                </value>
                <value>
                    <fullName>Data Insufficient</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Report_Sent__c</fullName>
        <label>Report Sent</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reports_Status__c</fullName>
        <description>This field represents the status of the Reports</description>
        <inlineHelpText>Specify the status of the Reports</inlineHelpText>
        <label>Reports Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Unsent</fullName>
                    <default>true</default>
                    <label>Unsent</label>
                </value>
                <value>
                    <fullName>Ready to be Generated</fullName>
                </value>
                <value>
                    <fullName>Generated</fullName>
                </value>
                <value>
                    <fullName>Partially Sent</fullName>
                </value>
                <value>
                    <fullName>Sent</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Respondent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field represents the Bureau Candidate who shall acting as a respondent and shall be rating the Participant.</description>
        <inlineHelpText>Specify the Candidate who shall be rating the Participant</inlineHelpText>
        <label>Respondent</label>
        <referenceTo>Bureau_Candidate__c</referenceTo>
        <relationshipName>Bureau_Ratings_As_Respondent</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Single_Use_Link__c</fullName>
        <label>Single Use Link</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>This field represents the Status of the Rating</description>
        <formula>IF(Total_Instruments__c== Instruments_Completed__c,&quot;Completed&quot;,IF(Instruments_Completed__c&gt;0 || Instruments_In_Progress__c&gt;0,&quot;In Progress&quot;, &quot;Not Started&quot;))</formula>
        <inlineHelpText>This is the current status of the Rating</inlineHelpText>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TC_Report_Sent__c</fullName>
        <inlineHelpText>To capture the status of TC platform report sent to customer.</inlineHelpText>
        <label>TC Report Sent</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Sent</fullName>
                </value>
                <value>
                    <fullName>Sent</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TC_Status__c</fullName>
        <label>TC Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Recalled</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Ready to Submit</fullName>
                    <isActive>false</isActive>
                    <label>Ready to Submit</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Managed Services Rating</label>
    <nameField>
        <displayFormat>BR{000000000}</displayFormat>
        <label>Rating Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Managed Services Ratings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Work_Request__c.object
<CustomObject>
    <description>Module to store work request generated by managed services team and submitted by client back to managed services team</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Work Request</label>
    <nameField>
        <displayFormat>WR-{0000}</displayFormat>
        <label>Work Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CandidateRatingManager.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 12-09-2025
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
public class CandidateRatingManager {

    public CandidateRatingManager() {

    }
    
    public class CandidateAndRatingData{
        @AuraEnabled public list<Bureau_Rating__c> ratingData;
        @AuraEnabled public List<Bureau_Candidate__c> candidateData;
    }

    @AuraEnabled
    public static CandidateAndRatingData getRatingDataForReportView(String soqlQueryList, String soqlQueryCandidateList,  String jobId, Integer offSetValue, List<Map<String, String>> filters){
    //public static CandidateAndRatingData getRatingDataForReportView(String soqlQueryList, String soqlQueryCandidateList,  String jobId, Integer offSetValue, String filterValue){
        list<Bureau_Rating__c> ratingList = new list<Bureau_Rating__c>();
        List<Bureau_Candidate__c> candidateList = new List<Bureau_Candidate__c>();
        list<Id> candidateIdList = new list<Id>();
        CandidateAndRatingData wrapper = new CandidateAndRatingData();
        String soqlQuery;
        String baseQuery = 'Select ' + soqlQueryList + ' FROM Bureau_Rating__c WHERE Participant__r.Bureau_Job__c =:jobId AND ';
        system.debug('--->offSetValue'+offSetValue);
        system.debug('--->baseQuery '+baseQuery);
        //commented poc search function
        List<String> conditions = new List<String>();
		System.debug('Filters from LWC '+filters);
        // Generate WHERE clause based on filters
        if(filters!=null){
           for (Map<String, String> filter : filters) {
            String field = filter.get('key');
            String value = filter.get('value');
               if(field=='participantName'){
                   field = 'Participant__r.Full_Name__c';
               }
               else if(field=='participantEmail'){
                   field = 'Participant__r.Email__c';
               }
               else if(field=='respondentName'){
                   field = 'Respondent__r.Full_Name__c';
               }
               else if(field=='respondentEmail'){
                   field = 'Respondent__r.Email__c';
               }
            Schema.DescribeFieldResult fieldDescribe = null;
               if(!field.contains('.')){
                   fieldDescribe = Schema.getGlobalDescribe().get('Bureau_Rating__c').getDescribe().fields.getMap().get(field).getDescribe();
               }
                
            if (fieldDescribe!=null && fieldDescribe.getType() == Schema.DisplayType.Picklist) {
                System.debug('Inside If');
                conditions.add(field + ' = \'' + value + '\'');
            } 
               else if(field=='Deadline__c'){
                System.debug('Inside Else If');
                conditions.add(field + ' = '+ value +' '); 
               }
               else {
                conditions.add(field + ' LIKE \'%' + value + '%\'');
            }
        }
        }
       

        // Combine conditions using AND
        if (conditions.isEmpty()) {
            soqlQuery = 'Select ' + soqlQueryList + ' FROM Bureau_Rating__c WHERE Participant__r.Bureau_Job__c =:jobId ORDER BY Participant__r.Full_Name__c LIMIT 200 OFFSET: offSetValue'; // No filters
        } else {
            soqlQuery = baseQuery + String.join(conditions, ' AND ') +  'ORDER BY Participant__r.Full_Name__c LIMIT 200 OFFSET: offSetValue';
        }
        //old search function
       /* if(String.isBlank(filterValue)){
                   soqlQuery = 'Select ' + soqlQueryList + ' FROM Bureau_Rating__c WHERE Participant__r.Bureau_Job__c =:jobId ORDER BY Participant__r.Full_Name__c LIMIT 200 OFFSET: offSetValue';
        }
        else{
            String namePattern = '%' + String.escapeSingleQuotes(filterValue) + '%';
                  soqlQuery = 'Select ' + soqlQueryList + ' FROM Bureau_Rating__c WHERE Participant__r.Bureau_Job__c =:jobId AND (Participant__r.Full_Name__c like: namePattern OR Respondent__r.Full_Name__c like: namePattern OR Rater_Type__c like: namePattern OR Respondent__r.Email__c like: namePattern OR MFS_Status__c like: namePattern OR TC_Status__c like: namePattern OR Overall_Status__c like: namePattern OR Report_Ready__c like: namePattern OR Report_Sent__c like: namePattern ) ORDER BY Participant__r.Full_Name__c LIMIT 200 OFFSET: offSetValue';
        }*/

        system.debug('--->soqlQuery'+soqlQuery);
        
        ratingList = database.query(soqlQuery);
        
        for(Bureau_Rating__c r : ratingList){
            candidateIdList.add(r.Respondent__c);
        }
        
        String soqlQueryCandidate = 'Select ' + soqlQueryCandidateList + ' FROM Bureau_Candidate__c WHERE Id IN :candidateIdList ORDER BY Full_Name__c';
        candidateList = database.query(soqlQueryCandidate);
        wrapper.ratingData = ratingList;
        wrapper.candidateData = candidateList;
        return wrapper;
    }
    
    @AuraEnabled
    public static CandidateAndRatingData getRatingDataWrf(String soqlQueryList, String jobId, Integer offSetValue, String filterValue, String TCstatus, String MFSstatus, String ReminderVal){
        list<Bureau_Rating__c> ratingList = new list<Bureau_Rating__c>();
        List<Bureau_Candidate__c> candidateList = new List<Bureau_Candidate__c>();
        list<Id> candidateIdList = new list<Id>();
        CandidateAndRatingData wrapper = new CandidateAndRatingData();
        if(String.isBlank(filterValue) && String.isBlank(TCstatus) && String.isBlank(MFSstatus) && String.isBlank(ReminderVal)){
            system.debug('--->All filters are blank<---'+String.isBlank(filterValue));
            ratingList = [SELECT Id,Name,Participant__c,Participant__r.Name,Participant__r.Full_Name__c,Participant__r.Email__c,
                      Respondent__c,Respondent__r.Name,Respondent__r.Full_Name__c,Respondent__r.Email__c,Rater_Type__c,Status__c,Participant__r.Reports_Status__c,
                      MFS_Status__c,TC_Status__c,Overall_Status__c,Rater_String__c,Reminder__c,Report_Ready__c,Report_Sent__c,Deadline__c,Comments__c,File_Name__c,
                      Single_Use_Link__c, MFS_Report_Sent__c, TC_Report_Sent__c, Insights_Status__c, VADC_Status__c,
                      Participant__r.Work_Request__c, Participant__r.Work_Request__r.Name,
                          EmailType__c, Email_File_Name__c, Sharepoint_File_Path__c // Added for SSE-28492
         				FROM Bureau_Rating__c WHERE Participant__r.Bureau_Job__c = :jobId ORDER BY Participant__r.Full_Name__c LIMIT 200 OFFSET: offSetValue];
            
        }
        else if(String.isBlank(filterValue) == false && String.isBlank(TCstatus) == false && String.isBlank(MFSstatus) == false && String.isBlank(ReminderVal) == false)
        {
            system.debug('--->All filters are applied<---'+String.isBlank(TCstatus));
            filterValue = '%'+filterValue+'%';
            ratingList = [SELECT Id,Name,Participant__c,Participant__r.Name,Participant__r.Full_Name__c,Participant__r.Email__c,
                      Respondent__c,Respondent__r.Name,Respondent__r.Full_Name__c,Respondent__r.Email__c,Rater_Type__c,Status__c,Participant__r.Reports_Status__c,
                      MFS_Status__c,TC_Status__c,Overall_Status__c,Rater_String__c,Reminder__c,Report_Ready__c,Report_Sent__c,Deadline__c,Comments__c,File_Name__c,Single_Use_Link__c, MFS_Report_Sent__c, TC_Report_Sent__c, Insights_Status__c, VADC_Status__c,
                      Participant__r.Work_Request__c, Participant__r.Work_Request__r.Name,
                          EmailType__c, Email_File_Name__c, Sharepoint_File_Path__c // Added for SSE-28492
         				FROM Bureau_Rating__c WHERE (Participant__r.Bureau_Job__c = :jobId) AND (Participant__r.Full_Name__c like: filterValue OR Respondent__r.Full_Name__c like: filterValue OR Rater_Type__c like: filterValue OR Respondent__r.Email__c like: filterValue OR MFS_Status__c like: filterValue OR TC_Status__c like: filterValue OR Overall_Status__c like: filterValue OR Reminder__c =: filterValue) AND (TC_Status__c =: TCstatus) AND (MFS_Status__c =: MFSstatus) AND(Reminder__c =:ReminderVal) ORDER BY Participant__c LIMIT 200 OFFSET: offSetValue];
        }
        else if(String.isBlank(TCstatus) && String.isBlank(filterValue) == false && String.isBlank(MFSstatus) && String.isBlank(ReminderVal)){
            system.debug('--->Only search string<---'+String.isBlank(filterValue));
            filterValue = '%'+filterValue+'%';
            ratingList = [SELECT Id,Name,Participant__c,Participant__r.Name,Participant__r.Full_Name__c,Participant__r.Email__c,
                      Respondent__c,Respondent__r.Name,Respondent__r.Full_Name__c,Respondent__r.Email__c,Rater_Type__c,Status__c,Participant__r.Reports_Status__c,
                      MFS_Status__c,TC_Status__c,Overall_Status__c,Rater_String__c,Reminder__c,Report_Ready__c,Report_Sent__c,Deadline__c,Comments__c,File_Name__c,Single_Use_Link__c, MFS_Report_Sent__c, TC_Report_Sent__c, Insights_Status__c, VADC_Status__c,
                      Participant__r.Work_Request__c, Participant__r.Work_Request__r.Name,
                          EmailType__c, Email_File_Name__c, Sharepoint_File_Path__c // Added for SSE-28492
         				FROM Bureau_Rating__c WHERE (Participant__r.Bureau_Job__c = :jobId) AND (Participant__r.Full_Name__c like: filterValue OR Respondent__r.Full_Name__c like: filterValue OR Rater_Type__c like: filterValue OR Respondent__r.Email__c like: filterValue OR MFS_Status__c like: filterValue OR TC_Status__c like: filterValue OR Overall_Status__c like: filterValue OR Reminder__c =: filterValue OR Participant__r.Work_Request__r.Name LIKE:filterValue) ORDER BY Participant__c LIMIT 200 OFFSET: offSetValue];
        }
		else if(String.isBlank(TCstatus) == false && String.isBlank(filterValue) && String.isBlank(MFSstatus) && String.isBlank(ReminderVal)){
			system.debug('--->Only TC status applied<---'+String.isBlank(TCstatus));
            filterValue = '%'+filterValue+'%';
            ratingList = [SELECT Id,Name,Participant__c,Participant__r.Name,Participant__r.Full_Name__c,Participant__r.Email__c,
                      Respondent__c,Respondent__r.Name,Respondent__r.Full_Name__c,Respondent__r.Email__c,Rater_Type__c,Status__c,Participant__r.Reports_Status__c,
                      MFS_Status__c,TC_Status__c,Overall_Status__c,Rater_String__c,Reminder__c,Report_Ready__c,Report_Sent__c,Deadline__c,Comments__c,File_Name__c,Single_Use_Link__c, MFS_Report_Sent__c, TC_Report_Sent__c, Insights_Status__c, VADC_Status__c,
                      Participant__r.Work_Request__c, Participant__r.Work_Request__r.Name,
                          EmailType__c, Email_File_Name__c, Sharepoint_File_Path__c // Added for SSE-28492
         				FROM Bureau_Rating__c WHERE (Participant__r.Bureau_Job__c = :jobId) AND (TC_Status__c =: TCstatus) ORDER BY Participant__c LIMIT 200 OFFSET: offSetValue];
        
		}
		else if(String.isBlank(TCstatus) && String.isBlank(filterValue) && String.isBlank(MFSstatus) == false && String.isBlank(ReminderVal)){
			system.debug('--->Only MFS status applied<---'+String.isBlank(TCstatus));
            filterValue = '%'+filterValue+'%';
            ratingList = [SELECT Id,Name,Participant__c,Participant__r.Name,Participant__r.Full_Name__c,Participant__r.Email__c,
                      Respondent__c,Respondent__r.Name,Respondent__r.Full_Name__c,Respondent__r.Email__c,Rater_Type__c,Status__c,Participant__r.Reports_Status__c,
                      MFS_Status__c,TC_Status__c,Overall_Status__c,Rater_String__c,Reminder__c,Report_Ready__c,Report_Sent__c,Deadline__c,Comments__c,File_Name__c,Single_Use_Link__c, MFS_Report_Sent__c, TC_Report_Sent__c, Insights_Status__c, VADC_Status__c,
                      Participant__r.Work_Request__c, Participant__r.Work_Request__r.Name,
                          EmailType__c, Email_File_Name__c, Sharepoint_File_Path__c // Added for SSE-28492
         				FROM Bureau_Rating__c WHERE (Participant__r.Bureau_Job__c = :jobId) AND (MFS_Status__c =: MFSstatus) ORDER BY Participant__c LIMIT 200 OFFSET: offSetValue];
        
		}
        else if(String.isBlank(TCstatus) && String.isBlank(filterValue) && String.isBlank(MFSstatus) && String.isBlank(ReminderVal) == false){
			system.debug('--->Only Reminder applied<---'+String.isBlank(TCstatus));
            filterValue = '%'+filterValue+'%';
            ratingList = [SELECT Id,Name,Participant__c,Participant__r.Name,Participant__r.Full_Name__c,Participant__r.Email__c,
                      Respondent__c,Respondent__r.Name,Respondent__r.Full_Name__c,Respondent__r.Email__c,Rater_Type__c,Status__c,Participant__r.Reports_Status__c,
                      MFS_Status__c,TC_Status__c,Overall_Status__c,Rater_String__c,Reminder__c,Report_Ready__c,Report_Sent__c,Deadline__c,Comments__c,File_Name__c,Single_Use_Link__c, MFS_Report_Sent__c, TC_Report_Sent__c , Insights_Status__c, VADC_Status__c,
                      Participant__r.Work_Request__c, Participant__r.Work_Request__r.Name,
                          EmailType__c, Email_File_Name__c, Sharepoint_File_Path__c // Added for SSE-28492
         				FROM Bureau_Rating__c WHERE (Participant__r.Bureau_Job__c = :jobId) AND (Reminder__c =: ReminderVal) ORDER BY Participant__c LIMIT 200 OFFSET: offSetValue];
        
		}
		else if(String.isBlank(TCstatus)== false && String.isBlank(filterValue) && String.isBlank(MFSstatus) == false && String.isBlank(ReminderVal)){
			system.debug('--->Only MFS and TC status applied<---'+String.isBlank(TCstatus));
            filterValue = '%'+filterValue+'%';
            ratingList = [SELECT Id,Name,Participant__c,Participant__r.Name,Participant__r.Full_Name__c,Participant__r.Email__c,
                      Respondent__c,Respondent__r.Name,Respondent__r.Full_Name__c,Respondent__r.Email__c,Rater_Type__c,Status__c,Participant__r.Reports_Status__c,
                      MFS_Status__c,TC_Status__c,Overall_Status__c,Rater_String__c,Reminder__c,Report_Ready__c,Report_Sent__c,Deadline__c,Comments__c,File_Name__c,Single_Use_Link__c, MFS_Report_Sent__c, TC_Report_Sent__c, Insights_Status__c, VADC_Status__c,
                      Participant__r.Work_Request__c, Participant__r.Work_Request__r.Name,
                          EmailType__c, Email_File_Name__c, Sharepoint_File_Path__c // Added for SSE-28492
         				FROM Bureau_Rating__c WHERE (Participant__r.Bureau_Job__c = :jobId) AND (MFS_Status__c =: MFSstatus) AND (TC_Status__c =: TCstatus) ORDER BY Participant__c LIMIT 200 OFFSET: offSetValue];
        
		}
		else if(String.isBlank(TCstatus) == false && String.isBlank(filterValue) == false && String.isBlank(MFSstatus) && String.isBlank(ReminderVal)){
            system.debug('--->TC & Search string<---'+String.isBlank(filterValue));
            filterValue = '%'+filterValue+'%';
            ratingList = [SELECT Id,Name,Participant__c,Participant__r.Name,Participant__r.Full_Name__c,Participant__r.Email__c,
                      Respondent__c,Respondent__r.Name,Respondent__r.Full_Name__c,Respondent__r.Email__c,Rater_Type__c,Status__c,Participant__r.Reports_Status__c,
                      MFS_Status__c,TC_Status__c,Overall_Status__c,Rater_String__c,Reminder__c,Report_Ready__c,Report_Sent__c,Deadline__c,Comments__c,File_Name__c,Single_Use_Link__c, MFS_Report_Sent__c, TC_Report_Sent__c, Insights_Status__c, VADC_Status__c,
                      Participant__r.Work_Request__c, Participant__r.Work_Request__r.Name,
                          EmailType__c, Email_File_Name__c, Sharepoint_File_Path__c // Added for SSE-28492
         				FROM Bureau_Rating__c WHERE (Participant__r.Bureau_Job__c = :jobId) AND (Participant__r.Full_Name__c like: filterValue OR Respondent__r.Full_Name__c like: filterValue OR Rater_Type__c like: filterValue OR Respondent__r.Email__c like: filterValue OR MFS_Status__c like: filterValue OR TC_Status__c like: filterValue OR Overall_Status__c like: filterValue OR Reminder__c =: filterValue) AND (TC_Status__c =: TCstatus) ORDER BY Participant__c LIMIT 200 OFFSET: offSetValue];
        }
		else if(String.isBlank(TCstatus)  && String.isBlank(filterValue) == false && String.isBlank(MFSstatus) == false && String.isBlank(ReminderVal)){
            system.debug('--->MFS & Search string<---'+String.isBlank(filterValue));
            filterValue = '%'+filterValue+'%';
            ratingList = [SELECT Id,Name,Participant__c,Participant__r.Name,Participant__r.Full_Name__c,Participant__r.Email__c,
                      Respondent__c,Respondent__r.Name,Respondent__r.Full_Name__c,Respondent__r.Email__c,Rater_Type__c,Status__c,Participant__r.Reports_Status__c,
                      MFS_Status__c,TC_Status__c,Overall_Status__c,Rater_String__c,Reminder__c,Report_Ready__c,Report_Sent__c,Deadline__c,Comments__c,File_Name__c,Single_Use_Link__c, MFS_Report_Sent__c, TC_Report_Sent__c, Insights_Status__c, VADC_Status__c,
                      Participant__r.Work_Request__c, Participant__r.Work_Request__r.Name,
                          EmailType__c, Email_File_Name__c, Sharepoint_File_Path__c // Added for SSE-28492
         				FROM Bureau_Rating__c WHERE (Participant__r.Bureau_Job__c = :jobId) AND (Participant__r.Full_Name__c like: filterValue OR Respondent__r.Full_Name__c like: filterValue OR Rater_Type__c like: filterValue OR Respondent__r.Email__c like: filterValue OR MFS_Status__c like: filterValue OR TC_Status__c like: filterValue OR Overall_Status__c like: filterValue OR Reminder__c =: filterValue) AND (MFS_Status__c =: MFSstatus) ORDER BY Participant__c LIMIT 200 OFFSET: offSetValue];
        }
        else if(String.isBlank(TCstatus)  && String.isBlank(filterValue) == false && String.isBlank(MFSstatus) && String.isBlank(ReminderVal)  == false){
            system.debug('--->Reminder & Search string<---'+String.isBlank(filterValue));
            filterValue = '%'+filterValue+'%';
            ratingList = [SELECT Id,Name,Participant__c,Participant__r.Name,Participant__r.Full_Name__c,Participant__r.Email__c,
                      Respondent__c,Respondent__r.Name,Respondent__r.Full_Name__c,Respondent__r.Email__c,Rater_Type__c,Status__c,Participant__r.Reports_Status__c,
                      MFS_Status__c,TC_Status__c,Overall_Status__c,Rater_String__c,Reminder__c,Report_Ready__c,Report_Sent__c,Deadline__c,Comments__c,File_Name__c,Single_Use_Link__c, MFS_Report_Sent__c, TC_Report_Sent__c, Insights_Status__c, VADC_Status__c,
                      Participant__r.Work_Request__c, Participant__r.Work_Request__r.Name,
                          EmailType__c, Email_File_Name__c, Sharepoint_File_Path__c // Added for SSE-28492
         				FROM Bureau_Rating__c WHERE (Participant__r.Bureau_Job__c = :jobId) AND (Participant__r.Full_Name__c like: filterValue OR Respondent__r.Full_Name__c like: filterValue OR Rater_Type__c like: filterValue OR Respondent__r.Email__c like: filterValue OR MFS_Status__c like: filterValue OR TC_Status__c like: filterValue OR Overall_Status__c like: filterValue OR Reminder__c =: filterValue) AND (Reminder__c =: ReminderVal) ORDER BY Participant__c LIMIT 200 OFFSET: offSetValue];
        }
        else if(String.isBlank(TCstatus)== false && String.isBlank(filterValue) && String.isBlank(MFSstatus) && String.isBlank(ReminderVal)  == false){
			system.debug('--->Only Reminder and TC status applied<---'+String.isBlank(TCstatus));
            filterValue = '%'+filterValue+'%';
            ratingList = [SELECT Id,Name,Participant__c,Participant__r.Name,Participant__r.Full_Name__c,Participant__r.Email__c,
                      Respondent__c,Respondent__r.Name,Respondent__r.Full_Name__c,Respondent__r.Email__c,Rater_Type__c,Status__c,Participant__r.Reports_Status__c,
                      MFS_Status__c,TC_Status__c,Overall_Status__c,Rater_String__c,Reminder__c,Report_Ready__c,Report_Sent__c,Deadline__c,Comments__c,File_Name__c,Single_Use_Link__c, MFS_Report_Sent__c, TC_Report_Sent__c, Insights_Status__c, VADC_Status__c,
                      Participant__r.Work_Request__c, Participant__r.Work_Request__r.Name,
                          EmailType__c, Email_File_Name__c, Sharepoint_File_Path__c // Added for SSE-28492
         				FROM Bureau_Rating__c WHERE (Participant__r.Bureau_Job__c = :jobId) AND (Reminder__c =: ReminderVal) AND (TC_Status__c =: TCstatus) ORDER BY Participant__c LIMIT 200 OFFSET: offSetValue];
        
		}
        else if(String.isBlank(TCstatus)&& String.isBlank(filterValue) && String.isBlank(MFSstatus) == false  && String.isBlank(ReminderVal)  == false){
			system.debug('--->Only Reminder and MFS status applied<---'+String.isBlank(TCstatus));
            filterValue = '%'+filterValue+'%';
            ratingList = [SELECT Id,Name,Participant__c,Participant__r.Name,Participant__r.Full_Name__c,Participant__r.Email__c,
                      Respondent__c,Respondent__r.Name,Respondent__r.Full_Name__c,Respondent__r.Email__c,Rater_Type__c,Status__c,Participant__r.Reports_Status__c,
                      MFS_Status__c,TC_Status__c,Overall_Status__c,Rater_String__c,Reminder__c,Report_Ready__c,Report_Sent__c,Deadline__c,Comments__c,File_Name__c,Single_Use_Link__c, MFS_Report_Sent__c, TC_Report_Sent__c, Insights_Status__c, VADC_Status__c,
                      Participant__r.Work_Request__c, Participant__r.Work_Request__r.Name,
                          EmailType__c, Email_File_Name__c, Sharepoint_File_Path__c // Added for SSE-28492
         				FROM Bureau_Rating__c WHERE (Participant__r.Bureau_Job__c = :jobId) AND (Reminder__c =: ReminderVal) AND (MFS_Status__c =: MFSstatus) ORDER BY Participant__c LIMIT 200 OFFSET: offSetValue];
        
		}
        else if(String.isBlank(TCstatus) == false && String.isBlank(filterValue) && String.isBlank(MFSstatus) == false  && String.isBlank(ReminderVal)  == false){
			system.debug('--->Only Reminder, TC and MFS status applied<---'+String.isBlank(TCstatus));
            filterValue = '%'+filterValue+'%';
            ratingList = [SELECT Id,Name,Participant__c,Participant__r.Name,Participant__r.Full_Name__c,Participant__r.Email__c,
                      Respondent__c,Respondent__r.Name,Respondent__r.Full_Name__c,Respondent__r.Email__c,Rater_Type__c,Status__c,Participant__r.Reports_Status__c,
                      MFS_Status__c,TC_Status__c,Overall_Status__c,Rater_String__c,Reminder__c,Report_Ready__c,Report_Sent__c,Deadline__c,Comments__c,File_Name__c,Single_Use_Link__c, MFS_Report_Sent__c, TC_Report_Sent__c, Insights_Status__c, VADC_Status__c,
                      Participant__r.Work_Request__c, Participant__r.Work_Request__r.Name,
                          EmailType__c, Email_File_Name__c, Sharepoint_File_Path__c // Added for SSE-28492
         				FROM Bureau_Rating__c WHERE (Participant__r.Bureau_Job__c = :jobId) AND (Reminder__c =: ReminderVal) AND (MFS_Status__c =: MFSstatus) AND (TC_Status__c =: TCstatus) ORDER BY Participant__c LIMIT 200 OFFSET: offSetValue];
        
		}
        else if(String.isBlank(TCstatus) == false  && String.isBlank(filterValue) == false && String.isBlank(MFSstatus) && String.isBlank(ReminderVal)  == false){
            system.debug('--->Reminder, TC & Search string<---'+String.isBlank(filterValue));
            filterValue = '%'+filterValue+'%';
            ratingList = [SELECT Id,Name,Participant__c,Participant__r.Name,Participant__r.Full_Name__c,Participant__r.Email__c,
                      Respondent__c,Respondent__r.Name,Respondent__r.Full_Name__c,Respondent__r.Email__c,Rater_Type__c,Status__c,Participant__r.Reports_Status__c,
                      MFS_Status__c,TC_Status__c,Overall_Status__c,Rater_String__c,Reminder__c,Report_Ready__c,Report_Sent__c,Deadline__c,Comments__c,File_Name__c,Single_Use_Link__c, MFS_Report_Sent__c, TC_Report_Sent__c , Insights_Status__c, VADC_Status__c,
                      Participant__r.Work_Request__c, Participant__r.Work_Request__r.Name,
                          EmailType__c, Email_File_Name__c, Sharepoint_File_Path__c // Added for SSE-28492
         				FROM Bureau_Rating__c WHERE (Participant__r.Bureau_Job__c = :jobId) AND (Participant__r.Full_Name__c like: filterValue OR Respondent__r.Full_Name__c like: filterValue OR Rater_Type__c like: filterValue OR Respondent__r.Email__c like: filterValue OR MFS_Status__c like: filterValue OR TC_Status__c like: filterValue OR Overall_Status__c like: filterValue OR Reminder__c =: filterValue) AND (Reminder__c =: ReminderVal) AND(TC_Status__c =:TCstatus) ORDER BY Participant__c LIMIT 200 OFFSET: offSetValue];
        }
        else if(String.isBlank(TCstatus)   && String.isBlank(filterValue) == false && String.isBlank(MFSstatus)== false && String.isBlank(ReminderVal)  == false){
            system.debug('--->Reminder, TC & Search string<---'+String.isBlank(filterValue));
            filterValue = '%'+filterValue+'%';
            ratingList = [SELECT Id,Name,Participant__c,Participant__r.Name,Participant__r.Full_Name__c,Participant__r.Email__c,
                      Respondent__c,Respondent__r.Name,Respondent__r.Full_Name__c,Respondent__r.Email__c,Rater_Type__c,Status__c,Participant__r.Reports_Status__c,
                      MFS_Status__c,TC_Status__c,Overall_Status__c,Rater_String__c,Reminder__c,Report_Ready__c,Report_Sent__c,Deadline__c,Comments__c,File_Name__c,Single_Use_Link__c, MFS_Report_Sent__c, TC_Report_Sent__c, Insights_Status__c, VADC_Status__c,
                      Participant__r.Work_Request__c, Participant__r.Work_Request__r.Name,
                          EmailType__c, Email_File_Name__c, Sharepoint_File_Path__c // Added for SSE-28492
         				FROM Bureau_Rating__c WHERE (Participant__r.Bureau_Job__c = :jobId) AND (Participant__r.Full_Name__c like: filterValue OR Respondent__r.Full_Name__c like: filterValue OR Rater_Type__c like: filterValue OR Respondent__r.Email__c like: filterValue OR MFS_Status__c like: filterValue OR TC_Status__c like: filterValue OR Overall_Status__c like: filterValue OR Reminder__c =: filterValue) AND (Reminder__c =: ReminderVal) AND(MFS_Status__c =:MFSstatus) ORDER BY Participant__c LIMIT 200 OFFSET: offSetValue];
        }
        else {
            system.debug('--->else no filter<---'+String.isBlank(filterValue));
            filterValue = '%'+filterValue+'%';
            ratingList = [SELECT Id,Name,Participant__c,Participant__r.Name,Participant__r.Full_Name__c,Participant__r.Email__c,
                      Respondent__c,Respondent__r.Name,Respondent__r.Full_Name__c,Respondent__r.Email__c,Rater_Type__c,Status__c,Participant__r.Reports_Status__c,
                      MFS_Status__c,TC_Status__c,Overall_Status__c,Rater_String__c,Reminder__c,Report_Ready__c,Report_Sent__c,Deadline__c,Comments__c,File_Name__c,Single_Use_Link__c, MFS_Report_Sent__c, TC_Report_Sent__c , Insights_Status__c, VADC_Status__c,
                      Participant__r.Work_Request__c, Participant__r.Work_Request__r.Name,
                          EmailType__c, Email_File_Name__c, Sharepoint_File_Path__c // Added for SSE-28492
         				FROM Bureau_Rating__c WHERE (Participant__r.Bureau_Job__c = :jobId) ORDER BY Participant__c LIMIT 200 OFFSET: offSetValue];
      
            
        }
        for(Bureau_Rating__c r : ratingList){
            candidateIdList.add(r.Respondent__c);
        }
        
        String soqlQuery = 'Select ' + soqlQueryList + ' FROM Bureau_Candidate__c WHERE Id IN :candidateIdList ORDER BY Full_Name__c';
        System.debug('soqlQuery '+soqlQuery);
        candidateList = database.query(soqlQuery);
        wrapper.ratingData = ratingList;
        wrapper.candidateData = candidateList;
        return wrapper;
    }
    
    @AuraEnabled
    public static list<Bureau_Rating__c> getRatingData(String jobId, Integer offSetValue, String filterValue){
        list<Bureau_Rating__c> ratingList = new list<Bureau_Rating__c>();
        if(String.isBlank(filterValue)){
            ratingList = [SELECT Id,Name,Participant__c,Participant__r.Name,Participant__r.Full_Name__c,Participant__r.Email__c,
                      Respondent__c,Respondent__r.Name,Respondent__r.Full_Name__c,Respondent__r.Email__c,Rater_Type__c,Status__c,
                          Participant__r.Reports_Status__c , Insights_Status__c, VADC_Status__c, Participant__r.Work_Request__c, Participant__r.Work_Request__r.Name
         				FROM Bureau_Rating__c WHERE Participant__r.Bureau_Job__c = :jobId ORDER BY Participant__c LIMIT 200 OFFSET: offSetValue];
        }else{
            filterValue = '%'+filterValue+'%';
            ratingList = [SELECT Id,Name,Participant__c,Participant__r.Name,Participant__r.Full_Name__c,Participant__r.Email__c,
                      Respondent__c,Respondent__r.Name,Respondent__r.Full_Name__c,Respondent__r.Email__c,Rater_Type__c,Status__c,
                          Participant__r.Reports_Status__c , Insights_Status__c, VADC_Status__c, Participant__r.Work_Request__c, Participant__r.Work_Request__r.Name
         				FROM Bureau_Rating__c WHERE (Participant__r.Bureau_Job__c = :jobId) AND (Participant__r.Full_Name__c like: filterValue OR Respondent__r.Full_Name__c like: filterValue OR Rater_Type__c like: filterValue OR Respondent__r.Email__c like: filterValue) ORDER BY Participant__c LIMIT 200 OFFSET: offSetValue];
        }
        return ratingList;
    }
    
    @AuraEnabled
    public static Map<String, List<String>> getPicklistValues(String objectName, List<String> fieldNames) {
        Map<String, List<String>> picklistValues = new Map<String, List<String>>();
        
        Schema.DescribeSObjectResult objDescribe = Schema.getGlobalDescribe().get(objectName).getDescribe();
        for (String fieldName : fieldNames) {
            Schema.DescribeFieldResult fieldDescribe = objDescribe.fields.getMap().get(fieldName).getDescribe();
            List<String> values = new List<String>();
            
            for (Schema.PicklistEntry entry : fieldDescribe.getPicklistValues()) {
                values.add(entry.getValue());
            }
            
            picklistValues.put(fieldName, values);
        }
        
        return picklistValues;
    }
}