objects/Bureau_Candidate__c.object
<CustomObject>
    <description>Managed Services module</description>
    <fields>
        <fullName>Bureau_Job__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Managed Services Job</label>
        <referenceTo>Job__c</referenceTo>
        <relationshipLabel>Managed Services Candidates</relationshipLabel>
        <relationshipName>Bureau_Candidates</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Managed Services Candidate</label>
    <nameField>
        <displayFormat>BC{000000000}</displayFormat>
        <label>Candidate Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Managed Services Candidates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/objects/Bureau_Rating__c.object
<CustomObject>
    <description>This object represents a self rating or a respondent rating for a Bureau Project Job.</description>
    <fields>
        <fullName>Bureau_Job__c</fullName>
        <formula>CASESAFEID(Participant__r.Bureau_Job__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Managed Services_Job</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Participant__c</fullName>
        <description>This field represents the Bureau Candidate who shall be acting as a participant and shall be rated by the Respondent.</description>
        <inlineHelpText>Specify the Bureau Candidate to be rated</inlineHelpText>
        <label>Participant</label>
        <referenceTo>Bureau_Candidate__c</referenceTo>
        <relationshipName>Bureau_Ratings_As_Participant</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Rating_Transfer_Status__c</fullName>
        <defaultValue>&quot;Not Transferred&quot;</defaultValue>
        <description>This field is created to store the transfer status of rating. Transfer is related FTP</description>
        <label>Rating Transfer Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Transferred</fullName>
                </value>
                <value>
                    <fullName>Transferred</fullName>
                </value>
                <value>
                    <fullName>Updated from FTP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Managed Services Rating</label>
    <nameField>
        <displayFormat>BR{000000000}</displayFormat>
        <label>Rating Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Managed Services Ratings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Job__c.object
<CustomObject>
    <description>The entity used to identify a work request from a client to the Bureau.</description>
    <label>Job</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Job Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/GetUpdatedRatingsJobs.cls
//Scheduled class to trigger a batch job that updates Job Transfer Status and Candidate Transfer Status on Job records.
//This class is designed to be run on a schedule from Schedule Apex button at 12 PM, 4 PM, 8 PM and 12 AM daily.
//and it initiates the GetUpdatedRatingsJobs batch process.

global class GetUpdatedRatingsJobs implements Database.Batchable<sObject>,Database.Stateful {
    
    public Set<Id> JobIds = new Set<Id>();
            
    global Database.QueryLocator start(Database.BatchableContext bc) {
        DateTime fourHoursAgo = DateTime.now().addHours(-4);
        return Database.getQueryLocator([
            SELECT Id, Participant__r.Bureau_Job__c,Rating_Transfer_Status__c
            FROM Bureau_Rating__c
            WHERE Lastmodifieddate >=:fourHoursAgo
            AND Participant__c != null
            AND (Participant__r.Bureau_Job__r.Candidate_Transfer_Status__c = 'Ready to transfer' OR 
                 Participant__r.Bureau_Job__r.Candidate_Transfer_Status__c = 'Sent to FTP with error')
        ]);
    }
    
    global void execute(Database.BatchableContext bc, List<Bureau_Rating__c> ratingScope) {
        for(Bureau_Rating__c rating:ratingScope){
            Id jobId = rating.Participant__r.Bureau_Job__c;
            if (jobId == null) continue;
            this.JobIds.add(jobId);
        } 
    }
    
    global void finish(Database.BatchableContext bc) {
        UpdateJobTransferStatusBatch callBatch = new UpdateJobTransferStatusBatch(this.JobIds);
		Database.executeBatch(callBatch, 2000);
    }

}