objects/Bureau_Candidate__c.object
<CustomObject>
    <description>Managed Services module</description>
    <fields>
        <fullName>Bureau_Job__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Managed Services Job</label>
        <referenceTo>Job__c</referenceTo>
        <relationshipLabel>Managed Services Candidates</relationshipLabel>
        <relationshipName>Bureau_Candidates</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Managed Services Candidate</label>
    <nameField>
        <displayFormat>BC{000000000}</displayFormat>
        <label>Candidate Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Managed Services Candidates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/objects/Bureau_Rating__c.object
<CustomObject>
    <description>This object represents a self rating or a respondent rating for a Bureau Project Job.</description>
    <fields>
        <fullName>Bureau_Job__c</fullName>
        <formula>CASESAFEID(Participant__r.Bureau_Job__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Managed Services_Job</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Participant__c</fullName>
        <description>This field represents the Bureau Candidate who shall be acting as a participant and shall be rated by the Respondent.</description>
        <inlineHelpText>Specify the Bureau Candidate to be rated</inlineHelpText>
        <label>Participant</label>
        <referenceTo>Bureau_Candidate__c</referenceTo>
        <relationshipName>Bureau_Ratings_As_Participant</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Rating_Transfer_Status__c</fullName>
        <defaultValue>&quot;Not Transferred&quot;</defaultValue>
        <description>This field is created to store the transfer status of rating. Transfer is related FTP</description>
        <label>Rating Transfer Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Transferred</fullName>
                </value>
                <value>
                    <fullName>Transferred</fullName>
                </value>
                <value>
                    <fullName>Updated from FTP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Managed Services Rating</label>
    <nameField>
        <displayFormat>BR{000000000}</displayFormat>
        <label>Rating Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Managed Services Ratings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Job__c.object
<CustomObject>
    <description>The entity used to identify a work request from a client to the Bureau.</description>
    <fields>
        <fullName>Candidate_Count__c</fullName>
        <formula>Number_of_Participants_New__c  +  Number_of_Respondents_New__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Ratings</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Candidate_Transfer_Status__c</fullName>
        <defaultValue>&quot;Not Sent to FTP&quot;</defaultValue>
        <description>This field is created to store Overall transfer satus of ratings related to Job. Transfer status is related to transfer to FTP.</description>
        <label>Candidate Transfer Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Sent to FTP</fullName>
                    <label>Not Transferred to FTP</label>
                </value>
                <value>
                    <fullName>Ready to transfer</fullName>
                    <label>Ready to Transfer</label>
                </value>
                <value>
                    <fullName>Sent to FTP</fullName>
                    <label>Transferred to FTP</label>
                </value>
                <value>
                    <fullName>Sent to FTP with error</fullName>
                    <label>Partial Transfer to FTP / Error</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Not_Transferred_Candidate_Count__c</fullName>
        <description>This field is created to store the count of not transferred ratings on the Job. Transfer is related to FTP</description>
        <label>Not Transferred Candidate Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Transferred_Candidate_Count__c</fullName>
        <description>This field is created to store the count of transferred ratings on Job, Transfer is related to FTP</description>
        <label>Transferred Candidate Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Job</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Job Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/UpdateJobTransferStatusBatch.cls
global class UpdateJobTransferStatusBatch implements Database.Batchable<sObject>,Database.Stateful {
	public Set<Id> JobIds = new Set<Id>();
    public Map<Id,Integer> JobRatingTransferredCount = new Map<Id,Integer>();
    public Map<Id,Integer> JobRatingNotTransferredCount = new Map<Id,Integer>();
    public Map<Id, Job__c> jobMap = new Map<Id, Job__c>();

    public UpdateJobTransferStatusBatch(Set<Id> JobIds){
        this.JobIds = JobIds;
    }
    
    global Database.QueryLocator start(Database.BatchableContext bc) {
        
        //DateTime fourHoursAgo = DateTime.now().addHours(-4);
        /*DateTime fourHoursAgo = DateTime.now().addHours(-4);
        return Database.getQueryLocator([
            SELECT Id, Participant__r.Bureau_Job__c,Rating_Transfer_Status__c
            FROM Bureau_Rating__c
            WHERE Lastmodifieddate >=:fourHoursAgo
            AND Participant__c != null
            AND (Participant__r.Bureau_Job__r.Candidate_Transfer_Status__c = 'Ready to transfer')
        ]);*/
        return Database.getQueryLocator([
            SELECT Id, Participant__r.Bureau_Job__c,Rating_Transfer_Status__c
            FROM Bureau_Rating__c
            WHERE Participant__c != null
            AND Participant__r.Bureau_Job__c IN :this.JobIds
        ]);
    }
    
    global void execute(Database.BatchableContext bc, List<Bureau_Rating__c> ratingScope) {
        
        /*for(Bureau_Rating__c rating:ratingScope){
            Id jobId = rating.Participant__r.Bureau_Job__c;
            if (jobId == null) continue;
            JobIds.add(jobId);
        }*/ 
        
        /*if(this.jobMap == null){
         	this.jobMap = new Map<Id, Job__c>([SELECT Id, Candidate_Count__c, Transferred_Candidate_Count__c, 
                                          Not_Transferred_Candidate_Count__c, Candidate_Transfer_Status__c
                                          FROM Job__c WHERE Id IN :JobIds]);   
        }else{
            this.jobMap.putAll(new Map<Id, Job__c>([SELECT Id, Candidate_Count__c, Transferred_Candidate_Count__c, 
                                          Not_Transferred_Candidate_Count__c, Candidate_Transfer_Status__c 
                                               FROM Job__c WHERE Id IN :JobIds]));
        }*/
        
        for(Bureau_Rating__c rating:ratingScope){
            if (rating.Rating_Transfer_Status__c == 'Not Transferred') {
                if(this.JobRatingNotTransferredCount.containskey(rating.Participant__r.Bureau_Job__c)){
                    this.JobRatingNotTransferredCount.put(rating.Participant__r.Bureau_Job__c,this.JobRatingNotTransferredCount.get(rating.Participant__r.Bureau_Job__c)+1);
                }
                else{
                    this.JobRatingNotTransferredCount.put(rating.Participant__r.Bureau_Job__c,1);
                }
            }
            else{
                if(this.JobRatingTransferredCount.containskey(rating.Participant__r.Bureau_Job__c)){
                    this.JobRatingTransferredCount.put(rating.Participant__r.Bureau_Job__c,this.JobRatingTransferredCount.get(rating.Participant__r.Bureau_Job__c)+1);
                }
                else{
                    this.JobRatingTransferredCount.put(rating.Participant__r.Bureau_Job__c,1);
                }
            }
        }
        System.debug('TransferredCount '+this.JobRatingTransferredCount);
        System.debug('NotTransferredCount '+this.JobRatingNotTransferredCount);
    }
    
    global void finish(Database.BatchableContext bc) {
        List<Job__c> JobsToUpdate = new List<Job__c>();
        for(Id job:this.JobIds){
            Job__c jobToUpdate = new Job__c(id=job);
            if(this.JobRatingTransferredCount.get(job) != null){
                jobToUpdate.Transferred_Candidate_Count__c = this.JobRatingTransferredCount.get(job);
            }else{
                jobToUpdate.Transferred_Candidate_Count__c = 0;
            }
            if(this.JobRatingNotTransferredCount.get(job)!=null){
                jobToUpdate.Not_Transferred_Candidate_Count__c = this.JobRatingNotTransferredCount.get(job);
            }else{
                jobToUpdate.Not_Transferred_Candidate_Count__c = 0;
            }
            //System.debug('this.jobMap.get(job).Transferred_Candidate_Count__c '+this.jobMap.get(job).Transferred_Candidate_Count__c);
            //System.debug('this.JobRatingTransferredCount.get(job) '+this.JobRatingTransferredCount.get(job));
            /*if(this.jobMap.get(job).Transferred_Candidate_Count__c != null && this.JobRatingTransferredCount.get(job)!=null){
                jobToUpdate.Transferred_Candidate_Count__c = this.jobMap.get(job).Transferred_Candidate_Count__c + this.JobRatingTransferredCount.get(job);
            }else if(this.JobRatingTransferredCount.get(job)!=null){
               jobToUpdate.Transferred_Candidate_Count__c = this.JobRatingTransferredCount.get(job); 
            }
            
            if(jobToUpdate.Transferred_Candidate_Count__c == null){
                jobToUpdate.Transferred_Candidate_Count__c = 0;
            }
            jobToUpdate.Not_Transferred_Candidate_Count__c = this.jobMap.get(job).Candidate_Count__c - jobToUpdate.Transferred_Candidate_Count__c;
            */
            //jobToUpdate.Not_Transferred_Candidate_Count__c = this.JobRatingNotTransferredCount.get(job);
            //jobToUpdate.Transferred_Candidate_Count__c = this.JobRatingTransferredCount.get(job);
            //if(this.JobRatingNotTransferredCount.get(job)!=null && this.JobRatingNotTransferredCount.get(job)!=0){
            if(jobToUpdate.Transferred_Candidate_Count__c != 0 && jobToUpdate.Not_Transferred_Candidate_Count__c != 0){
                jobToUpdate.Candidate_Transfer_Status__c = 'Sent to FTP with error';
            }
            if(jobToUpdate.Not_Transferred_Candidate_Count__c == 0){
                jobToUpdate.Candidate_Transfer_Status__c = 'Sent to FTP';
            }
            JobsToUpdate.add(jobToUpdate);
        }
        update JobsToUpdate;
    }
}