objects/Bureau_Candidate__c.object
<CustomObject>
    <description>Managed Services module</description>
    <fields>
        <fullName>Bureau_Job__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Managed Services Job</label>
        <referenceTo>Job__c</referenceTo>
        <relationshipLabel>Managed Services Candidates</relationshipLabel>
        <relationshipName>Bureau_Candidates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Afghanistan</fullName>
                </value>
                <value>
                    <fullName>Albania</fullName>
                </value>
                <value>
                    <fullName>Algeria</fullName>
                </value>
                <value>
                    <fullName>American Samoa</fullName>
                </value>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Angola</fullName>
                </value>
                <value>
                    <fullName>Anguilla</fullName>
                </value>
                <value>
                    <fullName>Antartica</fullName>
                </value>
                <value>
                    <fullName>Antigua and Barbuda</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Armenia</fullName>
                </value>
                <value>
                    <fullName>Aruba</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Azerbaidjan</fullName>
                </value>
                <value>
                    <fullName>Bahamas</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Bangladesh</fullName>
                </value>
                <value>
                    <fullName>Barbados</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Benin</fullName>
                </value>
                <value>
                    <fullName>Bermuda</fullName>
                </value>
                <value>
                    <fullName>Bhutan</fullName>
                </value>
                <value>
                    <fullName>Bolivia</fullName>
                </value>
                <value>
                    <fullName>Bosnia-Herzegovina</fullName>
                </value>
                <value>
                    <fullName>Botswana</fullName>
                </value>
                <value>
                    <fullName>Bouvet Island</fullName>
                </value>
                <value>
                    <fullName>Brazil</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Email_as_Username__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is used to capture true or false. If true then Email will be copied over Username</description>
        <label>Email as Username?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Male</fullName>
                </value>
                <value>
                    <fullName>Female</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Language__c</fullName>
        <label>Language</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>German</fullName>
                </value>
                <value>
                    <fullName>English</fullName>
                </value>
                <value>
                    <fullName>Norwegian</fullName>
                </value>
                <value>
                    <fullName>Swedish</fullName>
                </value>
                <value>
                    <fullName>Danish</fullName>
                </value>
                <value>
                    <fullName>Dutch</fullName>
                </value>
                <value>
                    <fullName>French</fullName>
                </value>
                <value>
                    <fullName>Italian</fullName>
                </value>
                <value>
                    <fullName>Spanish</fullName>
                </value>
                <value>
                    <fullName>Portuguese</fullName>
                </value>
                <value>
                    <fullName>Finnish</fullName>
                </value>
                <value>
                    <fullName>Polish</fullName>
                </value>
                <value>
                    <fullName>Turkish</fullName>
                </value>
                <value>
                    <fullName>Hungarian</fullName>
                </value>
                <value>
                    <fullName>Icelandic</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone_Number__c</fullName>
        <label>Phone Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Product_Assessment__c</fullName>
        <description>This field is used to capture Products &amp; Assessments applicable for a candidate</description>
        <label>Product/Assessment</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reports_Status__c</fullName>
        <description>This field represents the status of the Reports for this Participant</description>
        <inlineHelpText>Specify the status of the Reports for this Participant</inlineHelpText>
        <label>Reports Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Unsent</fullName>
                    <default>true</default>
                    <label>Unsent</label>
                </value>
                <value>
                    <fullName>Ready to be Generated</fullName>
                </value>
                <value>
                    <fullName>Generated</fullName>
                </value>
                <value>
                    <fullName>Partially Sent</fullName>
                </value>
                <value>
                    <fullName>Sent</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status2__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Not Started</fullName>
                    <default>true</default>
                    <label>Not Started</label>
                </value>
                <value>
                    <fullName>Pass</fullName>
                </value>
                <value>
                    <fullName>Fail</fullName>
                </value>
                <value>
                    <fullName>DNA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>System_s__c</fullName>
        <description>This field is used to capture System(s) applicable for a candidate</description>
        <label>System(s)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Username_New__c</fullName>
        <formula>IF(
				ISBLANK(Username__c), 
			IF(NOT(Email_as_Username__c),
			  NULL
			, Email__c)
			,Username__c
)</formula>
        <label>Username</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Username__c</fullName>
        <description>This field is used to capture Username based on Email as Username field</description>
        <label>Username</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>isExported__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is used for backend processing while candidate export.</description>
        <label>isExported</label>
        <type>Checkbox</type>
    </fields>
    <label>Managed Services Candidate</label>
    <nameField>
        <displayFormat>BC{000000000}</displayFormat>
        <label>Candidate Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Managed Services Candidates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/objects/Bureau_System__c.object
<CustomObject>
    <description>This object represents a relation between a Bureau Job and a System.</description>
    <fields>
        <fullName>Bureau_Job__c</fullName>
        <description>This field represents the Bureau Job to which is the parent of this record.</description>
        <label>Managed Services Job</label>
        <referenceTo>Job__c</referenceTo>
        <relationshipLabel>Managed Services Systems</relationshipLabel>
        <relationshipName>Bureau_Systems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Managed Services System</label>
    <nameField>
        <displayFormat>BJS{000000}</displayFormat>
        <label>Managed Services System Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Managed Services Systems</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Job__c.object
<CustomObject>
    <description>The entity used to identify a work request from a client to the Bureau.</description>
    <fields>
        <fullName>Capture_Content_Version_Ids_For_Export__c</fullName>
        <description>This field is used to capture Content Version Ids for candidate bulk export</description>
        <label>Capture Content Version Ids For Export</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Assessment__c</fullName>
        <description>Assessments linked to this Job Card or Project.</description>
        <inlineHelpText>Add  assessments applicable for this job or project.</inlineHelpText>
        <label>Product/Assessment</label>
        <type>TextArea</type>
    </fields>
    <label>Job</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Job Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/ExportCandidateData.cls
global with sharing class ExportCandidateData implements Database.Batchable<sObject>, Database.Stateful{

    global final String finalQuery;
    global Job__c job;
    global String outputText;
    global Integer processedRecordsCount = 0;
    global String jobRecordTypeName;
    global List<Bureau_System__c> bureauSystemsList;
    global Boolean isExecuteCalled = false;
    global Integer count = 0;
    
    global ExportCandidateData(Job__c jb, Integer count1) {
        job = jb;
        count = count1;
        String query;
        
        query='SELECT Id,Name,First_Name__c,Last_Name__c,Email__c,Phone_Number__c,Country__c,Language__c,Gender__c,Reports_Status__c,Status2__c,Username__c,Product_Assessment__c,System_s__c,Email_as_Username__c,Username_New__c,isExported__c';
        query+=' FROM Bureau_Candidate__c where Bureau_Job__c=\''+job.Id+'\'';
        query+=' AND isExported__c = false';
        query+=' LIMIT 26000';
        
        finalQuery = query;

        List<String> columnHeaderList;
            columnHeaderList = new List<String>{'Record ID','First Name','Last Name','Email Address','Gender','Phone Number','Country','Language','Status','Report Status','Username','Product/Assessment','System(s)','Email as Username?'};
            outputText = '';
            outputText += columnHeaderList[0];
            for(Integer j=1; j<columnHeaderList.size();j++)
                outputText += ','+columnHeaderList[j];
    }

    global Database.QueryLocator start(Database.BatchableContext BC)
    {
      return Database.getQueryLocator(finalQuery);
    }
   
    global void execute(Database.BatchableContext BC,List<Bureau_Candidate__c> scope)
    {
        if(Limits.getHeapSize() < 0.9*Limits.getLimitHeapSize()) {
        for(Bureau_Candidate__c s : scope)
            {
                isExecuteCalled = true;
                processedRecordsCount += 1;

                outputText += '\r\n'+s.get('id');
                outputText += ','+s.get('First_Name__c');
                outputText += ','+(s.get('Last_Name__c')==null?'':s.get('Last_Name__c'));
                outputText += ','+s.get('Email__c');
                outputText += ','+(s.get('Gender__c')==null?'':s.get('Gender__c'));
                outputText += ','+(s.get('Phone_Number__c')==null?'':s.get('Phone_Number__c'));
                outputText += ','+(s.get('Country__c')==null?'':s.get('Country__c'));
                outputText += ','+(s.get('Language__c')==null?'':s.get('Language__c'));
                outputText += ','+(s.get('Status2__c')==null?'':s.get('Status2__c'));
                outputText += ','+(s.get('Reports_Status__c')==null?'':s.get('Reports_Status__c'));
                outputText += ','+(s.get('Username_New__c')==null?'':s.get('Username_New__c'));
                outputText += ',"'+(s.get('Product_Assessment__c')==null?'':s.get('Product_Assessment__c'))+'"';
                outputText += ',"'+(s.get('System_s__c')==null?'':s.get('System_s__c'))+'"';
                outputText += ','+(s.get('Email_as_Username__c')==null?'':s.get('Email_as_Username__c'));
                
                Bureau_Candidate__c bureauCandidate = (Bureau_Candidate__c)s;
                s.isExported__c = true;
            }
            UPDATE scope;
            }
    }

    global void finish(Database.BatchableContext BC)
    {
        AsyncApexJob a = [SELECT Id, Status, NumberOfErrors, JobItemsProcessed,
                            TotalJobItems, CreatedBy.Email FROM AsyncApexJob WHERE Id = :BC.getJobId()];
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        String[] toAddresses = new String[] {a.CreatedBy.Email};
        mail.setToAddresses(toAddresses);
        
        if(a.Status=='Completed')
        {
            count = count + 1;
            ContentVersion Cv = new ContentVersion();    
            Cv.Origin='C';
            Cv.VersionData = Blob.ValueOf(outputText);
            Cv.Title = job.Name+'CandidateExportSheet'+count+'.csv';
            Cv.PathOnClient = job.Name+'CandidateExportSheet.csv'; 
            Cv.ContentLocation='S';        
            insert Cv;  

            // First get the content document Id from ContentVersion
            Id conDoc = [SELECT ContentDocumentId FROM ContentVersion WHERE Id =:Cv.Id].ContentDocumentId;
             
            //Create ContentDocumentLink
            ContentDocumentLink cDe = new ContentDocumentLink();
            cDe.ContentDocumentId = conDoc;
            cDe.Visibility='AllUsers';
            cDe.LinkedEntityId = job.Id;
            cDe.ShareType = 'V';
            insert cDe;    
            

            String previousValue;
            if(job.Capture_Content_Version_Ids_For_Export__c != NULL){
                previousValue = job.Capture_Content_Version_Ids_For_Export__c;
                job.Capture_Content_Version_Ids_For_Export__c = previousValue + ',' + Cv.Id;
            }else{
                job.Capture_Content_Version_Ids_For_Export__c = Cv.Id;
            }
            UPDATE job;

            if(processedRecordsCount == 26000){
                ExportCandidateData b = new ExportCandidateData(job, count);
                Database.executeBatch(b, 200);
            }else if(isExecuteCalled == true && (processedRecordsCount == 0 || processedRecordsCount < 26000)){
                String fullFileURL;
                String messageBody = '';
                List<String> fullFileURLList = new List<String>();
                    
                if(job.Capture_Content_Version_Ids_For_Export__c != NULL){
                    String contentVersionValue = job.Capture_Content_Version_Ids_For_Export__c;
                    List<String> listOfJobIds = contentVersionValue.split(',');
                    for(String aa : listOfJobIds){
                        fullFileURL = URL.getSalesforceBaseUrl().toExternalForm()+'/'+aa;
                        fullFileURLList.add(fullFileURL);
                    }
                    for(Integer i=0 ;i<fullFileURLList.size();i++){
                        messageBody = messageBody + 'Please <a href=\''+fullFileURLList[i]+'\' > Click Here - '+job.Name+'CandidateExportSheet'+(i+1)+'.csv </a>to download the candidate upload sheet. </br>';
                    }    
                }
                
                mail.setSubject('Candidate Upload Sheet has been exported successfully. ');
                mail.setHtmlBody(messageBody);
                
                Messaging.SendEmailResult[] res = Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
                RevertIsExportedOnCandidate b1 = new RevertIsExportedOnCandidate(job);
                Database.executeBatch(b1, 2000);
            }else{
                System.debug('It is a Failure');
            }
        }
        else
        {
            mail.setSubject('Exporting Candidate Upload Sheet has been failed. ');
            mail.setHtmlBody('The batch Apex job processed ' + a.TotalJobItems +' batches with '+ a.NumberOfErrors + ' failures.');
            Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
        
        }  
    }

}