objects/Bureau_Candidate__c.object
<CustomObject>
    <description>Managed Services module</description>
    <fields>
        <fullName>Bureau_Job__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Managed Services Job</label>
        <referenceTo>Job__c</referenceTo>
        <relationshipLabel>Managed Services Candidates</relationshipLabel>
        <relationshipName>Bureau_Candidates</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Managed Services Candidate</label>
    <nameField>
        <displayFormat>BC{000000000}</displayFormat>
        <label>Candidate Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Managed Services Candidates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/objects/Bureau_Candidate_Login__c.object
<CustomObject>
    <description>Bureau module</description>
    <fields>
        <fullName>Bureau_Candidate__c</fullName>
        <description>This field represents the Candidate to which this Candidate Login belongs</description>
        <inlineHelpText>Select the Candidate to which this Candidate Login belongs</inlineHelpText>
        <label>Managed Services Candidate</label>
        <referenceTo>Bureau_Candidate__c</referenceTo>
        <relationshipLabel>Managed Services Candidate Logins</relationshipLabel>
        <relationshipName>Bureau_Candidate_Logins</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Bureau_System__c</fullName>
        <description>This field represents the Bureau System to which this Candidate Login belongs</description>
        <inlineHelpText>Select  the Bureau System to which this Candidate Login belongs</inlineHelpText>
        <label>Managed Services System</label>
        <referenceTo>Bureau_System__c</referenceTo>
        <relationshipLabel>Managed Services Candidate Logins</relationshipLabel>
        <relationshipName>Bureau_Candidate_Logins</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Password__c</fullName>
        <label>Password</label>
        <length>50</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
    <label>Managed Services Candidate Login</label>
    <nameField>
        <displayFormat>BCL{0000000000}</displayFormat>
        <label>Managed Services Candidate Login Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Managed Services Candidate Logins</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/objects/Bureau_System__c.object
<CustomObject>
    <description>This object represents a relation between a Bureau Job and a System.</description>
    <fields>
        <fullName>Bureau_Job__c</fullName>
        <description>This field represents the Bureau Job to which is the parent of this record.</description>
        <label>Managed Services Job</label>
        <referenceTo>Job__c</referenceTo>
        <relationshipLabel>Managed Services Systems</relationshipLabel>
        <relationshipName>Bureau_Systems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Managed Services System</label>
    <nameField>
        <displayFormat>BJS{000000}</displayFormat>
        <label>Managed Services System Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Managed Services Systems</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Job__c.object
<CustomObject>
    <description>The entity used to identify a work request from a client to the Bureau.</description>
    <fields>
        <fullName>Candidate_Username_Prefix__c</fullName>
        <description>This field is meant for specifying a 4-character text that shall be used as a prefix of the usernames generated for the candidates of a Job.</description>
        <inlineHelpText>Specify the username prefix for all candidates of this Job.</inlineHelpText>
        <label>Candidate Username Prefix</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <label>Job</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Job Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/MS_SystemTriggerManager.cls
/*****************************************************************************
CREATED BY :- Prabhat Arora
CREATED DATE :- 22-08-2019
DESCRIPTION :- This class contains Methods to create Candidate Login & Passwords in context to MS System Functionality as per SHL business process,
               this class is being refered from MS_System_Trigger, covering the After Insert Event on MS System Records. 
******************************************************************************/
Global class MS_SystemTriggerManager{
    Global MS_SystemTriggerManager(){
        
    }
    // Public static void CreateCandidatelogins(List<Bureau_System__c> NewSystemList){
    //     System.debug('NewSystemList ###'+NewSystemList.size());
    //     Set<Id> jobIds = new Set<Id>();
    //     for(Bureau_System__c bureauSystem:NewSystemList)
    //     {
    //         if(!jobIds.contains(bureauSystem.Bureau_Job__c))
    //             jobIds.add(bureauSystem.Bureau_Job__c);
    //     }
    //     Map<Id,Job__c> jobMap = new Map<Id,Job__c>([SELECT Id,Name,Candidate_Username_Prefix__c,(SELECT Id, Name FROM Bureau_Candidates__r) FROM Job__c WHERE Id IN:jobIds]);
        
    //     List<Bureau_Candidate_Login__c> candidateLogins = new List<Bureau_Candidate_Login__c>();
    //     for(Bureau_System__c bureauSystem:NewSystemList)
    //     {
    //         Job__c job = jobMap.get(bureauSystem.Bureau_Job__c);
    //         List<Bureau_Candidate__c> candidates = job.Bureau_Candidates__r;
    //         for(Bureau_Candidate__c candidate: candidates)
                
    //         {
    //             Bureau_Candidate_Login__c candidateLogin = new Bureau_Candidate_Login__c();
    //             candidateLogin.Bureau_Candidate__c = candidate.Id;
    //             candidateLogin.Bureau_System__c = bureauSystem.Id;
    //             candidateLogin.Password__c = EncodingUtil.convertToHex(crypto.generateAesKey(128)).substring(0,8).replace('0','h').replace('1','i').replace('2','j').replace('3','k').replace('4','l').replace('5','m').replace('6','n').replace('7','o').replace('8','p').replace('9','q');        
    //             candidateLogins.add(candidateLogin);
    //         }
    //     }
    //     //system.debug('This is Candidate Id'+candidates[0].id);
    //     insert candidateLogins;
        
    //     BureauJob_Manager.refreshRaterTypes(jobIds);
    // }
    
}