objects/Bureau_Candidate__c.object
<CustomObject>
    <description>Managed Services module</description>
    <fields>
        <fullName>Category__c</fullName>
        <description>This field is used to capture Rater Type or Category of Candidate. Applicable only for MFS</description>
        <label>Category</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Managed Services Candidate</label>
    <nameField>
        <displayFormat>BC{000000000}</displayFormat>
        <label>Candidate Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Managed Services Candidates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Form_Attribute__c.object
<CustomObject>
    <fields>
        <fullName>API_Name__c</fullName>
        <label>API Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Work Request Form</fullName>
                </value>
                <value>
                    <fullName>Candidate Import Template</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Data_Type__c</fullName>
        <label>Data Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>text</fullName>
                </value>
                <value>
                    <fullName>number</fullName>
                </value>
                <value>
                    <fullName>date</fullName>
                </value>
                <value>
                    <fullName>time</fullName>
                </value>
                <value>
                    <fullName>datetime</fullName>
                </value>
                <value>
                    <fullName>checkbox</fullName>
                </value>
                <value>
                    <fullName>checkboxgroup</fullName>
                </value>
                <value>
                    <fullName>DropDown</fullName>
                </value>
                <value>
                    <fullName>email</fullName>
                </value>
                <value>
                    <fullName>radiogroup</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Label__c</fullName>
        <label>Label</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Object__c</fullName>
        <label>Object</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Bureau_Candidate__c</fullName>
                </value>
                <value>
                    <fullName>Work_Request__c</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Form Attribute</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Attribute Index Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Form Attributes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/FormAttributeTriggerManager_Test.cls
@isTest
public class FormAttributeTriggerManager_Test {
	
    @isTest
    public static void beforeInsert(){
        Form_Attribute__c fa = new Form_Attribute__c();
        fa.Label__c = 'ForTestClass';
        fa.API_Name__c = 'For_Test_Class__c';
        fa.Data_Type__c = 'text';
        fa.Category__c = 'Candidate Import Template';
        fa.Object__c = 'Bureau_Candidate__c';
        
        Test.startTest();
        insert fa;
        fa.Data_Type__c = 'number';
        update fa;
        Test.stopTest(); 
    }
    
    @isTest
    public static void beforeInsertDuplicate(){
        Form_Attribute__c fa = new Form_Attribute__c();
        fa.Label__c = 'ForTestClass';
        fa.API_Name__c = 'For_Test_Class__c';
        fa.Data_Type__c = 'text';
        fa.Category__c = 'Candidate Import Template';
        fa.Object__c = 'Bureau_Candidate__c';
        insert fa;
        
        Form_Attribute__c fa1 = new Form_Attribute__c();
        fa1.Label__c = 'ForTestClass';
        fa1.API_Name__c = 'For_Test_Class__c';
        fa1.Data_Type__c = 'text';
        fa1.Category__c = 'Candidate Import Template';
        fa1.Object__c = 'Bureau_Candidate__c';

        List<Form_Attribute__c> formAttributesList = new List<Form_Attribute__c>{fa1};
        
        Test.startTest();
        FormAttributeTriggerManager.beforeInsertUpdate(formAttributesList, null);
        Test.stopTest();
        
    }
}