objects/Bureau_Candidate__c.object
<CustomObject>
    <description>Managed Services module</description>
    <fields>
        <fullName>Category__c</fullName>
        <description>This field is used to capture Rater Type or Category of Candidate. Applicable only for MFS</description>
        <label>Category</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Managed Services Candidate</label>
    <nameField>
        <displayFormat>BC{000000000}</displayFormat>
        <label>Candidate Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Managed Services Candidates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Form_Attribute__c.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Work Request Form</fullName>
                </value>
                <value>
                    <fullName>Candidate Import Template</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Label__c</fullName>
        <label>Label</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Object__c</fullName>
        <label>Object</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Bureau_Candidate__c</fullName>
                </value>
                <value>
                    <fullName>Work_Request__c</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Form Attribute</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Attribute Index Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Form Attributes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/FormAttributeTriggerManager.cls
public class FormAttributeTriggerManager {
    
    public static list<MetadataService.Metadata> mtdt = new list<MetadataService.Metadata>();
    
    public static void beforeInsertUpdate(list<Form_Attribute__c> formAttributesList, Map<Id, Form_Attribute__c> formMap){
        Set<String> uniqueLabel = new Set<String>();
        Set<Form_Attribute__c> recordsToInsert = new Set<Form_Attribute__c>();
        Map<String, Boolean> existingFormAttributeRecordsMap = new Map<String, Boolean>();
        for (Form_Attribute__c fa : formAttributesList) {
            System.debug('Inside For loop ');
            if(fa.Category__c == 'Candidate Import Template'
              && fa.Label__c != null
              && fa.Object__c == 'Bureau_Candidate__c'){
                  System.debug('Inside If statement ');
                  if(formMap != null && fa.Label__c != formMap.get(fa.Id).Label__c){
                      uniqueLabel.add(fa.Label__c.toLowerCase());
                	  recordsToInsert.add(fa);
                  }
                  if(formMap == null){
                      System.debug('Inside second If statement ');
                      SYstem.debug('Label '+fa.Label__c);
                     uniqueLabel.add(fa.Label__c.toLowerCase());
                	  recordsToInsert.add(fa); 
                  }
            }
        }
                
        if (!recordsToInsert.isEmpty()) {
            System.debug('uniqueLabel '+uniqueLabel);
            /*List<Form_Attribute__c> existingAttrubutes = [SELECT Id, Label__c, Object__c, Category__c FROM Form_Attribute__c 
                                      WHERE Label__c IN :uniqueLabel 
                                      AND Category__c = 'Candidate Import Template'
                                      AND Object__c = 'Bureau_Candidate__c'];*/
            List<Form_Attribute__c> existingAttrubutes = [SELECT Id, Label__c, Object__c, Category__c FROM Form_Attribute__c 
                                      WHERE Category__c = 'Candidate Import Template'
                                      AND Object__c = 'Bureau_Candidate__c'];
            
            System.debug('existingAttrubutes '+existingAttrubutes);
            for (Form_Attribute__c fa : existingAttrubutes) {
                existingFormAttributeRecordsMap.put(fa.Label__c, true);
            }
			System.debug('existingFormAttributeRecordsMap '+existingFormAttributeRecordsMap);
			            
            for (Form_Attribute__c fa : recordsToInsert) {
                system.debug('fa '+fa.Label__c);
                if (existingFormAttributeRecordsMap.containsKey(fa.Label__c)) {
                    fa.addError('A record with the same label already exists.');
                }
            }
        }
        
    }
}