objects/Bureau_Candidate__c.object
<CustomObject>
    <description>Managed Services module</description>
    <fields>
        <fullName>Bureau_Job__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Managed Services Job</label>
        <referenceTo>Job__c</referenceTo>
        <relationshipLabel>Managed Services Candidates</relationshipLabel>
        <relationshipName>Bureau_Candidates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <description>This field is used to capture Rater Type or Category of Candidate. Applicable only for MFS</description>
        <label>Category</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>IF( Total_Ratings__c ==  Ratings_Completed__c ,&quot;Completed&quot;,IF(Ratings_Completed__c&gt;0 ||  Ratings_In_Progress__c&gt;0,&quot;In Progress&quot;, &quot;Not Started&quot;))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <label>Managed Services Candidate</label>
    <nameField>
        <displayFormat>BC{000000000}</displayFormat>
        <label>Candidate Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Managed Services Candidates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Bureau_Item_Master__c.object
<CustomObject>
    <description>This object represents an Item such as Instrument, Report or Service.</description>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Online Admin</fullName>
                </value>
                <value>
                    <fullName>S2P Solutions</fullName>
                </value>
                <value>
                    <fullName>Online Reports</fullName>
                </value>
                <value>
                    <fullName>S2P Tests (a – d)</fullName>
                </value>
                <value>
                    <fullName>Gradu8</fullName>
                </value>
                <value>
                    <fullName>S2P Tests (d – f)</fullName>
                </value>
                <value>
                    <fullName>Online - PJM/WPS/JCF/OCP</fullName>
                </value>
                <value>
                    <fullName>S2P Tests (g – j)</fullName>
                </value>
                <value>
                    <fullName>Offline Scoring</fullName>
                </value>
                <value>
                    <fullName>S2P Tests (k – n)</fullName>
                </value>
                <value>
                    <fullName>360 Services</fullName>
                </value>
                <value>
                    <fullName>S2P Tests (o – r)</fullName>
                </value>
                <value>
                    <fullName>Offline Reports</fullName>
                </value>
                <value>
                    <fullName>S2P Tests (s – v)</fullName>
                </value>
                <value>
                    <fullName>Managed Services</fullName>
                </value>
                <value>
                    <fullName>S2P Tests (w – z)</fullName>
                </value>
                <value>
                    <fullName>Offline - PJM/WPS/JCF/OCP</fullName>
                </value>
                <value>
                    <fullName>Previsor Products</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Item</label>
    <nameField>
        <label>Managed Services Item Master Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <recordTypes>
        <fullName>Instrument</fullName>
        <active>true</active>
        <description>This record type defines the Bureau Item as an Instrument</description>
        <label>Instrument</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/objects/Bureau_Product__c.object
<CustomObject>
    <description>To link to the Job object for OLB jobs</description>
    <fields>
        <fullName>Category__c</fullName>
        <description>Instrument or Report</description>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Express Service</fullName>
                </value>
                <value>
                    <fullName>Instrument</fullName>
                </value>
                <value>
                    <fullName>Report</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Invoice_Only__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Invoice Only</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Item_Type__c</fullName>
        <formula>TEXT(Item__r.Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Item Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Item</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Bureau_Item_Master__c.Type__c</field>
                <operation>equals</operation>
                <valueField>$Source.Category__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Bureau_Item_Master__c</referenceTo>
        <relationshipName>Bureau_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Job__c</fullName>
        <label>Job</label>
        <referenceTo>Job__c</referenceTo>
        <relationshipName>Bureau_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Managed Services Product</label>
    <nameField>
        <displayFormat>BProd{00000}</displayFormat>
        <label>Managed Services Product</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Managed Services Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/objects/Bureau_Rating__c.object
<CustomObject>
    <description>This object represents a self rating or a respondent rating for a Bureau Project Job.</description>
    <fields>
        <fullName>Bureau_Job__c</fullName>
        <formula>CASESAFEID(Participant__r.Bureau_Job__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Managed Services_Job</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Participant__c</fullName>
        <description>This field represents the Bureau Candidate who shall be acting as a participant and shall be rated by the Respondent.</description>
        <inlineHelpText>Specify the Bureau Candidate to be rated</inlineHelpText>
        <label>Participant</label>
        <referenceTo>Bureau_Candidate__c</referenceTo>
        <relationshipName>Bureau_Ratings_As_Participant</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Respondent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field represents the Bureau Candidate who shall acting as a respondent and shall be rating the Participant.</description>
        <inlineHelpText>Specify the Candidate who shall be rating the Participant</inlineHelpText>
        <label>Respondent</label>
        <referenceTo>Bureau_Candidate__c</referenceTo>
        <relationshipName>Bureau_Ratings_As_Respondent</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>This field represents the Status of the Rating</description>
        <formula>IF(Total_Instruments__c== Instruments_Completed__c,&quot;Completed&quot;,IF(Instruments_Completed__c&gt;0 || Instruments_In_Progress__c&gt;0,&quot;In Progress&quot;, &quot;Not Started&quot;))</formula>
        <inlineHelpText>This is the current status of the Rating</inlineHelpText>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <label>Managed Services Rating</label>
    <nameField>
        <displayFormat>BR{000000000}</displayFormat>
        <label>Rating Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Managed Services Ratings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/objects/Bureau_Rating_Progress__c.object
<CustomObject>
    <description>Bureau module</description>
    <fields>
        <fullName>Bureau_Product__c</fullName>
        <label>Managed Services Product</label>
        <referenceTo>Bureau_Product__c</referenceTo>
        <relationshipLabel>Managed Services Ratings Progress</relationshipLabel>
        <relationshipName>Bureau_Ratings_Progresss</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Bureau_Rating__c</fullName>
        <label>Managed Services Rating</label>
        <referenceTo>Bureau_Rating__c</referenceTo>
        <relationshipLabel>Managed Services Ratings Progress</relationshipLabel>
        <relationshipName>Bureau_Ratings_Progress</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                    <default>true</default>
                    <label>Not Started</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Managed Services Rating Progress</label>
    <nameField>
        <displayFormat>BRP{0000000000}</displayFormat>
        <label>Rating Progress Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Managed Services Ratings Progress</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Job__c.object
<CustomObject>
    <description>The entity used to identify a work request from a client to the Bureau.</description>
    <fields>
        <fullName>CurrencyToBeBilled__c</fullName>
        <formula>TEXT(Account__r.CurrencyIsoCode)</formula>
        <label>Currency To Be Billed</label>
        <type>Text</type>
    </fields>
    <label>Job</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Job Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/MS_ProductTriggerManager.cls
/*****************************************************************************
CREATED BY :- Prabhat Arora
CREATED DATE :- 21-08-2019
DESCRIPTION :- This class contains Methods to create Rating Progress records in context to MS Product & Rating Functionality as per SHL business process,
               this class is being refered from MS_Product_Trigger, covering the Before/After Insert/Delete & Update Events on MS Product Records. 
******************************************************************************/
Global class MS_ProductTriggerManager {
    //Commented By : Shubham Singh
    //Reason: deprecate Rating Progress
    //Reference: SSE-19314
    
    /*Public static void setcurencyISOCode(List<Bureau_Product__c> NewProductList){
        Set<Id> jobIdsSet = new Set<Id>();
        for(Integer i=0; i< NewProductList.size();i++)  
            jobIdsSet.add(NewProductList[i].Job__c);
        Map<Id,Job__c> jobsMap = new Map<Id,Job__c>([Select id,CurrencyToBeBilled__c from Job__c where id in :jobIdsSet]);
        for(Integer i=0; i< NewProductList.size();i++)  
            NewProductList[i].CurrencyIsoCode = jobsMap.get(NewProductList[i].Job__c).CurrencyToBeBilled__c;
    }
    
    Public static void DeleteProgressRating(List<Bureau_Product__c> OldProductList){
        Set<Id> bureauProductIdsSet = new Set<Id>();
        List<Bureau_Rating_Progress__c> bRatingProgressToDeleteList = new List<Bureau_Rating_Progress__c>();
        for(Integer i=0;i<OldProductList.size();i++)
            bureauProductIdsSet.add(OldProductList[i].id);
        Map<Id,Bureau_Product__c> bureauProductMap = new Map<Id,Bureau_Product__c>([Select id,(Select id,Status__c from Bureau_Ratings_Progresss__r) from Bureau_Product__c where id in :bureauProductIdsSet]);
        for(Integer i=0;i<OldProductList.size();i++)
        {
            Boolean productCanNotBeDeleted = false;
            for(Bureau_Rating_Progress__c bRP:bureauProductMap.get(OldProductList[i].id).Bureau_Ratings_Progresss__r)
            {
                if(bRP.Status__c == 'In Progress' || bRP.Status__c == 'Completed')
                {
                    productCanNotBeDeleted = true;
                    OldProductList[i].addError('This product cannot be deleted as there are related ratings which are either in progress or completed. Please change the status of these ratings to "Not Started" in order to delete this product.');
                    break;
                }
            }
            if(bureauProductMap.get(OldProductList[i].id).Bureau_Ratings_Progresss__r.size()>0 && productCanNotBeDeleted == false)
                bRatingProgressToDeleteList.addAll(bureauProductMap.get(OldProductList[i].id).Bureau_Ratings_Progresss__r);
        }
        if(bRatingProgressToDeleteList.size()>0){
            if(bRatingProgressToDeleteList.size()<8000){
                delete bRatingProgressToDeleteList;
            }
        }
    }
    
    //Commented By : Pallavi Jadhav
    //Reason: deprecate Rating Progress
    //Reference: SSE-18140
    /*Public static void InsertProgressRating(List<Bureau_Product__c> NewProductList,List<Bureau_Product__c> OldProductList,Boolean IsInsert){
        Set<Id> jobIds = new Set<Id>();
        Set<Id> invoiceOnlyProductIds = new Set<Id>();
        Set<Id> bureauProductIds = new Set<Id>();
        for(Integer i=0;i<NewProductList.size();i++)
        {
            if(NewProductList[i].Item_Type__c=='Instrument')
            {
                bureauProductIds.add(NewProductList[i].id);
                if(IsInsert)
                {
                    if(NewProductList[i].Invoice_Only__c==false)
                        jobIds.add(NewProductList[i].Job__c);
                }
                else if(!IsInsert)
                {
                    if(NewProductList[i].Invoice_Only__c!=OldProductList[i].Invoice_Only__c)
                    {
                        if(NewProductList[i].Invoice_Only__c==false)
                            jobIds.add(NewProductList[i].Job__c);
                        else
                            invoiceOnlyProductIds.add(NewProductList[i].Id);
                    }
                }
            }
        }
        
        Savepoint sp = Database.setSavepoint();
        List<Bureau_Product__c> bureauProductsList = [Select id,Item__r.Category__c,Item__c,Invoice_Only__c,Job__c
                                                      from Bureau_Product__c where id in :bureauProductIds];
        try{
            if(jobIds.size()>0)
            {
                List<Bureau_Rating__c> bureauRatingsList = [Select Id,Participant__r.Bureau_Job__c,Respondent__c FROM Bureau_Rating__c WHERE Participant__r.Bureau_Job__c IN :jobIds ORDER BY Participant__r.Bureau_Job__c];
                IF(bureauRatingsList.size()>0)
                {
                    Map<Id,List<Bureau_Rating__c>> bureauJobsMap = new Map<Id,List<Bureau_Rating__c>>();
                    List<Bureau_Rating__c> ratingsList;
                    for(Bureau_Rating__c bureauRating:bureauRatingsList)
                    {
                        if(bureauJobsMap.get(bureauRating.Participant__r.Bureau_Job__c)==null)
                        {
                            ratingsList = new List<Bureau_Rating__c>();
                            ratingsList.add(bureauRating);
                            bureauJobsMap.put(bureauRating.Participant__r.Bureau_Job__c,ratingsList);
                        }
                        else 
                            bureauJobsMap.get(bureauRating.Participant__r.Bureau_Job__c).add(bureauRating);
                        
                    }
                    List<Bureau_Rating_Progress__c> ratingProgressList = new List<Bureau_Rating_Progress__c>();
                    for(Bureau_Product__c bureauProduct: bureauProductsList)
                    {
                        if(bureauProduct.Invoice_Only__c==false)
                        {
                            for(Bureau_Rating__c bureauRating:bureauJobsMap.get(bureauProduct.Job__c))
                            {
                                if(bureauProduct.Item__r.Category__c == '360 Services')
                                {
                                    Bureau_Rating_Progress__c ratingProgress = new Bureau_Rating_Progress__c();
                                    ratingProgress.Bureau_Product__c = bureauProduct.id;
                                    ratingProgress.Bureau_Rating__c = bureauRating.id;
                                    ratingProgressList.add(ratingProgress);
                                }
                                else
                                {
                                    if(bureauRating.Participant__c == bureauRating.Respondent__c)
                                    {
                                        Bureau_Rating_Progress__c ratingProgress = new Bureau_Rating_Progress__c();
                                        ratingProgress.Bureau_Product__c = bureauProduct.id;
                                        ratingProgress.Bureau_Rating__c = bureauRating.id;
                                        ratingProgressList.add(ratingProgress);
                                    }
                                }
                            }
                        }
                    }
                    if(ratingProgressList.size()>0){
                        if(ratingProgressList.size()<8000){
                            insert ratingProgressList;
                        }else{
                            manageBureauRatingProgressInsert_Batch createBRP = new manageBureauRatingProgressInsert_Batch(ratingProgressList);
                            ID batchprocessid = Database.executeBatch(createBRP,500);
                        }
                    }
                }
            }
            
            if(invoiceOnlyProductIds.size()>0){
                List<Bureau_Rating_Progress__c> ratingProgressToBeDeleted = [SELECT Id FROM Bureau_Rating_Progress__c WHERE Bureau_Product__c IN:invoiceOnlyProductIds];
               // List<Bureau_Candidate_Score__c> candidateScoresTobeDeleted = [SELECT Id FROM Bureau_Candidate_Score__c WHERE Bureau_Product__c IN:invoiceOnlyProductIds];
                if(ratingProgressToBeDeleted.size()>0)
                    delete ratingProgressToBeDeleted;
             //if(candidateScoresTobeDeleted.size()>0)
               //     delete candidateScoresTobeDeleted; 
            }
            
        }catch(Exception e){
            DataBase.Rollback(sp);
            for(Integer i=0;i<NewProductList.size();i++)
                NewProductList[i].addError(e.getMessage());
        }
    }*/
}