objects/Bureau_Candidate__c.object
<CustomObject>
    <description>Managed Services module</description>
    <fields>
        <fullName>Bureau_Job__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Managed Services Job</label>
        <referenceTo>Job__c</referenceTo>
        <relationshipLabel>Managed Services Candidates</relationshipLabel>
        <relationshipName>Bureau_Candidates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Candidate_Unique_Id__c</fullName>
        <label>Candidate Unique Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Job_Region__c</fullName>
        <label>Job Region</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>China</fullName>
                </value>
                <value>
                    <fullName>Non China</fullName>
                </value>
                <value>
                    <fullName>Hong Kong</fullName>
                </value>
                <value>
                    <fullName>Singapore</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Managed Services Candidate</label>
    <nameField>
        <displayFormat>BC{000000000}</displayFormat>
        <label>Candidate Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Managed Services Candidates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Job__c.object
<CustomObject>
    <description>The entity used to identify a work request from a client to the Bureau.</description>
    <fields>
        <fullName>Job_Region__c</fullName>
        <label>Job Region</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>China</fullName>
                </value>
                <value>
                    <fullName>Non China</fullName>
                </value>
                <value>
                    <fullName>Hong Kong</fullName>
                </value>
                <value>
                    <fullName>Singapore</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Job</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Job Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/CandidateCreationController.cls
public with sharing class CandidateCreationController {
    
    @AuraEnabled
    public static void createCandidateRecords(List<Bureau_Candidate__c> candidateList){
        try {
            List<Bureau_Candidate__c> candidateListToInsert = new List<Bureau_Candidate__c>();
            Map<Id, Bureau_Candidate__c> candidateToInsertMap;
            Id jobRecordId = candidateList[0].Bureau_Job__c;
            String JobRegion = [select id,Job_Region__c from Job__c where id=:jobRecordId limit 1].Job_Region__c;
            for(Bureau_Candidate__c candidate : candidateList) {
                candidate.Candidate_Unique_Id__c = candidate.Bureau_Job__c + candidate.First_Name__c + candidate.Last_Name__c + candidate.Email__c;
                candidate.Job_Region__c = JobRegion;
                candidateListToInsert.add(candidate);
            }
            insert candidateListToInsert;
            candidateToInsertMap = new Map<Id, Bureau_Candidate__c>(candidateListToInsert);

            RollUpCandidateFields.calculateCountFields(candidateToInsertMap);
            RollUpCandidateFields.updateRollupSummaryFieldsOnJob(candidateListToInsert); //Changed by Shubham Singh
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}