objects/Bureau_Candidate__c.object
<CustomObject>
    <description>Managed Services module</description>
    <fields>
        <fullName>Bureau_Job__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Managed Services Job</label>
        <referenceTo>Job__c</referenceTo>
        <relationshipLabel>Managed Services Candidates</relationshipLabel>
        <relationshipName>Bureau_Candidates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Rater_Types__c</fullName>
        <formula>IF(Manager_Ratings__c&gt;0, &apos;Manager;&apos;,&apos;&apos;) 
+ IF(Peer_Ratings__c&gt;0, &apos;Peer;&apos;,&apos;&apos;)
+ IF(Subordinate_Ratings__c&gt;0, &apos;Subordinate;&apos;,&apos;&apos;)
+ IF(Customer_Ratings__c&gt;0, &apos;Customer;&apos;,&apos;&apos;)
+ IF(Client_Ratings__c&gt;0, &apos;Client;&apos;,&apos;&apos;)
+ IF(Other_Ratings__c&gt;0, &apos;Other&apos;,&apos;&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Rater Types</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sequence_No__c</fullName>
        <description>This field is meant for storing the sequence number of the candidate</description>
        <inlineHelpText>Sequence No of the candidiate</inlineHelpText>
        <label>Sequence No</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Managed Services Candidate</label>
    <nameField>
        <displayFormat>BC{000000000}</displayFormat>
        <label>Candidate Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Managed Services Candidates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/objects/Bureau_Candidate_Login__c.object
<CustomObject>
    <description>Bureau module</description>
    <fields>
        <fullName>Bureau_Candidate__c</fullName>
        <description>This field represents the Candidate to which this Candidate Login belongs</description>
        <inlineHelpText>Select the Candidate to which this Candidate Login belongs</inlineHelpText>
        <label>Managed Services Candidate</label>
        <referenceTo>Bureau_Candidate__c</referenceTo>
        <relationshipLabel>Managed Services Candidate Logins</relationshipLabel>
        <relationshipName>Bureau_Candidate_Logins</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Bureau_System__c</fullName>
        <description>This field represents the Bureau System to which this Candidate Login belongs</description>
        <inlineHelpText>Select  the Bureau System to which this Candidate Login belongs</inlineHelpText>
        <label>Managed Services System</label>
        <referenceTo>Bureau_System__c</referenceTo>
        <relationshipLabel>Managed Services Candidate Logins</relationshipLabel>
        <relationshipName>Bureau_Candidate_Logins</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Password__c</fullName>
        <label>Password</label>
        <length>50</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
    <label>Managed Services Candidate Login</label>
    <nameField>
        <displayFormat>BCL{0000000000}</displayFormat>
        <label>Managed Services Candidate Login Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Managed Services Candidate Logins</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/objects/Bureau_Rating__c.object
<CustomObject>
    <description>This object represents a self rating or a respondent rating for a Bureau Project Job.</description>
    <fields>
        <fullName>Bureau_Job__c</fullName>
        <formula>CASESAFEID(Participant__r.Bureau_Job__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Managed Services_Job</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rater_Type__c</fullName>
        <label>Rater Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Self</fullName>
                </value>
                <value>
                    <fullName>Manager</fullName>
                </value>
                <value>
                    <fullName>Colleagues</fullName>
                </value>
                <value>
                    <fullName>Others</fullName>
                </value>
                <value>
                    <fullName>Direct Reports</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Respondent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field represents the Bureau Candidate who shall acting as a respondent and shall be rating the Participant.</description>
        <inlineHelpText>Specify the Candidate who shall be rating the Participant</inlineHelpText>
        <label>Respondent</label>
        <referenceTo>Bureau_Candidate__c</referenceTo>
        <relationshipName>Bureau_Ratings_As_Respondent</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Managed Services Rating</label>
    <nameField>
        <displayFormat>BR{000000000}</displayFormat>
        <label>Rating Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Managed Services Ratings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/objects/Bureau_System__c.object
<CustomObject>
    <description>This object represents a relation between a Bureau Job and a System.</description>
    <fields>
        <fullName>Bureau_Job__c</fullName>
        <description>This field represents the Bureau Job to which is the parent of this record.</description>
        <label>Managed Services Job</label>
        <referenceTo>Job__c</referenceTo>
        <relationshipLabel>Managed Services Systems</relationshipLabel>
        <relationshipName>Bureau_Systems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Managed Services System</label>
    <nameField>
        <displayFormat>BJS{000000}</displayFormat>
        <label>Managed Services System Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Managed Services Systems</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Job__c.object
<CustomObject>
    <description>The entity used to identify a work request from a client to the Bureau.</description>
    <fields>
        <fullName>Candidate_Max_Sequence_No_New__c</fullName>
        <description>&quot;This field is created on the place of old Candidate Max Sequence field while Relationship conversion. 
Number of Candidates uploaded on Job.&quot;</description>
        <label>Number of Candidates</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Candidate_Username_Prefix__c</fullName>
        <description>This field is meant for specifying a 4-character text that shall be used as a prefix of the usernames generated for the candidates of a Job.</description>
        <inlineHelpText>Specify the username prefix for all candidates of this Job.</inlineHelpText>
        <label>Candidate Username Prefix</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rater_Types__c</fullName>
        <description>This field represents the rater types used in the Job ratings</description>
        <inlineHelpText>These are the Rater Types used in this Job&apos;s ratings</inlineHelpText>
        <label>Rater Types</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Job</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Job Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/BureauCandidateTriggerManager_1.cls
/**************************************************************************************************************************************
CREATED BY :- RISHABH KANOTRA
CREATED DATE :- 25-07-2019
DESCRIPTION :- This class contains various validations and functionality to modify Bureau_Candidate__c and its fields refered from Bureau_Candidate triggers : before Insert,after Update,after Insert, after Delete
***************************************************************************************************************************************/ 
 
Global class BureauCandidateTriggerManager_1 {
    
    global BureauCandidateTriggerManager_1(){
        
    }
        //Commented class as for MS Lex Migration.
        //1.Delete all such ratings where candidates are Respondents 
      /*  public static void afterBureauCandidateDelete(List<Bureau_Candidate__c> oldCandidate){       
        
            Set<Id> candidateIds = new Set<Id>();
            Set<Id> jobIds = new Set<Id>();
            for(Bureau_Candidate__c candidate: oldCandidate)
            {
                candidateIds.add(candidate.Id);
                if(!jobIds.contains(candidate.Bureau_Job__c))
                jobIds.add(candidate.Bureau_Job__c);
            }    
            
            //Fetch the list of ratings where these candidates are Respondents    
            List<Bureau_Rating__c> ratingsAsRespondent = [SELECT Id FROM Bureau_Rating__c WHERE Rater_Type__c<>'Self' AND Respondent__c IN:candidateIds]; 
            
            //Delete all such ratings where these candidates are Respondents 
            if(ratingsAsRespondent.size()>0)
                delete ratingsAsRespondent;
            
            BureauJob_Manager.refreshRaterTypes(jobIds);
        
        }//afterBureauCandidateDelete
        
        //1.If Rater_Types__c is changed then refresh RaterTypes of Job__c
        public static void afterBureauCandidateUpdate(List<Bureau_Candidate__c> oldCandidate, List<Bureau_Candidate__c> newCandidate){ 
            
            Set<Id> jobIds = new Set<Id>();
            for(Integer i=0; i<newCandidate.size(); i++)
            {
                if(!jobIds.contains(newCandidate[i].Bureau_Job__c))
                {
                    if(newCandidate[i].Rater_Types__c<>oldCandidate[i].Rater_Types__c)
                        jobIds.add(newCandidate[i].Bureau_Job__c);
                }
            }  
            
            if(jobIds.size()>0)
            BureauJob_Manager.refreshRaterTypes(jobIds);
        
        
        }//afterBureauCandidateUpdate
        
        //1.Updating 'Sequence_No__c' of the candidate using 'Candidate_Max_Sequence_No_New__c' field.
        public static void beforeBureauCandidateInsert(List<Bureau_Candidate__c> newCandidate){ 
            // Set<Id> jobIds = new Set<Id>();
            // for(Bureau_Candidate__c candidate: newCandidate)
            // {
            //     if(!jobIds.contains(candidate.Bureau_Job__c))
            //     jobIds.add(candidate.Bureau_Job__c);
            // }

            // List<Job__c> jobsList = [SELECT Id, Candidate_Max_Sequence_No_New__c FROM Job__c WHERE Id IN:jobIds];
            // Map<Id, Decimal> jobsMap = new Map<Id, Decimal>();
            // for(Job__c job: jobsList)
            //     jobsMap.put(job.Id, job.Candidate_Max_Sequence_No_New__c );
            
            // for(Bureau_Candidate__c candidate: newCandidate)
            // {
            //     Decimal maxSequenceNo = jobsMap.get(candidate.Bureau_Job__c);
            //     candidate.Sequence_No__c = maxSequenceNo==null?1:maxSequenceNo + 1;
            //     jobsMap.put(candidate.Bureau_Job__c,candidate.Sequence_No__c);
            // }
            
            Map<Id, Integer> jobIdVsCandidateCount = new Map<Id, Integer>();
            Set<Id> jobIdSet = new Set<Id>();

            for(Bureau_Candidate__c candidate: newCandidate)
            {
                if(String.isNotEmpty(candidate.Bureau_Job__c))
                jobIdSet.add(candidate.Bureau_Job__c);
            }

            for(AggregateResult groupedResults : [SELECT COUNT(Id) Candidate_Count, Bureau_Job__c From Bureau_Candidate__c WHERE Bureau_Job__c IN :jobIdSet GROUP BY Bureau_Job__c]) {
                jobIdVsCandidateCount.put((Id) groupedResults.get('Bureau_Job__c'), (Integer) groupedResults.get('Candidate_Count'));
            }
            
            for(Bureau_Candidate__c candidate: newCandidate)
            {
                Integer maxSequenceNo = jobIdVsCandidateCount.get(candidate.Bureau_Job__c);
                candidate.Sequence_No__c = maxSequenceNo==null?1:maxSequenceNo + 1;
                jobIdVsCandidateCount.put(candidate.Bureau_Job__c,Integer.valueOf(candidate.Sequence_No__c));
            }
         
        }//beforeBureauCandidateInsert
        
        //1.Update 'Bureau_Candidate_Login__c' fields - 1.Bureau_Candidate__c 2.Bureau_System__c 3.Password__c
        //2.Using apex class 'BureauJob_Manager' refresh RaterTypes of Job__c.
        public static void afterBureauCandidateInsert(List<Bureau_Candidate__c> newCandidate){ 
        
            Set<Id> jobIds = new Set<Id>();
            for(Bureau_Candidate__c candidate: newCandidate)
            {
                if(!jobIds.contains(candidate.Bureau_Job__c))
                jobIds.add(candidate.Bureau_Job__c);
            }
            Map<Id,Job__c> jobMap = new Map<Id,Job__c>([SELECT Id,Name,Candidate_Username_Prefix__c,(SELECT Id, Name FROM Bureau_Systems__r) FROM Job__c WHERE Id IN:jobIds]);
            
            List<Bureau_Candidate_Login__c> candidateLogins = new List<Bureau_Candidate_Login__c>();
            for(Bureau_Candidate__c candidate: newCandidate)
            {
                Job__c job = jobMap.get(candidate.Bureau_Job__c);
                List<Bureau_System__c> systemsUsed = job.Bureau_Systems__r;
                for(Bureau_System__c systemUsed: systemsUsed)
                {
                    Bureau_Candidate_Login__c candidateLogin = new Bureau_Candidate_Login__c();
                    candidateLogin.Bureau_Candidate__c = candidate.Id;
                    candidateLogin.Bureau_System__c = systemUsed.Id;
                    candidateLogin.Password__c = EncodingUtil.convertToHex(crypto.generateAesKey(128)).substring(0,8).replace('0','h').replace('1','i').replace('2','j').replace('3','k').replace('4','l').replace('5','m').replace('6','n').replace('7','o').replace('8','p').replace('9','q');        
                    candidateLogins.add(candidateLogin);
                }
            }
            insert candidateLogins;
            
            BureauJob_Manager.refreshRaterTypes(jobIds);
        
        }//afterBureauCandidateInsert */
   
   }//BureauCandidateTriggerManager_1