objects/Bureau_Candidate__c.object
<CustomObject>
    <description>Managed Services module</description>
    <fields>
        <fullName>Bureau_Job__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Managed Services Job</label>
        <referenceTo>Job__c</referenceTo>
        <relationshipLabel>Managed Services Candidates</relationshipLabel>
        <relationshipName>Bureau_Candidates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Work_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Work Request</label>
        <referenceTo>Work_Request__c</referenceTo>
        <relationshipLabel>Managed Services Candidates</relationshipLabel>
        <relationshipName>Managed_Services_Candidates</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Managed Services Candidate</label>
    <nameField>
        <displayFormat>BC{000000000}</displayFormat>
        <label>Candidate Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Managed Services Candidates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/objects/Bureau_Rating__c.object
<CustomObject>
    <description>This object represents a self rating or a respondent rating for a Bureau Project Job.</description>
    <fields>
        <fullName>Bureau_Job__c</fullName>
        <formula>CASESAFEID(Participant__r.Bureau_Job__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Managed Services_Job</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MFS_Status__c</fullName>
        <label>MFS Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Ready to Submit</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Participant_Name__c</fullName>
        <description>This field is used to capture Candidate Name where Category is Self</description>
        <formula>Participant__r.Full_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Participant Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Participant__c</fullName>
        <description>This field represents the Bureau Candidate who shall be acting as a participant and shall be rated by the Respondent.</description>
        <inlineHelpText>Specify the Bureau Candidate to be rated</inlineHelpText>
        <label>Participant</label>
        <referenceTo>Bureau_Candidate__c</referenceTo>
        <relationshipName>Bureau_Ratings_As_Participant</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Rater_String__c</fullName>
        <label>Rater String</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Rater_Type__c</fullName>
        <label>Rater Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Self</fullName>
                </value>
                <value>
                    <fullName>Manager</fullName>
                </value>
                <value>
                    <fullName>Colleagues</fullName>
                </value>
                <value>
                    <fullName>Others</fullName>
                </value>
                <value>
                    <fullName>Direct Reports</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Rating_Transfer_Status__c</fullName>
        <defaultValue>&quot;Not Transferred&quot;</defaultValue>
        <description>This field is created to store the transfer status of rating. Transfer is related FTP</description>
        <label>Rating Transfer Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Transferred</fullName>
                </value>
                <value>
                    <fullName>Transferred</fullName>
                </value>
                <value>
                    <fullName>Updated from FTP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Reminder_1__c</fullName>
        <label>Reminder 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Report_Ready__c</fullName>
        <label>Report Ready</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Ready</fullName>
                    <default>true</default>
                    <label>Not Ready</label>
                </value>
                <value>
                    <fullName>Can be Generated</fullName>
                </value>
                <value>
                    <fullName>Can not be generated</fullName>
                </value>
                <value>
                    <fullName>100% Completed</fullName>
                </value>
                <value>
                    <fullName>Data Insufficient</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Respondent_Name__c</fullName>
        <description>This field is used to capture Candidate Name where Category is not Self</description>
        <formula>Respondent__r.Full_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Respondent Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Respondent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field represents the Bureau Candidate who shall acting as a respondent and shall be rating the Participant.</description>
        <inlineHelpText>Specify the Candidate who shall be rating the Participant</inlineHelpText>
        <label>Respondent</label>
        <referenceTo>Bureau_Candidate__c</referenceTo>
        <relationshipName>Bureau_Ratings_As_Respondent</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Work_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is created to link Rating with Work Request</description>
        <label>Work Request</label>
        <referenceTo>Work_Request__c</referenceTo>
        <relationshipLabel>Managed Services Ratings</relationshipLabel>
        <relationshipName>Managed_Services_Ratings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Managed Services Rating</label>
    <nameField>
        <displayFormat>BR{000000000}</displayFormat>
        <label>Rating Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Managed Services Ratings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>Bureau_Job__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Select the Bureau Job Number if relevant</inlineHelpText>
        <label>Job</label>
        <referenceTo>Job__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

objects/Job__c.object
<CustomObject>
    <description>The entity used to identify a work request from a client to the Bureau.</description>
    <fields>
        <fullName>Status_Calculations__c</fullName>
        <description>This field stores the json for the different status calculations, it is created for backend use.</description>
        <label>Status Calculations</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Job</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Job Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Work_Request__c.object
<CustomObject>
    <description>Module to store work request generated by managed services team and submitted by client back to managed services team</description>
    <fields>
        <fullName>Job__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>System Use: To link job from where the work requests will be processed</description>
        <inlineHelpText>System Use: To link job from where the work requests will be processed</inlineHelpText>
        <label>Job</label>
        <referenceTo>Job__c</referenceTo>
        <relationshipLabel>Work Requests Submitted</relationshipLabel>
        <relationshipName>Work_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Work Request</label>
    <nameField>
        <displayFormat>WR-{0000}</displayFormat>
        <label>Work Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Requests</pluralLabel>
    <recordTypes>
        <fullName>Submitted</fullName>
        <active>true</active>
        <description>To mark records as Generated which are MS submitted on behalf fof client or directly submitted by client.</description>
        <label>Submitted</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CalculateRatingsFieldBatch.cls
global class CalculateRatingsFieldBatch implements Database.Batchable<sObject>, Database.Stateful {
    private String wrfId;
    private String wrfName;
    private list<String> errors = new list<String>();
    public Map<String, String> raterStringMap = new Map<String, String>();
    public String jobId;
    public Map<Id, Integer> respondentCountMap = new Map<Id, Integer>();
    
    public CalculateRatingsFieldBatch(String wrfId, String wrfNumber, String jobId) {
        this.wrfId = wrfId;
        this.wrfName = wrfNumber;
        this.jobId = jobId;
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        //SSE-28262 Updated query to get Ratings linked to current WRf only 
        String query = 'SELECT Id, Rater_String__c, Reminder_1__c, Report_Ready__c, ' +
                   'Participant_Name__c, Respondent_Name__c, Rater_Type__c, MFS_Status__c, ' +
                   'Participant__r.Bureau_Job__c, Participant__r.Email__c, Respondent__r.Email__c, Rating_Transfer_Status__c ' +
                   'FROM Bureau_Rating__c ' +
            	   'WHERE Work_Request__c = \'' + String.escapeSingleQuotes(this.wrfId) + '\' ';
        
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<Bureau_Rating__c> ratingList) {  
        System.debug('rating list size --> '+ratingList.size());
        if (!ratingList.isEmpty()) {
            List<Bureau_Rating__c> otherRatingList = new List<Bureau_Rating__c>();
            List<Bureau_Rating__c> selfRatingList = new List<Bureau_Rating__c>();
            Map<String, String> participantEmailNameMap = new Map<String, String>();
            
            jobId = ratingList[0].Participant__r.Bureau_Job__c;
            System.debug('Execute jobId '+jobId);
            for(Bureau_Rating__c rating : ratingList){
                participantEmailNameMap.put(rating.Participant__r.Email__c, rating.Participant_Name__c);
            }
            
            for(Bureau_Rating__c rating : ratingList){
                rating.Reminder_1__c ='Eligible';
                if (rating.Rater_Type__c != 'Self') {
                    if (rating.MFS_Status__c != 'Completed') {
                        String respondentEmail = rating.Respondent__r.Email__c.toLowerCase();
                        if (!raterStringMap.containsKey(respondentEmail)) {
                            raterStringMap.put(respondentEmail, participantEmailNameMap.get(rating.Participant__r.Email__c));
                        } else {
                            String oldValue = raterStringMap.get(respondentEmail);
                            if(oldValue == ''){
                                raterStringMap.put(respondentEmail, participantEmailNameMap.get(rating.Participant__r.Email__c));
                            }else{
                                raterStringMap.put(respondentEmail, oldValue + ', ' + participantEmailNameMap.get(rating.Participant__r.Email__c));
                            }
                        }
                    }
                    
                }
                if (rating.Rater_Type__c == 'Self') {
                    selfRatingList.add(rating);
                }
                if(rating.Rater_Type__c != 'Self') {
                    otherRatingList.add(rating);
                }
                
            }
            for(Bureau_Rating__c rating : otherRatingList){
                rating.Rater_String__c = raterStringMap.get(rating.Respondent__r.Email__c.toLowerCase());
            }
            
            if(!selfRatingList.isEmpty()){
                List<Database.SaveResult> ratingResults = Database.update(selfRatingList, false);
                for(Database.SaveResult sr : ratingResults) {
                    if(!sr.isSuccess()){               
                        list<Database.Error> err = sr.getErrors();
                        errors.add(err[0].getStatusCode() + ': ' + err[0].getMessage());
                    }
                }
            }
            if(!otherRatingList.isEmpty()){
                List<Database.SaveResult> ratingResults1 = Database.update(otherRatingList, false);
                for(Database.SaveResult sr : ratingResults1) {
                    if(!sr.isSuccess()){               
                        list<Database.Error> err = sr.getErrors();
                        errors.add(err[0].getStatusCode() + ': ' + err[0].getMessage());
                    }
                }
            }   
            //SSE-28262 Calculates the number of Rating records where the Candidate is listed as the Respondent. 
            //Update Respondent Count field on Candidate.
            RollUpCandidateFields.calculateRespondentCountOnCandidate(ratingList);
            //Calculate Not Transferred Rating Count and Candidate Transfer Status on Job
            RollUpCandidateFields.updateTransferCountonJobOnNewWorkRequest(ratingList);  
            
        }
    }   
    
    global void finish(Database.BatchableContext BC) {
        String errorBody;
        String subjectBody;
        
        if(!errors.isEmpty()) {
            subjectBody='Errors Occurred While computing ratings';
            errorBody='Updation failed, some error has occured. Rating updation related to Work Request Number:'+wrfName+' is failing because of following errors mentioned below:'+'<br/>';
            for(String error : errors ){errorBody += error + '<br/>';}
        }else{
            /* Commenting below code as it is added in CandidateBulkUploadBatch and 
             * we are calling CandidateBulkUploadBatch batch class below
		     * to fix Number of Respondent count on job when only a respondent is submitted 
			 * through WRF in case of duplicates in SHL 360/ MFS. (SSE-26836) 
			*/
            /*if(!Test.isRunningTest()){
                String json = RollUpCandidateFields.updateStatusCalculations(jobId);
                Job__c job = new Job__c();job.id = jobId;job.Status_Calculations__c = json;update job;
            }*/
            
            subjectBody='Rating Updation Completed Successfully';
            errorBody='The Rating updation process is completed successfully. All Ratings related to Work Request Number:'+wrfName+' are updated.';
        }
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        mail.setSubject(subjectBody);
        mail.setTargetObjectId(UserInfo.getUserId());
        mail.setSaveAsActivity(false);
        mail.setHtmlBody(errorBody);
        Messaging.sendEmail(new Messaging.Email[] { mail });
        System.debug('Finish jobId '+jobId);
        /* Added below batch job call to fix Respondent count in case of duplicates for MFS (SSE-26836) */
        CandidateBulkUploadBatch candidatebatch= new CandidateBulkUploadBatch(jobId,'insert','Bureau_Candidate__c');
        Database.executeBatch(candidatebatch, 2000);
    }
}