objects/Bureau_Item_Master__c.object
<CustomObject>
    <description>This object represents an Item such as Instrument, Report or Service.</description>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Online Admin</fullName>
                </value>
                <value>
                    <fullName>S2P Solutions</fullName>
                </value>
                <value>
                    <fullName>Online Reports</fullName>
                </value>
                <value>
                    <fullName>S2P Tests (a – d)</fullName>
                </value>
                <value>
                    <fullName>Gradu8</fullName>
                </value>
                <value>
                    <fullName>S2P Tests (d – f)</fullName>
                </value>
                <value>
                    <fullName>Online - PJM/WPS/JCF/OCP</fullName>
                </value>
                <value>
                    <fullName>S2P Tests (g – j)</fullName>
                </value>
                <value>
                    <fullName>Offline Scoring</fullName>
                </value>
                <value>
                    <fullName>S2P Tests (k – n)</fullName>
                </value>
                <value>
                    <fullName>360 Services</fullName>
                </value>
                <value>
                    <fullName>S2P Tests (o – r)</fullName>
                </value>
                <value>
                    <fullName>Offline Reports</fullName>
                </value>
                <value>
                    <fullName>S2P Tests (s – v)</fullName>
                </value>
                <value>
                    <fullName>Managed Services</fullName>
                </value>
                <value>
                    <fullName>S2P Tests (w – z)</fullName>
                </value>
                <value>
                    <fullName>Offline - PJM/WPS/JCF/OCP</fullName>
                </value>
                <value>
                    <fullName>Previsor Products</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Item</label>
    <nameField>
        <label>Managed Services Item Master Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <recordTypes>
        <fullName>Instrument</fullName>
        <active>true</active>
        <description>This record type defines the Bureau Item as an Instrument</description>
        <label>Instrument</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/objects/Bureau_Product__c.object
<CustomObject>
    <description>To link to the Job object for OLB jobs</description>
    <fields>
        <fullName>Category__c</fullName>
        <description>Instrument or Report</description>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Express Service</fullName>
                </value>
                <value>
                    <fullName>Instrument</fullName>
                </value>
                <value>
                    <fullName>Report</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Item</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Bureau_Item_Master__c.Type__c</field>
                <operation>equals</operation>
                <valueField>$Source.Category__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Bureau_Item_Master__c</referenceTo>
        <relationshipName>Bureau_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Job__c</fullName>
        <label>Job</label>
        <referenceTo>Job__c</referenceTo>
        <relationshipName>Bureau_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Managed Services Product</label>
    <nameField>
        <displayFormat>BProd{00000}</displayFormat>
        <label>Managed Services Product</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Managed Services Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/objects/Bureau_Rating__c.object
<CustomObject>
    <description>This object represents a self rating or a respondent rating for a Bureau Project Job.</description>
    <fields>
        <fullName>Bureau_Job__c</fullName>
        <formula>CASESAFEID(Participant__r.Bureau_Job__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Managed Services_Job</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Participant__c</fullName>
        <description>This field represents the Bureau Candidate who shall be acting as a participant and shall be rated by the Respondent.</description>
        <inlineHelpText>Specify the Bureau Candidate to be rated</inlineHelpText>
        <label>Participant</label>
        <referenceTo>Bureau_Candidate__c</referenceTo>
        <relationshipName>Bureau_Ratings_As_Participant</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Respondent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field represents the Bureau Candidate who shall acting as a respondent and shall be rating the Participant.</description>
        <inlineHelpText>Specify the Candidate who shall be rating the Participant</inlineHelpText>
        <label>Respondent</label>
        <referenceTo>Bureau_Candidate__c</referenceTo>
        <relationshipName>Bureau_Ratings_As_Respondent</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>This field represents the Status of the Rating</description>
        <formula>IF(Total_Instruments__c== Instruments_Completed__c,&quot;Completed&quot;,IF(Instruments_Completed__c&gt;0 || Instruments_In_Progress__c&gt;0,&quot;In Progress&quot;, &quot;Not Started&quot;))</formula>
        <inlineHelpText>This is the current status of the Rating</inlineHelpText>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <label>Managed Services Rating</label>
    <nameField>
        <displayFormat>BR{000000000}</displayFormat>
        <label>Rating Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Managed Services Ratings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/objects/Bureau_Rating_Progress__c.object
<CustomObject>
    <description>Bureau module</description>
    <fields>
        <fullName>Bureau_Product__c</fullName>
        <label>Managed Services Product</label>
        <referenceTo>Bureau_Product__c</referenceTo>
        <relationshipLabel>Managed Services Ratings Progress</relationshipLabel>
        <relationshipName>Bureau_Ratings_Progresss</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Bureau_Rating__c</fullName>
        <label>Managed Services Rating</label>
        <referenceTo>Bureau_Rating__c</referenceTo>
        <relationshipLabel>Managed Services Ratings Progress</relationshipLabel>
        <relationshipName>Bureau_Ratings_Progress</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Rater__c</fullName>
        <formula>Bureau_Rating__r.Respondent__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Rater</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                    <default>true</default>
                    <label>Not Started</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Managed Services Rating Progress</label>
    <nameField>
        <displayFormat>BRP{0000000000}</displayFormat>
        <label>Rating Progress Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Managed Services Ratings Progress</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Job__c.object
<CustomObject>
    <description>The entity used to identify a work request from a client to the Bureau.</description>
    <label>Job</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Job Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/MS_RatingTriggerManager.cls
/*****************************************************************************
CREATED BY :- Prabhat Arora
CREATED DATE :- 21-08-2019
DESCRIPTION :- This class contains Methods to create Rating Progress in context to MS Rating Functionality as per SHL business process,
               this class is being refered from MS_Rating_Trigger, covering the After Insert Events on MS Rating Records. 
******************************************************************************/

Global class MS_RatingTriggerManager{
    
    global MS_RatingTriggerManager(){
        
    }
    //Commented By : Pallavi Jadhav
    //Reason: deprecate Rating Progress
    //Reference: SSE-18140
    /*Public static void CreateRatingProgress(List<Bureau_Rating__c> NewRatingList){
        //Create a set of Respondent Ids of the inserted ratings
        Set<Id> respondentIds = new Set<Id>();
        for(Bureau_Rating__c rating:NewRatingList)
        {
            if(!respondentIds.contains(rating.Respondent__c))
                respondentIds.add(rating.Respondent__c);
        }
        
        //Initiate a Job map that shall be used to get the Job instruments if required.  
        Map<Id, Job__c> jobMap = new Map<Id, Job__c>();
        
        //Create a map of candidates with the set of instrument ids selected for that candidate 
        Map<Id, Set<Id>> respondentsMap = new Map<Id, Set<Id>>();
        
        if(respondentIds.size()>0){
            for(Bureau_Rating_Progress__c existingRatingProgress: [SELECT Id,Rater__c,Bureau_Product__c FROM Bureau_Rating_Progress__c WHERE Rater__c IN :respondentIds ORDER BY Rater__c])
            {
                if(!respondentsMap.containsKey(existingRatingProgress.Rater__c))
                    respondentsMap.put(existingRatingProgress.Rater__c,new Set<Id>());
                Set<Id> instrumentIds = respondentsMap.get(existingRatingProgress.Rater__c);
                if(!instrumentIds.contains(existingRatingProgress.Bureau_Product__c))
                    instrumentIds.add(existingRatingProgress.Bureau_Product__c);
            }
        }
        
        //Initiate a list of rating progress records to be created
        List<Bureau_Rating_Progress__c> ratingsProgressToBeCreated = new List<Bureau_Rating_Progress__c>();
        
        //Loop through each inserted rating and create a rating progress record for each instrument selected for the rating's respondent
        
        Set<Id> allInstrumentsIdsSet = new set<Id>();
        for(Bureau_Rating__c rating:NewRatingList)
        {
            //Get the instruments selected for the current rating's respondent from the respondents map
            Set<Id> respondentInstrumentIds = respondentsMap.get(rating.Respondent__c);
            
            //If there are no instruments selected for the current rating's respondent
            if(respondentInstrumentIds==null)
            {
                //If the rating's Job doesn't exist in the Job map, then fetch the Job along with its instruments
                if(!jobMap.containsKey(rating.Bureau_Job__c))
                    jobMap.put(rating.Bureau_Job__c,[SELECT Id,(SELECT Id FROM Bureau_Products__r WHERE Category__c='Instrument') FROM Job__c WHERE Id=:rating.Bureau_Job__c]); 
                
                //Get the instruments for the Job
                List<Bureau_Product__c> respondentInstruments = jobMap.get(rating.Bureau_Job__c).Bureau_Products__r;
                respondentInstrumentIds =  new Set<Id>();
                for(Bureau_Product__c instrument: respondentInstruments)
                    respondentInstrumentIds.add(instrument.Id);
            }
            allInstrumentsIdsSet.addAll(respondentInstrumentIds);
        }
        Map<Id,Boolean> isInstrument360 = new Map<Id,Boolean>();
        if(allInstrumentsIdsSet.size()>0){
            for(Bureau_Product__c bProduct:[SELECT Id,Item__r.Category__c,Item__c FROM Bureau_Product__c WHERE Category__c ='Instrument' and id in :allInstrumentsIdsSet])
            {
                if(bProduct.Item__r.Category__c == '360 Services')
                    isInstrument360.put(bProduct.id,true);
                else
                    isInstrument360.put(bProduct.id,false);
            }
        }
        for(Bureau_Rating__c rating:NewRatingList)
        {   
            
            //Get the instruments selected for the current rating's respondent from the respondents map
            Set<Id> respondentInstrumentIds = respondentsMap.get(rating.Respondent__c);
            
            //If there are no instruments selected for the current rating's respondent
            if(respondentInstrumentIds==null)
            {
                List<Bureau_Product__c> respondentInstruments = jobMap.get(rating.Bureau_Job__c).Bureau_Products__r;
                respondentInstrumentIds =  new Set<Id>();
                for(Bureau_Product__c instrument: respondentInstruments)
                    respondentInstrumentIds.add(instrument.Id);
            }
            //Add a rating for each instrument of the Job
            for(Id instrumentId: respondentInstrumentIds)
            {
                if(isInstrument360.get(instrumentId))
                {
                    Bureau_Rating_Progress__c ratingProgress = new Bureau_Rating_Progress__c();
                    ratingProgress.Bureau_Rating__c = rating.Id;
                    ratingProgress.Bureau_Product__c = instrumentId;
                    ratingProgress.Status__c = 'Not Started';
                    ratingsProgressToBeCreated.add(ratingProgress);
                }
                else
                {
                    if(rating.Participant__c == rating.Respondent__c)
                    {
                        Bureau_Rating_Progress__c ratingProgress = new Bureau_Rating_Progress__c();
                        ratingProgress.Bureau_Rating__c = rating.Id;
                        ratingProgress.Bureau_Product__c = instrumentId;
                        ratingProgress.Status__c = 'Not Started';
                        ratingsProgressToBeCreated.add(ratingProgress);
                    }
                }
            }
        }
        
        insert ratingsProgressToBeCreated;
    }*/
}