objects/Bureau_Candidate__c.object
<CustomObject>
    <description>Managed Services module</description>
    <fields>
        <fullName>Bureau_Job__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Managed Services Job</label>
        <referenceTo>Job__c</referenceTo>
        <relationshipLabel>Managed Services Candidates</relationshipLabel>
        <relationshipName>Bureau_Candidates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <label>Managed Services Candidate</label>
    <nameField>
        <displayFormat>BC{000000000}</displayFormat>
        <label>Candidate Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Managed Services Candidates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/objects/Bureau_Rating__c.object
<CustomObject>
    <description>This object represents a self rating or a respondent rating for a Bureau Project Job.</description>
    <fields>
        <fullName>Bureau_Job__c</fullName>
        <formula>CASESAFEID(Participant__r.Bureau_Job__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Managed Services_Job</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MFS_Report_Sent__c</fullName>
        <inlineHelpText>To capture the status of MFS platform report sent to customer.</inlineHelpText>
        <label>MFS Report Sent</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Sent</fullName>
                </value>
                <value>
                    <fullName>Sent</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MFS_Status__c</fullName>
        <label>MFS Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Ready to Submit</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Overall_Status__c</fullName>
        <formula>if(TEXT(MFS_Status__c) = null &amp;&amp; TEXT(TC_Status__c)= null,null,
if(TEXT(MFS_Status__c)!= null &amp;&amp; TEXT(TC_Status__c)= null,TEXT(MFS_Status__c),
If(TEXT(MFS_Status__c)= null &amp;&amp; TEXT(TC_Status__c)!= null,TEXT(TC_Status__c),
if(TEXT(MFS_Status__c)= &apos;Not Started&apos; &amp;&amp; TEXT(TC_Status__c)= &apos;Not Started&apos;,&apos;Not Started&apos;,
if(TEXT(MFS_Status__c)= &apos;Not Started&apos; &amp;&amp; TEXT(TC_Status__c)= &apos;In Progress&apos;,&apos;In Progress&apos;,
if(TEXT(MFS_Status__c)= &apos;Not Started&apos; &amp;&amp; TEXT(TC_Status__c)= &apos;Completed&apos;,&apos;In Progress&apos;,
if(TEXT(MFS_Status__c)= &apos;In Progress&apos; &amp;&amp; TEXT(TC_Status__c)= &apos;Not Started&apos;,&apos;In Progress&apos;,
if(TEXT(MFS_Status__c)= &apos;In Progress&apos; &amp;&amp; TEXT(TC_Status__c)= &apos;In Progress&apos;,&apos;In Progress&apos;,
if(TEXT(MFS_Status__c)= &apos;In Progress&apos; &amp;&amp; TEXT(TC_Status__c)= &apos;Completed&apos;,&apos;In Progress&apos;,
if(TEXT(MFS_Status__c)= &apos;Ready to Submit&apos; &amp;&amp; TEXT(TC_Status__c)= &apos;Not Started&apos;,&apos;In Progress&apos;,
if(TEXT(MFS_Status__c)= &apos;Ready to Submit&apos; &amp;&amp; TEXT(TC_Status__c)= &apos;In Progress&apos;,&apos;In Progress&apos;,
if(TEXT(MFS_Status__c)= &apos;Ready to Submit&apos; &amp;&amp; TEXT(TC_Status__c)= &apos;Completed&apos;,&apos;Ready to Submit&apos;,
if(TEXT(MFS_Status__c)= &apos;Completed&apos; &amp;&amp; TEXT(TC_Status__c)= &apos;Not Started&apos;,&apos;In Progress&apos;,
if(TEXT(MFS_Status__c)= &apos;Completed&apos; &amp;&amp; TEXT(TC_Status__c)= &apos;In Progress&apos;,&apos;In Progress&apos;,
if(TEXT(MFS_Status__c)= &apos;Completed&apos; &amp;&amp; TEXT(TC_Status__c)= &apos;Completed&apos;,&apos;Completed&apos;,null))))))))))))))
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Overall Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Participant_Name__c</fullName>
        <description>This field is used to capture Candidate Name where Category is Self</description>
        <formula>Participant__r.Full_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Participant Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Participant__c</fullName>
        <description>This field represents the Bureau Candidate who shall be acting as a participant and shall be rated by the Respondent.</description>
        <inlineHelpText>Specify the Bureau Candidate to be rated</inlineHelpText>
        <label>Participant</label>
        <referenceTo>Bureau_Candidate__c</referenceTo>
        <relationshipName>Bureau_Ratings_As_Participant</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Rater_String__c</fullName>
        <label>Rater String</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Rater_Type__c</fullName>
        <label>Rater Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Self</fullName>
                </value>
                <value>
                    <fullName>Manager</fullName>
                </value>
                <value>
                    <fullName>Colleagues</fullName>
                </value>
                <value>
                    <fullName>Others</fullName>
                </value>
                <value>
                    <fullName>Direct Reports</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Reminder_1__c</fullName>
        <label>Reminder 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Report_Ready__c</fullName>
        <label>Report Ready</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Ready</fullName>
                    <default>true</default>
                    <label>Not Ready</label>
                </value>
                <value>
                    <fullName>Can be Generated</fullName>
                </value>
                <value>
                    <fullName>Can not be generated</fullName>
                </value>
                <value>
                    <fullName>100% Completed</fullName>
                </value>
                <value>
                    <fullName>Data Insufficient</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Respondent_Name__c</fullName>
        <description>This field is used to capture Candidate Name where Category is not Self</description>
        <formula>Respondent__r.Full_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Respondent Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Respondent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field represents the Bureau Candidate who shall acting as a respondent and shall be rating the Participant.</description>
        <inlineHelpText>Specify the Candidate who shall be rating the Participant</inlineHelpText>
        <label>Respondent</label>
        <referenceTo>Bureau_Candidate__c</referenceTo>
        <relationshipName>Bureau_Ratings_As_Respondent</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TC_Report_Sent__c</fullName>
        <inlineHelpText>To capture the status of TC platform report sent to customer.</inlineHelpText>
        <label>TC Report Sent</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Sent</fullName>
                </value>
                <value>
                    <fullName>Sent</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Managed Services Rating</label>
    <nameField>
        <displayFormat>BR{000000000}</displayFormat>
        <label>Rating Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Managed Services Ratings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Job__c.object
<CustomObject>
    <description>The entity used to identify a work request from a client to the Bureau.</description>
    <fields>
        <fullName>Status_Calculations__c</fullName>
        <description>This field stores the json for the different status calculations, it is created for backend use.</description>
        <label>Status Calculations</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Job</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Job Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/CalculateRatingsBatchOnPlatformUpdate.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 08-22-2025
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
global class CalculateRatingsBatchOnPlatformUpdate implements Database.Batchable<sObject>, Database.Stateful {
    private String jobId;
    private String jobName;
    private list<String> errors = new list<String>();
    public Map<String, String> raterStringMap = new Map<String, String>();
    
    public CalculateRatingsBatchOnPlatformUpdate(String jobId, String jobNumber) {
        this.jobId = jobId;
        this.jobName = jobNumber;
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        String query = 'SELECT Id, Rater_String__c, Reminder_1__c, Report_Ready__c, Participant_Name__c, Respondent_Name__c, Rater_Type__c, MFS_Status__c, Participant__r.Bureau_Job__c,MFS_Report_Sent__c,TC_Report_Sent__c,Overall_Status__c,Participant__r.Email__c, Respondent__r.Email__c from Bureau_Rating__c WHERE Participant__r.Bureau_Job__c = \''+ this.jobId +'\'';
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<Bureau_Rating__c> ratingList) {  
        if (!ratingList.isEmpty()) {
            List<Bureau_Rating__c> otherRatingList = new List<Bureau_Rating__c>();
            List<Bureau_Rating__c> selfRatingList = new List<Bureau_Rating__c>();
            Map<String, String> participantEmailNameMap = new Map<String, String>();
            
            jobId = ratingList[0].Participant__r.Bureau_Job__c;
            Map<String,String> reminderMap1 = new Map<String,String>();
            Boolean computeForNonSelf1 = false;
            
            for(Bureau_Rating__c rating : ratingList){
                participantEmailNameMap.put(rating.Participant__r.Email__c, rating.Participant_Name__c);
            }
            
            for(Bureau_Rating__c rating : ratingList){
        
                //rating.Reminder_1__c ='Eligible';
                if (rating.Rater_Type__c == 'Self') {
                        if (rating.MFS_Report_Sent__c == 'Sent' && rating.TC_Report_Sent__c == 'Sent') {
                            computeForNonSelf1 = false;
                            //String participantName = rating.Participant_Name__c.toLowerCase();
                            String participantEmail = rating.Participant__r.Email__c.toLowerCase();
                            reminderMap1.put(participantEmail, 'Not Eligible');
                        }
                        else if (rating.MFS_Report_Sent__c == 'Not Sent' || rating.TC_Report_Sent__c == 'Not Sent') {
                            computeForNonSelf1 = true;
                            //String participantName = rating.Participant_Name__c.toLowerCase();
                            //String respondentName = rating.Respondent_Name__c.toLowerCase();
                            String participantEmail = rating.Participant__r.Email__c.toLowerCase();
                            String respondentEmail = rating.Respondent__r.Email__c.toLowerCase();
                            String key = participantEmail + respondentEmail;
                            if (rating.Overall_Status__c == 'In Progress' || rating.Overall_Status__c == 'Not Started') {
                                reminderMap1.put(key, 'Eligible');
                            }
                            else {
                                reminderMap1.put(key, 'Not Eligible');
                            }
                        }
                    else if(rating.MFS_Report_Sent__c == null && rating.TC_Report_Sent__c == 'Sent'){
                            computeForNonSelf1 = false;
                             String participantEmail = rating.Participant__r.Email__c.toLowerCase();
                            reminderMap1.put(participantEmail, 'Not Eligible');
                        }
                    }
                    if (computeForNonSelf1 && rating.Rater_Type__c != 'Self') {
                        //String participantName = rating.Participant_Name__c.toLowerCase();
                        //String respondentName = rating.Respondent_Name__c.toLowerCase();
                        String participantEmail = rating.Participant__r.Email__c.toLowerCase();
                        String respondentEmail = rating.Respondent__r.Email__c.toLowerCase();
                        String key = participantEmail + respondentEmail;
                        if (rating.Overall_Status__c == 'In Progress' || rating.Overall_Status__c == 'Not Started') {
                            reminderMap1.put(key, 'Eligible');
                        }
                        else {
                            reminderMap1.put(key, 'Not Eligible');
                        }
                    }
                if (rating.Rater_Type__c != 'Self') {
                    if (rating.MFS_Status__c != 'Completed') {
                        String respondentEmail = rating.Respondent__r.Email__c.toLowerCase();
                        if (!raterStringMap.containsKey(respondentEmail)) {
                            raterStringMap.put(respondentEmail, participantEmailNameMap.get(rating.Participant__r.Email__c));
                        } else {
                            String oldValue = raterStringMap.get(respondentEmail);
                            if(oldValue == ''){
                                raterStringMap.put(respondentEmail, participantEmailNameMap.get(rating.Participant__r.Email__c));
                            }else{
                                raterStringMap.put(respondentEmail, oldValue + ', ' + participantEmailNameMap.get(rating.Participant__r.Email__c));
                            }
                        }
                    }else if (rating.MFS_Status__c == 'Completed') {
                        String respondentEmail = rating.Respondent__r.Email__c.toLowerCase();
                        if (!raterStringMap.containsKey(respondentEmail)) {
                            raterStringMap.put(respondentEmail, '');
                        }
                    }
                }
                if (rating.Rater_Type__c == 'Self') {
                    selfRatingList.add(rating);
                }
                if(rating.Rater_Type__c != 'Self') {
                    otherRatingList.add(rating);
                }
                
            }
            for(Bureau_Rating__c rating : selfRatingList){
                //String participantName = rating.Participant_Name__c.toLowerCase();
                //String respondentName = rating.Respondent_Name__c.toLowerCase();
                String participantEmail = rating.Participant__r.Email__c.toLowerCase();
                String respondentEmail = rating.Respondent__r.Email__c.toLowerCase();
                String key = participantEmail + respondentEmail;
                if (reminderMap1.containsKey(key)) {
                    rating.Reminder_1__c = reminderMap1.get(key);
                } else {
                    rating.Reminder_1__c = reminderMap1.get(participantEmail);
                }
                
            }
            
            for(Bureau_Rating__c rating : otherRatingList){
                rating.Rater_String__c = raterStringMap.get(rating.Respondent__r.Email__c.toLowerCase());
                //String participantName = rating.Participant_Name__c.toLowerCase();
                //String respondentName = rating.Respondent_Name__c.toLowerCase();
                String participantEmail = rating.Participant__r.Email__c.toLowerCase();
                String respondentEmail = rating.Respondent__r.Email__c.toLowerCase();
                String key = participantEmail + respondentEmail;
                if (reminderMap1.containsKey(key)) {
                    rating.Reminder_1__c = reminderMap1.get(key);
                } else {
                    rating.Reminder_1__c = reminderMap1.get(participantEmail);
                }
            }
            
            if(!selfRatingList.isEmpty()){
                List<Database.SaveResult> ratingResults = Database.update(selfRatingList, false);
                for(Database.SaveResult sr : ratingResults) {
                    if(!sr.isSuccess()){               
                        list<Database.Error> err = sr.getErrors();
                        errors.add(err[0].getStatusCode() + ': ' + err[0].getMessage());
                    }
                }
            }
            if(!otherRatingList.isEmpty()){
                List<Database.SaveResult> ratingResults1 = Database.update(otherRatingList, false);
                for(Database.SaveResult sr : ratingResults1) {
                    if(!sr.isSuccess()){               
                        list<Database.Error> err = sr.getErrors();
                        errors.add(err[0].getStatusCode() + ': ' + err[0].getMessage());
                    }
                }
            }   
            
            
        }
    }   
    
    global void finish(Database.BatchableContext BC) {
        String errorBody;
        String subjectBody;
        
        if(!errors.isEmpty()) {
            subjectBody='Errors Occurred While computing ratings';
            errorBody='Updation failed, some error has occured. Rating updation related to Job Number:'+jobName+' is failing because of following errors mentioned below:'+'<br/>';
            for(String error : errors ){errorBody += error + '<br/>';}
        }else{
            /*if(!Test.isRunningTest()){
                String json = RollUpCandidateFields.updateStatusCalculations(jobId);
                Job__c job = new Job__c();job.id = jobId;job.Status_Calculations__c = json;update job;
            }*/
            
            subjectBody='Rating Updation Completed Successfully';
            errorBody='The Rating updation process is completed successfully. All Ratings related to Job Number:'+jobName+' are updated.';
        }
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        mail.setSubject(subjectBody);
        mail.setTargetObjectId(UserInfo.getUserId());
        mail.setSaveAsActivity(false);
        mail.setHtmlBody(errorBody);
        Messaging.sendEmail(new Messaging.Email[] { mail });
        
    }

}