objects/Bureau_Candidate__c.object
<CustomObject>
    <description>Managed Services module</description>
    <fields>
        <fullName>Bureau_Job__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Managed Services Job</label>
        <referenceTo>Job__c</referenceTo>
        <relationshipLabel>Managed Services Candidates</relationshipLabel>
        <relationshipName>Bureau_Candidates</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Managed Services Candidate</label>
    <nameField>
        <displayFormat>BC{000000000}</displayFormat>
        <label>Candidate Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Managed Services Candidates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Job__c.object
<CustomObject>
    <description>The entity used to identify a work request from a client to the Bureau.</description>
    <fields>
        <fullName>Actual_Count_of_Candidates_PassFail__c</fullName>
        <description>It is used to capture (Sum of candidates with Status as Completed) Or (Sum of candidates with status Pass or Fail)</description>
        <label>Actual Count of Candidates</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Candidate_Max_Sequence_No_New__c</fullName>
        <description>&quot;This field is created on the place of old Candidate Max Sequence field while Relationship conversion. 
Number of Candidates uploaded on Job.&quot;</description>
        <label>Number of Candidates</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Count_of_Candidates_DNA__c</fullName>
        <description>It is used to capture count of Candidates with status DNA</description>
        <label>Count of Candidates DNA</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Count_of_Candidates_fail__c</fullName>
        <description>It is used to capture count of Candidates with status Fail</description>
        <label>Count of Candidates Fail</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Count_of_Candidates_pass__c</fullName>
        <description>It is used to capture count of Candidates with status Pass</description>
        <label>Count of Candidates Pass</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Count_of_candidates_invited__c</fullName>
        <description>It is used to capture count of Candidates with status Pass + Fail + DNA</description>
        <label>Count of Candidates Invited</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Assessments__c</fullName>
        <description>Sum of field &quot;Number of Product/Assessment&quot; on Candidates related to Job</description>
        <inlineHelpText>The sum of field on Candidate named as &quot;Number of Product/Assessment&quot;</inlineHelpText>
        <label>Number of Assessments</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Participants_New__c</fullName>
        <description>This field is created on the place of old Number of Participant field while Relationship conversion. 
Sum of field &quot;&quot;Number_of_participants__c&quot;&quot; on Candidates related to Job</description>
        <label>Number of Participants</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Respondents_New__c</fullName>
        <description>This field is created on the place of old Number of Respondent field while Relationship conversion. 
Sum of field &quot;&quot;Number_of_Respondents__c&quot;&quot; on Candidates related to Job.</description>
        <label>Number of Respondents</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Job</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Job Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/CandidateBulkDeletionBatch.cls
global class CandidateBulkDeletionBatch implements Database.Batchable<sObject>, Database.Stateful {
    private String jobid;
    private String jobName;
    private list<String> errors = new list<String>();
    public CandidateBulkDeletionBatch(String jobid) {
        this.jobid = jobid;
    }
    global Database.QueryLocator start(Database.BatchableContext BC) {
        String query = 'Select id,Bureau_Job__r.Name from Bureau_Candidate__c where Bureau_Job__c = \''+ this.jobid +'\'';
        return Database.getQueryLocator(query);
    }
     
    global void execute(Database.BatchableContext BC, List<Bureau_Candidate__c> candidateList) {  
          jobName = candidateList[0].Bureau_Job__r.Name;
          List<Database.DeleteResult> deleteResults = Database.delete(candidateList,false);
          for(Database.DeleteResult sr : deleteResults) {
             if(!sr.isSuccess()){               
               list<Database.Error> err = sr.getErrors();
               errors.add(err[0].getStatusCode() + ': ' + err[0].getMessage());
             }
           }
    }   
     
    global void finish(Database.BatchableContext BC) {
        String errorBody;
        String subjectBody;
        
        if(!errors.isEmpty()) {
            subjectBody='Errors Occurred While Deleting Candidates';
            errorBody='Deletion failed, some error has occured. Candidate deletion related to job Number:'+jobName+' is failing because of following errors mentioned below:'+'<br/>';
            for(String error : errors ){
                errorBody += error + '<br/>';
            }
        }else{
            subjectBody='Candidate Deletion Completed Successfully';
            errorBody='The Candidate deletion process is completed successfully. All Candidates related to job Number:'+jobName+' are deleted.';
            Job__c JobRec = [Select id,Number_of_Assessments__c,Number_of_Respondents_New__c,Number_of_Participants_New__c ,
                                 Candidate_Max_Sequence_No_New__c,Count_of_Candidates_pass__c,Count_of_Candidates_fail__c,
                                 Count_of_Candidates_DNA__c, Actual_Count_of_Candidates_PassFail__c,Count_of_candidates_invited__c
                                 from Job__c where id =: jobId ];
            if(JobRec != null){
               JobRec.Number_of_Assessments__c = 0;
               JobRec.Number_of_Respondents_New__c = 0;
               JobRec.Number_of_Participants_New__c = 0;
               JobRec.Candidate_Max_Sequence_No_New__c = 0;
               JobRec.Count_of_Candidates_pass__c = 0;
               JobRec.Count_of_Candidates_fail__c = 0;
               JobRec.Count_of_Candidates_DNA__c = 0;
               JobRec.Actual_Count_of_Candidates_PassFail__c = 0;
               JobRec.Count_of_candidates_invited__c = 0;
                  
               update JobRec;
            }
        }
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        mail.setSubject(subjectBody);
        mail.setTargetObjectId(UserInfo.getUserId());
        mail.setSaveAsActivity(false);
        mail.setHtmlBody(errorBody);
        Messaging.sendEmail(new Messaging.Email[] { mail });
        
    }
}