objects/Case.object
<CustomObject>
    <fields>
        <fullName>Assigned_To__c</fullName>
        <description>Call Assignment selection to redirect cases to correct Regional Helpdesk</description>
        <inlineHelpText>Only raise a case to Legal following discussion with your Manager or Team Leader</inlineHelpText>
        <label>Assigned To</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>!!Please Select a Helpdesk!!</fullName>
                </value>
                <value>
                    <fullName>Accounts Receivable</fullName>
                </value>
                <value>
                    <fullName>AM APAC Technical Support</fullName>
                </value>
                <value>
                    <fullName>AM China Technical Support</fullName>
                </value>
                <value>
                    <fullName>AM EMEA Technical Support</fullName>
                </value>
                <value>
                    <fullName>Americas Client Helpdesk</fullName>
                </value>
                <value>
                    <fullName>AM Presales</fullName>
                </value>
                <value>
                    <fullName>AMS PS Branding</fullName>
                </value>
                <value>
                    <fullName>AMS PS Cases</fullName>
                </value>
                <value>
                    <fullName>AM US Technical Support</fullName>
                </value>
                <value>
                    <fullName>APAC client helpdesk</fullName>
                </value>
                <value>
                    <fullName>APAC Customer Experience</fullName>
                </value>
                <value>
                    <fullName>APAC Helpdesk</fullName>
                </value>
                <value>
                    <fullName>APAC Technical Support</fullName>
                </value>
                <value>
                    <fullName>Bureau</fullName>
                </value>
                <value>
                    <fullName>Bureau helpdesk</fullName>
                </value>
                <value>
                    <fullName>CEB Sunstone Analytics Client Advisors</fullName>
                </value>
                <value>
                    <fullName>China Customer Experience</fullName>
                </value>
                <value>
                    <fullName>China Technical Support</fullName>
                </value>
                <value>
                    <fullName>CSIT</fullName>
                </value>
                <value>
                    <fullName>Customer Collections</fullName>
                </value>
                <value>
                    <fullName>Customer Experience</fullName>
                </value>
                <value>
                    <fullName>Customer Experience general</fullName>
                </value>
                <value>
                    <fullName>Customer Experience onboarding</fullName>
                </value>
                <value>
                    <fullName>Customer Systems Training</fullName>
                </value>
                <value>
                    <fullName>EMEA Customer Experience</fullName>
                </value>
                <value>
                    <fullName>EMEA TAM</fullName>
                </value>
                <value>
                    <fullName>EMEA Technical Support</fullName>
                </value>
                <value>
                    <fullName>General</fullName>
                </value>
                <value>
                    <fullName>India APAC Technical Support</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Call_Type__c</fullName>
        <description>From call logging</description>
        <label>Case Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Account Manager Referral</fullName>
                </value>
                <value>
                    <fullName>Assessment Preview</fullName>
                </value>
                <value>
                    <fullName>Candidate Support call</fullName>
                </value>
                <value>
                    <fullName>Courses/Training/Qualifications</fullName>
                </value>
                <value>
                    <fullName>Course Sales / Bookings</fullName>
                </value>
                <value>
                    <fullName>DC Enquiry</fullName>
                </value>
                <value>
                    <fullName>Delivery/Returns</fullName>
                </value>
                <value>
                    <fullName>Demo</fullName>
                </value>
                <value>
                    <fullName>Demo Actual Responses Report</fullName>
                </value>
                <value>
                    <fullName>Disability query</fullName>
                </value>
                <value>
                    <fullName>Distributors Orders</fullName>
                </value>
                <value>
                    <fullName>External Sales/Marketing call</fullName>
                </value>
                <value>
                    <fullName>Goodwill gesture</fullName>
                </value>
                <value>
                    <fullName>Internal Product Support</fullName>
                </value>
                <value>
                    <fullName>Internal SHL support</fullName>
                </value>
                <value>
                    <fullName>Invoice/Credit/Licence</fullName>
                </value>
                <value>
                    <fullName>Lead Qualifications &amp; Processing</fullName>
                </value>
                <value>
                    <fullName>Leased Materials</fullName>
                </value>
                <value>
                    <fullName>Legacy/offline support</fullName>
                </value>
                <value>
                    <fullName>Managed Services</fullName>
                </value>
                <value>
                    <fullName>Onboarding</fullName>
                </value>
                <value>
                    <fullName>Order Investigation</fullName>
                </value>
                <value>
                    <fullName>Order Placed</fullName>
                </value>
                <value>
                    <fullName>P&amp;P/Book Orders</fullName>
                </value>
                <value>
                    <fullName>Partners</fullName>
                </value>
                <value>
                    <fullName>Phone Issue</fullName>
                </value>
                <value>
                    <fullName>Phone Issues</fullName>
                </value>
                <value>
                    <fullName>PO Number Received</fullName>
                </value>
                <value>
                    <fullName>Pricing Queries</fullName>
                </value>
                <value>
                    <fullName>Product Consulting</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Caller_Type__c</fullName>
        <inlineHelpText>Candidates are not listed as contacts on SFDC so it is necessary to select either of these options when logging the case.</inlineHelpText>
        <label>Caller Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Customer</fullName>
                </value>
                <value>
                    <fullName>Candidate</fullName>
                </value>
                <value>
                    <fullName>Internal</fullName>
                </value>
                <value>
                    <fullName>None</fullName>
                    <default>true</default>
                    <label>None</label>
                </value>
                <value>
                    <fullName>Client</fullName>
                </value>
                <value>
                    <fullName>Customer Experience</fullName>
                </value>
                <value>
                    <fullName>Professional Services</fullName>
                </value>
                <value>
                    <fullName>Sales</fullName>
                </value>
                <value>
                    <fullName>Finance</fullName>
                </value>
                <value>
                    <fullName>Managed Services</fullName>
                </value>
                <value>
                    <fullName>Technical Support</fullName>
                </value>
                <value>
                    <fullName>IT</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>50</length>
        <type>Text</type>
    </fields>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Mailing_Address_Line_1__c</fullName>
        <label>Address Line 1</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mailing_Address_Line_2__c</fullName>
        <label>Address Line 2</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mailing_Address_Line_3__c</fullName>
        <label>Address Line 3</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mailing_Address_Line_4__c</fullName>
        <label>Address Line 4</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mailing_City__c</fullName>
        <label>City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mailing_Country__c</fullName>
        <label>Country (not in use)</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AFGHANISTAN</fullName>
                </value>
                <value>
                    <fullName>ALBANIA</fullName>
                </value>
                <value>
                    <fullName>ALDERNEY</fullName>
                </value>
                <value>
                    <fullName>ALGERIA</fullName>
                </value>
                <value>
                    <fullName>AMERICAN SAMOA</fullName>
                </value>
                <value>
                    <fullName>ANDORRA</fullName>
                </value>
                <value>
                    <fullName>ANGOLA</fullName>
                </value>
                <value>
                    <fullName>ANGUILLA</fullName>
                </value>
                <value>
                    <fullName>ANTARCTICA</fullName>
                </value>
                <value>
                    <fullName>ANTIGUA AND BARBUDA</fullName>
                </value>
                <value>
                    <fullName>ARGENTINA</fullName>
                </value>
                <value>
                    <fullName>ARMENIA</fullName>
                </value>
                <value>
                    <fullName>ARUBA</fullName>
                </value>
                <value>
                    <fullName>AUSTRALIA</fullName>
                </value>
                <value>
                    <fullName>AUSTRIA</fullName>
                </value>
                <value>
                    <fullName>AZERBAIJAN</fullName>
                </value>
                <value>
                    <fullName>BAHAMAS</fullName>
                </value>
                <value>
                    <fullName>BAHRAIN</fullName>
                </value>
                <value>
                    <fullName>BANGLADESH</fullName>
                </value>
                <value>
                    <fullName>BARBADOS</fullName>
                </value>
                <value>
                    <fullName>BELARUS</fullName>
                </value>
                <value>
                    <fullName>BELGIUM</fullName>
                </value>
                <value>
                    <fullName>BELIZE</fullName>
                </value>
                <value>
                    <fullName>BENIN</fullName>
                </value>
                <value>
                    <fullName>BERMUDA</fullName>
                </value>
                <value>
                    <fullName>BHUTAN</fullName>
                </value>
                <value>
                    <fullName>BOLIVIA</fullName>
                </value>
                <value>
                    <fullName>BOSNIA AND HERZEGOWINA</fullName>
                </value>
                <value>
                    <fullName>BOTSWANA</fullName>
                </value>
                <value>
                    <fullName>BOUVET ISLAND</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Mailing_State_County__c</fullName>
        <label>State/County</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mailing_ZIP_Postal_Code__c</fullName>
        <label>ZIP/Postal Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
</CustomObject>

force-app/main/objects/Payment_case_country_mapping__mdt.object
<CustomObject>
    <description>This custom metadata is used to map the contact mailing country code to the case county code.</description>
    <fields>
        <fullName>Country_Code__c</fullName>
        <label>Country Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country_Name__c</fullName>
        <description>Country name</description>
        <label>Country Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Payment case country mapping</label>
    <pluralLabel>Payment case country mappings</pluralLabel>
</CustomObject>

classes/MakePaymentContact.cls
public class MakePaymentContact{
  
    public String conid{get;set;} 
    public String accid{get;set;} 
    public String inputText3{get;set;} 
    public String inputText4{get;set;}
    public Id Cid;
    
    
    public MakePaymentContact(ApexPages.StandardController controller) {
       conid = ApexPages.currentPage().getParameters().get('id');
       
    }
    
       public PageReference createCase(){
           contact con = [select id,Account.CurrencyIsoCode,Name,FirstName,LastName,Mailing_Address_Line_1__c,Mailing_Address_Line_2__c,Mailing_Address_Line_3__c,Mailing_Address_Line_4__c,Mailing_City__c,Mailing_ZIP_Postal_Code__c,Mailing_Country__c,Mailing_State_County__c from CONTACT where id =:conid ];
           Map<String,String> countryAndCountryCodeMap = new Map<String,String>();
           for(Payment_case_country_mapping__mdt obj : [select id,Country_Code__c,Country_Name__c from Payment_case_country_mapping__mdt 
                                                        where Country_Name__c =: con.Mailing_Country__c]){
               countryAndCountryCodeMap.put(obj.Country_Name__c,obj.Country_Code__c);
           }
           Case c = new Case();
           c.RecordtypeId = '012D0000000V9YhIAK';
           c.Origin = 'Phone';
           c.ContactId = conid;           
           c.Subject = 'Invoice Payment - ';
           c.Call_Type__c = 'Invoice/Credit/Licence';
           c.Status = 'In Progress';
           c.Caller_Type__c = 'Customer';
           
           c.CurrencyIsoCode =  con.Account.CurrencyIsoCode;
           //c.Assigned_To__c = 'APAC Customer Success'; // Assigned To logic to be discussed
           //c.Case_Country__c = con.Mailing_Country__c;
           if(!countryAndCountryCodeMap.isEmpty() && countryAndCountryCodeMap.containsKey(con.Mailing_Country__c)){
               c.Case_Country__c = countryAndCountryCodeMap.get(con.Mailing_Country__c);//added by sanjeev
           }
           c.Description = 'NVM Case';      
           c.Problem2__c = 'Other';
           c.Solution__c = 'Other';
           
           c.Preferred_Language__c = 'English';
           c.Caller_s_Name__c = con.Name;        
           c.First_Name__c= con.FirstName;
           c.Last_Name__c= con.LastName;
           c.Building_Name__c= con.Mailing_Address_Line_1__c;    
           c.Street__c = (con.Mailing_Address_Line_2__c + ' ' + con.Mailing_Address_Line_3__c + ' ' + con.Mailing_Address_Line_4__c).remove('null');
           c.City_town__c= con.Mailing_City__c;
           c.Zip_Postal__c= con.Mailing_ZIP_Postal_Code__c;
           c.Country__c= con.Mailing_Country__c;
           c.State__c = con.Mailing_State_County__c;   
           
           insert c;
           
           
           if(c.id != NULL){
               PageReference nextPage = new PageReference('/' + c.id );
               //PageReference pageRef = new PageReference('http://www.google.com');
               nextPage.setRedirect(false);
               //return pageRef;
               return nextPage;
               
           }
           
           else{
               return null;
           }
       }
}