objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Same_As_The_Account_Billing_Address__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If this option is selected, then the Contact Mailing Address is copied from the Account Billing Address.</description>
        <inlineHelpText>Check this box to set the Contact Address to the same as the Account Billing Address. This address will not be populated from the Account until you hit Save. You must ensure this box is not ticked if you want to enter a different address for the Contact.</inlineHelpText>
        <label>Same As The Account Billing Address</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

force-app/main/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Billing_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Billing Contact(Legacy)</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contracts (Billing Contact)</relationshipLabel>
        <relationshipName>Contracts2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Legal_Order_Name__c</fullName>
        <label>Legal Order Name(Legacy)</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NVM_Credit_Card_ID__c</fullName>
        <label>NVM Payment ID(Legacy)</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>S2P_Reference_Required__c</fullName>
        <description>Check on the S2P Reference.</description>
        <inlineHelpText>Choose new if system referenced in the order does not currently exist, otherwise choose Existing</inlineHelpText>
        <label>System Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Existing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Subscription_Start_Date__c</fullName>
        <inlineHelpText>This date should be the same as the Contract Start Date unless delay has been approved in CLM.</inlineHelpText>
        <label>Product Subscription Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Unconfirmed_Sun_Order_Number__c</fullName>
        <label>Unconfirmed Sun Order Number(Legacy)</label>
        <length>11</length>
        <type>Text</type>
    </fields>
</CustomObject>

force-app/main/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Billing_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Billing Contact</label>
        <lookupFilter>
            <active>false</active>
            <errorMessage>Billing Contact should be part of the account linked to the opportunity.</errorMessage>
            <filterItems>
                <field>$Source.AccountId</field>
                <operation>equals</operation>
                <valueField>Contact.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Business_Type__c</fullName>
        <description>Choose the Opportunity Type that best describes the type of business pursued.  
Reboost should only be used with In-Advance clients. 
Cross-sell is simply New Business with a client that has a current commercial relationship.</description>
        <label>Opportunity Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Expansion</fullName>
                </value>
                <value>
                    <fullName>Renewal</fullName>
                </value>
                <value>
                    <fullName>Debooking</fullName>
                    <label>Debooking / Adjustment</label>
                </value>
                <value>
                    <fullName>Extension</fullName>
                </value>
                <value>
                    <fullName>In Arrears</fullName>
                </value>
                <value>
                    <fullName>In Advance</fullName>
                </value>
                <value>
                    <fullName>Managed Services</fullName>
                </value>
                <value>
                    <fullName>Professional Services: non-subscription</fullName>
                </value>
                <value>
                    <fullName>Top Up / Addition</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Forecast_Category__c</fullName>
        <inlineHelpText>Please select “Commit” if you want this opportunity to be counted in your Forecast number. Please select Pipeline or Renewal at Risk if you do not want it to be included.</inlineHelpText>
        <label>Forecast Category</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Business_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Commit</fullName>
                </value>
                <value>
                    <fullName>Pipeline</fullName>
                    <default>true</default>
                    <label>Pipeline</label>
                </value>
                <value>
                    <fullName>Renewal at Risk</fullName>
                </value>
                <value>
                    <fullName>Forecast</fullName>
                    <isActive>false</isActive>
                    <label>Forecast</label>
                </value>
                <value>
                    <fullName>Parked</fullName>
                    <isActive>false</isActive>
                    <label>Parked</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>NVM_Credit_Card_ID__c</fullName>
        <label>NVM Payment ID</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities (Primary Contact)</relationshipLabel>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Unconfirmed_Sun_Order_Number__c</fullName>
        <label>Unconfirmed Sun Order Number</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Variation_Opportunity__c</fullName>
        <label>Variation Opportunity</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                    <default>true</default>
                    <label>No</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

force-app/main/objects/Order.object
<CustomObject>
    <fields>
        <fullName>Order_Year__c</fullName>
        <label>Order Year</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Reduction_Order__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checkbox to define whether order is reduction or not.</description>
        <label>Reduction order</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Unconfirmed_Sun_Order_Number__c</fullName>
        <label>Unconfirmed Sun Order Number</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Variation_Opportunity__c</fullName>
        <formula>Text(Opportunity.Variation_Opportunity__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Variation Order</label>
        <type>Text</type>
    </fields>
</CustomObject>

classes/ReductionOrderLEXClassTester.cls
@istest(SeeAllData=true)
/*public class ReductionOrderLEXClassTester {
    static TestMethod void ReductionOrderLEXClassTesterTestMethod(){
     List<Order> ord = new List<Order>();
        for ( Integer count = 0; count < 50; count++){
            ord.add(new Order);
        }
        insert ord;
        Test.startTest();
        
	 ReductionOrderLEXClass.relatedOrderRecord(ord.Id);
        Test.stopTest();
        Order ordr = [Select id from Order LIMIT 1];
        System.assertEquals(Integer.valueOf(ordr.Id),000000000000000);
     
      
    }

}*/


public class ReductionOrderLEXClassTester{
    
     public static testMethod void ReductionOrderLEXClassTesterTestMethod(){
     
           // ReductionOrderLEXClass.relatedOrderRecord();
            Account account=CreateTestData.getAccount();
            
            Contact contact = new Contact(AccountId=account.Id,LastName='test12345',email='test12345@test.com',phone='2345345345',Same_As_The_Account_Billing_Address__c=true);
            insert contact;
              Contract contract = new Contract();
        contract.AccountId = account.Id;   
        contract.CurrencyIsoCode = account.CurrencyIsoCode;
        contract.S2P_Reference_Required__c = 'New';
        contract.Status = 'Draft';
        contract.CustomerSignedDate = Date.Today();
        contract.StartDate = Date.Today();
        contract.ContractTerm = 6;  
        contract.Legal_Order_Name__c='test';
        contract.Subscription_Start_Date__c = system.today();
        insert contract;
            Opportunity opportunity= new Opportunity(AccountId=Account.Id,Billing_Contact__c=Contact.Id,Business_Type__c='New customer: subscription',Forecast_Category__c='Forecast',Primary_Contact__c=Contact.Id,name='Test Opportunity',NVM_Credit_Card_ID__c='',Unconfirmed_Sun_Order_Number__c='',CurrencyISOCode='GBP',StageName='New',Variation_Opportunity__c ='No',closeDate=System.today());
            insert opportunity;
         
            Order ord = new Order();
            Id orderrt = Schema.SObjectType.Order.getRecordTypeInfosByName().get('Standard Order').getRecordTypeId();

        ord.Accountid = account.id;
        ord.ContractId = contract.id;
        ord.name = 'test';
        //ord.RecordTypeId = '0127E0000032wq7';
        ord.RecordTypeId = orderrt;
        ord.Status = 'Draft';
        ord.EffectiveDate = system.today();
        ord.CurrencyIsoCode = contract.CurrencyIsoCode;
        ord.Pricebook2Id = '01s2000000000vQAAQ';
        ord.Reduction_Order__c = false;
        ord.Order_Year__c = 1;
         ord.OpportunityId = opportunity.id;
        //ord.Variation_Opportunity__c = 'Yes';
        
        //ord.quantity = 1;
        //ord.UnitPrice = 1000;
        insert ord;
       
          
          
         //ReductionOrderLEXClass.relatedOrderRecord(String.ordId);
     // List <Order> ordr = [Select id from Order where Id =:opportunity.Id];
         ReductionOrderLEXClass.relatedOrderRecord(opportunity.Id);
     }
}