objects/Contract_Invoice_Header__c.object
<CustomObject>
    <description>Invoice Header on Contract Object</description>
    <fields>
        <fullName>Alternative_Responsible_Code_1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Alternative Responsible Code</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Invoice_Headers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Invoice_Comments__c</fullName>
        <label>Printable Note</label>
        <length>550</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Invoice_Header_Comments__c</fullName>
        <description>Comments that will appear on the Invoice</description>
        <inlineHelpText>This field should be used for large amounts of text to be added to invoices and should be created manually in Sun.</inlineHelpText>
        <label>Extended Comments</label>
        <length>9999</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Invoice_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Invoice Request</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Project_Invoice__c.Status__c</field>
                <operation>equals</operation>
                <value>Submitted for Processing, Processed</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Project_Invoice__c</referenceTo>
        <relationshipLabel>Invoice Headers</relationshipLabel>
        <relationshipName>Invoice_Headers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Invoice_Status__c</fullName>
        <description>Invoice status. This includes all invoice lines below.</description>
        <label>Invoice Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Draft - awaiting milestones</fullName>
                </value>
                <value>
                    <fullName>On Hold for Payment Milestone</fullName>
                </value>
                <value>
                    <fullName>Cross Border</fullName>
                </value>
                <value>
                    <fullName>Queried</fullName>
                </value>
                <value>
                    <fullName>Awaiting PO</fullName>
                </value>
                <value>
                    <fullName>Awaiting GST/VAT Info</fullName>
                </value>
                <value>
                    <fullName>Awaiting Chop</fullName>
                </value>
                <value>
                    <fullName>No Usage</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Ready to Invoice</fullName>
                </value>
                <value>
                    <fullName>Ready for SOE Review</fullName>
                </value>
                <value>
                    <fullName>Ready for Sun Transfer</fullName>
                </value>
                <value>
                    <fullName>Transferring to Sun</fullName>
                </value>
                <value>
                    <fullName>Sun Order Complete</fullName>
                </value>
                <value>
                    <fullName>Sun Invoice Complete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Manual_Transfer__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Manual Transfer</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Process_Date__c</fullName>
        <description>Shows the date that invoice will be raised on</description>
        <inlineHelpText>Enter date that invoice needs to be created on.</inlineHelpText>
        <label>Date invoice to be processed by SOP</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project_Number__c</fullName>
        <label>Project Number</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SFDC2SUN_Log__c</fullName>
        <description>This field contains the success and failure logs of the Header during transfer process to Sun Systems</description>
        <inlineHelpText>Header transfer logs</inlineHelpText>
        <label>SFDC2SUN: Log</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>SFDC2SUN_Transfer_Status__c</fullName>
        <description>It indicates the Invoice Header status whether it has been transferred to Sun or not.</description>
        <inlineHelpText>The status of the last transfer attempt from SFDC to Sun.</inlineHelpText>
        <label>SFDC2SUN: Transfer Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Transferred</fullName>
                </value>
                <value>
                    <fullName>Transferred</fullName>
                </value>
                <value>
                    <fullName>Ready for Transfer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SFDC2SUN_Transferred_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field indicates the salesforce.com user who transferred the Invoice header in Sun Systems</description>
        <inlineHelpText>The user who last transferred the record from SFDC to Sun.</inlineHelpText>
        <label>SFDC2SUN: Transferred By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>InvoiceHeaders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SFDC2SUN_Transferred_On__c</fullName>
        <description>This field indicates the date when the Invoice header was transferred in Sun Systems</description>
        <inlineHelpText>The date of the last transfer attempt from SFDC to Sun.</inlineHelpText>
        <label>SFDC2SUN: Transferred On</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Sales_Type__c</fullName>
        <label>Sales Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>SFSOLSPLIT</fullName>
                </value>
                <value>
                    <fullName>SFSOLSPLITCN</fullName>
                </value>
                <value>
                    <fullName>SFSOLUTION</fullName>
                </value>
                <value>
                    <fullName>SFSOLUTIONCN</fullName>
                </value>
                <value>
                    <fullName>SFSOL27</fullName>
                </value>
                <value>
                    <fullName>SFSOL27CN</fullName>
                </value>
                <value>
                    <fullName>1</fullName>
                    <isActive>false</isActive>
                    <label>1</label>
                </value>
                <value>
                    <fullName>2</fullName>
                    <isActive>false</isActive>
                    <label>2</label>
                </value>
                <value>
                    <fullName>3</fullName>
                    <isActive>false</isActive>
                    <label>3</label>
                </value>
                <value>
                    <fullName>4</fullName>
                    <isActive>false</isActive>
                    <label>4</label>
                </value>
                <value>
                    <fullName>RISOLUTION</fullName>
                    <isActive>false</isActive>
                    <label>RISOLUTION</label>
                </value>
                <value>
                    <fullName>RISOLUTIONCN</fullName>
                    <isActive>false</isActive>
                    <label>RISOLUTIONCN</label>
                </value>
                <value>
                    <fullName>RISOLUTIONCR</fullName>
                    <isActive>false</isActive>
                    <label>RISOLUTIONCR</label>
                </value>
                <value>
                    <fullName>RISUBS</fullName>
                    <isActive>false</isActive>
                    <label>RISUBS</label>
                </value>
                <value>
                    <fullName>RISUBSCN</fullName>
                    <isActive>false</isActive>
                    <label>RISUBSCN</label>
                </value>
                <value>
                    <fullName>S1NINV</fullName>
                    <isActive>false</isActive>
                    <label>S1NINV</label>
                </value>
                <value>
                    <fullName>S1RIC</fullName>
                    <isActive>false</isActive>
                    <label>S1RIC</label>
                </value>
                <value>
                    <fullName>S1RII</fullName>
                    <isActive>false</isActive>
                    <label>S1RII</label>
                </value>
                <value>
                    <fullName>SFBANG</fullName>
                    <isActive>false</isActive>
                    <label>SFBANG</label>
                </value>
                <value>
                    <fullName>SFBANGCN</fullName>
                    <isActive>false</isActive>
                    <label>SFBANGCN</label>
                </value>
                <value>
                    <fullName>SFBUNDLED</fullName>
                    <isActive>false</isActive>
                    <label>SFBUNDLED</label>
                </value>
                <value>
                    <fullName>SFBUNDLEDAED</fullName>
                    <isActive>false</isActive>
                    <label>SFBUNDLEDAED</label>
                </value>
                <value>
                    <fullName>SFBUNDLEDCN</fullName>
                    <isActive>false</isActive>
                    <label>SFBUNDLEDCN</label>
                </value>
                <value>
                    <fullName>SFBUNDLEDCNAED</fullName>
                    <isActive>false</isActive>
                    <label>SFBUNDLEDCNAED</label>
                </value>
                <value>
                    <fullName>SFBUNDLEDTAX</fullName>
                    <isActive>false</isActive>
                    <label>SFBUNDLEDTAX</label>
                </value>
                <value>
                    <fullName>SFBUNDLEDTAXCN</fullName>
                    <isActive>false</isActive>
                    <label>SFBUNDLEDTAXCN</label>
                </value>
                <value>
                    <fullName>SFGURG</fullName>
                    <isActive>false</isActive>
                    <label>SFGURG</label>
                </value>
                <value>
                    <fullName>SFGURGCN</fullName>
                    <isActive>false</isActive>
                    <label>SFGURGCN</label>
                </value>
                <value>
                    <fullName>SFSOE</fullName>
                    <isActive>false</isActive>
                    <label>SFSOE</label>
                </value>
                <value>
                    <fullName>SFSOEAED</fullName>
                    <isActive>false</isActive>
                    <label>SFSOEAED</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SunSystems_Order_Reference__c</fullName>
        <inlineHelpText>Once the order has been raised in SunSystems enter the Order Reference here</inlineHelpText>
        <label>Sun Order Reference</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sun_Invoice_Number__c</fullName>
        <label>Sun Invoice Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Invoice Header</label>
    <nameField>
        <displayFormat>CIH{0000000}</displayFormat>
        <label>Invoice Header ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Headers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Contract_Invoice_Line__c.object
<CustomObject>
    <description>One or more lines that make up the Invoice Request</description>
    <fields>
        <fullName>Invoice_Header_ID__c</fullName>
        <label>Invoice Header ID</label>
        <referenceTo>Contract_Invoice_Header__c</referenceTo>
        <relationshipLabel>Invoice Lines</relationshipLabel>
        <relationshipName>Invoice_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Month__c</fullName>
        <label>Month</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Type__c</fullName>
        <formula>TEXT(Invoice_Header_ID__r.Sales_Type__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sales Type</label>
        <type>Text</type>
    </fields>
    <label>Invoice Line</label>
    <nameField>
        <displayFormat>CIL{0000000}</displayFormat>
        <label>Invoice Line ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ContractInvoiceHeader_Manager.cls
global with sharing class ContractInvoiceHeader_Manager
{
    //This method accepts the Id of an Invoice Header as input, creates a clone of the Invoice Header corresponding to this Id as well as the Invoice Lines related to this Invoice Header, inserts these clones in the database and return a SUCESS/ERORR/UNAUTHORISED message
    WebService static String[] superClone(String invoiceHeaderId)
    {
        try
        {
            //Check if the user has permissions to create the Invoice Header & the Invoice Lines 
            if(!(Schema.sObjectType.Contract_Invoice_Header__c.isCreateable() && Schema.sObjectType.Contract_Invoice_Line__c.isCreateable()))
                //Return a Message for no permissions
                return new String[]{'UNAUTHORISED'};
            
            //Create a Clone of the current Invoice Header 
            Contract_Invoice_Header__c newInvoiceHeader = createCloneOfContractInvoiceHeader(invoiceHeaderId);
            //Insert the cloned invoice Header in the Database
            insert newInvoiceHeader;
            
            //Create a Clone of the Invoice Lines related of the current Invoice Header             
            List<Contract_Invoice_Line__c> newInvoiceLineList = createCloneOfContractInvoiceLines(invoiceHeaderId);
            //Iterate through each of the cloned Invoice Lines
            for(Contract_Invoice_Line__c newInvoiceLine:newInvoiceLineList)
            {
                //Set the relationship between the cloned Invoice Line and the cloned Invoice Header
                newInvoiceLine.Invoice_Header_ID__c = newInvoiceHeader.id;
                //Increment the Month of the cloned Invoice Line by 1
                //If the incremented Month is null then return an error message.
                
                /* Commented on 24 Oct 2017 by Pankhuri Jain for SSE-5399, to remove month__c usage
                newInvoiceLine.Month__c = incrementInvoiceLineMonth(newInvoiceLine.Month__c);              
                if(newInvoiceLine.Month__c==null)
                    return new String[]{'The Month for one or more Invoice Lines of this Invoice header is not in the correct date format (yyyymm).'};
                Comment End */
                
            }
            //Insert the list of the cloned Invoice Lines 
            insert newInvoiceLineList;
            
            //Query the Name of new Invoice Header in order to add it in the Success Message 
            newInvoiceHeader = [SELECT Id, Name FROM Contract_Invoice_Header__c WHERE Id = :newInvoiceHeader.id];
            //Return the success message
            return new string[]{'SUCCESS',newInvoiceHeader.id,newInvoiceHeader.Name};
        }
        catch(Exception e)
        {
            System.debug('Failed method: superClone. Error:'+e.getMessage());
            //Return the exception message 
            return new String[]{e.getMessage()};
        }
    }
    
    //This method accepts the Id of an Invoice Header as input, retreives the Invoice Header corresponding to this Id from the database and returns a clone of the retrieved Invoice Header
    private static Contract_Invoice_Header__c createCloneOfContractInvoiceHeader(String invoiceHeaderId)
    {Contract_Invoice_Header__c invoiceheaderclone = new Contract_Invoice_Header__c();
        //Create a string all creatable fields of the Invoice Header object
        String contractInvoiceHeaderFieldsString = getObjectFieldsString(Schema.SObjectType.contract_Invoice_Header__c.fields.getMap());
        //Create a string of the Query required to fetch the Invoice Header to be cloned using the above string of Invoice Header fields
        String contractInvoiceHeaderQuery = String.format('SELECT {0},CurrencyIsoCode FROM Contract_Invoice_Header__c WHERE Id = {1} LIMIT 1',new String[]{contractInvoiceHeaderFieldsString,'\''+invoiceHeaderId+'\''});
        //Retreive the Invoice Header to be cloned by executeing the query created above
        Contract_Invoice_Header__c invoiceHeader = DataBase.query(contractInvoiceHeaderQuery);
        id editRecTypeId = [select Id ,name from RecordType where SobjectType='Contract_Invoice_Header__c' and name = 'Invoice Header'].id;
        
        //update a current date 
        invoiceHeader.Process_Date__c = System.today();
        //Return a clone of the Invoice Header retrieved above
        //return invoiceHeader.clone(false,true);
          invoiceheaderclone = invoiceHeader.clone(false, true);
          invoiceheaderclone.Invoice_Status__c='Draft';
         
            invoiceheaderclone.Sun_Invoice_Number__c= null;
            invoiceheaderclone.Project_Number__c= null;
            invoiceheaderclone.Invoice_Request__c= null;
          //invoiceheaderclone.Invoice_Comments__c= '';//printable Note SSE-6226:commented by ritika
     
            invoiceheaderclone.Alternative_Responsible_Code_1__c= null;
            invoiceheaderclone.Manual_Transfer__c= true;
            invoiceheaderclone.Sales_Type__c= null;
           // invoiceheaderclone.Invoice_Header_Comments__c='';//extended comments:SSE-6226:commented by ritika
          
          invoiceheaderclone.SunSystems_Order_Reference__c= null;
           invoiceheaderclone.RecordTypeId  =editRecTypeId ;//SSE-6226:added by ritika
            invoiceheaderclone.SFDC2SUN_Log__c= null;
            invoiceheaderclone.SFDC2SUN_Transferred_By__c=null;
           invoiceheaderclone.SFDC2SUN_Transferred_On__c=null;
            invoiceheaderclone.SFDC2SUN_Transfer_Status__c='';
                           
        return invoiceheaderclone;
        
    }
    
    //This method accepts the Id of an Invoice Header as input, retreives the list of Invoice Lines related to the Invoice Header corresponding to this Id from the database and returns a cloned list of the retrieved Invoice Lines 
    private static List<Contract_Invoice_Line__c> createCloneOfContractInvoiceLines(String invoiceHeaderId)
    {
        //Create a string all creatable fields of the Invoice Line object
        String contractInvoiceLineFieldsString = getObjectFieldsString(Schema.SObjectType.Contract_Invoice_Line__c.fields.getMap());
        //Create a string of the Query required to fetch the Invoice Lines to be cloned using the above string of Invoice Line fields
        String contractInvoiceLineQuery = String.format('SELECT {0},CurrencyIsoCode FROM Contract_Invoice_Line__c WHERE Invoice_Header_ID__c ={1}',new String[]{contractInvoiceLineFieldsString,'\''+invoiceHeaderId+'\''});
        //Retreive the list of Invoice Lines to be cloned by executeing the query created above
        List<Contract_Invoice_Line__c> invoiceLineList = DataBase.query(contractInvoiceLineQuery);
       
        //Return a cloned list of the Invoice Lines reterieved above
        return invoiceLineList.deepClone(false);
    }
    
    //This method accepts the Month of the Invoice Line, increments the month by 1 and return the incremented month
    private static String incrementInvoiceLineMonth(String invoiceLineMonth)
    {
        //Check if the length of Month is not equal to 6 
        if(invoiceLineMonth.length()==6)
        {
            //If yes, then create a Datetime variable for the Month String 
            Datetime invoiceLineDate = Datetime.newInstance(integer.valueOf(invoiceLineMonth.substring(0,4)), integer.valueOf(invoiceLineMonth.substring(4,6)), 10);
            //Add 1 month to the Datetime variable create above
            invoiceLineDate = invoiceLineDate.addMonths(1);
            //Return the incremented Datetime variable in the form of a string of format 'yyyyMM'
            return invoiceLineDate.format('yyyyMM');
        }
        else
            //If no, then return a null value so that an approriate error message can be thrown
            return null;
    }
    
    //This method accepts the a Map of object fields as an input, creates a comma delimited string of these fields and returns this string of fields
    private static String getObjectFieldsString(Map<String, Schema.SObjectField> objectFieldsMap)
    {
        //Create an empty string of Fields
        string fieldsString = ''; 
        //Iterate through each Field of the Fields Map
        for(Schema.SObjectField field:objectFieldsMap.values())
        {
            //Get the schema description of the current Field
            Schema.DescribeFieldResult fieldDesc = field.getDescribe();
            //Check if the field is creatable and it doesn't have a default value
            if(fieldDesc.isCreateable()==true && fieldDesc.isDefaultedOnCreate()==false)
                //If yes, then append the name of this field to the string of fields followed by a comma 
                fieldsString += fieldDesc.getName() + ',';
        }
        //Return the string of fields generated above after removing the last comma
        return fieldsString.subString(0,fieldsString.lastIndexOf(','));
    }
    
    
}