objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Same_As_The_Account_Billing_Address__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If this option is selected, then the Contact Mailing Address is copied from the Account Billing Address.</description>
        <inlineHelpText>Check this box to set the Contact Address to the same as the Account Billing Address. This address will not be populated from the Account until you hit Save. You must ensure this box is not ticked if you want to enter a different address for the Contact.</inlineHelpText>
        <label>Same As The Account Billing Address</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

force-app/main/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Activated_Date__c</fullName>
        <description>New custom field for Activated Date which will be hidden on Page layouts</description>
        <label>Activated Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Agreement__c</fullName>
        <label>Agreement</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Standard</fullName>
                    <default>true</default>
                    <label>Standard</label>
                </value>
                <value>
                    <fullName>Standard MA</fullName>
                </value>
                <value>
                    <fullName>Non-Standard</fullName>
                </value>
                <value>
                    <fullName>Non-Standard MA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Final_Submission_Date_EST__c</fullName>
        <label>Submitted to OATs(Legacy)</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Legal_Order_Name__c</fullName>
        <label>Legal Order Name(Legacy)</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>S2P_Reference_Required__c</fullName>
        <description>Check on the S2P Reference.</description>
        <inlineHelpText>Choose new if system referenced in the order does not currently exist, otherwise choose Existing</inlineHelpText>
        <label>System Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Existing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Submission_Offset__c</fullName>
        <label>Submission Offset</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Subscription_Start_Date__c</fullName>
        <inlineHelpText>This date should be the same as the Contract Start Date unless delay has been approved in CLM.</inlineHelpText>
        <label>Product Subscription Start Date</label>
        <type>Date</type>
    </fields>
</CustomObject>

force-app/main/objects/Order.object
<CustomObject>
    <fields>
        <fullName>Submission_Offset__c</fullName>
        <label>Submission Offset</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

classes/RestrictAttachmentdeleteOrder_TestClass.cls
@isTest(SeeAllData=true)
public class RestrictAttachmentdeleteOrder_TestClass
{public static Account account;
public static List<Contact> contacts;
      public static testMethod void testTriggers()
      {
        Contract contract = new Contract();
        
        Account a = new Account();
            //Schema.sObjectType t = a.getSObjectType();
            //List<account> a1 = Test.loadData(t, 'AccountTestData');
            //Get first test account
            account = TestDataUtility.getAccount();
            account.name = 'RestrictAttachmentdeleteOrder_TestClass';
            insert account;
             Contact contact = new Contact(AccountId=account.Id,LastName='test12345',email='test12345@test.com',phone='2345345345',Same_As_The_Account_Billing_Address__c=true);
        contacts = new List<Contact>();
        contacts.add(contact);
        insert contacts;
        contract.AccountId = account.Id;  
        contract.Legal_Order_Name__c = 'test'; 
        contract.CurrencyIsoCode = account.CurrencyIsoCode;
        contract.S2P_Reference_Required__c = 'New';
        contract.Status = 'Draft';
        contract.CustomerSignedDate = Date.Today();
        contract.StartDate = Date.Today();
        contract.ContractTerm = 6;   
        contract.Activated_Date__c=datetime.now();
        contract.Final_Submission_Date_EST__c=datetime.now().addDays(-2);
        contract.Submission_Offset__c = 10;
        contract.Agreement__c = 'Order';
        contract.Subscription_Start_Date__c = Date.Today();
        insert contract;
        
        Attachment attach = new Attachment();
        attach.Name='Unit Test Attachment';
        Blob bodyBlob=Blob.valueOf('Unit Test Attachment Body');
        attach.body=bodyBlob; 
        attach.parentId = contract.id;
        insert attach;
        delete attach;
        
        
}

}