objects/Contract_Line__c.object
<CustomObject>
    <description>Order Management</description>
    <fields>
        <fullName>Original_Order_Line__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Original Order Line</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Original_Order__c</field>
                <operation>equals</operation>
                <valueField>Contract_Line__c.Contract__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contract_Line__c</referenceTo>
        <relationshipLabel>Variation Order Lines</relationshipLabel>
        <relationshipName>Order_Line</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Line Price</label>
        <precision>11</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Running_Total__c</fullName>
        <description>This field will be sum of price on original order line and price of related/linked variation order lines.</description>
        <label>Running Total</label>
        <precision>11</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Variation_Order__c</fullName>
        <formula>Contract__r.Variation_Order__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Variation Order</label>
        <type>Text</type>
    </fields>
    <label>Order Line</label>
    <nameField>
        <displayFormat>CLN{0000000}</displayFormat>
        <label>Order Line</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Line</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ContractLineTriggerManager_7.cls
/**************************************************************************************************************************************
CREATED BY :- Virendra Kumar
CREATED DATE :- 29-07-2019
DESCRIPTION :-  This class contains ContractLine trigger related functionalities :  after insert, after update(running total field update)
***************************************************************************************************************************************/
public class ContractLineTriggerManager_7{
    //This method contains the logic for Updation of running total filed as per line price.
    public static void runningtotalfieldUpdate(Set<Id> ContractLineList)
    {
    system.debug('ContractLineList_7'+ContractLineList);
    map<Contract_Line__c, Double> Orderlineprice=new map<Contract_Line__c, Double>();
    list<Contract_Line__c> Contractlineinnerlist = new list<Contract_Line__c>();
         //Below code added against the CRI - 1203 implementation. Below code fetches all the original order lines and update the running total field whenever there is a change in price of the variation order lines.
    List<Contract_Line__c> orderlinesList = [Select id, Price__c,Running_Total__c,(Select id,Price__c from Order_Line__r where
     Variation_Order__c = 'Yes') from Contract_Line__c where id in :ContractLineList];
   
   if(orderlinesList.size()>0)
    {
        for(Contract_Line__c orderLine:orderlinesList)
        {
            orderLine.Running_Total__c = orderLine.Price__c;
            if(orderLine.Order_Line__r.size()>0)
            {
                for(Contract_Line__c ordLine:orderLine.Order_Line__r)
                {
                    orderLine.Running_Total__c += ordLine.Price__c;
                }
            }
        }
        update orderlinesList;
    }
    
    }
    }