objects/Contract_Invoice_Header__c.object
<CustomObject>
    <description>Invoice Header on Contract Object</description>
    <fields>
        <fullName>Contract_Line__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup Reltionship to Help pull fields over from Contract Line to Invoice Header</description>
        <label>Order Line</label>
        <referenceTo>Contract_Line__c</referenceTo>
        <relationshipLabel>Invoice Headers</relationshipLabel>
        <relationshipName>Invoice_Headers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Invoice_Status__c</fullName>
        <description>Invoice status. This includes all invoice lines below.</description>
        <label>Invoice Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Draft - awaiting milestones</fullName>
                </value>
                <value>
                    <fullName>On Hold for Payment Milestone</fullName>
                </value>
                <value>
                    <fullName>Cross Border</fullName>
                </value>
                <value>
                    <fullName>Queried</fullName>
                </value>
                <value>
                    <fullName>Awaiting PO</fullName>
                </value>
                <value>
                    <fullName>Awaiting GST/VAT Info</fullName>
                </value>
                <value>
                    <fullName>Awaiting Chop</fullName>
                </value>
                <value>
                    <fullName>No Usage</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Ready to Invoice</fullName>
                </value>
                <value>
                    <fullName>Ready for SOE Review</fullName>
                </value>
                <value>
                    <fullName>Ready for Sun Transfer</fullName>
                </value>
                <value>
                    <fullName>Transferring to Sun</fullName>
                </value>
                <value>
                    <fullName>Sun Order Complete</fullName>
                </value>
                <value>
                    <fullName>Sun Invoice Complete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Invoice Header</label>
    <nameField>
        <displayFormat>CIH{0000000}</displayFormat>
        <label>Invoice Header ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Headers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Contract_Invoice_Line__c.object
<CustomObject>
    <description>One or more lines that make up the Invoice Request</description>
    <fields>
        <fullName>Contract_Line_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order Line ID (Legacy)</label>
        <referenceTo>Contract_Line__c</referenceTo>
        <relationshipLabel>Invoice Lines</relationshipLabel>
        <relationshipName>Invoice_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contract_Line_Price__c</fullName>
        <description>Price from Contract Line</description>
        <formula>Order_Product_Id__r.Quantity * Order_Product_Id__r.UnitPrice</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Order Product Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>IM_Lookup_Code_For_Filter__c</fullName>
        <description>this field is used to filter the rollup field</description>
        <label>IM Lookup Code For Filter</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IM_Lookup_Code__c</fullName>
        <description>IM Lookup Code from Contract Line</description>
        <formula>Order_Product_Id__r.Product2.StockKeepingUnit</formula>
        <label>IM Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Invoice_Header_ID__c</fullName>
        <label>Invoice Header ID</label>
        <referenceTo>Contract_Invoice_Header__c</referenceTo>
        <relationshipLabel>Invoice Lines</relationshipLabel>
        <relationshipName>Invoice_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Invoice_Line_Total__c</fullName>
        <label>Invoice Line Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Order_Line_Item__c</fullName>
        <label>Order Product &amp; Service</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Platform__c</fullName>
        <label>Platform</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <inlineHelpText>Only enter a price if you wish to override the calculated price</inlineHelpText>
        <label>Override Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <inlineHelpText>Only enter a quantity if you wish to change the calculated quantity</inlineHelpText>
        <label>Override Quantity</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Usage_Allowance__c</fullName>
        <label>Usage Allowance</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Invoice Line</label>
    <nameField>
        <displayFormat>CIL{0000000}</displayFormat>
        <label>Invoice Line ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Contract_Line__c.object
<CustomObject>
    <description>Order Management</description>
    <fields>
        <fullName>IM_Lookup_Code__c</fullName>
        <label>Order Line Item</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Order_Method__c</controllingField>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>360 Platform Set up</fullName>
                </value>
                <value>
                    <fullName>360 Subscription</fullName>
                </value>
                <value>
                    <fullName>Advisory Services Subscription</fullName>
                </value>
                <value>
                    <fullName>AM Aptitude (In Arrears)</fullName>
                </value>
                <value>
                    <fullName>AM Coding (In Arrears)</fullName>
                </value>
                <value>
                    <fullName>AM Generic (In Arrears)</fullName>
                </value>
                <value>
                    <fullName>AM Language (In Arrears)</fullName>
                </value>
                <value>
                    <fullName>AM Personal &amp; Behavioural (In Arrears)</fullName>
                </value>
                <value>
                    <fullName>AM Pool Hiring (In Arrears)</fullName>
                </value>
                <value>
                    <fullName>AM Proctoring (In Arrears)</fullName>
                </value>
                <value>
                    <fullName>AM Product Subscription</fullName>
                </value>
                <value>
                    <fullName>AM Professional Services</fullName>
                </value>
                <value>
                    <fullName>AM Skills: Analytics (In Arrears)</fullName>
                </value>
                <value>
                    <fullName>AM Skills: Banking and Financial Serv (In Arrears)</fullName>
                </value>
                <value>
                    <fullName>AM Skills: Customer Service, Contact Center and BPO (In Arrears)</fullName>
                </value>
                <value>
                    <fullName>AM Skills: Engineering (In Arrears)</fullName>
                </value>
                <value>
                    <fullName>AM Skills: Finance and Accounting (In Arrears)</fullName>
                </value>
                <value>
                    <fullName>AM Skills: Healthcare, Pharma and Life Sciences (In Arrears)</fullName>
                </value>
                <value>
                    <fullName>AM Skills: Human Resources, Marketing and Operations (In Arrears)</fullName>
                </value>
                <value>
                    <fullName>AM Skills: MS Office (In Arrears)</fullName>
                </value>
                <value>
                    <fullName>AM Skills: Sales and Business Development (In Arrears)</fullName>
                </value>
                <value>
                    <fullName>AM Skills: Sciences (In Arrears)</fullName>
                </value>
                <value>
                    <fullName>AM Skills: Technology (In Arrears)</fullName>
                </value>
                <value>
                    <fullName>AM Skills: Tourism and Hospitality (In Arrears)</fullName>
                </value>
                <value>
                    <fullName>AM Video (In Arrears)</fullName>
                </value>
                <value>
                    <fullName>Application Analytics Subscription</fullName>
                </value>
                <value>
                    <fullName>Bureau</fullName>
                </value>
                <value>
                    <fullName>Candidate Support – Bronze</fullName>
                </value>
                <value>
                    <fullName>Candidate Support for Subscription</fullName>
                </value>
                <value>
                    <fullName>Candidate Support –  Gold</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Platform__c</fullName>
        <label>Platform</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Brainbench</fullName>
                </value>
                <value>
                    <fullName>iAssess</fullName>
                </value>
                <value>
                    <fullName>MFS</fullName>
                </value>
                <value>
                    <fullName>MS</fullName>
                </value>
                <value>
                    <fullName>Nacho</fullName>
                </value>
                <value>
                    <fullName>Precise Fit Modules</fullName>
                </value>
                <value>
                    <fullName>S2P</fullName>
                </value>
                <value>
                    <fullName>SODA</fullName>
                </value>
                <value>
                    <fullName>Sunstone</fullName>
                </value>
                <value>
                    <fullName>Talent Central</fullName>
                </value>
                <value>
                    <fullName>Valtera</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Line Price</label>
        <precision>11</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>7</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Usage_Allowance__c</fullName>
        <label>Usage Allowance</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Capped</fullName>
                </value>
                <value>
                    <fullName>Uncapped</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Order Line</label>
    <nameField>
        <displayFormat>CLN{0000000}</displayFormat>
        <label>Order Line</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Line</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ContractLineTriggerManager_6.cls
/**************************************************************************************************************************************
CREATED BY :- Virendra Kumar
CREATED DATE :- 29-07-2019
DESCRIPTION :-  This class contains ContractLine trigger related functionalities :  after update(Invoice Line Field Update)
***************************************************************************************************************************************/
public class ContractLineTriggerManager_6{
/* This method helps in updating Invoice line fields when:
    1. New Line price is not equal to old line price & quantity !=null.
    2. If new and old values of IM_Lookup_Code__c Platform__cUsage_Allowance__c are not same and Invoice Header's Status in 'Draft' , cross border, Queried, Cancelled, awaiting po, No      
         Usage then set invoice line's platform, usage allowance, order line  item
*/
public static void invoiceLineFieldupdate(list<Contract_Line__c> ContractlineNewlist,Map<Id,Contract_Line__c> ContractlineNewmaplist,list<Contract_Line__c> ContractlineOldlist,Map<Id,Contract_Line__c> ContractlineOldmaplist   )
{
  Set<Id> contractLineIds = new Set<Id>();
    Set<Id> updatedIMLookupOnOLI = new Set<Id>();
    Map<String, Decimal> m = new Map<String, Decimal>();  // Added for SSE-5399
    List<Contract_Invoice_Line__c> contractInvoiceLines = new List<Contract_Invoice_Line__c>();
    for (integer i=0;i<ContractlineNewlist.size();i++)
    {
        if(ContractlineNewlist[i].Price__c != ContractlineOldlist[i].Price__c)
            contractLineIds.add(ContractlineNewlist[i].Id);
            m.put(ContractlineNewlist[i].name,ContractlineNewlist[i].Price__c);    // Added for SSE-5399
            System.debug('mapid ' + m);
        if(ContractlineNewlist[i].IM_Lookup_Code__c != ContractlineOldlist[i].IM_Lookup_Code__c || ContractlineNewlist[i].Platform__c!=ContractlineOldlist[i].Platform__c || ContractlineNewlist[i].Usage_Allowance__c != ContractlineOldlist[i].Usage_Allowance__c)         
            updatedIMLookupOnOLI.add(ContractlineNewlist[i].Id);
    }
   
    contractInvoiceLines = [SELECT Id,Quantity__c,Contract_Line_ID__c,Contract_Line_ID__r.name,Contract_Line_Price__c,Price__c,Invoice_Line_Total__c from Contract_Invoice_Line__c WHERE Contract_Line_ID__c IN:contractLineIds];  
    // Added by pankhuri on 1 Nov 2017 for SSE-5399
    System.debug('List** ' + contractInvoiceLines); 
    for(Contract_Invoice_Line__c cv: contractInvoiceLines){
    
        System.debug('Price** '+ cv.Price__c);
        System.debug('Name** ' + m.get(cv.Contract_Line_ID__r.name));
        
        if(cv.Quantity__c == null){
           cv.Quantity__c = 0;
        }
        if(cv.Price__c != null && cv.Quantity__c != null){
            cv.Invoice_Line_Total__c = cv.Quantity__c * cv.Price__c;  
            System.debug('Total1 '+ cv.Invoice_Line_Total__c);        
        }
        else
            cv.Invoice_Line_Total__c = cv.Quantity__c * m.get(cv.Contract_Line_ID__r.name);
            System.debug('Total2 '+ cv.Invoice_Line_Total__c);
     // end
    }
    update contractInvoiceLines;
    
    if(updatedIMLookupOnOLI.size()>0){
        List<Contract_Invoice_Line__c> updatedInvoiceLine = new List<Contract_Invoice_Line__c>();
        for(Contract_Invoice_Line__c cil : [select id,IM_Lookup_Code_For_Filter__c,Invoice_Header_ID__r.Invoice_Status__c ,Contract_Line_ID__c from Contract_Invoice_Line__c where Contract_Line_ID__c IN: updatedIMLookupOnOLI]){
            //if (cil.Invoice_Header_ID__r.Invoice_Status__c  != 'Transferred to Infor10' && cil.Invoice_Header_ID__r.Invoice_Status__c  != 'Invoice Complete' )
            if (cil.Invoice_Header_ID__r.Invoice_Status__c  == 'Draft' || cil.Invoice_Header_ID__r.Invoice_Status__c  == 'Cross Border' || cil.Invoice_Header_ID__r.Invoice_Status__c  == 'Queried' || cil.Invoice_Header_ID__r.Invoice_Status__c  == 'Cancelled' || cil.Invoice_Header_ID__r.Invoice_Status__c  == 'Awaiting PO' || cil.Invoice_Header_ID__r.Invoice_Status__c  == 'No Usage' )   // SSE-5643
            {
                 cil.Platform__c = ContractlineNewmaplist.get(cil.Contract_Line_ID__c).Platform__c;
                 cil.Usage_Allowance__c = ContractlineNewmaplist.get(cil.Contract_Line_ID__c).Usage_Allowance__c;
                 cil.Order_Line_Item__c = ContractlineNewmaplist.get(cil.Contract_Line_ID__c).IM_Lookup_Code__c;
                 cil.IM_Lookup_Code_For_Filter__c = ContractlineNewmaplist.get(cil.Contract_Line_ID__c).IM_Lookup_Code__c;
                 updatedInvoiceLine.add(cil);
            }
            else if(ContractlineNewmaplist.get(cil.Contract_Line_ID__c).IM_Lookup_Code__c != ContractlineOldmaplist.get(cil.Contract_Line_ID__c).IM_Lookup_Code__c )
            {
                cil.IM_Lookup_Code_For_Filter__c = ContractlineNewmaplist.get(cil.Contract_Line_ID__c).IM_Lookup_Code__c;
                updatedInvoiceLine.add(cil);
            }
            
        }
        if(updatedInvoiceLine.size()>0){
            update updatedInvoiceLine;
        }
    }
    }
}