objects/Expense__c.object
<CustomObject>
    <fields>
        <fullName>Project_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Expenses2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>ProjectObject__c</referenceTo>
        <relationshipLabel>Expenses</relationshipLabel>
        <relationshipName>Expenses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>Processed</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                    <default>true</default>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>Submitted for Processing</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Expense</label>
    <nameField>
        <displayFormat>E{000000}</displayFormat>
        <label>Expense Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expenses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ProjectObject__c.object
<CustomObject>
    <description>Used for PSA work</description>
    <fields>
        <fullName>Project_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Manager</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>User.Is_Project_Manager__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>$User.Id</field>
                <operation>equals</operation>
                <value>0054G00000CSIBq</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project</label>
    <nameField>
        <displayFormat>P{000000}</displayFormat>
        <label>Project Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <recordTypes>
        <fullName>Project</fullName>
        <active>true</active>
        <label>Project</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/objects/User.object
<CustomObject>
    <fields>
        <fullName>PSA_Role__c</fullName>
        <description>This specifies the role that the user should be assigned as per the PSA Securit y Model.</description>
        <inlineHelpText>Specify the role that the user should be assigned as per the PSA Securit y Model.</inlineHelpText>
        <label>PSA Role</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>User</fullName>
                </value>
                <value>
                    <fullName>Project Manager</fullName>
                </value>
                <value>
                    <fullName>PSA Lead</fullName>
                    <default>true</default>
                    <label>PSA Lead</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

classes/ExpenseTriggerManager.cls
/*****************************************************************************
CREATED BY :- Prabhat Arora
CREATED DATE :- 22-07-2019
DESCRIPTION :- This class contains various Methods/Checks/Assignments to controll Expense Functionality as per SHL business process,
               this class is being refered from Expense_Trigger, covering all the Before/After, Insert/Delete & Update Events on Expense Records. 
******************************************************************************/


public class ExpenseTriggerManager {
    //Getting Project Manager from Project
    public static void copyDataFromProject(List<Expense__c> expenses){
        Set<Id> projectIds = new Set<Id>();
        for(Expense__c expense: expenses)
            if(!projectIds.contains(expense.Project__c))
            projectIds.add(expense.Project__c);
        Map<Id, ProjectObject__c> projectsMap = new Map<Id, ProjectObject__c>([SELECT Id, Project_Manager__c FROM ProjectObject__c WHERE id IN :projectIds]);
        for(Expense__c expense: expenses)
            expense.Project_Manager__c = projectsMap.get(expense.Project__c).Project_Manager__c;
    }
    //Restricting the Editing of Expenses if User role is not PSA Lead
    public static void RestrictExpenseEdit(List<Expense__c> NewExpenseList,List<Expense__c> OldExpenseList){
        User user = [SELECT Id, PSA_Role__c FROM User WHERE Id= :UserInfo.getUserId()];
        for(Integer i=0; i<NewExpenseList.size(); i++){
        //If the status of the expense has not changed.
            if(OldExpenseList[i].Status__c==NewExpenseList[i].Status__c){
                if(NewExpenseList[i].Status__c=='Approved' && user.PSA_Role__c!='PSA Lead')
                NewExpenseList[i].addError('You do not have permissions to modify this expense');
            }
        }
    }
    //Restricting the Editing of Expenses if User role is not PSA Lead, throw error.
    public static void RestrictExpenseDelete(List<Expense__c> OldExpenseList){
        User user = [SELECT Id, PSA_Role__c FROM User WHERE Id= :UserInfo.getUserId()];
        for(Integer i=0; i<OldExpenseList.size(); i++){
            if(OldExpenseList[i].Status__c=='Approved' && user.PSA_Role__c!='PSA Lead')
            OldExpenseList[i].addError('You do not have permissions to delete this expense');
        }
    }
}