objects/Invoice_Billing_Detail__c.object
<CustomObject>
    <fields>
        <fullName>Invoice_Request__c</fullName>
        <label>Invoice Request</label>
        <referenceTo>Project_Invoice__c</referenceTo>
        <relationshipLabel>PS Invoice Billing Details</relationshipLabel>
        <relationshipName>Invoice_Billing_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Order_Number__c</fullName>
        <label>Order Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order_Product_Id__c</fullName>
        <label>Order Product Id</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Invoice Billing Details</relationshipLabel>
        <relationshipName>Invoice_Billing_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Invoice Billing Detail</label>
    <nameField>
        <displayFormat>PS-INV-{0000}</displayFormat>
        <label>PS Billing Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Billing Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/objects/OrderItem.object
<CustomObject>
    <fields>
        <fullName>Invoice_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Invoice Request #</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Project__c</field>
                <operation>equals</operation>
                <valueField>Project_Invoice__c.Project__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Project_Invoice__c</referenceTo>
        <relationshipLabel>Order Products</relationshipLabel>
        <relationshipName>Order_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Package__c</fullName>
        <label>Offering Details</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Graduate Essential</fullName>
                </value>
                <value>
                    <fullName>Graduate Advanced</fullName>
                </value>
                <value>
                    <fullName>Graduate Ultimate</fullName>
                </value>
                <value>
                    <fullName>Volume Essential</fullName>
                </value>
                <value>
                    <fullName>Volume Advanced</fullName>
                </value>
                <value>
                    <fullName>Apprentice Essential</fullName>
                </value>
                <value>
                    <fullName>Tech Essential</fullName>
                </value>
                <value>
                    <fullName>Tech Advanced</fullName>
                </value>
                <value>
                    <fullName>Managerial Essential</fullName>
                </value>
                <value>
                    <fullName>Managerial Advanced</fullName>
                </value>
                <value>
                    <fullName>Managerial Ultimate</fullName>
                </value>
                <value>
                    <fullName>Video Essential</fullName>
                </value>
                <value>
                    <fullName>Video Advanced</fullName>
                </value>
                <value>
                    <fullName>Video Ultimate</fullName>
                </value>
                <value>
                    <fullName>Professional Essential</fullName>
                </value>
                <value>
                    <fullName>Professional Advanced</fullName>
                </value>
                <value>
                    <fullName>Professional Ultimate</fullName>
                </value>
                <value>
                    <fullName>Product</fullName>
                </value>
                <value>
                    <fullName>Mobilize Essential</fullName>
                </value>
                <value>
                    <fullName>Mobilize Advanced</fullName>
                </value>
                <value>
                    <fullName>Mobilize Ultimate</fullName>
                </value>
                <value>
                    <fullName>Sales Transformation Hiring Essential</fullName>
                </value>
                <value>
                    <fullName>Sales Transformation Hiring Advanced</fullName>
                </value>
                <value>
                    <fullName>Sales Transformation Hiring Ultimate</fullName>
                </value>
                <value>
                    <fullName>Sales Transformation Review Essential</fullName>
                </value>
                <value>
                    <fullName>Sales Transformation Review Advanced</fullName>
                </value>
                <value>
                    <fullName>Sales Transformation Review Ultimate</fullName>
                </value>
                <value>
                    <fullName>Service</fullName>
                </value>
                <value>
                    <fullName>OA 1:1 Essential</fullName>
                </value>
                <value>
                    <fullName>OA 1:1 Advanced</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Platform__c</fullName>
        <label>Platform</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>iAssess</fullName>
                </value>
                <value>
                    <fullName>MFS</fullName>
                </value>
                <value>
                    <fullName>Talent Central</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>ProjectObject__c</referenceTo>
        <relationshipLabel>Order Products</relationshipLabel>
        <relationshipName>Order_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Proposition__c</fullName>
        <label>Use-case</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Volume Hiring</fullName>
                </value>
                <value>
                    <fullName>Technology Hiring</fullName>
                </value>
                <value>
                    <fullName>Managerial Hiring</fullName>
                </value>
                <value>
                    <fullName>Senior Leadership / Executive Hiring </fullName>
                </value>
                <value>
                    <fullName>Professional Hiring</fullName>
                </value>
                <value>
                    <fullName>Talent Management</fullName>
                </value>
                <value>
                    <fullName>Early Careers Hiring</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Service_End_Date__c</fullName>
        <label>PS Service End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Source_of_PS_Scoping__c</fullName>
        <label>Source of PS Scoping</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>E2E Scoping Tool</fullName>
                </value>
                <value>
                    <fullName>Other Existing Pricing Calculator</fullName>
                </value>
                <value>
                    <fullName>Other Scoping Template</fullName>
                </value>
                <value>
                    <fullName>None Available</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Total_Price__c</fullName>
        <formula>Quantity  *  UnitPrice</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
</CustomObject>

force-app/main/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Beta</fullName>
                </value>
                <value>
                    <fullName>Revenue Ready</fullName>
                    <default>true</default>
                    <label>Revenue Ready</label>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
                <value>
                    <fullName>End of Life</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

objects/Project_Invoice__c.object
<CustomObject>
    <description>Represents the invoice generated for the Time &amp; Expenses of a Project.</description>
    <fields>
        <fullName>Credit__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>All values for credit notes must be entered as negative values in the ‘Amount to be invoiced’ fields below.
Enter the PO Number of the Invoice Request to be credited in the PO Number field above.</inlineHelpText>
        <label>Credit</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <description>Project to which this invoice belongs</description>
        <label>Project</label>
        <referenceTo>ProjectObject__c</referenceTo>
        <relationshipLabel>Invoice Requests</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Invoice Request Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>In Progress</fullName>
                    <default>true</default>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>Submitted for Processing</fullName>
                </value>
                <value>
                    <fullName>Processed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TotalAmount_Product__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Order Product Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Invoice Request</label>
    <nameField>
        <displayFormat>Inv{000000}</displayFormat>
        <label>Invoice Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ProjectObject__c.object
<CustomObject>
    <description>Used for PSA work</description>
    <fields>
        <fullName>Platform__c</fullName>
        <label>Platform</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>P41</fullName>
                </value>
                <value>
                    <fullName>SODA</fullName>
                </value>
                <value>
                    <fullName>DSPS</fullName>
                </value>
                <value>
                    <fullName>Nacho</fullName>
                </value>
                <value>
                    <fullName>MFS</fullName>
                </value>
                <value>
                    <fullName>OAS</fullName>
                </value>
                <value>
                    <fullName>ORS</fullName>
                </value>
                <value>
                    <fullName>Values@work</fullName>
                </value>
                <value>
                    <fullName>CCQ</fullName>
                </value>
                <value>
                    <fullName>ASO Stand-alone</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project</label>
    <nameField>
        <displayFormat>P{000000}</displayFormat>
        <label>Project Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <recordTypes>
        <fullName>Project</fullName>
        <active>true</active>
        <label>Project</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/objects/PS_Order_Product__c.object
<CustomObject>
    <fields>
        <fullName>Invoice_Request__c</fullName>
        <label>Invoice Request</label>
        <referenceTo>Project_Invoice__c</referenceTo>
        <relationshipLabel>PS Order Products</relationshipLabel>
        <relationshipName>PS_Order_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Order_Number__c</fullName>
        <formula>HYPERLINK(&apos;/&apos;+Order_Product__r.Order.Id, Order_Product__r.Order.OrderNumber,&apos;_self&apos;)</formula>
        <label>Order Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order_Product__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Order Product</label>
        <referenceTo>OrderItem</referenceTo>
        <relationshipLabel>PS Order Products</relationshipLabel>
        <relationshipName>PS_Order_Products</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Package__c</fullName>
        <formula>TEXT( Order_Product__r.Package__c)</formula>
        <label>Solution</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Platform__c</fullName>
        <formula>TEXT(Order_Product__r.Platform__c)</formula>
        <label>Platform</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Proposition__c</fullName>
        <formula>TEXT( Order_Product__r.Proposition__c)</formula>
        <label>Use-case</label>
        <type>Text</type>
    </fields>
    <label>PS Order Product</label>
    <nameField>
        <displayFormat>PS-OP-{0000}</displayFormat>
        <label>PS Order Product Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PS Order Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/OrderProductsOnInvoiceRequestController.cls
public class OrderProductsOnInvoiceRequestController {
    public List<orderitem> orderItemList{get;set;}
    public boolean selected{get;set;}
    public string InvoiceRequestId {get;set;}
    public List<wrapOrderItem> wrapOrderItemList {get; set;}
    public List<orderitem> selectedOrderItem{get;set;}
    public List<orderitem> ordelinesToUpdate{get;set;}
    public List<Invoice_Billing_Detail__c> InvoiceBillingDetails;
    public List<Invoice_Billing_Detail__c> RelatedInvoiceBillingDetails;
    public List<Invoice_Billing_Detail__c> InvoiceBillingDetailstoDelete;
    public List<PS_Order_Product__c> PSOrderProductstoAdd;
    public List<PS_Order_Product__c> PSOrderProductstoDelete;
    public List<PS_Order_Product__c> RelatedPSOrderProducts;
    public List<PS_Order_Product__c> LatestPSOrderProducts;
    public Project_Invoice__c InvoiceRequest{get;set;}
    
    public OrderProductsOnInvoiceRequestController() {
        InvoiceRequestId=ApexPages.currentPage().getParameters().get('InvoiceRequest');
        System.debug('This is project id: '+ApexPages.currentPage().getParameters().get('Project'));
        System.debug('This is inovice request id: '+ApexPages.currentPage().getParameters().get('InvoiceRequest'));
        InvoiceRequest = [select id,TotalAmount_Product__c,Credit__c,CurrencyIsoCode,Status__c from Project_Invoice__c where id=:InvoiceRequestId];
        RelatedInvoiceBillingDetails = [select Id,Invoice_Request__c,Product__c,Order_Number__c,Order_Product_Id__c from Invoice_Billing_Detail__c where Invoice_Request__c=:InvoiceRequestId];
        RelatedPSOrderProducts = [select Id,Invoice_Request__c,Order_Product__c from PS_Order_Product__c where Invoice_Request__c=:InvoiceRequestId];
        if(wrapOrderItemList==null){
            wrapOrderItemList=new List<wrapOrderItem>();
            For(OrderItem op:[select id,Project__c,Product2.name,Product2.StockKeepingUnit,Quantity,UnitPrice,Order.OrderNumber,Invoice_Request__c, Proposition__c,Package__c,TotalPrice,Platform__c,Source_of_PS_Scoping__c,Service_End_Date__c from OrderItem where Project__r.name=:ApexPages.currentPage().getParameters().get('Project')])
                wrapOrderItemList.add(new wrapOrderItem(op,RelatedPSOrderProducts));
        }
    }
    public PageReference AddProducts(){
        system.debug('wrapOrderItemList'+wrapOrderItemList);
        selectedOrderItem = new List<orderitem>();
        ordelinesToUpdate= new List<orderitem>();
        InvoiceBillingDetails= new List<Invoice_Billing_Detail__c>();
        InvoiceBillingDetailstoDelete = new List<Invoice_Billing_Detail__c>();
        PSOrderProductstoAdd = new List<PS_Order_Product__c >();
        PSOrderProductstoDelete = new List<PS_Order_Product__c >();
        Boolean createrecord=true;
        Boolean createPSrecord=true;
        For(wrapOrderItem rec:wrapOrderItemList)
        {
            if(rec.selected==true){
                For(PS_Order_Product__c PSO: RelatedPSOrderProducts)
                {
                    if(PSO.Order_Product__c == rec.Orderitemrec.id)
                    {
                        createPSrecord=false;
                        break;
                    }
                    else
                        continue;
                } 
                
                if(createPSrecord==true)
                {
                    PS_Order_Product__c PsOrderProduct = new PS_Order_Product__c();
                    PsOrderProduct.Invoice_Request__c = ApexPages.currentPage().getParameters().get('InvoiceRequest');
                    PsOrderProduct.Order_Product__c = rec.Orderitemrec.id;
                    PsOrderProduct.CurrencyIsoCode = InvoiceRequest.CurrencyIsoCode;
                    PSOrderProductstoAdd.add(PsOrderProduct);
                }
                else
                    createPSrecord=true;
            }
            else
            {
                For(PS_Order_Product__c PSOrderproduct: RelatedPSOrderProducts)
                { 
                    if(PSOrderproduct.Order_Product__c== rec.Orderitemrec.id)
                        PSOrderProductstoDelete.add(PSOrderproduct);
                } 
            }
            
        }
        if(PSOrderProductstoAdd.size()>0)
            insert PSOrderProductstoAdd;
        if(PSOrderProductstoDelete.size()>0)
            Delete PSOrderProductstoDelete;
        LatestPSOrderProducts=[select Id,Invoice_Request__c,Order_Product__c,Total_Price__c,Order_Product__r.TotalPrice from PS_Order_Product__c where Invoice_Request__c=:InvoiceRequestId];
        For(wrapOrderItem rec:wrapOrderItemList)
        {
            if(rec.selected==true){
                For(Invoice_Billing_Detail__c IVD: RelatedInvoiceBillingDetails)
                {
                    if(IVD.Product__c == rec.Orderitemrec.Product2.id)
                    {
                        createrecord=false;
                        break;
                    }
                    else
                        continue;
                } 
                if(createrecord==true)
                {
                    Invoice_Billing_Detail__c InvoiceBillingDetail = new Invoice_Billing_Detail__c();
                    InvoiceBillingDetail.Invoice_Request__c = InvoiceRequestId;
                    InvoiceBillingDetail.IM_Code__c = rec.Orderitemrec.Product2.StockKeepingUnit;
                    InvoiceBillingDetail.Product__c = rec.Orderitemrec.Product2.id;
                    InvoiceBillingDetail.Quantity__c= rec.Orderitemrec.Quantity;
                    InvoiceBillingDetail.Order_Number__c= rec.Orderitemrec.Order.OrderNumber;
                    InvoiceBillingDetail.Order_Product_Id__c = rec.Orderitemrec.Id;
                    for(PS_Order_Product__c psorderprod:LatestPSOrderProducts)
                    {
                        if(psorderprod.Order_Product__c==rec.Orderitemrec.id)
                        {
                            if(InvoiceRequest.Credit__c==true && rec.Orderitemrec.UnitPrice>0)
                                InvoiceBillingDetail.Amount_Unit_Price__c = 0-psorderprod.Total_Price__c;
                            else
                                InvoiceBillingDetail.Amount_Unit_Price__c = psorderprod.Total_Price__c;
                            break;
                        }
                        else
                            continue;
                    }
                    InvoiceBillingDetail.CurrencyIsoCode = InvoiceRequest.CurrencyIsoCode;
                    InvoiceBillingDetails.add(InvoiceBillingDetail);
                }
                else
                    createrecord=true;
            }
            else
            {
                For(Invoice_Billing_Detail__c IVD: RelatedInvoiceBillingDetails)
                { 
                    if(IVD.Order_Product_Id__c== rec.Orderitemrec.Id)
                        InvoiceBillingDetailstoDelete.add(IVD);
                }
                
            }
        }
        if(InvoiceBillingDetails.size()>0)
            insert InvoiceBillingDetails;
        if(InvoiceBillingDetailstoDelete.size()>0)
            Delete InvoiceBillingDetailstoDelete; 
        
        UpdateInvoiceRequestProductTotal();
        ApexPages.AddMessage(new ApexPages.Message(ApexPages.Severity.CONFIRM,'Order Products added Successfully.Thank you!'));
        PageReference pg = new PageReference('/'+ApexPages.currentPage().getParameters().get('InvoiceRequest'));
        pg.setRedirect(true);
        return pg; 
    }
    public void UpdateInvoiceRequestProductTotal(){
        //List<OrderItem> OrdProdLst=[select id,TotalPrice from OrderItem where Invoice_Request__c=:InvoiceRequestId];
        InvoiceRequest.TotalAmount_Product__c=0;
        InvoiceRequest.Order_Product_count__c=0;
        for(PS_Order_Product__c PSorderprod:LatestPSOrderProducts)
        {
            InvoiceRequest.TotalAmount_Product__c = InvoiceRequest.TotalAmount_Product__c + PSorderprod.Order_Product__r.TotalPrice ;
            InvoiceRequest.Order_Product_count__c = InvoiceRequest.Order_Product_count__c+1;
        }
        update InvoiceRequest;
    }
    public class wrapOrderItem {
        
        public OrderItem Orderitemrec {get; set;}
        public Boolean selected {get; set;}
        public wrapOrderItem(OrderItem a,List<PS_Order_Product__c> RelatedPSOrderProducts ) {
            selected= false;
            Orderitemrec = a;
            for(PS_Order_Product__c PSorderproduct:RelatedPSOrderProducts)
            {
                if(PSorderproduct.order_product__c==a.id)
                {
                    selected = true;
                    break;
                }
                else
                    continue;
            }
            
        }
    }
}