objects/Invoice_Billing_Detail__c.object
<CustomObject>
    <fields>
        <fullName>Amount_Unit_Price__c</fullName>
        <label>Amount (Unit Price)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Discount_Amount__c</fullName>
        <label>Discount Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Discount_Approved_By__c</fullName>
        <formula>Invoice_Request__r.Discount_Approved_By__r.FirstName +&apos; &apos;+ Invoice_Request__r.Discount_Approved_By__r.LastName</formula>
        <label>Discount Approved By</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Expense_Recharge__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Expense Recharge</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>IM_Code__c</fullName>
        <label>IM Code</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Invoice_Request__c</fullName>
        <label>Invoice Request</label>
        <referenceTo>Project_Invoice__c</referenceTo>
        <relationshipLabel>PS Invoice Billing Details</relationshipLabel>
        <relationshipName>Invoice_Billing_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Invoice Billing Details</relationshipLabel>
        <relationshipName>Invoice_Billing_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Amount__c</fullName>
        <formula>( Amount_Unit_Price__c *  Quantity__c ) -  Discount_Amount__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Invoice Billing Detail</label>
    <nameField>
        <displayFormat>PS-INV-{0000}</displayFormat>
        <label>PS Billing Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Billing Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Beta</fullName>
                </value>
                <value>
                    <fullName>Revenue Ready</fullName>
                    <default>true</default>
                    <label>Revenue Ready</label>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
                <value>
                    <fullName>End of Life</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

objects/Project_Invoice__c.object
<CustomObject>
    <description>Represents the invoice generated for the Time &amp; Expenses of a Project.</description>
    <fields>
        <fullName>Credit__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>All values for credit notes must be entered as negative values in the ‘Amount to be invoiced’ fields below.
Enter the PO Number of the Invoice Request to be credited in the PO Number field above.</inlineHelpText>
        <label>Credit</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Discount_Amount__c</fullName>
        <inlineHelpText>Please enter a specific discount amount.</inlineHelpText>
        <label>Discount Amount</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Discount_Approved_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Discount Approved By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Invoice_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <description>Project to which this invoice belongs</description>
        <label>Project</label>
        <referenceTo>ProjectObject__c</referenceTo>
        <relationshipLabel>Invoice Requests</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <inlineHelpText>Please enter the quantity product sold.</inlineHelpText>
        <label>Quantity</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Invoice Request Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>In Progress</fullName>
                    <default>true</default>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>Submitted for Processing</fullName>
                </value>
                <value>
                    <fullName>Processed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Invoice Request</label>
    <nameField>
        <displayFormat>Inv{000000}</displayFormat>
        <label>Invoice Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ProjectObject__c.object
<CustomObject>
    <description>Used for PSA work</description>
    <fields>
        <fullName>Discount_Approved_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Discount Approved By</label>
        <lookupFilter>
            <active>false</active>
            <errorMessage>Discounts can only be approved by selected users.</errorMessage>
            <filterItems>
                <field>User.Approve_TE_Discounts__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Projects2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Co_ordinator__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Co-ordinator</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>User.Is_Project_Co_ordinator__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>$User.Id</field>
                <operation>equals</operation>
                <value>0054G00000CSIBq</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Projects3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Manager</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>User.Is_Project_Manager__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>$User.Id</field>
                <operation>equals</operation>
                <value>0054G00000CSIBq</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project</label>
    <nameField>
        <displayFormat>P{000000}</displayFormat>
        <label>Project Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/objects/User.object
<CustomObject>
    <fields>
        <fullName>Approve_TE_Discounts__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Check this box if this user has rights to approve T&amp;E discounts</inlineHelpText>
        <label>Approve T&amp;E Discounts</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

classes/InvoiceBillingDetailsOnIRController.cls
public class InvoiceBillingDetailsOnIRController {

    public string InvoiceRequestId {get;set;}
    public list<Invoice_Billing_Detail__c> InvoiceDetailsList{get;set;}
    public Project_Invoice__c invoice{get;set;}
    public boolean disablebutton{get;set;}
    public boolean IsSuperUser{get;set;}
    public List<SelectOption> DiscountApprovers
    {
        get
        {
            if(this.DiscountApprovers==null)
            {
                this.DiscountApprovers = new List<SelectOption>();
                this.DiscountApprovers.add(new SelectOption('','--None--'));
                for(User user: [SELECT Id, Name FROM User WHERE Approve_TE_Discounts__c =:true and isactive=:true ORDER BY Name ASC])
                    this.DiscountApprovers.add(new SelectOption(user.Id,user.Name));
            }
            return this.DiscountApprovers;
        }
        set;
    }
    public InvoiceBillingDetailsOnIRController(){
        disablebutton = false;
        IsSuperUser = false;
        InvoiceRequestId=ApexPages.currentPage().getParameters().get('InvoiceRequest');
        invoice = [select id,Discount_Approved_By__c,CurrencyISOCode,Status__c,Project__r.Project_Manager__c,Project__r.Project_Co_ordinator__c,Credit__c from Project_Invoice__c where id=:InvoiceRequestId];
        InvoiceDetailsList = [Select IM_Code__c,Quantity__c,Amount_Unit_Price__c,Discount_Amount__c,Expense_Recharge__c,Product__r.name,Total_Amount__c from Invoice_Billing_Detail__c where Invoice_Request__c=:InvoiceRequestId];
        
        List<ProjectObject__Share> Shrarerecords = [select UserOrGroupId from ProjectObject__Share where ParentId =:invoice.Project__c];
        Id Groupid;
        For(ProjectObject__Share sharingrec:Shrarerecords){
            String usergroupID = sharingrec.UserOrGroupId;
            if(usergroupID.startsWith('00G')) 
                Groupid= usergroupID;
        }
        System.debug('This is Group ID '+Groupid);
        for(GroupMember m : [Select UserOrGroupId From GroupMember Where GroupId =:Groupid]) {
            System.debug('This is group member ID '+m.UserOrGroupId);
            if(m.UserOrGroupId==UserInfo.getUserId()){
                IsSuperUser=True;
                break;
            }
        }
        System.debug('This is logged in user ID '+UserInfo.getUserId());
        System.debug('This is boolean '+IsSuperUser);
        
    }
    
    public PageReference Save(){
        disablebutton = true;
        for(Invoice_Billing_Detail__c invoicebill:InvoiceDetailsList)
        {
         if(invoice.Credit__c==true && invoicebill.Amount_Unit_Price__c>0)
          invoicebill.Amount_Unit_Price__c = 0-invoicebill.Amount_Unit_Price__c;
         else if(invoice.Credit__c==true && invoicebill.Expense_Recharge__c>0)
          invoicebill.Expense_Recharge__c = 0-invoicebill.Expense_Recharge__c;
         else 
          continue;
        }
        update InvoiceDetailsList;
        update invoice;
        ApexPages.AddMessage(new ApexPages.Message(ApexPages.Severity.CONFIRM,'Invoice Billing Details added successfully.Thank you!'));
        PageReference pg = new PageReference('/'+ApexPages.currentPage().getParameters().get('InvoiceRequest'));
        pg.setRedirect(true);
        return pg; 
    }

}