objects/Job__c.object
<CustomObject>
    <description>The entity used to identify a work request from a client to the Bureau.</description>
    <fields>
        <fullName>MS_Line_of_Business__c</fullName>
        <description>This field stores the MS- Line of business selected by the user</description>
        <label>MS - Line of Business</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>TA - Corporate</fullName>
                </value>
                <value>
                    <fullName>TA - Credentialing</fullName>
                </value>
                <value>
                    <fullName>Talent Management</fullName>
                </value>
                <value>
                    <fullName>Talent Management (Dashboards)</fullName>
                </value>
                <value>
                    <fullName>TA - Vocational (Analytics)</fullName>
                </value>
                <value>
                    <fullName>TA - Vocational (Batch)</fullName>
                </value>
                <value>
                    <fullName>TA - Vocational (School)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Job</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Job Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/SchedulableClassMock.cls
@isTest
global class SchedulableClassMock implements HttpCalloutMock{
    Integer numberRecordsProcessed;
    Integer numberRecordsFailed;
    String responseBody;
    
    global SchedulableClassMock(Integer numberRecordsProcessed, Integer numberRecordsFailed, String responseBody){
        this.numberRecordsFailed = numberRecordsFailed;
        this.numberRecordsProcessed = numberRecordsProcessed;
        this.responseBody = responseBody;
    }
    
    global HTTPResponse respond(HTTPRequest request) {
        Job__c jobObj = [SELECT Id, MS_Line_of_Business__c FROM Job__c LIMIT 1];
        HttpResponse response = new HttpResponse();
        String endpoint = request.getEndpoint();
        response.setStatusCode(200);
        if(numberRecordsFailed > 0){
            response.setBody(responseBody);
        }else{
            response.setBody(responseBody);
        }
        return response;
    }
}