objects/Job__c.object
<CustomObject>
    <description>The entity used to identify a work request from a client to the Bureau.</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Jobs</relationshipLabel>
        <relationshipName>Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Job</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Job Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/objects/Order.object
<CustomObject>
    <fields>
        <fullName>Booking_Date__c</fullName>
        <label>Booking Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Oats_Status__c</fullName>
        <label>OAT Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Status</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Queried</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Awaiting GST/VAT Info</fullName>
                </value>
                <value>
                    <fullName>Awaiting PO</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Under Legal Review</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

classes/GenericClassToGetData.cls
public class GenericClassToGetData {
    
    @AuraEnabled
    public static list<Order> getOrderData(String jobId){
        list<Order> orderData = new list<Order>();

        try{
            Id oppId = [SELECT Id, Opportunity__c FROM Job__c WHERE Id =: jobId].Opportunity__c;
            if(oppId != null){
                orderData = [SELECT 
                            Id, Name, OrderNumber, Status, Oats_Status__c, 
                            EffectiveDate, Booking_Date__c, TotalAmount, CurrencyISOCode
                            FROM Order 
                            WHERE OpportunityId =: oppId];
            }
            if(orderData.size() > 0){
                return orderData;
            }
            return new list<Order>();
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}