objects/Job__c.object
<CustomObject>
    <description>The entity used to identify a work request from a client to the Bureau.</description>
    <fields>
        <fullName>bulkJobId__c</fullName>
        <description>This field is used to store comma separated Bulk Data Job Ids for Candidate upload</description>
        <label>bulkJobId</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>Job</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Job Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Work_Request__c.object
<CustomObject>
    <description>Module to store work request generated by managed services team and submitted by client back to managed services team</description>
    <fields>
        <fullName>Job__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>System Use: To link job from where the work requests will be processed</description>
        <inlineHelpText>System Use: To link job from where the work requests will be processed</inlineHelpText>
        <label>Job</label>
        <referenceTo>Job__c</referenceTo>
        <relationshipLabel>Work Requests Submitted</relationshipLabel>
        <relationshipName>Work_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>No_of_Candidate_Created__c</fullName>
        <description>System Use: To capture the total number of canidates created from work request submission</description>
        <inlineHelpText>System Use: To capture the total number of canidates created from work request submission</inlineHelpText>
        <label>No. of Candidates Created</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>bulkJobId__c</fullName>
        <label>bulkJobId</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>Work Request</label>
    <nameField>
        <displayFormat>WR-{0000}</displayFormat>
        <label>Work Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ScheduleClassToGetJobStatusWRF.cls
public with sharing class ScheduleClassToGetJobStatusWRF implements Schedulable{
	private String workRequestId;
    private list<String> jobIds;

    public ScheduleClassToGetJobStatusWRF(String wrfId) {
        this.workRequestId = wrfId;
    }
    
    public void execute(SchedulableContext ctx) {
            Work_Request__c workRequest = [SELECT Id, Name, No_of_Candidate_Created__c, bulkJobId__c, Job__c, Status__c FROM Work_Request__c WHERE Id =: workRequestId];
            System.debug('workRequest --> '+workRequest);
            list<Id> jobIdList = new list<Id>();
            if(workRequest.bulkJobId__c != null){
                String jobbulkId = workRequest.bulkJobId__c;
                List<String> listOfJobIds = jobbulkId.split(',');
                System.debug('listOfJobIds: '+ listOfJobIds);
                //list<Id> jobIdList = new list<Id>();
                for(String a : listOfJobIds){
                    Id job_Id = Id.valueOf(a);
                    System.debug('job_Id: '+ job_Id);
                    jobIdList.add(job_Id);
                }
            }else{
                jobIdList = null;
            }
            System.debug('jobIdList: '+ jobIdList);
            Id jobID1 = System.enqueueJob(new QueueableToGetBulkJobStatusWRF(workRequest, jobIdList, 0, 0, 0, ''));
            System.abortJob(ctx.getTriggerId());

    }
}