objects/Job__c.object
<CustomObject>
    <description>The entity used to identify a work request from a client to the Bureau.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Looks up existing SFDC accounts</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>R00N20000000oB15EAE</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Name__c</fullName>
        <label>Project Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Task_Type__c</fullName>
        <description>This field is related to task created on job. It is created on Job as we want to control the field dependency on the basis of Job record type.This field is created only for Bureau Job Card</description>
        <label>Task Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Check request for all details</fullName>
                </value>
                <value>
                    <fullName>CEB Self Service Client Contact</fullName>
                </value>
                <value>
                    <fullName>Pre Setup Task / Data Cleaning</fullName>
                </value>
                <value>
                    <fullName>Follow Up - See Comments</fullName>
                </value>
                <value>
                    <fullName>Project Setup</fullName>
                </value>
                <value>
                    <fullName>QA Project</fullName>
                </value>
                <value>
                    <fullName>Launch</fullName>
                </value>
                <value>
                    <fullName>MFS Phase 2 Launch (4&amp;5)</fullName>
                </value>
                <value>
                    <fullName>MFS Phase 1 Completion Date</fullName>
                </value>
                <value>
                    <fullName>Rater Completion Date</fullName>
                </value>
                <value>
                    <fullName>Progress Report - Update &amp; Send</fullName>
                </value>
                <value>
                    <fullName>MFS Phase 1 Reminder</fullName>
                </value>
                <value>
                    <fullName>MFS Phase 2 Reminder</fullName>
                </value>
                <value>
                    <fullName>Standard Reminder</fullName>
                </value>
                <value>
                    <fullName>Reports Download and Send</fullName>
                </value>
                <value>
                    <fullName>Project Closed</fullName>
                </value>
                <value>
                    <fullName>Project Reopened</fullName>
                </value>
                <value>
                    <fullName>Invoice Query</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Job</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Job Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/objects/MS_Queues__mdt.object
<CustomObject>
    <fields>
        <fullName>Id__c</fullName>
        <label>Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MS_Team__c</fullName>
        <label>MS Team</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>TA - Vocational</fullName>
                    <default>true</default>
                    <label>TA - Vocational</label>
                </value>
                <value>
                    <fullName>TA - Corporate</fullName>
                </value>
                <value>
                    <fullName>Talent Management</fullName>
                </value>
                <value>
                    <fullName>Analytics and Dashboards</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>MS Queues</label>
    <pluralLabel>MS Queues</pluralLabel>
</CustomObject>

objects/MS_Task__c.object
<CustomObject>
    <description>Object to accommodate Task information related to Managed Services</description>
    <fields>
        <fullName>Actual_Time_Taken__c</fullName>
        <description>This field holds the overridden value of time entered by superuser or project manager</description>
        <label>Overridden Time</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Job__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Job</label>
        <referenceTo>Job__c</referenceTo>
        <relationshipLabel>MS Tasks</relationshipLabel>
        <relationshipName>MS_Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Original_Time_Taken__c</fullName>
        <formula>IF(
				OR(ISBLANK(Task_Start_Time__c), ISBLANK(Task_End_Time__c)),
				&apos;0 minute&apos;,
    TEXT( FLOOR( ( (  (UNIXTIMESTAMP(Task_End_Time__c)*1000 - UNIXTIMESTAMP(Task_Start_Time__c)*1000 - Timer_Offset__c)/1000 ))/3600) ) &amp; &apos; hour &apos; &amp;
				TEXT(	FLOOR(MOD((( (UNIXTIMESTAMP(Task_End_Time__c)*1000 - UNIXTIMESTAMP(Task_Start_Time__c)*1000 - Timer_Offset__c)/1000 )), 3600)/60 ) + IF(FLOOR( MOD(MOD( (( (UNIXTIMESTAMP(Task_End_Time__c)*1000 - UNIXTIMESTAMP(Task_Start_Time__c)*1000 - Timer_Offset__c)/1000 )), 3600), 60) )&lt; 30, 0, 1) ) &amp; &apos; minutes &apos;
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>System Calculated Time</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Scheduled_Time__c</fullName>
        <description>This field holds the value of Time of the day at which particular task is scheduled to be picked up.</description>
        <label>Scheduled Time</label>
        <type>Time</type>
    </fields>
    <fields>
        <fullName>Task_Date__c</fullName>
        <description>This field holds the value of Date on which particular task is scheduled.</description>
        <label>Task Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Task_End_Time__c</fullName>
        <label>Task End Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Task_Start_Time__c</fullName>
        <label>Task Start Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Task_Status__c</fullName>
        <label>Task Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Completed – Appointment booked</fullName>
                    <isActive>false</isActive>
                    <label>Completed – Appointment booked</label>
                </value>
                <value>
                    <fullName>Completed – No further action</fullName>
                    <isActive>false</isActive>
                    <label>Completed – No further action</label>
                </value>
                <value>
                    <fullName>Completed – Sale made</fullName>
                    <isActive>false</isActive>
                    <label>Completed – Sale made</label>
                </value>
                <value>
                    <fullName>Deferred</fullName>
                    <isActive>false</isActive>
                    <label>Deferred</label>
                </value>
                <value>
                    <fullName>Waiting on someone else</fullName>
                    <isActive>false</isActive>
                    <label>Waiting on someone else</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Task_Type__c</fullName>
        <label>Task Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Task_Category__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Additional Candidates QA</fullName>
                </value>
                <value>
                    <fullName>Additional Candidates Setup</fullName>
                </value>
                <value>
                    <fullName>Assessment Creation</fullName>
                </value>
                <value>
                    <fullName>Assessment Tracking - BOD/EOD Tracking and Reporting</fullName>
                </value>
                <value>
                    <fullName>Assessor Alignment</fullName>
                </value>
                <value>
                    <fullName>Bandwidth Deployment (Internal)</fullName>
                </value>
                <value>
                    <fullName>Batch Acceptance and TP intimation - Batch acceptance on Central portal</fullName>
                </value>
                <value>
                    <fullName>Batch Acceptance and TP intimation - Batch details entered in the tracker</fullName>
                </value>
                <value>
                    <fullName>Batch Acceptance and TP intimation - Other stakeholder intimation</fullName>
                </value>
                <value>
                    <fullName>Batch Acceptance and TP intimation - TP intimation</fullName>
                </value>
                <value>
                    <fullName>Billing Tracker</fullName>
                </value>
                <value>
                    <fullName>Build - Demo</fullName>
                </value>
                <value>
                    <fullName>Build - Iteration</fullName>
                </value>
                <value>
                    <fullName>Build - Update</fullName>
                </value>
                <value>
                    <fullName>Cab Delay</fullName>
                </value>
                <value>
                    <fullName>Candidate Changes</fullName>
                </value>
                <value>
                    <fullName>Candidate Completion check</fullName>
                </value>
                <value>
                    <fullName>Candidate Completion Check (extension)</fullName>
                </value>
                <value>
                    <fullName>Candidate Recall</fullName>
                </value>
                <value>
                    <fullName>Candidate Reminder</fullName>
                </value>
                <value>
                    <fullName>Candidate Reminder QA</fullName>
                </value>
                <value>
                    <fullName>Candidate Resend Invitation</fullName>
                </value>
                <value>
                    <fullName>Candidate Reset Assessment</fullName>
                </value>
                <value>
                    <fullName>Categorising Mailbox</fullName>
                </value>
                <value>
                    <fullName>Check Request for all details</fullName>
                </value>
                <value>
                    <fullName>Clean Data</fullName>
                </value>
                <value>
                    <fullName>Client Portal Acceptance</fullName>
                </value>
                <value>
                    <fullName>Client Portal Upload</fullName>
                </value>
                <value>
                    <fullName>Client Result Approval</fullName>
                </value>
                <value>
                    <fullName>Contact Coaching</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>MS Task</label>
    <nameField>
        <displayFormat>TSK-{00000}</displayFormat>
        <label>MS Task Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MS Tasks</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/TaskSearchController.cls
public with sharing class TaskSearchController {
       @AuraEnabled(cacheable=true)
       public static List<Group> returnManagedServiceGroups(){
        try {
            Group maingroup = [SELECT Id,DeveloperName FROM Group where DeveloperName = 'Managed_and_Bureau_Services'];
            List<GroupMember> members = [SELECT Id,UserOrGroupId FROM GroupMember where GroupId =:maingroup.Id];
            List<Id> groupIDs = new List<Id>();
            FOr(GroupMember member:members){
                groupIDs.add(member.UserOrGroupId);
            }
            return [SELECT Id,name FROM Group where Id In :groupIDs];
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled(cacheable=true)
    public static Map<String,String> getQueueList(){
        try {
           Map<String,String> QueueMap = new Map<String,String>();
            List<MS_Queues__mdt> queues = MS_Queues__mdt.getall().values();
            for(MS_Queues__mdt queue:queues){
                System.debug('LOB Value from setting '+queue.MS_Team__c);
                {
                    QueueMap.put(queue.MasterLabel,queue.Id__c);
                }
            }
            System.debug('Map value '+QueueMap);
            if(QueueMap.isEmpty()){
                return null;
            }
            else{
                return QueueMap;
            }
        } 
        catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static List<MS_Task__c> returnTasks(List<Id> AssignedToGroups,List<String> TaskStatusList, String StartDate, String EndDate,String SelectedOwner, List<String> JobNumbers){
        List<Job__c> jobsList = new List<Job__c>();
        System.debug('Jobnumbers '+JobNumbers);
        System.debug('Jobnumbers size '+JobNumbers.size());
        System.debug('Jobnumbers is empty '+JobNumbers.isEmpty());
        if(!JobNumbers.isEmpty()){
            jobsList = [select id from Job__c where name IN : JobNumbers order by name];
            if(jobsList.isEmpty()){
                throw new AuraHandledException('Invalid Job Number(s)');
            }
        }
        List<GroupMember> memberslist = [SELECT GroupId,Id,UserOrGroupId FROM GroupMember where GroupId in:AssignedToGroups];
        List<Id> membersId = new List<Id>();
        List<Id> JobIdList = new List<Id>();
        List<String> statusList = new List<String>();
        //String query = 'Select id,Scheduled_Time__c,OwnerId,ActivityDate,What.Name,Description,EstimatedDurationInMinutes__c,Actual_Time_Taken__c,Status,Task_Type__c,Owner.Name,Task_End_Time__c,Task_Start_Time__c from Task where Related_To_Prefix__c = \'a00\' and (NOT Subject Like \'Email:%\')';
        String query = 'Select id,Scheduled_Time__c,OwnerId,Task_Date__c,Job__r.Name,Job__r.Project_Name__c,Job__r.Account__r.Name,Actual_Time_Taken__c,Task_Status__c,Task_Type__c,Owner.Name,Task_End_Time__c,Task_Start_Time__c,Original_Time_Taken__c from MS_Task__c where Job__c!=null';
        if(AssignedToGroups.size()>0){
            query +=' and OwnerId IN :AssignedToGroups';
        }
        for(GroupMember member:memberslist){
            membersId.add(member.UserOrGroupId);
        }
        if(SelectedOwner!=''){
            membersId.add(SelectedOwner);
        }
        if(membersId.size()>0){
            query +=' and OwnerId IN :membersId';
        }
        if(TaskStatusList.size()>0)
        {
            if(!TaskStatusList.contains('All Tasks'))
            {
                for(String status : TaskStatusList)
                {
                    if(status == 'Not Completed')
                    {
                        statusList.add('Not Started');
                        statusList.add('In Progress');
                    }
                    else
                        statusList.add(status);
                }
                query += ' and Task_Status__c in :statusList';
            }
        }
        if(StartDate!='' && StartDate!=null)
            Date convertedStartDate = Date.valueOf(StartDate);
            query += ' and Task_Date__c >= :convertedStartDate';
        if(EndDate!='' && EndDate!=null)
            Date convertedEndDate = Date.valueOf(EndDate);
            query += ' and Task_Date__c <= :convertedEndDate';
        if(JobNumbers.size()>0){
            for(Job__c j : jobsList){
                JobIdList.add(j.id);
            }
            if(jobsList.size()>0){
            query +=' and Job__c IN : JobIdList';
            }
        }
        System.debug('Query '+query);
        query +=' order by Task_Date__c limit 10000';
        System.debug('Query '+query);
        return Database.query(query);
    }

}