objects/Milestone__c.object
<CustomObject>
    <description>An object to record Milestones that can be signed by the PM Agent for revenue recognition</description>
    <label>Milestone</label>
    <nameField>
        <displayFormat>MS{00000}</displayFormat>
        <label>Milestone Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Milestones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ProjectObject__c.object
<CustomObject>
    <description>Used for PSA work</description>
    <fields>
        <fullName>Project_Status__c</fullName>
        <label>Project Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Initiation</fullName>
                </value>
                <value>
                    <fullName>Planning</fullName>
                </value>
                <value>
                    <fullName>Executing</fullName>
                </value>
                <value>
                    <fullName>Closing</fullName>
                </value>
                <value>
                    <fullName>Closed/Delivered</fullName>
                </value>
                <value>
                    <fullName>Closed/Cancelled</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Live</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Total_Orderline_Value_RollUp__c</fullName>
        <label>Total Order Product Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Project</label>
    <nameField>
        <displayFormat>P{000000}</displayFormat>
        <label>Project Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <recordTypes>
        <fullName>Project</fullName>
        <active>true</active>
        <label>Project</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/MilestoneBulkControllerTester.cls
@isTest(seeAllData = true)
public class MilestoneBulkControllerTester {
    static testMethod void CoverMethods(){
        ProjectObject__c project = [select id from ProjectObject__c where Project_Status__c='In Progress' and Total_Orderline_Value_RollUp__c!=null limit 1];
        MilestoneBulkController.getProjectData(project.Id);
        MilestoneBulkController.getMilestonesData(project.Id);
        MilestoneBulkController.saveMilestones(CreateMilestoneTestRecords());
        MilestoneBulkController.checkAccess();
    }
    static testMethod List<Milestone__c> CreateMilestoneTestRecords(){
        List<Milestone__c> TempMilestone = new List<Milestone__c>();
        ProjectObject__c project = [select id from ProjectObject__c where Project_Status__c='In Progress' and Total_Orderline_Value_RollUp__c!=null limit 1];
        for(integer i=0;i<5;i++){
            Milestone__c milestone = new Milestone__c();
            TempMilestone.add(milestone);
        }
        return TempMilestone;
    }

}