objects/ProjectObject__c.object
<CustomObject>
    <description>Used for PSA work</description>
    <fields>
        <fullName>Function_Timesheet__c</fullName>
        <formula>IF(INCLUDES(Functional_Area__c, &apos;Internal&apos;), &apos;IN&apos;, 
IF(INCLUDES(Functional_Area__c, &apos;Generic PreSales/Sales&apos;),&apos;AM&apos;, 
IF(INCLUDES(Functional_Area__c, &apos;PST – Generic&apos;), &apos;PSTG&apos;, 
IF(INCLUDES(Functional_Area__c, &apos;Account PreSales/Sales&apos;), &apos;AP&apos;, 
IF(INCLUDES(Functional_Area__c, &apos;Sales&apos;), &apos;SAL&apos;, 
IF(INCLUDES(Functional_Area__c,&apos;Commercial Operations&apos;),&apos;CO&apos;,
IF(INCLUDES(Functional_Area__c, &apos;Internal Organisation&apos;), &apos;INT&apos;, 
LEFT 
( 
IF(INCLUDES(Functional_Area__c, &apos;PS Consulting&apos;), &apos;PSC;&apos;, &apos;&apos;) + 
IF(INCLUDES(Functional_Area__c, &apos;PS Training&apos;), &apos;PST;&apos;, &apos;&apos;) + 
IF(INCLUDES(Functional_Area__c, &apos;PST – Client&apos;), &apos;PSTC;&apos;, &apos;&apos;) + 
IF(INCLUDES(Functional_Area__c, &apos;Custom Solutions&apos;), &apos;CS;&apos;, &apos;&apos;)+ 
IF(INCLUDES(Functional_Area__c, &apos;Consulting &amp; Training&apos;), &apos;CT;&apos;, &apos;&apos;) + 
IF(INCLUDES(Functional_Area__c, &apos;Pre-sales&apos;), &apos;PSAL;&apos;, &apos;&apos;), 
LEN 
( 
IF(INCLUDES(Functional_Area__c, &apos;PS Consulting&apos;), &apos;PSC;&apos;, &apos;&apos;) + 
IF(INCLUDES(Functional_Area__c, &apos;PS Training&apos;), &apos;PST;&apos;, &apos;&apos;) + 
IF(INCLUDES(Functional_Area__c, &apos;PST – Client&apos;), &apos;PSTC;&apos;, &apos;&apos;) + 
IF(INCLUDES(Functional_Area__c, &apos;Custom Solutions&apos;), &apos;CS;&apos;, &apos;&apos;)+ 
IF(INCLUDES(Functional_Area__c, &apos;Consulting &amp; Training&apos;), &apos;CT;&apos;, &apos;&apos;) + 
IF(INCLUDES(Functional_Area__c, &apos;Pre-sales&apos;), &apos;PSAL;&apos;, &apos;&apos;) 
)-1 
) 
) 
) 
) 
)
) 
) 
)</formula>
        <label>Function (Timesheet)</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Functional_Area__c</fullName>
        <description>specifies the functional area of the Project</description>
        <label>Functional Area</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Consulting &amp; Training</fullName>
                </value>
                <value>
                    <fullName>Sales</fullName>
                </value>
                <value>
                    <fullName>Pre-sales</fullName>
                </value>
                <value>
                    <fullName>Commercial Operations</fullName>
                </value>
                <value>
                    <fullName>Internal Organisation</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project</label>
    <nameField>
        <displayFormat>P{000000}</displayFormat>
        <label>Project Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/objects/Timesheet_Line__c.object
<CustomObject>
    <description>Time recording in T&amp;E module</description>
    <fields>
        <fullName>Billable__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Billable</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Billing_Rate__c</fullName>
        <label>Billing Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Date_Invoiced__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Function__c</fullName>
        <label>Function</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>CT</fullName>
                </value>
                <value>
                    <fullName>SAL</fullName>
                </value>
                <value>
                    <fullName>PSAL</fullName>
                </value>
                <value>
                    <fullName>INT</fullName>
                </value>
                <value>
                    <fullName>CT;PSAL</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Hours__c</fullName>
        <label>Hours</label>
        <precision>4</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>ProjectObject__c</referenceTo>
        <relationshipLabel>Timesheets</relationshipLabel>
        <relationshipName>Timesheets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Resource__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Resource</label>
        <referenceTo>User</referenceTo>
        <relationshipName>R00N20000001Jpa3EAC</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Task_Category__c</fullName>
        <label>Task Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1:1 Assessment</fullName>
                </value>
                <value>
                    <fullName>1:1 Assessment Feedback Session</fullName>
                </value>
                <value>
                    <fullName>1:1 Developmental Feedback Session</fullName>
                </value>
                <value>
                    <fullName>1:1 Development Assessment</fullName>
                </value>
                <value>
                    <fullName>360 System</fullName>
                </value>
                <value>
                    <fullName>Account Specific</fullName>
                </value>
                <value>
                    <fullName>Admin</fullName>
                </value>
                <value>
                    <fullName>Advisory Services</fullName>
                </value>
                <value>
                    <fullName>Aspiring Minds</fullName>
                </value>
                <value>
                    <fullName>Assessment Centre</fullName>
                </value>
                <value>
                    <fullName>Business Outcome Study / Validation Study</fullName>
                </value>
                <value>
                    <fullName>Client and End-User Support and Consulting</fullName>
                </value>
                <value>
                    <fullName>Client Custom Assessment</fullName>
                </value>
                <value>
                    <fullName>Client Support</fullName>
                </value>
                <value>
                    <fullName>Coaching</fullName>
                </value>
                <value>
                    <fullName>Competency Design</fullName>
                </value>
                <value>
                    <fullName>Competency Mapping</fullName>
                </value>
                <value>
                    <fullName>Coordination of Intra SHL Purchase of Services</fullName>
                </value>
                <value>
                    <fullName>Custom Norm</fullName>
                </value>
                <value>
                    <fullName>Custom Report</fullName>
                </value>
                <value>
                    <fullName>Custom Report - Configured</fullName>
                </value>
                <value>
                    <fullName>Dashboards</fullName>
                </value>
                <value>
                    <fullName>Development Centre</fullName>
                </value>
                <value>
                    <fullName>Development Coach</fullName>
                </value>
                <value>
                    <fullName>Digital Readiness</fullName>
                </value>
                <value>
                    <fullName>Enablement</fullName>
                </value>
                <value>
                    <fullName>Engagement</fullName>
                </value>
                <value>
                    <fullName>Enterprise Leadership</fullName>
                </value>
                <value>
                    <fullName>Generic</fullName>
                </value>
                <value>
                    <fullName>Graduate Solution</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Task__c</fullName>
        <label>Task</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Time_Category__c</controllingField>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>1:1</fullName>
                </value>
                <value>
                    <fullName>Account / Opportunity Specific</fullName>
                </value>
                <value>
                    <fullName>Account Review and Preparation &amp; Facilitation</fullName>
                </value>
                <value>
                    <fullName>Additional Consultancy Coordination</fullName>
                </value>
                <value>
                    <fullName>Ad-hoc Advisory Support</fullName>
                </value>
                <value>
                    <fullName>Admin, Management and Meetings</fullName>
                </value>
                <value>
                    <fullName>Admin for projects – e.g. spec doc creation, JIRA ticket creation, issue management</fullName>
                    <label>Admin for projects - e.g. spec doc creation, JIRA ticket creation, issue management</label>
                </value>
                <value>
                    <fullName>Advisory</fullName>
                </value>
                <value>
                    <fullName>Advisory Program Initiation</fullName>
                </value>
                <value>
                    <fullName>Analysis</fullName>
                </value>
                <value>
                    <fullName>Analytics</fullName>
                </value>
                <value>
                    <fullName>Application Analytics Consulting</fullName>
                </value>
                <value>
                    <fullName>Assessment / Development Centre</fullName>
                </value>
                <value>
                    <fullName>Assessment and Development Delivery</fullName>
                </value>
                <value>
                    <fullName>Assessment Solution Updates</fullName>
                </value>
                <value>
                    <fullName>Associate Contracting</fullName>
                </value>
                <value>
                    <fullName>Associate Payment</fullName>
                </value>
                <value>
                    <fullName>Attending Company Training</fullName>
                </value>
                <value>
                    <fullName>Automation</fullName>
                </value>
                <value>
                    <fullName>BOS/Validation</fullName>
                </value>
                <value>
                    <fullName>Build</fullName>
                </value>
                <value>
                    <fullName>Client Changes</fullName>
                </value>
                <value>
                    <fullName>Client Support</fullName>
                </value>
                <value>
                    <fullName>Coaching</fullName>
                </value>
                <value>
                    <fullName>Company Holiday</fullName>
                </value>
                <value>
                    <fullName>Compassionate Leave</fullName>
                </value>
                <value>
                    <fullName>Competency Framework</fullName>
                </value>
                <value>
                    <fullName>Configuration and Implementation</fullName>
                </value>
                <value>
                    <fullName>Configuration Forms</fullName>
                </value>
                <value>
                    <fullName>Consulting Travel</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Timesheet</label>
    <nameField>
        <displayFormat>TSL{000000}</displayFormat>
        <label>Timesheet Line Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Timesheets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/Timesheet_TriggerTester.cls
public class Timesheet_TriggerTester
{
    public static void testTimesheetTriggers()
    {
        testBasicMethods(null);
    }
    
    public static void testBasicMethods(String projectId)
    {
        List<Timesheet_Line__c> timesheets;
        
        timesheets = insertTimesheets(projectId);
            
        updateTimesheets(timesheets);
        
        deleteTimesheets(timesheets);
    }
    
    public static void testSpecialMethods(List<Timesheet_Line__c> timesheets)
    {
        
    }
    
    public static List<Timesheet_Line__c> insertTimesheets(String projectId)
     {
        system.debug('Timesheet: Insert Started');
        List<ProjectObject__c> projectList = new List<ProjectObject__c>();
        if(projectId==null)
        {
            projectList = [SELECT Id,Function_Timesheet__c from ProjectObject__c WHERE Functional_Area__c INCLUDES ('Consulting & Training') LIMIT 1];
            projectId = projectList[0].id;
        }
        else
            projectList = [SELECT Id,Function_Timesheet__c from ProjectObject__c WHERE id = :projectId];
        String userId = Userinfo.getUserId(); 
         
        List<Timesheet_Line__c> timesheets = new List<Timesheet_Line__c>();
        
        for(Integer i=0;i<2;i++)
        {
            Timesheet_Line__c timesheet = new Timesheet_Line__c();
            timesheet.Project__c =projectId;
            timesheet.Resource__c =  userId;
            timesheet.Billable__c = true;
            timesheet.Task_Category__c = 'Consulting';
            timesheet.Task__c = 'Assessment';
            timesheet.Date_Invoiced__c = Date.newInstance(2008,4+i,21);
            timesheet.Billing_Rate__c = 50 + i*10;
            timesheet.Hours__c = 4;
            timesheet.Function__c = projectList[0].Function_Timesheet__c;
            timesheet.Time_Category__c = 'Internal Organisation';
            timesheet.Task__c = 'Admin, Management And Meetings';
            timesheets.add(timesheet);
        }
    
        insert timesheets;
        
        return timesheets;
     }
     
     public static void updateTimesheets(List<Timesheet_Line__c> insertedTimesheets)
     {
        List<Timesheet_Line__c> timesheets = new List<Timesheet_Line__c>();
        
        for(Timesheet_Line__c timesheet: insertedTimesheets)
        {
            timesheet.Billing_Rate__c += 10;
            timesheets.add(timesheet);
        }
    
        update timesheets ;
        
     }
     
     public static void deleteTimesheets(List<Timesheet_Line__c> insertedTimesheets)
     {
        delete insertedTimesheets;
        
     }
}