objects/Project_Invoice__c.object
<CustomObject>
    <description>Represents the invoice generated for the Time &amp; Expenses of a Project.</description>
    <fields>
        <fullName>LBU__c</fullName>
        <label>LBU</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>AD1</fullName>
                </value>
                <value>
                    <fullName>AU1</fullName>
                </value>
                <value>
                    <fullName>BE5</fullName>
                </value>
                <value>
                    <fullName>CA1</fullName>
                </value>
                <value>
                    <fullName>CH1</fullName>
                </value>
                <value>
                    <fullName>CN1</fullName>
                </value>
                <value>
                    <fullName>DE5</fullName>
                </value>
                <value>
                    <fullName>DK1</fullName>
                </value>
                <value>
                    <fullName>FI1</fullName>
                </value>
                <value>
                    <fullName>FR5</fullName>
                </value>
                <value>
                    <fullName>HK1</fullName>
                </value>
                <value>
                    <fullName>IN1</fullName>
                </value>
                <value>
                    <fullName>IT1</fullName>
                </value>
                <value>
                    <fullName>ME1</fullName>
                </value>
                <value>
                    <fullName>NL5</fullName>
                </value>
                <value>
                    <fullName>NO1</fullName>
                </value>
                <value>
                    <fullName>NZ1</fullName>
                </value>
                <value>
                    <fullName>PH1</fullName>
                </value>
                <value>
                    <fullName>SA5</fullName>
                </value>
                <value>
                    <fullName>SE1</fullName>
                </value>
                <value>
                    <fullName>SG1</fullName>
                </value>
                <value>
                    <fullName>UK1</fullName>
                </value>
                <value>
                    <fullName>US5</fullName>
                </value>
                <value>
                    <fullName>ZA1</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <description>Project to which this invoice belongs</description>
        <label>Project</label>
        <referenceTo>ProjectObject__c</referenceTo>
        <relationshipLabel>Invoice Requests</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Invoice Request</label>
    <nameField>
        <displayFormat>Inv{000000}</displayFormat>
        <label>Invoice Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ProjectObject__c.object
<CustomObject>
    <description>Used for PSA work</description>
    <fields>
        <fullName>LBU__c</fullName>
        <label>LBU</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AD1</fullName>
                </value>
                <value>
                    <fullName>AU1</fullName>
                </value>
                <value>
                    <fullName>BE5</fullName>
                </value>
                <value>
                    <fullName>CA1</fullName>
                </value>
                <value>
                    <fullName>CH1</fullName>
                </value>
                <value>
                    <fullName>CN1</fullName>
                </value>
                <value>
                    <fullName>CPS</fullName>
                </value>
                <value>
                    <fullName>DE5</fullName>
                </value>
                <value>
                    <fullName>DK1</fullName>
                </value>
                <value>
                    <fullName>FI1</fullName>
                </value>
                <value>
                    <fullName>FR5</fullName>
                </value>
                <value>
                    <fullName>HK1</fullName>
                </value>
                <value>
                    <fullName>IN1</fullName>
                </value>
                <value>
                    <fullName>IT1</fullName>
                </value>
                <value>
                    <fullName>ME1</fullName>
                </value>
                <value>
                    <fullName>NL5</fullName>
                </value>
                <value>
                    <fullName>NO1</fullName>
                </value>
                <value>
                    <fullName>NZ1</fullName>
                </value>
                <value>
                    <fullName>PH1</fullName>
                </value>
                <value>
                    <fullName>SA5</fullName>
                </value>
                <value>
                    <fullName>SE1</fullName>
                </value>
                <value>
                    <fullName>SG1</fullName>
                </value>
                <value>
                    <fullName>UK1</fullName>
                </value>
                <value>
                    <fullName>US5</fullName>
                </value>
                <value>
                    <fullName>ZA1</fullName>
                </value>
                <value>
                    <fullName>ID1</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PNO__c</fullName>
        <label>PNO</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Manager</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>User.Is_Project_Manager__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>$User.Id</field>
                <operation>equals</operation>
                <value>0054G00000CSIBq</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SequenceNo__c</fullName>
        <displayFormat>P-{00000}</displayFormat>
        <label>SequenceNo</label>
        <type>AutoNumber</type>
    </fields>
    <label>Project</label>
    <nameField>
        <displayFormat>P{000000}</displayFormat>
        <label>Project Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <recordTypes>
        <fullName>Project</fullName>
        <active>true</active>
        <label>Project</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/objects/User.object
<CustomObject>
    <fields>
        <fullName>PSA_Role__c</fullName>
        <description>This specifies the role that the user should be assigned as per the PSA Securit y Model.</description>
        <inlineHelpText>Specify the role that the user should be assigned as per the PSA Securit y Model.</inlineHelpText>
        <label>PSA Role</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>User</fullName>
                </value>
                <value>
                    <fullName>Project Manager</fullName>
                </value>
                <value>
                    <fullName>PSA Lead</fullName>
                    <default>true</default>
                    <label>PSA Lead</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

classes/Project_Manager.cls
global class Project_Manager 
{
    public static List<ProjectObject__c> getProjectsForInvoices(List<Project_Invoice__c> invoices)
    {
        Set<Id> projectIds = new Set<Id>();
        List<ProjectObject__c> projects = new List<ProjectObject__c>();
        
        for(Integer i=0;i<invoices.size();i++)
        {
            if(!projectIds.contains(invoices[i].Project__c))
            {
                projects.add(new ProjectObject__c(id = invoices[i].Project__c));    
                projectIds.add(invoices[i].Project__c); 
            }   
        } 
        
        return projects;
    }
    
    public static boolean userCanCreateProjects()
    {
        User user = getUserDetails();
        
        //If the user is a PSA Lead
        if(user.PSA_Role__c == 'PSA Lead')
            return true;
        //If the user is a Project Manager
        else if(user.PSA_Role__c == 'Project Manager')
            return true;
        //if it is any other user
        else
            return false;
    }

    public static boolean userCanManageAllProjects()
    {
        User user = getUserDetails();
        
        //If the user is a PSA Lead
        if(user.PSA_Role__c == 'PSA Lead')
            return true;
        //if it is any other user
        else
            return false;
    }
    
    public static Map<Id, Boolean> userCanManageProjects(List<ProjectObject__c> projects)
    {
        projects = getProjectDetails(projects);
        
        User user = getUserDetails();
        
        Map<Id, Boolean> projectAccessMap = new Map<Id, Boolean>();
        //If the user is a PSA Lead
        if(user.PSA_Role__c == 'PSA Lead')
        {
            for(ProjectObject__c project: projects)
                  projectAccessMap.put(project.Id, true);
        }
        else if(user.PSA_Role__c == 'Project Manager')
        {
            for(ProjectObject__c project: projects)
            {
                if(user.Id == project.Project_Manager__c)
                    projectAccessMap.put(project.Id, true);
                else
                    projectAccessMap.put(project.Id, false);
            }
        }
        else
        {
            for(ProjectObject__c project: projects)
                  projectAccessMap.put(project.Id, false);
        }
        return projectAccessMap;
    }
    
    private static User getUserDetails()
    {
        User user = [SELECT id, Profile.PermissionsModifyAllData, PSA_Role__c FROM USER WHERE id = :Userinfo.getUserId()];
        return user;
    }
    
    private static List<ProjectObject__c> getProjectDetails(List<ProjectObject__c> projects)
    {
        Map<Id, ProjectObject__c> projectMap = new Map<Id, ProjectObject__c>(projects);
        for(ProjectObject__c project: projects)
        {
            if(project.Project_Manager__c==null)
            {
                projects = [SELECT Id, Project_Manager__c FROM ProjectObject__c WHERE Id IN :projectMap.keySet()];
            }
        }
        return projects;
    } 
    
    WebService static void populateProjectWithUpdatedAmounts(ProjectObject__c selectedProject,Boolean includeAssociates)
    {
        ProjectObject__c project = getProjectWithUpdatedAmounts(selectedProject,includeAssociates);
        
    }
    
    WebService static ProjectObject__c getProjectWithUpdatedAmounts(ProjectObject__c selectedProject,Boolean includeAssociates)
    {
        ///Intialize the instance of the project that is to be returned by the function
        ProjectObject__c project = new ProjectObject__c(id=selectedProject.id);
        
        Map<String, Double> currencyMap = new Map<String, Double>();
        for(CurrencyType currencyType: [SELECT IsoCode, ConversionRate FROM CurrencyType])
            currencyMap.put(currencyType.IsoCode, currencyType.ConversionRate);
               
        //Find the Invoice CurrencyType
        Double projectCurrencyConversionRate = currencyMap.get(selectedProject.CurrencyIsoCode);
        return project;
    }
    
    
    /*WebService static void changeProjectNumberFormat(ProjectObject__c selectedProject)
    {
        string Serial;
        Integer Sequence;
        ProjectObject__c project = new ProjectObject__c(id=selectedProject.Id);
        
        Serial = [Select SequenceNo__c from ProjectObject__c Order By SequenceNo__c Desc LIMIT 1].SequenceNo__c;
        Sequence=serial!=null?Integer.valueOf(Serial):1;
        
        string[] monthName = new string[]{'JAN','FEB','MAR','APR','MAY','JUN','JUL','AUG','SEP','OCT','NOV','DEC'};
        
        project.PNO__c = 'P'+ selectedProject.LBU__c+ selectedProject.createdDate.year()+ monthName[(selectedProject.createdDate.month())-1]+ selectedProject.createdDate.day()+'-'+Sequence;
        update project;
    }
    
    public static testMethod void testChangePNo()
    {
        ProjectObject__c project = [SELECT  Id,LBU__c, CreatedDate from ProjectObject__c Where Id ='a09R0000000Ajxp'LIMIT 1];
        changeProjectNumberFormat(project);
    }*/
}