objects/ProjectObject__c.object
<CustomObject>
    <description>Used for PSA work</description>
    <fields>
        <fullName>Functional_Area__c</fullName>
        <description>specifies the functional area of the Project</description>
        <label>Functional Area</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Consulting &amp; Training</fullName>
                </value>
                <value>
                    <fullName>Sales</fullName>
                </value>
                <value>
                    <fullName>Pre-sales</fullName>
                </value>
                <value>
                    <fullName>Commercial Operations</fullName>
                </value>
                <value>
                    <fullName>Internal Organisation</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PS_Project_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>PS Project Number</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <errorMessage>Only PS project can be linked with CPS Project.</errorMessage>
            <filterItems>
                <field>ProjectObject__c.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Project</value>
            </filterItems>
            <filterItems>
                <field>$User.Id</field>
                <operation>equals</operation>
                <value>0054G00000CSIBq</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>ProjectObject__c</referenceTo>
        <relationshipLabel>Central PS Projects</relationshipLabel>
        <relationshipName>Projects1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project</label>
    <nameField>
        <displayFormat>P{000000}</displayFormat>
        <label>Project Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/objects/Timesheet_Line__c.object
<CustomObject>
    <description>Time recording in T&amp;E module</description>
    <fields>
        <fullName>Billable1__c</fullName>
        <label>Billable</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Task__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Billable__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Billable</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Billing_Rate__c</fullName>
        <label>Billing Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Date_Invoiced__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Hours__c</fullName>
        <label>Hours</label>
        <precision>4</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>ProjectObject__c</referenceTo>
        <relationshipLabel>Timesheets</relationshipLabel>
        <relationshipName>Timesheets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Resource__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Resource</label>
        <referenceTo>User</referenceTo>
        <relationshipName>R00N20000001Jpa3EAC</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Task_Category__c</fullName>
        <label>Task Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1:1 Assessment</fullName>
                </value>
                <value>
                    <fullName>1:1 Assessment Feedback Session</fullName>
                </value>
                <value>
                    <fullName>1:1 Developmental Feedback Session</fullName>
                </value>
                <value>
                    <fullName>1:1 Development Assessment</fullName>
                </value>
                <value>
                    <fullName>360 System</fullName>
                </value>
                <value>
                    <fullName>Account Specific</fullName>
                </value>
                <value>
                    <fullName>Admin</fullName>
                </value>
                <value>
                    <fullName>Advisory Services</fullName>
                </value>
                <value>
                    <fullName>Aspiring Minds</fullName>
                </value>
                <value>
                    <fullName>Assessment Centre</fullName>
                </value>
                <value>
                    <fullName>Business Outcome Study / Validation Study</fullName>
                </value>
                <value>
                    <fullName>Client and End-User Support and Consulting</fullName>
                </value>
                <value>
                    <fullName>Client Custom Assessment</fullName>
                </value>
                <value>
                    <fullName>Client Support</fullName>
                </value>
                <value>
                    <fullName>Coaching</fullName>
                </value>
                <value>
                    <fullName>Competency Design</fullName>
                </value>
                <value>
                    <fullName>Competency Mapping</fullName>
                </value>
                <value>
                    <fullName>Coordination of Intra SHL Purchase of Services</fullName>
                </value>
                <value>
                    <fullName>Custom Norm</fullName>
                </value>
                <value>
                    <fullName>Custom Report</fullName>
                </value>
                <value>
                    <fullName>Custom Report - Configured</fullName>
                </value>
                <value>
                    <fullName>Dashboards</fullName>
                </value>
                <value>
                    <fullName>Development Centre</fullName>
                </value>
                <value>
                    <fullName>Development Coach</fullName>
                </value>
                <value>
                    <fullName>Digital Readiness</fullName>
                </value>
                <value>
                    <fullName>Enablement</fullName>
                </value>
                <value>
                    <fullName>Engagement</fullName>
                </value>
                <value>
                    <fullName>Enterprise Leadership</fullName>
                </value>
                <value>
                    <fullName>Generic</fullName>
                </value>
                <value>
                    <fullName>Graduate Solution</fullName>
                </value>
                <value>
                    <fullName>PS Consulting</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Task__c</fullName>
        <label>Task</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Time_Category__c</controllingField>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>1:1</fullName>
                </value>
                <value>
                    <fullName>Account / Opportunity Specific</fullName>
                </value>
                <value>
                    <fullName>Account Review and Preparation &amp; Facilitation</fullName>
                </value>
                <value>
                    <fullName>Additional Consultancy Coordination</fullName>
                </value>
                <value>
                    <fullName>Ad-hoc Advisory Support</fullName>
                </value>
                <value>
                    <fullName>Admin, Management and Meetings</fullName>
                </value>
                <value>
                    <fullName>Admin for projects – e.g. spec doc creation, JIRA ticket creation, issue management</fullName>
                    <label>Admin for projects - e.g. spec doc creation, JIRA ticket creation, issue management</label>
                </value>
                <value>
                    <fullName>Advisory</fullName>
                </value>
                <value>
                    <fullName>Advisory Program Initiation</fullName>
                </value>
                <value>
                    <fullName>Analysis</fullName>
                </value>
                <value>
                    <fullName>Analytics</fullName>
                </value>
                <value>
                    <fullName>Application Analytics Consulting</fullName>
                </value>
                <value>
                    <fullName>Assessment / Development Centre</fullName>
                </value>
                <value>
                    <fullName>Assessment and Development Delivery</fullName>
                </value>
                <value>
                    <fullName>Assessment Solution Updates</fullName>
                </value>
                <value>
                    <fullName>Associate Contracting</fullName>
                </value>
                <value>
                    <fullName>Associate Payment</fullName>
                </value>
                <value>
                    <fullName>Attending Company Training</fullName>
                </value>
                <value>
                    <fullName>Automation</fullName>
                </value>
                <value>
                    <fullName>BOS/Validation</fullName>
                </value>
                <value>
                    <fullName>Build</fullName>
                </value>
                <value>
                    <fullName>Client Changes</fullName>
                </value>
                <value>
                    <fullName>Client Support</fullName>
                </value>
                <value>
                    <fullName>Coaching</fullName>
                </value>
                <value>
                    <fullName>Company Holiday</fullName>
                </value>
                <value>
                    <fullName>Compassionate Leave</fullName>
                </value>
                <value>
                    <fullName>Competency Framework</fullName>
                </value>
                <value>
                    <fullName>Configuration and Implementation</fullName>
                </value>
                <value>
                    <fullName>Configuration Forms</fullName>
                </value>
                <value>
                    <fullName>Consulting Travel</fullName>
                </value>
                <value>
                    <fullName>Delivery</fullName>
                </value>
                <value>
                    <fullName>Design</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Time_Category__c</fullName>
        <label>Time Category</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Internal Organisation</fullName>
                </value>
                <value>
                    <fullName>Investments</fullName>
                </value>
                <value>
                    <fullName>Pre-Sales</fullName>
                </value>
                <value>
                    <fullName>Delivery - Outsourced Assessments</fullName>
                </value>
                <value>
                    <fullName>Delivery – Solution, Product</fullName>
                    <label>Delivery - Solution, Product</label>
                </value>
                <value>
                    <fullName>Delivery - Other</fullName>
                </value>
                <value>
                    <fullName>Cases - CSIT</fullName>
                    <isActive>false</isActive>
                    <label>Cases - CSIT</label>
                </value>
                <value>
                    <fullName>Courses - CSIT</fullName>
                    <isActive>false</isActive>
                    <label>Courses - CSIT</label>
                </value>
                <value>
                    <fullName>Delivery</fullName>
                    <isActive>false</isActive>
                    <label>Delivery</label>
                </value>
                <value>
                    <fullName>Delivery - Product Consulting</fullName>
                    <isActive>false</isActive>
                    <label>Delivery - Product Consulting</label>
                </value>
                <value>
                    <fullName>Delivery - Solutions Consulting</fullName>
                    <isActive>false</isActive>
                    <label>Delivery - Solutions Consulting</label>
                </value>
                <value>
                    <fullName>Delivery - Training</fullName>
                    <isActive>false</isActive>
                    <label>Delivery - Training</label>
                </value>
                <value>
                    <fullName>Email - CSIT</fullName>
                    <isActive>false</isActive>
                    <label>Email - CSIT</label>
                </value>
                <value>
                    <fullName>Project Resourcing and Support</fullName>
                    <isActive>false</isActive>
                    <label>Project Resourcing and Support</label>
                </value>
                <value>
                    <fullName>Support Materials - CSIT</fullName>
                    <isActive>false</isActive>
                    <label>Support Materials - CSIT</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Timesheet</label>
    <nameField>
        <displayFormat>TSL{000000}</displayFormat>
        <label>Timesheet Line Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Timesheets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TimesheetTriggerManager_Tester2.cls
@isTest(SeeAllData=true)
private class TimesheetTriggerManager_Tester2
{
    static testMethod void TimeSheetTester2(){
        ProjectObject__c PsnoProj =[select id,PS_Project_Number__c,Functional_Area__c  from projectobject__c where PS_Project_Number__c!=null limit 1];
        User GlobsUser=[select id from user where username like'%globus.development@shlgroup.com%' limit 1];
        
        Timesheet_Line__c timesheet = new Timesheet_Line__c ();
        timesheet.Project__c =PsnoProj.Id;
        //timesheet.Project__c ='a09D000000vOLau';
        timesheet.Resource__c = GlobsUser.Id;
        //timesheet.Billable__c = true;
        timesheet.Time_Category__c='Delivery';
        timesheet.Task_Category__c = 'PS Consulting';//Modified by prabhat
        timesheet.Task__c = 'Design';
        timesheet.Billable1__c = 'YES';
        //timesheet.Date_Invoiced__c = Date.newInstance(200,4+i,21);
        //timesheet.Billing_Rate__c = 50 + i*10;
        timesheet.Hours__c = 1;
        timesheet.Function__c = 'CT';
        //timesheet.Timesheet_From_CPS_Project__c=true;
        
       
        insert timesheet;
        timesheet.Hours__c = 2;
        Test.startTest();
        update timesheet;
        Test.stopTest();
        delete timesheet;
    }

    
    
}