objects/ProjectObject__c.object
<CustomObject>
    <description>Used for PSA work</description>
    <fields>
        <fullName>CPS_Project_Number__c</fullName>
        <displayFormat>P{000000}</displayFormat>
        <label>CPS Project Number</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>CS_Lead__c</fullName>
        <label>I/O Lead</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Alison Hollamby</fullName>
                </value>
                <value>
                    <fullName>Anthony Spencer</fullName>
                </value>
                <value>
                    <fullName>Ellie Mullins</fullName>
                </value>
                <value>
                    <fullName>Harpreet Dhami</fullName>
                </value>
                <value>
                    <fullName>Krutika Peres da Silva</fullName>
                </value>
                <value>
                    <fullName>Laura Ruttle</fullName>
                </value>
                <value>
                    <fullName>Leila Zid</fullName>
                </value>
                <value>
                    <fullName>Louis Lu</fullName>
                </value>
                <value>
                    <fullName>Matthew Rogers</fullName>
                </value>
                <value>
                    <fullName>Michael Lippstreu</fullName>
                </value>
                <value>
                    <fullName>Rachelle Visser</fullName>
                </value>
                <value>
                    <fullName>Sharmistha Banerjee</fullName>
                </value>
                <value>
                    <fullName>Tunrea Khaira</fullName>
                </value>
                <value>
                    <fullName>Udita Chaudhary</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Project_Name__c</fullName>
        <label>Project Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Project</label>
    <nameField>
        <displayFormat>P{000000}</displayFormat>
        <label>Project Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <recordTypes>
        <fullName>CPS_Project</fullName>
        <active>true</active>
        <description>For use by Central PS only</description>
        <label>CPS Project</label>
    </recordTypes>
    <recordTypes>
        <fullName>Project</fullName>
        <active>true</active>
        <label>Project</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Workpacket__c.object
<CustomObject>
    <fields>
        <fullName>Actual_Delivery__c</fullName>
        <label>Actual Delivery</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Agreed_Delivery__c</fullName>
        <label>Agreed Delivery</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CPS_Project_Number__c</fullName>
        <label>CPS Project Number</label>
        <referenceTo>ProjectObject__c</referenceTo>
        <relationshipLabel>Workpackets</relationshipLabel>
        <relationshipName>Workpackets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>CS_Lead__c</fullName>
        <label>I/O Lead</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Alison Hollamby</fullName>
                </value>
                <value>
                    <fullName>Anthony Spencer</fullName>
                </value>
                <value>
                    <fullName>Chloe Gabriel</fullName>
                </value>
                <value>
                    <fullName>Daniel Adeline</fullName>
                </value>
                <value>
                    <fullName>Elizabeth Antoniou</fullName>
                </value>
                <value>
                    <fullName>Ellie Mullins</fullName>
                </value>
                <value>
                    <fullName>Harpreet Dhami</fullName>
                </value>
                <value>
                    <fullName>Krutika Peres da Silva</fullName>
                </value>
                <value>
                    <fullName>Laura Ruttle</fullName>
                </value>
                <value>
                    <fullName>Leila Zid</fullName>
                </value>
                <value>
                    <fullName>Louis Lu</fullName>
                </value>
                <value>
                    <fullName>Matthew Rogers</fullName>
                </value>
                <value>
                    <fullName>Michael Lippstreu</fullName>
                </value>
                <value>
                    <fullName>Rachelle Visser</fullName>
                </value>
                <value>
                    <fullName>Sharmistha Banerjee</fullName>
                </value>
                <value>
                    <fullName>Tunrea Khaira</fullName>
                </value>
                <value>
                    <fullName>Udita Chaudhary</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <label>Workpacket</label>
    <nameField>
        <displayFormat>WP-{00000000}</displayFormat>
        <label>Workpacket Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Workpackets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/workpacketTestclass.cls
@isTest(seeAllData=true) 
public class workpacketTestclass {

static testMethod void workpacket()
{
    Test.startTest();
        User oppsUser = [SELECT Id FROM User WHERE UserName Like 'globus.development@shlgroup.com%' limit 1];
        RecordType newRT = [select id from RecordType where developerName='CPS_Project' AND SobjectType='ProjectObject__c'];
        System.runAs(oppsUser) {
            ProjectObject__c prj = new ProjectObject__c(CS_Lead__c='Emma Lee',Project_Name__c='CPS Project',RecordTypeId=newRT.Id);
            insert prj;
            
            Workpacket__c  wc = new Workpacket__c (CS_Lead__c='Emma Lee',CPS_Project_Number__c=prj.Id,Actual_Delivery__c=Date.Today(),Agreed_Delivery__c=Date.today().addDays(5),Description__c='Test');
            insert wc;
            
            wc.Actual_Delivery__c =Date.Today().addDays(1);
            update wc;
        }
    Test.stopTest();
}



}