objects/ProjectObject__c.object
<CustomObject>
    <description>Used for PSA work</description>
    <fields>
        <fullName>Is_Auto_Created__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Auto Created</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LBU__c</fullName>
        <label>LBU</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AD1</fullName>
                </value>
                <value>
                    <fullName>AU1</fullName>
                </value>
                <value>
                    <fullName>BE5</fullName>
                </value>
                <value>
                    <fullName>CA1</fullName>
                </value>
                <value>
                    <fullName>CH1</fullName>
                </value>
                <value>
                    <fullName>CN1</fullName>
                </value>
                <value>
                    <fullName>CPS</fullName>
                </value>
                <value>
                    <fullName>DE5</fullName>
                </value>
                <value>
                    <fullName>DK1</fullName>
                </value>
                <value>
                    <fullName>FI1</fullName>
                </value>
                <value>
                    <fullName>FR5</fullName>
                </value>
                <value>
                    <fullName>HK1</fullName>
                </value>
                <value>
                    <fullName>IN1</fullName>
                </value>
                <value>
                    <fullName>IT1</fullName>
                </value>
                <value>
                    <fullName>ME1</fullName>
                </value>
                <value>
                    <fullName>NL5</fullName>
                </value>
                <value>
                    <fullName>NO1</fullName>
                </value>
                <value>
                    <fullName>NZ1</fullName>
                </value>
                <value>
                    <fullName>PH1</fullName>
                </value>
                <value>
                    <fullName>SA5</fullName>
                </value>
                <value>
                    <fullName>SE1</fullName>
                </value>
                <value>
                    <fullName>SG1</fullName>
                </value>
                <value>
                    <fullName>UK1</fullName>
                </value>
                <value>
                    <fullName>US5</fullName>
                </value>
                <value>
                    <fullName>ZA1</fullName>
                </value>
                <value>
                    <fullName>ID1</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project</label>
    <nameField>
        <displayFormat>P{000000}</displayFormat>
        <label>Project Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <recordTypes>
        <fullName>Project</fullName>
        <active>true</active>
        <label>Project</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/CurrentUserInfoControlllerTester.cls
@isTest
public class CurrentUserInfoControlllerTester {
@istest(seealldata=true)
    public static void CurrentUserInfoControlllerTestMethod(){
        test.startTest();
        CurrentUserInfoController.fetchUser();
        Account account =createtestdata.GetAccount();
        Contact contact =createtestdata.getContact(account.Id);
        Opportunity opp = createtestdata.getOpportunity(account.Id, contact.Id);
        CurrentUserInfoController.fetchProject(CreateTestData.getProject(account.Id, createtestdata.getOpportunity(account.Id, createtestdata.getContact(account.Id).Id).Id).Id);
        CurrentUserInfoController.checkuser();
        NewExpense.fetchUser();
ScheduleBatchProjectDailyAlert sh1 = new ScheduleBatchProjectDailyAlert();
String sch = '0 0 2 * * ?'; 
system.schedule('Test Territory Check', sch, sh1); 
        ProjectObject__c project = createtestdata.getProject(account.Id, opp.Id);
        project.Is_Auto_Created__c = true;
        project.LBU__c='US5';
        update project;
        database.executeBatch(new Project_Daily_Alert());
        test.stopTest();
    }
}