objects/ProjectObject__c.object
<CustomObject>
    <description>Used for PSA work</description>
    <fields>
        <fullName>CPS_Project_Manager__c</fullName>
        <label>CPS Project Manager</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Abhishek Yadav</fullName>
                </value>
                <value>
                    <fullName>Akhil Aggarwal</fullName>
                </value>
                <value>
                    <fullName>Amandeepti</fullName>
                </value>
                <value>
                    <fullName>Anmol Kaul Dembi</fullName>
                </value>
                <value>
                    <fullName>Anna Perry</fullName>
                </value>
                <value>
                    <fullName>Brian Swords</fullName>
                </value>
                <value>
                    <fullName>Cathy Agnew</fullName>
                </value>
                <value>
                    <fullName>Claire Fix</fullName>
                </value>
                <value>
                    <fullName>Clay Ferrell</fullName>
                </value>
                <value>
                    <fullName>David Egerton-Smith</fullName>
                </value>
                <value>
                    <fullName>Debbie Determan</fullName>
                </value>
                <value>
                    <fullName>Deede Fulton</fullName>
                </value>
                <value>
                    <fullName>Dimple</fullName>
                </value>
                <value>
                    <fullName>Dragan Dragas</fullName>
                </value>
                <value>
                    <fullName>Ellie Mullins</fullName>
                </value>
                <value>
                    <fullName>Gavin Grover</fullName>
                </value>
                <value>
                    <fullName>Gemma Townsend</fullName>
                </value>
                <value>
                    <fullName>Giampaolo Squadroni</fullName>
                </value>
                <value>
                    <fullName>Hernan De Armas</fullName>
                </value>
                <value>
                    <fullName>Jaishree Medepalli</fullName>
                </value>
                <value>
                    <fullName>Jayant Yadav</fullName>
                </value>
                <value>
                    <fullName>Jennifer Blamey</fullName>
                </value>
                <value>
                    <fullName>Jennifer Skavnak</fullName>
                </value>
                <value>
                    <fullName>John Daniel</fullName>
                </value>
                <value>
                    <fullName>Julia Endersby</fullName>
                </value>
                <value>
                    <fullName>Karen Froistad</fullName>
                </value>
                <value>
                    <fullName>Katie Ohland</fullName>
                </value>
                <value>
                    <fullName>Kerry Moechnig-Studer</fullName>
                </value>
                <value>
                    <fullName>Kim Havelund</fullName>
                </value>
                <value>
                    <fullName>Kylie Angell</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CPS_Project_Number__c</fullName>
        <displayFormat>P{000000}</displayFormat>
        <label>CPS Project Number</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>LBU__c</fullName>
        <label>LBU</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AD1</fullName>
                </value>
                <value>
                    <fullName>AU1</fullName>
                </value>
                <value>
                    <fullName>BE5</fullName>
                </value>
                <value>
                    <fullName>CA1</fullName>
                </value>
                <value>
                    <fullName>CH1</fullName>
                </value>
                <value>
                    <fullName>CN1</fullName>
                </value>
                <value>
                    <fullName>CPS</fullName>
                </value>
                <value>
                    <fullName>DE5</fullName>
                </value>
                <value>
                    <fullName>DK1</fullName>
                </value>
                <value>
                    <fullName>FI1</fullName>
                </value>
                <value>
                    <fullName>FR5</fullName>
                </value>
                <value>
                    <fullName>HK1</fullName>
                </value>
                <value>
                    <fullName>IN1</fullName>
                </value>
                <value>
                    <fullName>IT1</fullName>
                </value>
                <value>
                    <fullName>ME1</fullName>
                </value>
                <value>
                    <fullName>NL5</fullName>
                </value>
                <value>
                    <fullName>NO1</fullName>
                </value>
                <value>
                    <fullName>NZ1</fullName>
                </value>
                <value>
                    <fullName>PH1</fullName>
                </value>
                <value>
                    <fullName>SA5</fullName>
                </value>
                <value>
                    <fullName>SE1</fullName>
                </value>
                <value>
                    <fullName>SG1</fullName>
                </value>
                <value>
                    <fullName>UK1</fullName>
                </value>
                <value>
                    <fullName>US5</fullName>
                </value>
                <value>
                    <fullName>ZA1</fullName>
                </value>
                <value>
                    <fullName>ID1</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Milestone_Status__c</fullName>
        <formula>IMAGE(IF( ROUND(Milestones_Value__c,2)  &lt;&gt;  ROUND(Total_Orderline_Value_RollUp__c,2) ,&quot;/img/samples/light_red.gif&quot;,&quot;/img/samples/light_green.gif&quot;),&quot;Project Status Indicator&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Green if milestones value equals total orderline value - otherwise red.</inlineHelpText>
        <label>Milestone Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Milestones_Value__c</fullName>
        <inlineHelpText>Total of all milestones associated with project</inlineHelpText>
        <label>Milestones Value</label>
        <summarizedField>Milestone__c.Amount__c</summarizedField>
        <summaryForeignKey>Milestone__c.Project__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Project_Health_Detail__c</fullName>
        <label>Project Health Detail</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Red</fullName>
                </value>
                <value>
                    <fullName>Amber</fullName>
                </value>
                <value>
                    <fullName>Green</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Project_Name__c</fullName>
        <label>Project Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total_Orderline_Value_RollUp__c</fullName>
        <label>Total Order Product Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Project</label>
    <nameField>
        <displayFormat>P{000000}</displayFormat>
        <label>Project Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <recordTypes>
        <fullName>Project</fullName>
        <active>true</active>
        <label>Project</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Workpacket__c.object
<CustomObject>
    <fields>
        <fullName>Agreed_Delivery__c</fullName>
        <label>Agreed Delivery</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CPS_Project_Number__c</fullName>
        <label>CPS Project Number</label>
        <referenceTo>ProjectObject__c</referenceTo>
        <relationshipLabel>Workpackets</relationshipLabel>
        <relationshipName>Workpackets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>LBU__c</fullName>
        <formula>CPS_Project_Number__r.LBU_CPS__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>LBU</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_PS__c</fullName>
        <label>Product/PS</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Product Support</fullName>
                </value>
                <value>
                    <fullName>PS Revenue</fullName>
                </value>
                <value>
                    <fullName>FOC</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Solution_Type__c</fullName>
        <label>Solution Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>360</fullName>
                </value>
                <value>
                    <fullName>Advisory Services</fullName>
                </value>
                <value>
                    <fullName>APTA</fullName>
                </value>
                <value>
                    <fullName>Aspiring Minds</fullName>
                </value>
                <value>
                    <fullName>BOS / Validation</fullName>
                </value>
                <value>
                    <fullName>Branding</fullName>
                </value>
                <value>
                    <fullName>Configurable Grad SJT</fullName>
                </value>
                <value>
                    <fullName>Custom Assessment</fullName>
                </value>
                <value>
                    <fullName>Custom Norm</fullName>
                </value>
                <value>
                    <fullName>Custom Report - Complex</fullName>
                </value>
                <value>
                    <fullName>Custom Report - TCR</fullName>
                </value>
                <value>
                    <fullName>Custom Scale</fullName>
                </value>
                <value>
                    <fullName>Data Extract</fullName>
                </value>
                <value>
                    <fullName>DPN Changes</fullName>
                </value>
                <value>
                    <fullName>Group Report</fullName>
                </value>
                <value>
                    <fullName>Integration – Production Additional Stream(s)</fullName>
                </value>
                <value>
                    <fullName>Integration - Production Build</fullName>
                </value>
                <value>
                    <fullName>Integration – UAT Additional Stream(s)</fullName>
                </value>
                <value>
                    <fullName>Integration - UAT Build</fullName>
                </value>
                <value>
                    <fullName>Internal</fullName>
                </value>
                <value>
                    <fullName>JFA</fullName>
                </value>
                <value>
                    <fullName>Localisation</fullName>
                </value>
                <value>
                    <fullName>MCP</fullName>
                </value>
                <value>
                    <fullName>Migration</fullName>
                </value>
                <value>
                    <fullName>Multimedia – Other</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Precise Fit</fullName>
                </value>
                <value>
                    <fullName>RJP Multimedia</fullName>
                </value>
                <value>
                    <fullName>RJP Text</fullName>
                </value>
                <value>
                    <fullName>Security Monitoring</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Planning</fullName>
                </value>
                <value>
                    <fullName>Executing</fullName>
                </value>
                <value>
                    <fullName>Closing</fullName>
                </value>
                <value>
                    <fullName>Closed/Delivered</fullName>
                </value>
                <value>
                    <fullName>Closed/Cancelled</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Workpacket</label>
    <nameField>
        <displayFormat>WP-{00000000}</displayFormat>
        <label>Workpacket Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Workpackets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/WorkpacketBulkController.cls
public class WorkpacketBulkController {

    @AuraEnabled
    public static String saveWorkpackets(List<Workpacket__c> WorkpacketList){
        try{
        Upsert WorkpacketList; 
        return 'Workpacket records saved successfully';
        }
        catch(Exception e)
        {
            return e.getMessage();
        }
    }
      @AuraEnabled
    public static ProjectObject__c getProjectData(Id ProjectId){
        system.debug('Project Id '+ProjectId);
     return [select Id,Project_Name__c,LBU__c,CurrencyIsoCode,Project_Health_Detail__c,Milestone_Status__c,Milestones_Value__c,Total_Orderline_Value_RollUp__c from ProjectObject__c where Id=:ProjectId];
    }
     @AuraEnabled
    public static List<Workpacket__c> getData(String SelectedIds){
        
        system.debug('Selected Ids '+SelectedIds);
        List<String> result = SelectedIds.split(',');
        List<Workpacket__c> Workpackets = [Select CPS_Project_Number__c,Product_PS__c,Solution_Type__c,Status__c,Agreed_Delivery__c,Description__c,CPS_Project_Manager__c,Name,Actual_Delivery__c,Delivery_Variance_Comment__c,Reasons_For_Changed_Delivery_Date__c from Workpacket__c where Id IN:result];
        return Workpackets;
    }
    
}