force-app/main/objects/Account.object
<CustomObject>
    <fields>
        <fullName>BU__c</fullName>
        <label>BU</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Master_BUs</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Billing_Address_Line_1__c</fullName>
        <inlineHelpText>If the address goes over more than one line then please use Address Line 2 and Address Line 3. This formatting will display on any Customer facing documents.</inlineHelpText>
        <label>Billing Address Line 1</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_City__c</fullName>
        <label>Billing City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_Country__c</fullName>
        <label>Billing Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AFGHANISTAN</fullName>
                </value>
                <value>
                    <fullName>ALBANIA</fullName>
                </value>
                <value>
                    <fullName>ALDERNEY</fullName>
                </value>
                <value>
                    <fullName>ALGERIA</fullName>
                </value>
                <value>
                    <fullName>AMERICAN SAMOA</fullName>
                </value>
                <value>
                    <fullName>ANDORRA</fullName>
                </value>
                <value>
                    <fullName>ANGOLA</fullName>
                </value>
                <value>
                    <fullName>ANGUILLA</fullName>
                </value>
                <value>
                    <fullName>ANTARCTICA</fullName>
                </value>
                <value>
                    <fullName>ANTIGUA AND BARBUDA</fullName>
                </value>
                <value>
                    <fullName>ARGENTINA</fullName>
                </value>
                <value>
                    <fullName>ARMENIA</fullName>
                </value>
                <value>
                    <fullName>ARUBA</fullName>
                </value>
                <value>
                    <fullName>AUSTRALIA</fullName>
                </value>
                <value>
                    <fullName>AUSTRIA</fullName>
                </value>
                <value>
                    <fullName>AZERBAIJAN</fullName>
                </value>
                <value>
                    <fullName>BAHAMAS</fullName>
                </value>
                <value>
                    <fullName>BAHRAIN</fullName>
                </value>
                <value>
                    <fullName>BANGLADESH</fullName>
                </value>
                <value>
                    <fullName>BARBADOS</fullName>
                </value>
                <value>
                    <fullName>BELARUS</fullName>
                </value>
                <value>
                    <fullName>BELGIUM</fullName>
                </value>
                <value>
                    <fullName>BELIZE</fullName>
                </value>
                <value>
                    <fullName>BENIN</fullName>
                </value>
                <value>
                    <fullName>BERMUDA</fullName>
                </value>
                <value>
                    <fullName>BHUTAN</fullName>
                </value>
                <value>
                    <fullName>BOLIVIA</fullName>
                </value>
                <value>
                    <fullName>BOSNIA AND HERZEGOWINA</fullName>
                </value>
                <value>
                    <fullName>BOTSWANA</fullName>
                </value>
                <value>
                    <fullName>BOUVET ISLAND</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Billing_State__c</fullName>
        <inlineHelpText>If State is required, please enter as two alphanumeric characters, e.g. GA instead of Georgia</inlineHelpText>
        <label>Billing State/County</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_ZIP_Postal_Code__c</fullName>
        <label>Billing ZIP/Postal Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>1. Not yet trading with SHL - (definition - the account is new and/or has no trading history with SHL to date)
2. Trading with SHL - (definition - the account has sales recorded with SHL in the last 2 years)
3. Ceased Trading with SHL - (definition - the account has not traded with SHL in the past 12 months but has previously.) 
4. Dead - (Gone out of Business) (definition - The Account for whatever reason is no longer a trading entity)
Previous Values
1. Active with SHL (definition - The account has a track record of sales and/or opportunities managed in the last 2 years)
2. Inactive with SHL (definition - The account is still a trading account but there has been no activity with SHL (sales or opportunities managed) in the last 2 years)</description>
        <inlineHelpText>Status indicates if Account is approved or not. If you believe an unapproved Account should be Approved, Submit for Approval.</inlineHelpText>
        <label>Account Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Unapproved</fullName>
                    <default>true</default>
                    <label>Unapproved</label>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Unapproved - Out of Business</fullName>
                </value>
                <value>
                    <fullName>Unapproved - Trade Not Allowed</fullName>
                </value>
                <value>
                    <fullName>Unapproved - Duplicate</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

force-app/main/objects/Activity.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

objects/Talent_Central__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Talent_Central</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Current_Transition_Activity__c</fullName>
        <label>Current Transition Activity</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Confirmation letter approved</fullName>
                </value>
                <value>
                    <fullName>Confirmation letter received</fullName>
                </value>
                <value>
                    <fullName>Confirmation letter rejected</fullName>
                </value>
                <value>
                    <fullName>Confirmation letter sent</fullName>
                </value>
                <value>
                    <fullName>Do Not Transition - Client Rejection</fullName>
                </value>
                <value>
                    <fullName>Do Not Transition - Deferred</fullName>
                </value>
                <value>
                    <fullName>Do Not Transition - Inactive Client</fullName>
                </value>
                <value>
                    <fullName>No confirmation letter required - client agreed</fullName>
                </value>
                <value>
                    <fullName>Reverted to legacy system</fullName>
                </value>
                <value>
                    <fullName>Selected for Transition</fullName>
                </value>
                <value>
                    <fullName>Selected for Transition – On Hold</fullName>
                </value>
                <value>
                    <fullName>Transition Date Confirmed</fullName>
                </value>
                <value>
                    <fullName>Transition Activity Completed</fullName>
                </value>
                <value>
                    <fullName>Transitioned - legacy system still active</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TC_Transition_Slot__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>TC Transition Slot</label>
        <referenceTo>TC_Transition_Slot__c</referenceTo>
        <relationshipName>TalentCentral_Transition</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Transition_Slot_Type__c</fullName>
        <formula>text(TC_Transition_Slot__r.Transition_Slot_Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Transition Slot Type</label>
        <type>Text</type>
    </fields>
    <label>TC Upgrade</label>
    <nameField>
        <displayFormat>TCU-{0000}</displayFormat>
        <label>TC Upgrade Record</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TC Upgrade</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/objects/TC_Transition_Slot__c.object
<CustomObject>
    <fields>
        <fullName>Booking_Availability__c</fullName>
        <label>Booking Availability</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Low Touch - Date Pre-allocated</fullName>
                </value>
                <value>
                    <fullName>Global Priority Slot - By Special Request</fullName>
                </value>
                <value>
                    <fullName>Standard_Bookable</fullName>
                    <label>Standard - Bookable</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Maximum_Transitions__c</fullName>
        <label>Maximum Transitions</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Transition_Slot_Description__c</fullName>
        <label>Transition Slot Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Transition_Slot_Type__c</fullName>
        <label>Transition Slot Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Low Touch</fullName>
                </value>
                <value>
                    <fullName>Integrated</fullName>
                </value>
                <value>
                    <fullName>Standalone</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>TC Transition Slot</label>
    <nameField>
        <displayFormat>TCS-{000000}</displayFormat>
        <label>TC Transition Slot</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TC Transition Slots</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/Master_BUs.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Abu Dhabi - AD1</fullName>
    </customValue>
    <customValue>
        <fullName>Australia - AU1</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium SPS - BE5</fullName>
    </customValue>
    <customValue>
        <fullName>Canada - CA1</fullName>
    </customValue>
    <customValue>
        <fullName>China - CN1</fullName>
    </customValue>
    <customValue>
        <fullName>Denmark - DK1</fullName>
    </customValue>
    <customValue>
        <fullName>Finland - FI1</fullName>
    </customValue>
    <customValue>
        <fullName>France SPS - FR5</fullName>
    </customValue>
    <customValue>
        <fullName>Germany SPS - DE5</fullName>
    </customValue>
    <customValue>
        <fullName>Hong Kong - HK1</fullName>
    </customValue>
    <customValue>
        <fullName>India - IN1</fullName>
    </customValue>
    <customValue>
        <fullName>Italy - IT1</fullName>
    </customValue>
    <customValue>
        <fullName>Middle East - ME1</fullName>
    </customValue>
    <customValue>
        <fullName>Netherlands SPS - NL5</fullName>
    </customValue>
    <customValue>
        <fullName>New Zealand - NZ1</fullName>
    </customValue>
    <customValue>
        <fullName>Norway - NO1</fullName>
    </customValue>
    <customValue>
        <fullName>Philippines - PH1</fullName>
    </customValue>
    <customValue>
        <fullName>Saudi Arabia - SA5</fullName>
    </customValue>
    <customValue>
        <fullName>Singapore - SG1</fullName>
    </customValue>
    <customValue>
        <fullName>South Africa - ZA1</fullName>
    </customValue>
    <customValue>
        <fullName>Sweden - SE1</fullName>
    </customValue>
    <customValue>
        <fullName>Switzerland - CH1</fullName>
    </customValue>
    <customValue>
        <fullName>UK - UK1</fullName>
    </customValue>
    <customValue>
        <fullName>US - US5</fullName>
    </customValue>
    <customValue>
        <fullName>Indonesia - ID1</fullName>
    </customValue>
    <customValue>
        <fullName>Asia Pac	India</fullName>
        <isActive>false</isActive>
        <label>Asia Pac	India</label>
    </customValue>
    <customValue>
        <fullName>Asia Pac	Singapore</fullName>
        <isActive>false</isActive>
        <label>Asia Pac	Singapore</label>
    </customValue>
    <customValue>
        <fullName>Asia Pac	AP Region</fullName>
        <isActive>false</isActive>
        <label>Asia Pac	AP Region</label>
    </customValue>
    <customValue>
        <fullName>UK	  - UK1</fullName>
        <isActive>false</isActive>
        <label>UK	  - UK1</label>
    </customValue>
    <customValue>
        <fullName>Head Office  - H50</fullName>
        <isActive>false</isActive>
        <label>Head Office  - H50</label>
    </customValue>
    <masterLabel>Master BUs</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

classes/testutilityclass.cls
@isTest(SeeAllData=true)
public class testutilityclass {
    
    @isTest
    static void testUtilityMethods()
    {   
        Datetime variable=System.now();
        String Testname='Test Account'+variable;
        Account account=new Account(name=Testname,Status__c='Approved',Billing_Address_Line_1__c='test',Billing_City__c='Test City',Billing_Country__c='Test Country',Billing_State__c='Test',Billing_ZIP_Postal_Code__c='1100110',BU__c='Australia - AU1',industry='Agriculture');
        insert account;
        
        List<TC_Transition_Slot__c> lTCSlot = new List<TC_Transition_Slot__c>();
        TC_Transition_Slot__c tcslotRec = new TC_Transition_Slot__c();
        
        tcslotRec.Transition_Slot_Description__c = 'test';
        tcslotRec.Transition_Slot_Type__c = 'Standard';
        tcslotRec.Booking_Availability__c = 'Regional slot - bookable';
        tcslotRec.Date__c = system.today().addDays(29);
        tcslotRec.Maximum_Transitions__c = 10;
        lTCSlot.add(tcslotRec);
        
        
        List<Talent_Central__c> lTcRec = new List<Talent_Central__c>();
        Talent_Central__c tcRec = new Talent_Central__c();
        tcRec.Account__c = account.id;
        tcRec.Current_Transition_Activity__c = 'Transition Activity Completed';
        tcRec.TC_Transition_Slot__c = lTCSlot[0].id;
        lTcRec.add(tcRec);
        insert ltcRec;
        
        test.startTest();
        
        Utility.slotProvandConfTotal(lTcRec);
        Utility.delTCTransitionRec(lTcRec);
        Set<string> resultstring = Utility.getOpptyType();
        Set<String> resultstring8=Utility.getAccountTradingStatus();
        String resultstring7=Utility.getOpptyTypeNBBNL();
        String resultstring9=Utility.getOpptyTypeNBBCS();
        Set<string> resultstring2 = Utility.getSystemTransitionStatus();
        string resultstring3 = Utility.getCurrentTransitionActivity();
        Set<string> resultstring4 = Utility.getIMLookupCode();
        string resultstring5 = Utility.getBookingStatus();
        Set<string> resultstring6 = Utility.getSubscriptionPBI();
        Set<string> resultstring10 = Utility.getSubscriptionPBIName(); 
        Set<String> resultstring11=Utility.getOrderLineItemValuesFilter2();
        Set<String> resultstring12=Utility.getOrderLineItemValuesFilter1();
        Set<String> resultstring13=Utility.getOrderLineItemValuesFilter1_1();
        Set<String> resultstring14=Utility.getUlyanaFerreria();
        Set<String> resultstring15=Utility.getAutoRenewalfromOrder();
        Set<String> resultstring16=Utility.getreboostProducts();
        Set<String> resultstring17=Utility.getEACVvaluesforOrder();
        List<String> resultstring18=Utility.getMultiYearOrderLinesName();
        List<String> resultstring19=Utility.getMultiYearOrderLinesPlatform();
        List<String> resultstring20=Utility.getSubscriptionProductSequence();
        List<String> resultstring21=Utility.getMilestoneWatcheremail();
        boolean resultstring22=Utility.getMWatcherChecked();
        
        test.stopTest();
    }
}