force-app/main/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Buying_Centre_Id__c</fullName>
        <description>Fro regional grouping of the same accounts, this field will be populated by the BI team.</description>
        <label>Buying Centre Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

force-app/main/objects/Account_Plan__c.object
<CustomObject>
    <description>Module to capture Key Account Plan details</description>
    <fields>
        <fullName>Account_Name__c</fullName>
        <description>This field is used to store the related account for Account Plan</description>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Plans</relationshipLabel>
        <relationshipName>Account_Plans</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Account_Plan_Status__c</fullName>
        <label>Account Plan Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>In Review</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Retired</fullName>
                </value>
                <value>
                    <fullName>Migrated to Regional - Retired</fullName>
                    <isActive>false</isActive>
                    <label>Migrated to Regional - Retired</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Account_Plan_Type__c</fullName>
        <description>Created in Account Plan Phase 4 to determine the type of Account Plan</description>
        <inlineHelpText>This field is used to determine the type of Account Plan</inlineHelpText>
        <label>Account Plan Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Current</fullName>
                    <default>true</default>
                    <label>Current</label>
                </value>
                <value>
                    <fullName>Regional</fullName>
                </value>
                <value>
                    <fullName>Global</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Buying_Centre_Id__c</fullName>
        <description>This is used to identify if an Account Plan is Regional Account Plan .</description>
        <inlineHelpText>This field shows the value of Buying Centre same as on Account if an Account Plan is regional</inlineHelpText>
        <label>Buying Centre Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Account Plan</label>
    <nameField>
        <displayFormat>ACP-{0000}</displayFormat>
        <label>Account Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ProjectObject__c.object
<CustomObject>
    <description>Used for PSA work</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Closed_Date__c</fullName>
        <description>This captures the latest date, whenever a project is marked Completed or Cancelled.</description>
        <label>Project Closed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project_Status__c</fullName>
        <label>Project Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Initiation</fullName>
                </value>
                <value>
                    <fullName>Planning</fullName>
                </value>
                <value>
                    <fullName>Executing</fullName>
                </value>
                <value>
                    <fullName>Closing</fullName>
                </value>
                <value>
                    <fullName>Closed/Delivered</fullName>
                </value>
                <value>
                    <fullName>Closed/Cancelled</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Live</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project</label>
    <nameField>
        <displayFormat>P{000000}</displayFormat>
        <label>Project Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/objects/Strategy_and_Goal__c.object
<CustomObject>
    <fields>
        <fullName>Account_Plan_Status__c</fullName>
        <formula>TEXT(Account_Plan__r.Account_Plan_Status__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Plan Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account_Plan__c</fullName>
        <label>Account Plan</label>
        <referenceTo>Account_Plan__c</referenceTo>
        <relationshipLabel>Strategies and Goals</relationshipLabel>
        <relationshipName>Strategies_and_Goals</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Strategy_Name__c</fullName>
        <label>Strategy Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Strategy and Goals</label>
    <nameField>
        <displayFormat>STR-{0000}</displayFormat>
        <label>Strategy Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Strategies and Goals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CustomLookupController.cls
public with Sharing class CustomLookupController {
    
    public static Date sixMonthsAgo;

    @AuraEnabled(cacheable=true)
    public static List<SObjectWrapper> getRequiredLookupRecords(String itemToSearch, String objectName, String filter, String accountPlanId) {
        String query = null;
        String name ='';
        String queryMode = '';
        
        Account_Plan__c accplan = new Account_Plan__c();
        name = objectName=='Strategy_and_Goal__c'?'Strategy_Name__c':'Name';
        //System.debug(' CustomLookupController ' + objectName);
        if(accountPlanId != ''){
            accplan = [select id , Account_Name__c,Account_Plan_Status__c , Account_Name__r.CurrencyIsoCode,Account_Plan_Type__c,Buying_Centre_Id__c
                                   from Account_Plan__c where id=:accountPlanId];
        }else{
            queryMode = 'System';
        }
        //System.debug(' CustomLookupController ' + queryMode);
        List<Id> accountIdList = new List<Id>();
        if(objectName=='Contact'){
            if(accplan.Account_Plan_Type__c=='Regional'){
            List<Account> accList = [SELECT Id FROM Account WHERE Buying_Centre_Id__c= :accplan.Buying_Centre_Id__c];
            List<Id> accIds = new List<Id>();
            for (Account acc : accList) {
                accIds.add(acc.Id);
            }
            accountIdList = accIds;
        }else if(accplan.Account_Plan_Type__c=='Current'){
            accountIdList.add(accplan.Account_Name__c);
        }else if(accplan.Account_Plan_Type__c=='Global'){
            Set<Id> allAccountIds = new Set<Id>{accplan.Account_Name__c};
                Set<Id> parentIds = new Set<Id>{accplan.Account_Name__c};
                    List<Account> childAccounts = new List<Account>();
            do {
                childAccounts = [SELECT Id FROM Account WHERE ParentId IN :parentIds AND RecordType.name != 'Competitor Account'];
                parentIds.clear();
                for (Account child : childAccounts){
                    parentIds.add(child.Id);
                    allAccountIds.add(child.Id);
                }
            } while (childAccounts.size() > 0);
            accountIdList = new List<Id>(allAccountIds);
        }
        }
        if(filter != null && filter != ''){
            if(objectName=='Contact'){
                query = 'Select Id,Account_D_Number__c,'+ name +' from '+objectName+' Where '+ name +' Like  \'%' + itemToSearch + '%\' AND '+'AccountId IN :accountIdList'+' LIMIT  5';
            }else{
                query = 'Select Id,'+ name +' from '+objectName+' Where '+ name +' Like  \'%' + itemToSearch + '%\' AND '+filter+' LIMIT  5';
            }
        }
        else {
            if(itemToSearch == null || itemToSearch == ''){
                if(objectName=='ProjectObject__c'){
                    sixMonthsAgo = Date.today().addMonths(-6);
                 	query = 'Select Id, Account__r.Name,'+ name +' from '+objectName+' Where LastViewedDate != NULL' +
               ' AND ((Project_Status__c != \'Closed\' AND Project_Status__c != \'Cancelled\')' + 
               ' OR (Project_Status__c IN (\'Closed\', \'Cancelled\')' + 
               ' AND Project_Closed_Date__c >= :sixMonthsAgo))' + 
               ' ORDER BY LastViewedDate DESC LIMIT 5';
                //System.debug(query);
                }else{
                	query = 'Select Id,'+ name +' from '+objectName+' Where LastViewedDate != NULL ORDER BY LastViewedDate DESC LIMIT  5';
                }
            }
            else {
                if(objectName=='ProjectObject__c'){
                    sixMonthsAgo = Date.today().addMonths(-6);
                    query = 'Select Id, Account__r.Name,'+ name +' from '+objectName+' Where ('+ name +' Like  \'%' + itemToSearch + '%\' OR Account__r.Name Like  \'%' + itemToSearch + '%\')'+ 
               ' AND ((Project_Status__c != \'Closed\' AND Project_Status__c != \'Cancelled\')' + 
               ' OR (Project_Status__c IN (\'Closed\', \'Cancelled\')' + 
               ' AND Project_Closed_Date__c >= :sixMonthsAgo ))' + 
               ' LIMIT 5';
                 //System.debug(query);
                }else{
                	query = 'Select Id,'+ name +' from '+objectName+' Where '+ name +' Like  \'%' + itemToSearch + '%\' LIMIT  5';
                }
            }
        }
        //system.debug(query);
        List<sObject> listToProcess = new List<sObject>();
        if(queryMode=='System'){
            QueryInSystemMode queryClassObject = new QueryInSystemMode();
 			listToProcess = queryClassObject.getData(query);
        }else{
            listToProcess = database.query(query);
        }
        List<SObjectWrapper> listToReturn = new List<SObjectWrapper>();
        for (sObject obj : listToProcess) {
            SObjectWrapper wrap = new SObjectWrapper();
            wrap.Id = obj.Id;
            wrap.Name = objectName!='Contact' || (accplan.Account_Plan_Type__c=='Current' && objectName=='Contact')?(String) obj.get(name): (String) obj.get(name)+' - '+ (String)obj.get('Account_D_Number__c');
            if(objectName=='ProjectObject__c'){
                wrap.AccountName = (String)obj.getSobject('Account__r').get(name);
            }
            listToReturn.add(wrap);
        }
        return listToReturn;
    }
    
    public without sharing class QueryInSystemMode{
        
        public List<sObject> getData(String query){
            //system.debug(sixMonthsAgo);
            return database.query(query);
        }
    }

    public class SObjectWrapper{
        @AuraEnabled public Id Id;
        @AuraEnabled public String Name;
        @AuraEnabled public String AccountName;
    }
}