force-app/main/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Territory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Territory</label>
        <lookupFilter>
            <active>false</active>
            <errorMessage>Territory associated with an account should be active</errorMessage>
            <filterItems>
                <field>Territory__c.Is_Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Territory__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

force-app/main/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Business_Type__c</fullName>
        <description>Choose the Opportunity Type that best describes the type of business pursued.  
Reboost should only be used with In-Advance clients. 
Cross-sell is simply New Business with a client that has a current commercial relationship.</description>
        <label>Opportunity Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Expansion</fullName>
                </value>
                <value>
                    <fullName>Renewal</fullName>
                </value>
                <value>
                    <fullName>Debooking</fullName>
                    <label>Debooking / Adjustment</label>
                </value>
                <value>
                    <fullName>Extension</fullName>
                </value>
                <value>
                    <fullName>In Arrears</fullName>
                </value>
                <value>
                    <fullName>In Advance</fullName>
                </value>
                <value>
                    <fullName>Managed Services</fullName>
                </value>
                <value>
                    <fullName>Professional Services: non-subscription</fullName>
                </value>
                <value>
                    <fullName>Top Up / Addition</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity_Deal_Year__c</fullName>
        <defaultValue>1</defaultValue>
        <description>Current Deal Year of Opportunity</description>
        <label>Opportunity Year</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Original_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Original Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Variation / Renewal Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Previous_Price__c</fullName>
        <inlineHelpText>Annual value of all recurring products from the original Opportunity</inlineHelpText>
        <label>Previous Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Recurring_Products_value__c</fullName>
        <inlineHelpText>Sum of all Recurring products that will form part of ARR and appear on the subsequent renewal Opportunity</inlineHelpText>
        <label>Recurring Products value</label>
        <summarizedField>OpportunityLineItem.TotalPrice</summarizedField>
        <summaryFilterItems>
            <field>OpportunityLineItem.RenewableNew__c</field>
            <operation>equals</operation>
            <value>Ongoing</value>
        </summaryFilterItems>
        <summaryForeignKey>OpportunityLineItem.OpportunityId</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Renewal_Date__c</fullName>
        <inlineHelpText>This date is calculated from the Contract End Date + 1 day and signifies the true date that the next Renewal is due to start on.</inlineHelpText>
        <label>Renewal Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Renewal_Opportunity__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Auto-Created Renewal</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sales_Price_in_USD__c</fullName>
        <description>Used in Account Plan to show USD vaue on contract details.</description>
        <formula>IF(
TEXT(CurrencyIsoCode) = &apos;USD&apos;, Amount,
Amount / CURRENCYRATE(TEXT(CurrencyIsoCode))*CURRENCYRATE(&apos;USD&apos;))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sales Price in USD</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
</CustomObject>

force-app/main/objects/Territory__c.object
<CustomObject>
    <label>Territory</label>
    <nameField>
        <label>Territory</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TerritoryApprovalResolver.cls
public with sharing class TerritoryApprovalResolver {

    @InvocableMethod(
        label='Get Approval Group Fields from Territory'
        description='Resolves Territory approval fields dynamically from Opportunity.Account.Territory__r'
    )
    public static List<OutputWrapper> resolveApproval(List<InputWrapper> inputs) {
        List<OutputWrapper> results = new List<OutputWrapper>();
        OutputWrapper output = new OutputWrapper();
        List<String> approvalFields = new List<String>();
        List<String> currentApprovers = new List<String>();
        List<String> escalationLevel1Approvers = new List<String>();
        List<String> escalationLevel2Approvers = new List<String>();
        List<String> priorApprovers = new List<String>();
        String originalApproverString;
        String escalationLevel1ApproverString;
        String escalationLevel2ApproverString;
        String priorApproverString;

        if (inputs == null || inputs.isEmpty()) {
            return results;
        }
		
        String approvalStatus = inputs.get(0).discountApprovalStatus;
        if(approvalStatus == 'Submitted for Approval'){
            originalApproverString = inputs.get(0).originalApprovers;
        }else if(approvalStatus == 'Escalated Level 1'){
            escalationLevel1ApproverString = inputs.get(0).originalApprovers;
            priorApproverString = inputs.get(0).escalationLevel1Approvers;
        }else if(approvalStatus == 'Escalated Level 2'){
            escalationLevel2ApproverString = inputs.get(0).originalApprovers;
            priorApproverString = inputs.get(0).escalationLevel1Approvers;
        }
        Id opportunityId = inputs.get(0).recordId;
        
        if(originalApproverString != null){
            currentApprovers = originalApproverString.split(';');
            approvalFields.addAll(currentApprovers);
            //output.currentApproverList = currentApprovers;
        }
        if(escalationLevel1ApproverString != null){
            escalationLevel1Approvers = escalationLevel1ApproverString.split(';');
            approvalFields.addAll(escalationLevel1Approvers);
            //output.priorApproverList = escalationLevel1Approvers;
        }
        if(escalationLevel2ApproverString != null){
            escalationLevel2Approvers = escalationLevel2ApproverString.split(';');
            approvalFields.addAll(escalationLevel2Approvers);
        }
        if(priorApproverString != null){
            priorApprovers = priorApproverString.split(';');
            approvalFields.addAll(priorApprovers);
        }
        
        Opportunity opportunityRecord = [SELECT Id, Account.Territory__c, Opportunity_Deal_Year__c,
                                         Business_Type__c, Renewal_Opportunity__c, Renewal_Date__c,
                                         Sales_Price_in_USD__c, Original_Opportunity__c, 
                                         Original_Opportunity__r.Sales_Price_in_USD__c,
                                         Recurring_Products_value__c, Previous_Price__c
                                         FROM Opportunity WHERE Id = :opportunityId LIMIT 1];
        Id territoryId = opportunityRecord.Account.Territory__c;
        String soql = 'SELECT Id ';
                for (String fieldApi : approvalFields) {
                    soql += ', ' + fieldApi;
                    soql += ', ' + fieldApi.replace('__c','__r.Username');
                    soql += ', ' + fieldApi.replace('__c','__r.Name');
                }
                soql += ' FROM Territory__c WHERE Id = :territoryId LIMIT 1';
         System.debug('soql '+ soql);       
                list<Territory__c> territoryData = Database.query(soql);
                SObject territory = territoryData[0];
        
        Boolean doNotSendApprovalToCRO = false;
        Boolean sendApprovalOnlyToCRO = false;
        
        if(opportunityRecord.Opportunity_Deal_Year__c == 1
          && opportunityRecord.Business_Type__c == 'Renewal'
          && opportunityRecord.Renewal_Opportunity__c == true
          && opportunityRecord.Renewal_Date__c != null
		  && opportunityRecord.Recurring_Products_value__c >= 100001
		  && opportunityRecord.Recurring_Products_value__c <= 300000
          ){
              Decimal originalACV = opportunityRecord.Previous_Price__c;
              Decimal renewalACV = opportunityRecord.Recurring_Products_value__c;
              Decimal calculateDecrease = ((originalACV - renewalACV)/originalACV) * 100;
              if(calculateDecrease <= 15){
                  doNotSendApprovalToCRO = true;
              }
			  if(calculateDecrease > 15){
                  sendApprovalOnlyToCRO = true;
              }
        }
        
        for (String fieldApi : currentApprovers){
            String relationshipName = fieldApi.replace('__c','__r');
            SObject userObj = territory.getSObject(relationshipName);
            if (userObj != null) {
                String username = (String) userObj.get('Username');
                System.debug('username '+ username);
                if(fieldApi.trim().toLowerCase().contains('commercial_leader_primary')){
                    output.leader1 = username;
                    output.CommercialDirector = null;
                }
                if(fieldApi.trim().toLowerCase().contains('commercial_leader_secondary')){
                    output.leader2 = username;
                    output.CommercialDirector = null;
                } 
                if(fieldApi.trim().toLowerCase().contains('commercial_director')){
                    output.CommercialDirector = username;
                }
                if (fieldApi.trim().toLowerCase().contains('fbp_team')) {
                    output.FBPTeam = username;
                }
                if (!sendApprovalOnlyToCRO && fieldApi.trim().toLowerCase().contains('fbp_director')) {
                //if(fieldApi.trim().toLowerCase().contains('fbp_director')) {
                    output.FBPDirector = username;
                }
                if (!doNotSendApprovalToCRO && fieldApi.trim().toLowerCase().contains('cro')) {
                //if(fieldApi.trim().toLowerCase().contains('cro')) {
                    output.CRO = username;
                }
                if (!sendApprovalOnlyToCRO && fieldApi.trim().toLowerCase().contains('md')) {
                //if (fieldApi.trim().toLowerCase().contains('md')) {
                    output.MD = username;
                }
            }
        }
        
        for (String fieldApi : escalationLevel1Approvers){
            String relationshipName = fieldApi.replace('__c','__r');
            SObject userObj = territory.getSObject(relationshipName);
            if (userObj != null) {
                String username = (String) userObj.get('Username');
                System.debug('username '+ username);
                if(output.escalationLevel1Approver1 == null){
                 	output.escalationLevel1Approver1 = username;   
                }else{
                    output.escalationLevel1Approver2 = username;   
                }
            }
        }
        
        for (String fieldApi : escalationLevel2Approvers){
            String relationshipName = fieldApi.replace('__c','__r');
            SObject userObj = territory.getSObject(relationshipName);
            if (userObj != null) {
                String username = (String) userObj.get('Username');
                System.debug('username '+ username);
                if(output.escalationLevel2Approver1 == null){
                 	output.escalationLevel2Approver1 = username;   
                }else{
                    output.escalationLevel2Approver2 = username;   
                }
            }
        }

        for (String fieldApi : priorApprovers){
            String relationshipName = fieldApi.replace('__c','__r');
            SObject userObj = territory.getSObject(relationshipName);
            if (userObj != null) {
                String fullname = (String) userObj.get('Name');
                System.debug('fullname '+ fullname);
                if(output.priorApproverForEmailBody == null){
                 	output.priorApproverForEmailBody = fullname;   
                }else{
                    output.priorApproverForEmailBody = output.priorApproverForEmailBody + ', ' + fullname;   
                }
            }
        }
        results.add(output);
        return results;
    }

    // INPUT
    public class InputWrapper {
		    
        @InvocableVariable(required=true)
        public Id recordId;

        @InvocableVariable(required=true)
        public String originalApprovers;
        
        @InvocableVariable(required=true)
        public String discountApprovalStatus;

        @InvocableVariable(required=false)
        public String escalationLevel1Approvers;

        @InvocableVariable(required=false)
        public String escalationLevel2Approvers;
    }


    // OUTPUT
    public class OutputWrapper {
	
        // Normal approval outputs
        @InvocableVariable
        public String CommercialDirector;

        @InvocableVariable
        public String FBPTeam;

        @InvocableVariable
        public String FBPDirector;

        @InvocableVariable
        public String CRO;

        @InvocableVariable
        public String MD;
        
        @InvocableVariable
        public String leader1;

        @InvocableVariable
        public String leader2;

        // Escalation outputs
        @InvocableVariable
        public String escalationLevel1Approver1;

        @InvocableVariable
        public String escalationLevel1Approver2;
        
        @InvocableVariable
        public String escalationLevel2Approver1;

        @InvocableVariable
        public String escalationLevel2Approver2;

        @InvocableVariable
        public list<String> currentApproverList;

        @InvocableVariable
        public list<String> priorApproverList;

        @InvocableVariable
        public list<String> priorToPriorApproverList;

        @InvocableVariable
        public String priorApproverForEmailBody;
    }
}