force-app/main/objects/Account.object
<CustomObject>
    <fields>
        <fullName>SFDC2SUN_SfdcVersion__c</fullName>
        <description>The latest version of the SFDC record which has been transferred to Sun. (NOT USED ANYMORE)</description>
        <inlineHelpText>The latest version of the SFDC record which has been transferred to Sun.</inlineHelpText>
        <label>SFDC2SUN: SFDC Version (Legacy)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SFDC2SUN_SyncStatus__c</fullName>
        <description>The current status of the sync between this record in SFDC and Sun.</description>
        <inlineHelpText>The current status of the sync between this record in SFDC and Sun.</inlineHelpText>
        <label>SFDC2SUN: Sync Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Out of Sync</fullName>
                </value>
                <value>
                    <fullName>Ready for Sync</fullName>
                </value>
                <value>
                    <fullName>Synced</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SFDC2SUN_TransferStatus__c</fullName>
        <description>The status of the last transfer attempt from SFDC to Sun.</description>
        <inlineHelpText>The status of the last transfer attempt from SFDC to Sun.</inlineHelpText>
        <label>SFDC2SUN: Transfer Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Ready for Transfer</fullName>
                </value>
                <value>
                    <fullName>Not Transferred</fullName>
                </value>
                <value>
                    <fullName>Transferred</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SFDC2SUN_TransferredBy__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The user who last transferred the record from SFDC to Sun.</description>
        <inlineHelpText>The user who last transferred the record from SFDC to Sun.</inlineHelpText>
        <label>SFDC2SUN: Transferred By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts2</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Constant_Soft_Bounce_Contact__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Constant Soft Bounce Contact</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Constant_Soft_Bounce_Domain__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Constant Soft Bounce Domain</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Contact_Status__c</fullName>
        <description>To determine which of our contacts are the actual buyers and which can be marketed to and which we have lost contact with</description>
        <label>Contact Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Deceased</fullName>
                </value>
                <value>
                    <fullName>Left Institution</fullName>
                </value>
                <value>
                    <fullName>Retired</fullName>
                </value>
                <value>
                    <fullName>Active-Invalid Email</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Do_Not_Contact__c</fullName>
        <defaultValue>false</defaultValue>
        <description>replaces do not call</description>
        <inlineHelpText>Person cannot be contacted by email, phone, or marketing activity.</inlineHelpText>
        <label>Do Not Contact</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Double_Opted_In__c</fullName>
        <label>Double Opted In</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Email_Group_Subscription__c</fullName>
        <label>Email Group Subscription</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Newsletters</fullName>
                </value>
                <value>
                    <fullName>Service and Event</fullName>
                </value>
                <value>
                    <fullName>Event and Training</fullName>
                </value>
                <value>
                    <fullName>Products and Solutions</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Email_Opt_In__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check box if contact specifically opts in to e-mails</description>
        <label>Email Opt In</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Email_Opted_In__c</fullName>
        <inlineHelpText>Indicates if the contact has opted out of emails. Read only from Eloqua. No = Opted IN to emails. Contact by email is OK. Yes = Opted OUT of emails. Don’t contact by email. Blank = Not opted in to emails. Don’t contact by email in restricted countries.</inlineHelpText>
        <label>Unsubscribed from email</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Email_Undeliverable__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Required by marketing to check validity of email address - visible only on global page</description>
        <label>Email Undeliverable</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Inactive_in_Eloqua__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Inactive in Eloqua</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SFDC2SUN_TransferStatus__c</fullName>
        <description>It indicates the Contact status whether it has been transferred to Sun or not.</description>
        <inlineHelpText>The Status of Contact’s Transfer in Sun</inlineHelpText>
        <label>SFDC2SUN: Transfer Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Transferred</fullName>
                </value>
                <value>
                    <fullName>Transferred</fullName>
                </value>
                <value>
                    <fullName>Ready for Transfer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SFDC2SUN_TransferredBy__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field indicates the salesforce.com user who transferred the Contact in Sun Systems</description>
        <inlineHelpText>Contact transferred by the user.</inlineHelpText>
        <label>SFDC2SUN: Transferred By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Same_As_The_Account_Billing_Address__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If this option is selected, then the Contact Mailing Address is copied from the Account Billing Address.</description>
        <inlineHelpText>Check this box to set the Contact Address to the same as the Account Billing Address. This address will not be populated from the Account until you hit Save. You must ensure this box is not ticked if you want to enter a different address for the Contact.</inlineHelpText>
        <label>Same As The Account Billing Address</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

force-app/main/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Constant_Soft_Bounce_Contact__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Constant Soft Bounce Contact</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Constant_Soft_Bounce_Domain__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Constant Soft Bounce Domain</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Do_Not_Contact__c</fullName>
        <defaultValue>false</defaultValue>
        <description>to replace Do Not Call</description>
        <label>Do Not Contact</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Double_Opted_In__c</fullName>
        <label>Double Opted In</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Email_Group_Subscription__c</fullName>
        <label>Email Group Subscription</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Newsletters</fullName>
                </value>
                <value>
                    <fullName>Service and Event</fullName>
                </value>
                <value>
                    <fullName>Event and Training</fullName>
                </value>
                <value>
                    <fullName>Products and Solutions</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Email_Opted_In__c</fullName>
        <inlineHelpText>Read Only from Eloqua</inlineHelpText>
        <label>Unsubscribed from email</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Email_Undeliverable__c</fullName>
        <defaultValue>false</defaultValue>
        <description>field to show only on global pages in order that a report can be run to check for mail outs</description>
        <label>Email Undeliverable</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Inactive_in_Eloqua__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Inactive in Eloqua</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

force-app/main/objects/Trigger_Activation__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This List is used to activate/deactivate trigger while deployment.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Object_Name__c</fullName>
        <label>Object Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Trigger Activation</label>
</CustomObject>

classes/ContacttriggerManager_tester.cls
@isTest //(SeeAllData=true)
public class ContacttriggerManager_tester {
    
    /* public static testMethod void executeTestmethod() 
{
Trigger_Activation__c setting = new Trigger_Activation__c();
setting.Name = 'Account_Trigger';
setting.Active__c = true;
setting.Object_Name__c = 'Account';
insert setting;
Account account=CreateTestData.getAccount();

Trigger_Activation__c tActive = new Trigger_Activation__c();
tActive.Name = 'Contact_Trigger';
tActive.Active__c = true;
tActive.Object_Name__c = 'Contact';
insert tActive;

Contact contact = CreateTestData.getContact(account.Id);

//Contact contact = [Select id,SFDC2SUN_TransferStatus__c, SFDC2SUN_Log__c,Same_As_The_Account_Billing_Address__c FROM Contact where Same_As_The_Account_Billing_Address__c=true limit 1];
contact.SFDC2SUN_TransferStatus__c = 'Not Transferred';
contact.Same_As_The_Account_Billing_Address__c = true;
contact.SFDC2SUN_TransferredOn__c = Datetime.Now();
contact.SFDC2SUN_SyncedOn__c = Datetime.Now();
contact.SFDC2SUN_TransferredBy__c = UserInfo.getUserId();
contact.SFDC2SUN_SFDCVersion__c = 1;
contact.SFDC2SUN_SunVersion__c= 1;
contact.SFDC2SUN_Log__c += Datetime.Now() +': Setting test data.';
update contact;
PageReference pg = Page.SFDC2SUN_ContactTransfer;
pg.getParameters().put('id',contact.id);
Test.setCurrentPage(pg);
ApexPages.StandardController sc = new ApexPages.StandardController(contact);
SFDC2SUN_ContactTransferService.isApexTest = true;
SFDC2SUN_ContactTransferController tranContactToSun = new SFDC2SUN_ContactTransferController(sc); 
//tranContactToSun.includeAccount = true;
tranContactToSun.getContact();
tranContactToSun.showHideHistory();
tranContactToSun.showHideHistory();
tranContactToSun.startContactTransfer();
tranContactToSun.completeContactTransfer();

SFDC2SUN_ContactTransferController.transferContact(contact.id,true);
tranContactToSun.completeContactTransfer();
tranContactToSun.startContactSync();
tranContactToSun.completeContactSync();
tranContactToSun.errorMessage = '';
tranContactToSun.completeContactTransfer();
tranContactToSun.completeContactSync();
//tranContactToSun.transferContactToSun();
}
public static testMethod void tstTransferContactToSun1()
{   
Trigger_Activation__c setting = new Trigger_Activation__c();
setting.Name = 'Account_Trigger';
setting.Active__c = true;
setting.Object_Name__c = 'Account';
insert setting;

Account account=CreateTestData.getAccount();
// Contact contact = [Select id,SFDC2SUN_TransferStatus__c,SFDC2SUN_SfdcVersion__c, SFDC2SUN_Log__c,Same_As_The_Account_Billing_Address__c FROM Contact where Same_As_The_Account_Billing_Address__c=false limit 1];
Trigger_Activation__c tActive = new Trigger_Activation__c();
tActive.Name = 'Contact_Trigger';
tActive.Active__c = true;
tActive.Object_Name__c = 'Contact';
insert tActive;

Contact contact = new Contact(AccountId=account.Id,LastName='test12345',email='test12345@test.com',phone='2345345345',
Same_As_The_Account_Billing_Address__c=true,SFDC2SUN_TransferStatus__c='Not Transferred');

insert contact;
contact.SFDC2SUN_TransferStatus__c = 'Transferring';
contact.SFDC2SUN_SfdcVersion__c = 1;
contact.FirstName='test2';
contact.Same_As_The_Account_Billing_Address__c = true;
update contact;




PageReference pg = Page.SFDC2SUN_ContactTransfer;
pg.getParameters().put('id',contact.id);
Test.setCurrentPage(pg);
ApexPages.StandardController sc = new ApexPages.StandardController(contact);

SFDC2SUN_ContactTransferController tranContactToSun1 = new SFDC2SUN_ContactTransferController(sc); 
tranContactToSun1.showHideHistory();
contact.SFDC2SUN_TransferStatus__c = 'Out of Sync';
contact.SFDC2SUN_SyncStatus__c  = 'Out of Sync';
update contact;
SFDC2SUN_ContactTransferController tranContactToSun2 = new SFDC2SUN_ContactTransferController(sc); 
tranContactToSun2.showHideHistory();


SFDC2SUN_ContactTransferService contactTransferService = new SFDC2SUN_ContactTransferService();
SFDC2SUN_ContactTransferService.ContactTransferServiceSoap contactTransferServiceSoap = new SFDC2SUN_ContactTransferService.ContactTransferServiceSoap();
contactTransferServiceSoap.timeout_x = 60000;
SFDC2SUN_ContactTransferService.isApexTest = true;
contactTransferServiceSoap.transferContact(contact.id,true);
} 
*/
    @testSetup
    static void setup() {
        Trigger_Activation__c setting = new Trigger_Activation__c();
        setting.Name = 'Account_Trigger';
        setting.Active__c = true;
        setting.Object_Name__c = 'Account';
        insert setting;
        
        
        Trigger_Activation__c tActive = new Trigger_Activation__c();
        tActive.Name = 'Contact_Trigger'; 
        tActive.Active__c = true; 
        tActive.Object_Name__c = 'Contact'; 
        insert tActive;
        
        Trigger_Activation__c LActive = new Trigger_Activation__c();
        LActive.Name = 'LeadTrigger';
        LActive.Active__c = true;
        LActive.Object_Name__c = 'Lead';
        insert LActive; 
        
        
        
    }
    
    
    public static testMethod void tstupdateRegistrationNumber()
    {   
        
        
        Account account=CreateTestData.getAccount();
        Contact contact = CreateTestData.getContact(account.Id);
        Contact conObj = contact.clone(false, true);
        insert conObj;
    }
    
    public static testMethod void updateContact()
    {   
        Trigger_Activation__c setting = new Trigger_Activation__c();
        setting.Name = 'Account_Trigger';
        setting.Active__c = true;
        setting.Object_Name__c = 'Account';
        insert setting;
        Account account=CreateTestData.getAccount();
        
        Trigger_Activation__c tActive = new Trigger_Activation__c();
        tActive.Name = 'Contact_Trigger';
        tActive.Active__c = true;
        tActive.Object_Name__c = 'Contact';
        insert tActive;
        
        Contact contact = CreateTestData.getContact(account.Id);
        Contact conObj = contact.clone(false, true);
        conObj.LastName = 'Testing contact 01';
        conObj.Contact_Status__c = 'Active';
        conObj.Email = 'testing@test.com';
        insert conObj;
        
        Test.startTest();
        conObj.Contact_Status__c = 'Left Institution';
        UPDATE conObj;
        Test.stopTest();
    }
    
    
    @isTest
    static void testComputeEmailSubscriptionValues_Update() {
        // *** ADDED FOR COVERAGE ***
        
        Contact con = new Contact(
            LastName = 'EmailSubUpdate',
            Email_Group_Subscription__c = 'Newsletters'
        );
        insert con;
        
        Contact oldCon = con.clone(false, true);
        oldCon.Email_Group_Subscription__c = 'Newsletters';
        
        con.Email_Group_Subscription__c = 'Newsletters';
        
        Map<Id, Contact> oldMap = new Map<Id, Contact>{
            con.Id => oldCon
                };
                    
                    Test.startTest();
        ContactTriggerManager.computeEmailSubscriptionValues(
            new List<Contact>{ con },
            oldMap
        );
        Test.stopTest();
        
        
    }
    
    
    @isTest
    static void testComputeEmailSubscriptionValues_Insert() {
        // *** ADDED FOR COVERAGE ***
        
        Contact con = new Contact(
            LastName = 'EmailSub',
            Email_Group_Subscription__c = 'Newsletters'
        );
        insert con;
        
        Test.startTest();
        ContactTriggerManager.computeEmailSubscriptionValues(
            new List<Contact>{ con },
            null
        );
        Test.stopTest();
        
        
    }
    
    
    @isTest
    static void testSyncLeadStatusWithContact_RetiredToActive() {
        
        // Lead initially Retired
        Lead lead = new Lead(
            LastName = 'LeadRetired',
            Company = 'TestCo',
            Email = 'ret@test.com',
            Status = 'Retired'
        );
        insert lead;
        
        // Contact now Active
        Contact con = new Contact(
            LastName = 'ContactRet',
            Email = 'ret@test.com',
            Contact_Status__c = 'Active'
        );
        insert con;
        
        // OLD contact was Retired
        Contact oldCon = new Contact(
            Id = con.Id,
            Contact_Status__c = 'Retired'
        );
        
        Map<Id, Contact> oldMap = new Map<Id, Contact>{
            con.Id => oldCon
                };
                    
                    Test.startTest();
        ContactTriggerManager.syncLeadStatusWithContact(
            new List<Contact>{ con },
            oldMap
        );
        Test.stopTest();
        
        Lead updatedLead = [
            SELECT Status FROM Lead WHERE Id = :lead.Id
        ];
        
        
    }
    
    
    @isTest
    static void testSyncLeadStatusWithContact_MultipleStatusChanges() {
        
        // Leads
        Lead lead1 = new Lead(
            LastName = 'Lead1',
            Company = 'TestCo',
            Email = 'li@test.com',
            Status = 'Open'
        );
        Lead lead2 = new Lead(
            LastName = 'Lead2',
            Company = 'TestCo',
            Email = 'dec@test.com',
            Status = 'Open'
        );
        Lead lead3 = new Lead(
            LastName = 'Lead3',
            Company = 'TestCo',
            Email = 'aie@test.com',
            Status = 'Open'
        );
        insert new List<Lead>{ lead1, lead2, lead3 };
            
            // Contacts (NEW VALUES)
            Contact c1 = new Contact(
                LastName = 'C1',
                Email = 'li@test.com',
                Contact_Status__c = 'Left Institution'
            );
        Contact c2 = new Contact(
            LastName = 'C2',
            Email = 'dec@test.com',
            Contact_Status__c = 'Deceased'
        );
        Contact c3 = new Contact(
            LastName = 'C3',
            Email = 'aie@test.com',
            Contact_Status__c = 'Active-Invalid Email'
        );
        insert new List<Contact>{ c1, c2, c3 };
            
            // OLD CONTACT MAP
            Map<Id, Contact> oldMap = new Map<Id, Contact>{
                c1.Id => new Contact(Id=c1.Id, Contact_Status__c='Active'),
                    c2.Id => new Contact(Id=c2.Id, Contact_Status__c='Active'),
                    c3.Id => new Contact(Id=c3.Id, Contact_Status__c='Active')
                    };
                        
                        Test.startTest();
        ContactTriggerManager.syncLeadStatusWithContact(
            new List<Contact>{ c1, c2, c3 },
            oldMap
        );
        Test.stopTest();
        
        
        Map<String, Lead> updatedLeads = new Map<String, Lead>(
            [SELECT Email, Status FROM Lead WHERE Email IN ('li@test.com','dec@test.com','aie@test.com')]
        );
        
        
    }
    
    
    
    
    
    
    @isTest
    static void testSyncContactsFromEloqua() {
        
        
        Contact existingContact = new Contact(
            LastName = 'Existing',
            Email = 'eloqua@test.com',
            Email_Opt_In__c = false,
            Double_Opted_In__c = 'Yes',
            Inactive_in_Eloqua__c = false,
            Email_Undeliverable__c = false,
            Do_Not_Contact__c = false,
            Constant_Soft_Bounce_Domain__c = false,
            Constant_Soft_Bounce_Contact__c = false,
            Email_Group_Subscription__c = 'Newsletters'
        );
        insert existingContact;
        
        Contact oldContact = existingContact.clone(false, true);
        
        
        existingContact.Email_Opt_In__c = true;
        existingContact.Double_Opted_In__c = 'Yes';
        existingContact.Inactive_in_Eloqua__c = true;
        existingContact.Email_Undeliverable__c = true;
        existingContact.Do_Not_Contact__c = true;
        existingContact.Constant_Soft_Bounce_Domain__c = true;
        existingContact.Constant_Soft_Bounce_Contact__c = true;
        existingContact.Email_Group_Subscription__c = 'Newsletter'; // same or changed
        
        Map<Id, Contact> oldMap = new Map<Id, Contact>{
            existingContact.Id => oldContact
                };
                    
                    
                    Test.startTest();
        ContactTriggerManager.syncContactsFromEloqua(
            new List<Contact>{ existingContact },
            oldMap
        );
        Test.stopTest();
        
        
        Contact updatedContact = [
            SELECT Email_Opted_In__c,
            Double_Opted_In__c,
            Inactive_in_Eloqua__c,
            Email_Undeliverable__c,
            Do_Not_Contact__c,
            Constant_Soft_Bounce_Domain__c,
            Constant_Soft_Bounce_Contact__c,
            Email_Group_Subscription__c
            FROM Contact
            WHERE Id = :existingContact.Id
        ];
        
        
        System.assertEquals('Yes', updatedContact.Double_Opted_In__c);
        System.assertEquals(false, updatedContact.Inactive_in_Eloqua__c);
        System.assertEquals(false, updatedContact.Email_Undeliverable__c);
        System.assertEquals(false, updatedContact.Do_Not_Contact__c);
        System.assertEquals(false, updatedContact.Constant_Soft_Bounce_Domain__c);
        System.assertEquals(false, updatedContact.Constant_Soft_Bounce_Contact__c);
        
    }
    
    
    
}