force-app/main/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>1. Not yet trading with SHL - (definition - the account is new and/or has no trading history with SHL to date)
2. Trading with SHL - (definition - the account has sales recorded with SHL in the last 2 years)
3. Ceased Trading with SHL - (definition - the account has not traded with SHL in the past 12 months but has previously.) 
4. Dead - (Gone out of Business) (definition - The Account for whatever reason is no longer a trading entity)
Previous Values
1. Active with SHL (definition - The account has a track record of sales and/or opportunities managed in the last 2 years)
2. Inactive with SHL (definition - The account is still a trading account but there has been no activity with SHL (sales or opportunities managed) in the last 2 years)</description>
        <inlineHelpText>Status indicates if Account is approved or not. If you believe an unapproved Account should be Approved, Submit for Approval.</inlineHelpText>
        <label>Account Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Unapproved</fullName>
                    <default>true</default>
                    <label>Unapproved</label>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Unapproved - Out of Business</fullName>
                </value>
                <value>
                    <fullName>Unapproved - Trade Not Allowed</fullName>
                </value>
                <value>
                    <fullName>Unapproved - Duplicate</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

objects/Project_Invoice__c.object
<CustomObject>
    <description>Represents the invoice generated for the Time &amp; Expenses of a Project.</description>
    <fields>
        <fullName>Account_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Invoice_Requests1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Specify the Account to which this invoice belongs. By default, it is same as the Project.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Invoice Requests</relationshipLabel>
        <relationshipName>R00N20000001RCWmEAO</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Approved_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Represents the user who approved this invoice</description>
        <label>Approved By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <inlineHelpText>Select the End Date upto which the amount to be billed is calculated</inlineHelpText>
        <label>Invoice End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <description>Project to which this invoice belongs</description>
        <label>Project</label>
        <referenceTo>ProjectObject__c</referenceTo>
        <relationshipLabel>Invoice Requests</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <inlineHelpText>Select the start date from which the amount to be invoiced is calculated</inlineHelpText>
        <label>Invoice Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Invoice Request Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>In Progress</fullName>
                    <default>true</default>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>Submitted for Processing</fullName>
                </value>
                <value>
                    <fullName>Processed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Submitted_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Represents the user who submitted this invoice</description>
        <label>Submitted By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Invoices1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sun_Invoice_No__c</fullName>
        <label>Sun Order No</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Invoice Request</label>
    <nameField>
        <displayFormat>Inv{000000}</displayFormat>
        <label>Invoice Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ProjectObject__c.object
<CustomObject>
    <description>Used for PSA work</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Type__c</fullName>
        <label>Project Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Consulting and outsourced assessments</fullName>
                </value>
                <value>
                    <fullName>Inco Training</fullName>
                </value>
                <value>
                    <fullName>Internal Organisation</fullName>
                </value>
                <value>
                    <fullName>Pre-sales</fullName>
                </value>
                <value>
                    <fullName>Public Training</fullName>
                </value>
                <value>
                    <fullName>Sales</fullName>
                </value>
                <value>
                    <fullName>Advisory Services</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project</label>
    <nameField>
        <displayFormat>P{000000}</displayFormat>
        <label>Project Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <recordTypes>
        <fullName>Project</fullName>
        <active>true</active>
        <label>Project</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/ProjectInvoiceTriggerManager.cls
/**************************************************************************************************************************************
CREATED BY :- PRIYANK ANAND	
CREATED DATE :- 23-08-2019
DESCRIPTION :- This class contains various validations and assignments on fields of Invoice Request object, this class is called in ProjectInvoice_Trigger.
***************************************************************************************************************************************/ 

Global class ProjectInvoiceTriggerManager {
    
    //This method is throwing error on below conditions
    //1) If status is Processed and user is trying to delete invoice request.
    //2) If PSA_Role is not equal to PSA Lead or Project mangaer and user try to delete record.
    public static void CheckInvoiceDeletion(List<Project_Invoice__c> ProjectInvoices){
        List<ProjectObject__c> projects = Project_Manager.getProjectsForInvoices(ProjectInvoices);
        Map<Id, Boolean> projectAccessMap = Project_Manager.userCanManageProjects(projects);
        for(Integer i=0;i<ProjectInvoices.size();i++)
        {
            if(ProjectInvoices[i].Status__c == 'Processed')
                ProjectInvoices[i].addError('This invoice request has processed status therefore you cannot delete this invoice.'); 
            else
            {
                Boolean userCanDeleteProjectInvoice = projectAccessMap.get(ProjectInvoices[i].Project__c); 
                if(!userCanDeleteProjectInvoice)
                    ProjectInvoices[i].addError('You are not authorised to delete this invoice. Please contact GSD if you believe this to be incorrect.');
            }
        }
    }
    
    //This method is updating Account_Owner__c and CurrencyIsoCode of InvoiceRequest object
    public static void UpdateAccountOwnerAndCurrencyIsoCode(List<Project_Invoice__c> ProjectInvoices){
        List<Id> ProjectIds = new List<Id>();
        Set<Id> accountIdsSet = new Set<Id>();
        for(Integer i=0;i<ProjectInvoices.size();i++)
        {
            ProjectIds.add(ProjectInvoices[i].Project__c);
            accountIdsSet.add(ProjectInvoices[i].Account__c);
        }
        Map<Id,Account> accountMap = new Map<Id,Account>([Select id,CurrencyIsoCode,OwnerId from Account where id in :accountIdsSet]);  
        Map<Id,ProjectObject__c> projectMap = new Map<Id,ProjectObject__c>([SELECT ID,Account__c,Account__r.OwnerId, CurrencyIsoCode, Project_Type__c from ProjectObject__c WHERE id IN:ProjectIds]);
        if(projectMap!=null)
        {
            for(Project_Invoice__c InvoiceRequest:ProjectInvoices)
            {
                if(InvoiceRequest.Account__c != null)
                    InvoiceRequest.Account_Owner__c = accountMap.get(InvoiceRequest.Account__c).OwnerId;
                InvoiceRequest.CurrencyIsoCode = projectMap.get(InvoiceRequest.Project__c).CurrencyIsoCode;
            }
        }
        
    }
    
    //This method is performing below tasks
    //1) If status is changed to 'Submitted For Processing' then set 'Submitted_By__c' to User id.
    //2) if status is 'Processed' and Sun_Invoice_No__c is null then throw error.
    //3) Populate Invoice with updated amounts.
    //4) Process IMLookup Values.
    //5) Update Account_Owner__c of Invoice request object.
    public static void BeforeUpdateTasks(List<Project_Invoice__c> NewProjectInvoices,List<Project_Invoice__c> OldProjectInvoices){
        Set<Id> accountIdsSet = new Set<Id>();
        for(Integer i=0;i<NewProjectInvoices.size();i++)
        {
            if(NewProjectInvoices[i].Account__c!=OldProjectInvoices[i].Account__c)
                accountIdsSet.add(NewProjectInvoices[i].Account__c);
            
            //Swati added below code on 10/16/2013 to update Submitted By field when status is Submitted for Processing
            if(NewProjectInvoices[i].Status__c != OldProjectInvoices[i].Status__c && NewProjectInvoices[i].Status__c == 'Submitted For Processing')
            {
                NewProjectInvoices[i].Submitted_By__c = userInfo.getUserId();
            }
            //Swati added below code on 10/16/2013 to update Submitted By field when status is Submitted for Processing
            
            if(NewProjectInvoices[i].Status__c == 'Processed')
            {
                if (NewProjectInvoices[i].Sun_Invoice_No__c ==null)
                    NewProjectInvoices[i].addError('Please enter SUN Order No to Process this Invoice Request');
                //Swati added below code on 10/16/2013 to update Approved By field when status is Processed         
                NewProjectInvoices[i].Approved_By__c = userInfo.getUserId();
                //Swati added below code on 10/16/2013 to update Approved By field when status is Processed
            }
            
            if ((NewProjectInvoices[i].Start_Date__c != OldProjectInvoices[i].Start_Date__c)  
             //  || (NewProjectInvoices[i].End_Date__c != OldProjectInvoices[i].End_Date__c) 
             || (NewProjectInvoices[i].CurrencyIsoCode != OldProjectInvoices[i].CurrencyIsoCode))
              ProjectInvoice_Manager.populateInvoiceWithUpdatedAmounts(NewProjectInvoices[i], true, true, true);
            
         ProjectInvoice_Manager.processIMLookupvalues(NewProjectInvoices[i]);
        }
        if(accountIdsSet.size()>0)
        {
            Map<Id,Account> accountMap = new Map<Id,Account>([Select id,CurrencyIsoCode,OwnerId from Account where id in :accountIdsSet]);  
            for(Integer i=0;i<trigger.new.size();i++)
            {
                if(NewProjectInvoices[i].Account__c!=OldProjectInvoices[i].Account__c)
                    NewProjectInvoices[i].Account_Owner__c = accountMap.get(NewProjectInvoices[i].Account__c).OwnerId;
            }
        }
        
    }
}