force-app/main/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Number__c</fullName>
        <description>For use with integration to SUN &amp; PSA</description>
        <displayFormat>D{0000000}</displayFormat>
        <externalId>true</externalId>
        <label>Account Number</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Buying_Centre_Id__c</fullName>
        <description>Fro regional grouping of the same accounts, this field will be populated by the BI team.</description>
        <label>Buying Centre Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Global_Billing_Country__c</fullName>
        <description>This is the new field created for making the country value set consistent over all modules in Salesforce.</description>
        <label>Billing Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Global_Country_Picklist</valueSetName>
        </valueSet>
    </fields>
</CustomObject>

force-app/main/objects/Account_Plan__c.object
<CustomObject>
    <description>Module to capture Key Account Plan details</description>
    <fields>
        <fullName>Account_Name__c</fullName>
        <description>This field is used to store the related account for Account Plan</description>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Plans</relationshipLabel>
        <relationshipName>Account_Plans</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Account_Plan_Status__c</fullName>
        <label>Account Plan Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>In Review</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Retired</fullName>
                </value>
                <value>
                    <fullName>Migrated to Regional - Retired</fullName>
                    <isActive>false</isActive>
                    <label>Migrated to Regional - Retired</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Account_Plan_Type__c</fullName>
        <description>Created in Account Plan Phase 4 to determine the type of Account Plan</description>
        <inlineHelpText>This field is used to determine the type of Account Plan</inlineHelpText>
        <label>Account Plan Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Current</fullName>
                    <default>true</default>
                    <label>Current</label>
                </value>
                <value>
                    <fullName>Regional</fullName>
                </value>
                <value>
                    <fullName>Global</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Buying_Centre_Id__c</fullName>
        <description>This is used to identify if an Account Plan is Regional Account Plan .</description>
        <inlineHelpText>This field shows the value of Buying Centre same as on Account if an Account Plan is regional</inlineHelpText>
        <label>Buying Centre Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Account Plan</label>
    <nameField>
        <displayFormat>ACP-{0000}</displayFormat>
        <label>Account Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Account_LBU__c</fullName>
        <formula>RIGHT(TEXT( Account.BU__c ), 3)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account LBU</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account_Number__c</fullName>
        <description>This field displays Account Number of Account linked to</description>
        <formula>Account.Account_Number__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Business_Type__c</fullName>
        <description>Choose the Opportunity Type that best describes the type of business pursued.  
Reboost should only be used with In-Advance clients. 
Cross-sell is simply New Business with a client that has a current commercial relationship.</description>
        <label>Opportunity Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Expansion</fullName>
                </value>
                <value>
                    <fullName>Renewal</fullName>
                </value>
                <value>
                    <fullName>Debooking</fullName>
                    <label>Debooking / Adjustment</label>
                </value>
                <value>
                    <fullName>Extension</fullName>
                </value>
                <value>
                    <fullName>In Arrears</fullName>
                </value>
                <value>
                    <fullName>In Advance</fullName>
                </value>
                <value>
                    <fullName>Managed Services</fullName>
                </value>
                <value>
                    <fullName>Professional Services: non-subscription</fullName>
                </value>
                <value>
                    <fullName>Top Up / Addition</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Client_Business_Function__c</fullName>
        <inlineHelpText>Select the client business function(s) where the talent level sits.</inlineHelpText>
        <label>Function</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Finance</fullName>
                </value>
                <value>
                    <fullName>HR</fullName>
                </value>
                <value>
                    <fullName>IT / Technology</fullName>
                </value>
                <value>
                    <fullName>Legal</fullName>
                </value>
                <value>
                    <fullName>Customer Service / Call Center</fullName>
                </value>
                <value>
                    <fullName>Sales</fullName>
                </value>
                <value>
                    <fullName>Marketing</fullName>
                </value>
                <value>
                    <fullName>Procurement &amp; Ops</fullName>
                </value>
                <value>
                    <fullName>R&amp;D</fullName>
                </value>
                <value>
                    <fullName>Corporate Office</fullName>
                </value>
                <value>
                    <fullName>Enterprise Wide</fullName>
                </value>
                <value>
                    <fullName>Manufacturing</fullName>
                </value>
                <value>
                    <fullName>Store Front</fullName>
                </value>
                <value>
                    <fullName>Logistics &amp; warehouse</fullName>
                </value>
                <value>
                    <fullName>Unknown</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Multi_YearDeal__c</fullName>
        <defaultValue>TEXT(1)</defaultValue>
        <description>Describes length of Contract signed</description>
        <label>Contract length (In Month)</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                    <default>true</default>
                    <label>0 - 12</label>
                </value>
                <value>
                    <fullName>2</fullName>
                    <label>13 - 24</label>
                </value>
                <value>
                    <fullName>3</fullName>
                    <label>25 - 36</label>
                </value>
                <value>
                    <fullName>4</fullName>
                    <label>37 - 48</label>
                </value>
                <value>
                    <fullName>5</fullName>
                    <label>49 - 60</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>OpportunityId__c</fullName>
        <displayFormat>Opp{00000}</displayFormat>
        <externalId>true</externalId>
        <label>Opportunity ID</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Opportunity_ID18__c</fullName>
        <formula>CASESAFEID(Id)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Opportunity ID18</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity_Nickname__c</fullName>
        <inlineHelpText>Free text field for user specific reporting</inlineHelpText>
        <label>Opportunity Nickname</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Renewal_Date__c</fullName>
        <inlineHelpText>This date is calculated from the Contract End Date + 1 day and signifies the true date that the next Renewal is due to start on.</inlineHelpText>
        <label>Renewal Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Sales_Price_in_USD__c</fullName>
        <description>Used in Account Plan to show USD vaue on contract details.</description>
        <formula>IF(
TEXT(CurrencyIsoCode) = &apos;USD&apos;, Amount,
Amount / CURRENCYRATE(TEXT(CurrencyIsoCode))*CURRENCYRATE(&apos;USD&apos;))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sales Price in USD</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
</CustomObject>

force-app/main/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Package__c</fullName>
        <label>Offering Details</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Proposition__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Graduate Essential</fullName>
                </value>
                <value>
                    <fullName>Graduate Advanced</fullName>
                </value>
                <value>
                    <fullName>Graduate Ultimate</fullName>
                </value>
                <value>
                    <fullName>Volume Essential</fullName>
                </value>
                <value>
                    <fullName>Volume Advanced</fullName>
                </value>
                <value>
                    <fullName>Apprentice Essential</fullName>
                </value>
                <value>
                    <fullName>Tech Essential</fullName>
                    <label>Technology Essential</label>
                </value>
                <value>
                    <fullName>Tech Advanced</fullName>
                    <label>Technology Advanced</label>
                </value>
                <value>
                    <fullName>Technology Ultimate</fullName>
                </value>
                <value>
                    <fullName>Managerial Essential</fullName>
                </value>
                <value>
                    <fullName>Managerial Advanced</fullName>
                </value>
                <value>
                    <fullName>Managerial Ultimate</fullName>
                </value>
                <value>
                    <fullName>Video Essential</fullName>
                </value>
                <value>
                    <fullName>Video Advanced</fullName>
                </value>
                <value>
                    <fullName>Video Ultimate</fullName>
                </value>
                <value>
                    <fullName>Professional Essential</fullName>
                </value>
                <value>
                    <fullName>Professional Advanced</fullName>
                </value>
                <value>
                    <fullName>Professional Ultimate</fullName>
                </value>
                <value>
                    <fullName>Core Essential</fullName>
                </value>
                <value>
                    <fullName>Core Advanced</fullName>
                </value>
                <value>
                    <fullName>Core Unit Essential</fullName>
                </value>
                <value>
                    <fullName>Review Essential</fullName>
                </value>
                <value>
                    <fullName>Review Advanced</fullName>
                </value>
                <value>
                    <fullName>Review Ultimate</fullName>
                </value>
                <value>
                    <fullName>Mobilize Essential</fullName>
                </value>
                <value>
                    <fullName>Mobilize Advanced</fullName>
                </value>
                <value>
                    <fullName>Mobilize Ultimate</fullName>
                </value>
                <value>
                    <fullName>Product</fullName>
                </value>
                <value>
                    <fullName>Sales Transformation Review Essential</fullName>
                </value>
                <value>
                    <fullName>Sales Transformation Review Advanced</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

globalValueSets/Global_Country_Picklist.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>AFGHANISTAN</fullName>
    </customValue>
    <customValue>
        <fullName>ALBANIA</fullName>
    </customValue>
    <customValue>
        <fullName>ALDERNEY</fullName>
    </customValue>
    <customValue>
        <fullName>ALGERIA</fullName>
    </customValue>
    <customValue>
        <fullName>AMERICAN SAMOA</fullName>
    </customValue>
    <customValue>
        <fullName>ANDORRA</fullName>
    </customValue>
    <customValue>
        <fullName>ANGOLA</fullName>
    </customValue>
    <customValue>
        <fullName>ANGUILLA</fullName>
    </customValue>
    <customValue>
        <fullName>ANTARCTICA</fullName>
    </customValue>
    <customValue>
        <fullName>ANTIGUA AND BARBUDA</fullName>
    </customValue>
    <customValue>
        <fullName>ARGENTINA</fullName>
    </customValue>
    <customValue>
        <fullName>ARMENIA</fullName>
    </customValue>
    <customValue>
        <fullName>ARUBA</fullName>
    </customValue>
    <customValue>
        <fullName>AUSTRALIA</fullName>
    </customValue>
    <customValue>
        <fullName>AUSTRIA</fullName>
    </customValue>
    <customValue>
        <fullName>AZERBAIJAN</fullName>
    </customValue>
    <customValue>
        <fullName>BAHAMAS</fullName>
    </customValue>
    <customValue>
        <fullName>BAHRAIN</fullName>
    </customValue>
    <customValue>
        <fullName>BANGLADESH</fullName>
    </customValue>
    <customValue>
        <fullName>BARBADOS</fullName>
    </customValue>
    <customValue>
        <fullName>BELARUS</fullName>
    </customValue>
    <customValue>
        <fullName>BELGIUM</fullName>
    </customValue>
    <customValue>
        <fullName>BELIZE</fullName>
    </customValue>
    <customValue>
        <fullName>BENIN</fullName>
    </customValue>
    <customValue>
        <fullName>BERMUDA</fullName>
    </customValue>
    <customValue>
        <fullName>BHUTAN</fullName>
    </customValue>
    <customValue>
        <fullName>BOLIVIA</fullName>
    </customValue>
    <customValue>
        <fullName>BOSNIA AND HERZEGOWINA</fullName>
    </customValue>
    <customValue>
        <fullName>BOTSWANA</fullName>
    </customValue>
    <customValue>
        <fullName>BOUVET ISLAND</fullName>
    </customValue>
    <description>used as a global picklist over all the modules in salesforce</description>
    <masterLabel>Global Country Picklist</masterLabel>
</GlobalValueSet>

classes/CurrentPipelineController.cls
public without sharing class CurrentPipelineController {
    
    @AuraEnabled(cacheable=true)
    public static CurrentOpportunityDetailsWrapper getOpenOpportunitiesDetails(Id accountPlanId,String businessType){
        
        CurrentOpportunityDetailsWrapper wrapperToReturn = new CurrentOpportunityDetailsWrapper();
        //List<String> businessTypeList;
        // if(businessType=='Renewal'){
        //     businessTypeList = new List<String>{'Renewal'};
        //         }else if(businessType=='New Business/Cross Sell'){
        //             businessTypeList= new List<String>{'New customer: subscription','New customer: non-subscription','Cross-sell: subscription','Existing customer: non-subscription','migration'};
        //                 }//else if(businessType=='Cross Sell'){
                        //     businessTypeList= new List<String>{'Cross-sell: subscription','Existing customer: non-subscription','migration'};
                        //         }
        Account_Plan__c accplan = [select id , Account_Name__c,Account_Plan_Status__c , Account_Name__r.CurrencyIsoCode,Account_Plan_Type__c,Buying_Centre_Id__c
                                   from Account_Plan__c where id=:accountPlanId];
        
        List<Opportunity> oppData = new List<Opportunity>();
        if(accplan.Account_Plan_Type__c=='Regional'){
            List<Account> accList = [SELECT Id FROM Account WHERE Buying_Centre_Id__c= :accplan.Buying_Centre_Id__c];
            List<Id> accIds = new List<Id>();
            for (Account acc : accList) {
                accIds.add(acc.Id);
            }
            if(businessType=='Renewal'){
                oppData = [SELECT Id,Account.CurrencyIsoCode,Account.Account_Number__c,OpportunityId__c,Opportunity_Nickname__c,Sales_Price_in_USD__c,Opportunity_ID18__c,NextStep,StageName,Multi_YearDeal__c,CloseDate,Amount,Account_LBU__c,Account.Global_Billing_Country__c,Client_Business_Function__c,(Select Id,Package__c from OpportunityLineItems),Renewal_Date__c From Opportunity where AccountId IN :accIds AND StageName NOT IN ('Closed/Won','Closed Lost') AND Business_Type__c IN ('Renewal') ORDER BY CloseDate];
            }else{
                oppData = [SELECT Id,Account.CurrencyIsoCode,Account.Account_Number__c,OpportunityId__c,Opportunity_Nickname__c,Sales_Price_in_USD__c,Opportunity_ID18__c,NextStep,StageName,Multi_YearDeal__c,CloseDate,Amount,Account_LBU__c,Account.Global_Billing_Country__c,Client_Business_Function__c,(Select Id,Package__c from OpportunityLineItems),Renewal_Date__c From Opportunity where AccountId IN :accIds AND StageName NOT IN ('Closed/Won','Closed Lost') AND Business_Type__c NOT IN ('Renewal') ORDER BY CloseDate];
            }
            
        }else if(accplan.Account_Plan_Type__c=='Current'){
            if(businessType=='Renewal'){
                oppData = [SELECT Id,Account.CurrencyIsoCode,Account.Account_Number__c,OpportunityId__c,Opportunity_Nickname__c,Sales_Price_in_USD__c,Opportunity_ID18__c,NextStep,StageName,Multi_YearDeal__c,CloseDate,Amount,Account_LBU__c,Account.Global_Billing_Country__c,Client_Business_Function__c,(Select Id,Package__c from OpportunityLineItems),Renewal_Date__c From Opportunity where AccountId=:accplan.Account_Name__c AND StageName NOT IN ('Closed/Won','Closed Lost') AND Business_Type__c IN ('Renewal') ORDER BY CloseDate];
            }else{
                oppData = [SELECT Id,Account.CurrencyIsoCode,Account.Account_Number__c,OpportunityId__c,Opportunity_Nickname__c,Sales_Price_in_USD__c,Opportunity_ID18__c,NextStep,StageName,Multi_YearDeal__c,CloseDate,Amount,Account_LBU__c,Account.Global_Billing_Country__c,Client_Business_Function__c,(Select Id,Package__c from OpportunityLineItems),Renewal_Date__c From Opportunity where AccountId=:accplan.Account_Name__c AND StageName NOT IN ('Closed/Won','Closed Lost') AND Business_Type__c NOT IN ('Renewal') ORDER BY CloseDate];
            }
            
        }else if(accplan.Account_Plan_Type__c=='Global'){
            Set<Id> allAccountIds = new Set<Id>{accplan.Account_Name__c};
                Set<Id> parentIds = new Set<Id>{accplan.Account_Name__c};
                    List<Account> childAccounts = new List<Account>();
            do {
                childAccounts = [SELECT Id FROM Account WHERE ParentId IN :parentIds AND RecordType.name != 'Competitor Account'];
                parentIds.clear();
                for (Account child : childAccounts){
                    parentIds.add(child.Id);
                    allAccountIds.add(child.Id);
                }
            } while (childAccounts.size() > 0);
            if(businessType=='Renewal'){
                oppData = [SELECT Id,Account.CurrencyIsoCode,Account.Account_Number__c,OpportunityId__c,Opportunity_Nickname__c,Sales_Price_in_USD__c,Opportunity_ID18__c,NextStep,StageName,Multi_YearDeal__c,CloseDate,Amount,Account_LBU__c,Account.Global_Billing_Country__c,Client_Business_Function__c,(Select Id,Package__c from OpportunityLineItems),Renewal_Date__c From Opportunity where AccountId IN :allAccountIds AND StageName NOT IN ('Closed/Won','Closed Lost') AND Business_Type__c IN ('Renewal') ORDER BY CloseDate];
            }else{
                oppData = [SELECT Id,Account.CurrencyIsoCode,Account.Account_Number__c,OpportunityId__c,Opportunity_Nickname__c,Sales_Price_in_USD__c,Opportunity_ID18__c,NextStep,StageName,Multi_YearDeal__c,CloseDate,Amount,Account_LBU__c,Account.Global_Billing_Country__c,Client_Business_Function__c,(Select Id,Package__c from OpportunityLineItems),Renewal_Date__c From Opportunity where AccountId IN :allAccountIds AND StageName NOT IN ('Closed/Won','Closed Lost') AND Business_Type__c NOT IN ('Renewal') ORDER BY CloseDate];
            }            
        }
        List<CurrentOpportunityWrapper> currentPipeline = new List<CurrentOpportunityWrapper>(); 
        Integer serialNumber = 1;
        Decimal totalSalesValue = 0;
        Decimal totalSalesValueInUSD = 0;
        String currencyFromAccount = accplan.Account_Name__r.CurrencyIsoCode;
        String sfdcBaseURL = URL.getSalesforceBaseUrl().toExternalForm();
        for (Opportunity opp : oppData) {
            CurrentOpportunityWrapper wrap = new CurrentOpportunityWrapper();
            wrap.opportunityUrl = sfdcBaseURL+'/'+opp.Id;
            wrap.serialNumber = serialNumber;
            wrap.opportunityName = opp.OpportunityId__c;
            wrap.oppId = opp.Opportunity_ID18__c;
            wrap.amount = opp.Amount;
            wrap.amountWithCurrency = opp.Amount!=null?opp.Account.CurrencyIsoCode + ' '+opp.Amount:opp.Account.CurrencyIsoCode + ' ' + 0;
            wrap.nextStep = opp.NextStep;
            wrap.stageName = opp.StageName;
            wrap.closeDate = opp.CloseDate;
            wrap.contractLength = opp.Multi_YearDeal__c;
            wrap.accountBU = opp.Account_LBU__c;
            if(opp.OpportunityLineItems.size()>0){
                Set<String> solution = new Set<String>();
                for (OpportunityLineItem lineItem : opp.OpportunityLineItems) {
                    solution.add(lineItem.Package__c);
                }
                wrap.solution = String.join(new List<String>(solution),',');
            }
            wrap.renewalDate = opp.Renewal_Date__c;
            wrap.opportunityNickname = opp.Opportunity_Nickname__c;
            wrap.dNumber = opp.Account.Account_Number__c;
            currentPipeline.add(wrap);
            serialNumber++;
            totalSalesValue += (opp.Amount!=null)?opp.Amount:0;
            totalSalesValueInUSD += opp.Sales_Price_in_USD__c;
        }
        
        wrapperToReturn.currentPipeline = currentPipeline;
        if(currencyFromAccount=='USD' || accplan.Account_Plan_Type__c=='Global' || accplan.Account_Plan_Type__c=='Regional'){
            wrapperToReturn.totalSalesValue = 'USD '+totalSalesValueInUSD;
        }else{
            wrapperToReturn.totalSalesValue = currencyFromAccount +' '+ totalSalesValue+' ( USD '+totalSalesValueInUSD +' )';
        }
        return wrapperToReturn;
    }
    
    public class CurrentOpportunityDetailsWrapper{
        @AuraEnabled public String totalSalesValue;
        @AuraEnabled public List<CurrentOpportunityWrapper> currentPipeline;
    }
    
    public class CurrentOpportunityWrapper{
        
        @AuraEnabled public String opportunityName;
        @AuraEnabled public Decimal amount;
        @AuraEnabled public String amountWithCurrency;
        @AuraEnabled public Date closeDate;
        @AuraEnabled public String stageName;
        @AuraEnabled public String contractLength;
        @AuraEnabled public String solution;
        @AuraEnabled public String accountBU;
        @AuraEnabled public String nextStep;
        @AuraEnabled public String oppId;
        @AuraEnabled public Integer serialNumber;
        @AuraEnabled public String opportunityUrl;
        @AuraEnabled public Date renewalDate;
        @AuraEnabled public String opportunityNickname;
        @AuraEnabled public String dNumber;
    }
}