force-app/main/objects/Account.object
<CustomObject>
    <fields>
        <fullName>BU__c</fullName>
        <label>BU</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Master_BUs</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Billing_Address_Line_1__c</fullName>
        <inlineHelpText>If the address goes over more than one line then please use Address Line 2 and Address Line 3. This formatting will display on any Customer facing documents.</inlineHelpText>
        <label>Billing Address Line 1</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_City__c</fullName>
        <label>Billing City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_Country__c</fullName>
        <label>Billing Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AFGHANISTAN</fullName>
                </value>
                <value>
                    <fullName>ALBANIA</fullName>
                </value>
                <value>
                    <fullName>ALDERNEY</fullName>
                </value>
                <value>
                    <fullName>ALGERIA</fullName>
                </value>
                <value>
                    <fullName>AMERICAN SAMOA</fullName>
                </value>
                <value>
                    <fullName>ANDORRA</fullName>
                </value>
                <value>
                    <fullName>ANGOLA</fullName>
                </value>
                <value>
                    <fullName>ANGUILLA</fullName>
                </value>
                <value>
                    <fullName>ANTARCTICA</fullName>
                </value>
                <value>
                    <fullName>ANTIGUA AND BARBUDA</fullName>
                </value>
                <value>
                    <fullName>ARGENTINA</fullName>
                </value>
                <value>
                    <fullName>ARMENIA</fullName>
                </value>
                <value>
                    <fullName>ARUBA</fullName>
                </value>
                <value>
                    <fullName>AUSTRALIA</fullName>
                </value>
                <value>
                    <fullName>AUSTRIA</fullName>
                </value>
                <value>
                    <fullName>AZERBAIJAN</fullName>
                </value>
                <value>
                    <fullName>BAHAMAS</fullName>
                </value>
                <value>
                    <fullName>BAHRAIN</fullName>
                </value>
                <value>
                    <fullName>BANGLADESH</fullName>
                </value>
                <value>
                    <fullName>BARBADOS</fullName>
                </value>
                <value>
                    <fullName>BELARUS</fullName>
                </value>
                <value>
                    <fullName>BELGIUM</fullName>
                </value>
                <value>
                    <fullName>BELIZE</fullName>
                </value>
                <value>
                    <fullName>BENIN</fullName>
                </value>
                <value>
                    <fullName>BERMUDA</fullName>
                </value>
                <value>
                    <fullName>BHUTAN</fullName>
                </value>
                <value>
                    <fullName>BOLIVIA</fullName>
                </value>
                <value>
                    <fullName>BOSNIA AND HERZEGOWINA</fullName>
                </value>
                <value>
                    <fullName>BOTSWANA</fullName>
                </value>
                <value>
                    <fullName>BOUVET ISLAND</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Billing_State__c</fullName>
        <inlineHelpText>If State is required, please enter as two alphanumeric characters, e.g. GA instead of Georgia</inlineHelpText>
        <label>Billing State/County</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_ZIP_Postal_Code__c</fullName>
        <label>Billing ZIP/Postal Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>1. Not yet trading with SHL - (definition - the account is new and/or has no trading history with SHL to date)
2. Trading with SHL - (definition - the account has sales recorded with SHL in the last 2 years)
3. Ceased Trading with SHL - (definition - the account has not traded with SHL in the past 12 months but has previously.) 
4. Dead - (Gone out of Business) (definition - The Account for whatever reason is no longer a trading entity)
Previous Values
1. Active with SHL (definition - The account has a track record of sales and/or opportunities managed in the last 2 years)
2. Inactive with SHL (definition - The account is still a trading account but there has been no activity with SHL (sales or opportunities managed) in the last 2 years)</description>
        <inlineHelpText>Status indicates if Account is approved or not. If you believe an unapproved Account should be Approved, Submit for Approval.</inlineHelpText>
        <label>Account Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Unapproved</fullName>
                    <default>true</default>
                    <label>Unapproved</label>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Unapproved - Out of Business</fullName>
                </value>
                <value>
                    <fullName>Unapproved - Trade Not Allowed</fullName>
                </value>
                <value>
                    <fullName>Unapproved - Duplicate</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>BU__c</fullName>
        <formula>text(Account.BU__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>BU</label>
        <type>Text</type>
    </fields>
</CustomObject>

objects/Hierarchy_Information__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Hierarchy Information</relationshipLabel>
        <relationshipName>Hierarchy_Information</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Hierarchy Information</label>
    <nameField>
        <displayFormat>HR-{0000}</displayFormat>
        <label>Hierarchy Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Hierarchy Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Annual_Contract_Value__c</fullName>
        <label>Annual Contract Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Billing_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Billing Contact</label>
        <lookupFilter>
            <active>false</active>
            <errorMessage>Billing Contact should be part of the account linked to the opportunity.</errorMessage>
            <filterItems>
                <field>$Source.AccountId</field>
                <operation>equals</operation>
                <valueField>Contact.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Business_Type__c</fullName>
        <description>Choose the Opportunity Type that best describes the type of business pursued.  
Reboost should only be used with In-Advance clients. 
Cross-sell is simply New Business with a client that has a current commercial relationship.</description>
        <label>Opportunity Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Expansion</fullName>
                </value>
                <value>
                    <fullName>Renewal</fullName>
                </value>
                <value>
                    <fullName>Debooking</fullName>
                    <label>Debooking / Adjustment</label>
                </value>
                <value>
                    <fullName>Extension</fullName>
                </value>
                <value>
                    <fullName>In Arrears</fullName>
                </value>
                <value>
                    <fullName>In Advance</fullName>
                </value>
                <value>
                    <fullName>Managed Services</fullName>
                </value>
                <value>
                    <fullName>Professional Services: non-subscription</fullName>
                </value>
                <value>
                    <fullName>Top Up / Addition</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Forecast_Category__c</fullName>
        <inlineHelpText>Please select “Commit” if you want this opportunity to be counted in your Forecast number. Please select Pipeline or Renewal at Risk if you do not want it to be included.</inlineHelpText>
        <label>Forecast Category</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Business_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Commit</fullName>
                </value>
                <value>
                    <fullName>Pipeline</fullName>
                    <default>true</default>
                    <label>Pipeline</label>
                </value>
                <value>
                    <fullName>Renewal at Risk</fullName>
                </value>
                <value>
                    <fullName>Forecast</fullName>
                    <isActive>false</isActive>
                    <label>Forecast</label>
                </value>
                <value>
                    <fullName>Parked</fullName>
                    <isActive>false</isActive>
                    <label>Parked</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>GCSC__c</fullName>
        <label>GCSC Method</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Phone</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Multi_YearDeal__c</fullName>
        <defaultValue>TEXT(1)</defaultValue>
        <description>Describes length of Contract signed</description>
        <label>Contract length (In Month)</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                    <default>true</default>
                    <label>0 - 12</label>
                </value>
                <value>
                    <fullName>2</fullName>
                    <label>13 - 24</label>
                </value>
                <value>
                    <fullName>3</fullName>
                    <label>25 - 36</label>
                </value>
                <value>
                    <fullName>4</fullName>
                    <label>37 - 48</label>
                </value>
                <value>
                    <fullName>5</fullName>
                    <label>49 - 60</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>NVM_Credit_Card_ID__c</fullName>
        <label>NVM Payment ID</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OpportunityAmountMappedWithLead__c</fullName>
        <description>As there is another standard field Amount exist on Opp but we can not map it with a custom field Opportunity Amount on lead during lead convert. So we are creating this custom filed only to map it with its correspondent on lead. This field will not be added on page layout.</description>
        <label>OpportunityAmountMappedWithLead</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>OpportunityTypeMappedWithLead__c</fullName>
        <description>As there is another standard field Type exist on Opp but we can not map it with a custom field Opportunity Type on lead during lead convert. So we are creating this custom filed only to map it with its correspondent on lead. This field will not be added on page layout.</description>
        <label>OpportunityTypeMappedWithLead</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Existing Business</fullName>
                </value>
                <value>
                    <fullName>New Business</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Original_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Original Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Variation / Renewal Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Primary_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities (Primary Contact)</relationshipLabel>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Unconfirmed_Sun_Order_Number__c</fullName>
        <label>Unconfirmed Sun Order Number</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Variation_Opportunity__c</fullName>
        <label>Variation Opportunity</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                    <default>true</default>
                    <label>No</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

classes/OpportunityContactHierarchy_Test.cls
@isTest
class OpportunityContactHierarchy_Test {
    
    @isTest(seeAlldata=true)
    static void testCreateHierarchy() {
        Account account = new Account(name = 'Test Contact Hierarchy Class',
                                      industry = 'Legal', Status__c = 'Approved',
                                      Billing_Address_Line_1__c = 'test', Billing_City__c = 'Test City',
                                      Billing_Country__c = 'India', Billing_State__c = 'Test',
                                      Billing_ZIP_Postal_Code__c = '1100110', BU__c = 'Australia - AU1');
        insert account;
        
        List<Contact> testContacts = new List<Contact>();
        for(Integer i=0;i<4;i++) {
            testContacts.add(new Contact(LastName = 'TestCon'+i,Email = 'TestCon'+i+'@'+'TestCon'+i+'.com',AccountId=account.Id));
        }
        insert testContacts;
        
        Opportunity opp =
            new Opportunity(name = 'Test Opportunity', AccountID = account.id);
        opp.Billing_Contact__c = testContacts[0].id;
        opp.Closedate = system.today();
        opp.Primary_Contact__c = testContacts[0].id;
        opp.CurrencyIsoCode = 'AUD';
        opp.Unconfirmed_Sun_Order_Number__c = '1234';
        opp.NVM_Credit_Card_ID__c = '1234';
        opp.Amount = 1000;
        opp.Variation_Opportunity__c = 'No';
        opp.Original_Opportunity__c = null;
        opp.Annual_Contract_Value__c = 1000.00;
        opp.StageName = 'Closed Won';
        opp.GCSC__c = 'Phone';
        opp.OpportunityAmountMappedWithLead__c = 323.34; //**********
        opp.OpportunityTypeMappedWithLead__c = 'New Business'; //**********
        opp.Business_Type__c = 'Renewal';
        opp.Forecast_Category__c = 'Commit';
        opp.Multi_YearDeal__c = '1';
        opp.Opportunity_Deal_Year__c = 1;
        
        insert opp;
        
        
        String hierarchyInformationId = OpportunityContactHierarchy.createHierarchyOnOpportunity(opp.Id, 'Default Heirarchy');
        
        Hierarchy_Information__c hierarchyInformation = [SELECT Id FROM Hierarchy_Information__c WHERE Id =:hierarchyInformationId];
        
        OpportunityContactHierarchy.HierarchyDetails hierarchyDetails = OpportunityContactHierarchy.getHierarchyDetails(hierarchyInformationId);
        
        OpportunityContactHierarchy.getHierarchyInformationOfOpportunity(opp.Id);
        
        OpportunityContactHierarchy.HierarchyWrapper placeholder = new OpportunityContactHierarchy.HierarchyWrapper();
        placeholder.IsPlaceholder = true;
        placeholder.Name = 'Test';
        placeholder.Id = 'Placeholder1';
        placeholder.ReportsTo = 'rootlevel';
        placeholder.Children = new List<OpportunityContactHierarchy.HierarchyWrapper>();

        hierarchyDetails.HierarchyList.add(placeholder);
        
        Contact conToReplace = new Contact();
        conToReplace.LastName = 'Hierarchy'+System.Now();
        
        
        OpportunityContactHierarchy.updateHierarchyOnPlaceholderCreation(hierarchyDetails.HierarchyList, hierarchyInformationId);
        
        OpportunityContactHierarchy.updateHierarchyOnDelete(hierarchyDetails.HierarchyList, hierarchyInformationId, new List<Contact>(), testContacts[1].Id);
        
        OpportunityContactHierarchy.updateHierarchyOnReplace(hierarchyDetails.HierarchyList, hierarchyInformationId, testContacts[0].Id, conToReplace, new list<Contact>{testContacts[0]}, null, 'Influencer;Decision Maker');

        OpportunityContactHierarchy.updateHierarchyOnReparent(hierarchyDetails.HierarchyList, hierarchyInformationId, testContacts[0].Id, testContacts[1].Id, false, new list<Contact>{testContacts[0]});
        
        OpportunityContactHierarchy.deleteHierarchy(hierarchyInformationId);
        
        OpportunityContactHierarchy.ContactWrapper con = new OpportunityContactHierarchy.ContactWrapper(1,testContacts[0].Id , 'Mr', 'Test', 'Test', account.Id, testContacts[0].email, 'Test', 'Test', 'Test', 'Test', 'Test');
        OpportunityContactHierarchy.HierarchyWrapper hier = new OpportunityContactHierarchy.HierarchyWrapper('rootlevel', null, null, false, new List<OpportunityContactHierarchy.HierarchyWrapper>());
        //OpportunityContactHierarchy.updateHierarchyOnReparent(hierarchyDetails.HierarchyList, hierarchyInformationId, , , , );
        
    }
    
    @isTest(seeAlldata=true)
    static void testUpdateContactRole() {
        Account account = new Account(name = 'Test Contact Hierarchy Class',
                                      industry = 'Legal', Status__c = 'Approved',
                                      Billing_Address_Line_1__c = 'test', Billing_City__c = 'Test City',
                                      Billing_Country__c = 'India', Billing_State__c = 'Test',
                                      Billing_ZIP_Postal_Code__c = '1100110', BU__c = 'Australia - AU1');
        insert account;
        
        List<Contact> testContacts = new List<Contact>();
        for(Integer i=0;i<4;i++) {
            testContacts.add(new Contact(LastName = 'TestCon'+i,Email = 'TestCon'+i+'@'+'TestCon'+i+'.com',AccountId=account.Id));
        }
        insert testContacts;
        
        Opportunity opp =
            new Opportunity(name = 'Test Opportunity', AccountID = account.id);
        opp.Billing_Contact__c = testContacts[0].id;
        opp.Closedate = system.today();
        opp.Primary_Contact__c = testContacts[0].id;
        opp.CurrencyIsoCode = 'AUD';
        opp.Unconfirmed_Sun_Order_Number__c = '1234';
        opp.NVM_Credit_Card_ID__c = '1234';
        opp.Amount = 1000;
        opp.Variation_Opportunity__c = 'No';
        opp.Original_Opportunity__c = null;
        opp.Annual_Contract_Value__c = 1000.00;
        opp.StageName = 'Closed Won';
        opp.GCSC__c = 'Phone';
        opp.OpportunityAmountMappedWithLead__c = 323.34; //**********
        opp.OpportunityTypeMappedWithLead__c = 'New Business'; //**********
        opp.Business_Type__c = 'Renewal';
        opp.Forecast_Category__c = 'Commit';
        opp.Multi_YearDeal__c = '1';
        opp.Opportunity_Deal_Year__c = 1;
        
        insert opp;
            
        
        OpportunityContactRole newRole = new OpportunityContactRole(
            OpportunityId = opp.Id, 
            ContactId = testContacts[1].Id, 
            Role = 'Budget Holder'
        );
        insert newRole;
        
        String hierarchyInformationId = OpportunityContactHierarchy.createHierarchyOnOpportunity(opp.Id, 'Default Heirarchy');
        Hierarchy_Information__c hierarchyInformation = [SELECT Id, Opportunity__c FROM Hierarchy_Information__c WHERE Id =:hierarchyInformationId];
        OpportunityContactHierarchy.HierarchyDetails hierarchyDetails = OpportunityContactHierarchy.getHierarchyDetails(hierarchyInformationId);
        Test.startTest();
        OpportunityContactRole newRoleToCreate = new OpportunityContactRole(
            OpportunityId = opp.Id, 
            ContactId = testContacts[3].Id, 
            Role = 'Budget Holder'
        );
        OpportunityContactHierarchy.createContactRoleRecords(new list<OpportunityContactRole>{newRoleToCreate});
        list<OpportunityContactHierarchy.ContactWrapper> listOfcontactWrapper1 = new list<OpportunityContactHierarchy.ContactWrapper>();
        OpportunityContactHierarchy.ContactWrapper contactWrapper1= new OpportunityContactHierarchy.ContactWrapper();
        contactWrapper1.firstName = 'ceofirstname';
        contactWrapper1.lastName = 'ceolastname';
        contactWrapper1.email = 'ceofirstname@test.com';
        contactWrapper1.phone = '9876543211';
        contactWrapper1.role = 'Blocker';
        contactWrapper1.title = 'CEO';
        contactWrapper1.jobFunction = 'Talent Management';
        
        listOfcontactWrapper1.add(contactWrapper1);
        
        OpportunityContactHierarchy.ContactWrapper contactWrapper11= new OpportunityContactHierarchy.ContactWrapper();
        contactWrapper11.firstName = 'chrofirstname';
        contactWrapper11.lastName = 'chrolastname';
        contactWrapper11.email = 'chrofirstname@test.com';
        contactWrapper11.phone = '9876543211';
        contactWrapper11.role = 'Budget Holder;Influencer';
        contactWrapper11.title = 'CHRO';
        contactWrapper11.jobFunction = 'Talent Management';
        
        listOfcontactWrapper1.add(contactWrapper11);
        
        OpportunityContactHierarchy.createContactRecords(listOfcontactWrapper1, hierarchyInformation.Opportunity__c, hierarchyInformationId, 'rootlevel', hierarchyDetails.HierarchyList);
        
        list<OpportunityContactHierarchy.ContactWrapper> listOfcontactWrapper = new list<OpportunityContactHierarchy.ContactWrapper>();
        OpportunityContactHierarchy.ContactWrapper contactWrapper = new OpportunityContactHierarchy.ContactWrapper();
        contactWrapper.id = testContacts[2].Id;
        contactWrapper.role = 'Influencer;Budget Holder';
        listOfcontactWrapper.add(contactWrapper);
        
        OpportunityContactHierarchy.ContactWrapper contactWrapper2 = new OpportunityContactHierarchy.ContactWrapper();
        contactWrapper2.id = testContacts[3].Id;
        contactWrapper2.role = 'Blocker';
        
        listOfcontactWrapper.add(contactWrapper2);
        OpportunityContactHierarchy.updateHierarchyOnExistingContactSelection(listOfcontactWrapper, hierarchyInformation.Opportunity__c, hierarchyInformationId, 'rootlevel', hierarchyDetails.HierarchyList);
		OpportunityContactHierarchy.updateContactRole('Blocker', null, hierarchyDetails.HierarchyList, hierarchyInformationId, testContacts[0].Id);
        list<Opportunity> oppDetails = OpportunityContactHierarchy.getOpportunityDetails(opp.OpportunityId__c);
        OpportunityContactHierarchy.getActiveContacts(0, '', new list<String>{testContacts[0].Id}, account.Id,true);
        OpportunityContactHierarchy.getActiveContacts(0, 'ceo', new list<String>{testContacts[0].Id}, account.Id,true);
         Test.stopTest();
    }
    
    
}