force-app/main/objects/Account.object
<CustomObject>
    <fields>
        <fullName>BU__c</fullName>
        <label>BU</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Master_BUs</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Billing_Address_Line_1__c</fullName>
        <inlineHelpText>If the address goes over more than one line then please use Address Line 2 and Address Line 3. This formatting will display on any Customer facing documents.</inlineHelpText>
        <label>Billing Address Line 1</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_City__c</fullName>
        <label>Billing City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_Country__c</fullName>
        <label>Billing Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AFGHANISTAN</fullName>
                </value>
                <value>
                    <fullName>ALBANIA</fullName>
                </value>
                <value>
                    <fullName>ALDERNEY</fullName>
                </value>
                <value>
                    <fullName>ALGERIA</fullName>
                </value>
                <value>
                    <fullName>AMERICAN SAMOA</fullName>
                </value>
                <value>
                    <fullName>ANDORRA</fullName>
                </value>
                <value>
                    <fullName>ANGOLA</fullName>
                </value>
                <value>
                    <fullName>ANGUILLA</fullName>
                </value>
                <value>
                    <fullName>ANTARCTICA</fullName>
                </value>
                <value>
                    <fullName>ANTIGUA AND BARBUDA</fullName>
                </value>
                <value>
                    <fullName>ARGENTINA</fullName>
                </value>
                <value>
                    <fullName>ARMENIA</fullName>
                </value>
                <value>
                    <fullName>ARUBA</fullName>
                </value>
                <value>
                    <fullName>AUSTRALIA</fullName>
                </value>
                <value>
                    <fullName>AUSTRIA</fullName>
                </value>
                <value>
                    <fullName>AZERBAIJAN</fullName>
                </value>
                <value>
                    <fullName>BAHAMAS</fullName>
                </value>
                <value>
                    <fullName>BAHRAIN</fullName>
                </value>
                <value>
                    <fullName>BANGLADESH</fullName>
                </value>
                <value>
                    <fullName>BARBADOS</fullName>
                </value>
                <value>
                    <fullName>BELARUS</fullName>
                </value>
                <value>
                    <fullName>BELGIUM</fullName>
                </value>
                <value>
                    <fullName>BELIZE</fullName>
                </value>
                <value>
                    <fullName>BENIN</fullName>
                </value>
                <value>
                    <fullName>BERMUDA</fullName>
                </value>
                <value>
                    <fullName>BHUTAN</fullName>
                </value>
                <value>
                    <fullName>BOLIVIA</fullName>
                </value>
                <value>
                    <fullName>BOSNIA AND HERZEGOWINA</fullName>
                </value>
                <value>
                    <fullName>BOTSWANA</fullName>
                </value>
                <value>
                    <fullName>BOUVET ISLAND</fullName>
                </value>
                <value>
                    <fullName>CHINA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Billing_State__c</fullName>
        <inlineHelpText>If State is required, please enter as two alphanumeric characters, e.g. GA instead of Georgia</inlineHelpText>
        <label>Billing State/County</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_ZIP_Postal_Code__c</fullName>
        <label>Billing ZIP/Postal Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>1. Not yet trading with SHL - (definition - the account is new and/or has no trading history with SHL to date)
2. Trading with SHL - (definition - the account has sales recorded with SHL in the last 2 years)
3. Ceased Trading with SHL - (definition - the account has not traded with SHL in the past 12 months but has previously.) 
4. Dead - (Gone out of Business) (definition - The Account for whatever reason is no longer a trading entity)
Previous Values
1. Active with SHL (definition - The account has a track record of sales and/or opportunities managed in the last 2 years)
2. Inactive with SHL (definition - The account is still a trading account but there has been no activity with SHL (sales or opportunities managed) in the last 2 years)</description>
        <inlineHelpText>Status indicates if Account is approved or not. If you believe an unapproved Account should be Approved, Submit for Approval.</inlineHelpText>
        <label>Account Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Unapproved</fullName>
                    <default>true</default>
                    <label>Unapproved</label>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Unapproved - Out of Business</fullName>
                </value>
                <value>
                    <fullName>Unapproved - Trade Not Allowed</fullName>
                </value>
                <value>
                    <fullName>Unapproved - Duplicate</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>BU__c</fullName>
        <formula>text(Account.BU__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>BU</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mailing_Address_Line_1__c</fullName>
        <label>Address Line 1</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mailing_City__c</fullName>
        <label>City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mailing_Country__c</fullName>
        <label>Country (not in use)</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AFGHANISTAN</fullName>
                </value>
                <value>
                    <fullName>ALBANIA</fullName>
                </value>
                <value>
                    <fullName>ALDERNEY</fullName>
                </value>
                <value>
                    <fullName>ALGERIA</fullName>
                </value>
                <value>
                    <fullName>AMERICAN SAMOA</fullName>
                </value>
                <value>
                    <fullName>ANDORRA</fullName>
                </value>
                <value>
                    <fullName>ANGOLA</fullName>
                </value>
                <value>
                    <fullName>ANGUILLA</fullName>
                </value>
                <value>
                    <fullName>ANTARCTICA</fullName>
                </value>
                <value>
                    <fullName>ANTIGUA AND BARBUDA</fullName>
                </value>
                <value>
                    <fullName>ARGENTINA</fullName>
                </value>
                <value>
                    <fullName>ARMENIA</fullName>
                </value>
                <value>
                    <fullName>ARUBA</fullName>
                </value>
                <value>
                    <fullName>AUSTRALIA</fullName>
                </value>
                <value>
                    <fullName>AUSTRIA</fullName>
                </value>
                <value>
                    <fullName>AZERBAIJAN</fullName>
                </value>
                <value>
                    <fullName>BAHAMAS</fullName>
                </value>
                <value>
                    <fullName>BAHRAIN</fullName>
                </value>
                <value>
                    <fullName>BANGLADESH</fullName>
                </value>
                <value>
                    <fullName>BARBADOS</fullName>
                </value>
                <value>
                    <fullName>BELARUS</fullName>
                </value>
                <value>
                    <fullName>BELGIUM</fullName>
                </value>
                <value>
                    <fullName>BELIZE</fullName>
                </value>
                <value>
                    <fullName>BENIN</fullName>
                </value>
                <value>
                    <fullName>BERMUDA</fullName>
                </value>
                <value>
                    <fullName>BHUTAN</fullName>
                </value>
                <value>
                    <fullName>BOLIVIA</fullName>
                </value>
                <value>
                    <fullName>BOSNIA AND HERZEGOWINA</fullName>
                </value>
                <value>
                    <fullName>BOTSWANA</fullName>
                </value>
                <value>
                    <fullName>BOUVET ISLAND</fullName>
                </value>
                <value>
                    <fullName>CHINA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Mailing_ZIP_Postal_Code__c</fullName>
        <label>ZIP/Postal Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Same_As_The_Account_Billing_Address__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If this option is selected, then the Contact Mailing Address is copied from the Account Billing Address.</description>
        <inlineHelpText>Check this box to set the Contact Address to the same as the Account Billing Address. This address will not be populated from the Account until you hit Save. You must ensure this box is not ticked if you want to enter a different address for the Contact.</inlineHelpText>
        <label>Same As The Account Billing Address</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

force-app/main/objects/Course_Booking__c.object
<CustomObject>
    <description>Public and Incompany course bookings to replace Big Sky Courses &amp; Bookings module</description>
    <fields>
        <fullName>Course_Description__c</fullName>
        <description>From the course record</description>
        <label>Course Description</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Course_Type__c</fullName>
        <description>Course Type from Course object</description>
        <label>Course Type</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Course Booking</label>
    <nameField>
        <displayFormat>CB{000000}</displayFormat>
        <label>Booking Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Bookings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/objects/Courses__c.object
<CustomObject>
    <description>Area to keep list of all course types, codes, costs and venues</description>
    <fields>
        <fullName>Course_Description__c</fullName>
        <description>Full name of the course which can be translated and appears on templates.</description>
        <label>Course Description</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Course_Type__c</fullName>
        <label>Course Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Ability</fullName>
                </value>
                <value>
                    <fullName>Personality</fullName>
                </value>
                <value>
                    <fullName>Ability/Personality</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Job Profiling</fullName>
                </value>
                <value>
                    <fullName>Internal</fullName>
                </value>
                <value>
                    <fullName>System Training</fullName>
                </value>
                <value>
                    <fullName>System Demo</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Duration__c</fullName>
        <description>To replace duration formula field renamed to Old</description>
        <inlineHelpText>Number of days the course runs for</inlineHelpText>
        <label>Duration</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <label>Courses</label>
    <nameField>
        <displayFormat>C{000000}</displayFormat>
        <label>Course Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <recordTypes>
        <fullName>Public</fullName>
        <active>true</active>
        <label>Public</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/CourseBookingBulkImplementorTest.cls
/*************This Component is used to handle the creation of Bulk Course Booking from the Courses. ************************
*             Created By: Prachi Gupta(prachi.gupta@shl.com)                                                                *                      
*             Created Date: 28-04-2022                                                                                      *
*****************************************************************************************************************************/

@isTest
public class CourseBookingBulkImplementorTest{

    @isTest(seealldata=true) 
    
    //Test Method For having Duplicate CB for Course.
    static void testMethod1(){
        
        test.StartTest();
        Account testAct=new Account(name='Test Account_CB',Status__c='Approved',Billing_Address_Line_1__c='test',Billing_City__c='Test City',
                                    Billing_Country__c='CHINA',Billing_State__c='Test',Billing_ZIP_Postal_Code__c='1100110',BU__c='China - CN1');
        insert testAct;
        Contact testCont =CreateTestData.getContact(testAct.id);  
        Contact testContact =new Contact(lastname='Test Contact_CB',
                                         AccountId=testAct.Id ,
                                         Same_As_The_Account_Billing_Address__c=true,
                                         Mailing_Address_Line_1__c ='test',
                                         Mailing_City__c='test',
                                         Mailing_ZIP_Postal_Code__c ='110094',      
                                         Mailing_Country__c='India');
        insert testContact;
        
        Courses__c testCourses = new Courses__c(Course_Type__c = 'System' ,Course_Description__c = 'Test',Duration__c = '5',
                                               Profit_Centre__c = 'Canada - CA1' ,Course_Start_Date__c = system.today() ,
                                               Course_End_Date__c = system.today(), Course_Status__c = 'Provisional' , Delivery_Mode__c = 'Online',
                                               Survey_Language__c = 'EN-GB', Course_Name__c = 'FS' , Course_BU__c = 'Canada', Maximum_Delegates__c = 10);
        
        insert testCourses;
        
         Course_Booking__c cb = new Course_Booking__c(Course_Number__c = testCourses.iD , Delegate_Contact__c = testContact.Id ,Booking_Status__c = 'Confirmed');
       insert cb;
        
       Courses__c courseData = CourseBookingBulkImplementor.getCourseData(testCourses.iD);
       Decimal fs = courseData.Course_Free_Spaces__c; 
       system.assertEquals(testCourses.iD , courseData.iD) ;
       List<Course_Booking__c> courseBookingList = new List<Course_Booking__c>();
        for(integer i=0;i<2;i++){
            Course_Booking__c cb2 = new Course_Booking__c(Course_Number__c = testCourses.iD , Delegate_Contact__c = testContact.Id ,Booking_Status__c = 'Confirmed');
            courseBookingList.add(cb2); 
            
        }
        
         Course_Booking__c cb3 = new Course_Booking__c(Course_Number__c = testCourses.iD , Delegate_Contact__c = testCont.Id ,Booking_Status__c = 'Confirmed');
         courseBookingList.add(cb3); 
         CourseBookingBulkImplementor.CBResultWrapper CBR = new CourseBookingBulkImplementor.CBResultWrapper();
         CBR = CourseBookingBulkImplementor.saveCourseBookings(courseBookingList,fs);  
         system.assertEquals('1 Course Bookings records saved successfully', CBR.Message) ;
         system.assertEquals('Success', CBR.MessageType) ;
        test.stopTest();
        
    }
    
    //Test Method For Course having no existing CB.
    @isTest(seealldata=true) 
    static void testMethod2(){
         List<Course_Booking__c> courseBookingList = new List<Course_Booking__c>();  
       
        test.startTest();
        //Test Data
        Account testAct=new Account(name='Test Account_CB',Status__c='Approved',Billing_Address_Line_1__c='test',Billing_City__c='Test City',Billing_Country__c='CHINA',Billing_State__c='Test',Billing_ZIP_Postal_Code__c='1100110',BU__c='China - CN1');
        insert testAct;
        Contact testCont =CreateTestData.getContact(testAct.id); 
        Courses__c testCourses = new Courses__c(Course_Type__c = 'System' ,Course_Description__c = 'Test',Duration__c = '5',
                                               Profit_Centre__c = 'Canada - CA1' ,Course_Start_Date__c = system.today() ,
                                               Course_End_Date__c = system.today(), Course_Status__c = 'Provisional' , Delivery_Mode__c = 'Online',
                                               Survey_Language__c = 'EN-GB', Course_Name__c = 'FS' , Course_BU__c = 'Canada', Maximum_Delegates__c = 10);
      
        insert testCourses;
        
         Contact testContact =new Contact(lastname='Test Contact_CB',
                                         AccountId=testAct.Id ,
                                         Same_As_The_Account_Billing_Address__c=true,
                                         Mailing_Address_Line_1__c ='test',
                                         Mailing_City__c='test',
                                         Mailing_ZIP_Postal_Code__c ='110094',      
                                         Mailing_Country__c='India');
     insert testContact;   
     
     for(integer i=0;i<2;i++){
            Course_Booking__c cb2 = new Course_Booking__c(Course_Number__c = testCourses.iD , Delegate_Contact__c = testContact.Id ,Booking_Status__c = 'Confirmed');
            courseBookingList.add(cb2); 
            
        }
        
         Course_Booking__c cb3 = new Course_Booking__c(Course_Number__c = testCourses.iD , Delegate_Contact__c = testCont.Id ,Booking_Status__c = 'Confirmed');
         courseBookingList.add(cb3); 
        
       
       Courses__c courseData = CourseBookingBulkImplementor.getCourseData(testCourses.iD);
         
       Decimal fs = courseData.Course_Free_Spaces__c; 
       system.assertEquals(testCourses.iD , courseData.iD) ;
       
         CourseBookingBulkImplementor.CBResultWrapper CBR = new CourseBookingBulkImplementor.CBResultWrapper();
         CBR = CourseBookingBulkImplementor.saveCourseBookings(courseBookingList,fs);  
         system.assertEquals('2 Course Bookings records saved successfully', CBR.Message) ;
         system.assertEquals('Success', CBR.MessageType) ;
         test.stopTest();  
        
    }
    
    //Test Method For Course having duplicate CB.
     @isTest(seealldata=true) 
    static void duplicateRecordTest(){
         List<Course_Booking__c> courseBookingList = new List<Course_Booking__c>();  
       
        test.startTest();
        //Test Data
        Account testAct=new Account(name='Test Account_CB',Status__c='Approved',Billing_Address_Line_1__c='test',Billing_City__c='Test City',Billing_Country__c='CHINA',Billing_State__c='Test',Billing_ZIP_Postal_Code__c='1100110',BU__c='China - CN1');
        insert testAct;
        Contact testCont =CreateTestData.getContact(testAct.id); 
        Courses__c testCourses = new Courses__c(Course_Type__c = 'System' ,Course_Description__c = 'Test',Duration__c = '5',
                                               Profit_Centre__c = 'Canada - CA1' ,Course_Start_Date__c = system.today() ,
                                               Course_End_Date__c = system.today(), Course_Status__c = 'Provisional' , Delivery_Mode__c = 'Online',
                                               Survey_Language__c = 'EN-GB', Course_Name__c = 'FS' , Course_BU__c = 'Canada', Maximum_Delegates__c = 10);
      
        insert testCourses;
        
         Contact testContact =new Contact(lastname='Test Contact_CB',
                                         AccountId=testAct.Id ,
                                         Same_As_The_Account_Billing_Address__c=true,
                                         Mailing_Address_Line_1__c ='test',
                                         Mailing_City__c='test',
                                         Mailing_ZIP_Postal_Code__c ='110094',      
                                         Mailing_Country__c='India');
     insert testContact;   
    
            Course_Booking__c cb2 = new Course_Booking__c(Course_Number__c = testCourses.iD , Delegate_Contact__c = testContact.Id ,Booking_Status__c = 'Confirmed');
            insert cb2; 
            
    
        
         Course_Booking__c cb3 = new Course_Booking__c(Course_Number__c = testCourses.iD , Delegate_Contact__c = testContact.Id ,Booking_Status__c = 'Confirmed');
         courseBookingList.add(cb3); 
        
       
       Courses__c courseData = CourseBookingBulkImplementor.getCourseData(testCourses.iD);
         
       Decimal fs = courseData.Course_Free_Spaces__c; 
       system.assertEquals(testCourses.iD , courseData.iD) ;
       
         CourseBookingBulkImplementor.CBResultWrapper CBR = new CourseBookingBulkImplementor.CBResultWrapper();
         CBR = CourseBookingBulkImplementor.saveCourseBookings(courseBookingList,fs);  
         system.assertEquals('Duplicate Course Booking! This Course already has a Course Booking with this Delegate Contact.', CBR.Message) ;
         system.assertEquals('Error', CBR.MessageType) ;
         test.stopTest();  
        
    }
    
    
      //Test Method For negative Case check. When we add CB having no Delegate Contact
     @isTest(seealldata=true) 
    static void CBwithNoDelegateTest(){
         List<Course_Booking__c> courseBookingList = new List<Course_Booking__c>();  
       
        test.startTest();
        //Test Data
        Account testAct=new Account(name='Test Account_CB',Status__c='Approved',Billing_Address_Line_1__c='test',Billing_City__c='Test City',Billing_Country__c='CHINA',Billing_State__c='Test',Billing_ZIP_Postal_Code__c='1100110',BU__c='China - CN1');
        insert testAct;
        Contact testCont =CreateTestData.getContact(testAct.id); 
        Courses__c testCourses = new Courses__c(Course_Type__c = 'System' ,Course_Description__c = 'Test', Duration__c = '5',
                                               Profit_Centre__c = 'Canada - CA1' ,Course_Start_Date__c = system.today() ,
                                               Course_End_Date__c = system.today(), Course_Status__c = 'Provisional' , Delivery_Mode__c = 'Online',
                                               Survey_Language__c = 'EN-GB', Course_Name__c = 'FS' , Course_BU__c = 'Canada', Maximum_Delegates__c = 10);
      
        insert testCourses;
        
         Contact testContact =new Contact(lastname='Test Contact_CB',
                                         AccountId=testAct.Id ,
                                         Same_As_The_Account_Billing_Address__c=true,
                                         Mailing_Address_Line_1__c ='test',
                                         Mailing_City__c='test',
                                         Mailing_ZIP_Postal_Code__c ='110094',      
                                         Mailing_Country__c='India');
     insert testContact;   
    
            Course_Booking__c cb2 = new Course_Booking__c(Course_Number__c = testCourses.iD , Delegate_Contact__c = testContact.Id ,Booking_Status__c = 'Confirmed');
            insert cb2; 
            
    
        
         Course_Booking__c cb3 = new Course_Booking__c(Course_Number__c = testCourses.iD  ,Booking_Status__c = 'Confirmed');
         courseBookingList.add(cb3); 
        
       
       Courses__c courseData = CourseBookingBulkImplementor.getCourseData(testCourses.iD);
         
       Decimal fs = courseData.Course_Free_Spaces__c; 
       system.assertEquals(testCourses.iD , courseData.iD) ;
       
         CourseBookingBulkImplementor.CBResultWrapper CBR = new CourseBookingBulkImplementor.CBResultWrapper();
        try{
         CBR = CourseBookingBulkImplementor.saveCourseBookings(courseBookingList,fs);  
        }catch(AuraHAndledException ex){
             String Message = ex.getMessage();
             system.assert(Message.contains('Script-thrown exception'));
        }
         test.stopTest();
  
           
        
    }
    
}