force-app/main/objects/Account.object
<CustomObject>
    <fields>
        <fullName>BU__c</fullName>
        <label>BU</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Master_BUs</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Billing_Address_Line_1__c</fullName>
        <inlineHelpText>If the address goes over more than one line then please use Address Line 2 and Address Line 3. This formatting will display on any Customer facing documents.</inlineHelpText>
        <label>Billing Address Line 1</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_City__c</fullName>
        <label>Billing City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_Country__c</fullName>
        <label>Billing Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AFGHANISTAN</fullName>
                </value>
                <value>
                    <fullName>ALBANIA</fullName>
                </value>
                <value>
                    <fullName>ALDERNEY</fullName>
                </value>
                <value>
                    <fullName>ALGERIA</fullName>
                </value>
                <value>
                    <fullName>AMERICAN SAMOA</fullName>
                </value>
                <value>
                    <fullName>ANDORRA</fullName>
                </value>
                <value>
                    <fullName>ANGOLA</fullName>
                </value>
                <value>
                    <fullName>ANGUILLA</fullName>
                </value>
                <value>
                    <fullName>ANTARCTICA</fullName>
                </value>
                <value>
                    <fullName>ANTIGUA AND BARBUDA</fullName>
                </value>
                <value>
                    <fullName>ARGENTINA</fullName>
                </value>
                <value>
                    <fullName>ARMENIA</fullName>
                </value>
                <value>
                    <fullName>ARUBA</fullName>
                </value>
                <value>
                    <fullName>AUSTRALIA</fullName>
                </value>
                <value>
                    <fullName>AUSTRIA</fullName>
                </value>
                <value>
                    <fullName>AZERBAIJAN</fullName>
                </value>
                <value>
                    <fullName>BAHAMAS</fullName>
                </value>
                <value>
                    <fullName>BAHRAIN</fullName>
                </value>
                <value>
                    <fullName>BANGLADESH</fullName>
                </value>
                <value>
                    <fullName>BARBADOS</fullName>
                </value>
                <value>
                    <fullName>BELARUS</fullName>
                </value>
                <value>
                    <fullName>BELGIUM</fullName>
                </value>
                <value>
                    <fullName>BELIZE</fullName>
                </value>
                <value>
                    <fullName>BENIN</fullName>
                </value>
                <value>
                    <fullName>BERMUDA</fullName>
                </value>
                <value>
                    <fullName>BHUTAN</fullName>
                </value>
                <value>
                    <fullName>BOLIVIA</fullName>
                </value>
                <value>
                    <fullName>BOSNIA AND HERZEGOWINA</fullName>
                </value>
                <value>
                    <fullName>BOTSWANA</fullName>
                </value>
                <value>
                    <fullName>BOUVET ISLAND</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Billing_State__c</fullName>
        <inlineHelpText>If State is required, please enter as two alphanumeric characters, e.g. GA instead of Georgia</inlineHelpText>
        <label>Billing State/County</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_ZIP_Postal_Code__c</fullName>
        <label>Billing ZIP/Postal Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>1. Not yet trading with SHL - (definition - the account is new and/or has no trading history with SHL to date)
2. Trading with SHL - (definition - the account has sales recorded with SHL in the last 2 years)
3. Ceased Trading with SHL - (definition - the account has not traded with SHL in the past 12 months but has previously.) 
4. Dead - (Gone out of Business) (definition - The Account for whatever reason is no longer a trading entity)
Previous Values
1. Active with SHL (definition - The account has a track record of sales and/or opportunities managed in the last 2 years)
2. Inactive with SHL (definition - The account is still a trading account but there has been no activity with SHL (sales or opportunities managed) in the last 2 years)</description>
        <inlineHelpText>Status indicates if Account is approved or not. If you believe an unapproved Account should be Approved, Submit for Approval.</inlineHelpText>
        <label>Account Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Unapproved</fullName>
                    <default>true</default>
                    <label>Unapproved</label>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Unapproved - Out of Business</fullName>
                </value>
                <value>
                    <fullName>Unapproved - Trade Not Allowed</fullName>
                </value>
                <value>
                    <fullName>Unapproved - Duplicate</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>BU__c</fullName>
        <formula>text(Account.BU__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>BU</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mailing_Address_Line_1__c</fullName>
        <label>Address Line 1</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mailing_City__c</fullName>
        <label>City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mailing_Country__c</fullName>
        <label>Country (not in use)</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AFGHANISTAN</fullName>
                </value>
                <value>
                    <fullName>ALBANIA</fullName>
                </value>
                <value>
                    <fullName>ALDERNEY</fullName>
                </value>
                <value>
                    <fullName>ALGERIA</fullName>
                </value>
                <value>
                    <fullName>AMERICAN SAMOA</fullName>
                </value>
                <value>
                    <fullName>ANDORRA</fullName>
                </value>
                <value>
                    <fullName>ANGOLA</fullName>
                </value>
                <value>
                    <fullName>ANGUILLA</fullName>
                </value>
                <value>
                    <fullName>ANTARCTICA</fullName>
                </value>
                <value>
                    <fullName>ANTIGUA AND BARBUDA</fullName>
                </value>
                <value>
                    <fullName>ARGENTINA</fullName>
                </value>
                <value>
                    <fullName>ARMENIA</fullName>
                </value>
                <value>
                    <fullName>ARUBA</fullName>
                </value>
                <value>
                    <fullName>AUSTRALIA</fullName>
                </value>
                <value>
                    <fullName>AUSTRIA</fullName>
                </value>
                <value>
                    <fullName>AZERBAIJAN</fullName>
                </value>
                <value>
                    <fullName>BAHAMAS</fullName>
                </value>
                <value>
                    <fullName>BAHRAIN</fullName>
                </value>
                <value>
                    <fullName>BANGLADESH</fullName>
                </value>
                <value>
                    <fullName>BARBADOS</fullName>
                </value>
                <value>
                    <fullName>BELARUS</fullName>
                </value>
                <value>
                    <fullName>BELGIUM</fullName>
                </value>
                <value>
                    <fullName>BELIZE</fullName>
                </value>
                <value>
                    <fullName>BENIN</fullName>
                </value>
                <value>
                    <fullName>BERMUDA</fullName>
                </value>
                <value>
                    <fullName>BHUTAN</fullName>
                </value>
                <value>
                    <fullName>BOLIVIA</fullName>
                </value>
                <value>
                    <fullName>BOSNIA AND HERZEGOWINA</fullName>
                </value>
                <value>
                    <fullName>BOTSWANA</fullName>
                </value>
                <value>
                    <fullName>BOUVET ISLAND</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Mailing_ZIP_Postal_Code__c</fullName>
        <label>ZIP/Postal Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Same_As_The_Account_Billing_Address__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If this option is selected, then the Contact Mailing Address is copied from the Account Billing Address.</description>
        <inlineHelpText>Check this box to set the Contact Address to the same as the Account Billing Address. This address will not be populated from the Account until you hit Save. You must ensure this box is not ticked if you want to enter a different address for the Contact.</inlineHelpText>
        <label>Same As The Account Billing Address</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

force-app/main/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Billing_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Billing Contact(Legacy)</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contracts (Billing Contact)</relationshipLabel>
        <relationshipName>Contracts2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Legal_Order_Name__c</fullName>
        <label>Legal Order Name(Legacy)</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>S2P_Reference_Required__c</fullName>
        <description>Check on the S2P Reference.</description>
        <inlineHelpText>Choose new if system referenced in the order does not currently exist, otherwise choose Existing</inlineHelpText>
        <label>System Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Existing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Subscription_Start_Date__c</fullName>
        <inlineHelpText>This date should be the same as the Contract Start Date unless delay has been approved in CLM.</inlineHelpText>
        <label>Product Subscription Start Date</label>
        <type>Date</type>
    </fields>
</CustomObject>

force-app/main/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Billing_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Billing Contact</label>
        <lookupFilter>
            <active>false</active>
            <errorMessage>Billing Contact should be part of the account linked to the opportunity.</errorMessage>
            <filterItems>
                <field>$Source.AccountId</field>
                <operation>equals</operation>
                <valueField>Contact.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Primary_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities (Primary Contact)</relationshipLabel>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TM_Phase__c</fullName>
        <description>This field is used to replace the existing proposition field.</description>
        <inlineHelpText>Select the Client Interest that best defines the scope of the client’s project, or Combined if the project is mixed.</inlineHelpText>
        <label>Client Interest</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Talent Acquisition</fullName>
                </value>
                <value>
                    <fullName>Talent Management</fullName>
                </value>
                <value>
                    <fullName>TAandTMCombined</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Talent_Segment__c</fullName>
        <description>This is new field, created as a part of nomenclature change(SSE--113)</description>
        <inlineHelpText>Select the overall talent segment or population that the client is focused on.</inlineHelpText>
        <label>Talent Segment</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Graduate / Apprentice</fullName>
                </value>
                <value>
                    <fullName>High Potential</fullName>
                </value>
                <value>
                    <fullName>Functional / Professional</fullName>
                </value>
                <value>
                    <fullName>Manager / Leader</fullName>
                </value>
                <value>
                    <fullName>Volume</fullName>
                </value>
                <value>
                    <fullName>Other / Unknown</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

force-app/main/objects/Order.object
<CustomObject>
    <fields>
        <fullName>BU__c</fullName>
        <formula>TEXT(Account.BU__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>BU</label>
        <type>Text</type>
    </fields>
</CustomObject>

classes/ReductionOrderCreationOpptyClsTest.cls
@istest
public class ReductionOrderCreationOpptyClsTest {
    @istest(seealldata = true)
    public static void ReductionOrderCreationOpptyClsTestMethod(){
        Account acc=new Account(currencyisocode = 'AUD',name='Test Account',Status__c='Approved',Billing_Address_Line_1__c='test',Billing_City__c='Test City',Billing_Country__c='Test Country',Billing_State__c='Test',Billing_ZIP_Postal_Code__c='1100110',BU__c='China - CN1');
        insert acc;
        
        Contact con=new Contact(lastname='Test Contact', Accountid=acc.id,Same_As_The_Account_Billing_Address__c=true,Mailing_Address_Line_1__c ='test',Mailing_City__c='test',Mailing_ZIP_Postal_Code__c ='110094',Mailing_Country__c='India');
        insert con;
        
        Contract contract = new Contract();
        contract.AccountId = acc.Id;   
        contract.CurrencyIsoCode = acc.CurrencyIsoCode;
        contract.S2P_Reference_Required__c = 'New';
        contract.Status = 'Draft';
        contract.CustomerSignedDate = Date.Today();
        contract.StartDate = Date.Today();
        contract.ContractTerm = 6;  
        contract.Legal_Order_Name__c='test';
        contract.Subscription_Start_Date__c = system.today();
        insert contract;
        string contractnumber = [select ContractNumber from contract where id = :contract.id].ContractNumber;
        
        Opportunity opp=new Opportunity(name='Test Opportunity', AccountID=acc.id,Talent_Segment__c='Volume', TM_Phase__c='Post-Hire');
        opp.ownerid=UserInfo.getUserId();
        opp.StageName='Draft';
        opp.Billing_Contact__c=con.id;
        opp.Closedate=system.today();
        opp.Primary_Contact__c=con.id;
        opp.pricebook2id='01s2000000000vQAAQ';
        opp.CurrencyIsoCode='AUD';
        opp.NVM_Credit_Card_ID__c='1234';
        opp.Amount=1000;
        opp.Variation_Opportunity__c='NO';
        opp.OppUpdatedByOrderOn__c=Date.today();
        opp.Original_Opportunity__c=null;
        opp.Annual_Contract_Value__c=1000.00;
        opp.Business_Type__c='New customer: subscription';
        opp.CurrencyISOCode='GBP';
        opp.RecordTypeID=System.label.StandardRecordType;
        opp.Forecast_Category__c='Forecast';
        opp.Multi_YearDeal__c='3';
        opp.ContractId = contract.id;
        insert opp;
        
        Order ord = new Order();
                  Id orderrt = Schema.SObjectType.Order.getRecordTypeInfosByName().get('Standard Order').getRecordTypeId();

        ord.Accountid = acc.id;
        ord.ContractId = contract.id;
        ord.name = 'test';
        //ord.RecordTypeId = '0127E0000032wq7';
        ord.Status = 'Draft';
        ord.RecordTypeId = orderrt;
        ord.EffectiveDate = system.today();
        ord.CurrencyIsoCode = contract.CurrencyIsoCode;
        ord.Pricebook2Id = '01s2000000000vQAAQ';
        ord.Reduction_Order__c = false;
        //ord.quantity = 1;
        //ord.UnitPrice = 1000;
        insert ord;
        
        PageReference pageRef = Page.ReductionOrderCreationOpportunity;
            //pageRef.getParameters().put('Project', project.id);
            //pageRef.getParameters().put('Contract', contractnumber);
            Test.setCurrentPage(pageRef);
            //apexpage.standardcontroller std = new apexpages.StandardController(opp);
            ReductionOrderCreationOpptyCls controller = new ReductionOrderCreationOpptyCls(new ApexPages.StandardController(opp));
            controller.getCloseWindow();
    }
}