force-app/main/objects/Account.object
<CustomObject>
    <fields>
        <fullName>BU__c</fullName>
        <label>BU</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Master_BUs</valueSetName>
        </valueSet>
    </fields>
</CustomObject>

force-app/main/objects/AutomaticJobCreation__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>MS_Line_of_Business__c</fullName>
        <label>MS - Line of Business</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>AutomaticJobCreation</label>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>BU__c</fullName>
        <formula>text(Account.BU__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>BU</label>
        <type>Text</type>
    </fields>
</CustomObject>

force-app/main/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Activation_Offset__c</fullName>
        <label>Activation Offset</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Booked_Elsewhere__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Booked Elsewhere(Legacy)</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Contract_End_Date__c</fullName>
        <description>Custom field to capture end date of contract and can be edited by user manually.</description>
        <inlineHelpText>Automatically populated on OAT review and activation – calculated using Product Subscription Start Date plus Duration (from Opportunity) / MSA expiry date.</inlineHelpText>
        <label>Contract End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Submission_Offset__c</fullName>
        <label>Submission Offset</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Subscription_Start_Date__c</fullName>
        <inlineHelpText>This date should be the same as the Contract Start Date unless delay has been approved in CLM.</inlineHelpText>
        <label>Product Subscription Start Date</label>
        <type>Date</type>
    </fields>
</CustomObject>

objects/Contract_Invoice_Header__c.object
<CustomObject>
    <description>Invoice Header on Contract Object</description>
    <fields>
        <fullName>BU__c</fullName>
        <label>BU</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>BU</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Credit_Note__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Credit Note?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Invoice_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Invoice Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Invoice Headers (Invoice Account)</relationshipLabel>
        <relationshipName>Invoice_Headers1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Invoice_Gross_Amount__c</fullName>
        <description>Keeps the gross invoice amount from SUN Infor10 System</description>
        <label>Sun Invoice Gross Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Invoice_Status__c</fullName>
        <description>Invoice status. This includes all invoice lines below.</description>
        <label>Invoice Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Draft - awaiting milestones</fullName>
                </value>
                <value>
                    <fullName>On Hold for Payment Milestone</fullName>
                </value>
                <value>
                    <fullName>Cross Border</fullName>
                </value>
                <value>
                    <fullName>Queried</fullName>
                </value>
                <value>
                    <fullName>Awaiting PO</fullName>
                </value>
                <value>
                    <fullName>Awaiting GST/VAT Info</fullName>
                </value>
                <value>
                    <fullName>Awaiting Chop</fullName>
                </value>
                <value>
                    <fullName>No Usage</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Ready to Invoice</fullName>
                </value>
                <value>
                    <fullName>Ready for SOE Review</fullName>
                </value>
                <value>
                    <fullName>Ready for Sun Transfer</fullName>
                </value>
                <value>
                    <fullName>Transferring to Sun</fullName>
                </value>
                <value>
                    <fullName>Sun Order Complete</fullName>
                </value>
                <value>
                    <fullName>Sun Invoice Complete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Invoice Headers</relationshipLabel>
        <relationshipName>Invoice_Headers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Payment_Due_Date__c</fullName>
        <description>Keeps the Invoice Payment Due Date from SUN Infor10 System</description>
        <inlineHelpText>Keeps the Invoice Payment Due Date from SUN Infor10 System</inlineHelpText>
        <label>Sun Payment Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SunSystems_Order_Reference__c</fullName>
        <inlineHelpText>Once the order has been raised in SunSystems enter the Order Reference here</inlineHelpText>
        <label>Sun Order Reference</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Invoice Header</label>
    <nameField>
        <displayFormat>CIH{0000000}</displayFormat>
        <label>Invoice Header ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Headers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Field_Value_Setting__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Field value setting to avoid the hard coding of values in Apex triggers or Classes.</description>
    <label>Field Value Setting</label>
</CustomObject>

force-app/main/objects/Order.object
<CustomObject>
    <fields>
        <fullName>Activation_Offset__c</fullName>
        <label>Activation Offset</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BU__c</fullName>
        <formula>TEXT(Account.BU__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>BU</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Booked_Elsewhere__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Booked Elsewhere</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Submission_Offset__c</fullName>
        <label>Submission Offset</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

force-app/main/objects/Trigger_Activation__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This List is used to activate/deactivate trigger while deployment.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Trigger Activation</label>
</CustomObject>

globalValueSets/BU.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Abu Dhabi - AD1</fullName>
    </customValue>
    <customValue>
        <fullName>Australia - AU1</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium SPS - BE5</fullName>
    </customValue>
    <customValue>
        <fullName>Canada - CA1</fullName>
    </customValue>
    <customValue>
        <fullName>China - CN1</fullName>
    </customValue>
    <customValue>
        <fullName>Denmark - DK1</fullName>
    </customValue>
    <customValue>
        <fullName>Finland - FI1</fullName>
    </customValue>
    <customValue>
        <fullName>France SPS - FR5</fullName>
    </customValue>
    <customValue>
        <fullName>Germany SPS - DE5</fullName>
    </customValue>
    <customValue>
        <fullName>Hong Kong - HK1</fullName>
    </customValue>
    <customValue>
        <fullName>India - IN1</fullName>
    </customValue>
    <customValue>
        <fullName>Italy - IT1</fullName>
    </customValue>
    <customValue>
        <fullName>Middle East - ME1</fullName>
    </customValue>
    <customValue>
        <fullName>Netherlands SPS - NL5</fullName>
    </customValue>
    <customValue>
        <fullName>New Zealand - NZ1</fullName>
    </customValue>
    <customValue>
        <fullName>Norway - NO1</fullName>
    </customValue>
    <customValue>
        <fullName>Philippines - PH1</fullName>
    </customValue>
    <customValue>
        <fullName>Saudi Arabia - SA5</fullName>
    </customValue>
    <customValue>
        <fullName>Singapore - SG1</fullName>
    </customValue>
    <customValue>
        <fullName>South Africa - ZA1</fullName>
    </customValue>
    <customValue>
        <fullName>Sweden - SE1</fullName>
    </customValue>
    <customValue>
        <fullName>Switzerland - CH1</fullName>
    </customValue>
    <customValue>
        <fullName>UK - UK1</fullName>
    </customValue>
    <customValue>
        <fullName>US - US5</fullName>
    </customValue>
    <customValue>
        <fullName>Indonesia - ID1</fullName>
    </customValue>
    <masterLabel>BU</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

globalValueSets/Master_BUs.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Abu Dhabi - AD1</fullName>
    </customValue>
    <customValue>
        <fullName>Australia - AU1</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium SPS - BE5</fullName>
    </customValue>
    <customValue>
        <fullName>Canada - CA1</fullName>
    </customValue>
    <customValue>
        <fullName>China - CN1</fullName>
    </customValue>
    <customValue>
        <fullName>Denmark - DK1</fullName>
    </customValue>
    <customValue>
        <fullName>Finland - FI1</fullName>
    </customValue>
    <customValue>
        <fullName>France SPS - FR5</fullName>
    </customValue>
    <customValue>
        <fullName>Germany SPS - DE5</fullName>
    </customValue>
    <customValue>
        <fullName>Hong Kong - HK1</fullName>
    </customValue>
    <customValue>
        <fullName>India - IN1</fullName>
    </customValue>
    <customValue>
        <fullName>Italy - IT1</fullName>
    </customValue>
    <customValue>
        <fullName>Middle East - ME1</fullName>
    </customValue>
    <customValue>
        <fullName>Netherlands SPS - NL5</fullName>
    </customValue>
    <customValue>
        <fullName>New Zealand - NZ1</fullName>
    </customValue>
    <customValue>
        <fullName>Norway - NO1</fullName>
    </customValue>
    <customValue>
        <fullName>Philippines - PH1</fullName>
    </customValue>
    <customValue>
        <fullName>Saudi Arabia - SA5</fullName>
    </customValue>
    <customValue>
        <fullName>Singapore - SG1</fullName>
    </customValue>
    <customValue>
        <fullName>South Africa - ZA1</fullName>
    </customValue>
    <customValue>
        <fullName>Sweden - SE1</fullName>
    </customValue>
    <customValue>
        <fullName>Switzerland - CH1</fullName>
    </customValue>
    <customValue>
        <fullName>UK - UK1</fullName>
    </customValue>
    <customValue>
        <fullName>US - US5</fullName>
    </customValue>
    <customValue>
        <fullName>Indonesia - ID1</fullName>
    </customValue>
    <customValue>
        <fullName>Asia Pac	India</fullName>
        <isActive>false</isActive>
        <label>Asia Pac	India</label>
    </customValue>
    <customValue>
        <fullName>Asia Pac	Singapore</fullName>
        <isActive>false</isActive>
        <label>Asia Pac	Singapore</label>
    </customValue>
    <customValue>
        <fullName>Asia Pac	AP Region</fullName>
        <isActive>false</isActive>
        <label>Asia Pac	AP Region</label>
    </customValue>
    <customValue>
        <fullName>UK	  - UK1</fullName>
        <isActive>false</isActive>
        <label>UK	  - UK1</label>
    </customValue>
    <customValue>
        <fullName>Head Office  - H50</fullName>
        <isActive>false</isActive>
        <label>Head Office  - H50</label>
    </customValue>
    <masterLabel>Master BUs</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

classes/DebtManagementController_Test.cls
@isTest
public class DebtManagementController_Test {

    @testSetup
    static void setupData() {
        String valueFV = 'XTRAE-EMP,XTRAE-ASSOC,XTREL,DEB,FREIGHT';
        Field_Value_Setting__c fVS = TestDataUtility.getFieldValueSetting(valueFV, 'Credit Note IM Codes');
        INSERT fVS;
        
        insert new Trigger_Activation__c(Name = 'ProjectInvoice_Trigger', Active__c = true);
        insert new Trigger_Activation__c(Name = 'InvoiceHeader_Trigger', Active__c = true);
        insert new Trigger_Activation__c(Name = 'Account_Trigger', Active__c = true);
        insert new Trigger_Activation__c(Name = 'Contact_Trigger', Active__c = true);
        insert new Trigger_Activation__c(Name = 'Project_Trigger', Active__c = true);
        insert new Trigger_Activation__c(Name = 'Order_Trigger', Active__c = true);
        insert new Trigger_Activation__c(Name = 'Opportunity_Trigger', Active__c = true);
        insert new Trigger_Activation__c(Name = 'OpportunityContactRoleTrigger', Active__c = true);
        insert new Trigger_Activation__c(Name = 'Contract_Trigger', Active__c = true);
        insert new Trigger_Activation__c(Name = 'ContractInvoiceLine_Trigger', Active__c = true);
        
        AutomaticJobCreation__c autoJobSettings = new AutomaticJobCreation__c(
            Name = 'Values',
            MS_Line_of_Business__c = 'Consulting,Delivery,Support'
        );
        insert autoJobSettings;
    
        Account acc = TestDataUtility.getAccount();
        insert acc;
    
        Contact contact = new Contact(
            FirstName = 'Test',
            LastName = 'Contact',
            Email = 'testcontact@example.com',
            AccountId = acc.Id
        );
        insert contact;
        
           
        Opportunity opportunityRecord = TestDataUtility.getOpportunity(acc.id, contact.id);
        INSERT opportunityRecord;
        
        // Should create Opp Line Items
        
        Contract contractRecord = TestDataUtility.getContract(acc.id, opportunityRecord.id);
        contractRecord.Subscription_Start_Date__c = date.today();
        contractRecord.Contract_End_Date__c = date.today()+365;
        contractRecord.AccountId = acc.id;
        INSERT contractRecord; 
        
        Order orderRecord = TestDataUtility.getOrder(contractRecord.id, acc.id);
        orderRecord.Booked_Elsewhere__c = False;
        orderRecord.EffectiveDate = date.today();
        orderRecord.Submission_Offset__c = -18000000;
        orderRecord.Activation_Offset__c = -18000000;
        orderRecord.opportunityId = opportunityRecord.Id;
        INSERT orderRecord;

        // Create a Contract Invoice Header
        List<Contract_Invoice_Header__c> headerList = new List<Contract_Invoice_Header__c>();
        Contract_Invoice_Header__c header = new Contract_Invoice_Header__c(
            Invoice_status__c = 'Draft',
            SunSystems_Order_Reference__c = 'SO123',
            Credit_Note__c = false,
            Invoice_Account__c = acc.Id,
            Order__c = orderRecord.Id,
            BU__c = 'India - IN1',
            Invoice_Gross_Amount__c = 200,
            Payment_Due_Date__c = date.today() - 50
        );
         Contract_Invoice_Header__c header1 = new Contract_Invoice_Header__c(
            Invoice_status__c = 'Draft',
            SunSystems_Order_Reference__c = 'SO123',
            Credit_Note__c = false,
            Invoice_Account__c = acc.Id,
            Order__c = orderRecord.Id,
            BU__c = 'India - IN1',
            Invoice_Gross_Amount__c = 200,
            Payment_Due_Date__c = date.today() - 90
        );
        headerList.add(header);
        headerList.add(header1);
        insert headerList;
    }
    
    @isTest
    static void testDebtManagement() {
        Account account = [SELECT Id FROM Account Limit 1];
        DebtManagementController.getDebtInformation(account.Id, 'Account');
        
        Opportunity opportunity = [SELECT Id FROM Opportunity Limit 1];
        DebtManagementController.getDebtInformation(opportunity.Id, 'Opportunity');
        
        Order order = [SELECT Id FROM Order Limit 1];
        DebtManagementController.getDebtInformation(order.Id, 'Order');
    }

}