force-app/main/objects/Account.object
<CustomObject>
    <fields>
        <fullName>BU__c</fullName>
        <label>BU</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Master_BUs</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Billing_Address_Line_1__c</fullName>
        <inlineHelpText>If the address goes over more than one line then please use Address Line 2 and Address Line 3. This formatting will display on any Customer facing documents.</inlineHelpText>
        <label>Billing Address Line 1</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_City__c</fullName>
        <label>Billing City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_Country__c</fullName>
        <label>Billing Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AFGHANISTAN</fullName>
                </value>
                <value>
                    <fullName>ALBANIA</fullName>
                </value>
                <value>
                    <fullName>ALDERNEY</fullName>
                </value>
                <value>
                    <fullName>ALGERIA</fullName>
                </value>
                <value>
                    <fullName>AMERICAN SAMOA</fullName>
                </value>
                <value>
                    <fullName>ANDORRA</fullName>
                </value>
                <value>
                    <fullName>ANGOLA</fullName>
                </value>
                <value>
                    <fullName>ANGUILLA</fullName>
                </value>
                <value>
                    <fullName>ANTARCTICA</fullName>
                </value>
                <value>
                    <fullName>ANTIGUA AND BARBUDA</fullName>
                </value>
                <value>
                    <fullName>ARGENTINA</fullName>
                </value>
                <value>
                    <fullName>ARMENIA</fullName>
                </value>
                <value>
                    <fullName>ARUBA</fullName>
                </value>
                <value>
                    <fullName>AUSTRALIA</fullName>
                </value>
                <value>
                    <fullName>AUSTRIA</fullName>
                </value>
                <value>
                    <fullName>AZERBAIJAN</fullName>
                </value>
                <value>
                    <fullName>BAHAMAS</fullName>
                </value>
                <value>
                    <fullName>BAHRAIN</fullName>
                </value>
                <value>
                    <fullName>BANGLADESH</fullName>
                </value>
                <value>
                    <fullName>BARBADOS</fullName>
                </value>
                <value>
                    <fullName>BELARUS</fullName>
                </value>
                <value>
                    <fullName>BELGIUM</fullName>
                </value>
                <value>
                    <fullName>BELIZE</fullName>
                </value>
                <value>
                    <fullName>BENIN</fullName>
                </value>
                <value>
                    <fullName>BERMUDA</fullName>
                </value>
                <value>
                    <fullName>BHUTAN</fullName>
                </value>
                <value>
                    <fullName>BOLIVIA</fullName>
                </value>
                <value>
                    <fullName>BOSNIA AND HERZEGOWINA</fullName>
                </value>
                <value>
                    <fullName>BOTSWANA</fullName>
                </value>
                <value>
                    <fullName>BOUVET ISLAND</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Billing_State__c</fullName>
        <inlineHelpText>If State is required, please enter as two alphanumeric characters, e.g. GA instead of Georgia</inlineHelpText>
        <label>Billing State/County</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_ZIP_Postal_Code__c</fullName>
        <label>Billing ZIP/Postal Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Same_As_The_Billing_Address__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Same As The Billing Address</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>1. Not yet trading with SHL - (definition - the account is new and/or has no trading history with SHL to date)
2. Trading with SHL - (definition - the account has sales recorded with SHL in the last 2 years)
3. Ceased Trading with SHL - (definition - the account has not traded with SHL in the past 12 months but has previously.) 
4. Dead - (Gone out of Business) (definition - The Account for whatever reason is no longer a trading entity)
Previous Values
1. Active with SHL (definition - The account has a track record of sales and/or opportunities managed in the last 2 years)
2. Inactive with SHL (definition - The account is still a trading account but there has been no activity with SHL (sales or opportunities managed) in the last 2 years)</description>
        <inlineHelpText>Status indicates if Account is approved or not. If you believe an unapproved Account should be Approved, Submit for Approval.</inlineHelpText>
        <label>Account Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Unapproved</fullName>
                    <default>true</default>
                    <label>Unapproved</label>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Unapproved - Out of Business</fullName>
                </value>
                <value>
                    <fullName>Unapproved - Trade Not Allowed</fullName>
                </value>
                <value>
                    <fullName>Unapproved - Duplicate</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>BU__c</fullName>
        <formula>text(Account.BU__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>BU</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Same_As_The_Account_Billing_Address__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If this option is selected, then the Contact Mailing Address is copied from the Account Billing Address.</description>
        <inlineHelpText>Check this box to set the Contact Address to the same as the Account Billing Address. This address will not be populated from the Account until you hit Save. You must ensure this box is not ticked if you want to enter a different address for the Contact.</inlineHelpText>
        <label>Same As The Account Billing Address</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

force-app/main/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Client_Business_Function__c</fullName>
        <inlineHelpText>Select the client business function(s) where the talent level sits.</inlineHelpText>
        <label>Function</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Finance</fullName>
                </value>
                <value>
                    <fullName>HR</fullName>
                </value>
                <value>
                    <fullName>IT / Technology</fullName>
                </value>
                <value>
                    <fullName>Legal</fullName>
                </value>
                <value>
                    <fullName>Customer Service / Call Center</fullName>
                </value>
                <value>
                    <fullName>Sales</fullName>
                </value>
                <value>
                    <fullName>Marketing</fullName>
                </value>
                <value>
                    <fullName>Procurement &amp; Ops</fullName>
                </value>
                <value>
                    <fullName>R&amp;D</fullName>
                </value>
                <value>
                    <fullName>Corporate Office</fullName>
                </value>
                <value>
                    <fullName>Enterprise Wide</fullName>
                </value>
                <value>
                    <fullName>Manufacturing</fullName>
                </value>
                <value>
                    <fullName>Store Front</fullName>
                </value>
                <value>
                    <fullName>Logistics &amp; warehouse</fullName>
                </value>
                <value>
                    <fullName>Unknown</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Offering__c</fullName>
        <description>This field has been created as a part of Nomenclature (SSE--113)</description>
        <inlineHelpText>Select the Offering(s) or Solution(s) that best define the product the client is buying.</inlineHelpText>
        <label>Offerings</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cognitive (Verify, G+ etc)</fullName>
                </value>
                <value>
                    <fullName>Cognitive Interactive (Verify Interactive)</fullName>
                </value>
                <value>
                    <fullName>OPQ</fullName>
                </value>
                <value>
                    <fullName>APTA</fullName>
                </value>
                <value>
                    <fullName>MQ</fullName>
                </value>
                <value>
                    <fullName>PJM</fullName>
                </value>
                <value>
                    <fullName>Language</fullName>
                </value>
                <value>
                    <fullName>Skills: Technology</fullName>
                </value>
                <value>
                    <fullName>Skills: non-Technology</fullName>
                </value>
                <value>
                    <fullName>JFA Standard</fullName>
                </value>
                <value>
                    <fullName>JFA Custom</fullName>
                </value>
                <value>
                    <fullName>SJT Standard</fullName>
                </value>
                <value>
                    <fullName>SJT Custom</fullName>
                </value>
                <value>
                    <fullName>Remote WorkQ</fullName>
                </value>
                <value>
                    <fullName>Coding Simulation (Automata)</fullName>
                </value>
                <value>
                    <fullName>Contact Center Simulation</fullName>
                </value>
                <value>
                    <fullName>Simulation - Others</fullName>
                </value>
                <value>
                    <fullName>Smart Interview: On Demand (Async Video Interview, AutoView)</fullName>
                </value>
                <value>
                    <fullName>Smart Interview: Live (Smart Meet, Live Interview)</fullName>
                </value>
                <value>
                    <fullName>Smart Interview: Live Coding</fullName>
                </value>
                <value>
                    <fullName>SHL Experiences</fullName>
                </value>
                <value>
                    <fullName>Candidate Engagement Portal</fullName>
                </value>
                <value>
                    <fullName>In person Assessment Centre</fullName>
                </value>
                <value>
                    <fullName>In person Development Centre</fullName>
                </value>
                <value>
                    <fullName>Virtual Assessment Centre</fullName>
                </value>
                <value>
                    <fullName>Virtual Development Centre</fullName>
                </value>
                <value>
                    <fullName>HiPo</fullName>
                </value>
                <value>
                    <fullName>Leader Edge</fullName>
                </value>
                <value>
                    <fullName>360</fullName>
                </value>
                <value>
                    <fullName>Surveys</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Talent_Level__c</fullName>
        <description>This field is created as a part of Nomenclature(SSE--113)</description>
        <inlineHelpText>Select the level(s) of employee that best defines the scope of the client’s project.</inlineHelpText>
        <label>Talent Level</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Vocational</fullName>
                </value>
                <value>
                    <fullName>Entry Level / Associate</fullName>
                </value>
                <value>
                    <fullName>Graduate and Intern</fullName>
                </value>
                <value>
                    <fullName>Professional / Individual Contributor</fullName>
                </value>
                <value>
                    <fullName>Supervisor</fullName>
                </value>
                <value>
                    <fullName>Manager</fullName>
                </value>
                <value>
                    <fullName>Individual Contributor Leader</fullName>
                </value>
                <value>
                    <fullName>Senior leadership</fullName>
                </value>
                <value>
                    <fullName>All Levels</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Talent_Segment__c</fullName>
        <description>This is new field, created as a part of nomenclature change(SSE--113)</description>
        <inlineHelpText>Select the overall talent segment or population that the client is focused on.</inlineHelpText>
        <label>Talent Segment</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Graduate / Apprentice</fullName>
                </value>
                <value>
                    <fullName>High Potential</fullName>
                </value>
                <value>
                    <fullName>Functional / Professional</fullName>
                </value>
                <value>
                    <fullName>Manager / Leader</fullName>
                </value>
                <value>
                    <fullName>Volume</fullName>
                </value>
                <value>
                    <fullName>Other / Unknown</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

classes/dependentPicklist_UpdateCtrlTester.cls
@isTest(SeeAllData=true)
public class dependentPicklist_UpdateCtrlTester {
    @isTest
    public static void test(){
        //String AcId=[select id from Account].Id;
        Account acc= new Account();
            acc.Name='Test234';
            acc.BU__c='AP Region - P10';
            acc.CurrencyIsoCode='GBP'; 
            acc.Industry='Consulting';
            acc.Billing_Address_Line_1__c='test23';
            acc.Billing_City__c='test23';
            acc.Same_As_The_Billing_Address__c=true;
            acc.Billing_Country__c='test23';
            acc.Billing_State__c='test23';
            acc.Billing_ZIP_Postal_Code__c='test23';           
            
        insert acc;
        //Account account=new Account(name='Test Account',Status__c='Approved',Billing_Address_Line_1__c='test',Billing_City__c='Test City',Billing_Country__c='Test Country',Billing_State__c='Test',Billing_ZIP_Postal_Code__c='1100110',BU__c='China - CN1');
        //insert account;
        
        Test.startTest();
        Contact con=new Contact();
        con.LastName='Test';
        con.Accountid=acc.Id;
        con.phone='9876772772';
        con.Email='abc@ymail.com';
        con.Same_As_The_Account_Billing_Address__c=true;
        insert con;
        Opportunity oppty=new Opportunity(name='Test Opportunity', AccountID=acc.Id,Offering__c='Enterprise Leadership',Talent_Level__c='Leader',Talent_Segment__c='Volume',Client_Business_Function__c='HR');
        //Opportunity oppty = CreateTestData.getOpportunity(AcId,Con.Id);
        Case case34 = new case(AccountId=acc.Id,ContactId=Con.Id,Problem2__c='Login Issue',Solution__c='other',Assigned_To__c ='Customer Systems Training',Issues__c = 'Platform-related', Product1__c = 'Ability - Verify',Opportunity__c=oppty.Id);

        
        dependentPicklist_UpdateCtrl.decimalToBinary(12);
        dependentPicklist_UpdateCtrl.base64ToBits('Test');
        dependentPicklist_UpdateCtrl.PicklistEntryWrapper PicklistEntryWrapperobj= new dependentPicklist_UpdateCtrl.PicklistEntryWrapper();
        String active=PicklistEntryWrapperobj.active;
        String defaultValue=PicklistEntryWrapperobj.defaultValue;
        String label=PicklistEntryWrapperobj.label;
        
        String value=PicklistEntryWrapperobj.value;
        String validFor=PicklistEntryWrapperobj.validFor;
        dependentPicklist_UpdateCtrl.getDependentMap(case34,'PreChatCountry__c','PreChatLanguage__c');
        
        Test.stopTest();
        
    }
    @isTest
    public static void test2(){
        string India;
        Test.startTest();
        dependentPicklist_UpdateCtrl.getButtonId('Belgium','French','Product, billing or ordering query');
        dependentPicklist_UpdateCtrl.getCntryAbrvtn_CSet(India);
        Test.stopTest();
    }
}