force-app/main/objects/Account.object
<CustomObject>
    <fields>
        <fullName>BU__c</fullName>
        <label>BU</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Master_BUs</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Billing_Address_Line_1__c</fullName>
        <inlineHelpText>If the address goes over more than one line then please use Address Line 2 and Address Line 3. This formatting will display on any Customer facing documents.</inlineHelpText>
        <label>Billing Address Line 1</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_City__c</fullName>
        <label>Billing City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_Country__c</fullName>
        <label>Billing Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AFGHANISTAN</fullName>
                </value>
                <value>
                    <fullName>ALBANIA</fullName>
                </value>
                <value>
                    <fullName>ALDERNEY</fullName>
                </value>
                <value>
                    <fullName>ALGERIA</fullName>
                </value>
                <value>
                    <fullName>AMERICAN SAMOA</fullName>
                </value>
                <value>
                    <fullName>ANDORRA</fullName>
                </value>
                <value>
                    <fullName>ANGOLA</fullName>
                </value>
                <value>
                    <fullName>ANGUILLA</fullName>
                </value>
                <value>
                    <fullName>ANTARCTICA</fullName>
                </value>
                <value>
                    <fullName>ANTIGUA AND BARBUDA</fullName>
                </value>
                <value>
                    <fullName>ARGENTINA</fullName>
                </value>
                <value>
                    <fullName>ARMENIA</fullName>
                </value>
                <value>
                    <fullName>ARUBA</fullName>
                </value>
                <value>
                    <fullName>AUSTRALIA</fullName>
                </value>
                <value>
                    <fullName>AUSTRIA</fullName>
                </value>
                <value>
                    <fullName>AZERBAIJAN</fullName>
                </value>
                <value>
                    <fullName>BAHAMAS</fullName>
                </value>
                <value>
                    <fullName>BAHRAIN</fullName>
                </value>
                <value>
                    <fullName>BANGLADESH</fullName>
                </value>
                <value>
                    <fullName>BARBADOS</fullName>
                </value>
                <value>
                    <fullName>BELARUS</fullName>
                </value>
                <value>
                    <fullName>BELGIUM</fullName>
                </value>
                <value>
                    <fullName>BELIZE</fullName>
                </value>
                <value>
                    <fullName>BENIN</fullName>
                </value>
                <value>
                    <fullName>BERMUDA</fullName>
                </value>
                <value>
                    <fullName>BHUTAN</fullName>
                </value>
                <value>
                    <fullName>BOLIVIA</fullName>
                </value>
                <value>
                    <fullName>BOSNIA AND HERZEGOWINA</fullName>
                </value>
                <value>
                    <fullName>BOTSWANA</fullName>
                </value>
                <value>
                    <fullName>BOUVET ISLAND</fullName>
                </value>
                <value>
                    <fullName>INDIA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Billing_State__c</fullName>
        <inlineHelpText>If State is required, please enter as two alphanumeric characters, e.g. GA instead of Georgia</inlineHelpText>
        <label>Billing State/County</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_ZIP_Postal_Code__c</fullName>
        <label>Billing ZIP/Postal Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Same_As_The_Billing_Address__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Same As The Billing Address</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Territory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Territory</label>
        <lookupFilter>
            <active>false</active>
            <errorMessage>Territory associated with an account should be active</errorMessage>
            <filterItems>
                <field>Territory__c.Is_Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Territory__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

force-app/main/objects/Territory__c.object
<CustomObject>
    <fields>
        <fullName>Account_Director__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Director</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Territories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Business_Development_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Business Development Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Territories2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Manager_1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Manager 1</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Territories3</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Territory</label>
    <nameField>
        <label>Territory</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/objects/Trigger_Activation__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This List is used to activate/deactivate trigger while deployment.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Trigger Activation</label>
</CustomObject>

globalValueSets/Master_BUs.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Abu Dhabi - AD1</fullName>
    </customValue>
    <customValue>
        <fullName>Australia - AU1</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium SPS - BE5</fullName>
    </customValue>
    <customValue>
        <fullName>Canada - CA1</fullName>
    </customValue>
    <customValue>
        <fullName>China - CN1</fullName>
    </customValue>
    <customValue>
        <fullName>Denmark - DK1</fullName>
    </customValue>
    <customValue>
        <fullName>Finland - FI1</fullName>
    </customValue>
    <customValue>
        <fullName>France SPS - FR5</fullName>
    </customValue>
    <customValue>
        <fullName>Germany SPS - DE5</fullName>
    </customValue>
    <customValue>
        <fullName>Hong Kong - HK1</fullName>
    </customValue>
    <customValue>
        <fullName>India - IN1</fullName>
    </customValue>
    <customValue>
        <fullName>Italy - IT1</fullName>
    </customValue>
    <customValue>
        <fullName>Middle East - ME1</fullName>
    </customValue>
    <customValue>
        <fullName>Netherlands SPS - NL5</fullName>
    </customValue>
    <customValue>
        <fullName>New Zealand - NZ1</fullName>
    </customValue>
    <customValue>
        <fullName>Norway - NO1</fullName>
    </customValue>
    <customValue>
        <fullName>Philippines - PH1</fullName>
    </customValue>
    <customValue>
        <fullName>Saudi Arabia - SA5</fullName>
    </customValue>
    <customValue>
        <fullName>Singapore - SG1</fullName>
    </customValue>
    <customValue>
        <fullName>South Africa - ZA1</fullName>
    </customValue>
    <customValue>
        <fullName>Sweden - SE1</fullName>
    </customValue>
    <customValue>
        <fullName>Switzerland - CH1</fullName>
    </customValue>
    <customValue>
        <fullName>UK - UK1</fullName>
    </customValue>
    <customValue>
        <fullName>US - US5</fullName>
    </customValue>
    <customValue>
        <fullName>Indonesia - ID1</fullName>
    </customValue>
    <customValue>
        <fullName>Asia Pac	India</fullName>
        <isActive>false</isActive>
        <label>Asia Pac	India</label>
    </customValue>
    <customValue>
        <fullName>Asia Pac	Singapore</fullName>
        <isActive>false</isActive>
        <label>Asia Pac	Singapore</label>
    </customValue>
    <customValue>
        <fullName>Asia Pac	AP Region</fullName>
        <isActive>false</isActive>
        <label>Asia Pac	AP Region</label>
    </customValue>
    <customValue>
        <fullName>UK	  - UK1</fullName>
        <isActive>false</isActive>
        <label>UK	  - UK1</label>
    </customValue>
    <customValue>
        <fullName>Head Office  - H50</fullName>
        <isActive>false</isActive>
        <label>Head Office  - H50</label>
    </customValue>
    <masterLabel>Master BUs</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

classes/AccountTerritoryManagementTest.cls
@IsTest
public class AccountTerritoryManagementTest {

    private static User createUser(String alias) {
        Profile p = [
            SELECT Id FROM Profile WHERE Name = 'Standard User' LIMIT 1
        ];

        return new User(
            Alias = alias,
            Email = alias + '@test.com',
            EmailEncodingKey = 'UTF-8',
            LastName = alias,
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US',
            ProfileId = p.Id,
            TimeZoneSidKey = 'Asia/Kolkata',
            UserName = alias + System.currentTimeMillis() + '@test.com'
        );
    }

    private static Account createAccount() {
        return new Account(
            Name = 'Test Account',
            BU__c = 'UK - UK1',
            CurrencyIsoCode = 'GBP',
            Industry = 'Agriculture',
            Billing_Address_Line_1__c = 'Line1',
            Billing_City__c = 'City',
            Same_As_The_Billing_Address__c = true,
            Billing_Country__c = 'INDIA',
            Billing_State__c = 'State',
            Billing_ZIP_Postal_Code__c = 'Zip'
        );
    }

    /* 
        INSERT ACCOUNT WITHOUT TERRITORY
    */
    @IsTest
    static void testAfterInsert_NoTerritory() {

        insert new Trigger_Activation__c(
            Name = 'Account_Trigger',
            Active__c = true
        );

        Account acc = createAccount();

        Test.startTest();
        insert acc;
        Test.stopTest();

        System.assertNotEquals(null, acc.Id);
    }

    /* 
        UPDATE WITHOUT TERRITORY CHANGE
     */
    @IsTest
    static void testAfterUpdate_NoTerritoryChange() {

        insert new Trigger_Activation__c(
            Name = 'Account_Trigger',
            Active__c = true
        );

        Account acc = createAccount();
        insert acc;

        Test.startTest();
        AccountTerritoryManagement.handleAfterInsertUpdate(
            new List<Account>{ acc },
            new Map<Id, Account>{ acc.Id => acc }
        );
        Test.stopTest();

        System.assert(true);
    }

    /* 
       TEST: FULL FLOW WITH TERRITORY 
     */
    @IsTest
    static void testSyncAccountTeams_WithTerritory() {

        insert new Trigger_Activation__c(Name = 'Account_Trigger',Active__c = true);
		insert new Trigger_Activation__c(Name = 'User_Trigger', Active__c = true);
        User bdm = createUser('bdm');
        insert bdm;
        insert new Trigger_Activation__c(Name = 'Territory_Trigger', Active__c = true);
		
        Territory__c terr = new Territory__c(
            Name = 'Test Territory',
            Business_Development_Manager__c = bdm.Id
        );
        insert terr;

        Account acc = createAccount();
        acc.Territory__c = terr.Id;
        insert acc;

        Test.startTest();
        AccountTerritoryManagement.syncAccountTeams(
            new Set<Id>{ acc.Id }
        );
        Test.stopTest();

        // Owner updated from priority
        acc = [SELECT OwnerId FROM Account WHERE Id = :acc.Id];
        System.assertEquals(bdm.Id, acc.OwnerId);

        // Account Team Member created
        System.assertEquals(
            1,
            [SELECT COUNT() FROM AccountTeamMember WHERE AccountId = :acc.Id]
        );
    }

    /* 
       DELETE EXISTING ACCOUNT TEAM MEMBERS
     */
    @IsTest
    static void testDeleteExistingAccountTeamsCoverage() {

        insert new Trigger_Activation__c(
            Name = 'Account_Trigger',
            Active__c = true
        );

        Account acc = createAccount();
        insert acc;

        AccountTeamMember atm = new AccountTeamMember(
            AccountId = acc.Id,
            UserId = UserInfo.getUserId(),
            TeamMemberRole = 'Account Manager',
            AccountAccessLevel = 'Edit'
        );
        insert atm;

        Test.startTest();
        AccountTerritoryManagement.syncAccountTeams(
            new Set<Id>{ acc.Id }
        );
        Test.stopTest();

        System.assertEquals(
            0,
            [SELECT COUNT() FROM AccountTeamMember WHERE AccountId = :acc.Id]
        );
    }

    /* 
        EMPTY INPUT SAFETY
    */
    @IsTest
    static void testEmptyHandlerSafety() {

        Test.startTest();
        AccountTerritoryManagement.handleAfterInsertUpdate(
            new List<Account>(),
            null
        );
        Test.stopTest();

        System.assert(true);
    }

    /* 
      OWNER PRIORITY LOGIC
    */
    @IsTest
    static void testGetOwnerFromPriority_AllBranches() {

        Id uid = UserInfo.getUserId();

        Territory__c t1 = new Territory__c(
            Business_Development_Manager__c = uid
        );
        System.assertEquals(uid,
            AccountTerritoryManagement.getOwnerFromPriority(t1)
        );

        Territory__c t2 = new Territory__c(
            Account_Director__c = uid
        );
        System.assertEquals(uid,
            AccountTerritoryManagement.getOwnerFromPriority(t2)
        );

        Territory__c t3 = new Territory__c(
            Manager_1__c = uid
        );
        System.assertEquals(uid,
            AccountTerritoryManagement.getOwnerFromPriority(t3)
        );

        Territory__c t4 = new Territory__c();
        System.assertEquals(
            null,
            AccountTerritoryManagement.getOwnerFromPriority(t4)
        );
    }
}