force-app/main/objects/Account.object
<CustomObject>
    <fields>
        <fullName>BU__c</fullName>
        <label>BU</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Master_BUs</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Billing_Address_Line_1__c</fullName>
        <inlineHelpText>If the address goes over more than one line then please use Address Line 2 and Address Line 3. This formatting will display on any Customer facing documents.</inlineHelpText>
        <label>Billing Address Line 1</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_City__c</fullName>
        <label>Billing City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_Country__c</fullName>
        <label>Billing Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AFGHANISTAN</fullName>
                </value>
                <value>
                    <fullName>ALBANIA</fullName>
                </value>
                <value>
                    <fullName>ALDERNEY</fullName>
                </value>
                <value>
                    <fullName>ALGERIA</fullName>
                </value>
                <value>
                    <fullName>AMERICAN SAMOA</fullName>
                </value>
                <value>
                    <fullName>ANDORRA</fullName>
                </value>
                <value>
                    <fullName>ANGOLA</fullName>
                </value>
                <value>
                    <fullName>ANGUILLA</fullName>
                </value>
                <value>
                    <fullName>ANTARCTICA</fullName>
                </value>
                <value>
                    <fullName>ANTIGUA AND BARBUDA</fullName>
                </value>
                <value>
                    <fullName>ARGENTINA</fullName>
                </value>
                <value>
                    <fullName>ARMENIA</fullName>
                </value>
                <value>
                    <fullName>ARUBA</fullName>
                </value>
                <value>
                    <fullName>AUSTRALIA</fullName>
                </value>
                <value>
                    <fullName>AUSTRIA</fullName>
                </value>
                <value>
                    <fullName>AZERBAIJAN</fullName>
                </value>
                <value>
                    <fullName>BAHAMAS</fullName>
                </value>
                <value>
                    <fullName>BAHRAIN</fullName>
                </value>
                <value>
                    <fullName>BANGLADESH</fullName>
                </value>
                <value>
                    <fullName>BARBADOS</fullName>
                </value>
                <value>
                    <fullName>BELARUS</fullName>
                </value>
                <value>
                    <fullName>BELGIUM</fullName>
                </value>
                <value>
                    <fullName>BELIZE</fullName>
                </value>
                <value>
                    <fullName>BENIN</fullName>
                </value>
                <value>
                    <fullName>BERMUDA</fullName>
                </value>
                <value>
                    <fullName>BHUTAN</fullName>
                </value>
                <value>
                    <fullName>BOLIVIA</fullName>
                </value>
                <value>
                    <fullName>BOSNIA AND HERZEGOWINA</fullName>
                </value>
                <value>
                    <fullName>BOTSWANA</fullName>
                </value>
                <value>
                    <fullName>BOUVET ISLAND</fullName>
                </value>
                <value>
                    <fullName>INDIA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Billing_State__c</fullName>
        <inlineHelpText>If State is required, please enter as two alphanumeric characters, e.g. GA instead of Georgia</inlineHelpText>
        <label>Billing State/County</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_ZIP_Postal_Code__c</fullName>
        <label>Billing ZIP/Postal Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Same_As_The_Billing_Address__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Same As The Billing Address</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

force-app/main/objects/India_GST__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>India_GST</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Address_Line_1__c</fullName>
        <label>Address Line 1</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Global_Country__c</fullName>
        <label>Country</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Global_Country_Picklist</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>State_Code__c</fullName>
        <label>State Code</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>State_County__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Status_Code</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>State_County__c</fullName>
        <label>State/County</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Global_Country__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>State_Values</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Taxpayer_Type__c</fullName>
        <label>Taxpayer Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>EXPWOP</fullName>
                    <label>External Sales without tax (EXPWOP)</label>
                </value>
                <value>
                    <fullName>EXPWP</fullName>
                    <label>External sale with tax (EXPWP)</label>
                </value>
                <value>
                    <fullName>SEZWOP</fullName>
                    <label>Sales to Special Economic Zone without tax (SEZWOP)</label>
                </value>
                <value>
                    <fullName>SEZWP</fullName>
                    <label>Sales to Special Economic Zone with tax (SEZWP)</label>
                </value>
                <value>
                    <fullName>B2B</fullName>
                    <label>Sales to customer in India not in SEZ (B2B)</label>
                </value>
                <value>
                    <fullName>URP</fullName>
                    <label>Unregistered person (URP)</label>
                </value>
                <value>
                    <fullName>B2C</fullName>
                    <isActive>false</isActive>
                    <label>Sale to end consumer</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>GST</fullName>
                </value>
                <value>
                    <fullName>VAT</fullName>
                </value>
                <value>
                    <fullName>Sales Tax</fullName>
                </value>
                <value>
                    <fullName>Billing Address</fullName>
                </value>
                <value>
                    <fullName>Shipping Address</fullName>
                </value>
                <value>
                    <fullName>PAN</fullName>
                </value>
                <value>
                    <fullName>TAN</fullName>
                </value>
                <value>
                    <fullName>Headquarters Address</fullName>
                </value>
                <value>
                    <fullName>Home Address</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ZIP_Postal_Code__c</fullName>
        <label>ZIP/Postal Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Address &amp; Tax Information</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Address &amp; Tax Information</pluralLabel>
    <recordTypes>
        <fullName>Tax</fullName>
        <active>true</active>
        <label>Tax</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

globalValueSets/Global_Country_Picklist.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>AFGHANISTAN</fullName>
    </customValue>
    <customValue>
        <fullName>ALBANIA</fullName>
    </customValue>
    <customValue>
        <fullName>ALDERNEY</fullName>
    </customValue>
    <customValue>
        <fullName>ALGERIA</fullName>
    </customValue>
    <customValue>
        <fullName>AMERICAN SAMOA</fullName>
    </customValue>
    <customValue>
        <fullName>ANDORRA</fullName>
    </customValue>
    <customValue>
        <fullName>ANGOLA</fullName>
    </customValue>
    <customValue>
        <fullName>ANGUILLA</fullName>
    </customValue>
    <customValue>
        <fullName>ANTARCTICA</fullName>
    </customValue>
    <customValue>
        <fullName>ANTIGUA AND BARBUDA</fullName>
    </customValue>
    <customValue>
        <fullName>ARGENTINA</fullName>
    </customValue>
    <customValue>
        <fullName>ARMENIA</fullName>
    </customValue>
    <customValue>
        <fullName>ARUBA</fullName>
    </customValue>
    <customValue>
        <fullName>AUSTRALIA</fullName>
    </customValue>
    <customValue>
        <fullName>AUSTRIA</fullName>
    </customValue>
    <customValue>
        <fullName>AZERBAIJAN</fullName>
    </customValue>
    <customValue>
        <fullName>BAHAMAS</fullName>
    </customValue>
    <customValue>
        <fullName>BAHRAIN</fullName>
    </customValue>
    <customValue>
        <fullName>BANGLADESH</fullName>
    </customValue>
    <customValue>
        <fullName>BARBADOS</fullName>
    </customValue>
    <customValue>
        <fullName>BELARUS</fullName>
    </customValue>
    <customValue>
        <fullName>BELGIUM</fullName>
    </customValue>
    <customValue>
        <fullName>BELIZE</fullName>
    </customValue>
    <customValue>
        <fullName>BENIN</fullName>
    </customValue>
    <customValue>
        <fullName>BERMUDA</fullName>
    </customValue>
    <customValue>
        <fullName>BHUTAN</fullName>
    </customValue>
    <customValue>
        <fullName>BOLIVIA</fullName>
    </customValue>
    <customValue>
        <fullName>BOSNIA AND HERZEGOWINA</fullName>
    </customValue>
    <customValue>
        <fullName>BOTSWANA</fullName>
    </customValue>
    <customValue>
        <fullName>BOUVET ISLAND</fullName>
    </customValue>
    <customValue>
        <fullName>INDIA</fullName>
    </customValue>
    <description>used as a global picklist over all the modules in salesforce</description>
    <masterLabel>Global Country Picklist</masterLabel>
</GlobalValueSet>

globalValueSets/Master_BUs.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Abu Dhabi - AD1</fullName>
    </customValue>
    <customValue>
        <fullName>Australia - AU1</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium SPS - BE5</fullName>
    </customValue>
    <customValue>
        <fullName>Canada - CA1</fullName>
    </customValue>
    <customValue>
        <fullName>China - CN1</fullName>
    </customValue>
    <customValue>
        <fullName>Denmark - DK1</fullName>
    </customValue>
    <customValue>
        <fullName>Finland - FI1</fullName>
    </customValue>
    <customValue>
        <fullName>France SPS - FR5</fullName>
    </customValue>
    <customValue>
        <fullName>Germany SPS - DE5</fullName>
    </customValue>
    <customValue>
        <fullName>Hong Kong - HK1</fullName>
    </customValue>
    <customValue>
        <fullName>India - IN1</fullName>
    </customValue>
    <customValue>
        <fullName>Italy - IT1</fullName>
    </customValue>
    <customValue>
        <fullName>Middle East - ME1</fullName>
    </customValue>
    <customValue>
        <fullName>Netherlands SPS - NL5</fullName>
    </customValue>
    <customValue>
        <fullName>New Zealand - NZ1</fullName>
    </customValue>
    <customValue>
        <fullName>Norway - NO1</fullName>
    </customValue>
    <customValue>
        <fullName>Philippines - PH1</fullName>
    </customValue>
    <customValue>
        <fullName>Saudi Arabia - SA5</fullName>
    </customValue>
    <customValue>
        <fullName>Singapore - SG1</fullName>
    </customValue>
    <customValue>
        <fullName>South Africa - ZA1</fullName>
    </customValue>
    <customValue>
        <fullName>Sweden - SE1</fullName>
    </customValue>
    <customValue>
        <fullName>Switzerland - CH1</fullName>
    </customValue>
    <customValue>
        <fullName>UK - UK1</fullName>
    </customValue>
    <customValue>
        <fullName>US - US5</fullName>
    </customValue>
    <customValue>
        <fullName>Indonesia - ID1</fullName>
    </customValue>
    <customValue>
        <fullName>Asia Pac	India</fullName>
        <isActive>false</isActive>
        <label>Asia Pac	India</label>
    </customValue>
    <customValue>
        <fullName>Asia Pac	Singapore</fullName>
        <isActive>false</isActive>
        <label>Asia Pac	Singapore</label>
    </customValue>
    <customValue>
        <fullName>Asia Pac	AP Region</fullName>
        <isActive>false</isActive>
        <label>Asia Pac	AP Region</label>
    </customValue>
    <customValue>
        <fullName>UK	  - UK1</fullName>
        <isActive>false</isActive>
        <label>UK	  - UK1</label>
    </customValue>
    <customValue>
        <fullName>Head Office  - H50</fullName>
        <isActive>false</isActive>
        <label>Head Office  - H50</label>
    </customValue>
    <masterLabel>Master BUs</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

globalValueSets/State_Values.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Andaman &amp; Nicobar Islands</fullName>
    </customValue>
    <customValue>
        <fullName>Andhra Pradesh</fullName>
    </customValue>
    <customValue>
        <fullName>Arunachal Pradesh</fullName>
    </customValue>
    <customValue>
        <fullName>Assam</fullName>
    </customValue>
    <customValue>
        <fullName>Bihar</fullName>
    </customValue>
    <customValue>
        <fullName>Chandigarh</fullName>
    </customValue>
    <customValue>
        <fullName>Chhattisgarh</fullName>
    </customValue>
    <customValue>
        <fullName>Dadra and Nagar Haveli and Daman and Diu</fullName>
    </customValue>
    <customValue>
        <fullName>Delhi</fullName>
    </customValue>
    <customValue>
        <fullName>Goa</fullName>
    </customValue>
    <customValue>
        <fullName>Gujarat</fullName>
    </customValue>
    <customValue>
        <fullName>Haryana</fullName>
    </customValue>
    <customValue>
        <fullName>Himachal Pradesh</fullName>
    </customValue>
    <customValue>
        <fullName>Jammu &amp; Kashmir</fullName>
    </customValue>
    <customValue>
        <fullName>Jharkhand</fullName>
    </customValue>
    <customValue>
        <fullName>Karnataka</fullName>
    </customValue>
    <customValue>
        <fullName>Kerala</fullName>
    </customValue>
    <customValue>
        <fullName>Ladakh</fullName>
    </customValue>
    <customValue>
        <fullName>Lakshdweep</fullName>
    </customValue>
    <customValue>
        <fullName>Madhya Pradesh</fullName>
    </customValue>
    <customValue>
        <fullName>Maharashtra</fullName>
    </customValue>
    <customValue>
        <fullName>Manipur</fullName>
    </customValue>
    <customValue>
        <fullName>Meghalaya</fullName>
    </customValue>
    <customValue>
        <fullName>Mizoram</fullName>
    </customValue>
    <customValue>
        <fullName>Nagaland</fullName>
    </customValue>
    <customValue>
        <fullName>Odisha</fullName>
    </customValue>
    <customValue>
        <fullName>Puducherry</fullName>
    </customValue>
    <customValue>
        <fullName>Punjab</fullName>
    </customValue>
    <customValue>
        <fullName>Rajasthan</fullName>
    </customValue>
    <customValue>
        <fullName>Sikkim</fullName>
    </customValue>
    <masterLabel>State Values</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

globalValueSets/Status_Code.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>01</fullName>
    </customValue>
    <customValue>
        <fullName>02</fullName>
    </customValue>
    <customValue>
        <fullName>03</fullName>
    </customValue>
    <customValue>
        <fullName>04</fullName>
    </customValue>
    <customValue>
        <fullName>05</fullName>
    </customValue>
    <customValue>
        <fullName>06</fullName>
    </customValue>
    <customValue>
        <fullName>07</fullName>
    </customValue>
    <customValue>
        <fullName>08</fullName>
    </customValue>
    <customValue>
        <fullName>09</fullName>
    </customValue>
    <customValue>
        <fullName>10</fullName>
    </customValue>
    <customValue>
        <fullName>11</fullName>
    </customValue>
    <customValue>
        <fullName>12</fullName>
    </customValue>
    <customValue>
        <fullName>13</fullName>
    </customValue>
    <customValue>
        <fullName>14</fullName>
    </customValue>
    <customValue>
        <fullName>15</fullName>
    </customValue>
    <customValue>
        <fullName>16</fullName>
    </customValue>
    <customValue>
        <fullName>17</fullName>
    </customValue>
    <customValue>
        <fullName>18</fullName>
    </customValue>
    <customValue>
        <fullName>19</fullName>
    </customValue>
    <customValue>
        <fullName>20</fullName>
    </customValue>
    <customValue>
        <fullName>21</fullName>
    </customValue>
    <customValue>
        <fullName>22</fullName>
    </customValue>
    <customValue>
        <fullName>23</fullName>
    </customValue>
    <customValue>
        <fullName>24</fullName>
    </customValue>
    <customValue>
        <fullName>26</fullName>
    </customValue>
    <customValue>
        <fullName>27</fullName>
    </customValue>
    <customValue>
        <fullName>29</fullName>
    </customValue>
    <customValue>
        <fullName>30</fullName>
    </customValue>
    <customValue>
        <fullName>31</fullName>
    </customValue>
    <customValue>
        <fullName>32</fullName>
    </customValue>
    <masterLabel>Status Code</masterLabel>
</GlobalValueSet>

classes/MarkInactiveAddressAndTaxControllerTest.cls
@isTest(SeeAllData=true)
class MarkInactiveAddressAndTaxControllerTest {

    @isTest
    public static void testMarkInactive(){
        
        Account acc= new Account();
        acc.Name='Test234';
        acc.BU__c='India - IN1';
        acc.CurrencyIsoCode='INR'; 
        acc.Industry='Agriculture';
        acc.Billing_Address_Line_1__c='test23';
        acc.Billing_City__c='test23';
        acc.Same_As_The_Billing_Address__c=true;
        acc.Billing_Country__c='test23';
        acc.Billing_State__c='test23';
        acc.Billing_ZIP_Postal_Code__c='test23'; 
        insert acc;
        
        Id taxRecordTypeId = Schema.SObjectType.India_GST__c.getRecordTypeInfosByName().get('Tax').getRecordTypeId();
        
        India_GST__c addressAndTaxRecord = new India_GST__c(name='07TESTOTESTB123',Account__c=acc.Id);
        addressAndTaxRecord.Address_Line_1__c='Ground Floor, Corporate One';
        addressAndTaxRecord.City__c ='New Delhi'; 
        addressAndTaxRecord.Global_Country__c='INDIA';
        addressAndTaxRecord.State_County__c ='Delhi';
        addressAndTaxRecord.State_Code__c ='07';
        addressAndTaxRecord.ZIP_Postal_Code__c='110076';
        addressAndTaxRecord.Taxpayer_Type__c='EXPWOP';
        addressAndTaxRecord.Type__c = 'GST';
        addressAndTaxRecord.RecordTypeId = taxRecordTypeId;
        
        insert addressAndTaxRecord;
        
        Test.startTest();
        
        MarkInactiveAddressAndTaxController.getAddressAndTaxType(addressAndTaxRecord.Id);
        MarkInactiveAddressAndTaxController.markInactive(addressAndTaxRecord.Id);

        Test.stopTest();

    }
}