force-app/main/objects/Account.object
<CustomObject>
    <fields>
        <fullName>BU__c</fullName>
        <label>BU</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Master_BUs</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Billing_Address_Line_1__c</fullName>
        <inlineHelpText>If the address goes over more than one line then please use Address Line 2 and Address Line 3. This formatting will display on any Customer facing documents.</inlineHelpText>
        <label>Billing Address Line 1</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_City__c</fullName>
        <label>Billing City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_Country__c</fullName>
        <label>Billing Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AFGHANISTAN</fullName>
                </value>
                <value>
                    <fullName>ALBANIA</fullName>
                </value>
                <value>
                    <fullName>ALDERNEY</fullName>
                </value>
                <value>
                    <fullName>ALGERIA</fullName>
                </value>
                <value>
                    <fullName>AMERICAN SAMOA</fullName>
                </value>
                <value>
                    <fullName>ANDORRA</fullName>
                </value>
                <value>
                    <fullName>ANGOLA</fullName>
                </value>
                <value>
                    <fullName>ANGUILLA</fullName>
                </value>
                <value>
                    <fullName>ANTARCTICA</fullName>
                </value>
                <value>
                    <fullName>ANTIGUA AND BARBUDA</fullName>
                </value>
                <value>
                    <fullName>ARGENTINA</fullName>
                </value>
                <value>
                    <fullName>ARMENIA</fullName>
                </value>
                <value>
                    <fullName>ARUBA</fullName>
                </value>
                <value>
                    <fullName>AUSTRALIA</fullName>
                </value>
                <value>
                    <fullName>AUSTRIA</fullName>
                </value>
                <value>
                    <fullName>AZERBAIJAN</fullName>
                </value>
                <value>
                    <fullName>BAHAMAS</fullName>
                </value>
                <value>
                    <fullName>BAHRAIN</fullName>
                </value>
                <value>
                    <fullName>BANGLADESH</fullName>
                </value>
                <value>
                    <fullName>BARBADOS</fullName>
                </value>
                <value>
                    <fullName>BELARUS</fullName>
                </value>
                <value>
                    <fullName>BELGIUM</fullName>
                </value>
                <value>
                    <fullName>BELIZE</fullName>
                </value>
                <value>
                    <fullName>BENIN</fullName>
                </value>
                <value>
                    <fullName>BERMUDA</fullName>
                </value>
                <value>
                    <fullName>BHUTAN</fullName>
                </value>
                <value>
                    <fullName>BOLIVIA</fullName>
                </value>
                <value>
                    <fullName>BOSNIA AND HERZEGOWINA</fullName>
                </value>
                <value>
                    <fullName>BOTSWANA</fullName>
                </value>
                <value>
                    <fullName>BOUVET ISLAND</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Billing_State__c</fullName>
        <inlineHelpText>If State is required, please enter as two alphanumeric characters, e.g. GA instead of Georgia</inlineHelpText>
        <label>Billing State/County</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_ZIP_Postal_Code__c</fullName>
        <label>Billing ZIP/Postal Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>1. Not yet trading with SHL - (definition - the account is new and/or has no trading history with SHL to date)
2. Trading with SHL - (definition - the account has sales recorded with SHL in the last 2 years)
3. Ceased Trading with SHL - (definition - the account has not traded with SHL in the past 12 months but has previously.) 
4. Dead - (Gone out of Business) (definition - The Account for whatever reason is no longer a trading entity)
Previous Values
1. Active with SHL (definition - The account has a track record of sales and/or opportunities managed in the last 2 years)
2. Inactive with SHL (definition - The account is still a trading account but there has been no activity with SHL (sales or opportunities managed) in the last 2 years)</description>
        <inlineHelpText>Status indicates if Account is approved or not. If you believe an unapproved Account should be Approved, Submit for Approval.</inlineHelpText>
        <label>Account Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Unapproved</fullName>
                    <default>true</default>
                    <label>Unapproved</label>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Unapproved - Out of Business</fullName>
                </value>
                <value>
                    <fullName>Unapproved - Trade Not Allowed</fullName>
                </value>
                <value>
                    <fullName>Unapproved - Duplicate</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

force-app/main/objects/AutomaticJobCreation__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>MS_Line_of_Business__c</fullName>
        <label>MS - Line of Business</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>AutomaticJobCreation</label>
</CustomObject>

force-app/main/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Forecast_Category__c</fullName>
        <inlineHelpText>Please select “Commit” if you want this opportunity to be counted in your Forecast number. Please select Pipeline or Renewal at Risk if you do not want it to be included.</inlineHelpText>
        <label>Forecast Category</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Business_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Commit</fullName>
                </value>
                <value>
                    <fullName>Pipeline</fullName>
                    <default>true</default>
                    <label>Pipeline</label>
                </value>
                <value>
                    <fullName>Renewal at Risk</fullName>
                </value>
                <value>
                    <fullName>Forecast</fullName>
                    <isActive>false</isActive>
                    <label>Forecast</label>
                </value>
                <value>
                    <fullName>Parked</fullName>
                    <isActive>false</isActive>
                    <label>Parked</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TM_Phase__c</fullName>
        <description>This field is used to replace the existing proposition field.</description>
        <inlineHelpText>Select the Client Interest that best defines the scope of the client’s project, or Combined if the project is mixed.</inlineHelpText>
        <label>Client Interest</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Talent Acquisition</fullName>
                </value>
                <value>
                    <fullName>Talent Management</fullName>
                </value>
                <value>
                    <fullName>TAandTMCombined</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

force-app/main/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>MS_Product__c</fullName>
        <formula>PricebookEntry.Product2.MS_Product__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>MS Product</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>TEXT(PricebookEntry.Product2.Status__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
</CustomObject>

force-app/main/objects/Order.object
<CustomObject>
    <fields>
        <fullName>BU__c</fullName>
        <formula>TEXT(Account.BU__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>BU</label>
        <type>Text</type>
    </fields>
</CustomObject>

force-app/main/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>MS_Product__c</fullName>
        <defaultValue>false</defaultValue>
        <label>MS Product</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Revenue_Category__c</fullName>
        <label>Stream</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Professional Services</fullName>
                </value>
                <value>
                    <fullName>Managed Services</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Product subscription</fullName>
                </value>
                <value>
                    <fullName>Product in advance</fullName>
                </value>
                <value>
                    <fullName>Product in arrears</fullName>
                </value>
                <value>
                    <fullName>Professional Services (Public Training)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Beta</fullName>
                </value>
                <value>
                    <fullName>Revenue Ready</fullName>
                    <default>true</default>
                    <label>Revenue Ready</label>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
                <value>
                    <fullName>End of Life</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

force-app/main/objects/Trigger_Activation__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This List is used to activate/deactivate trigger while deployment.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Trigger Activation</label>
</CustomObject>

classes/TopUpOpportunityControllerTest.cls
@IsTest
public class TopUpOpportunityControllerTest {


    private static Id oppId;

    @TestSetup
    static void setupData() {

        insert new AutomaticJobCreation__c(
            Name = 'Values',
            MS_Line_of_Business__c = 'TestType'
        );

        insert new List<Trigger_Activation__c>{
            new Trigger_Activation__c(Name='Account_Trigger', Active__c=true),
            new Trigger_Activation__c(Name='Contact_Trigger', Active__c=true),
            new Trigger_Activation__c(Name='OpportunityLineItem_Trigger', Active__c=true),
            new Trigger_Activation__c(Name='Opportunity_Trigger', Active__c=true),
            new Trigger_Activation__c(Name='PricebookEntry_Trigger', Active__c=true),
            new Trigger_Activation__c(Name='Product2_Trigger', Active__c=true),
            new Trigger_Activation__c(Name='Pricebook2_Trigger', Active__c=true)
        };

        Account acc = new Account(
            Name = 'Test Account',
            Status__c = 'Approved',
            Billing_Address_Line_1__c = 'Test',
            Billing_City__c = 'City',
            Billing_Country__c = 'India',
            Billing_State__c = 'State',
            Billing_ZIP_Postal_Code__c = '1100110',
            Industry = 'Legal',
            BU__c = 'Hong Kong - HK1'
        );
        insert acc;


        Id stdPbId = Test.getStandardPricebookId();

        Product2 prod = new Product2(
            Name = 'Test Product',
            IsActive = true,
            Revenue_Category__c = 'Training',
            MS_Product__c = true,
            Status__c = 'Revenue Ready'
        );
        insert prod;

        PricebookEntry pbe = new PricebookEntry(
            Pricebook2Id = stdPbId,
            Product2Id = prod.Id,
            UnitPrice = 1000,
            IsActive = true,
            CurrencyIsoCode = 'GBP'
        );
        insert pbe;

        Opportunity opp = new Opportunity(
            Name = 'Original Opp',
            AccountId = acc.Id,
            CloseDate = Date.today(),
            Pricebook2Id = stdPbId,
            CurrencyIsoCode = 'GBP',
            Forecast_Category__c = 'Commit',
            TM_Phase__c = 'Test',
            Proposition__c = 'Test',
            Price_Increase_Percentage__c = 10,
            Variation_Opportunity__c = 'Yes',
            Variation_Reason__c = 'Addition to order',
            StageName = 'Information Gathering',
            Business_Type__c = 'Top Up / Addition'
        );
        insert opp;

        oppId = opp.Id;

        List<OpportunityLineItem> oliList = new List<OpportunityLineItem>{

            new OpportunityLineItem(
                OpportunityId = opp.Id,
                PricebookEntryId = pbe.Id,
                Quantity = 1,
                TotalPrice = 1000,
                RenewableNew__c = 'Ongoing',
                Solution_Cap__c = 2,
                Package__c = 'Package A',
                Product_Name__c = 'Test Product A',
                Basis_of_Fees__c = 'Standard',
                Proposition__c = 'Test Proposition',
                Platform__c = 'Test Platform',
                Debooked_Quantity__c = 0,
                Debooked_Sales_Price__c = 0,
                Number_of_Services__c = 1
            ),

            new OpportunityLineItem(
                OpportunityId = opp.Id,
                PricebookEntryId = pbe.Id,
                Quantity = 1,
                TotalPrice = 2000,
                RenewableNew__c = 'Ongoing',
                Solution_Cap__c = 3,
                Package__c = 'Package B',
                Product_Name__c = 'Test Product B',
                Basis_of_Fees__c = 'Standard',
                Proposition__c = 'Test Proposition',
                Platform__c = 'Test Platform',
                Debooked_Quantity__c = 0,
                Debooked_Sales_Price__c = 0,
                Number_of_Services__c = 2
            ),

            new OpportunityLineItem(
                OpportunityId = opp.Id,
                PricebookEntryId = pbe.Id,
                Quantity = 1,
                TotalPrice = 500,
                RenewableNew__c = 'Ongoing',
                Solution_Cap__c = 1,
                Package__c = 'Package A'
            )
        };

        insert oliList;
    }


    private static Opportunity getOpp() {
        return [SELECT Id FROM Opportunity LIMIT 1];
    }



    @IsTest
    static void testGetOpportunityLine_UpdateTrue() {

        Test.startTest();
        TopUpOpportunityController.TopUpInformationWrapper result =
            TopUpOpportunityController.getOpportunityLine(getOpp().Id, true);
        Test.stopTest();

        System.assertNotEquals(null, result);

        for (TopUpOpportunityController.SolutionWrapper sw : result.solutionList) {

            if (sw.solutionName == 'Package A') {
                System.assertEquals(1500, sw.solutionTotalValueOnOriginal);
                System.assertEquals(2, sw.oppLines.size());
            }

            if (sw.solutionName == 'Package B') {
                System.assertEquals(2000, sw.solutionTotalValueOnOriginal);
                System.assertEquals(1, sw.oppLines.size());
            }
        }
    }

    @IsTest
    static void testGetOpportunityLine_UpdateFalse() {

        Test.startTest();
        TopUpOpportunityController.TopUpInformationWrapper result =
            TopUpOpportunityController.getOpportunityLine(getOpp().Id, false);
        Test.stopTest();

        for (TopUpOpportunityController.SolutionWrapper sw : result.solutionList) {
            System.assertEquals(0, sw.solutionCap);
            System.assertEquals(0, sw.solutionTotalValue);
        }
    }

    @IsTest
    static void testCreateTopUpOpportunity() {

        TopUpOpportunityController.TopUpInformationWrapper data =
            TopUpOpportunityController.getOpportunityLine(getOpp().Id, true);

        for (TopUpOpportunityController.SolutionWrapper sw : data.solutionList) {
            sw.solutionCap = sw.solutionCapOnOriginal + 1;
        }

        Test.startTest();
        TopUpOpportunityController.returnMessageWrapper response =
            TopUpOpportunityController.createTopUpOpportunity(data, getOpp().Id);
        Test.stopTest();

        System.assertNotEquals(null, response);
    }

    @IsTest
    static void testUpdateTopUpOpportunityLines() {

        TopUpOpportunityController.TopUpInformationWrapper data =
            TopUpOpportunityController.getOpportunityLine(getOpp().Id, true);

        for (TopUpOpportunityController.SolutionWrapper sw : data.solutionList) {
            sw.solutionCap = sw.solutionCapOnOriginal + 2;
        }

        Test.startTest();
        TopUpOpportunityController.returnMessageWrapper response =
            TopUpOpportunityController.updateTopUpOpportunityLines(data, getOpp().Id);
        Test.stopTest();

        System.assertNotEquals(null, response);
    }

    @IsTest
    static void testCreateTopUpOpportunity_Exception() {

        TopUpOpportunityController.TopUpInformationWrapper data =
            new TopUpOpportunityController.TopUpInformationWrapper();
        data.solutionList = null;

        Test.startTest();
        TopUpOpportunityController.returnMessageWrapper response =
            TopUpOpportunityController.createTopUpOpportunity(data, oppId);
        Test.stopTest();

        System.assertEquals('Error', response.MessageType);
    }
}