force-app/main/objects/Account.object
<CustomObject>
    <fields>
        <fullName>BU__c</fullName>
        <label>BU</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Master_BUs</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Billing_Address_Line_1__c</fullName>
        <inlineHelpText>If the address goes over more than one line then please use Address Line 2 and Address Line 3. This formatting will display on any Customer facing documents.</inlineHelpText>
        <label>Billing Address Line 1</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_City__c</fullName>
        <label>Billing City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_Country__c</fullName>
        <label>Billing Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AFGHANISTAN</fullName>
                </value>
                <value>
                    <fullName>ALBANIA</fullName>
                </value>
                <value>
                    <fullName>ALDERNEY</fullName>
                </value>
                <value>
                    <fullName>ALGERIA</fullName>
                </value>
                <value>
                    <fullName>AMERICAN SAMOA</fullName>
                </value>
                <value>
                    <fullName>ANDORRA</fullName>
                </value>
                <value>
                    <fullName>ANGOLA</fullName>
                </value>
                <value>
                    <fullName>ANGUILLA</fullName>
                </value>
                <value>
                    <fullName>ANTARCTICA</fullName>
                </value>
                <value>
                    <fullName>ANTIGUA AND BARBUDA</fullName>
                </value>
                <value>
                    <fullName>ARGENTINA</fullName>
                </value>
                <value>
                    <fullName>ARMENIA</fullName>
                </value>
                <value>
                    <fullName>ARUBA</fullName>
                </value>
                <value>
                    <fullName>AUSTRALIA</fullName>
                </value>
                <value>
                    <fullName>AUSTRIA</fullName>
                </value>
                <value>
                    <fullName>AZERBAIJAN</fullName>
                </value>
                <value>
                    <fullName>BAHAMAS</fullName>
                </value>
                <value>
                    <fullName>BAHRAIN</fullName>
                </value>
                <value>
                    <fullName>BANGLADESH</fullName>
                </value>
                <value>
                    <fullName>BARBADOS</fullName>
                </value>
                <value>
                    <fullName>BELARUS</fullName>
                </value>
                <value>
                    <fullName>BELGIUM</fullName>
                </value>
                <value>
                    <fullName>BELIZE</fullName>
                </value>
                <value>
                    <fullName>BENIN</fullName>
                </value>
                <value>
                    <fullName>BERMUDA</fullName>
                </value>
                <value>
                    <fullName>BHUTAN</fullName>
                </value>
                <value>
                    <fullName>BOLIVIA</fullName>
                </value>
                <value>
                    <fullName>BOSNIA AND HERZEGOWINA</fullName>
                </value>
                <value>
                    <fullName>BOTSWANA</fullName>
                </value>
                <value>
                    <fullName>BOUVET ISLAND</fullName>
                </value>
                <value>
                    <fullName>INDIA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Billing_State__c</fullName>
        <inlineHelpText>If State is required, please enter as two alphanumeric characters, e.g. GA instead of Georgia</inlineHelpText>
        <label>Billing State/County</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_ZIP_Postal_Code__c</fullName>
        <label>Billing ZIP/Postal Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Global_Billing_Country__c</fullName>
        <description>This is the new field created for making the country value set consistent over all modules in Salesforce.</description>
        <label>Billing Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Global_Country_Picklist</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <formula>TEXT(Territory__r.Region__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Region</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Same_As_The_Billing_Address__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Same As The Billing Address</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Territory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Territory</label>
        <lookupFilter>
            <active>false</active>
            <errorMessage>Territory associated with an account should be active</errorMessage>
            <filterItems>
                <field>Territory__c.Is_Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Territory__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

force-app/main/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Actual_Contract_Duration__c</fullName>
        <label>Actual Contract Duration</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Business_Type__c</fullName>
        <description>Choose the Opportunity Type that best describes the type of business pursued.  
Reboost should only be used with In-Advance clients. 
Cross-sell is simply New Business with a client that has a current commercial relationship.</description>
        <label>Opportunity Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Expansion</fullName>
                </value>
                <value>
                    <fullName>Renewal</fullName>
                </value>
                <value>
                    <fullName>Debooking</fullName>
                    <label>Debooking / Adjustment</label>
                </value>
                <value>
                    <fullName>Extension</fullName>
                </value>
                <value>
                    <fullName>In Arrears</fullName>
                </value>
                <value>
                    <fullName>In Advance</fullName>
                </value>
                <value>
                    <fullName>Managed Services</fullName>
                </value>
                <value>
                    <fullName>Professional Services: non-subscription</fullName>
                </value>
                <value>
                    <fullName>Top Up / Addition</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Forecast_Category__c</fullName>
        <inlineHelpText>Please select “Commit” if you want this opportunity to be counted in your Forecast number. Please select Pipeline or Renewal at Risk if you do not want it to be included.</inlineHelpText>
        <label>Forecast Category</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Business_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Commit</fullName>
                </value>
                <value>
                    <fullName>Pipeline</fullName>
                    <default>true</default>
                    <label>Pipeline</label>
                </value>
                <value>
                    <fullName>Renewal at Risk</fullName>
                </value>
                <value>
                    <fullName>Forecast</fullName>
                    <isActive>false</isActive>
                    <label>Forecast</label>
                </value>
                <value>
                    <fullName>Parked</fullName>
                    <isActive>false</isActive>
                    <label>Parked</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity_Deal_Year__c</fullName>
        <defaultValue>1</defaultValue>
        <description>Current Deal Year of Opportunity</description>
        <label>Opportunity Year</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Original_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Original Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Variation / Renewal Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Products_Discount__c</fullName>
        <label>Contract Product Discount</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Renewal_Date__c</fullName>
        <inlineHelpText>This date is calculated from the Contract End Date + 1 day and signifies the true date that the next Renewal is due to start on.</inlineHelpText>
        <label>Renewal Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Renewal_Opportunity__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Auto-Created Renewal</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sales_Price_in_USD__c</fullName>
        <description>Used in Account Plan to show USD vaue on contract details.</description>
        <formula>IF(
TEXT(CurrencyIsoCode) = &apos;USD&apos;, Amount,
Amount / CURRENCYRATE(TEXT(CurrencyIsoCode))*CURRENCYRATE(&apos;USD&apos;))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sales Price in USD</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Services_Discount__c</fullName>
        <label>Contract Service Discount</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
</CustomObject>

force-app/main/objects/Territory__c.object
<CustomObject>
    <fields>
        <fullName>CRO__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CRO</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Territories8</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Commercial_Director__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Commercial Director</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Territories6031</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FBP_Director__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>FBP Director</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Territories7</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FBP_Team__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>FBP Team</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Territories5wOs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MD__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Managing Director</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Territories9</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Region</valueSetName>
        </valueSet>
    </fields>
    <label>Territory</label>
    <nameField>
        <label>Territory</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/objects/Trigger_Activation__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This List is used to activate/deactivate trigger while deployment.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Trigger Activation</label>
</CustomObject>

globalValueSets/Global_Country_Picklist.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>AFGHANISTAN</fullName>
    </customValue>
    <customValue>
        <fullName>ALBANIA</fullName>
    </customValue>
    <customValue>
        <fullName>ALDERNEY</fullName>
    </customValue>
    <customValue>
        <fullName>ALGERIA</fullName>
    </customValue>
    <customValue>
        <fullName>AMERICAN SAMOA</fullName>
    </customValue>
    <customValue>
        <fullName>ANDORRA</fullName>
    </customValue>
    <customValue>
        <fullName>ANGOLA</fullName>
    </customValue>
    <customValue>
        <fullName>ANGUILLA</fullName>
    </customValue>
    <customValue>
        <fullName>ANTARCTICA</fullName>
    </customValue>
    <customValue>
        <fullName>ANTIGUA AND BARBUDA</fullName>
    </customValue>
    <customValue>
        <fullName>ARGENTINA</fullName>
    </customValue>
    <customValue>
        <fullName>ARMENIA</fullName>
    </customValue>
    <customValue>
        <fullName>ARUBA</fullName>
    </customValue>
    <customValue>
        <fullName>AUSTRALIA</fullName>
    </customValue>
    <customValue>
        <fullName>AUSTRIA</fullName>
    </customValue>
    <customValue>
        <fullName>AZERBAIJAN</fullName>
    </customValue>
    <customValue>
        <fullName>BAHAMAS</fullName>
    </customValue>
    <customValue>
        <fullName>BAHRAIN</fullName>
    </customValue>
    <customValue>
        <fullName>BANGLADESH</fullName>
    </customValue>
    <customValue>
        <fullName>BARBADOS</fullName>
    </customValue>
    <customValue>
        <fullName>BELARUS</fullName>
    </customValue>
    <customValue>
        <fullName>BELGIUM</fullName>
    </customValue>
    <customValue>
        <fullName>BELIZE</fullName>
    </customValue>
    <customValue>
        <fullName>BENIN</fullName>
    </customValue>
    <customValue>
        <fullName>BERMUDA</fullName>
    </customValue>
    <customValue>
        <fullName>BHUTAN</fullName>
    </customValue>
    <customValue>
        <fullName>BOLIVIA</fullName>
    </customValue>
    <customValue>
        <fullName>BOSNIA AND HERZEGOWINA</fullName>
    </customValue>
    <customValue>
        <fullName>BOTSWANA</fullName>
    </customValue>
    <customValue>
        <fullName>BOUVET ISLAND</fullName>
    </customValue>
    <customValue>
        <fullName>INDIA</fullName>
    </customValue>
    <description>used as a global picklist over all the modules in salesforce</description>
    <masterLabel>Global Country Picklist</masterLabel>
</GlobalValueSet>

globalValueSets/Master_BUs.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Abu Dhabi - AD1</fullName>
    </customValue>
    <customValue>
        <fullName>Australia - AU1</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium SPS - BE5</fullName>
    </customValue>
    <customValue>
        <fullName>Canada - CA1</fullName>
    </customValue>
    <customValue>
        <fullName>China - CN1</fullName>
    </customValue>
    <customValue>
        <fullName>Denmark - DK1</fullName>
    </customValue>
    <customValue>
        <fullName>Finland - FI1</fullName>
    </customValue>
    <customValue>
        <fullName>France SPS - FR5</fullName>
    </customValue>
    <customValue>
        <fullName>Germany SPS - DE5</fullName>
    </customValue>
    <customValue>
        <fullName>Hong Kong - HK1</fullName>
    </customValue>
    <customValue>
        <fullName>India - IN1</fullName>
    </customValue>
    <customValue>
        <fullName>Italy - IT1</fullName>
    </customValue>
    <customValue>
        <fullName>Middle East - ME1</fullName>
    </customValue>
    <customValue>
        <fullName>Netherlands SPS - NL5</fullName>
    </customValue>
    <customValue>
        <fullName>New Zealand - NZ1</fullName>
    </customValue>
    <customValue>
        <fullName>Norway - NO1</fullName>
    </customValue>
    <customValue>
        <fullName>Philippines - PH1</fullName>
    </customValue>
    <customValue>
        <fullName>Saudi Arabia - SA5</fullName>
    </customValue>
    <customValue>
        <fullName>Singapore - SG1</fullName>
    </customValue>
    <customValue>
        <fullName>South Africa - ZA1</fullName>
    </customValue>
    <customValue>
        <fullName>Sweden - SE1</fullName>
    </customValue>
    <customValue>
        <fullName>Switzerland - CH1</fullName>
    </customValue>
    <customValue>
        <fullName>UK - UK1</fullName>
    </customValue>
    <customValue>
        <fullName>US - US5</fullName>
    </customValue>
    <customValue>
        <fullName>Indonesia - ID1</fullName>
    </customValue>
    <customValue>
        <fullName>Asia Pac	India</fullName>
        <isActive>false</isActive>
        <label>Asia Pac	India</label>
    </customValue>
    <customValue>
        <fullName>Asia Pac	Singapore</fullName>
        <isActive>false</isActive>
        <label>Asia Pac	Singapore</label>
    </customValue>
    <customValue>
        <fullName>Asia Pac	AP Region</fullName>
        <isActive>false</isActive>
        <label>Asia Pac	AP Region</label>
    </customValue>
    <customValue>
        <fullName>UK	  - UK1</fullName>
        <isActive>false</isActive>
        <label>UK	  - UK1</label>
    </customValue>
    <customValue>
        <fullName>Head Office  - H50</fullName>
        <isActive>false</isActive>
        <label>Head Office  - H50</label>
    </customValue>
    <masterLabel>Master BUs</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

globalValueSets/Region.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>ANZ</fullName>
    </customValue>
    <customValue>
        <fullName>Core AMS</fullName>
    </customValue>
    <customValue>
        <fullName>Core EU</fullName>
    </customValue>
    <customValue>
        <fullName>Core UKI</fullName>
    </customValue>
    <customValue>
        <fullName>Distributors</fullName>
    </customValue>
    <customValue>
        <fullName>Enterprise AMS</fullName>
    </customValue>
    <customValue>
        <fullName>Enterprise North EU</fullName>
    </customValue>
    <customValue>
        <fullName>Enterprise South EU</fullName>
    </customValue>
    <customValue>
        <fullName>Enterprise UKI</fullName>
    </customValue>
    <customValue>
        <fullName>Growth UK/EU</fullName>
    </customValue>
    <customValue>
        <fullName>Hong Kong</fullName>
    </customValue>
    <customValue>
        <fullName>India</fullName>
    </customValue>
    <customValue>
        <fullName>Middle East</fullName>
    </customValue>
    <customValue>
        <fullName>NB AMS</fullName>
    </customValue>
    <customValue>
        <fullName>NB Core</fullName>
    </customValue>
    <customValue>
        <fullName>NB Enterprise</fullName>
    </customValue>
    <customValue>
        <fullName>NB Partner</fullName>
    </customValue>
    <customValue>
        <fullName>Other AMS</fullName>
    </customValue>
    <customValue>
        <fullName>Partners AMS</fullName>
    </customValue>
    <customValue>
        <fullName>Philippines</fullName>
    </customValue>
    <customValue>
        <fullName>Singapore</fullName>
    </customValue>
    <customValue>
        <fullName>South Africa</fullName>
    </customValue>
    <customValue>
        <fullName>Strategic EU</fullName>
    </customValue>
    <customValue>
        <fullName>Strategic UKI</fullName>
    </customValue>
    <customValue>
        <fullName>China East</fullName>
    </customValue>
    <customValue>
        <fullName>China North</fullName>
    </customValue>
    <customValue>
        <fullName>China Partner</fullName>
    </customValue>
    <customValue>
        <fullName>China South</fullName>
    </customValue>
    <customValue>
        <fullName>China Enterprise</fullName>
    </customValue>
    <customValue>
        <fullName>China Core</fullName>
    </customValue>
    <customValue>
        <fullName>AMS</fullName>
    </customValue>
    <masterLabel>Region</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

classes/TerritoryApprovalResolverTest.cls
@IsTest
public class TerritoryApprovalResolverTest {

    static Id oppId;

    @TestSetup
    static void setupData(){

        insert new List<Trigger_Activation__c>{
            new Trigger_Activation__c(Name='Account_Trigger',Active__c=true),
            new Trigger_Activation__c(Name='Task_Trigger',Active__c=true),
            new Trigger_Activation__c(Name='User_Trigger',Active__c=true),
            new Trigger_Activation__c(Name='Opportunity_Trigger',Active__c=true),
            new Trigger_Activation__c(Name='Territory_Trigger',Active__c=true)
        };

        Profile p = [SELECT Id FROM Profile WHERE Name='Standard User' LIMIT 1];

     User directorUser = new User(
    Alias='diru',
    Email='director@test.com',
    EmailEncodingKey='UTF-8',
    LastName='Director',
    LanguageLocaleKey='en_US',
    LocaleSidKey='en_US',
    ProfileId=p.Id,
    TimeZoneSidKey='Asia/Kolkata',
    UserName='director' + System.currentTimeMillis() + '@test.com'
);

User croUser = new User(
    Alias='crou',
    Email='cro@test.com',
    EmailEncodingKey='UTF-8',
    LastName='CRO',
    LanguageLocaleKey='en_US',
    LocaleSidKey='en_US',
    ProfileId=p.Id,
    TimeZoneSidKey='Asia/Kolkata',
    UserName='cro' + System.currentTimeMillis() + '@test.com'
);

User mdUser = new User(
    Alias='mdu',
    Email='md@test.com',
    EmailEncodingKey='UTF-8',
    LastName='MD',
    LanguageLocaleKey='en_US',
    LocaleSidKey='en_US',
    ProfileId=p.Id,
    TimeZoneSidKey='Asia/Kolkata',
    UserName='md' + System.currentTimeMillis() + '@test.com'
);
        User FBPUser = new User(
    Alias='FBP',
    Email='fbp@test.com',
    EmailEncodingKey='UTF-8',
    LastName='FBP',
    LanguageLocaleKey='en_US',
    LocaleSidKey='en_US',
    ProfileId=p.Id,
    TimeZoneSidKey='Asia/Kolkata',
    UserName='fbp' + System.currentTimeMillis() + '@test.com'
);
        User fbpDUser = new User(
    Alias='fbpD',
    Email='fbpD@test.com',
    EmailEncodingKey='UTF-8',
    LastName='fbpD',
    LanguageLocaleKey='en_US',
    LocaleSidKey='en_US',
    ProfileId=p.Id,
    TimeZoneSidKey='Asia/Kolkata',
    UserName='fbpD' + System.currentTimeMillis() + '@test.com'
);

insert new List<User>{directorUser, croUser, mdUser,FBPUser,fbpDUser};

Territory__c terr = new Territory__c(
    Name='Test Territory',
    Region__c='AMS',
    Commercial_Director__c = directorUser.Id,
    CRO__c = croUser.Id,
    MD__c = mdUser.Id,
    FBP_Team__c = FBPUser.Id,
    FBP_Director__c = fbpDUser.Id
);
insert terr;

        Account acc = new Account(
            Name='Test Account',
            BU__c='UK - UK1',
            CurrencyIsoCode='USD',
            Industry='Agriculture',
            Billing_Address_Line_1__c='Line1',
            Billing_City__c='City',
            Same_As_The_Billing_Address__c=true,
            Billing_Country__c='INDIA',
            Billing_State__c='State',
            Billing_ZIP_Postal_Code__c='Zip',
            Global_Billing_Country__c='AFGHANISTAN',
            Territory__c=terr.Id
        );
        
        insert acc;
        
        Opportunity originalOpp = new Opportunity(
            Name = 'Original Opp',
            AccountId = acc.Id,
            CloseDate = Date.today(),
            StageName = 'Prospecting',
            Amount = 20000000
        );
        insert originalOpp;

        Opportunity opp = new Opportunity(
            Name='Test Opportunity',
            AccountId=acc.Id,
            CloseDate=Date.today(),
            StageName='Prospecting',
            Amount=18000000,
            Products_Discount__c=10,
            Services_Discount__c=5,
            Business_Type__c='Renewal',
            Actual_Contract_Duration__c=12,
            Forecast_Category__c='Pipeline',
            Opportunity_Deal_Year__c=1,
            Renewal_Date__c = Date.newInstance(2026, 12, 12),
            Renewal_Opportunity__c=true,
             Original_Opportunity__c = originalOpp.Id
         
        );
        insert opp;
        acc = [SELECT Id, Territory__c FROM Account WHERE Id = :acc.Id];
        originalOpp = [SELECT Id FROM Opportunity WHERE Id = :originalOpp.Id];
        opp = [SELECT Id FROM Opportunity WHERE Id = :opp.Id];
		oppId = opp.Id;

    }


    private static TerritoryApprovalResolver.InputWrapper createInput(String status, String approverField,Id oppId){

        TerritoryApprovalResolver.InputWrapper input = new TerritoryApprovalResolver.InputWrapper();
        input.recordId = oppId;
        input.discountApprovalStatus = status;
        input.originalApprovers = approverField;

        return input;
    }


    @IsTest
    static void testSubmittedForApproval(){
	Opportunity opp = [Select id,Business_Type__c,Renewal_Opportunity__c, Renewal_Date__c,Opportunity_Deal_Year__c,Sales_Price_in_USD__c from opportunity limit 1];

        System.debug('DEBUGG FULL OPP1: ' + opp);
        
        TerritoryApprovalResolver.InputWrapper input =
            createInput('Submitted for Approval','Commercial_Director__c',opp.Id);

        List<TerritoryApprovalResolver.InputWrapper> inputs =
            new List<TerritoryApprovalResolver.InputWrapper>{input};

        Test.startTest();

        List<TerritoryApprovalResolver.OutputWrapper> result =
            TerritoryApprovalResolver.resolveApproval(inputs);

        Test.stopTest();

        System.assert(result.size() > 0);
    }


    @IsTest
    static void testEscalatedLevel1(){
	Opportunity opp = [Select id,Business_Type__c,Renewal_Opportunity__c, Renewal_Date__c,Opportunity_Deal_Year__c,Sales_Price_in_USD__c from opportunity limit 1];

        
        System.debug('DEBUGG FULL OPP2: ' + opp);
        
        TerritoryApprovalResolver.InputWrapper input =
            createInput('Escalated Level 1','CRO__c',opp.Id);

        List<TerritoryApprovalResolver.InputWrapper> inputs =
            new List<TerritoryApprovalResolver.InputWrapper>{input};

        Test.startTest();

        List<TerritoryApprovalResolver.OutputWrapper> result =
            TerritoryApprovalResolver.resolveApproval(inputs);

        Test.stopTest();

        System.assert(result.size() > 0);
    }


    @IsTest
    static void testEscalatedLevel2(){
	Opportunity opp = [Select id,Business_Type__c,Renewal_Opportunity__c, Renewal_Date__c,Opportunity_Deal_Year__c,Sales_Price_in_USD__c from opportunity limit 1];
       
        System.debug('DEBUGG FULL OPP3: ' + opp);
        
        TerritoryApprovalResolver.InputWrapper input =
            createInput('Escalated Level 2','MD__c',opp.Id);

        List<TerritoryApprovalResolver.InputWrapper> inputs =
            new List<TerritoryApprovalResolver.InputWrapper>{input};

        Test.startTest();

        List<TerritoryApprovalResolver.OutputWrapper> result =
            TerritoryApprovalResolver.resolveApproval(inputs);

        Test.stopTest();

        System.assert(result.size() > 0);
    }


    @IsTest
    static void testNullInput(){

        Test.startTest();

        List<TerritoryApprovalResolver.OutputWrapper> result =

            TerritoryApprovalResolver.resolveApproval(null);

        Test.stopTest();

        System.assertEquals(0,result.size());
    }
    @IsTest
static void testLowDecreaseScenario(){

	Opportunity opp = [Select id,Business_Type__c,Renewal_Opportunity__c, Renewal_Date__c,Opportunity_Deal_Year__c,Sales_Price_in_USD__c from opportunity limit 1];

    System.debug('DEBUGG FULL OPP4: ' + opp);
    TerritoryApprovalResolver.InputWrapper input =
        createInput(
            'Submitted for Approval',
            'MD__c;FBP_Director__c;FBP_Team__c',
            opp.Id
        );

    List<TerritoryApprovalResolver.InputWrapper> inputs =
        new List<TerritoryApprovalResolver.InputWrapper>{input};

    Test.startTest();

    List<TerritoryApprovalResolver.OutputWrapper> result =
        TerritoryApprovalResolver.resolveApproval(inputs);

    Test.stopTest();

    System.assertNotEquals(null, result[0].MD);
    System.assertNotEquals(null, result[0].FBPDirector);
    System.assertNotEquals(null, result[0].FBPTeam);
}
   
    

}