force-app/main/objects/Account.object
<CustomObject>
    <fields>
        <fullName>BU__c</fullName>
        <label>BU</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Master_BUs</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Billing_Address_Line_1__c</fullName>
        <inlineHelpText>If the address goes over more than one line then please use Address Line 2 and Address Line 3. This formatting will display on any Customer facing documents.</inlineHelpText>
        <label>Billing Address Line 1</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_City__c</fullName>
        <label>Billing City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_Country__c</fullName>
        <label>Billing Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AFGHANISTAN</fullName>
                </value>
                <value>
                    <fullName>ALBANIA</fullName>
                </value>
                <value>
                    <fullName>ALDERNEY</fullName>
                </value>
                <value>
                    <fullName>ALGERIA</fullName>
                </value>
                <value>
                    <fullName>AMERICAN SAMOA</fullName>
                </value>
                <value>
                    <fullName>ANDORRA</fullName>
                </value>
                <value>
                    <fullName>ANGOLA</fullName>
                </value>
                <value>
                    <fullName>ANGUILLA</fullName>
                </value>
                <value>
                    <fullName>ANTARCTICA</fullName>
                </value>
                <value>
                    <fullName>ANTIGUA AND BARBUDA</fullName>
                </value>
                <value>
                    <fullName>ARGENTINA</fullName>
                </value>
                <value>
                    <fullName>ARMENIA</fullName>
                </value>
                <value>
                    <fullName>ARUBA</fullName>
                </value>
                <value>
                    <fullName>AUSTRALIA</fullName>
                </value>
                <value>
                    <fullName>AUSTRIA</fullName>
                </value>
                <value>
                    <fullName>AZERBAIJAN</fullName>
                </value>
                <value>
                    <fullName>BAHAMAS</fullName>
                </value>
                <value>
                    <fullName>BAHRAIN</fullName>
                </value>
                <value>
                    <fullName>BANGLADESH</fullName>
                </value>
                <value>
                    <fullName>BARBADOS</fullName>
                </value>
                <value>
                    <fullName>BELARUS</fullName>
                </value>
                <value>
                    <fullName>BELGIUM</fullName>
                </value>
                <value>
                    <fullName>BELIZE</fullName>
                </value>
                <value>
                    <fullName>BENIN</fullName>
                </value>
                <value>
                    <fullName>BERMUDA</fullName>
                </value>
                <value>
                    <fullName>BHUTAN</fullName>
                </value>
                <value>
                    <fullName>BOLIVIA</fullName>
                </value>
                <value>
                    <fullName>BOSNIA AND HERZEGOWINA</fullName>
                </value>
                <value>
                    <fullName>BOTSWANA</fullName>
                </value>
                <value>
                    <fullName>BOUVET ISLAND</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Billing_State__c</fullName>
        <inlineHelpText>If State is required, please enter as two alphanumeric characters, e.g. GA instead of Georgia</inlineHelpText>
        <label>Billing State/County</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_ZIP_Postal_Code__c</fullName>
        <label>Billing ZIP/Postal Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Buying_Centre_Id__c</fullName>
        <description>Fro regional grouping of the same accounts, this field will be populated by the BI team.</description>
        <label>Buying Centre Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Same_As_The_Billing_Address__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Same As The Billing Address</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>1. Not yet trading with SHL - (definition - the account is new and/or has no trading history with SHL to date)
2. Trading with SHL - (definition - the account has sales recorded with SHL in the last 2 years)
3. Ceased Trading with SHL - (definition - the account has not traded with SHL in the past 12 months but has previously.) 
4. Dead - (Gone out of Business) (definition - The Account for whatever reason is no longer a trading entity)
Previous Values
1. Active with SHL (definition - The account has a track record of sales and/or opportunities managed in the last 2 years)
2. Inactive with SHL (definition - The account is still a trading account but there has been no activity with SHL (sales or opportunities managed) in the last 2 years)</description>
        <inlineHelpText>Status indicates if Account is approved or not. If you believe an unapproved Account should be Approved, Submit for Approval.</inlineHelpText>
        <label>Account Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Unapproved</fullName>
                    <default>true</default>
                    <label>Unapproved</label>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Unapproved - Out of Business</fullName>
                </value>
                <value>
                    <fullName>Unapproved - Trade Not Allowed</fullName>
                </value>
                <value>
                    <fullName>Unapproved - Duplicate</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

force-app/main/objects/Account_Plan__c.object
<CustomObject>
    <description>Module to capture Key Account Plan details</description>
    <fields>
        <fullName>Account_Name__c</fullName>
        <description>This field is used to store the related account for Account Plan</description>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Plans</relationshipLabel>
        <relationshipName>Account_Plans</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Account_Plan_Type__c</fullName>
        <description>Created in Account Plan Phase 4 to determine the type of Account Plan</description>
        <inlineHelpText>This field is used to determine the type of Account Plan</inlineHelpText>
        <label>Account Plan Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Current</fullName>
                    <default>true</default>
                    <label>Current</label>
                </value>
                <value>
                    <fullName>Regional</fullName>
                </value>
                <value>
                    <fullName>Global</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Buying_Centre_Id__c</fullName>
        <description>This is used to identify if an Account Plan is Regional Account Plan .</description>
        <inlineHelpText>This field shows the value of Buying Centre same as on Account if an Account Plan is regional</inlineHelpText>
        <label>Buying Centre Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Account Plan</label>
    <nameField>
        <displayFormat>ACP-{0000}</displayFormat>
        <label>Account Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>BU__c</fullName>
        <formula>text(Account.BU__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>BU</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Status__c</fullName>
        <description>To determine which of our contacts are the actual buyers and which can be marketed to and which we have lost contact with</description>
        <label>Contact Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Deceased</fullName>
                </value>
                <value>
                    <fullName>Left Institution</fullName>
                </value>
                <value>
                    <fullName>Retired</fullName>
                </value>
                <value>
                    <fullName>Active-Invalid Email</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

force-app/main/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Business_Type__c</fullName>
        <description>Choose the Opportunity Type that best describes the type of business pursued.  
Reboost should only be used with In-Advance clients. 
Cross-sell is simply New Business with a client that has a current commercial relationship.</description>
        <label>Opportunity Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Expansion</fullName>
                </value>
                <value>
                    <fullName>Renewal</fullName>
                </value>
                <value>
                    <fullName>Debooking</fullName>
                    <label>Debooking / Adjustment</label>
                </value>
                <value>
                    <fullName>Extension</fullName>
                </value>
                <value>
                    <fullName>In Arrears</fullName>
                </value>
                <value>
                    <fullName>In Advance</fullName>
                </value>
                <value>
                    <fullName>Managed Services</fullName>
                </value>
                <value>
                    <fullName>Professional Services: non-subscription</fullName>
                </value>
                <value>
                    <fullName>Top Up / Addition</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Forecast_Category__c</fullName>
        <inlineHelpText>Please select “Commit” if you want this opportunity to be counted in your Forecast number. Please select Pipeline or Renewal at Risk if you do not want it to be included.</inlineHelpText>
        <label>Forecast Category</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Business_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Commit</fullName>
                </value>
                <value>
                    <fullName>Pipeline</fullName>
                    <default>true</default>
                    <label>Pipeline</label>
                </value>
                <value>
                    <fullName>Renewal at Risk</fullName>
                </value>
                <value>
                    <fullName>Forecast</fullName>
                    <isActive>false</isActive>
                    <label>Forecast</label>
                </value>
                <value>
                    <fullName>Parked</fullName>
                    <isActive>false</isActive>
                    <label>Parked</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TM_Phase__c</fullName>
        <description>This field is used to replace the existing proposition field.</description>
        <inlineHelpText>Select the Client Interest that best defines the scope of the client’s project, or Combined if the project is mixed.</inlineHelpText>
        <label>Client Interest</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Talent Acquisition</fullName>
                </value>
                <value>
                    <fullName>Talent Management</fullName>
                </value>
                <value>
                    <fullName>TAandTMCombined</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

globalValueSets/Master_BUs.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Abu Dhabi - AD1</fullName>
    </customValue>
    <customValue>
        <fullName>Australia - AU1</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium SPS - BE5</fullName>
    </customValue>
    <customValue>
        <fullName>Canada - CA1</fullName>
    </customValue>
    <customValue>
        <fullName>China - CN1</fullName>
    </customValue>
    <customValue>
        <fullName>Denmark - DK1</fullName>
    </customValue>
    <customValue>
        <fullName>Finland - FI1</fullName>
    </customValue>
    <customValue>
        <fullName>France SPS - FR5</fullName>
    </customValue>
    <customValue>
        <fullName>Germany SPS - DE5</fullName>
    </customValue>
    <customValue>
        <fullName>Hong Kong - HK1</fullName>
    </customValue>
    <customValue>
        <fullName>India - IN1</fullName>
    </customValue>
    <customValue>
        <fullName>Italy - IT1</fullName>
    </customValue>
    <customValue>
        <fullName>Middle East - ME1</fullName>
    </customValue>
    <customValue>
        <fullName>Netherlands SPS - NL5</fullName>
    </customValue>
    <customValue>
        <fullName>New Zealand - NZ1</fullName>
    </customValue>
    <customValue>
        <fullName>Norway - NO1</fullName>
    </customValue>
    <customValue>
        <fullName>Philippines - PH1</fullName>
    </customValue>
    <customValue>
        <fullName>Saudi Arabia - SA5</fullName>
    </customValue>
    <customValue>
        <fullName>Singapore - SG1</fullName>
    </customValue>
    <customValue>
        <fullName>South Africa - ZA1</fullName>
    </customValue>
    <customValue>
        <fullName>Sweden - SE1</fullName>
    </customValue>
    <customValue>
        <fullName>Switzerland - CH1</fullName>
    </customValue>
    <customValue>
        <fullName>UK - UK1</fullName>
    </customValue>
    <customValue>
        <fullName>US - US5</fullName>
    </customValue>
    <customValue>
        <fullName>Indonesia - ID1</fullName>
    </customValue>
    <customValue>
        <fullName>Asia Pac	India</fullName>
        <isActive>false</isActive>
        <label>Asia Pac	India</label>
    </customValue>
    <customValue>
        <fullName>Asia Pac	Singapore</fullName>
        <isActive>false</isActive>
        <label>Asia Pac	Singapore</label>
    </customValue>
    <customValue>
        <fullName>Asia Pac	AP Region</fullName>
        <isActive>false</isActive>
        <label>Asia Pac	AP Region</label>
    </customValue>
    <customValue>
        <fullName>UK	  - UK1</fullName>
        <isActive>false</isActive>
        <label>UK	  - UK1</label>
    </customValue>
    <customValue>
        <fullName>Head Office  - H50</fullName>
        <isActive>false</isActive>
        <label>Head Office  - H50</label>
    </customValue>
    <masterLabel>Master BUs</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

classes/ChartsOnAccountPlanController_Test.cls
@isTest
public class ChartsOnAccountPlanController_Test {

    @IsTest(seeAlldata=true)
    static void testGetContactOpportunities() {
    Account acc= new Account();
        acc.Name='Test234';
        acc.BU__c='UK - UK1';
        acc.CurrencyIsoCode='GBP'; 
        acc.Industry='Agriculture';
        acc.Billing_Address_Line_1__c='test23';
        acc.Billing_City__c='test23';
        acc.Same_As_The_Billing_Address__c=true;
        acc.Billing_Country__c='test23';
        acc.Billing_State__c='test23';
        acc.Billing_ZIP_Postal_Code__c='test23';
        acc.Status__c = 'Approved';
        acc.Buying_Centre_Id__c ='90';
        insert acc;

        Contact con = new Contact(AccountId=acc.Id, FirstName='Test', LastName='Contact', Contact_Status__c='Active');
        insert con;

        List<Opportunity> oppList = new List<Opportunity>();
        Opportunity opp = new Opportunity(Name='Test Opportunity', StageName='New', CloseDate=System.today()-700, AccountId=acc.Id,amount=10000,TM_Phase__c='Talent Acquisition',Forecast_Category__c='Pipeline',Business_Type__c = 'Cross-sell: subscription');
        Opportunity opp1 = new Opportunity(Name='Test Opportunity', StageName='New', CloseDate=System.today()-700, AccountId=acc.Id,amount=10000,TM_Phase__c='Talent Management',Forecast_Category__c='Pipeline',Business_Type__c = 'Cross-sell: subscription');

        oppList.add(opp);
        oppList.add(opp1);
        insert oppList;
        
        List<Opportunity> oppListToUpdate = new List<Opportunity>();
        opp.StageName = 'Closed/Won';
        opp1.StageName = 'Closed/Won';
        oppListToUpdate.add(opp);
        oppListToUpdate.add(opp1);
        update oppListToUpdate;
        
        Account_Plan__c accPlan = new Account_Plan__c(Account_Name__c=acc.Id,Account_Plan_Type__c='Global');
        insert accPlan;
        
        Account_Plan__c accPlan1 = new Account_Plan__c(Account_Name__c=acc.Id,Account_Plan_Type__c='Regional',Buying_Centre_Id__c ='90');
        insert accPlan1;
        
        // Test method call
        Test.startTest();
        ChartsOnAccountPlanController.getOpportunitiesYearWise(accPlan.Id);
        ChartsOnAccountPlanController.getOpportunitiesYearWiseWithCI(accPlan.Id);
        ChartsOnAccountPlanController.getOpportunitiesYearWise(accPlan1.Id);
        ChartsOnAccountPlanController.getOpportunitiesYearWiseWithCI(accPlan1.Id);
        Test.stopTest();
    }
}