force-app/main/objects/Account.object
<CustomObject>
    <fields>
        <fullName>BU__c</fullName>
        <label>BU</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Master_BUs</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Billing_Address_Line_1__c</fullName>
        <inlineHelpText>If the address goes over more than one line then please use Address Line 2 and Address Line 3. This formatting will display on any Customer facing documents.</inlineHelpText>
        <label>Billing Address Line 1</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_City__c</fullName>
        <label>Billing City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_Country__c</fullName>
        <label>Billing Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AFGHANISTAN</fullName>
                </value>
                <value>
                    <fullName>ALBANIA</fullName>
                </value>
                <value>
                    <fullName>ALDERNEY</fullName>
                </value>
                <value>
                    <fullName>ALGERIA</fullName>
                </value>
                <value>
                    <fullName>AMERICAN SAMOA</fullName>
                </value>
                <value>
                    <fullName>ANDORRA</fullName>
                </value>
                <value>
                    <fullName>ANGOLA</fullName>
                </value>
                <value>
                    <fullName>ANGUILLA</fullName>
                </value>
                <value>
                    <fullName>ANTARCTICA</fullName>
                </value>
                <value>
                    <fullName>ANTIGUA AND BARBUDA</fullName>
                </value>
                <value>
                    <fullName>ARGENTINA</fullName>
                </value>
                <value>
                    <fullName>ARMENIA</fullName>
                </value>
                <value>
                    <fullName>ARUBA</fullName>
                </value>
                <value>
                    <fullName>AUSTRALIA</fullName>
                </value>
                <value>
                    <fullName>AUSTRIA</fullName>
                </value>
                <value>
                    <fullName>AZERBAIJAN</fullName>
                </value>
                <value>
                    <fullName>BAHAMAS</fullName>
                </value>
                <value>
                    <fullName>BAHRAIN</fullName>
                </value>
                <value>
                    <fullName>BANGLADESH</fullName>
                </value>
                <value>
                    <fullName>BARBADOS</fullName>
                </value>
                <value>
                    <fullName>BELARUS</fullName>
                </value>
                <value>
                    <fullName>BELGIUM</fullName>
                </value>
                <value>
                    <fullName>BELIZE</fullName>
                </value>
                <value>
                    <fullName>BENIN</fullName>
                </value>
                <value>
                    <fullName>BERMUDA</fullName>
                </value>
                <value>
                    <fullName>BHUTAN</fullName>
                </value>
                <value>
                    <fullName>BOLIVIA</fullName>
                </value>
                <value>
                    <fullName>BOSNIA AND HERZEGOWINA</fullName>
                </value>
                <value>
                    <fullName>BOTSWANA</fullName>
                </value>
                <value>
                    <fullName>BOUVET ISLAND</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Billing_State__c</fullName>
        <inlineHelpText>If State is required, please enter as two alphanumeric characters, e.g. GA instead of Georgia</inlineHelpText>
        <label>Billing State/County</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_ZIP_Postal_Code__c</fullName>
        <label>Billing ZIP/Postal Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Buying_Centre_Id__c</fullName>
        <description>Fro regional grouping of the same accounts, this field will be populated by the BI team.</description>
        <label>Buying Centre Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>1. Not yet trading with SHL - (definition - the account is new and/or has no trading history with SHL to date)
2. Trading with SHL - (definition - the account has sales recorded with SHL in the last 2 years)
3. Ceased Trading with SHL - (definition - the account has not traded with SHL in the past 12 months but has previously.) 
4. Dead - (Gone out of Business) (definition - The Account for whatever reason is no longer a trading entity)
Previous Values
1. Active with SHL (definition - The account has a track record of sales and/or opportunities managed in the last 2 years)
2. Inactive with SHL (definition - The account is still a trading account but there has been no activity with SHL (sales or opportunities managed) in the last 2 years)</description>
        <inlineHelpText>Status indicates if Account is approved or not. If you believe an unapproved Account should be Approved, Submit for Approval.</inlineHelpText>
        <label>Account Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Unapproved</fullName>
                    <default>true</default>
                    <label>Unapproved</label>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Unapproved - Out of Business</fullName>
                </value>
                <value>
                    <fullName>Unapproved - Trade Not Allowed</fullName>
                </value>
                <value>
                    <fullName>Unapproved - Duplicate</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>BU__c</fullName>
        <formula>text(Account.BU__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>BU</label>
        <type>Text</type>
    </fields>
</CustomObject>

force-app/main/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Annual_Contract_Value__c</fullName>
        <label>Annual Contract Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Billing_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Billing Contact</label>
        <lookupFilter>
            <active>false</active>
            <errorMessage>Billing Contact should be part of the account linked to the opportunity.</errorMessage>
            <filterItems>
                <field>$Source.AccountId</field>
                <operation>equals</operation>
                <valueField>Contact.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Business_Type__c</fullName>
        <description>Choose the Opportunity Type that best describes the type of business pursued.  
Reboost should only be used with In-Advance clients. 
Cross-sell is simply New Business with a client that has a current commercial relationship.</description>
        <label>Opportunity Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Expansion</fullName>
                </value>
                <value>
                    <fullName>Renewal</fullName>
                </value>
                <value>
                    <fullName>Debooking</fullName>
                    <label>Debooking / Adjustment</label>
                </value>
                <value>
                    <fullName>Extension</fullName>
                </value>
                <value>
                    <fullName>In Arrears</fullName>
                </value>
                <value>
                    <fullName>In Advance</fullName>
                </value>
                <value>
                    <fullName>Managed Services</fullName>
                </value>
                <value>
                    <fullName>Professional Services: non-subscription</fullName>
                </value>
                <value>
                    <fullName>Top Up / Addition</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Forecast_Category__c</fullName>
        <inlineHelpText>Please select “Commit” if you want this opportunity to be counted in your Forecast number. Please select Pipeline or Renewal at Risk if you do not want it to be included.</inlineHelpText>
        <label>Forecast Category</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Business_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Commit</fullName>
                </value>
                <value>
                    <fullName>Pipeline</fullName>
                    <default>true</default>
                    <label>Pipeline</label>
                </value>
                <value>
                    <fullName>Renewal at Risk</fullName>
                </value>
                <value>
                    <fullName>Forecast</fullName>
                    <isActive>false</isActive>
                    <label>Forecast</label>
                </value>
                <value>
                    <fullName>Parked</fullName>
                    <isActive>false</isActive>
                    <label>Parked</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>GCSC__c</fullName>
        <label>GCSC Method</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Phone</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Multi_YearDeal__c</fullName>
        <defaultValue>TEXT(1)</defaultValue>
        <description>Describes length of Contract signed</description>
        <label>Contract length (In Month)</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                    <default>true</default>
                    <label>0 - 12</label>
                </value>
                <value>
                    <fullName>2</fullName>
                    <label>13 - 24</label>
                </value>
                <value>
                    <fullName>3</fullName>
                    <label>25 - 36</label>
                </value>
                <value>
                    <fullName>4</fullName>
                    <label>37 - 48</label>
                </value>
                <value>
                    <fullName>5</fullName>
                    <label>49 - 60</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>NVM_Credit_Card_ID__c</fullName>
        <label>NVM Payment ID</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OpportunityAmountMappedWithLead__c</fullName>
        <description>As there is another standard field Amount exist on Opp but we can not map it with a custom field Opportunity Amount on lead during lead convert. So we are creating this custom filed only to map it with its correspondent on lead. This field will not be added on page layout.</description>
        <label>OpportunityAmountMappedWithLead</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>OpportunityTypeMappedWithLead__c</fullName>
        <description>As there is another standard field Type exist on Opp but we can not map it with a custom field Opportunity Type on lead during lead convert. So we are creating this custom filed only to map it with its correspondent on lead. This field will not be added on page layout.</description>
        <label>OpportunityTypeMappedWithLead</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Existing Business</fullName>
                </value>
                <value>
                    <fullName>New Business</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Original_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Original Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Variation / Renewal Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Primary_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities (Primary Contact)</relationshipLabel>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Unconfirmed_Sun_Order_Number__c</fullName>
        <label>Unconfirmed Sun Order Number</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Variation_Opportunity__c</fullName>
        <label>Variation Opportunity</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                    <default>true</default>
                    <label>No</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

classes/ACR_RelationshipMapController_Test.cls
@isTest
public class ACR_RelationshipMapController_Test {

    @isTest(seeAlldata=true)
    static void setupTestData() {
        Account account = new Account(name = 'Test Contact Hierarchy Class',
                                      industry = 'Legal', Status__c = 'Approved',
                                      Billing_Address_Line_1__c = 'test', Billing_City__c = 'Test City',
                                      Billing_Country__c = 'India', Billing_State__c = 'Test',
                                      Billing_ZIP_Postal_Code__c = '1100110', BU__c = 'Australia - AU1', Buying_Centre_Id__c='aa');
        insert account;
        
        List<Contact> testContacts = new List<Contact>();
        for(Integer i=0;i<4;i++) {
            testContacts.add(new Contact(LastName = 'TestCon'+i,Email = 'TestCon'+i+'@'+'TestCon'+i+'.com',AccountId=account.Id));
        }
        insert testContacts;
        
        String influenceJson = '[{"id":"'+testContacts[0].id + '-' + testContacts[1].id +'","target":"'+testContacts[1].id + '","source":"'+testContacts[0].id+'" }]';
        
        Opportunity opp =
            new Opportunity(name = 'Test Opportunity', AccountID = account.id);
        opp.Billing_Contact__c = testContacts[0].id;
        opp.Closedate = system.today();
        opp.Primary_Contact__c = testContacts[0].id;
        opp.CurrencyIsoCode = 'AUD';
        opp.Unconfirmed_Sun_Order_Number__c = '1234';
        opp.NVM_Credit_Card_ID__c = '1234';
        opp.Amount = 1000;
        opp.Variation_Opportunity__c = 'No';
        opp.Original_Opportunity__c = null;
        opp.Annual_Contract_Value__c = 1000.00;
        opp.StageName = 'New';
        opp.GCSC__c = 'Phone';
        opp.OpportunityAmountMappedWithLead__c = 323.34; //**********
        opp.OpportunityTypeMappedWithLead__c = 'New Business'; //**********
        opp.Business_Type__c = 'Renewal';
        opp.Forecast_Category__c = 'Commit';
        opp.Multi_YearDeal__c = '1';
        opp.Opportunity_Deal_Year__c = 1;
        
        insert opp;
        
        List<OpportunityContactRole> contactRoleList = new List<OpportunityContactRole>();
        OpportunityContactRole contactRole = new OpportunityContactRole();
        
        contactRole.ContactId = testContacts[0].Id;
        contactRole.OpportunityId = opp.Id;
        
        insert contactRole;

        Opportunity opp1=
            new Opportunity(name = 'Test Opportunity', AccountID = account.id);
        opp1.Billing_Contact__c = testContacts[0].id;
        opp1.Closedate = system.today();
        opp1.Primary_Contact__c = testContacts[0].id;
        opp1.CurrencyIsoCode = 'AUD';
        opp1.Unconfirmed_Sun_Order_Number__c = '1234';
        opp1.NVM_Credit_Card_ID__c = '1234';
        opp1.Amount = 1000;
        opp1.Variation_Opportunity__c = 'No';
        opp1.Original_Opportunity__c = null;
        opp1.Annual_Contract_Value__c = 1000.00;
        opp1.StageName = 'Closed Lost';
        opp1.GCSC__c = 'Phone';
        opp1.OpportunityAmountMappedWithLead__c = 323.34; //**********
        opp1.OpportunityTypeMappedWithLead__c = 'New Business'; //**********
        opp1.Business_Type__c = 'Renewal';
        opp1.Forecast_Category__c = 'Commit';
        opp1.Multi_YearDeal__c = '1';
        opp1.Opportunity_Deal_Year__c = 1;
        
        insert opp1;
        
        OpportunityContactRole contactRole1= new OpportunityContactRole();
        
        contactRole1.ContactId = testContacts[2].Id;
        contactRole1.OpportunityId = opp1.Id;
        
        insert contactRole1;
        Test.startTest();
        String hierarchyInformationId = ACR_RelationshipMapController.createHierarchyOnAccount(account.Id, 'Test Hierarchy');
        Hierarchy_Information__c hierarchyInformation = [SELECT Id, Account__c FROM Hierarchy_Information__c WHERE Id = :hierarchyInformationId LIMIT 1];
        ACR_RelationshipMapController.HierarchyDetails hierarchyDetails = ACR_RelationshipMapController.getHierarchyDetails(hierarchyInformationId);
        
        ACR_RelationshipMapController.HierarchyWrapper placeholder = new ACR_RelationshipMapController.HierarchyWrapper();
        placeholder.IsPlaceholder = true;
        placeholder.Name = 'Test';
        placeholder.Id = 'Placeholder1';
        placeholder.ReportsTo = 'rootlevel';
        placeholder.Children = new List<ACR_RelationshipMapController.HierarchyWrapper>();
        
        ACR_RelationshipMapController.HierarchyWrapper contactInMap = new ACR_RelationshipMapController.HierarchyWrapper();
        contactInMap.IsPlaceholder = false;
        contactInMap.Name = testContacts[0].Name;
        contactInMap.Id = testContacts[0].Id;
        contactInMap.ReportsTo = 'rootlevel';
        contactInMap.Children = new List<ACR_RelationshipMapController.HierarchyWrapper>();

        hierarchyDetails.HierarchyList.add(placeholder);
        hierarchyDetails.HierarchyList.add(contactInMap);
        
        list<ACR_RelationshipMapController.ContactWrapper> listOfcontactWrapper1 = new list<ACR_RelationshipMapController.ContactWrapper>();
        ACR_RelationshipMapController.ContactWrapper contactWrapper1= new ACR_RelationshipMapController.ContactWrapper();
        contactWrapper1.firstName = 'ceofirstname';
        contactWrapper1.lastName = 'ceolastname';
        contactWrapper1.email = 'ceofirstname@test.com';
        contactWrapper1.phone = '9876543211';
        contactWrapper1.persona = 'Other';
        contactWrapper1.title = 'CEO';
        contactWrapper1.advocacyLevel = 'Weak';
        contactWrapper1.areaOfInterest = 'Training';
        contactWrapper1.jobFunction = 'Talent Management';
        contactWrapper1.accountId = account.Id;
        
        listOfcontactWrapper1.add(contactWrapper1);
        
        // Creating an instance using the parameterized constructor
        ACR_RelationshipMapController.ContactWrapper contactWrapper09 = new ACR_RelationshipMapController.ContactWrapper(
            1, '003XXXXXXXXXXXX', null, 'John', 'Doe', '001XXXXXXXXXXXX', 'john.doe@example.com', 'Manager', 'Advocate', 'CEO', 'Admin', '1234567890', 'Influencer', 'Technology'
        );
        
        // Creating child instances
        List<ACR_RelationshipMapController.HierarchyWrapper> childList = new List<ACR_RelationshipMapController.HierarchyWrapper>{
            new ACR_RelationshipMapController.HierarchyWrapper('002XXXXXXXXXXXX', 'Child 1', '001XXXXXXXXXXXX', true, null),
            new ACR_RelationshipMapController.HierarchyWrapper('003XXXXXXXXXXXX', 'Child 2', '001XXXXXXXXXXXX', false, null)
        };
        
        // Creating a parent instance using the parameterized constructor
        ACR_RelationshipMapController.HierarchyWrapper hierarchyWrapper09 = new ACR_RelationshipMapController.HierarchyWrapper('001XXXXXXXXXXXX', 'Parent', null, true, childList);
       
        
        ACR_RelationshipMapController.ContactWrapper contactWrapper11= new ACR_RelationshipMapController.ContactWrapper();
        contactWrapper11.firstName = 'chrofirstname';
        contactWrapper11.lastName = 'chrolastname';
        contactWrapper11.email = 'chrofirstname@test.com';
        contactWrapper11.phone = '9876543211';
        contactWrapper11.persona = 'Head of TM';
        contactWrapper11.title = 'CHRO';
        contactWrapper11.advocacyLevel = 'None';
        contactWrapper11.areaOfInterest = 'Training';
        contactWrapper11.jobFunction = 'Talent Management';
        contactWrapper11.accountId = account.Id;
        
        list<ACR_RelationshipMapController.ContactWrapper> listOfcontactWrapper = new list<ACR_RelationshipMapController.ContactWrapper>();
        ACR_RelationshipMapController.ContactWrapper contactWrapper = new ACR_RelationshipMapController.ContactWrapper();
        contactWrapper.id = testContacts[2].Id;
        contactWrapper.persona = 'Head of TM';
        listOfcontactWrapper.add(contactWrapper);
        
        list<ACR_RelationshipMapController.ContactWrapper> listOfcontactWrapper01 = new list<ACR_RelationshipMapController.ContactWrapper>();
        ACR_RelationshipMapController.ContactWrapper contactWrapper01 = new ACR_RelationshipMapController.ContactWrapper();
        contactWrapper01.id = testContacts[3].Id;
        contactWrapper01.persona = 'Head of TM';
        listOfcontactWrapper01.add(contactWrapper01);
        
        ACR_RelationshipMapController.ContactWrapper contactWrapper2 = new ACR_RelationshipMapController.ContactWrapper();
        contactWrapper2.id = testContacts[3].Id;
        contactWrapper2.role = 'Other';
        
        Contact conToReplace = new Contact();
        conToReplace.LastName = 'Hierarchy'+System.Now();
        ACR_RelationshipMapController.updateHierarchyOnPlaceholderCreation(hierarchyDetails.HierarchyList, hierarchyInformationId);
        ACR_RelationshipMapController.updateHierarchyOnExistingContactSelection(listOfcontactWrapper, hierarchyInformation.Account__c, hierarchyInformationId, 'rootlevel', hierarchyDetails.HierarchyList);
        ACR_RelationshipMapController.updateHierarchyOnExistingContactSelection(listOfcontactWrapper, hierarchyInformation.Account__c, hierarchyInformationId, testContacts[2].Id, hierarchyDetails.HierarchyList);
        
        ACR_RelationshipMapController.HierarchyDetails hierarchyDetails01 = ACR_RelationshipMapController.getHierarchyDetails(hierarchyInformationId);
        ACR_RelationshipMapController.HierarchyWrapper placeholder01 = new ACR_RelationshipMapController.HierarchyWrapper();
        placeholder01.IsPlaceholder = true;
        placeholder01.Name = 'Test';
        placeholder01.Id = 'Placeholder1';
        placeholder01.ReportsTo = testContacts[2].Id;
        placeholder01.Children = new List<ACR_RelationshipMapController.HierarchyWrapper>();
        hierarchyDetails01.HierarchyList.add(placeholder01);
        ACR_RelationshipMapController.updateHierarchyOnPlaceholderCreation(hierarchyDetails.HierarchyList, hierarchyInformationId);
        ACR_RelationshipMapController.updateInfluenceJSON(influenceJson, hierarchyInformationId);
        ACR_RelationshipMapController.updateConflictJSON(influenceJson, hierarchyInformationId);
        ACR_RelationshipMapController.GetContactWrapper conWrapper00 = ACR_RelationshipMapController.getActiveContacts(0, '', new list<String>{testContacts[0].Id}, account.Id,true, null);
        ACR_RelationshipMapController.GetContactWrapper conWrapper01 = ACR_RelationshipMapController.getActiveContacts(0, 'ceo', new list<String>{testContacts[0].Id}, account.Id,true, null);
        //ACR_RelationshipMapController.GetContactWrapper conWrapper02 = ACR_RelationshipMapController.getActiveContacts(0, 'ceo', new list<String>{testContacts[0].Id}, account.Id,false, null);
        ACR_RelationshipMapController.GetContactWrapper conWrapper03 = ACR_RelationshipMapController.getActiveContacts(0, '', new list<String>{testContacts[0].Id}, account.Id,false, 'aa');
        ACR_RelationshipMapController.GetContactWrapper conWrapper04 = ACR_RelationshipMapController.getActiveContacts(0, 'ceo', new list<String>(), account.Id,true, 'aa');
        ACR_RelationshipMapController.createContactRecords(listOfcontactWrapper1, hierarchyInformation.Account__c, hierarchyInformationId, 'rootlevel', hierarchyDetails.HierarchyList);
        ACR_RelationshipMapController.getListOfRelationships(account.Id);
        ACR_RelationshipMapController.updateAdvocacyLevelOnContact('Weak', hierarchyDetails.HierarchyList, hierarchyInformationId, testContacts[0].Id);
        ACR_RelationshipMapController.updateRelationshipMapOnReplace(hierarchyDetails.HierarchyList, hierarchyInformationId, testContacts[0].Id, conToReplace, new list<Contact>{testContacts[0]}, testContacts[0].Id);
        ACR_RelationshipMapController.updateInfluenceJSON(influenceJson, hierarchyInformationId);
        ACR_RelationshipMapController.updateConflictJSON(influenceJson, hierarchyInformationId);
        ACR_RelationshipMapController.updateRelationshipMap(hierarchyDetails.HierarchyList, hierarchyInformationId,testContacts[0].Id);
        ACR_RelationshipMapController.updateEconomicBuyerOrIOPsychologistStatus(testContacts[0].Id, account.Id, 'Add','Economic Buyer');
        ACR_RelationshipMapController.updateEconomicBuyerOrIOPsychologistStatus(testContacts[0].Id, account.Id, 'Remove','Economic Buyer');
        ACR_RelationshipMapController.updateEconomicBuyerOrIOPsychologistStatus(testContacts[0].Id, account.Id, 'Add','IO Psychologist');
        ACR_RelationshipMapController.updateEconomicBuyerOrIOPsychologistStatus(testContacts[0].Id, account.Id, 'Remove','IO Psychologist');
        ACR_RelationshipMapController.insertNote('Note 1', testContacts[0].Id);
        ACR_RelationshipMapController.updateNote('Note 1', testContacts[0].Id);
        ACR_RelationshipMapController.getNote(testContacts[0].Id);
        ACR_RelationshipMapController.renameHierarchy('New Hierarchy', hierarchyInformationId);
        //ACR_RelationshipMapController.ActivityAndAddressWrapper activityAndAddress = ACR_RelationshipMapController.getActivityMetricData(testContacts[0].Id);
        ACR_RelationshipMapController.updateInfluenceJSON(influenceJson, hierarchyInformationId);
        ACR_RelationshipMapController.updateConflictJSON(influenceJson, hierarchyInformationId);
        ACR_RelationshipMapController.getInfluenceAndConflictDetails(hierarchyInformationId);
		ACR_RelationshipMapController.deleteInfluenceConflictLine(hierarchyInformationId, testContacts[0].Id + '-' + testContacts[1].Id, 'Influence');
        ACR_RelationshipMapController.deleteInfluenceConflictLine(hierarchyInformationId, testContacts[0].Id + '-' + testContacts[1].Id, 'Conflict');
        
        Opportunity oppToUpdate = new Opportunity();
        oppToUpdate.Id = opp.Id;
        oppToUpdate.StageName = System.Label.Opportunity_Stage_7;
        oppToUpdate.CloseDate = System.Today();
        update oppToUpdate;
       
        
        ACR_RelationshipMapController.getHierarchyDetails(hierarchyInformationId);
        
		ACR_RelationshipMapController.deleteHierarchy(hierarchyInformationId);

        Test.stopTest();
    }
}