force-app/main/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Approach__c</fullName>
        <inlineHelpText>Stance being currently taken with this account. Either a Grow, Protect or undefined</inlineHelpText>
        <label>Account Approach</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Grow</fullName>
                </value>
                <value>
                    <fullName>Protect</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>BU__c</fullName>
        <label>BU</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Master_BUs</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Billing_Address_Line_1__c</fullName>
        <inlineHelpText>If the address goes over more than one line then please use Address Line 2 and Address Line 3. This formatting will display on any Customer facing documents.</inlineHelpText>
        <label>Billing Address Line 1</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_City__c</fullName>
        <label>Billing City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_Country__c</fullName>
        <label>Billing Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AFGHANISTAN</fullName>
                </value>
                <value>
                    <fullName>ALBANIA</fullName>
                </value>
                <value>
                    <fullName>ALDERNEY</fullName>
                </value>
                <value>
                    <fullName>ALGERIA</fullName>
                </value>
                <value>
                    <fullName>AMERICAN SAMOA</fullName>
                </value>
                <value>
                    <fullName>ANDORRA</fullName>
                </value>
                <value>
                    <fullName>ANGOLA</fullName>
                </value>
                <value>
                    <fullName>ANGUILLA</fullName>
                </value>
                <value>
                    <fullName>ANTARCTICA</fullName>
                </value>
                <value>
                    <fullName>ANTIGUA AND BARBUDA</fullName>
                </value>
                <value>
                    <fullName>ARGENTINA</fullName>
                </value>
                <value>
                    <fullName>ARMENIA</fullName>
                </value>
                <value>
                    <fullName>ARUBA</fullName>
                </value>
                <value>
                    <fullName>AUSTRALIA</fullName>
                </value>
                <value>
                    <fullName>AUSTRIA</fullName>
                </value>
                <value>
                    <fullName>AZERBAIJAN</fullName>
                </value>
                <value>
                    <fullName>BAHAMAS</fullName>
                </value>
                <value>
                    <fullName>BAHRAIN</fullName>
                </value>
                <value>
                    <fullName>BANGLADESH</fullName>
                </value>
                <value>
                    <fullName>BARBADOS</fullName>
                </value>
                <value>
                    <fullName>BELARUS</fullName>
                </value>
                <value>
                    <fullName>BELGIUM</fullName>
                </value>
                <value>
                    <fullName>BELIZE</fullName>
                </value>
                <value>
                    <fullName>BENIN</fullName>
                </value>
                <value>
                    <fullName>BERMUDA</fullName>
                </value>
                <value>
                    <fullName>BHUTAN</fullName>
                </value>
                <value>
                    <fullName>BOLIVIA</fullName>
                </value>
                <value>
                    <fullName>BOSNIA AND HERZEGOWINA</fullName>
                </value>
                <value>
                    <fullName>BOTSWANA</fullName>
                </value>
                <value>
                    <fullName>BOUVET ISLAND</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Billing_State__c</fullName>
        <inlineHelpText>If State is required, please enter as two alphanumeric characters, e.g. GA instead of Georgia</inlineHelpText>
        <label>Billing State/County</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_ZIP_Postal_Code__c</fullName>
        <label>Billing ZIP/Postal Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>1. Not yet trading with SHL - (definition - the account is new and/or has no trading history with SHL to date)
2. Trading with SHL - (definition - the account has sales recorded with SHL in the last 2 years)
3. Ceased Trading with SHL - (definition - the account has not traded with SHL in the past 12 months but has previously.) 
4. Dead - (Gone out of Business) (definition - The Account for whatever reason is no longer a trading entity)
Previous Values
1. Active with SHL (definition - The account has a track record of sales and/or opportunities managed in the last 2 years)
2. Inactive with SHL (definition - The account is still a trading account but there has been no activity with SHL (sales or opportunities managed) in the last 2 years)</description>
        <inlineHelpText>Status indicates if Account is approved or not. If you believe an unapproved Account should be Approved, Submit for Approval.</inlineHelpText>
        <label>Account Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Unapproved</fullName>
                    <default>true</default>
                    <label>Unapproved</label>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Unapproved - Out of Business</fullName>
                </value>
                <value>
                    <fullName>Unapproved - Trade Not Allowed</fullName>
                </value>
                <value>
                    <fullName>Unapproved - Duplicate</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Territory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Territory</label>
        <lookupFilter>
            <active>false</active>
            <errorMessage>Territory associated with an account should be active</errorMessage>
            <filterItems>
                <field>Territory__c.Is_Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Territory__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

force-app/main/objects/Account_Plan__c.object
<CustomObject>
    <description>Module to capture Key Account Plan details</description>
    <fields>
        <fullName>Account_Name__c</fullName>
        <description>This field is used to store the related account for Account Plan</description>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Plans</relationshipLabel>
        <relationshipName>Account_Plans</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Account_Plan_Status__c</fullName>
        <label>Account Plan Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>In Review</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Retired</fullName>
                </value>
                <value>
                    <fullName>Migrated to Regional - Retired</fullName>
                    <isActive>false</isActive>
                    <label>Migrated to Regional - Retired</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Quarter__c</fullName>
        <label>Quarter</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <label>Year</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <label>Account Plan</label>
    <nameField>
        <displayFormat>ACP-{0000}</displayFormat>
        <label>Account Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Activated_Date__c</fullName>
        <description>New custom field for Activated Date which will be hidden on Page layouts</description>
        <label>Activated Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Agreement__c</fullName>
        <label>Agreement</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Standard</fullName>
                    <default>true</default>
                    <label>Standard</label>
                </value>
                <value>
                    <fullName>Standard MA</fullName>
                </value>
                <value>
                    <fullName>Non-Standard</fullName>
                </value>
                <value>
                    <fullName>Non-Standard MA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Final_Submission_Date_EST__c</fullName>
        <label>Submitted to OATs(Legacy)</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Legal_Order_Name__c</fullName>
        <label>Legal Order Name(Legacy)</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>S2P_Reference_Required__c</fullName>
        <description>Check on the S2P Reference.</description>
        <inlineHelpText>Choose new if system referenced in the order does not currently exist, otherwise choose Existing</inlineHelpText>
        <label>System Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Existing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Submission_Offset__c</fullName>
        <label>Submission Offset</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Subscription_Start_Date__c</fullName>
        <inlineHelpText>This date should be the same as the Contract Start Date unless delay has been approved in CLM.</inlineHelpText>
        <label>Product Subscription Start Date</label>
        <type>Date</type>
    </fields>
</CustomObject>

force-app/main/objects/Order.object
<CustomObject>
    <fields>
        <fullName>BU__c</fullName>
        <formula>TEXT(Account.BU__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>BU</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Submission_Offset__c</fullName>
        <label>Submission Offset</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

force-app/main/objects/Territory__c.object
<CustomObject>
    <label>Territory</label>
    <nameField>
        <label>Territory</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ContentDocumentTriggerManager_Tester.cls
@isTest(seeAllData = true)
public class ContentDocumentTriggerManager_Tester {
    public static testMethod void TestdeletecontentDocumentCSV(){
        Datetime variable=System.now();
        String TestAccountname='Test Account'+variable; 
        Account account=new Account(name=TestAccountname,Status__c='Approved',
                                    CurrencyIsoCode='INR',
                                    //done by aashi Territory__c='Alliances',
                                    Account_Approach__c='Grow',
                                    Billing_Address_Line_1__c='test',
                                    Billing_City__c='Test City',
                                    Billing_Country__c='India',
                                    Billing_State__c='Test',
                                    Billing_ZIP_Postal_Code__c='1100110',
                                    BU__c='Australia - AU1',
                                    Industry='Other');
        insert account;
        Contract contract = new Contract();
        contract.AccountId = account.Id;  
        contract.Legal_Order_Name__c = 'test'; 
        contract.CurrencyIsoCode = account.CurrencyIsoCode;
        contract.S2P_Reference_Required__c = 'New';
        contract.Status = 'Draft';
        contract.CustomerSignedDate = Date.Today();
        contract.StartDate = Date.Today();
        contract.ContractTerm = 6;   
        contract.Activated_Date__c=datetime.now();
        contract.Final_Submission_Date_EST__c=datetime.now().addDays(-2);
        contract.Submission_Offset__c = 10;
        contract.Agreement__c = 'Order';
        contract.Subscription_Start_Date__c = Date.Today();
        insert contract;
           
        Test.startTest();
        
        ContentVersion Cv1 = new ContentVersion();    
        Cv1.Origin='C';
        Cv1.VersionData = Blob.ValueOf('Hello');
        Cv1.Title = 'CandidateUploadSheet.PDF';
        Cv1.PathOnClient ='CandidateUploadSheet.PDF'; 
        Cv1.ContentLocation='S';        
        insert Cv1;  
        // First get the content document Id from ContentVersion
        Id conDoc1 = [SELECT ContentDocumentId FROM ContentVersion WHERE Id =:Cv1.Id].ContentDocumentId;             
        //Create ContentDocumentLink
        ContentDocumentLink cDe1 = new ContentDocumentLink();
        cDe1.ContentDocumentId = conDoc1;
        cDe1.Visibility='AllUsers';
        cDe1.LinkedEntityId = contract.Id; // you can use objectId,GroupId etc
        cDe1.ShareType = 'V'; // Inferred permission, checkout description of ContentDocumentLink object for more details
        //cDe.Visibility = 'InternalUsers';
        insert cDe1;
         
        Cv1 =  [select ContentDocument.Id from ContentVersion where Id = :Cv1.Id];
        delete Cv1.ContentDocument;
        Test.stopTest();
        
        
    }
    
    public static testMethod void TestdeletecontentDocumentPDF(){
        Datetime variable=System.now();
        String TestAccountname='Test Account'+variable; 
        Account account=new Account(name=TestAccountname,
                                    Status__c='Approved',
                                    CurrencyIsoCode='INR',
                                    //done by aashi Territory__c='Alliances',
                                    Account_Approach__c='Grow',
                                    Billing_Address_Line_1__c='test',
                                    Billing_City__c='Test City',
                                    Billing_Country__c='India',
                                    Billing_State__c='Test',
                                    Billing_ZIP_Postal_Code__c='1100110',
                                    BU__c='Australia - AU1',
                                   Industry='Other');
        insert account;
        Contract contract = new Contract();
        contract.AccountId = account.Id;  
        contract.Legal_Order_Name__c = 'test'; 
        contract.CurrencyIsoCode = account.CurrencyIsoCode;
        contract.S2P_Reference_Required__c = 'New';
        contract.Status = 'Draft';
        contract.CustomerSignedDate = Date.Today();
        contract.StartDate = Date.Today();
        contract.ContractTerm = 6;   
        contract.Activated_Date__c=datetime.now();
        contract.Final_Submission_Date_EST__c=datetime.now().addDays(-2);
        contract.Submission_Offset__c = 10;
        contract.Agreement__c = 'Order';
        contract.Subscription_Start_Date__c = Date.Today();
        insert contract;
        
        ContentVersion Cv1 = new ContentVersion();    
        Cv1.Origin='C';
        Cv1.VersionData = Blob.ValueOf('Hello');
        Cv1.Title = 'CandidateUploadSheet.PDF';
        Cv1.PathOnClient ='CandidateUploadSheet.PDF'; 
        Cv1.ContentLocation='S';        
        insert Cv1;
        
        // First get the content document Id from ContentVersion
        Id conDoc1 = [SELECT ContentDocumentId FROM ContentVersion WHERE Id =:Cv1.Id].ContentDocumentId;             
        //Create ContentDocumentLink
        ContentDocumentLink cDe1 = new ContentDocumentLink();
        cDe1.ContentDocumentId = conDoc1;
        cDe1.Visibility='AllUsers';
        cDe1.LinkedEntityId = contract.Id; // you can use objectId,GroupId etc
        cDe1.ShareType = 'V'; // Inferred permission, checkout description of ContentDocumentLink object for more details
        //cDe.Visibility = 'InternalUsers';
        insert cDe1; 
        
        test.startTest();  
        
        Cv1 =  [select ContentDocument.Id from ContentVersion where Id = :Cv1.Id];                
        delete Cv1.ContentDocument; 
        Contract contract1 = new Contract();
        contract1.AccountId = account.Id;  
        contract1.Legal_Order_Name__c = 'test'; 
        contract1.CurrencyIsoCode = account.CurrencyIsoCode;
        contract1.S2P_Reference_Required__c = 'New';
        contract1.Status = 'Draft';
        contract1.CustomerSignedDate = Date.Today();
        contract1.StartDate = Date.Today();
        contract1.ContractTerm = 6;   
        contract1.Activated_Date__c=datetime.now();
        contract1.Final_Submission_Date_EST__c=datetime.now().addDays(-2);
        contract1.Submission_Offset__c = 10;
        contract1.Agreement__c = 'Order';
        contract1.Subscription_Start_Date__c = Date.Today();
        insert contract1;
        Contract contract2 = new Contract();
        contract2.AccountId = account.Id;  
        contract2.Legal_Order_Name__c = 'test'; 
        contract2.CurrencyIsoCode = account.CurrencyIsoCode;
        contract2.S2P_Reference_Required__c = 'New';
        contract2.Status = 'Submitted';
        contract2.CustomerSignedDate = Date.Today();
        contract2.StartDate = Date.Today();
        contract2.ContractTerm = 6;   
        contract2.Activated_Date__c=datetime.now();
        contract2.Final_Submission_Date_EST__c=datetime.now().addDays(-2);
        contract2.Submission_Offset__c = 10;
        contract2.Agreement__c = 'Order';
        //insert contract2;
        
        ContentVersion Cv = new ContentVersion();    
        Cv.Origin='C';
        Cv.VersionData = Blob.ValueOf('Hello');
        Cv.Title = 'CandidateUploadSheet.csv';
        Cv.PathOnClient = 'CandidateUploadSheet.csv'; 
        Cv.ContentLocation='S';        
        insert Cv;  
        // First get the content document Id from ContentVersion
        Id conDoc = [SELECT ContentDocumentId FROM ContentVersion WHERE Id =:Cv.Id].ContentDocumentId;
        
        //Create ContentDocumentLink
        ContentDocumentLink cDe = new ContentDocumentLink();
        cDe.ContentDocumentId = conDoc;
        cDe.Visibility='AllUsers';
        cDe.LinkedEntityId = contract1.Id; // you can use objectId,GroupId etc
        cDe.ShareType = 'V'; // Inferred permission, checkout description of ContentDocumentLink object for more details
        //cDe.Visibility = 'InternalUsers';
        insert cDe;
        delete cDe;
        Cv =  [select ContentDocument.Id from ContentVersion where Id = :Cv.Id];
        delete Cv.ContentDocument;
        test.stopTest();
        
        
        
    }
  
    //Added by Prachi --SSE-21436
     @isTest
    public static void testavoidDeleteAutoGeneratedPDFAsAdmin(){
     test.startTest();

         User commUser = [Select id from user where Profile.name = 'Commercial' and IsActive = true limit 1];
         Account acc = new Account(name= 'Testname_AccountPlan' ,Status__c='Approved',
                                  Billing_Address_Line_1__c='test',Billing_City__c='Test City',
                                  Billing_Country__c='India',Billing_State__c='Test',Industry= 'Legal',
                                  Billing_ZIP_Postal_Code__c='1100110');
        
		insert acc;        
        Account_Plan__c ap = new Account_Plan__c(Account_Name__c = acc.id,Quarter__c ='Q1',
                                                 Year__c='2023',Account_Plan_Status__c ='Draft');
        
        
         Account_Plan__c ap1 = new Account_Plan__c(Account_Name__c = acc.id,Quarter__c ='Q1',
                                                 Year__c='2023',Account_Plan_Status__c ='Draft');
        
        acc.OwnerId = commUser.Id;
        update acc;
        
        system.runAs(commUser){ 
            insert ap;
            insert ap1;
        ContentVersion cv = new ContentVersion();
        cv.ContentLocation = 'S';
        cv.Title = 'Test CV';
        cv.PathOnClient = 'Test CV' + '.pdf';
        cv.SharingPrivacy = 'N' ;
        cv.SharingOption = 'A';
        cv.IsMajorVersion = true;  
        cv.FirstPublishLocationId = ap.id;
        cv.VersionData = Blob.valueOf('Testing File');
        cv.Description = 'This is an autogenerated PDF for Account Plan.';   
        insert cv;
        
        Id cdId = [Select id , ContentDocumentId from ContentVersion where id = : cv.id].ContentDocumentId;
        system.debug('cdId'+cdId);
        ContentDocument cd = new ContentDocument();
        cd.id = cdId;
         
        try{
       
                delete cd;
            
        }
        catch(Exception ex){
            system.debug('cdId'+ex.getMessage());
            system.Assert(ex.getMessage().contains('You do not have access to delete this File.'));
        }
        }
         test.stopTest();
    }
    
    //Added by Prachi --SSE-21436
     @isTest
    public static void testavoidDeleteAutoGeneratedPDF(){
     test.startTest();

         User commUser = [Select id from user where Profile.name = 'Commercial' and IsActive = true limit 1];
         Account acc = new Account(name= 'Testname_AccountPlan' ,Status__c='Approved',
                                  Billing_Address_Line_1__c='test',Billing_City__c='Test City',
                                  Billing_Country__c='India',Billing_State__c='Test',Industry= 'Legal',
                                  Billing_ZIP_Postal_Code__c='1100110',BU__c='China - CN1');
        insert acc;
        
        Account_Plan__c ap = new Account_Plan__c(Account_Name__c = acc.id,Quarter__c ='Q1',
                                                 Year__c='2023',Account_Plan_Status__c ='Draft');
        insert ap;
        
         Account_Plan__c ap1 = new Account_Plan__c(Account_Name__c = acc.id,Quarter__c ='Q1',
                                                 Year__c='2023',Account_Plan_Status__c ='Draft');
        insert ap1;
       
        ContentVersion cv = new ContentVersion();
        cv.ContentLocation = 'S';
        cv.Title = 'Test CV';
        cv.PathOnClient = 'Test CV' + '.pdf';
        cv.SharingPrivacy = 'N' ;
        cv.SharingOption = 'A';
        cv.IsMajorVersion = true;  
        cv.FirstPublishLocationId = ap.id;
        cv.VersionData = Blob.valueOf('Testing File');
        cv.Description = 'This is an autogenerated PDF for Account Plan.';   
        insert cv;
        
        Id cdId = [Select id , ContentDocumentId from ContentVersion where id = : cv.id].ContentDocumentId;
        system.debug('cdId'+cdId);
        ContentDocument cd = new ContentDocument();
        cd.id = cdId;
         
        try{
       
                delete cd;
            
        }
        catch(Exception ex){
            system.debug('cdId'+ex.getMessage());
            system.Assert(ex.getMessage().contains('You do not have access to delete this File.'));
        }
        
         test.stopTest();
    }
    
    //Added by Prachi -- SSE-21596
     /*@isTest
    public static void testavoidDeleteAutoGeneratedCSVAsAdmin(){
     test.startTest();

         User commUser = [Select id from user where Profile.name = 'Commercial' and IsActive = true limit 1];
         Account acc = new Account(name= 'Testname_AccountPlan' ,Status__c='Approved',
                                  Billing_Address_Line_1__c='test',Billing_City__c='Test City',
                                  Billing_Country__c='India',Billing_State__c='Test',Industry= 'Legal',
                                  Billing_ZIP_Postal_Code__c='1100110',BU__c='China - CN1');
        insert acc;
        
        Account_Plan__c ap = new Account_Plan__c(Account_Name__c = acc.id,Quarter__c ='Q1',
                                                 Year__c='2023',Account_Plan_Status__c ='Draft');
        insert ap;
        
         Account_Plan__c ap1 = new Account_Plan__c(Account_Name__c = acc.id,Quarter__c ='Q1',
                                                 Year__c='2023',Account_Plan_Status__c ='Draft');
        insert ap1;
        system.runAs(commUser){ 
        ContentVersion cv = new ContentVersion();
        cv.ContentLocation = 'S';
        cv.Title = 'Test CV';
        cv.PathOnClient = 'Test CV' + '.csv';
        cv.SharingPrivacy = 'N' ;
        cv.SharingOption = 'A';
        cv.IsMajorVersion = true;  
        cv.FirstPublishLocationId = ap.id;
        cv.VersionData = Blob.valueOf('Testing File');
        cv.Description = 'This is an autogenerated csv for Uploaded Contacts.';   
        insert cv;
        
        Id cdId = [Select id , ContentDocumentId from ContentVersion where id = : cv.id].ContentDocumentId;
        system.debug('cdId'+cdId);
        ContentDocument cd = new ContentDocument();
        cd.id = cdId;
         
        try{
       
                delete cd;
            
        }
        catch(Exception ex){
            system.debug('cdId'+ex.getMessage());
            system.Assert(ex.getMessage().contains('You do not have access to delete this File.'));
        }
        }
         test.stopTest();
    }*/
    
    //Added by Prachi -- SSE-21596
     @isTest
    public static void testavoidDeleteAutoGeneratedCSV(){
     test.startTest();

         User commUser = [Select id from user where Profile.name = 'Commercial' and IsActive = true limit 1];
         Account acc = new Account(name= 'Testname_AccountPlan' ,Status__c='Approved',
                                  Billing_Address_Line_1__c='test',Billing_City__c='Test City',
                                  Billing_Country__c='India',Billing_State__c='Test',Industry= 'Legal',
                                  Billing_ZIP_Postal_Code__c='1100110',BU__c='China - CN1');
        insert acc;
        
        Account_Plan__c ap = new Account_Plan__c(Account_Name__c = acc.id,Quarter__c ='Q1',
                                                 Year__c='2023',Account_Plan_Status__c ='Draft');
        insert ap;
        
         Account_Plan__c ap1 = new Account_Plan__c(Account_Name__c = acc.id,Quarter__c ='Q1',
                                                 Year__c='2023',Account_Plan_Status__c ='Draft');
        insert ap1;
       
        ContentVersion cv = new ContentVersion();
        cv.ContentLocation = 'S';
        cv.Title = 'Test CV';
        cv.PathOnClient = 'Test CV' + '.csv';
        cv.SharingPrivacy = 'N' ;
        cv.SharingOption = 'A';
        cv.IsMajorVersion = true;  
        cv.FirstPublishLocationId = ap.id;
        cv.VersionData = Blob.valueOf('Testing File');
        cv.Description = 'This is an autogenerated csv for Uploaded Contacts.';   
        insert cv;
        
        Id cdId = [Select id , ContentDocumentId from ContentVersion where id = : cv.id].ContentDocumentId;
        system.debug('cdId'+cdId);
        ContentDocument cd = new ContentDocument();
        cd.id = cdId;
         
        try{
       
                delete cd;
            
        }
        catch(Exception ex){
            system.debug('cdId'+ex.getMessage());
            system.Assert(ex.getMessage().contains('You do not have access to delete this File.'));
        }
        
         test.stopTest();
    }
}