force-app/main/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Number__c</fullName>
        <description>For use with integration to SUN &amp; PSA</description>
        <displayFormat>D{0000000}</displayFormat>
        <externalId>true</externalId>
        <label>Account Number</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>BU__c</fullName>
        <label>BU</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Master_BUs</valueSetName>
        </valueSet>
    </fields>
</CustomObject>

objects/Account_Configuration__mdt.object
<CustomObject>
    <description>PCIPAL-NVM. This lists the payment flows that have been configured on the Agent Assist service.</description>
    <fields>
        <fullName>BU__c</fullName>
        <label>BU</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Account Configuration</label>
    <pluralLabel>Account Configurations</pluralLabel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>Assigned_To__c</fullName>
        <description>Call Assignment selection to redirect cases to correct Regional Helpdesk</description>
        <inlineHelpText>Only raise a case to Legal following discussion with your Manager or Team Leader</inlineHelpText>
        <label>Assigned To</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>!!Please Select a Helpdesk!!</fullName>
                </value>
                <value>
                    <fullName>Accounts Receivable</fullName>
                </value>
                <value>
                    <fullName>AM APAC Technical Support</fullName>
                </value>
                <value>
                    <fullName>AM China Technical Support</fullName>
                </value>
                <value>
                    <fullName>AM EMEA Technical Support</fullName>
                </value>
                <value>
                    <fullName>Americas Client Helpdesk</fullName>
                </value>
                <value>
                    <fullName>AM Presales</fullName>
                </value>
                <value>
                    <fullName>AMS PS Branding</fullName>
                </value>
                <value>
                    <fullName>AMS PS Cases</fullName>
                </value>
                <value>
                    <fullName>AM US Technical Support</fullName>
                </value>
                <value>
                    <fullName>APAC client helpdesk</fullName>
                </value>
                <value>
                    <fullName>APAC Customer Experience</fullName>
                </value>
                <value>
                    <fullName>APAC Helpdesk</fullName>
                </value>
                <value>
                    <fullName>APAC Technical Support</fullName>
                </value>
                <value>
                    <fullName>Bureau</fullName>
                </value>
                <value>
                    <fullName>Bureau helpdesk</fullName>
                </value>
                <value>
                    <fullName>CEB Sunstone Analytics Client Advisors</fullName>
                </value>
                <value>
                    <fullName>China Customer Experience</fullName>
                </value>
                <value>
                    <fullName>China Technical Support</fullName>
                </value>
                <value>
                    <fullName>CSIT</fullName>
                </value>
                <value>
                    <fullName>Customer Collections</fullName>
                </value>
                <value>
                    <fullName>Customer Experience</fullName>
                </value>
                <value>
                    <fullName>Customer Experience general</fullName>
                </value>
                <value>
                    <fullName>Customer Experience onboarding</fullName>
                </value>
                <value>
                    <fullName>Customer Systems Training</fullName>
                </value>
                <value>
                    <fullName>EMEA Customer Experience</fullName>
                </value>
                <value>
                    <fullName>EMEA TAM</fullName>
                </value>
                <value>
                    <fullName>EMEA Technical Support</fullName>
                </value>
                <value>
                    <fullName>General</fullName>
                </value>
                <value>
                    <fullName>India APAC Technical Support</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Building_Name__c</fullName>
        <label>Building Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Call_Type__c</fullName>
        <description>From call logging</description>
        <label>Case Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Account Manager Referral</fullName>
                </value>
                <value>
                    <fullName>Assessment Preview</fullName>
                </value>
                <value>
                    <fullName>Candidate Support call</fullName>
                </value>
                <value>
                    <fullName>Courses/Training/Qualifications</fullName>
                </value>
                <value>
                    <fullName>Course Sales / Bookings</fullName>
                </value>
                <value>
                    <fullName>DC Enquiry</fullName>
                </value>
                <value>
                    <fullName>Delivery/Returns</fullName>
                </value>
                <value>
                    <fullName>Demo</fullName>
                </value>
                <value>
                    <fullName>Demo Actual Responses Report</fullName>
                </value>
                <value>
                    <fullName>Disability query</fullName>
                </value>
                <value>
                    <fullName>Distributors Orders</fullName>
                </value>
                <value>
                    <fullName>External Sales/Marketing call</fullName>
                </value>
                <value>
                    <fullName>Goodwill gesture</fullName>
                </value>
                <value>
                    <fullName>Internal Product Support</fullName>
                </value>
                <value>
                    <fullName>Internal SHL support</fullName>
                </value>
                <value>
                    <fullName>Invoice/Credit/Licence</fullName>
                </value>
                <value>
                    <fullName>Lead Qualifications &amp; Processing</fullName>
                </value>
                <value>
                    <fullName>Leased Materials</fullName>
                </value>
                <value>
                    <fullName>Legacy/offline support</fullName>
                </value>
                <value>
                    <fullName>Managed Services</fullName>
                </value>
                <value>
                    <fullName>Onboarding</fullName>
                </value>
                <value>
                    <fullName>Order Investigation</fullName>
                </value>
                <value>
                    <fullName>Order Placed</fullName>
                </value>
                <value>
                    <fullName>P&amp;P/Book Orders</fullName>
                </value>
                <value>
                    <fullName>Partners</fullName>
                </value>
                <value>
                    <fullName>Phone Issue</fullName>
                </value>
                <value>
                    <fullName>Phone Issues</fullName>
                </value>
                <value>
                    <fullName>PO Number Received</fullName>
                </value>
                <value>
                    <fullName>Pricing Queries</fullName>
                </value>
                <value>
                    <fullName>Product Consulting</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Case_Country__c</fullName>
        <description>Read only for self service web to case 3 digit country code.</description>
        <inlineHelpText>Read only for self service web to case 3 digit country code.</inlineHelpText>
        <label>Case Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AUS</fullName>
                </value>
                <value>
                    <fullName>CHN</fullName>
                </value>
                <value>
                    <fullName>DEU</fullName>
                </value>
                <value>
                    <fullName>DNK</fullName>
                </value>
                <value>
                    <fullName>FIN</fullName>
                </value>
                <value>
                    <fullName>FRA</fullName>
                </value>
                <value>
                    <fullName>GBR</fullName>
                </value>
                <value>
                    <fullName>IND</fullName>
                </value>
                <value>
                    <fullName>ITA</fullName>
                </value>
                <value>
                    <fullName>NLD</fullName>
                </value>
                <value>
                    <fullName>NOR</fullName>
                </value>
                <value>
                    <fullName>SWE</fullName>
                </value>
                <value>
                    <fullName>USA</fullName>
                </value>
                <value>
                    <fullName>ZAF</fullName>
                </value>
                <value>
                    <fullName>AFG</fullName>
                </value>
                <value>
                    <fullName>AGO</fullName>
                </value>
                <value>
                    <fullName>ALB</fullName>
                </value>
                <value>
                    <fullName>AND</fullName>
                </value>
                <value>
                    <fullName>ARE</fullName>
                </value>
                <value>
                    <fullName>ARG</fullName>
                </value>
                <value>
                    <fullName>ARM</fullName>
                </value>
                <value>
                    <fullName>ATG</fullName>
                </value>
                <value>
                    <fullName>AUT</fullName>
                </value>
                <value>
                    <fullName>AZE</fullName>
                </value>
                <value>
                    <fullName>BDI</fullName>
                </value>
                <value>
                    <fullName>BEL</fullName>
                </value>
                <value>
                    <fullName>BEN</fullName>
                </value>
                <value>
                    <fullName>BFA</fullName>
                </value>
                <value>
                    <fullName>BGD</fullName>
                </value>
                <value>
                    <fullName>BGR</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>City_town__c</fullName>
        <label>City/town</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>Cardholder’s First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Cardholder’s Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ref_Type__c</fullName>
        <label>Ref Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>INV</fullName>
                </value>
                <value>
                    <fullName>ORD</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sun_Reference_No__c</fullName>
        <label>Sun Reference No.</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zip_Postal__c</fullName>
        <label>Zip/Postal</label>
        <length>50</length>
        <type>Text</type>
    </fields>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>BU__c</fullName>
        <formula>text(Account.BU__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>BU</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mailing_ZIP_Postal_Code__c</fullName>
        <label>ZIP/Postal Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
</CustomObject>

force-app/main/objects/KB_CaseCountryCodeAndAssignmentEmails__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>To have country code, help desk assignments,and the respective emails for Technical Support</description>
    <fields>
        <fullName>Assigned_To__c</fullName>
        <label>Assigned To</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>KB_CaseCountryCodeAndAssignmentEmails</label>
</CustomObject>

force-app/main/objects/Order.object
<CustomObject>
    <fields>
        <fullName>BU__c</fullName>
        <formula>TEXT(Account.BU__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>BU</label>
        <type>Text</type>
    </fields>
</CustomObject>

classes/NVM_Payment_Form_Controller.cls
/**************************************************************************************************************************************
CREATED BY :- RISHABH KANOTRA
CREATED DATE :- 26-06-2019
DESCRIPTION :- This is a payment form to: 
               (1.Prepopulate the data from the Case record), 
               (2. Fetch data from the agent and pass on to the PCIPAL form.)
***************************************************************************************************************************************/ 

public class NVM_Payment_Form_Controller{
  
    public Boolean showpg{get;set;}
    public Boolean countryflag{get;set;}
    public Boolean showwar{get;set;}
    public Boolean shownoagent{get;set;}
    public Boolean samecont{get;set;}
    public String CallerNamestr{get;set;}
    public String Sunrefnovf{get;set;}
    public String reftypevf{get;set;}
    
    public String agentid{get;set;}
    public String CardType{get;set;}
    public String conFirstName{get;set;}
    public String conLastName{get;set;}
    public String buildingname{get;set;}
    public String street{get;set;}
    public String city{get;set;}
    public String zip{get;set;}
    public String country{get;set;}
    public String state{get;set;}
    public String acccurrency{get;set;}
    public Decimal accamount{get;set;}
    public String selectedCurrency{get;set;}
    public String selectedCountry{get;set;}
    public List<Account_Configuration__mdt> curList {get;set;}
    public List<Account_Configuration__mdt> availbu {get;set;}
    public List<KB_CaseCountryCodeAndAssignmentEmails__c> conList {get;set;}
    public List<String> curcode = new List<String>();
    public List<String> curname {get;set;}

    
    //public String inputText1{get;set;} 
    //public String inputText2{get;set;} 
    //public String inputText3{get;set;} 
    //public String inputText4{get;set;}
    public Id Cid;
    public Id Uid;
    public Case c;
    public User u;
    
    ApexPages.StandardController scn;
        
    public NVM_Payment_Form_Controller(ApexPages.StandardController controller) {       
        scn = controller;
        showpg=true;   
        countryflag=false;
        
       Uid =  UserInfo.getUserId();
       u =[SELECT id,NVMContactWorld__NVM_Agent_Id__c FROM USER WHERE id =:Uid LIMIT 1 ];
       //To disable page if user is not agent
       if(u.NVMContactWorld__NVM_Agent_Id__c == NULL){
           
            showpg=false;
            showwar=false;
            shownoagent=true;
       
       }
       agentid=u.NVMContactWorld__NVM_Agent_Id__c ;
    
       Cid = System.currentPagereference().getParameters().get('id');
       c = [Select id,Sun_Reference_No__c,Ref_Type__c,Account.name,Case_Country__c,Account.Account_Number__c,CurrencyIsoCode ,Contact.Email,Country__c,State__c,First_Name__c,Last_Name__c,Building_Name__c,Street__c,Status,City_town__c,Zip_Postal__c,Call_Type__c,Assigned_To__c  ,Account.BU__c, Account.CurrencyIsoCode,Contact.Mailing_ZIP_Postal_Code__c,Contact.Mailing_Country__c,Contact.Mailing_State_County__c,Contact.Mailing_City__c,contact.name,Contact.FirstName,Contact.LastName, contact.Mailing_Address_Line_1__c, contact.Mailing_Address_Line_2__c, contact.Mailing_Address_Line_3__c, contact.Mailing_Address_Line_4__c  from Case where id =: Cid];
        
       availbu =[select BU__c from Account_Configuration__mdt where BU__c =: c.Account.Bu__c ];
       system.debug('This is availbu**'+ availbu+availbu.isEmpty() );
        //code to disable button
            if( ( availbu.isEmpty()) || c.Status == 'Resolved/Closed' || c.Call_Type__c!='Invoice/Credit/Licence' || c.Assigned_To__c == NULL){
                showpg=false;
                showwar=true;
            }
        
        selectedCurrency = c.CurrencyIsoCode;
        selectedCountry = c.Case_Country__c;
        CallerNamestr = c.contact.name;
        Sunrefnovf = c.Sun_Reference_No__c;
        reftypevf = c.Ref_Type__c;
        
        samecont =True; // setting checkbox by default true
        
        if(samecont == True){
            conFirstName = c.First_Name__c;
            conLastName = c.Last_Name__c;
            buildingname= c.Building_Name__c;        
            street = c.Street__c;
            city = c.City_town__c;
            zip = c.Zip_Postal__c;
            country = c.Country__c;
            state = c.State__c;
            
        }
    
    }
    
    public pagereference CallWebService(){
        System.debug('hello');     
        String token; 
        NVM_PaymentController nv = new NVM_PaymentController();
        token = nv.PaymentGetToken(c);
        System.debug('**token ' + token);
        System.debug('**amount ' + accamount);
        
        if(countryflag==true){
        
        return null;
        
        
        }
        else{
        if(token != null && token != ''){
           System.debug('Starting PCI Session');
           System.debug('**Case ' + c.id);
           return(nv.StartPCISession(token,c,accamount,u));          
        }
        else{
            return null;
        }
        
        }
    }
    
    public void save(){
       
            c.Caller_s_Name__c = CallerNamestr;
            c.Ref_Type__c = reftypevf;
            c.Sun_Reference_No__c = Sunrefnovf;
            c.First_Name__c= conFirstName;
            c.Last_Name__c= conLastName;
            c.Building_Name__c= buildingname;
            c.Street__c = street;
            c.City_town__c= city;
            c.Zip_Postal__c= zip;
            c.Country__c= selectedCountry;
            c.State__c = state;       
            
            
            
            //PageReference nextPage = new PageReference('/apex/PaymentCardDetailsVF?amt='+accamount+ '&Cid=' + c.id + '&Ctype=' +  CardType );
            //return nextPage;
            
            System.debug('This is new currency'+ selectedCurrency);
            c.CurrencyIsoCode = selectedCurrency;
            c.Case_Country__c=selectedCountry;
            System.debug('This is new case currency'+ c.CurrencyIsoCode);
            
            
            System.debug('testselectedCountry***' + selectedCountry +'**state.length' + state.length());
            if(selectedCountry == 'USA' && state.length()!=2){
            
                System.debug('2testselectedCountry***' + selectedCountry +'**state.length' + state.length());
                //ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'Please enter valid data'));  
                countryflag=true;
                //return null;
            
            }
            
            else{
                
                countryflag=false;
           
                update c;
               //scn.save();
                
               // c.CurrencyIsoCode = selectedCurrency;
                //update c;
            }
           // System.debug('**case ' + c);
           // return null;
            
      
    }
    
    public void changeconinfo(){
          System.debug('This is value of samecont' + samecont ); 
        if(samecont == False){
        
            System.debug('This is value of samecont2' + samecont );
            conFirstName = '';
            conLastName = '';
            buildingname= '';       
            street = '';
            city = '';
            zip = '';
            //country = '';
            state = '';
            
            
         }
         
         else if(samecont == True){
         
            conFirstName = c.First_Name__c;
            conLastName = c.Last_Name__c;
            buildingname= c.Building_Name__c;        
            street = c.Street__c;
            city = c.City_town__c;
            zip = c.Zip_Postal__c;
            //country = c.Country__c;
            state = c.State__c;
            
         }
    
    }
    
    
    public List<SelectOption> getCurrencyOption() {
        List<SelectOption> options = new List<SelectOption>();
        curList = [select BU__c, Currency__c,CurrencyNames__c from Account_Configuration__mdt where BU__c =:c.Account.BU__c];
        for(Account_Configuration__mdt acc : curList ) {
        
            //if(!curcode.contains(acc.Currency__c)){
            
                options.add(new SelectOption(acc.Currency__c,acc.CurrencyNames__c ));
               // curcode.add(acc.Currency__c);
            //}
        }
        return options;
    }
    
    public List<SelectOption> getCountryOption () {
        List<SelectOption> options = new List<SelectOption>();
        conList = [select Name,ISO3__c from KB_CaseCountryCodeAndAssignmentEmails__c where ISO3__c!= null ORDER BY Name];
        for(KB_CaseCountryCodeAndAssignmentEmails__c kbc: conList ) {
        
            //if(!curcode.contains(acc.Currency__c)){
            
                options.add(new SelectOption(kbc.ISO3__c,kbc.Name ));
               // curcode.add(acc.Currency__c);
            //}
        }
        return options;
    }

}