force-app/main/objects/Account.object
<CustomObject>
    <fields>
        <fullName>BU__c</fullName>
        <label>BU</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Master_BUs</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Billing_Address_Line_1__c</fullName>
        <inlineHelpText>If the address goes over more than one line then please use Address Line 2 and Address Line 3. This formatting will display on any Customer facing documents.</inlineHelpText>
        <label>Billing Address Line 1</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_City__c</fullName>
        <label>Billing City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_Country__c</fullName>
        <label>Billing Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AFGHANISTAN</fullName>
                </value>
                <value>
                    <fullName>ALBANIA</fullName>
                </value>
                <value>
                    <fullName>ALDERNEY</fullName>
                </value>
                <value>
                    <fullName>ALGERIA</fullName>
                </value>
                <value>
                    <fullName>AMERICAN SAMOA</fullName>
                </value>
                <value>
                    <fullName>ANDORRA</fullName>
                </value>
                <value>
                    <fullName>ANGOLA</fullName>
                </value>
                <value>
                    <fullName>ANGUILLA</fullName>
                </value>
                <value>
                    <fullName>ANTARCTICA</fullName>
                </value>
                <value>
                    <fullName>ANTIGUA AND BARBUDA</fullName>
                </value>
                <value>
                    <fullName>ARGENTINA</fullName>
                </value>
                <value>
                    <fullName>ARMENIA</fullName>
                </value>
                <value>
                    <fullName>ARUBA</fullName>
                </value>
                <value>
                    <fullName>AUSTRALIA</fullName>
                </value>
                <value>
                    <fullName>AUSTRIA</fullName>
                </value>
                <value>
                    <fullName>AZERBAIJAN</fullName>
                </value>
                <value>
                    <fullName>BAHAMAS</fullName>
                </value>
                <value>
                    <fullName>BAHRAIN</fullName>
                </value>
                <value>
                    <fullName>BANGLADESH</fullName>
                </value>
                <value>
                    <fullName>BARBADOS</fullName>
                </value>
                <value>
                    <fullName>BELARUS</fullName>
                </value>
                <value>
                    <fullName>BELGIUM</fullName>
                </value>
                <value>
                    <fullName>BELIZE</fullName>
                </value>
                <value>
                    <fullName>BENIN</fullName>
                </value>
                <value>
                    <fullName>BERMUDA</fullName>
                </value>
                <value>
                    <fullName>BHUTAN</fullName>
                </value>
                <value>
                    <fullName>BOLIVIA</fullName>
                </value>
                <value>
                    <fullName>BOSNIA AND HERZEGOWINA</fullName>
                </value>
                <value>
                    <fullName>BOTSWANA</fullName>
                </value>
                <value>
                    <fullName>BOUVET ISLAND</fullName>
                </value>
                <value>
                    <fullName>INDIA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Billing_State__c</fullName>
        <inlineHelpText>If State is required, please enter as two alphanumeric characters, e.g. GA instead of Georgia</inlineHelpText>
        <label>Billing State/County</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_ZIP_Postal_Code__c</fullName>
        <label>Billing ZIP/Postal Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Global_Billing_Country__c</fullName>
        <description>This is the new field created for making the country value set consistent over all modules in Salesforce.</description>
        <label>Billing Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Global_Country_Picklist</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <formula>TEXT(Territory__r.Region__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Region</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Same_As_The_Billing_Address__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Same As The Billing Address</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Territory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Territory</label>
        <lookupFilter>
            <active>false</active>
            <errorMessage>Territory associated with an account should be active</errorMessage>
            <filterItems>
                <field>Territory__c.Is_Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Territory__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

force-app/main/objects/AutomaticJobCreation__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>MS_Line_of_Business__c</fullName>
        <label>MS - Line of Business</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>AutomaticJobCreation</label>
</CustomObject>

objects/Discount_Approval_Category__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Europe</fullName>
                </value>
                <value>
                    <fullName>ANZ</fullName>
                </value>
                <value>
                    <fullName>AMS</fullName>
                </value>
                <value>
                    <fullName>India</fullName>
                </value>
                <value>
                    <fullName>Asia</fullName>
                </value>
                <value>
                    <fullName>Middle East</fullName>
                </value>
                <value>
                    <fullName>China</fullName>
                </value>
                <value>
                    <fullName>GBL</fullName>
                </value>
                <value>
                    <fullName>Hong Kong</fullName>
                </value>
                <value>
                    <fullName>Indonesia</fullName>
                </value>
                <value>
                    <fullName>SEA</fullName>
                </value>
                <value>
                    <fullName>ESA</fullName>
                    <isActive>false</isActive>
                    <label>ESA</label>
                </value>
                <value>
                    <fullName>ME</fullName>
                    <isActive>false</isActive>
                    <label>ME</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Product</fullName>
                </value>
                <value>
                    <fullName>Services</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Discount Approval Category</label>
    <nameField>
        <label>Discount Approval Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Discount Approval Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Actual_Contract_Duration__c</fullName>
        <label>Actual Contract Duration</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Business_Type__c</fullName>
        <description>Choose the Opportunity Type that best describes the type of business pursued.  
Reboost should only be used with In-Advance clients. 
Cross-sell is simply New Business with a client that has a current commercial relationship.</description>
        <label>Opportunity Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Expansion</fullName>
                </value>
                <value>
                    <fullName>Renewal</fullName>
                </value>
                <value>
                    <fullName>Debooking</fullName>
                    <label>Debooking / Adjustment</label>
                </value>
                <value>
                    <fullName>Extension</fullName>
                </value>
                <value>
                    <fullName>In Arrears</fullName>
                </value>
                <value>
                    <fullName>In Advance</fullName>
                </value>
                <value>
                    <fullName>Managed Services</fullName>
                </value>
                <value>
                    <fullName>Professional Services: non-subscription</fullName>
                </value>
                <value>
                    <fullName>Top Up / Addition</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Discount_Approval_Status__c</fullName>
        <label>Discount Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Applicable for Approval</fullName>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Recalled</fullName>
                </value>
                <value>
                    <fullName>Escalated Level 1</fullName>
                </value>
                <value>
                    <fullName>Escalated Level 2</fullName>
                </value>
                <value>
                    <fullName>Re-Approval Required</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Products_Discount__c</fullName>
        <label>Contract Product Discount</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Services_Discount__c</fullName>
        <label>Contract Service Discount</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
</CustomObject>

force-app/main/objects/Territory__c.object
<CustomObject>
    <fields>
        <fullName>CRO__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CRO</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Territories8</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Commercial_Director__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Commercial Director</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Territories6031</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MD__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Managing Director</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Territories9</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Region</valueSetName>
        </valueSet>
    </fields>
    <label>Territory</label>
    <nameField>
        <label>Territory</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/objects/Trigger_Activation__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This List is used to activate/deactivate trigger while deployment.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Trigger Activation</label>
</CustomObject>

globalValueSets/Global_Country_Picklist.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>AFGHANISTAN</fullName>
    </customValue>
    <customValue>
        <fullName>ALBANIA</fullName>
    </customValue>
    <customValue>
        <fullName>ALDERNEY</fullName>
    </customValue>
    <customValue>
        <fullName>ALGERIA</fullName>
    </customValue>
    <customValue>
        <fullName>AMERICAN SAMOA</fullName>
    </customValue>
    <customValue>
        <fullName>ANDORRA</fullName>
    </customValue>
    <customValue>
        <fullName>ANGOLA</fullName>
    </customValue>
    <customValue>
        <fullName>ANGUILLA</fullName>
    </customValue>
    <customValue>
        <fullName>ANTARCTICA</fullName>
    </customValue>
    <customValue>
        <fullName>ANTIGUA AND BARBUDA</fullName>
    </customValue>
    <customValue>
        <fullName>ARGENTINA</fullName>
    </customValue>
    <customValue>
        <fullName>ARMENIA</fullName>
    </customValue>
    <customValue>
        <fullName>ARUBA</fullName>
    </customValue>
    <customValue>
        <fullName>AUSTRALIA</fullName>
    </customValue>
    <customValue>
        <fullName>AUSTRIA</fullName>
    </customValue>
    <customValue>
        <fullName>AZERBAIJAN</fullName>
    </customValue>
    <customValue>
        <fullName>BAHAMAS</fullName>
    </customValue>
    <customValue>
        <fullName>BAHRAIN</fullName>
    </customValue>
    <customValue>
        <fullName>BANGLADESH</fullName>
    </customValue>
    <customValue>
        <fullName>BARBADOS</fullName>
    </customValue>
    <customValue>
        <fullName>BELARUS</fullName>
    </customValue>
    <customValue>
        <fullName>BELGIUM</fullName>
    </customValue>
    <customValue>
        <fullName>BELIZE</fullName>
    </customValue>
    <customValue>
        <fullName>BENIN</fullName>
    </customValue>
    <customValue>
        <fullName>BERMUDA</fullName>
    </customValue>
    <customValue>
        <fullName>BHUTAN</fullName>
    </customValue>
    <customValue>
        <fullName>BOLIVIA</fullName>
    </customValue>
    <customValue>
        <fullName>BOSNIA AND HERZEGOWINA</fullName>
    </customValue>
    <customValue>
        <fullName>BOTSWANA</fullName>
    </customValue>
    <customValue>
        <fullName>BOUVET ISLAND</fullName>
    </customValue>
    <customValue>
        <fullName>INDIA</fullName>
    </customValue>
    <description>used as a global picklist over all the modules in salesforce</description>
    <masterLabel>Global Country Picklist</masterLabel>
</GlobalValueSet>

globalValueSets/Master_BUs.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Abu Dhabi - AD1</fullName>
    </customValue>
    <customValue>
        <fullName>Australia - AU1</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium SPS - BE5</fullName>
    </customValue>
    <customValue>
        <fullName>Canada - CA1</fullName>
    </customValue>
    <customValue>
        <fullName>China - CN1</fullName>
    </customValue>
    <customValue>
        <fullName>Denmark - DK1</fullName>
    </customValue>
    <customValue>
        <fullName>Finland - FI1</fullName>
    </customValue>
    <customValue>
        <fullName>France SPS - FR5</fullName>
    </customValue>
    <customValue>
        <fullName>Germany SPS - DE5</fullName>
    </customValue>
    <customValue>
        <fullName>Hong Kong - HK1</fullName>
    </customValue>
    <customValue>
        <fullName>India - IN1</fullName>
    </customValue>
    <customValue>
        <fullName>Italy - IT1</fullName>
    </customValue>
    <customValue>
        <fullName>Middle East - ME1</fullName>
    </customValue>
    <customValue>
        <fullName>Netherlands SPS - NL5</fullName>
    </customValue>
    <customValue>
        <fullName>New Zealand - NZ1</fullName>
    </customValue>
    <customValue>
        <fullName>Norway - NO1</fullName>
    </customValue>
    <customValue>
        <fullName>Philippines - PH1</fullName>
    </customValue>
    <customValue>
        <fullName>Saudi Arabia - SA5</fullName>
    </customValue>
    <customValue>
        <fullName>Singapore - SG1</fullName>
    </customValue>
    <customValue>
        <fullName>South Africa - ZA1</fullName>
    </customValue>
    <customValue>
        <fullName>Sweden - SE1</fullName>
    </customValue>
    <customValue>
        <fullName>Switzerland - CH1</fullName>
    </customValue>
    <customValue>
        <fullName>UK - UK1</fullName>
    </customValue>
    <customValue>
        <fullName>US - US5</fullName>
    </customValue>
    <customValue>
        <fullName>Indonesia - ID1</fullName>
    </customValue>
    <customValue>
        <fullName>Asia Pac	India</fullName>
        <isActive>false</isActive>
        <label>Asia Pac	India</label>
    </customValue>
    <customValue>
        <fullName>Asia Pac	Singapore</fullName>
        <isActive>false</isActive>
        <label>Asia Pac	Singapore</label>
    </customValue>
    <customValue>
        <fullName>Asia Pac	AP Region</fullName>
        <isActive>false</isActive>
        <label>Asia Pac	AP Region</label>
    </customValue>
    <customValue>
        <fullName>UK	  - UK1</fullName>
        <isActive>false</isActive>
        <label>UK	  - UK1</label>
    </customValue>
    <customValue>
        <fullName>Head Office  - H50</fullName>
        <isActive>false</isActive>
        <label>Head Office  - H50</label>
    </customValue>
    <masterLabel>Master BUs</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

globalValueSets/Region.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>ANZ</fullName>
    </customValue>
    <customValue>
        <fullName>Core AMS</fullName>
    </customValue>
    <customValue>
        <fullName>Core EU</fullName>
    </customValue>
    <customValue>
        <fullName>Core UKI</fullName>
    </customValue>
    <customValue>
        <fullName>Distributors</fullName>
    </customValue>
    <customValue>
        <fullName>Enterprise AMS</fullName>
    </customValue>
    <customValue>
        <fullName>Enterprise North EU</fullName>
    </customValue>
    <customValue>
        <fullName>Enterprise South EU</fullName>
    </customValue>
    <customValue>
        <fullName>Enterprise UKI</fullName>
    </customValue>
    <customValue>
        <fullName>Growth UK/EU</fullName>
    </customValue>
    <customValue>
        <fullName>Hong Kong</fullName>
    </customValue>
    <customValue>
        <fullName>India</fullName>
    </customValue>
    <customValue>
        <fullName>Middle East</fullName>
    </customValue>
    <customValue>
        <fullName>NB AMS</fullName>
    </customValue>
    <customValue>
        <fullName>NB Core</fullName>
    </customValue>
    <customValue>
        <fullName>NB Enterprise</fullName>
    </customValue>
    <customValue>
        <fullName>NB Partner</fullName>
    </customValue>
    <customValue>
        <fullName>Other AMS</fullName>
    </customValue>
    <customValue>
        <fullName>Partners AMS</fullName>
    </customValue>
    <customValue>
        <fullName>Philippines</fullName>
    </customValue>
    <customValue>
        <fullName>Singapore</fullName>
    </customValue>
    <customValue>
        <fullName>South Africa</fullName>
    </customValue>
    <customValue>
        <fullName>Strategic EU</fullName>
    </customValue>
    <customValue>
        <fullName>Strategic UKI</fullName>
    </customValue>
    <customValue>
        <fullName>China East</fullName>
    </customValue>
    <customValue>
        <fullName>China North</fullName>
    </customValue>
    <customValue>
        <fullName>China Partner</fullName>
    </customValue>
    <customValue>
        <fullName>China South</fullName>
    </customValue>
    <customValue>
        <fullName>China Enterprise</fullName>
    </customValue>
    <customValue>
        <fullName>China Core</fullName>
    </customValue>
    <customValue>
        <fullName>AMS</fullName>
    </customValue>
    <masterLabel>Region</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

classes/ApprovalHistoryControllerTest.cls
@IsTest
public class ApprovalHistoryControllerTest {
 
    static Id oppId;
 
    @TestSetup
    static void setupData() {
 
        insert new List<Trigger_Activation__c>{
            new Trigger_Activation__c(Name='Account_Trigger',Active__c=true),
            new Trigger_Activation__c(Name='Task_Trigger',Active__c=true),
            new Trigger_Activation__c(Name='User_Trigger',Active__c=true),
            new Trigger_Activation__c(Name='Opportunity_Trigger',Active__c=true),
            new Trigger_Activation__c(Name='Territory_Trigger',Active__c=true),
            new Trigger_Activation__c(Name='Contact_Trigger',Active__c=true),
            new Trigger_Activation__c(Name='Job_Trigger',Active__c=true)
        };
 
        // User
        Profile p = [SELECT Id FROM Profile WHERE Name='Standard User' LIMIT 1];
        
        // Custom Setting for Auto Job creation
        AutomaticJobCreation__c cs = new AutomaticJobCreation__c();
        cs.Name='Values';
        cs.MS_Line_of_Business__c = 'TA - Corporate,Talent Management,TA - Credentialing';
        INSERT cs;

        User bdm = new User(
            Alias='bdm',
            Email='bdm@test.com',
            EmailEncodingKey='UTF-8',
            LastName='BDM',
            LanguageLocaleKey='en_US',
            LocaleSidKey='en_US',
            ProfileId=p.Id,
            TimeZoneSidKey='Asia/Kolkata',
            UserName='bdm' + System.currentTimeMillis() + '@test.com'
        );
        insert bdm;
 
        // Territory
        Territory__c terr = new Territory__c(
            Name='Test Territory',
            Region__c='AMS',
            Commercial_Director__c=bdm.Id,
            CRO__c=bdm.Id,
            MD__c=bdm.Id
        );
        insert terr;
 
        // Account
        Account acc = new Account(
            Name='Test Account',
            BU__c='UK - UK1',
            CurrencyIsoCode='GBP',
            Industry='Agriculture',
            Billing_Address_Line_1__c='Line1',
            Billing_City__c='City',
            Same_As_The_Billing_Address__c=true,
            Billing_Country__c='INDIA',
            Billing_State__c='State',
            Billing_ZIP_Postal_Code__c='Zip',
            Global_Billing_Country__c='AFGHANISTAN',
            Territory__c=terr.Id
        );
        insert acc;
 
        // Opportunity
        Opportunity opp = new Opportunity(
            Name='Test Opportunity',
            AccountId=acc.Id,
            CloseDate=Date.today(),
            StageName='Information Gathering',
            Discount_Approval_Status__c='Applicable for Approval',
            Amount=77000,
            Products_Discount__c=20,
            Services_Discount__c=5,
            Business_Type__c='Expansion',
            Actual_Contract_Duration__c=12,
            Forecast_Category__c='Pipeline',
            Discount_Reason_Code__c='Strategic Deal',
            Discount_Reason_Justification__c='Test justification'
        );
        insert opp;
        
        // Discount Category
        insert new Discount_Approval_Category__c(
            Name='Test Category',
            Active__c=true,
            Type__c='Product',
            Region__c='AMS',
            Minimum_ACV__c=0,
            Maximum_ACV__c=300000,
            Minimum_Discount__c=0,
            Maximum_Discount__c=50,
            Original_Approver_DOA__c='Commercial_Director__c',
            Escalation_Level_1_DOA__c='CRO__c',
            Escalation_Level_2_DOA__c='MD__c',
            Approval_Strategy__c = 'ALL'
        );
        

        oppId = opp.Id;
    }
    @IsTest
    static void testFlowApprovalCoverage() {
 
        Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1];
 
        Test.startTest();
        
        opp.Discount_Approval_Status__c='Submitted for Approval';
        UPDATE opp;
        Test.stopTest();
        List<ApprovalHistoryController.ApprovalRowDTO> rows = ApprovalHistoryController.getApprovalRows(opp.Id);
 
        //System.assertNotEquals(null, rows);
        //System.assert(rows.size() >= 0); // safer assertion
    }
}