force-app/main/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>1. Not yet trading with SHL - (definition - the account is new and/or has no trading history with SHL to date)
2. Trading with SHL - (definition - the account has sales recorded with SHL in the last 2 years)
3. Ceased Trading with SHL - (definition - the account has not traded with SHL in the past 12 months but has previously.) 
4. Dead - (Gone out of Business) (definition - The Account for whatever reason is no longer a trading entity)
Previous Values
1. Active with SHL (definition - The account has a track record of sales and/or opportunities managed in the last 2 years)
2. Inactive with SHL (definition - The account is still a trading account but there has been no activity with SHL (sales or opportunities managed) in the last 2 years)</description>
        <inlineHelpText>Status indicates if Account is approved or not. If you believe an unapproved Account should be Approved, Submit for Approval.</inlineHelpText>
        <label>Account Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Unapproved</fullName>
                    <default>true</default>
                    <label>Unapproved</label>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Unapproved - Out of Business</fullName>
                </value>
                <value>
                    <fullName>Unapproved - Trade Not Allowed</fullName>
                </value>
                <value>
                    <fullName>Unapproved - Duplicate</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

force-app/main/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Business_Type__c</fullName>
        <description>Choose the Opportunity Type that best describes the type of business pursued.  
Reboost should only be used with In-Advance clients. 
Cross-sell is simply New Business with a client that has a current commercial relationship.</description>
        <label>Opportunity Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Expansion</fullName>
                </value>
                <value>
                    <fullName>Renewal</fullName>
                </value>
                <value>
                    <fullName>Debooking</fullName>
                    <label>Debooking / Adjustment</label>
                </value>
                <value>
                    <fullName>Extension</fullName>
                </value>
                <value>
                    <fullName>In Arrears</fullName>
                </value>
                <value>
                    <fullName>In Advance</fullName>
                </value>
                <value>
                    <fullName>Managed Services</fullName>
                </value>
                <value>
                    <fullName>Professional Services: non-subscription</fullName>
                </value>
                <value>
                    <fullName>Top Up / Addition</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity_Deal_Year__c</fullName>
        <defaultValue>1</defaultValue>
        <description>Current Deal Year of Opportunity</description>
        <label>Opportunity Year</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Variation_Reason__c</fullName>
        <label>Variation/ Extension Reason</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Addition to order</fullName>
                </value>
                <value>
                    <fullName>Reduction of order</fullName>
                </value>
                <value>
                    <fullName>Adjustment to order</fullName>
                </value>
                <value>
                    <fullName>Change to legal terms &amp; conditions</fullName>
                </value>
                <value>
                    <fullName>Change to payment terms</fullName>
                </value>
                <value>
                    <fullName>Change to SoW</fullName>
                </value>
                <value>
                    <fullName>Co-Terminating Cross Sell</fullName>
                </value>
                <value>
                    <fullName>Correction</fullName>
                </value>
                <value>
                    <fullName>Debooking</fullName>
                </value>
                <value>
                    <fullName>Excess Usage</fullName>
                </value>
                <value>
                    <fullName>In Arrears</fullName>
                </value>
                <value>
                    <fullName>Price List / Standing Order</fullName>
                </value>
                <value>
                    <fullName>Paid Subscription Extension</fullName>
                </value>
                <value>
                    <fullName>Service Delay – No Charge</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

force-app/main/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <formula>TEXT(PricebookEntry.Product2.Status__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
</CustomObject>

classes/EndOfLifeProducts.cls
public class EndOfLifeProducts {
    @AuraEnabled
    public static Boolean existEOFProducts(String recordId, String objectName){
        Boolean hasEOFProducts = false;
        
        hasEOFProducts = recordHasEOFProducts(recordId, objectName);

        return hasEOFProducts;
    }
    
    private static Boolean recordHasEOFProducts(String recordId, String objectName){
        Boolean hasEOFProducts = false;
        List<Opportunity> recordList = new List<Opportunity>();
		List<OpportunityLineItem> oliList = new List<OpportunityLineItem>();
        Id recTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('GCSC Opportunity').getRecordTypeId();
        
        if(objectName == 'Account'){
			recordList = [SELECT Id, (Select Id 
                                      From OpportunityLineItems
                                      Where Status__c = 'End of Life') 
                          From Opportunity 
                          Where AccountId =: recordId 
                          AND Opportunity_Deal_Year__c = 1 
                          AND Business_Type__c = 'Renewal'
                          AND (
                              (RecordTypeId =: recTypeId 
                               AND StageName != 'Closed Lost') 
                              OR 
                               (RecordTypeId !=: recTypeId 
                               //AND StageName != 'Verbal' 
                               AND StageName != 'Closed/Won' 
                               AND StageName != 'Closed Lost') 
                          )
                         ];
        }
        if(objectName == 'Opportunity'){
			recordList = [SELECT Id, (Select Id 
                                      From OpportunityLineItems
                                      Where Status__c = 'End of Life') 
                          From Opportunity 
                          Where Id =: recordId
                          AND Opportunity_Deal_Year__c = 1
                          AND (
                              (RecordTypeId =: recTypeId 
                               AND StageName != 'Closed Lost') 
                              OR 
                               (RecordTypeId !=: recTypeId 
                               //AND StageName != 'Verbal' 
                               AND StageName != 'Closed/Won' 
                               AND StageName != 'Closed Lost') 
                          ) AND Variation_Reason__c != 'Debooking'
                         ];
        }
		System.debug('recordList --' + recordList);
        if(recordList.size() > 0) {
            for(Opportunity opp : recordList){
                oliList = opp.OpportunityLineItems;
                if(oliList.size() > 0) {
                    hasEOFProducts = true;
                }                
            }
        }
        
        return hasEOFProducts;
    }
    
    
}