force-app/main/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Buying_Centre_Id__c</fullName>
        <description>Fro regional grouping of the same accounts, this field will be populated by the BI team.</description>
        <label>Buying Centre Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Number_of_Account_Plan__c</fullName>
        <defaultValue>0</defaultValue>
        <description>This is used to define how many Account Plan are currently present on Account.</description>
        <label>Number of Account Plan</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

force-app/main/objects/Account_Plan__c.object
<CustomObject>
    <description>Module to capture Key Account Plan details</description>
    <fields>
        <fullName>Account_Name__c</fullName>
        <description>This field is used to store the related account for Account Plan</description>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Plans</relationshipLabel>
        <relationshipName>Account_Plans</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Account_Plan_Name__c</fullName>
        <formula>&apos;SHL &apos; + Quarter__c + &quot;/&quot; + Year__c  + &quot; Account Plan - &quot; +   Account_Name__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Plan Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account_Plan_Status__c</fullName>
        <label>Account Plan Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>In Review</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Retired</fullName>
                </value>
                <value>
                    <fullName>Migrated to Regional - Retired</fullName>
                    <isActive>false</isActive>
                    <label>Migrated to Regional - Retired</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Account_Plan_Type__c</fullName>
        <description>Created in Account Plan Phase 4 to determine the type of Account Plan</description>
        <inlineHelpText>This field is used to determine the type of Account Plan</inlineHelpText>
        <label>Account Plan Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Current</fullName>
                    <default>true</default>
                    <label>Current</label>
                </value>
                <value>
                    <fullName>Regional</fullName>
                </value>
                <value>
                    <fullName>Global</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Active_Account_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Active Account Plan</label>
        <referenceTo>Account_Plan__c</referenceTo>
        <relationshipLabel>Account Plans</relationshipLabel>
        <relationshipName>Account_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Buying_Centre_Id__c</fullName>
        <description>This is used to identify if an Account Plan is Regional Account Plan .</description>
        <inlineHelpText>This field shows the value of Buying Centre same as on Account if an Account Plan is regional</inlineHelpText>
        <label>Buying Centre Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sub_Status__c</fullName>
        <description>This field used to determine the Regional Account Plan once the Account Plan is switch to Regional from Current</description>
        <label>Sub Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Switched To Regional</fullName>
                </value>
                <value>
                    <fullName>Current Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>is_Account_Plan_Retired__c</fullName>
        <defaultValue>false</defaultValue>
        <label>is Account Plan Retired?</label>
        <type>Checkbox</type>
    </fields>
    <label>Account Plan</label>
    <nameField>
        <displayFormat>ACP-{0000}</displayFormat>
        <label>Account Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/objects/Strategy_and_Goal__c.object
<CustomObject>
    <fields>
        <fullName>Account_Plan_Status__c</fullName>
        <formula>TEXT(Account_Plan__r.Account_Plan_Status__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Plan Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account_Plan__c</fullName>
        <label>Account Plan</label>
        <referenceTo>Account_Plan__c</referenceTo>
        <relationshipLabel>Strategies and Goals</relationshipLabel>
        <relationshipName>Strategies_and_Goals</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Strategy and Goals</label>
    <nameField>
        <displayFormat>STR-{0000}</displayFormat>
        <label>Strategy Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Strategies and Goals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/objects/Whitespace_Potential_Opportunity__c.object
<CustomObject>
    <fields>
        <fullName>Account_Plan__c</fullName>
        <label>Account Plan</label>
        <referenceTo>Account_Plan__c</referenceTo>
        <relationshipLabel>Whitespace Potential Opportunities</relationshipLabel>
        <relationshipName>Whitespace_Potential_Opportunities</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Whitespace Potential Opportunity</label>
    <nameField>
        <displayFormat>WPO-{0000}</displayFormat>
        <label>Whitespace Potential Opportunity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Whitespace Potential Opportunities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/switchToRegionalAccountPlanController.cls
/***********************************************************************************************************************************
* Created By: Prachi Gupta                                                                                                         * 
* Description: This class is used to Switch or Covert the Current Account Plan to Global/Regional.                                 *
************************************************************************************************************************************/

public without sharing class switchToRegionalAccountPlanController {
    
    @AuraEnabled
    public static returnMessageWrapper checkRegionalAccountPlanExist(String apId) {
        returnMessageWrapper rmw =  new returnMessageWrapper();
        rmw.ApplicableForRegional = false;
        rmw.ApplicableForGlobal = false;
        try{
            if(apId != '' && apId != null){
                Account_Plan__c accPlanData = [Select id , Account_Name__c, Account_Name__r.Buying_Centre_Id__c,
                                               Account_Plan_Type__c , is_Account_Plan_Retired__c,Account_Plan_Name__c
                                               from Account_Plan__c where id =: apId ]; 
                
             
                Id accId =  accPlanData.Account_Name__c;     
                String buyingCentreId = accPlanData.Account_Name__r.Buying_Centre_Id__c; 
              
               
                    
                  List<Account> accList = [select id from account where parentId = :accId];
                  if(!accList.isEmpty()){
                   // rmw.ApplicableForGlobal = true; 
                   // Remove the comments from above whenever Global Option will be made available for Users.              
                    
                } 
               
                if(buyingCentreId != null && buyingCentreId != '' && accPlanData.Account_Plan_Type__c == 'Current'){
                    List<Account_Plan__c> apList = [select id , name , Account_Plan_Type__c from Account_Plan__c
                                                    where Buying_Centre_Id__c =: buyingCentreId and 
                                                    Account_Plan_Type__c ='Regional' and is_Account_Plan_Retired__c = false];
                    
                    
                    if(!apList.isEmpty() && apList[0].id != apId){
                        rmw.MessageType = 'Success';
                        rmw.Message = 'Regional Account Plan Found';
                        rmw.accountPlanId = apList[0].id;
                    }  
                    else{
                         
                        rmw.MessageType = 'Success';
                        rmw.Message = 'No Regional Account Plan Found';
                        rmw.ApplicableForRegional = true;
                    } 
                     
                } 
                
                else{
                    rmw.MessageType = 'Success';
                    rmw.Message = 'No Regional Account Plan Required ';
                }
                
            }
            
            
        }
        catch(Exception ex){
            rmw.MessageType = 'ERROR';
            rmw.Message = ex.getMessage();
        }
         
        return rmw;
    }
    
    @AuraEnabled
    public static returnMessageWrapper getStrategyandWhiteSpaceData(String apId){
        returnMessageWrapper rmw =  new returnMessageWrapper();
        try{
            StrategyAndGoalController.returnMessageWrapper strategyList = new StrategyAndGoalController.returnMessageWrapper(); 
            strategyList = StrategyAndGoalController.getStrategyAndGoalsDetails(apId);
            
            WhiteSpaceOpportunityController.returnMessageWrapper whitespaceList = new WhiteSpaceOpportunityController.returnMessageWrapper();
            whitespaceList = WhiteSpaceOpportunityController.getWhiteSpaceOpportunitiesDetails(apId);
            
            rmw.MessageType = 'Success';
            rmw.whiteSpaceWrapper = whitespaceList;
            rmw.strategyWrapper = strategyList;
            
        }catch(Exception ex){
            rmw.MessageType = 'ERROR';
            rmw.Message = ex.getMessage();
        }
        return rmw;
    }

 @AuraEnabled
    public static returnMessageWrapper convertAccPlanToRegional(String apId){
        returnMessageWrapper rmw =  new returnMessageWrapper();
        try{
            if(apId!= null && apId != ''){
                 Account_Plan__c accPlanData = [Select id , Account_Name__c, Account_Name__r.Buying_Centre_Id__c,
                                               Account_Plan_Type__c , is_Account_Plan_Retired__c
                                               from Account_Plan__c where id =: apId];
                Id accId =  accPlanData.Account_Name__c;     
                String buyingCentreId = accPlanData.Account_Name__r.Buying_Centre_Id__c;  
                
                Account_Plan__c ap = new Account_Plan__c(
                id = apId,
                Account_Plan_Type__c = 'Regional',
                Buying_Centre_Id__c = buyingCentreId  
                );
                
                update ap;
                
               /*  List<Account> accData = [Select id , Number_of_Account_Plan__c 
                                          from Account where Buying_Centre_Id__c = :buyingCentreId];
                List<Account> accToUpdate = new List<Account>();
                if(!accData.isEmpty()){
                    for(Account acc : accData){
                        if(acc.Id != accId){
                            Decimal noOfAP = 0;
                            if(acc.Number_of_Account_Plan__c == null ){
                                noOfAP = 1;
                            }
                            else if( acc.Number_of_Account_Plan__c != null){
                                 noOfAP = acc.Number_of_Account_Plan__c + 1;
                            }
                       
                             acc.Number_of_Account_Plan__c = noOfAP;  
                             accToUpdate.add(acc);
                        
                        }                        
                    }
                   
                    update accToUpdate; 
                }*/
                
            }
            
            rmw.MessageType = 'Success';
          
            
        }catch(Exception ex){
            rmw.MessageType = 'ERROR';
            rmw.Message = ex.getMessage();
        }
        return rmw;
    }
    
    @AuraEnabled
    public static returnMessageWrapper convertAccPlanToGlobal(String apId){
        returnMessageWrapper rmw =  new returnMessageWrapper();
        try{
            if(apId!= null && apId != ''){
                 Account_Plan__c accPlanData = [Select id , Account_Name__c, Account_Name__r.Buying_Centre_Id__c,
                                               Account_Plan_Type__c , is_Account_Plan_Retired__c
                                               from Account_Plan__c where id =: apId];
                Id accId =  accPlanData.Account_Name__c;     
                String buyingCentreId = accPlanData.Account_Name__r.Buying_Centre_Id__c;  
                
                Account_Plan__c ap = new Account_Plan__c(
                id = apId,
                Account_Plan_Type__c = 'Global');
                
                update ap;
            }
            
            rmw.MessageType = 'Success';
          
            
        }catch(Exception ex){
            rmw.MessageType = 'ERROR';
            rmw.Message = ex.getMessage();
        }
        return rmw;
    }
    
    @AuraEnabled
    public static returnMessageWrapper  mergeCurrentAndRegionalAP(String currentAPId , 
                                                                  String regionalAPId , List<Id> stList,
                                                                  List<Id> wsList
                                                                 ){
        returnMessageWrapper rmw = new returnMessageWrapper();
                                                                  
        List<Strategy_and_Goal__c> stListUpdated = new List<Strategy_and_Goal__c>();
        List<Whitespace_Potential_Opportunity__c> wsListUpdated = new List<Whitespace_Potential_Opportunity__c>();
        try{
        if(regionalAPId != '' && regionalAPId != null){
           Account_Plan__c apData = [Select id , Account_Name__c, Account_Name__r.Buying_Centre_Id__c,
                                               Account_Plan_Status__c , is_Account_Plan_Retired__c,
                                               Account_Plan_Name__c,Account_Name__r.Number_of_Account_Plan__c
                                               from Account_Plan__c where id =: regionalAPId and is_Account_Plan_Retired__c= false ];
            if(apData.Account_Plan_Status__c == 'In Review'){
             rmw.MessageType = 'ERROR';
             rmw.Message = 'We can not switch Account To Regional since the Regional Account Plan : ' + apData.Account_Plan_Name__c + ' is In Review';
            }
            else{
            if(!stList.isEmpty()){
                
                for(Id stId : stList ){
                    Strategy_and_Goal__c st = new Strategy_and_Goal__c(
                    Account_Plan__c = regionalAPId,
                    id = stId); 
                    
                    stListUpdated.add(st);
                }
               update stListUpdated;
                
            }
            if(wsList.size()>0){
                 
                for(Id ws : wsList ){
                    Whitespace_Potential_Opportunity__c w = new Whitespace_Potential_Opportunity__c(
                        id = ws,
                        Account_Plan__c = regionalAPId
                    );
                    
                   wsListUpdated.add(w);                    
                }
                 
                update wsListUpdated;
                
            }
            Account_Plan__c ap = new Account_Plan__c(id = currentAPId ,
                                                     is_Account_Plan_Retired__c = true,
                                                     Account_Plan_Status__c	 ='Retired',
                                                     Sub_Status__c = 'Switched To Regional',
                                                     Active_Account_Plan__c = regionalAPId
                                                     );
            update ap;
            
       
             rmw.MessageType = 'Success';
             rmw.Message = 'Success';
            }
            }
            
        }catch(Exception ex){
              rmw.MessageType = 'ERROR';
             rmw.Message = ex.getMessage();            
        }
        return rmw;
        }
    public class returnMessageWrapper{
        @AuraEnabled public String MessageType;
        @AuraEnabled public String Message;
        @AuraEnabled public String accountPlanId;
        @AuraEnabled public Boolean ApplicableForRegional;
        @AuraEnabled public Boolean ApplicableForGlobal;
        @AuraEnabled public StrategyAndGoalController.returnMessageWrapper strategyWrapper;
        @AuraEnabled public WhiteSpaceOpportunityController.returnMessageWrapper whiteSpaceWrapper;
        
    }
}