force-app/main/objects/Account.object
<CustomObject>
    <fields>
        <fullName>BU__c</fullName>
        <label>BU</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Master_BUs</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Billing_Address_Line_1__c</fullName>
        <inlineHelpText>If the address goes over more than one line then please use Address Line 2 and Address Line 3. This formatting will display on any Customer facing documents.</inlineHelpText>
        <label>Billing Address Line 1</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_City__c</fullName>
        <label>Billing City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_Country__c</fullName>
        <label>Billing Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AFGHANISTAN</fullName>
                </value>
                <value>
                    <fullName>ALBANIA</fullName>
                </value>
                <value>
                    <fullName>ALDERNEY</fullName>
                </value>
                <value>
                    <fullName>ALGERIA</fullName>
                </value>
                <value>
                    <fullName>AMERICAN SAMOA</fullName>
                </value>
                <value>
                    <fullName>ANDORRA</fullName>
                </value>
                <value>
                    <fullName>ANGOLA</fullName>
                </value>
                <value>
                    <fullName>ANGUILLA</fullName>
                </value>
                <value>
                    <fullName>ANTARCTICA</fullName>
                </value>
                <value>
                    <fullName>ANTIGUA AND BARBUDA</fullName>
                </value>
                <value>
                    <fullName>ARGENTINA</fullName>
                </value>
                <value>
                    <fullName>ARMENIA</fullName>
                </value>
                <value>
                    <fullName>ARUBA</fullName>
                </value>
                <value>
                    <fullName>AUSTRALIA</fullName>
                </value>
                <value>
                    <fullName>AUSTRIA</fullName>
                </value>
                <value>
                    <fullName>AZERBAIJAN</fullName>
                </value>
                <value>
                    <fullName>BAHAMAS</fullName>
                </value>
                <value>
                    <fullName>BAHRAIN</fullName>
                </value>
                <value>
                    <fullName>BANGLADESH</fullName>
                </value>
                <value>
                    <fullName>BARBADOS</fullName>
                </value>
                <value>
                    <fullName>BELARUS</fullName>
                </value>
                <value>
                    <fullName>BELGIUM</fullName>
                </value>
                <value>
                    <fullName>BELIZE</fullName>
                </value>
                <value>
                    <fullName>BENIN</fullName>
                </value>
                <value>
                    <fullName>BERMUDA</fullName>
                </value>
                <value>
                    <fullName>BHUTAN</fullName>
                </value>
                <value>
                    <fullName>BOLIVIA</fullName>
                </value>
                <value>
                    <fullName>BOSNIA AND HERZEGOWINA</fullName>
                </value>
                <value>
                    <fullName>BOTSWANA</fullName>
                </value>
                <value>
                    <fullName>BOUVET ISLAND</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Billing_State__c</fullName>
        <inlineHelpText>If State is required, please enter as two alphanumeric characters, e.g. GA instead of Georgia</inlineHelpText>
        <label>Billing State/County</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_ZIP_Postal_Code__c</fullName>
        <label>Billing ZIP/Postal Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Buying_Centre_Id__c</fullName>
        <description>Fro regional grouping of the same accounts, this field will be populated by the BI team.</description>
        <label>Buying Centre Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Same_As_The_Billing_Address__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Same As The Billing Address</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

force-app/main/objects/Account_Plan__c.object
<CustomObject>
    <description>Module to capture Key Account Plan details</description>
    <fields>
        <fullName>Account_Name__c</fullName>
        <description>This field is used to store the related account for Account Plan</description>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Plans</relationshipLabel>
        <relationshipName>Account_Plans</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Account_Plan_Status__c</fullName>
        <label>Account Plan Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>In Review</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Retired</fullName>
                </value>
                <value>
                    <fullName>Migrated to Regional - Retired</fullName>
                    <isActive>false</isActive>
                    <label>Migrated to Regional - Retired</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Account_Plan_Type__c</fullName>
        <description>Created in Account Plan Phase 4 to determine the type of Account Plan</description>
        <inlineHelpText>This field is used to determine the type of Account Plan</inlineHelpText>
        <label>Account Plan Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Current</fullName>
                    <default>true</default>
                    <label>Current</label>
                </value>
                <value>
                    <fullName>Regional</fullName>
                </value>
                <value>
                    <fullName>Global</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Buying_Centre_Id__c</fullName>
        <description>This is used to identify if an Account Plan is Regional Account Plan .</description>
        <inlineHelpText>This field shows the value of Buying Centre same as on Account if an Account Plan is regional</inlineHelpText>
        <label>Buying Centre Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quarter__c</fullName>
        <label>Quarter</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <label>Year</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <label>Account Plan</label>
    <nameField>
        <displayFormat>ACP-{0000}</displayFormat>
        <label>Account Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>BU__c</fullName>
        <formula>text(Account.BU__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>BU</label>
        <type>Text</type>
    </fields>
</CustomObject>

force-app/main/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Business_Type__c</fullName>
        <description>Choose the Opportunity Type that best describes the type of business pursued.  
Reboost should only be used with In-Advance clients. 
Cross-sell is simply New Business with a client that has a current commercial relationship.</description>
        <label>Opportunity Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Expansion</fullName>
                </value>
                <value>
                    <fullName>Renewal</fullName>
                </value>
                <value>
                    <fullName>Debooking</fullName>
                    <label>Debooking / Adjustment</label>
                </value>
                <value>
                    <fullName>Extension</fullName>
                </value>
                <value>
                    <fullName>In Arrears</fullName>
                </value>
                <value>
                    <fullName>In Advance</fullName>
                </value>
                <value>
                    <fullName>Managed Services</fullName>
                </value>
                <value>
                    <fullName>Professional Services: non-subscription</fullName>
                </value>
                <value>
                    <fullName>Top Up / Addition</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

globalValueSets/Master_BUs.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Abu Dhabi - AD1</fullName>
    </customValue>
    <customValue>
        <fullName>Australia - AU1</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium SPS - BE5</fullName>
    </customValue>
    <customValue>
        <fullName>Canada - CA1</fullName>
    </customValue>
    <customValue>
        <fullName>China - CN1</fullName>
    </customValue>
    <customValue>
        <fullName>Denmark - DK1</fullName>
    </customValue>
    <customValue>
        <fullName>Finland - FI1</fullName>
    </customValue>
    <customValue>
        <fullName>France SPS - FR5</fullName>
    </customValue>
    <customValue>
        <fullName>Germany SPS - DE5</fullName>
    </customValue>
    <customValue>
        <fullName>Hong Kong - HK1</fullName>
    </customValue>
    <customValue>
        <fullName>India - IN1</fullName>
    </customValue>
    <customValue>
        <fullName>Italy - IT1</fullName>
    </customValue>
    <customValue>
        <fullName>Middle East - ME1</fullName>
    </customValue>
    <customValue>
        <fullName>Netherlands SPS - NL5</fullName>
    </customValue>
    <customValue>
        <fullName>New Zealand - NZ1</fullName>
    </customValue>
    <customValue>
        <fullName>Norway - NO1</fullName>
    </customValue>
    <customValue>
        <fullName>Philippines - PH1</fullName>
    </customValue>
    <customValue>
        <fullName>Saudi Arabia - SA5</fullName>
    </customValue>
    <customValue>
        <fullName>Singapore - SG1</fullName>
    </customValue>
    <customValue>
        <fullName>South Africa - ZA1</fullName>
    </customValue>
    <customValue>
        <fullName>Sweden - SE1</fullName>
    </customValue>
    <customValue>
        <fullName>Switzerland - CH1</fullName>
    </customValue>
    <customValue>
        <fullName>UK - UK1</fullName>
    </customValue>
    <customValue>
        <fullName>US - US5</fullName>
    </customValue>
    <customValue>
        <fullName>Indonesia - ID1</fullName>
    </customValue>
    <customValue>
        <fullName>Asia Pac	India</fullName>
        <isActive>false</isActive>
        <label>Asia Pac	India</label>
    </customValue>
    <customValue>
        <fullName>Asia Pac	Singapore</fullName>
        <isActive>false</isActive>
        <label>Asia Pac	Singapore</label>
    </customValue>
    <customValue>
        <fullName>Asia Pac	AP Region</fullName>
        <isActive>false</isActive>
        <label>Asia Pac	AP Region</label>
    </customValue>
    <customValue>
        <fullName>UK	  - UK1</fullName>
        <isActive>false</isActive>
        <label>UK	  - UK1</label>
    </customValue>
    <customValue>
        <fullName>Head Office  - H50</fullName>
        <isActive>false</isActive>
        <label>Head Office  - H50</label>
    </customValue>
    <masterLabel>Master BUs</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

classes/CurrentPipelineController_Test.cls
@isTest
public class CurrentPipelineController_Test {
	
    @IsTest(seeAlldata=true)
    static void testStrategies() {
        // Test data setup
        Account acc= new Account();
        acc.Name='Test234';
        acc.BU__c='UK - UK1';
        acc.CurrencyIsoCode='GBP'; 
        acc.Industry='Agriculture';
        acc.Billing_Address_Line_1__c='test23';
        acc.Billing_City__c='test23';
        acc.Same_As_The_Billing_Address__c=true;
        acc.Billing_Country__c='test23';
        acc.Billing_State__c='test23';
        acc.Billing_ZIP_Postal_Code__c='test23'; 
        acc.Buying_Centre_Id__c = '90';
        insert acc;
        
        Account_Plan__c ap = new Account_Plan__c(Account_Name__c = acc.id,Quarter__c ='Q1',Year__c='2023',Account_Plan_Status__c ='Draft',Account_Plan_Type__c='Global');
        insert ap;
        
        Account_Plan__c ap1 = new Account_Plan__c(Account_Name__c = acc.id,Quarter__c ='Q1',Year__c='2023',Account_Plan_Status__c ='Draft',Account_Plan_Type__c='Regional',Buying_Centre_Id__c='90');
        insert ap1;

        Contact con = CreateTestData.getContact(acc.Id);
        
        Opportunity opp = CreateTestData.getOpportunity(acc.Id,con.Id);
        opp.Business_Type__c = 'Renewal';
        
        update opp;
        
        Test.startTest();
   			CurrentPipelineController.getOpenOpportunitiesDetails(ap.Id,'Renewal');
       		CurrentPipelineController.getOpenOpportunitiesDetails(ap1.Id,'New Business/Cross Sell');
        Test.stopTest();
    }
}