force-app/main/objects/Account.object
<CustomObject>
    <fields>
        <fullName>BU__c</fullName>
        <label>BU</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Master_BUs</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Billing_Address_Line_1__c</fullName>
        <inlineHelpText>If the address goes over more than one line then please use Address Line 2 and Address Line 3. This formatting will display on any Customer facing documents.</inlineHelpText>
        <label>Billing Address Line 1</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_City__c</fullName>
        <label>Billing City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_Country__c</fullName>
        <label>Billing Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AFGHANISTAN</fullName>
                </value>
                <value>
                    <fullName>ALBANIA</fullName>
                </value>
                <value>
                    <fullName>ALDERNEY</fullName>
                </value>
                <value>
                    <fullName>ALGERIA</fullName>
                </value>
                <value>
                    <fullName>AMERICAN SAMOA</fullName>
                </value>
                <value>
                    <fullName>ANDORRA</fullName>
                </value>
                <value>
                    <fullName>ANGOLA</fullName>
                </value>
                <value>
                    <fullName>ANGUILLA</fullName>
                </value>
                <value>
                    <fullName>ANTARCTICA</fullName>
                </value>
                <value>
                    <fullName>ANTIGUA AND BARBUDA</fullName>
                </value>
                <value>
                    <fullName>ARGENTINA</fullName>
                </value>
                <value>
                    <fullName>ARMENIA</fullName>
                </value>
                <value>
                    <fullName>ARUBA</fullName>
                </value>
                <value>
                    <fullName>AUSTRALIA</fullName>
                </value>
                <value>
                    <fullName>AUSTRIA</fullName>
                </value>
                <value>
                    <fullName>AZERBAIJAN</fullName>
                </value>
                <value>
                    <fullName>BAHAMAS</fullName>
                </value>
                <value>
                    <fullName>BAHRAIN</fullName>
                </value>
                <value>
                    <fullName>BANGLADESH</fullName>
                </value>
                <value>
                    <fullName>BARBADOS</fullName>
                </value>
                <value>
                    <fullName>BELARUS</fullName>
                </value>
                <value>
                    <fullName>BELGIUM</fullName>
                </value>
                <value>
                    <fullName>BELIZE</fullName>
                </value>
                <value>
                    <fullName>BENIN</fullName>
                </value>
                <value>
                    <fullName>BERMUDA</fullName>
                </value>
                <value>
                    <fullName>BHUTAN</fullName>
                </value>
                <value>
                    <fullName>BOLIVIA</fullName>
                </value>
                <value>
                    <fullName>BOSNIA AND HERZEGOWINA</fullName>
                </value>
                <value>
                    <fullName>BOTSWANA</fullName>
                </value>
                <value>
                    <fullName>BOUVET ISLAND</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Billing_State__c</fullName>
        <inlineHelpText>If State is required, please enter as two alphanumeric characters, e.g. GA instead of Georgia</inlineHelpText>
        <label>Billing State/County</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_ZIP_Postal_Code__c</fullName>
        <label>Billing ZIP/Postal Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Same_As_The_Billing_Address__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Same As The Billing Address</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

force-app/main/objects/Account_Plan__c.object
<CustomObject>
    <description>Module to capture Key Account Plan details</description>
    <fields>
        <fullName>Account_Name__c</fullName>
        <description>This field is used to store the related account for Account Plan</description>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Plans</relationshipLabel>
        <relationshipName>Account_Plans</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Account_Plan_Type__c</fullName>
        <description>Created in Account Plan Phase 4 to determine the type of Account Plan</description>
        <inlineHelpText>This field is used to determine the type of Account Plan</inlineHelpText>
        <label>Account Plan Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Current</fullName>
                    <default>true</default>
                    <label>Current</label>
                </value>
                <value>
                    <fullName>Regional</fullName>
                </value>
                <value>
                    <fullName>Global</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Account Plan</label>
    <nameField>
        <displayFormat>ACP-{0000}</displayFormat>
        <label>Account Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>BU__c</fullName>
        <formula>text(Account.BU__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>BU</label>
        <type>Text</type>
    </fields>
</CustomObject>

force-app/main/objects/Strategy_and_Goal__c.object
<CustomObject>
    <fields>
        <fullName>Account_Plan__c</fullName>
        <label>Account Plan</label>
        <referenceTo>Account_Plan__c</referenceTo>
        <relationshipLabel>Strategies and Goals</relationshipLabel>
        <relationshipName>Strategies_and_Goals</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Business_Problem_Addressed__c</fullName>
        <label>Business Problem Addressed</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Estimated_Completion_Date__c</fullName>
        <label>Estimated Completion Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Key_Contact_Sponsor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Key Contact Sponsor</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Strategies and Goals</relationshipLabel>
        <relationshipName>Strategies_and_Goals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Solution_Goal__c</fullName>
        <label>Solution / Goal</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Solution_Product_Area__c</fullName>
        <label>Solution / Product Area</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Talent Acquisition - Grad</fullName>
                </value>
                <value>
                    <fullName>Talent Acquisition - Volume</fullName>
                </value>
                <value>
                    <fullName>Talent Acquisition - Tech</fullName>
                </value>
                <value>
                    <fullName>Talent Acquisition - Sales</fullName>
                </value>
                <value>
                    <fullName>Talent Acquisition - Professional/Managerial</fullName>
                </value>
                <value>
                    <fullName>Talent Acquisition - General</fullName>
                </value>
                <value>
                    <fullName>Talent Management</fullName>
                </value>
                <value>
                    <fullName>Both TA &amp; TM</fullName>
                </value>
                <value>
                    <fullName>Training</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Strategy_Name__c</fullName>
        <label>Strategy Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Strategy_Status__c</fullName>
        <label>Strategy Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Strategy_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started (Default)</fullName>
                </value>
                <value>
                    <fullName>Investigation</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Opportunity Created</fullName>
                </value>
                <value>
                    <fullName>No Opportunity</fullName>
                </value>
                <value>
                    <fullName>Won - Partial Achievement</fullName>
                </value>
                <value>
                    <fullName>Won - Achieved Revenue Goals</fullName>
                </value>
                <value>
                    <fullName>Completed - Failed</fullName>
                </value>
                <value>
                    <fullName>Completed - Partial Success</fullName>
                </value>
                <value>
                    <fullName>Completed - Success</fullName>
                </value>
                <value>
                    <fullName>Strategy Expired</fullName>
                </value>
                <value>
                    <fullName>Strategy Valid</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Strategy_Type__c</fullName>
        <label>Strategy Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Defend</fullName>
                </value>
                <value>
                    <fullName>Product Migration</fullName>
                </value>
                <value>
                    <fullName>Relationship</fullName>
                </value>
                <value>
                    <fullName>Sale</fullName>
                </value>
                <value>
                    <fullName>Competitor Displacement</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Strategy and Goals</label>
    <nameField>
        <displayFormat>STR-{0000}</displayFormat>
        <label>Strategy Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Strategies and Goals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/objects/Whitespace_Potential_Opportunity__c.object
<CustomObject>
    <fields>
        <fullName>Account_Plan__c</fullName>
        <label>Account Plan</label>
        <referenceTo>Account_Plan__c</referenceTo>
        <relationshipLabel>Whitespace Potential Opportunities</relationshipLabel>
        <relationshipName>Whitespace_Potential_Opportunities</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Any_help_needed__c</fullName>
        <label>Any help needed?</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Next_Step_s__c</fullName>
        <label>Next Step/s</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Potential_Value__c</fullName>
        <label>Potential Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Solution__c</fullName>
        <label>Solution</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Solution_Value_Set</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Strategy_and_Goals__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Strategy</label>
        <referenceTo>Strategy_and_Goal__c</referenceTo>
        <relationshipLabel>Whitespace Potential Opportunities</relationshipLabel>
        <relationshipName>Whitespace_Potential_Opportunities</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Who_do_you_need_to_speak_to__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Who do you need to speak to?</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Whitespace Potential Opportunities</relationshipLabel>
        <relationshipName>Whitespace_Potential_Opportunities</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Whitespace Potential Opportunity</label>
    <nameField>
        <displayFormat>WPO-{0000}</displayFormat>
        <label>Whitespace Potential Opportunity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Whitespace Potential Opportunities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

globalValueSets/Master_BUs.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Abu Dhabi - AD1</fullName>
    </customValue>
    <customValue>
        <fullName>Australia - AU1</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium SPS - BE5</fullName>
    </customValue>
    <customValue>
        <fullName>Canada - CA1</fullName>
    </customValue>
    <customValue>
        <fullName>China - CN1</fullName>
    </customValue>
    <customValue>
        <fullName>Denmark - DK1</fullName>
    </customValue>
    <customValue>
        <fullName>Finland - FI1</fullName>
    </customValue>
    <customValue>
        <fullName>France SPS - FR5</fullName>
    </customValue>
    <customValue>
        <fullName>Germany SPS - DE5</fullName>
    </customValue>
    <customValue>
        <fullName>Hong Kong - HK1</fullName>
    </customValue>
    <customValue>
        <fullName>India - IN1</fullName>
    </customValue>
    <customValue>
        <fullName>Italy - IT1</fullName>
    </customValue>
    <customValue>
        <fullName>Middle East - ME1</fullName>
    </customValue>
    <customValue>
        <fullName>Netherlands SPS - NL5</fullName>
    </customValue>
    <customValue>
        <fullName>New Zealand - NZ1</fullName>
    </customValue>
    <customValue>
        <fullName>Norway - NO1</fullName>
    </customValue>
    <customValue>
        <fullName>Philippines - PH1</fullName>
    </customValue>
    <customValue>
        <fullName>Saudi Arabia - SA5</fullName>
    </customValue>
    <customValue>
        <fullName>Singapore - SG1</fullName>
    </customValue>
    <customValue>
        <fullName>South Africa - ZA1</fullName>
    </customValue>
    <customValue>
        <fullName>Sweden - SE1</fullName>
    </customValue>
    <customValue>
        <fullName>Switzerland - CH1</fullName>
    </customValue>
    <customValue>
        <fullName>UK - UK1</fullName>
    </customValue>
    <customValue>
        <fullName>US - US5</fullName>
    </customValue>
    <customValue>
        <fullName>Indonesia - ID1</fullName>
    </customValue>
    <customValue>
        <fullName>Asia Pac	India</fullName>
        <isActive>false</isActive>
        <label>Asia Pac	India</label>
    </customValue>
    <customValue>
        <fullName>Asia Pac	Singapore</fullName>
        <isActive>false</isActive>
        <label>Asia Pac	Singapore</label>
    </customValue>
    <customValue>
        <fullName>Asia Pac	AP Region</fullName>
        <isActive>false</isActive>
        <label>Asia Pac	AP Region</label>
    </customValue>
    <customValue>
        <fullName>UK	  - UK1</fullName>
        <isActive>false</isActive>
        <label>UK	  - UK1</label>
    </customValue>
    <customValue>
        <fullName>Head Office  - H50</fullName>
        <isActive>false</isActive>
        <label>Head Office  - H50</label>
    </customValue>
    <masterLabel>Master BUs</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

globalValueSets/Solution_Value_Set.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Graduate Essential</fullName>
    </customValue>
    <customValue>
        <fullName>Graduate Advanced</fullName>
    </customValue>
    <customValue>
        <fullName>Graduate Ultimate</fullName>
    </customValue>
    <customValue>
        <fullName>Volume Essential</fullName>
    </customValue>
    <customValue>
        <fullName>Volume Advanced</fullName>
    </customValue>
    <customValue>
        <fullName>Apprentice Essential</fullName>
    </customValue>
    <customValue>
        <fullName>Managerial Essential</fullName>
    </customValue>
    <customValue>
        <fullName>Managerial Advanced</fullName>
    </customValue>
    <customValue>
        <fullName>Managerial Ultimate</fullName>
    </customValue>
    <customValue>
        <fullName>Video Essential</fullName>
    </customValue>
    <customValue>
        <fullName>Video Advanced</fullName>
    </customValue>
    <customValue>
        <fullName>Video Ultimate</fullName>
    </customValue>
    <customValue>
        <fullName>Professional Essential</fullName>
    </customValue>
    <customValue>
        <fullName>Professional Advanced</fullName>
    </customValue>
    <customValue>
        <fullName>Professional Ultimate</fullName>
    </customValue>
    <customValue>
        <fullName>Product</fullName>
    </customValue>
    <customValue>
        <fullName>Mobilize Essential</fullName>
    </customValue>
    <customValue>
        <fullName>Mobilize Advanced</fullName>
    </customValue>
    <customValue>
        <fullName>Mobilize Ultimate</fullName>
    </customValue>
    <customValue>
        <fullName>Sales Transformation Review Essential</fullName>
    </customValue>
    <customValue>
        <fullName>Sales Transformation Review Advanced</fullName>
    </customValue>
    <customValue>
        <fullName>Sales Transformation Review Ultimate</fullName>
    </customValue>
    <customValue>
        <fullName>Sales Transformation Hiring Essential</fullName>
    </customValue>
    <customValue>
        <fullName>Sales Transformation Hiring Advanced</fullName>
    </customValue>
    <customValue>
        <fullName>Sales Transformation Hiring Ultimate</fullName>
    </customValue>
    <customValue>
        <fullName>Service</fullName>
    </customValue>
    <customValue>
        <fullName>OA 1:1 Essential</fullName>
    </customValue>
    <customValue>
        <fullName>OA 1:1 Advanced</fullName>
    </customValue>
    <customValue>
        <fullName>OA 1:1 Ultimate</fullName>
    </customValue>
    <customValue>
        <fullName>OA 1:Many Essential</fullName>
    </customValue>
    <masterLabel>Solution Value Set</masterLabel>
</GlobalValueSet>

classes/WhiteSpaceOpportunityController_Test.cls
@isTest
public class WhiteSpaceOpportunityController_Test {
	
    @IsTest(seeAlldata=true)
    static void testWhitespace() {
        // Test data setup
        Account acc= new Account();
        acc.Name='Test234';
        acc.BU__c='UK - UK1';
        acc.CurrencyIsoCode='GBP'; 
        acc.Industry='Agriculture';
        acc.Billing_Address_Line_1__c='test23';
        acc.Billing_City__c='test23';
        acc.Same_As_The_Billing_Address__c=true;
        acc.Billing_Country__c='test23';
        acc.Billing_State__c='test23';
        acc.Billing_ZIP_Postal_Code__c='test23'; 
        insert acc;

        Contact con = CreateTestData.getContact(acc.Id);

        Account_Plan__c accPlan = new Account_Plan__c(Account_Name__c=acc.Id , Account_Plan_Type__c = 'Current');
        insert accPlan;
          
        Strategy_and_Goal__c stgoal = new Strategy_and_Goal__c(Account_Plan__c = accPlan.Id, 
                                                               Strategy_Name__c = 'Test',
                                                               Business_Problem_Addressed__c = 'Test', 
                                                               Estimated_Completion_Date__c = System.today(), 
                                                               Solution_Goal__c = 'Goal', 
                                                               Solution_Product_Area__c = 'Training', 
                                                               Strategy_Type__c = 'Product Migration', 
                                                               Strategy_Status__c = 'In Progress',
                                                               Key_Contact_Sponsor__c=con.Id);
        insert stgoal;
        
        Strategy_and_Goal__c strat = [SELECT Id, Name FROM Strategy_and_Goal__c WHERE Id =: stgoal.Id];
        Whitespace_Potential_Opportunity__c wsOpp = new Whitespace_Potential_Opportunity__c();
        wsOpp.Account_Plan__c = accPlan.Id;
        wsOpp.Strategy_and_Goals__c = strat.Id;
        wsOpp.Who_do_you_need_to_speak_to__c = con.Id;
        wsOpp.Solution__c = 'Product';
        wsOpp.Potential_Value__c = 10000;
        wsOpp.Any_help_needed__c ='No';
        wsOpp.Next_Step_s__c ='Test';
        
        Insert wsOpp;
        WhiteSpaceOpportunityController.WhiteSpaceOpportunityWrapper wrapper = new WhiteSpaceOpportunityController.WhiteSpaceOpportunityWrapper();
        wrapper.helpNeeded = 'No';
        wrapper.contactId = con.Id;
        wrapper.nextStep = 'Test';
        wrapper.strategy = strat.Id;
        wrapper.potentialValue = 10000;
        wrapper.solution = 'Product';
        wrapper.whiteSpaceOppId = wsOpp.Id;
        // Test method call
        Test.startTest();
   			WhiteSpaceOpportunityController.getWhiteSpaceOpportunitiesDetails(accPlan.Id);
        	WhiteSpaceOpportunityController.getWhiteSpaceOpportunitiesDetails(strat.Id);
        	WhiteSpaceOpportunityController.convertToOpportunity(accPlan.Id,wrapper);
           	WhiteSpaceOpportunityController.getConvertedWhiteSpaceOpportunities(accPlan.Id);
        Test.stopTest();
    }
}