force-app/main/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Number__c</fullName>
        <description>For use with integration to SUN &amp; PSA</description>
        <displayFormat>D{0000000}</displayFormat>
        <externalId>true</externalId>
        <label>Account Number</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>BU__c</fullName>
        <label>BU</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Master_BUs</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Buying_Centre_Id__c</fullName>
        <description>Fro regional grouping of the same accounts, this field will be populated by the BI team.</description>
        <label>Buying Centre Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Global_Billing_Country__c</fullName>
        <description>This is the new field created for making the country value set consistent over all modules in Salesforce.</description>
        <label>Billing Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Global_Country_Picklist</valueSetName>
        </valueSet>
    </fields>
</CustomObject>

objects/Competitor__c.object
<CustomObject>
    <description>To capture additional info beyond who the competitor is &amp; linked to an Opportunity</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>notEqual</operation>
                <value>Competitor Account</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Competitor Information</relationshipLabel>
        <relationshipName>CompetitorOpportunities</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Competing_Solution_Area__c</fullName>
        <label>Competing Solution Area</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Talent Acquisition - Grad</fullName>
                </value>
                <value>
                    <fullName>Talent Acquisition - Volume</fullName>
                </value>
                <value>
                    <fullName>Talent Acquisition - Tech</fullName>
                </value>
                <value>
                    <fullName>Talent Acquisition - Sales</fullName>
                </value>
                <value>
                    <fullName>Talent Acquisition - Professional</fullName>
                </value>
                <value>
                    <fullName>Talent Acquisition - Managerial</fullName>
                </value>
                <value>
                    <fullName>Talent Management - Review</fullName>
                </value>
                <value>
                    <fullName>Talent Management - Mobilize</fullName>
                </value>
                <value>
                    <fullName>Talent Management - Develop</fullName>
                    <isActive>false</isActive>
                    <label>Talent Management - Develop</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Competitor__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Competitor</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Competitor Account</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer Information</relationshipLabel>
        <relationshipName>Competitors</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Incumbent_Renewal_Date__c</fullName>
        <label>Incumbent Renewal Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Incumbent_Value__c</fullName>
        <label>Incumbent Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Incumbent_Value_in_USD__c</fullName>
        <formula>IF(
TEXT(CurrencyIsoCode) = &apos;USD&apos;, Incumbent_Value__c,  
Incumbent_Value__c / CURRENCYRATE(TEXT(CurrencyIsoCode))*CURRENCYRATE(&apos;USD&apos;))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Incumbent Value(in USD)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Incumbent_Vendor__c</fullName>
        <label>Incumbent Vendor</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Industry__c</fullName>
        <formula>TEXT(Account__r.Industry)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Industry</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Competitors</relationshipLabel>
        <relationshipName>Competitors</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Competitor</label>
    <nameField>
        <displayFormat>CMP-{0000000}</displayFormat>
        <label>Competitor Data</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Competitors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Account_Number__c</fullName>
        <description>This field displays Account Number of Account linked to</description>
        <formula>Account.Account_Number__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Number</label>
        <type>Text</type>
    </fields>
</CustomObject>

globalValueSets/Global_Country_Picklist.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>AFGHANISTAN</fullName>
    </customValue>
    <customValue>
        <fullName>ALBANIA</fullName>
    </customValue>
    <customValue>
        <fullName>ALDERNEY</fullName>
    </customValue>
    <customValue>
        <fullName>ALGERIA</fullName>
    </customValue>
    <customValue>
        <fullName>AMERICAN SAMOA</fullName>
    </customValue>
    <customValue>
        <fullName>ANDORRA</fullName>
    </customValue>
    <customValue>
        <fullName>ANGOLA</fullName>
    </customValue>
    <customValue>
        <fullName>ANGUILLA</fullName>
    </customValue>
    <customValue>
        <fullName>ANTARCTICA</fullName>
    </customValue>
    <customValue>
        <fullName>ANTIGUA AND BARBUDA</fullName>
    </customValue>
    <customValue>
        <fullName>ARGENTINA</fullName>
    </customValue>
    <customValue>
        <fullName>ARMENIA</fullName>
    </customValue>
    <customValue>
        <fullName>ARUBA</fullName>
    </customValue>
    <customValue>
        <fullName>AUSTRALIA</fullName>
    </customValue>
    <customValue>
        <fullName>AUSTRIA</fullName>
    </customValue>
    <customValue>
        <fullName>AZERBAIJAN</fullName>
    </customValue>
    <customValue>
        <fullName>BAHAMAS</fullName>
    </customValue>
    <customValue>
        <fullName>BAHRAIN</fullName>
    </customValue>
    <customValue>
        <fullName>BANGLADESH</fullName>
    </customValue>
    <customValue>
        <fullName>BARBADOS</fullName>
    </customValue>
    <customValue>
        <fullName>BELARUS</fullName>
    </customValue>
    <customValue>
        <fullName>BELGIUM</fullName>
    </customValue>
    <customValue>
        <fullName>BELIZE</fullName>
    </customValue>
    <customValue>
        <fullName>BENIN</fullName>
    </customValue>
    <customValue>
        <fullName>BERMUDA</fullName>
    </customValue>
    <customValue>
        <fullName>BHUTAN</fullName>
    </customValue>
    <customValue>
        <fullName>BOLIVIA</fullName>
    </customValue>
    <customValue>
        <fullName>BOSNIA AND HERZEGOWINA</fullName>
    </customValue>
    <customValue>
        <fullName>BOTSWANA</fullName>
    </customValue>
    <customValue>
        <fullName>BOUVET ISLAND</fullName>
    </customValue>
    <description>used as a global picklist over all the modules in salesforce</description>
    <masterLabel>Global Country Picklist</masterLabel>
</GlobalValueSet>

globalValueSets/Master_BUs.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Abu Dhabi - AD1</fullName>
    </customValue>
    <customValue>
        <fullName>Australia - AU1</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium SPS - BE5</fullName>
    </customValue>
    <customValue>
        <fullName>Canada - CA1</fullName>
    </customValue>
    <customValue>
        <fullName>China - CN1</fullName>
    </customValue>
    <customValue>
        <fullName>Denmark - DK1</fullName>
    </customValue>
    <customValue>
        <fullName>Finland - FI1</fullName>
    </customValue>
    <customValue>
        <fullName>France SPS - FR5</fullName>
    </customValue>
    <customValue>
        <fullName>Germany SPS - DE5</fullName>
    </customValue>
    <customValue>
        <fullName>Hong Kong - HK1</fullName>
    </customValue>
    <customValue>
        <fullName>India - IN1</fullName>
    </customValue>
    <customValue>
        <fullName>Italy - IT1</fullName>
    </customValue>
    <customValue>
        <fullName>Middle East - ME1</fullName>
    </customValue>
    <customValue>
        <fullName>Netherlands SPS - NL5</fullName>
    </customValue>
    <customValue>
        <fullName>New Zealand - NZ1</fullName>
    </customValue>
    <customValue>
        <fullName>Norway - NO1</fullName>
    </customValue>
    <customValue>
        <fullName>Philippines - PH1</fullName>
    </customValue>
    <customValue>
        <fullName>Saudi Arabia - SA5</fullName>
    </customValue>
    <customValue>
        <fullName>Singapore - SG1</fullName>
    </customValue>
    <customValue>
        <fullName>South Africa - ZA1</fullName>
    </customValue>
    <customValue>
        <fullName>Sweden - SE1</fullName>
    </customValue>
    <customValue>
        <fullName>Switzerland - CH1</fullName>
    </customValue>
    <customValue>
        <fullName>UK - UK1</fullName>
    </customValue>
    <customValue>
        <fullName>US - US5</fullName>
    </customValue>
    <customValue>
        <fullName>Indonesia - ID1</fullName>
    </customValue>
    <customValue>
        <fullName>Asia Pac	India</fullName>
        <isActive>false</isActive>
        <label>Asia Pac	India</label>
    </customValue>
    <customValue>
        <fullName>Asia Pac	Singapore</fullName>
        <isActive>false</isActive>
        <label>Asia Pac	Singapore</label>
    </customValue>
    <customValue>
        <fullName>Asia Pac	AP Region</fullName>
        <isActive>false</isActive>
        <label>Asia Pac	AP Region</label>
    </customValue>
    <customValue>
        <fullName>UK	  - UK1</fullName>
        <isActive>false</isActive>
        <label>UK	  - UK1</label>
    </customValue>
    <customValue>
        <fullName>Head Office  - H50</fullName>
        <isActive>false</isActive>
        <label>Head Office  - H50</label>
    </customValue>
    <masterLabel>Master BUs</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

classes/CompetitorOnAccountPlanController.cls
public without sharing class CompetitorOnAccountPlanController {
    //Changes start by Prachi SSE-21664
    /* public static List<CompetitorWrapper> getCompetitorDetails(Id accountId){

List<Competitor__c> compData = [SELECT Id,Name,Competing_Solution_Area__c,Incumbent_Value__c,Account__r.BU__c,
Account__r.Global_Billing_Country__c,Competitor__r.Name,Industry__c,Incumbent_Renewal_Date__c,
Opportunity__c,Opportunity__r.Name,Incumbent_Vendor__c 
FROM Competitor__c WHERE Account__c=:accountId];
List<CompetitorWrapper> wrapperList = new List<CompetitorWrapper>(); 
Integer serialNumber = 1;
String sfdcBaseURL = URL.getSalesforceBaseUrl().toExternalForm();
for (Competitor__c comp : compData) {
CompetitorWrapper wrap = new CompetitorWrapper();
wrap.competitorUrl = sfdcBaseURL+'/'+comp.Id;
wrap.serialNumber = serialNumber;
wrap.competitorName = comp.Competitor__r.Name;
wrap.id = comp.Id;
wrap.estimatedCustomerSpend = comp.Incumbent_Value__c;
wrap.solution = comp.Competing_Solution_Area__c;
wrap.areaDetails = comp.Account__r.BU__c+'/'+comp.Account__r.Global_Billing_Country__c;
if(comp.Opportunity__c!=null){
wrap.opportunityName = comp.Opportunity__r.Name;
wrap.opportunityUrl = sfdcBaseURL+'/'+comp.Opportunity__c;
}
wrap.industry = comp.Industry__c;
wrap.incumbentVendor = comp.Incumbent_Vendor__c;
wrap.incumbentDate = comp.Incumbent_Renewal_Date__c;
wrapperList.add(wrap);
serialNumber++;
}
return wrapperList;
}

*/
    
    @AuraEnabled(cacheable=true)
    public static List<FinalCompetitorWrapper> getCompetitorDetails(Id accountId, String apType){
        
        List<Competitor__c> compData = new List<Competitor__c>();
        String BuyingCentreId = [Select id , Buying_Centre_Id__c from account where id = :accountId].Buying_Centre_Id__c;
        
        if(apType == 'Current'){ 
            compData = [SELECT Id,Name,Competing_Solution_Area__c,Account__r.Account_Number__c,Account__c,
                        Incumbent_Value__c,Account__r.BU__c,Account__r.Global_Billing_Country__c,
                        Competitor__r.Name,Industry__c,Opportunity__c,Opportunity__r.Name,Incumbent_Value_in_USD__c,
                        Incumbent_Vendor__c,Incumbent_Renewal_Date__c,Competitor__c,CurrencyIsoCode
                        FROM Competitor__c WHERE Account__c=:accountId];
        }
        else if(apType == 'Global') {
            Set<Id> allAccountIds = new Set<Id>{accountId};
                Set<Id> parentIds = new Set<Id>{accountId};
                    List<Account> childAccounts = new List<Account>();
            do {
                childAccounts = [SELECT Id FROM Account WHERE ParentId IN :parentIds AND RecordType.name != 'Competitor Account'];
                parentIds.clear();
                for (Account child : childAccounts){
                    parentIds.add(child.Id);
                    allAccountIds.add(child.Id);
                }
            } while (childAccounts.size() > 0);
            
            compData = [SELECT Id,Name,Competing_Solution_Area__c,Account__r.Account_Number__c,Account__c,Competitor__c,
                        Incumbent_Value__c,Account__r.BU__c,Account__r.Global_Billing_Country__c,Incumbent_Value_in_USD__c,
                        Competitor__r.Name,Industry__c,Opportunity__c,Opportunity__r.Name,CurrencyIsoCode,
                        Incumbent_Vendor__c,Incumbent_Renewal_Date__c
                        FROM Competitor__c WHERE Account__c IN :allAccountIds];
        }
        else if(apType == 'Regional'){
            compData = [SELECT Id,Name,Competing_Solution_Area__c,Account__r.Account_Number__c,Account__c,Incumbent_Value_in_USD__c,
                        Incumbent_Value__c,Account__r.BU__c,Account__r.Global_Billing_Country__c,
                        Competitor__r.Name,Industry__c,Opportunity__c,Opportunity__r.Name,
                        Incumbent_Vendor__c,Incumbent_Renewal_Date__c,Competitor__c,CurrencyIsoCode
                        FROM Competitor__c WHERE Account__c IN (Select id from account where Buying_Centre_Id__c =:BuyingCentreId)
                       ];
        }
   
        List<FinalCompetitorWrapper> finalWrapperList = new List<FinalCompetitorWrapper>();
        
        Set<Id> competitorAccountId = new Set<Id>();
       
        
        if(!compData.isEmpty()){
            for (Competitor__c comp : compData) {
                competitorAccountId.add(comp.Competitor__c);
            } 
        }
         
         String sfdcBaseURL = URL.getSalesforceBaseUrl().toExternalForm();
         Integer MainTableSno = 0;
        if(!competitorAccountId.isEmpty()){
               
            for(Id cmpAcc : competitorAccountId){
                MainTableSno ++;
                FinalCompetitorWrapper fcw = new  FinalCompetitorWrapper();
                List<CompetitorWrapper> wrapperList = new List<CompetitorWrapper>();
                Decimal totalSpend = 0; 
                Integer serialNumber = 0; 
                for (Competitor__c comp : compData) {
                   
                    if(cmpAcc == comp.Competitor__c){ 
                        serialNumber++;
                        if(comp.Incumbent_Value_in_USD__c != null ){
                            totalSpend = totalSpend + comp.Incumbent_Value_in_USD__c;    
                        }
                       
                        CompetitorWrapper wrap = new CompetitorWrapper();
                        fcw.compAccountUrl =  sfdcBaseURL+'/'+comp.Competitor__c;
                        fcw.competitorAccName =  comp.Competitor__r.Name;
                         
                      //  wrap.competitorUrl = sfdcBaseURL+'/'+comp.Id;
                        wrap.serialNumber = serialNumber;
                        wrap.competitorName = comp.Competitor__r.Name;
                        wrap.id = comp.Id;
                        if(comp.Incumbent_Value__c != null ){
                             wrap.estimatedCustomerSpend = comp.CurrencyIsoCode+' ' + comp.Incumbent_Value__c;
                        }
                       
                        wrap.solution = comp.Competing_Solution_Area__c;
                        wrap.incumbentDate = comp.Incumbent_Renewal_Date__c;
                        wrap.areaDetails = comp.Account__r.BU__c+'/'+comp.Account__r.Global_Billing_Country__c;
                        if(comp.Opportunity__c!=null){
                            wrap.opportunityName = comp.Opportunity__r.Name;
                            wrap.opportunityUrl = sfdcBaseURL+'/'+comp.Opportunity__c;
                        }
                        wrap.industry = comp.Industry__c;
                        wrap.incumbentVendor = comp.Incumbent_Vendor__c;  
                         
                         wrapperList.add(wrap);
                             
                        
                    }
                     
                     
                }
                
                fcw.totalEstimatedCustomerSpend ='USD ' + totalSpend +'$';
                fcw.competitorDetails = wrapperList;
                fcw.MainTableSno = MainTableSno;
                finalWrapperList.add(fcw);
                
            }
            
        }
       
        return finalWrapperList;
    }
    
    //Changes end by Prachi SSE-21664
    public class CompetitorWrapper{
        
        @AuraEnabled public String competitorName { get; set; }
        @AuraEnabled public String estimatedCustomerSpend { get; set; }
        @AuraEnabled public String solution { get; set; }
        @AuraEnabled public String areaDetails { get; set; }
        @AuraEnabled public String strategyToContainOrDisplace { get; set; }
        @AuraEnabled public String id { get; set; }
        @AuraEnabled public String competitorUrl { get; set; }
        @AuraEnabled public Integer serialNumber { get; set; }
        @AuraEnabled public String opportunityUrl { get; set; }
        @AuraEnabled public String opportunityName { get; set; }
        @AuraEnabled public String industry { get; set; }
        @AuraEnabled public String incumbentVendor { get; set; }
        @AuraEnabled public Date incumbentDate { get; set; }
    }
    //Changes start by Prachi SSE-21664 
    public class FinalCompetitorWrapper{
        @AuraEnabled public String compAccountUrl{get; set; }
        @AuraEnabled public String totalEstimatedCustomerSpend { get; set; }
        @AuraEnabled public String competitorAccName { get; set; }
        @AuraEnabled public List<CompetitorWrapper> competitorDetails { get; set; }
        @AuraEnabled public Integer MainTableSno{ get; set; }
    }
    //Changes end by Prachi SSE-21664  
    
}