force-app/main/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Business_Defined_Attribute__c</fullName>
        <label>Business Defined Attribute</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>2024 Grad - Gold</fullName>
                </value>
                <value>
                    <fullName>2024 Grad - Platinum</fullName>
                </value>
                <value>
                    <fullName>2024 Grad - Silver</fullName>
                </value>
                <value>
                    <fullName>2024 Managerial &amp; Professional - Gold</fullName>
                </value>
                <value>
                    <fullName>2024 Managerial &amp; Professional - Platinum</fullName>
                </value>
                <value>
                    <fullName>2024 Managerial &amp; Professional - Silver</fullName>
                </value>
                <value>
                    <fullName>2024 Tech - Gold</fullName>
                </value>
                <value>
                    <fullName>2024 Tech - Platinum</fullName>
                </value>
                <value>
                    <fullName>2024 Tech - Silver</fullName>
                </value>
                <value>
                    <fullName>2024 TM Overall - Gold</fullName>
                </value>
                <value>
                    <fullName>2024 TM Overall - Platinum</fullName>
                </value>
                <value>
                    <fullName>2024 TM Overall - Silver</fullName>
                </value>
                <value>
                    <fullName>2024 Volume - Gold</fullName>
                </value>
                <value>
                    <fullName>2024 Volume - Platinum</fullName>
                </value>
                <value>
                    <fullName>2024 Volume - Silver</fullName>
                </value>
                <value>
                    <fullName>2025 - AMS Tier 1 WS</fullName>
                </value>
                <value>
                    <fullName>2025 - BPO</fullName>
                </value>
                <value>
                    <fullName>2025 - Competitor Displacement</fullName>
                </value>
                <value>
                    <fullName>2025 - Smart Interview Professional</fullName>
                </value>
                <value>
                    <fullName>2025 - Talent Mobility</fullName>
                </value>
                <value>
                    <fullName>Fortune 500</fullName>
                </value>
                <value>
                    <fullName>Project Atom</fullName>
                </value>
                <value>
                    <fullName>Project Atom/AMS-NB2-5/4k-8k/Tranche 3</fullName>
                </value>
                <value>
                    <fullName>Project Atom/AMS-NB2-5/8k-13k/Tranche 1</fullName>
                </value>
                <value>
                    <fullName>Project Atom (Mgr. &amp; Prof)</fullName>
                </value>
                <value>
                    <fullName>Project Atom (Volume)</fullName>
                </value>
                <value>
                    <fullName>Sangam</fullName>
                </value>
                <value>
                    <fullName>White Glove</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Buying_Centre_Id__c</fullName>
        <description>Fro regional grouping of the same accounts, this field will be populated by the BI team.</description>
        <label>Buying Centre Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

force-app/main/objects/Account_Plan__c.object
<CustomObject>
    <description>Module to capture Key Account Plan details</description>
    <fields>
        <fullName>Account_Name__c</fullName>
        <description>This field is used to store the related account for Account Plan</description>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Plans</relationshipLabel>
        <relationshipName>Account_Plans</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Account_Plan_Name__c</fullName>
        <formula>&apos;SHL &apos; + Quarter__c + &quot;/&quot; + Year__c  + &quot; Account Plan - &quot; +   Account_Name__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Plan Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account_Plan_Status__c</fullName>
        <label>Account Plan Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>In Review</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Retired</fullName>
                </value>
                <value>
                    <fullName>Migrated to Regional - Retired</fullName>
                    <isActive>false</isActive>
                    <label>Migrated to Regional - Retired</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Account_Plan_Type__c</fullName>
        <description>Created in Account Plan Phase 4 to determine the type of Account Plan</description>
        <inlineHelpText>This field is used to determine the type of Account Plan</inlineHelpText>
        <label>Account Plan Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Current</fullName>
                    <default>true</default>
                    <label>Current</label>
                </value>
                <value>
                    <fullName>Regional</fullName>
                </value>
                <value>
                    <fullName>Global</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Business_Defined_Attribute__c</fullName>
        <label>Business Defined Attribute</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Buying_Centre_Id__c</fullName>
        <description>This is used to identify if an Account Plan is Regional Account Plan .</description>
        <inlineHelpText>This field shows the value of Buying Centre same as on Account if an Account Plan is regional</inlineHelpText>
        <label>Buying Centre Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cases_Last_12_Months_open_closed__c</fullName>
        <label>All Cases Last 12 mths</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Contacts_Created_Last_12_Months__c</fullName>
        <inlineHelpText>This count only includes Active Contact records.</inlineHelpText>
        <label>Contacts Created Last 12 mths</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Contacts_Created_since_last_review__c</fullName>
        <label>Contacts Created since last review</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Contacts_at_this_Account__c</fullName>
        <label>Contacts at this Account</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Date_for_next_Plan_Review__c</fullName>
        <label>Date for next Plan Review</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_of_Last_Plan_Review__c</fullName>
        <label>Date of Last Plan Review</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Open_Cases__c</fullName>
        <inlineHelpText>These are all open support tickets regardless of priority or severity</inlineHelpText>
        <label>Open Support Cases</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Open_Opportunities__c</fullName>
        <label>Open Opportunities</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Open_Opportunity_Value__c</fullName>
        <label>Open Opportunity Value</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Opportunities_Created_since_last_Review__c</fullName>
        <label>Opportunities Created since last Review</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Subject_discussed_actions_agreed__c</fullName>
        <label>Subject discussed &amp; actions agreed</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Who_did_we_last_meet_in_the_organisation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Who did we last meet in the organisation</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Account_Name__c</field>
                <operation>equals</operation>
                <valueField>Contact.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Account Plans</relationshipLabel>
        <relationshipName>Account_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>is_Account_Plan_Retired__c</fullName>
        <defaultValue>false</defaultValue>
        <label>is Account Plan Retired?</label>
        <type>Checkbox</type>
    </fields>
    <label>Account Plan</label>
    <nameField>
        <displayFormat>ACP-{0000}</displayFormat>
        <label>Account Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Contact_Status__c</fullName>
        <description>To determine which of our contacts are the actual buyers and which can be marketed to and which we have lost contact with</description>
        <label>Contact Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Deceased</fullName>
                </value>
                <value>
                    <fullName>Left Institution</fullName>
                </value>
                <value>
                    <fullName>Retired</fullName>
                </value>
                <value>
                    <fullName>Active-Invalid Email</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Last_Activity_Happen__c</fullName>
        <label>Last Activity Happen</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Subject_Discussed__c</fullName>
        <label>Subject Discussed</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

force-app/main/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Sales_Price_in_USD__c</fullName>
        <description>Used in Account Plan to show USD vaue on contract details.</description>
        <formula>IF(
TEXT(CurrencyIsoCode) = &apos;USD&apos;, Amount,
Amount / CURRENCYRATE(TEXT(CurrencyIsoCode))*CURRENCYRATE(&apos;USD&apos;))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sales Price in USD</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
</CustomObject>

classes/AccountPlanDataFetch.cls
/***********************************************************************************************************************************
* Created By: Prachi Gupta                                                                                                         * 
* Description: This class is created to handle multiple functionality which needs to run in system mode also it will               *
               fetch data for different related objects for Account Plan.(SSE-23166)                                               *
************************************************************************************************************************************/
public without Sharing class AccountPlanDataFetch {
    
    public static List<Account_Plan__c> getAccountPlanData(String BuyingCentreId , string accountId){
         List<Account_Plan__c> accplanList = new  List<Account_Plan__c>();
        if(BuyingCentreId != '' && BuyingCentreId != null){
            accplanList = [select id , name ,Account_Plan_Type__c,Account_Name__c,Date_for_next_Plan_Review__c,
                               Account_Plan_Name__c,Account_Plan_Status__c
                               from Account_Plan__c
                               where (Account_Name__c=:accountId 
                                      or Buying_Centre_Id__c = :BuyingCentreId) 
                               and is_Account_Plan_Retired__c != true  //Change Added Account Plan Phase 4
                              ];
        }
        else{
             accplanList = [select id , name ,Account_Plan_Type__c,Account_Name__c,
                               Date_for_next_Plan_Review__c,
                               Account_Plan_Name__c,Account_Plan_Status__c
                               from Account_Plan__c
                               where Account_Name__c=:accountId 
                               
                              ];
        }
       
        return accplanList;
    }
    
    public static String syncAccountPlanMethod(String accountplanId){
          
       string successMessage = '';  
        Account_Plan__c accPlan = [select id , Account_Name__c,Date_of_Last_Plan_Review__c,
                                   Account_Name__r.Business_Defined_Attribute__c,Account_Plan_Type__c,Buying_Centre_Id__c,
                                   Account_Name__r.CurrencyIsoCode,CurrencyIsoCode,Business_Defined_Attribute__c
                                   from Account_Plan__c where id = :accountplanId];
        List<Contact> contactList = new List<Contact>();
        
        List<Opportunity> oppList = new List<Opportunity>();
        List<Case> caseList = new List<Case>();
        List<Case> allCaseList = new List<Case>();
        Datetime dateTimevar =  System.now();
        DateTime checklastyear = dateTimevar.addYears(-1);
        
        if(accPlan.Account_Plan_Type__c == 'Current'){
            contactList = [select id, Last_Activity_Happen__c,Subject_Discussed__c ,createddate from contact
                           where AccountId = :accPlan.Account_Name__c and 
                           Contact_Status__c = 'Active' 
                           order by Last_Activity_Happen__c desc ];
            
            oppList =[select id , amount , createdDate , Sales_Price_in_USD__c from opportunity 
                      where stagename != 'Closed/Won' and stagename != 'Closed Lost'  
                      and AccountId = :accPlan.Account_Name__c];
            
            caseList =[select id , createddate , status from case where AccountId =:accPlan.Account_Name__c
                       and (not Status like '%close%')];
            
             allCaseList = [select id , createddate , status from case 
                           where  AccountId =:accPlan.Account_Name__c
                           and  CreatedDate > :checklastyear  ];  
        }
        
        
        else if(accPlan.Account_Plan_Type__c == 'Regional'){
            
            contactList = [select id, Last_Activity_Happen__c,Subject_Discussed__c ,createddate from contact
                           where account.Buying_Centre_Id__c = :accPlan.Buying_Centre_Id__c and 
                           Contact_Status__c = 'Active' 
                           order by Last_Activity_Happen__c desc ];
            
            oppList =[select id , amount , createdDate , Sales_Price_in_USD__c from opportunity 
                      where stagename != 'Closed/Won' and stagename != 'Closed Lost'  
                      and account.Buying_Centre_Id__c = :accPlan.Buying_Centre_Id__c];
            
            caseList =[select id , createddate , status from case
                       where Account.Buying_Centre_Id__c =:accPlan.Buying_Centre_Id__c
                       and (not Status like '%close%')];
            
            allCaseList = [select id , createddate , status from case 
                           where  Account.Buying_Centre_Id__c =:accPlan.Buying_Centre_Id__c
                           and  CreatedDate > :checklastyear  ];  
            
        }
        
        
        else if(accPlan.Account_Plan_Type__c == 'Global'){
            
            Set<Id> allAccountIds = new Set<Id>{accPlan.Account_Name__c};
                Set<Id> parentIds = new Set<Id>{accPlan.Account_Name__c};
                    List<Account> childAccounts = new List<Account>();
            do {
                childAccounts = [SELECT Id FROM Account WHERE ParentId IN :parentIds AND RecordType.name != 'Competitor Account'];
                parentIds.clear();
                for (Account child : childAccounts){
                    parentIds.add(child.Id);
                    allAccountIds.add(child.Id);
                }
            } while (childAccounts.size() > 0);
  
            
            contactList = [select id, Last_Activity_Happen__c,Subject_Discussed__c ,createddate from contact
                           where AccountId in :allAccountIds and 
                           Contact_Status__c = 'Active' 
                           order by Last_Activity_Happen__c desc ];
            
            oppList =[select id , amount , createdDate , Sales_Price_in_USD__c from opportunity 
                      where stagename != 'Closed/Won' and stagename != 'Closed Lost'  
                      and AccountId in :allAccountIds];
            
            caseList =[select id , createddate , status from case where AccountId in :allAccountIds
                       and (not Status like '%close%')];
            
             allCaseList = [select id , createddate , status from case 
                           where  AccountId in :allAccountIds
                           and  CreatedDate > :checklastyear  ]; 
        }   
        
        Account_Plan__c ap = new Account_Plan__c();
            
            ap.id = accountplanId;
            if(accPlan.Business_Defined_Attribute__c!=accPlan.Account_Name__r.Business_Defined_Attribute__c){
                ap.Business_Defined_Attribute__c = accPlan.Account_Name__r.Business_Defined_Attribute__c;
            }
            
            
            if(contactList.size() > 0){
                
                Integer totalContactlastyear= 0;  
                Integer contactsCreatedAfterReview =0;
                
                ap.Contacts_at_this_Account__c = contactList.size();
                for(Contact c:contactList){
                    Date created_Date = date.newinstance((c.createdDate).year(), (c.createdDate).month(), (c.createdDate).day());
                   
                    
                    if(c.createdDate > checklastyear){
                        totalContactlastyear = totalContactlastyear +1;
                    }
                    if(accPlan.Date_of_Last_Plan_Review__c != null){
                        
                        if(created_Date > accPlan.Date_of_Last_Plan_Review__c){
                            contactsCreatedAfterReview = contactsCreatedAfterReview + 1;
                        
                        }
                    }
                    
                }
                
                ap.Contacts_Created_Last_12_Months__c = totalContactlastyear;
                ap.Contacts_Created_since_last_review__c = contactsCreatedAfterReview;
            }
            else{
                ap.Contacts_at_this_Account__c = 0;
                ap.Contacts_Created_Last_12_Months__c = 0;
                ap.Contacts_Created_since_last_review__c =0;
            }
             
            
                    if(!caseList.isEmpty()){
                    Integer noOfCase  = 0;
                    for(Case o : caseList){                       
                        noOfCase = noOfCase+ 1;                
                    }
                    ap.Open_Cases__c = noOfCase;
                }
                 else{
                    ap.Open_Cases__c = 0;
                }
                
                if(!allCaseList.isEmpty()){
                    Integer totalCaselastyear = 0;
                    
                    for(Case o : allCaseList){                       
                        totalCaselastyear = totalCaselastyear +1;              
                    }
                    ap.Cases_Last_12_Months_open_closed__c = totalCaselastyear;
                }else{
                    ap.Cases_Last_12_Months_open_closed__c = 0;
                }
            
            if(oppList.size() > 0){
                Decimal oppAmount = 0 ; 
                ap.Open_Opportunities__c = oppList.size();
                Integer oppCreatedAfterReview = 0;
                for(Opportunity o:oppList){
                    Date created_Date = date.newinstance((o.createdDate).year(), (o.createdDate).month(), (o.createdDate).day());
                  
                    if( o.Sales_Price_in_USD__c != null){
                        oppAmount = oppAmount + o.Sales_Price_in_USD__c;
                        
                    }
                    if(accPlan.Date_of_Last_Plan_Review__c != null){
                        
                        if(created_Date > accPlan.Date_of_Last_Plan_Review__c){
                            oppCreatedAfterReview = oppCreatedAfterReview + 1;
                            
                        }
                    }
                }   
                //Integer oppAmountInt = oppAmount.intValue();
                Decimal oppAmountInt = oppAmount.setScale(0);
                ap.Open_Opportunity_Value__c = oppAmountInt;
                ap.Opportunities_Created_since_last_Review__c = oppCreatedAfterReview;
            }
            else{
                ap.Open_Opportunities__c = 0;
                ap.Open_Opportunity_Value__c = 0;
            }
            
            if(accPlan.CurrencyIsoCode != accPlan.Account_Name__r.CurrencyIsoCode){
                ap.CurrencyIsoCode = accPlan.Account_Name__r.CurrencyIsoCode;
            }
            
            update ap; 
            successMessage = 'SUCCESS';
               
       return successMessage;
        
    }
    
    @AuraEnabled
    public static string checkUserAccessOnAP(string accountplanId){
        string AccessLevel = '';
        
        Account_Plan__c accPlan = [select id , Account_Name__c,Date_of_Last_Plan_Review__c,
        Account_Name__r.Business_Defined_Attribute__c,Account_Plan_Type__c,Buying_Centre_Id__c,
        Account_Name__r.CurrencyIsoCode,CurrencyIsoCode,Business_Defined_Attribute__c
        from Account_Plan__c where id = :accountplanId];

        if(accPlan != null){
         UserRecordAccess checkRecordAccess = [SELECT RecordId, HasReadAccess, HasEditAccess FROM UserRecordAccess 
                                                WHERE UserId =:UserInfo.getUserId() 
                                                AND RecordId =:accPlan.Account_Name__c];
         if(checkRecordAccess != null){
             if(checkRecordAccess.HasEditAccess == true){
                  AccessLevel = 'Edit' ;
             }
             else{
                 if(checkRecordAccess.HasReadAccess == true){
                     AccessLevel = 'Read' ; 
                 }
             }
            
               
            
         }
        }
        return AccessLevel;
    }
    
    public static string updateLastContactedDetailsMethod(String accountplanId){
         string successMessage = ''; 
         Account_Plan__c accPlan = [select id , Account_Name__c
                                   from Account_Plan__c where id = :accountplanId];
        
        List<Contact> contactList = [select id, Last_Activity_Happen__c,Subject_Discussed__c from contact
                                     where AccountId = :accPlan.Account_Name__c and Last_Activity_Happen__c != null
                                     order by Last_Activity_Happen__c desc limit 1];
            
            if(contactList.size() > 0){
                for(Contact c:contactList){
                    accPlan.Who_did_we_last_meet_in_the_organisation__c = c.id;
                    accPlan.Subject_discussed_actions_agreed__c = c.Subject_Discussed__c;
                }
            }
            
            update accPlan;
        successMessage = 'SUCCESS';
            return successMessage;
        
        
     
        
    }
        
    
    
}