force-app/main/objects/Account.object
<CustomObject>
    <fields>
        <fullName>BU__c</fullName>
        <label>BU</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Master_BUs</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Billing_Address_Line_1__c</fullName>
        <inlineHelpText>If the address goes over more than one line then please use Address Line 2 and Address Line 3. This formatting will display on any Customer facing documents.</inlineHelpText>
        <label>Billing Address Line 1</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_City__c</fullName>
        <label>Billing City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_Country__c</fullName>
        <label>Billing Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AFGHANISTAN</fullName>
                </value>
                <value>
                    <fullName>ALBANIA</fullName>
                </value>
                <value>
                    <fullName>ALDERNEY</fullName>
                </value>
                <value>
                    <fullName>ALGERIA</fullName>
                </value>
                <value>
                    <fullName>AMERICAN SAMOA</fullName>
                </value>
                <value>
                    <fullName>ANDORRA</fullName>
                </value>
                <value>
                    <fullName>ANGOLA</fullName>
                </value>
                <value>
                    <fullName>ANGUILLA</fullName>
                </value>
                <value>
                    <fullName>ANTARCTICA</fullName>
                </value>
                <value>
                    <fullName>ANTIGUA AND BARBUDA</fullName>
                </value>
                <value>
                    <fullName>ARGENTINA</fullName>
                </value>
                <value>
                    <fullName>ARMENIA</fullName>
                </value>
                <value>
                    <fullName>ARUBA</fullName>
                </value>
                <value>
                    <fullName>AUSTRALIA</fullName>
                </value>
                <value>
                    <fullName>AUSTRIA</fullName>
                </value>
                <value>
                    <fullName>AZERBAIJAN</fullName>
                </value>
                <value>
                    <fullName>BAHAMAS</fullName>
                </value>
                <value>
                    <fullName>BAHRAIN</fullName>
                </value>
                <value>
                    <fullName>BANGLADESH</fullName>
                </value>
                <value>
                    <fullName>BARBADOS</fullName>
                </value>
                <value>
                    <fullName>BELARUS</fullName>
                </value>
                <value>
                    <fullName>BELGIUM</fullName>
                </value>
                <value>
                    <fullName>BELIZE</fullName>
                </value>
                <value>
                    <fullName>BENIN</fullName>
                </value>
                <value>
                    <fullName>BERMUDA</fullName>
                </value>
                <value>
                    <fullName>BHUTAN</fullName>
                </value>
                <value>
                    <fullName>BOLIVIA</fullName>
                </value>
                <value>
                    <fullName>BOSNIA AND HERZEGOWINA</fullName>
                </value>
                <value>
                    <fullName>BOTSWANA</fullName>
                </value>
                <value>
                    <fullName>BOUVET ISLAND</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Billing_State__c</fullName>
        <inlineHelpText>If State is required, please enter as two alphanumeric characters, e.g. GA instead of Georgia</inlineHelpText>
        <label>Billing State/County</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_ZIP_Postal_Code__c</fullName>
        <label>Billing ZIP/Postal Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>1. Not yet trading with SHL - (definition - the account is new and/or has no trading history with SHL to date)
2. Trading with SHL - (definition - the account has sales recorded with SHL in the last 2 years)
3. Ceased Trading with SHL - (definition - the account has not traded with SHL in the past 12 months but has previously.) 
4. Dead - (Gone out of Business) (definition - The Account for whatever reason is no longer a trading entity)
Previous Values
1. Active with SHL (definition - The account has a track record of sales and/or opportunities managed in the last 2 years)
2. Inactive with SHL (definition - The account is still a trading account but there has been no activity with SHL (sales or opportunities managed) in the last 2 years)</description>
        <inlineHelpText>Status indicates if Account is approved or not. If you believe an unapproved Account should be Approved, Submit for Approval.</inlineHelpText>
        <label>Account Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Unapproved</fullName>
                    <default>true</default>
                    <label>Unapproved</label>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Unapproved - Out of Business</fullName>
                </value>
                <value>
                    <fullName>Unapproved - Trade Not Allowed</fullName>
                </value>
                <value>
                    <fullName>Unapproved - Duplicate</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>Call_Type__c</fullName>
        <description>From call logging</description>
        <label>Case Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Account Manager Referral</fullName>
                </value>
                <value>
                    <fullName>Assessment Preview</fullName>
                </value>
                <value>
                    <fullName>Candidate Support call</fullName>
                </value>
                <value>
                    <fullName>Courses/Training/Qualifications</fullName>
                </value>
                <value>
                    <fullName>Course Sales / Bookings</fullName>
                </value>
                <value>
                    <fullName>DC Enquiry</fullName>
                </value>
                <value>
                    <fullName>Delivery/Returns</fullName>
                </value>
                <value>
                    <fullName>Demo</fullName>
                </value>
                <value>
                    <fullName>Demo Actual Responses Report</fullName>
                </value>
                <value>
                    <fullName>Disability query</fullName>
                </value>
                <value>
                    <fullName>Distributors Orders</fullName>
                </value>
                <value>
                    <fullName>External Sales/Marketing call</fullName>
                </value>
                <value>
                    <fullName>Goodwill gesture</fullName>
                </value>
                <value>
                    <fullName>Internal Product Support</fullName>
                </value>
                <value>
                    <fullName>Internal SHL support</fullName>
                </value>
                <value>
                    <fullName>Invoice/Credit/Licence</fullName>
                </value>
                <value>
                    <fullName>Lead Qualifications &amp; Processing</fullName>
                </value>
                <value>
                    <fullName>Leased Materials</fullName>
                </value>
                <value>
                    <fullName>Legacy/offline support</fullName>
                </value>
                <value>
                    <fullName>Managed Services</fullName>
                </value>
                <value>
                    <fullName>Onboarding</fullName>
                </value>
                <value>
                    <fullName>Order Investigation</fullName>
                </value>
                <value>
                    <fullName>Order Placed</fullName>
                </value>
                <value>
                    <fullName>P&amp;P/Book Orders</fullName>
                </value>
                <value>
                    <fullName>Partners</fullName>
                </value>
                <value>
                    <fullName>Phone Issue</fullName>
                </value>
                <value>
                    <fullName>Phone Issues</fullName>
                </value>
                <value>
                    <fullName>PO Number Received</fullName>
                </value>
                <value>
                    <fullName>Pricing Queries</fullName>
                </value>
                <value>
                    <fullName>Product Consulting</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>BU__c</fullName>
        <formula>text(Account.BU__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>BU</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mailing_Address_Line_1__c</fullName>
        <label>Address Line 1</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mailing_City__c</fullName>
        <label>City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mailing_Country__c</fullName>
        <label>Country (not in use)</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AFGHANISTAN</fullName>
                </value>
                <value>
                    <fullName>ALBANIA</fullName>
                </value>
                <value>
                    <fullName>ALDERNEY</fullName>
                </value>
                <value>
                    <fullName>ALGERIA</fullName>
                </value>
                <value>
                    <fullName>AMERICAN SAMOA</fullName>
                </value>
                <value>
                    <fullName>ANDORRA</fullName>
                </value>
                <value>
                    <fullName>ANGOLA</fullName>
                </value>
                <value>
                    <fullName>ANGUILLA</fullName>
                </value>
                <value>
                    <fullName>ANTARCTICA</fullName>
                </value>
                <value>
                    <fullName>ANTIGUA AND BARBUDA</fullName>
                </value>
                <value>
                    <fullName>ARGENTINA</fullName>
                </value>
                <value>
                    <fullName>ARMENIA</fullName>
                </value>
                <value>
                    <fullName>ARUBA</fullName>
                </value>
                <value>
                    <fullName>AUSTRALIA</fullName>
                </value>
                <value>
                    <fullName>AUSTRIA</fullName>
                </value>
                <value>
                    <fullName>AZERBAIJAN</fullName>
                </value>
                <value>
                    <fullName>BAHAMAS</fullName>
                </value>
                <value>
                    <fullName>BAHRAIN</fullName>
                </value>
                <value>
                    <fullName>BANGLADESH</fullName>
                </value>
                <value>
                    <fullName>BARBADOS</fullName>
                </value>
                <value>
                    <fullName>BELARUS</fullName>
                </value>
                <value>
                    <fullName>BELGIUM</fullName>
                </value>
                <value>
                    <fullName>BELIZE</fullName>
                </value>
                <value>
                    <fullName>BENIN</fullName>
                </value>
                <value>
                    <fullName>BERMUDA</fullName>
                </value>
                <value>
                    <fullName>BHUTAN</fullName>
                </value>
                <value>
                    <fullName>BOLIVIA</fullName>
                </value>
                <value>
                    <fullName>BOSNIA AND HERZEGOWINA</fullName>
                </value>
                <value>
                    <fullName>BOTSWANA</fullName>
                </value>
                <value>
                    <fullName>BOUVET ISLAND</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Mailing_State_County__c</fullName>
        <label>State/County</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mailing_ZIP_Postal_Code__c</fullName>
        <label>ZIP/Postal Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Same_As_The_Account_Billing_Address__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If this option is selected, then the Contact Mailing Address is copied from the Account Billing Address.</description>
        <inlineHelpText>Check this box to set the Contact Address to the same as the Account Billing Address. This address will not be populated from the Account until you hit Save. You must ensure this box is not ticked if you want to enter a different address for the Contact.</inlineHelpText>
        <label>Same As The Account Billing Address</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

classes/NVM_Payment_Form_Controller_Tester.cls
@isTest(seeAllData = true)
public class NVM_Payment_Form_Controller_Tester{

     @isTest static void TestVf(){

        Account account=new Account(Status__c='Approved',Billing_Address_Line_1__c='test',Billing_City__c='Test City',Billing_Country__c='Test Country',Billing_State__c='Test',Billing_ZIP_Postal_Code__c='1100110',BU__c='Australia - AU1');
        account.name='Test Account1'+System.now();
        insert account;
        
        Contact con=new Contact(FirstName='abc',lastname='Test Contact1', Accountid=account.id);
        con.Same_As_The_Account_Billing_Address__c=true;
        con.Mailing_Address_Line_1__c ='test';
        con.Mailing_City__c='test';
        con.Mailing_ZIP_Postal_Code__c ='110094';
        con.Mailing_Country__c='India';
        con.Mailing_State_County__c='AB';
        con.email = 'abc@gmail.com';
        insert con;

        Case c = new Case();
        c.RecordtypeId = '012D0000000V9YhIAK';
        c.Origin = 'Phone';
        c.ContactId = con.id;           
        c.Subject = 'Invoice Payment - ';
        c.Call_Type__c = 'Invoice/Credit/Licence';
        c.Status = 'In Progress';
        c.Caller_Type__c = 'Customer';
        c.Account = account;
        c.Contact = con;
        c.CurrencyIsoCode =  'AUD';           
        c.Case_Country__c = con.Mailing_Country__c;           
        c.Description = 'NVM Case';      
        c.Problem2__c = 'Other';
        c.Solution__c = 'Other';            
        c.Preferred_Language__c = 'English';
        c.Caller_s_Name__c = con.Name;        
        c.First_Name__c= con.FirstName;
        c.Last_Name__c= con.LastName;
        c.Building_Name__c= con.Mailing_Address_Line_1__c;    
        c.Street__c = 'abc';
        c.City_town__c = 'abc';
        c.Zip_Postal__c = '2921';
        c.Country__c = 'ARM';
        c.Case_Country__c  = 'ARM';
        c.State__c = 'NS';
        c.Sun_Reference_No__c = '123';
        c.Ref_Type__c = '123';
        
        insert c;
      
        Test.startTest();    
       
        
        ApexPages.StandardController sc = new ApexPages.standardController(c);                              
        PageReference pageRef = Page.NVM_Payment_Form; // Add your VF page Name here
        pageRef.getParameters().put('id', String.valueOf(c.Id));
        pageRef.getParameters().put('selectedCountry','UKR');

        Test.setCurrentPage(pageRef);
   
        NVM_Payment_Form_Controller myPageCon = new NVM_Payment_Form_Controller (sc);
        Test.setMock(HttpCalloutMock.class, new MockHttpNVMResponseGenerator());  // Added by Pankhuri 
        pagereference pg = myPageCon.CallWebService();       
        myPageCon.changeconinfo();
        myPageCon.getCurrencyOption();
        myPageCon.getCountryOption();
        myPageCon.save();
       
        pageRef.getParameters().put('samecont','False');
        myPageCon.changeconinfo();       
       
        Test.stopTest();         

    }

    @isTest static void TestVf_CreateCase(){
    
        Account account=new Account(Status__c='Approved',Billing_Address_Line_1__c='test',Billing_City__c='Test City',Billing_Country__c='Test Country',Billing_State__c='Test',Billing_ZIP_Postal_Code__c='1100110',BU__c='Australia - AU1');
        account.name='Test Account1'+System.now();
        insert account;
        
        Contact con=new Contact(FirstName='abc',lastname='Test Contact1', Accountid=account.id);
        con.Same_As_The_Account_Billing_Address__c=true;
        con.Mailing_Address_Line_1__c ='test';
        con.Mailing_City__c='test';
        con.Mailing_ZIP_Postal_Code__c ='110094';
        con.Mailing_Country__c='India';
        con.Mailing_State_County__c='AB';
        con.email = 'abc@gmail.com';
        insert con;
        
        Test.startTest();
        
        ApexPages.StandardController scn = new ApexPages.standardController(con);
        PageReference pageRef2 = Page.MakePaymentContact; // Add your VF page Name here
        pageRef2.getParameters().put('id', String.valueOf(con.Id));
        Test.setCurrentPage(pageRef2);
        MakePaymentContact myPageCon2 = new MakePaymentContact(scn);
        myPageCon2.createCase();
        
        Test.stopTest(); 
        
    }
    
    @isTest static void TestVf_ErrorClass(){
    
        Account account=new Account(Status__c='Approved',Billing_Address_Line_1__c='test',Billing_City__c='Test City',Billing_Country__c='Test Country',Billing_State__c='Test',Billing_ZIP_Postal_Code__c='1100110',BU__c='Australia - AU1');
        account.name='Test Account1'+System.now();
        insert account;
        
        Contact con=new Contact(FirstName='abc',lastname='Test Contact1', Accountid=account.id);
        con.Same_As_The_Account_Billing_Address__c=true;
        con.Mailing_Address_Line_1__c ='test';
        con.Mailing_City__c='test';
        con.Mailing_ZIP_Postal_Code__c ='110094';
        con.Mailing_Country__c='India';
        con.Mailing_State_County__c='AB';
        con.email = 'abc@gmail.com';
        insert con;
        
        Case c = new Case();
        c.RecordtypeId = '012D0000000V9YhIAK';
        c.Origin = 'Phone';
        c.ContactId = con.id;           
        c.Subject = 'Invoice Payment - ';
        c.Call_Type__c = 'Invoice/Credit/Licence';
        c.Status = 'In Progress';
        c.Caller_Type__c = 'Customer';
        c.Account = account;
        c.Contact = con;
        c.CurrencyIsoCode =  'AUD';           
        c.Case_Country__c = con.Mailing_Country__c;           
        c.Description = 'NVM Case';      
        c.Problem2__c = 'Other';
        c.Solution__c = 'Other';            
        c.Preferred_Language__c = 'English';
        c.Caller_s_Name__c = con.Name;        
        c.First_Name__c= con.FirstName;
        c.Last_Name__c= con.LastName;
        c.Building_Name__c= con.Mailing_Address_Line_1__c;    
        c.Street__c = 'abc';
        c.City_town__c = 'abc';
        c.Zip_Postal__c = '2921';
        c.Country__c = 'ARM';
        c.Case_Country__c  = 'ARM';
        c.State__c = 'NS';
        c.Sun_Reference_No__c = '123';
        c.Ref_Type__c = '123';        
        insert c;
        
        Test.startTest();
       
        PageReference pageRef2 = Page.NVM_ErrorPaymentControllerVF; // Add your VF page Name here
        pageRef2.getParameters().put('err', String.valueOf('this is test error msg'));
        Test.setCurrentPage(pageRef2);
        NVM_ErrorPaymentController myPageCon2 = new NVM_ErrorPaymentController();
        myPageCon2.ReturnHome();
        
        Test.stopTest(); 
        
     }
    
     @isTest static void Test_NVM_PaymentController2(){
        Account account=new Account(Status__c='Approved',Billing_Address_Line_1__c='test',Billing_City__c='Test City',Billing_Country__c='Test Country',Billing_State__c='Test',Billing_ZIP_Postal_Code__c='1100110',BU__c='Australia - AU1');
        account.name='Test Account1'+System.now();
        insert account;
        
        Contact con=new Contact(FirstName='abc',lastname='Test Contact1', Accountid=account.id);
        con.Same_As_The_Account_Billing_Address__c=true;
        con.Mailing_Address_Line_1__c ='test';
        con.Mailing_City__c='test';
        con.Mailing_ZIP_Postal_Code__c ='110094';
        con.Mailing_Country__c='India';
        con.Mailing_State_County__c='AB';
        con.email = 'abc@gmail.com';
        insert con;
        
        Case c = new Case();
        c.RecordtypeId = '012D0000000V9YhIAK';
        c.Origin = 'Phone';
        c.ContactId = con.id;           
        c.Subject = 'Invoice Payment - ';
        c.Call_Type__c = 'Invoice/Credit/Licence';
        c.Status = 'In Progress';
        c.Caller_Type__c = 'Customer';
        c.Account = account;
        c.Contact = con;
        c.CurrencyIsoCode =  'AUD';           
        c.Case_Country__c = con.Mailing_Country__c;           
        c.Description = 'NVM Case';      
        c.Problem2__c = 'Other';
        c.Solution__c = 'Other';            
        c.Preferred_Language__c = 'English';
        c.Caller_s_Name__c = con.Name;        
        c.First_Name__c= con.FirstName;
        c.Last_Name__c= con.LastName;
        c.Building_Name__c= con.Mailing_Address_Line_1__c;    
        c.Street__c = 'abc';
        c.City_town__c = 'abc';
        c.Zip_Postal__c = '2921';
        c.Country__c = 'ARM';
        c.Case_Country__c  = 'ARM';
        c.State__c = 'NS';
        c.Sun_Reference_No__c = '123';
        c.Ref_Type__c = '123';        
        insert c;
        
        Test.startTest();
       
        PageReference pageRef = Page.NVM_PaymentControllerVF; // Add your VF page Name here
        pageRef.getParameters().put('Sid', String.valueOf('123'));
        pageRef.getParameters().put('tk', String.valueOf('1234'));
        pageRef.getParameters().put('t', String.valueOf('123'));
        pageRef.getParameters().put('rtk', String.valueOf('123'));
        pageRef.getParameters().put('Iurl', String.valueOf('iframed'));
        pageRef.getParameters().put('Csid', String.valueOf(c.id));
        Test.setCurrentPage(pageRef);
        NVM_PaymentController2 myPageCon = new NVM_PaymentController2();
        Test.setMock(HttpCalloutMock.class, new MockHttpNVMResponseGenerator());  // Added by Pankhuri 
        myPageCon.PaymentStatus();
       
        Test.stopTest(); 
     }
     
     @isTest static void Test2_NVM_PaymentController2(){
        Account account=new Account(Status__c='Approved',Billing_Address_Line_1__c='test',Billing_City__c='Test City',Billing_Country__c='Test Country',Billing_State__c='Test',Billing_ZIP_Postal_Code__c='1100110',BU__c='Australia - AU1');
        account.name='Test Account1'+System.now();
        insert account;
        
        Contact con=new Contact(FirstName='abc',lastname='Test Contact1', Accountid=account.id);
        con.Same_As_The_Account_Billing_Address__c=true;
        con.Mailing_Address_Line_1__c ='test';
        con.Mailing_City__c='test';
        con.Mailing_ZIP_Postal_Code__c ='110094';
        con.Mailing_Country__c='India';
        con.Mailing_State_County__c='AB';
        con.email = 'abc@gmail.com';
        insert con;
        
        Case c = new Case();
        c.RecordtypeId = '012D0000000V9YhIAK';
        c.Origin = 'Phone';
        c.ContactId = con.id;           
        c.Subject = 'Invoice Payment - ';
        c.Call_Type__c = 'Invoice/Credit/Licence';
        c.Status = 'In Progress';
        c.Caller_Type__c = 'Customer';
        c.Account = account;
        c.Contact = con;
        c.CurrencyIsoCode =  'AUD';           
        c.Case_Country__c = con.Mailing_Country__c;           
        c.Description = 'NVM Case';      
        c.Problem2__c = 'Other';
        c.Solution__c = 'Other';            
        c.Preferred_Language__c = 'English';
        c.Caller_s_Name__c = con.Name;        
        c.First_Name__c= con.FirstName;
        c.Last_Name__c= con.LastName;
        c.Building_Name__c= con.Mailing_Address_Line_1__c;    
        c.Street__c = 'abc';
        c.City_town__c = 'abc';
        c.Zip_Postal__c = '2921';
        c.Country__c = 'ARM';
        c.Case_Country__c  = 'ARM';
        c.State__c = 'NS';
        c.Sun_Reference_No__c = '123';
        c.Ref_Type__c = '123';        
        insert c;
        
        Test.startTest();
       
        PageReference pageRef = Page.NVM_PaymentControllerVF; // Add your VF page Name here
        pageRef.getParameters().put('Sid', String.valueOf('234'));
        pageRef.getParameters().put('tk', String.valueOf('1234'));
        pageRef.getParameters().put('t', String.valueOf('123'));
        pageRef.getParameters().put('rtk', String.valueOf('123'));
        pageRef.getParameters().put('Iurl', String.valueOf('iframed'));
        pageRef.getParameters().put('Csid', String.valueOf(c.id));
        Test.setCurrentPage(pageRef);        
        NVM_PaymentController2 myPageCon = new NVM_PaymentController2();
        Test.setMock(HttpCalloutMock.class, new MockHttpNVMResponseGenerator());  // Added by Pankhuri 
        myPageCon.PaymentStatus();
        
        Test.stopTest(); 
     }


}