force-app/main/objects/Assessment__c.object
<CustomObject>
    <description>Area to keep list of all course types, codes, costs and venues</description>
    <fields>
        <fullName>Profit_Centre__c</fullName>
        <inlineHelpText>Where the revenue is recognised</inlineHelpText>
        <label>Profit Centre</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Belgium - BE5</fullName>
                </value>
                <value>
                    <fullName>Denmark - DK5</fullName>
                </value>
                <value>
                    <fullName>France - FR5</fullName>
                </value>
                <value>
                    <fullName>Netherlands - NL5</fullName>
                    <default>true</default>
                    <label>Netherlands - NL5</label>
                </value>
                <value>
                    <fullName>Germany - DE5</fullName>
                </value>
                <value>
                    <fullName>Sweden - SE1</fullName>
                </value>
                <value>
                    <fullName>UK - UK1</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SSC_Email__c</fullName>
        <label>SSC Email</label>
        <type>Email</type>
    </fields>
    <label>Assessment</label>
    <nameField>
        <displayFormat>AS{000000}</displayFormat>
        <label>Assessment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Assessment_Manager.cls
public class Assessment_Manager 
{
    public static void ChkProfCenter(List<Assessment__c> NewAssessments,List<Assessment__c> OldAssessments)
    {
        List<Assessment__c> modifiedAssessments = new List<Assessment__c>();
        for(Integer i=0; i<trigger.new.size(); i++){
            if(NewAssessments[i].Profit_Centre__c != OldAssessments[i].Profit_Centre__c)
              modifiedAssessments.add(NewAssessments[i]);
        }
            setupAssessmentData(modifiedAssessments);
    
    }
    
    public static void setupAssessmentData(List<Assessment__c> assessments)
    {
        for(Assessment__c assessment: assessments)
        {
            Integer startIndexOfCharacter = assessment.Profit_Centre__c.indexOf('-')+2;
            Integer endIndexOfCharacter = startIndexOfCharacter+2;
            if(assessment.Profit_Centre__c.substring(startIndexOfCharacter,endIndexOfCharacter)=='uk')
                endIndexOfCharacter =startIndexOfCharacter+3;
            assessment.SSC_Email__c = assessment.Profit_Centre__c.substring(startIndexOfCharacter,endIndexOfCharacter) +'SOE@shlgroup.com';
        }   
    }        
}