force-app/main/objects/AutomaticJobCreation__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>MS_Line_of_Business__c</fullName>
        <label>MS - Line of Business</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>AutomaticJobCreation</label>
</CustomObject>

objects/Bureau_Candidate__c.object
<CustomObject>
    <description>Managed Services module</description>
    <fields>
        <fullName>Category__c</fullName>
        <description>This field is used to capture Rater Type or Category of Candidate. Applicable only for MFS</description>
        <label>Category</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Afghanistan</fullName>
                </value>
                <value>
                    <fullName>Albania</fullName>
                </value>
                <value>
                    <fullName>Algeria</fullName>
                </value>
                <value>
                    <fullName>American Samoa</fullName>
                </value>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Angola</fullName>
                </value>
                <value>
                    <fullName>Anguilla</fullName>
                </value>
                <value>
                    <fullName>Antartica</fullName>
                </value>
                <value>
                    <fullName>Antigua and Barbuda</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Armenia</fullName>
                </value>
                <value>
                    <fullName>Aruba</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Azerbaidjan</fullName>
                </value>
                <value>
                    <fullName>Bahamas</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Bangladesh</fullName>
                </value>
                <value>
                    <fullName>Barbados</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Benin</fullName>
                </value>
                <value>
                    <fullName>Bermuda</fullName>
                </value>
                <value>
                    <fullName>Bhutan</fullName>
                </value>
                <value>
                    <fullName>Bolivia</fullName>
                </value>
                <value>
                    <fullName>Bosnia-Herzegovina</fullName>
                </value>
                <value>
                    <fullName>Botswana</fullName>
                </value>
                <value>
                    <fullName>Bouvet Island</fullName>
                </value>
                <value>
                    <fullName>Brazil</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Male</fullName>
                </value>
                <value>
                    <fullName>Female</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone_Number__c</fullName>
        <label>Phone Number</label>
        <type>Phone</type>
    </fields>
    <label>Managed Services Candidate</label>
    <nameField>
        <displayFormat>BC{000000000}</displayFormat>
        <label>Candidate Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Managed Services Candidates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Job__c.object
<CustomObject>
    <description>The entity used to identify a work request from a client to the Bureau.</description>
    <fields>
        <fullName>MS_Line_of_Business__c</fullName>
        <description>This field stores the MS- Line of business selected by the user</description>
        <label>MS - Line of Business</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>TA - Corporate</fullName>
                </value>
                <value>
                    <fullName>TA - Credentialing</fullName>
                </value>
                <value>
                    <fullName>Talent Management</fullName>
                </value>
                <value>
                    <fullName>Talent Management (Dashboards)</fullName>
                </value>
                <value>
                    <fullName>TA - Vocational (Analytics)</fullName>
                </value>
                <value>
                    <fullName>TA - Vocational (Batch)</fullName>
                </value>
                <value>
                    <fullName>TA - Vocational (School)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>bulkJobId__c</fullName>
        <description>This field is used to store comma separated Bulk Data Job Ids for Candidate upload</description>
        <label>bulkJobId</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>Job</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Job Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>MS_Product__c</fullName>
        <formula>PricebookEntry.Product2.MS_Product__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>MS Product</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Renewable__c</fullName>
        <inlineHelpText>This is a renewable product</inlineHelpText>
        <label>Renewable(depricated)</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

force-app/main/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>MS_Product__c</fullName>
        <defaultValue>false</defaultValue>
        <label>MS Product</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MS_Type__c</fullName>
        <description>Value in this field defines the Product used by which MS Team, also this field being used to map LOB on auto created jobs based on the product selected at Opportunity level.</description>
        <label>MS Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>TA - Corporate</fullName>
                </value>
                <value>
                    <fullName>TA - Vocational</fullName>
                </value>
                <value>
                    <fullName>Talent Management</fullName>
                </value>
                <value>
                    <fullName>TA - Credentialing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Renewable__c</fullName>
        <inlineHelpText>This is a renewable product</inlineHelpText>
        <label>Renewable</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Revenue_Category__c</fullName>
        <label>Stream</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Professional Services</fullName>
                </value>
                <value>
                    <fullName>Managed Services</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Product subscription</fullName>
                </value>
                <value>
                    <fullName>Product in advance</fullName>
                </value>
                <value>
                    <fullName>Product in arrears</fullName>
                </value>
                <value>
                    <fullName>Professional Services (Public Training)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

force-app/main/objects/User.object
<CustomObject>
    <fields>
        <fullName>Is_Job_Manager__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Job Manager</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Managed_Service_Manager__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is used to identify Managed Service Job Project Manager</description>
        <label>Is Managed Service Manager</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MS_LOB__c</fullName>
        <description>This field defines the MS Team user belongs to &amp; controls the names appearing in Project Manager lookup on Job</description>
        <label>MS LOB</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>TA - Corporate</fullName>
                </value>
                <value>
                    <fullName>TA - Credentialing</fullName>
                </value>
                <value>
                    <fullName>Talent Management</fullName>
                </value>
                <value>
                    <fullName>Talent Management (Dashboards)</fullName>
                </value>
                <value>
                    <fullName>TA - Vocational (Analytics)</fullName>
                </value>
                <value>
                    <fullName>TA - Vocational (Batch)</fullName>
                </value>
                <value>
                    <fullName>TA - Vocational (School)</fullName>
                </value>
                <value>
                    <fullName>TA - Corporate &amp; TA - Credentialing</fullName>
                </value>
                <value>
                    <fullName>TA - Corporate &amp; Talent Management</fullName>
                </value>
                <value>
                    <fullName>TA - Vocational (Analytics) &amp; Talent Management</fullName>
                </value>
                <value>
                    <fullName>TA - Vocational (Batch) &amp; Talent Management</fullName>
                </value>
                <value>
                    <fullName>TA - Vocational (School) &amp; Talent Management</fullName>
                </value>
                <value>
                    <fullName>TA - Vocational (Analytics) &amp; TA - Corporate</fullName>
                </value>
                <value>
                    <fullName>TA - Vocational (Batch) &amp; TA - Corporate</fullName>
                </value>
                <value>
                    <fullName>TA - Vocational (School) &amp; TA - Corporate</fullName>
                </value>
                <value>
                    <fullName>TA - Corporate, TA - Credentialing, Talent Management, TA - Vocational (Batch) &amp; TA - Vocational (School)</fullName>
                </value>
                <value>
                    <fullName>TA - Vocational (Batch), TA - Vocational (School) &amp; TA - Vocational (Analytics)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

classes/Test_SchedulableClassToGetJobStatus.cls
@isTest
public class Test_SchedulableClassToGetJobStatus {
    
    @testSetup static void setup() {
        
        String valueFV = 'XTRAE-EMP,XTRAE-ASSOC,XTREL,DEB,FREIGHT';
        createFieldValueCustomSettingRecords(valueFV, 'Credit Note IM Codes');  
        
        createTriggerActivationCustomSettingRecords('User', 'User_Trigger');
        createTriggerActivationCustomSettingRecords('Account', 'Account_Trigger');
        createTriggerActivationCustomSettingRecords('Contact', 'Contact_Trigger');
        createTriggerActivationCustomSettingRecords('Opportunity', 'Opportunity_Trigger');
        createTriggerActivationCustomSettingRecords('OpportunityLineItem', 'OpportunityLineItem_Trigger');
        createTriggerActivationCustomSettingRecords('OpportunityContactRole', 'OpportunityContactRoleTrigger');
        createTriggerActivationCustomSettingRecords('Job__c', 'Job_Trigger');
        createTriggerActivationCustomSettingRecords('Order', 'Order_Trigger');
        createTriggerActivationCustomSettingRecords('ContentDocument', 'ContentDocument_Trigger');
        createTriggerActivationCustomSettingRecords('ContentDocumentLink', 'ContentDocumentLink_Trigger');
        
        User userRecord = TestDataUtility.getUser('Managed Service Lightning');
        userRecord.MS_LOB__c = 'TA - Corporate, TA - Credentialing, Talent Management, TA - Vocational (Batch) & TA - Vocational (School)';
        userRecord.Is_Job_Manager__c = true;
        userRecord.Is_Managed_Service_Manager__c = true;
        INSERT userRecord;
        
        Account accountRecord = TestDataUtility.getAccount();
        INSERT accountRecord;
        
        Contact contactRecord = TestDataUtility.getContact(accountRecord.Id);
        INSERT contactRecord;
        
        // Custom Setting for Auto Job creation
        AutomaticJobCreation__c cs = new AutomaticJobCreation__c();
        cs.Name='Values';
        cs.MS_Line_of_Business__c = 'TA - Corporate,Talent Management,TA - Credentialing';
        INSERT cs;
        
        Id pricebookId = Test.getStandardPricebookId();
        
        Opportunity opportunityRecord = TestDataUtility.getOpportunity(accountRecord.id, contactRecord.id, userRecord.Id);
        opportunityRecord.Pricebook2Id = pricebookId;
        INSERT opportunityRecord;
        
        Id oppPriceBookId = [SELECT Pricebook2Id FROM Opportunity WHERE Id =: opportunityRecord.Id].Pricebook2Id;
        
        // First Product
        Product2 productRecord = TestDataUtility.getProduct2();
        productRecord.Revenue_Category__c='Managed Services';
        productRecord.Renewable__c = 'No';
        productRecord.MS_Product__c = true;
        productRecord.MS_Type__c = 'Talent Management';
        productRecord.Family = 'Services';
        INSERT productRecord;
        
        PricebookEntry pricebookEntryRecord1 = TestDataUtility.getPricebookEntry(productRecord.Id, 'GBP', pricebookId);
        INSERT pricebookEntryRecord1;
        
        PricebookEntry pricebookEntryRecord = TestDataUtility.getPricebookEntry(productRecord.Id, 'GBP', oppPriceBookId);
        INSERT pricebookEntryRecord;
        
        OpportunityLineItem oli = new OpportunityLineItem(
            OpportunityId = opportunityRecord.Id,
            Quantity = 5,
            PricebookEntryId = pricebookEntryRecord.Id,
            TotalPrice = 10 * pricebookEntryRecord.UnitPrice
        );
        insert oli;
        
        Opportunity opp = [SELECT Id, StageName FROM Opportunity WHERE Id =: opportunityRecord.Id];
        opp.StageName = 'Closed/Won';
        UPDATE opp;
        
        Job__c jobRecord = [SELECT Id,bulkJobId__c FROM Job__c LIMIT 1];
        Bureau_Candidate__c candidateRecord = new Bureau_Candidate__c();
        list<Bureau_Candidate__c> candidateRecordList = new list<Bureau_Candidate__c>();
        candidateRecord = TestDataUtility.getCandidate(jobRecord.Id, 'Pass', 'candidate1@test.com');
        candidateRecordList.add(candidateRecord);
        candidateRecord = TestDataUtility.getCandidate(jobRecord.Id, 'Fail', 'candidate2@test.com');
        candidateRecordList.add(candidateRecord);
        candidateRecord = TestDataUtility.getCandidate(jobRecord.Id, 'DNA', 'candidate3@test.com');
        candidateRecordList.add(candidateRecord);
        candidateRecord = TestDataUtility.getCandidate(jobRecord.Id, 'Completed', 'candidate4@test.com');
        candidateRecordList.add(candidateRecord);
        candidateRecord = TestDataUtility.getCandidate(jobRecord.Id, 'In Progress', 'candidate5@test.com');
        candidateRecordList.add(candidateRecord);
        candidateRecord = TestDataUtility.getCandidate(jobRecord.Id, 'Not Started', 'candidate6@test.com');
        candidateRecordList.add(candidateRecord);
        INSERT candidateRecordList;
        
    }
    
    public static void createTriggerActivationCustomSettingRecords(String objectName, String customSettingName){
        Trigger_Activation__c recordToInsert = TestDataUtility.getTriggerActivation(objectName, customSettingName);
        INSERT recordToInsert;
    }
    
    public static void createFieldValueCustomSettingRecords(String values, String customSettingName){
        Field_Value_Setting__c fVS = TestDataUtility.getFieldValueSetting(values, customSettingName);
        INSERT fVS;
    }
    
    public static void testUploadFile(Job__c jobRecord){
        String base64 = 'Category__c,First_Name__c,Last_Name__c,Email__c,Gender__c,Phone_Number__c,Country__c,Language__c,Status2__c,Reports_Status__c,Username__c,Product_Assessment__c,System_s__c,Email_as_Username__c,Bureau_Job__c,Candidate_Unique_Id__c \n' + 
            'Self,Kevin,Laird,kevin.laird@test.com,Male,9090909090,India,English,Not Started,Sent,testjkb jk,shl 360,MFS,true,a003G000000sn8iQAA,a003G000000sn8iQAAKevinLairdkevin.laird@test.comtestjkb jk \n'; 
        CandidateUploadContoller.uploadFile(base64, 'Test_CandidateImportSheet.csv', jobRecord.Id); 
    }
    
    public static void callScheduleClass(Job__c jobRecord){
        ScheduleClassToGetJobStatus scheduleJob = new ScheduleClassToGetJobStatus(jobRecord.Id);
        String hour = String.valueOf(Datetime.now().hour());
        String min = String.valueOf(Datetime.now().minute());
        String ss = String.valueOf(Datetime.now().second());
        String sch = ss + ' ' + min + ' ' + hour + ' * * ?';
        String jobID1 = System.schedule('Test Get Bulk Job Status '+System.now(), sch, scheduleJob);
    }
    
    @isTest
    public static void testSuccessRecords(){
        String jobId;
        Job__c jobRecord = [SELECT Id,bulkJobId__c FROM Job__c LIMIT 1];
        Test.StartTest();
        User u1 = [SELECT id from User WHERE email = 'standarduser@testorg.com' LIMIT 1];
        
        System.runAs(u1){
            String responseBody = '{"id":"'+jobRecord.id+'","state":"JobComplete","numberRecordsFailed":'+0+',"numberRecordsProcessed":'+1+'}';
            System.Test.setMock(HttpCalloutMock.class, new SchedulableClassMock(1, 0, responseBody));
            testUploadFile(jobRecord);
            callScheduleClass(jobRecord);
        }
        Test.stopTest();
    }
    
    @isTest
    public static void testFailureRecords(){
        String jobId;
        Job__c jobRecord = [SELECT Id,Name,bulkJobId__c FROM Job__c LIMIT 1];
        Test.StartTest();
        User u1 = [SELECT id from User WHERE email = 'standarduser@testorg.com' LIMIT 1];
        String responseBody;
        System.runAs(u1){
            responseBody = '{"id":"'+jobRecord.id+'","state":"JobComplete","numberRecordsFailed":'+1+',"numberRecordsProcessed":'+1+'}\n'+
                '"sf_Id","sf_Error",Category\n'+'"","INVALID FIELD","Self1"\n';
            
            System.Test.setMock(HttpCalloutMock.class, new SchedulableClassMock(1, 1, responseBody));
            testUploadFile(jobRecord);
            callScheduleClass(jobRecord);
        }
        Test.stopTest();
    }
    
    @isTest
    public static void testFailureRecords2(){
        String jobId;
        Job__c jobRecord = [SELECT Id,Name,bulkJobId__c FROM Job__c LIMIT 1];
        Test.StartTest();
        User u1 = [SELECT id from User WHERE email = 'standarduser@testorg.com' LIMIT 1];
        String responseBody;
        System.runAs(u1){
            responseBody = '{"id":"'+jobRecord.id+'","state":"JobComplete","numberRecordsFailed":'+1+',"numberRecordsProcessed":'+2+'}\n'+
                '"sf_Id","sf_Error",Category\n'+'"","INVALID FIELD","Self1"\n';
            
            System.Test.setMock(HttpCalloutMock.class, new SchedulableClassMock(1, 1, responseBody));
            testUploadFile(jobRecord);
            callScheduleClass(jobRecord);
        }
        Test.stopTest();
    }
    
    public static void testRatingUploadFile(Job__c jobRecord){
        String base64 = 'Category,Email,Recipient_Email,\n' + 
            'Self,kevin.laird@test.com,kevin.laird@test.com\n'; 
        CandidateUploadContoller.uploadFile(base64, 'Test_CandidateImportRatingSheet.csv', jobRecord.Id); 
    }
    
    @isTest
    public static void testSuccessRecordsRating(){
        String jobId;
        Job__c jobRecord = [SELECT Id,bulkJobId__c FROM Job__c LIMIT 1];
        Test.StartTest();
        User u1 = [SELECT id from User WHERE email = 'standarduser@testorg.com' LIMIT 1];
        
        System.runAs(u1){
            String responseBody = '{"id":"'+jobRecord.id+'","state":"JobComplete","numberRecordsFailed":'+0+',"numberRecordsProcessed":'+2+'}';
            System.Test.setMock(HttpCalloutMock.class, new SchedulableClassMock(2, 0, responseBody));
            testUploadFile(jobRecord);
            testRatingUploadFile(jobRecord);
            callScheduleClass(jobRecord);
        }
        Test.stopTest();
    }
    
    /* Method to cover below classes as code snippet of these are not in use and commented */
    @isTest
    public static void coverEmptyClasses(){
        BureauCandidateTriggerManager_1 class1 = new BureauCandidateTriggerManager_1();
        BureauJob_InstrumentAssigner class2 = new BureauJob_InstrumentAssigner();
        BureauJob_InstrumentManager class3 = new BureauJob_InstrumentManager();
        BureauJob_RatingManager class4 = new BureauJob_RatingManager();
        MS_InvoiceTriggerManager class5 = new MS_InvoiceTriggerManager();
        MS_RatingTriggerManager class6 = new MS_RatingTriggerManager();
        BureauJob_InvoiceManager class7 = new BureauJob_InvoiceManager();
        BureauJob_ManageInvoice class8 = new BureauJob_ManageInvoice();
        MS_SystemTriggerManager class9 = new MS_SystemTriggerManager();
        BureauJob_CandidateImporter class10 = new BureauJob_CandidateImporter();
        manageBureauRatingProgressInsert_Batch class11 = new manageBureauRatingProgressInsert_Batch();
    }
    
}