force-app/main/objects/AutomaticJobCreation__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>MS_Line_of_Business__c</fullName>
        <label>MS - Line of Business</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>AutomaticJobCreation</label>
</CustomObject>

force-app/main/objects/Bureau_System__c.object
<CustomObject>
    <description>This object represents a relation between a Bureau Job and a System.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field represents the Job Account to which the selected System must belong if it is a Client System.</description>
        <inlineHelpText>Select the Account for selecting a Client System</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Bureau_Systems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>System__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field represents the System that is used by the Bureau Job</description>
        <inlineHelpText>Select the System to be used</inlineHelpText>
        <label>System</label>
        <referenceTo>System__c</referenceTo>
        <relationshipName>Bureau_Systems</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Managed Services System</label>
    <nameField>
        <displayFormat>BJS{000000}</displayFormat>
        <label>Managed Services System Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Managed Services Systems</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Job__c.object
<CustomObject>
    <description>The entity used to identify a work request from a client to the Bureau.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Looks up existing SFDC accounts</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>R00N20000000oB15EAE</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Candidate_Username_Prefix__c</fullName>
        <description>This field is meant for specifying a 4-character text that shall be used as a prefix of the usernames generated for the candidates of a Job.</description>
        <inlineHelpText>Specify the username prefix for all candidates of this Job.</inlineHelpText>
        <label>Candidate Username Prefix</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <description>This field represents the date on which the Project Job shall end</description>
        <inlineHelpText>This project shall end on this date</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>External_Contact_Other_Email_Address__c</fullName>
        <label>External Contact (Others) Email Address</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>External_Contact_Others__c</fullName>
        <description>This field is meant for entering the External Contact if it does not exist on the system</description>
        <inlineHelpText>If the external contact exists on Salesforce, then select the contact from External Contact field above otherwise enter the Contact name in this field as it is mandatory to enter the External Contact.</inlineHelpText>
        <label>External Contact (Others)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Generic_BS_Field_One__c</fullName>
        <label>Generic Bureau Field One</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Generic_Field_MS_One__c</fullName>
        <label>Generic Field MS One</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Generic_Field_Pipeline_One__c</fullName>
        <label>Generic Field Pipeline One</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>InternalContact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is meant for looking a Salesforce User who is the internal contact for this project.</description>
        <inlineHelpText>Select the Salesforce User who shall be the Internal Contact for this project.</inlineHelpText>
        <label>Internal Contact</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Is_Redirect_To_Task__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is used to redirect user to Task tab when user create a new Job for the first time.</description>
        <label>Is Redirect To Task</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Job_Type__c</fullName>
        <description>To be selected when a Job is added</description>
        <label>Job Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Bureau Task</fullName>
                </value>
                <value>
                    <fullName>Express Bureau</fullName>
                </value>
                <value>
                    <fullName>Offline Express</fullName>
                </value>
                <value>
                    <fullName>Offline Project</fullName>
                </value>
                <value>
                    <fullName>Offline Task</fullName>
                </value>
                <value>
                    <fullName>OLB</fullName>
                    <default>true</default>
                    <label>OLB</label>
                </value>
                <value>
                    <fullName>Online Express</fullName>
                </value>
                <value>
                    <fullName>Online Task</fullName>
                </value>
                <value>
                    <fullName>Premier Bureau</fullName>
                </value>
                <value>
                    <fullName>Project - 360</fullName>
                </value>
                <value>
                    <fullName>Project - 360 Managed Serv</fullName>
                </value>
                <value>
                    <fullName>Project - Managed Serv</fullName>
                </value>
                <value>
                    <fullName>Project - Other</fullName>
                </value>
                <value>
                    <fullName>Offline</fullName>
                </value>
                <value>
                    <fullName>Online</fullName>
                </value>
                <value>
                    <fullName>SHL Online</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MS_Line_of_Business__c</fullName>
        <description>This field stores the MS- Line of business selected by the user</description>
        <label>MS - Line of Business</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>TA - Corporate</fullName>
                </value>
                <value>
                    <fullName>TA - Credentialing</fullName>
                </value>
                <value>
                    <fullName>Talent Management</fullName>
                </value>
                <value>
                    <fullName>Talent Management (Dashboards)</fullName>
                </value>
                <value>
                    <fullName>TA - Vocational (Analytics)</fullName>
                </value>
                <value>
                    <fullName>TA - Vocational (Batch)</fullName>
                </value>
                <value>
                    <fullName>TA - Vocational (School)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Jobs</relationshipLabel>
        <relationshipName>Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PurchaseOrderNo__c</fullName>
        <label>Purchase Order Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ShortFall_Customer__c</fullName>
        <description>This field represents the Shortfall Parameter for the rater type &apos;Internal/External Customer&apos;</description>
        <inlineHelpText>This field represents the Shortfall Parameter for the rater type &apos;Internal/External Customer&apos;</inlineHelpText>
        <label>Internal/External Customer</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ShortFall_Manager__c</fullName>
        <description>This field represents the Shortfall Parameter for the rater type &apos;Manager/Supervisor&apos;</description>
        <inlineHelpText>Specify the Shortfall parameter for the rater type &apos;Manager/Supervisor&apos;</inlineHelpText>
        <label>Manager/Supervisor</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ShortFall_Other__c</fullName>
        <description>This field represents the Shortfall Parameter for the rater type &apos;Stakeholder/Other/Others&apos;</description>
        <inlineHelpText>Specify the Shortfall parameter for the rater type &apos;Stakeholder/Other/Others&apos;</inlineHelpText>
        <label>Stakeholder/Other</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Shortfall_Client__c</fullName>
        <description>This field represents the Shortfall Parameter for the rater type &apos;Internal/External Client&apos;</description>
        <inlineHelpText>Specify the Shortfall parameter for the rater type &apos;Internal/External Client&apos;</inlineHelpText>
        <label>Internal/External Client</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Shortfall_Peer__c</fullName>
        <description>This field represents the Shortfall Parameter for the rater type &apos;Peer/Colleague&apos;</description>
        <inlineHelpText>Specify the Shortfall parameter for the rater type &apos;Peer/Colleague&apos;</inlineHelpText>
        <label>Peer/Colleague</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Shortfall_Subordinate__c</fullName>
        <description>This field represents the Shortfall Parameter for the rater type &apos;DirectReport/Report/Subordinate&apos;</description>
        <inlineHelpText>Specify the Shortfall parameter for the rater type &apos;Direct Report/Report/Subordinate&apos;</inlineHelpText>
        <label>Direct Report/Report/Subordinate</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>This field represents the date on which the Project Job is started</description>
        <inlineHelpText>This project started on this date</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Job</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Job Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <recordTypes>
        <fullName>Managed_Service_Pipeline</fullName>
        <active>true</active>
        <label>Managed Service Pipeline</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/objects/System__c.object
<CustomObject>
    <description>For customer systems to be logged for external clients</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Systems</relationshipLabel>
        <relationshipName>Systems</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>System</label>
    <nameField>
        <displayFormat>SYS{00000}</displayFormat>
        <label>SFDC Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Systems</pluralLabel>
    <recordTypes>
        <fullName>SHL_System</fullName>
        <active>true</active>
        <description>This system represents an SHL System</description>
        <label>SHL System</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/SystemManagerControllerTest.cls
@isTest
public class SystemManagerControllerTest {

    @testSetup
    public static void setup() {
        
        createTriggerActivationCustomSettingRecords('System', 'System_Trigger');
        createTriggerActivationCustomSettingRecords('Managed Services System', 'MS_System_Trigger');
        createTriggerActivationCustomSettingRecords('Account', 'Account_Trigger');
        createTriggerActivationCustomSettingRecords('Contact', 'Contact_Trigger');
        createTriggerActivationCustomSettingRecords('Opportunity', 'Opportunity_Trigger');
        createTriggerActivationCustomSettingRecords('OpportunityContactRole', 'OpportunityContactRoleTrigger');
        createTriggerActivationCustomSettingRecords('Job__c', 'Job_Trigger');
        createTriggerActivationCustomSettingRecords('Bureau_Candidate__c', 'Bureau_Candidate_Trigger');
        createAutomaticJobCreationCustomSettingRecords('Values', 'TA - Corporate,Talent Management,TA - Credentialing');
        
        Account accountRecord = TestDataUtility.getAccount();
        INSERT accountRecord;
        
        Contact contactRecord = TestDataUtility.getContact(accountRecord.Id);
        INSERT contactRecord;
        
        Opportunity opportunityRecord = TestDataUtility.getOpportunity(accountRecord.id, contactRecord.id);
        INSERT opportunityRecord;
        
        Id RecordTypeIdJob2 = Schema.SObjectType.Job__c.getRecordTypeInfosByDeveloperName().get('Managed_Service_Pipeline').getRecordTypeId();
        Id RecordTypeIdSystem = Schema.SObjectType.System__c.getRecordTypeInfosByDeveloperName().get('SHL_System').getRecordTypeId();

        Job__c job = new Job__c();
        job.Account__c = accountRecord.Id;
        job.Opportunity__c = opportunityRecord.Id;
        job.MS_Line_of_Business__c = 'Talent Management';
        job.Job_Type__c = 'Project - 360';
        job.Start_Date__c = System.today();
        job.End_Date__c = System.today().addDays(30);
        job.InternalContact__c = UserInfo.getUserId();
        job.External_Contact_Others__c = 'External Contact';
        job.External_Contact_Other_Email_Address__c='test@test.com';
        job.Candidate_Username_Prefix__c = 'CAND';
        job.ShortFall_Manager__c = 1;
        job.Shortfall_Peer__c = 2;
        job.Shortfall_Subordinate__c = 3;
        job.ShortFall_Customer__c = 2;
        job.Shortfall_Client__c = 2;
        job.ShortFall_Other__c = 2;
        job.PurchaseOrderNo__c='rtertr';
        job.Generic_BS_Field_One__c='Bureau Service';
        job.Generic_Field_MS_One__c='Managed Service';
        job.Generic_Field_Pipeline_One__c = 'MS Pipeline';
        job.Is_Redirect_To_Task__c=true;
        job.System_Used__c = 'MFS;SODA / MFS;SODA / S2P;SODA / PD360;SHL ONLINE;';
        job.RecordTypeId = RecordTypeIdJob2;
        job.Do_Not_Send_Survey__c = True;
        job.Preferred_Language__c = 'English';
        job.Job_Region__c = 'Non China';
        insert job;
        
        System__c sys = new System__c();
        sys.System_Name__c = 'Test sys';
        sys.System_URL__c = 'www.test.com';
        sys.Account__c = accountRecord.Id;
        sys.RecordTypeId = RecordTypeIdSystem;
        sys.System_Type__c = 'MFS';
        sys.System_Client_ID__c = '1234';
        INSERT sys;
        
       
    }
    
    public static void createTriggerActivationCustomSettingRecords(String objectName, String customSettingName){
        Trigger_Activation__c recordToInsert = TestDataUtility.getTriggerActivation(objectName, customSettingName);
        INSERT recordToInsert;
    }
    
    public static void createAutomaticJobCreationCustomSettingRecords(String name, String msLOB){
        AutomaticJobCreation__c recordToInsert = TestDataUtility.getAutomaticJobCreation(name, msLOB);
        INSERT recordToInsert;
    }
    
    @isTest
    public static void getBureauSystemDetailstest() {
        Job__c job = [SELECT Id FROM Job__c];
        Test.startTest();
        SystemManagerController.getBureauSystemDetails(job.Id, 1, 0);
        Test.stopTest();
    }
    
    @isTest
    public static void getAllSystemstest() {
        Job__c job = [SELECT Id FROM Job__c LIMIT 1];
        Test.startTest();
        SystemManagerController.getAllSystems(job.Id, 1, 0);
        Test.stopTest();
    }
    
    @isTest
    public static void getPreselectedSystemtest() {
        Job__c job = [SELECT Id FROM Job__c LIMIT 1];
        System__c sys = [SELECT Id, Name FROM System__c LIMIT 1];
        List<String> sysName = new List<String>();
        sysName.add(sys.Name);
        Test.startTest();
        SystemManagerController.getPreselectedSystem(sysName,job.Id);
        Test.stopTest();
    }
    
    @isTest
    public static void createBureauSystemtest() {
        Job__c job = [SELECT Id FROM Job__c LIMIT 1];
        System__c sys = [SELECT Id,System_URL__c,System_Client_ID__c,Name,System_type__c FROM System__c LIMIT 1];
        String sys1 = '[{"name":"'+sys.Name+'","lang":"English"}]';
        String sys2 = '[{"name":"'+sys.Name+'","projectId":"12345"}]';
        List<System__c> sysName = new List<System__c>();
        sysName.add(sys);
        Test.startTest();
         SystemManagerController.createBureauSystem(sysName,sys1,sys2,job.Id);
         Bureau_System__c systemObj = new Bureau_System__c();
         systemObj.System__c = sys.Id;
         systemObj.Bureau_Job__c = job.Id;
         Insert systemObj;
         SystemManagerController.createBureauSystem(sysName,sys1,sys2,job.Id);
         Test.stopTest();
    }
}