force-app/main/objects/AutomaticJobCreation__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>MS_Line_of_Business__c</fullName>
        <label>MS - Line of Business</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>AutomaticJobCreation</label>
</CustomObject>

force-app/main/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Contract_End_Date__c</fullName>
        <description>Custom field to capture end date of contract and can be edited by user manually.</description>
        <inlineHelpText>Automatically populated on OAT review and activation – calculated using Product Subscription Start Date plus Duration (from Opportunity) / MSA expiry date.</inlineHelpText>
        <label>Contract End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity(Legacy)</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

objects/CryptoKeySetting__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>CRYPTO__c</fullName>
        <label>CRYPTO</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>CryptoKeySetting</label>
</CustomObject>

objects/Job__c.object
<CustomObject>
    <description>The entity used to identify a work request from a client to the Bureau.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Looks up existing SFDC accounts</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>R00N20000000oB15EAE</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Candidate_Username_Prefix__c</fullName>
        <description>This field is meant for specifying a 4-character text that shall be used as a prefix of the usernames generated for the candidates of a Job.</description>
        <inlineHelpText>Specify the username prefix for all candidates of this Job.</inlineHelpText>
        <label>Candidate Username Prefix</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contract_End_Date__c</fullName>
        <formula>Opportunity__r.Contract.Contract_End_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Contract End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <description>This field represents the date on which the Project Job shall end</description>
        <inlineHelpText>This project shall end on this date</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>External_Contact_Other_Email_Address__c</fullName>
        <label>External Contact (Others) Email Address</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>External_Contact_Others__c</fullName>
        <description>This field is meant for entering the External Contact if it does not exist on the system</description>
        <inlineHelpText>If the external contact exists on Salesforce, then select the contact from External Contact field above otherwise enter the Contact name in this field as it is mandatory to enter the External Contact.</inlineHelpText>
        <label>External Contact (Others)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>InternalContact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is meant for looking a Salesforce User who is the internal contact for this project.</description>
        <inlineHelpText>Select the Salesforce User who shall be the Internal Contact for this project.</inlineHelpText>
        <label>Internal Contact</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Job_Type__c</fullName>
        <description>To be selected when a Job is added</description>
        <label>Job Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Bureau Task</fullName>
                </value>
                <value>
                    <fullName>Express Bureau</fullName>
                </value>
                <value>
                    <fullName>Offline Express</fullName>
                </value>
                <value>
                    <fullName>Offline Project</fullName>
                </value>
                <value>
                    <fullName>Offline Task</fullName>
                </value>
                <value>
                    <fullName>OLB</fullName>
                    <default>true</default>
                    <label>OLB</label>
                </value>
                <value>
                    <fullName>Online Express</fullName>
                </value>
                <value>
                    <fullName>Online Task</fullName>
                </value>
                <value>
                    <fullName>Premier Bureau</fullName>
                </value>
                <value>
                    <fullName>Project - 360</fullName>
                </value>
                <value>
                    <fullName>Project - 360 Managed Serv</fullName>
                </value>
                <value>
                    <fullName>Project - Managed Serv</fullName>
                </value>
                <value>
                    <fullName>Project - Other</fullName>
                </value>
                <value>
                    <fullName>Offline</fullName>
                </value>
                <value>
                    <fullName>Online</fullName>
                </value>
                <value>
                    <fullName>SHL Online</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MS_Line_of_Business__c</fullName>
        <description>This field stores the MS- Line of business selected by the user</description>
        <label>MS - Line of Business</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>TA - Corporate</fullName>
                </value>
                <value>
                    <fullName>TA - Credentialing</fullName>
                </value>
                <value>
                    <fullName>Talent Management</fullName>
                </value>
                <value>
                    <fullName>Talent Management (Dashboards)</fullName>
                </value>
                <value>
                    <fullName>TA - Vocational (Analytics)</fullName>
                </value>
                <value>
                    <fullName>TA - Vocational (Batch)</fullName>
                </value>
                <value>
                    <fullName>TA - Vocational (School)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Jobs</relationshipLabel>
        <relationshipName>Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Lead</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR (2 AND (3 OR 4)) OR 5</booleanFilter>
            <filterItems>
                <field>User.Is_Bureau_Service_Manager__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>User.Is_Managed_Service_Manager__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Managed Service Commenced</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Managed Service Pipeline</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>OLBRecordType, General Job, Project Job</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Jobs_ProjectLead</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ShortFall_Manager__c</fullName>
        <description>This field represents the Shortfall Parameter for the rater type &apos;Manager/Supervisor&apos;</description>
        <inlineHelpText>Specify the Shortfall parameter for the rater type &apos;Manager/Supervisor&apos;</inlineHelpText>
        <label>Manager/Supervisor</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Shortfall_Peer__c</fullName>
        <description>This field represents the Shortfall Parameter for the rater type &apos;Peer/Colleague&apos;</description>
        <inlineHelpText>Specify the Shortfall parameter for the rater type &apos;Peer/Colleague&apos;</inlineHelpText>
        <label>Peer/Colleague</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>This field represents the date on which the Project Job is started</description>
        <inlineHelpText>This project started on this date</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Job</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Job Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Business_Type__c</fullName>
        <description>Choose the Opportunity Type that best describes the type of business pursued.  
Reboost should only be used with In-Advance clients. 
Cross-sell is simply New Business with a client that has a current commercial relationship.</description>
        <label>Opportunity Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Expansion</fullName>
                </value>
                <value>
                    <fullName>Renewal</fullName>
                </value>
                <value>
                    <fullName>Debooking</fullName>
                    <label>Debooking / Adjustment</label>
                </value>
                <value>
                    <fullName>Extension</fullName>
                </value>
                <value>
                    <fullName>In Arrears</fullName>
                </value>
                <value>
                    <fullName>In Advance</fullName>
                </value>
                <value>
                    <fullName>Managed Services</fullName>
                </value>
                <value>
                    <fullName>Professional Services: non-subscription</fullName>
                </value>
                <value>
                    <fullName>Top Up / Addition</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

force-app/main/objects/Trigger_Activation__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This List is used to activate/deactivate trigger while deployment.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Trigger Activation</label>
</CustomObject>

force-app/main/objects/User.object
<CustomObject>
    <fields>
        <fullName>Is_Bureau_Service_Manager__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is used to identify the Bureau Service Job Manager</description>
        <label>Is Managed Services Standard Manager</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

objects/Work_Request__c.object
<CustomObject>
    <description>Module to store work request generated by managed services team and submitted by client back to managed services team</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>System Use: To link account with work request which are generated by managed services team</description>
        <inlineHelpText>System Use: To link account with work request which are generated by managed services team</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Work Requests Generated</relationshipLabel>
        <relationshipName>Work_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Job__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>System Use: To link job from where the work requests will be processed</description>
        <inlineHelpText>System Use: To link job from where the work requests will be processed</inlineHelpText>
        <label>Job</label>
        <referenceTo>Job__c</referenceTo>
        <relationshipLabel>Work Requests Submitted</relationshipLabel>
        <relationshipName>Work_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Work Request</label>
    <nameField>
        <displayFormat>WR-{0000}</displayFormat>
        <label>Work Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Requests</pluralLabel>
    <recordTypes>
        <fullName>Generated</fullName>
        <active>true</active>
        <description>To mark records as Generated which are MS generated work request URL</description>
        <label>Generated</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/JobPasswordControllerTest.cls
@isTest
public class JobPasswordControllerTest {
    @testSetup
    static void setupTestData() {
        
         
        Trigger_Activation__c triggerSetting = new Trigger_Activation__c();
        triggerSetting.Name = 'Account_Trigger';
        triggerSetting.Active__c = true; // or false based on what you want to test
        insert triggerSetting;
        
        Trigger_Activation__c contacttriggerSetting = new Trigger_Activation__c();
        contacttriggerSetting.Name = 'Contact_Trigger';
        contacttriggerSetting.Active__c = true; // or false based on what you want to test
        insert contacttriggerSetting;
        
        Trigger_Activation__c opptriggerSetting = new Trigger_Activation__c();
        opptriggerSetting.Name = 'Opportunity_Trigger';
        opptriggerSetting.Active__c = true; // or false based on what you want to test
        insert opptriggerSetting;
        
        Trigger_Activation__c oppcontriggerSetting = new Trigger_Activation__c();
        oppcontriggerSetting.Name = 'OpportunityContactRoleTrigger';
        oppcontriggerSetting.Active__c = true; // or false based on what you want to test
        insert oppcontriggerSetting;
        
        Trigger_Activation__c jobtriggerSetting = new Trigger_Activation__c();
        jobtriggerSetting.Name = 'Job_Trigger';
        jobtriggerSetting.Active__c = true; // or false based on what you want to test
        insert jobtriggerSetting;
        
        Trigger_Activation__c tasktriggerSetting = new Trigger_Activation__c();
        tasktriggerSetting.Name = 'Task_Trigger';
        tasktriggerSetting.Active__c = true; // or false based on what you want to test
        insert tasktriggerSetting;
        
         Trigger_Activation__c ContentDocumentLink_TriggerSetting = new Trigger_Activation__c();
        ContentDocumentLink_TriggerSetting.Name = 'ContentDocumentLink_Trigger';
        ContentDocumentLink_TriggerSetting.Active__c = true; // or false based on what you want to test
        insert ContentDocumentLink_TriggerSetting;
        
        Trigger_Activation__c ContentDocument_TriggerSetting = new Trigger_Activation__c();
        ContentDocument_TriggerSetting.Name = 'ContentDocument_Trigger';
        ContentDocument_TriggerSetting.Active__c = true; // or false based on what you want to test
        insert ContentDocument_TriggerSetting;
        
        // Create a test CryptoKeySetting__c record
        CryptoKeySetting__c cryptoSetting = new CryptoKeySetting__c(
            Name = 'TestCryptoKey', CRYPTO__c = EncodingUtil.base64Encode(Crypto.generateAesKey(256))
        );
        insert cryptoSetting;
        
        AutomaticJobCreation__c autoJobCreation = new AutomaticJobCreation__c();
        autoJobCreation.Name = 'Values';
        autoJobCreation.MS_Line_of_Business__c = 'TA - Corporate,Talent Management,TA - Credentialing';
        Insert autoJobCreation;
        
       
        
        // Create a test Job__c record
         
        Account accountRecord = TestDataUtility.getAccount();
        INSERT accountRecord;
        
        Contact contactRecord = TestDataUtility.getContact(accountRecord.Id);
        INSERT contactRecord;
        
        Opportunity opportunityRecord = TestDataUtility.getOpportunity(accountRecord.id, contactRecord.id, UserInfo.getUserId());
        opportunityRecord.Business_Type__c = 'New customer: subscription';
        INSERT opportunityRecord;
        
        Contract contract = TestDataUtility.getContract(accountRecord.Id,opportunityRecord.Id);
        contract.Contract_End_Date__c = Date.Today();
        Insert contract;
        
        opportunityRecord.ContractId = contract.Id;
        update opportunityRecord;

        Id RecordTypeIdJob1 = Schema.SObjectType.Job__c.getRecordTypeInfosByName().get('Managed Service Commenced').getRecordTypeId();
        Id RecordTypeIdJob2 = Schema.SObjectType.Job__c.getRecordTypeInfosByName().get('Managed Service Pipeline').getRecordTypeId();
        Id userId = [select id from User where Is_Bureau_Service_Manager__c = true and IsActive = true limit 1].id;
        Job__c job = new Job__c();
        //Task t = new Task(Subject='Abc',Status='Not Started',Priority='Normal',WhatId = job1.id);
       // insert t;
        job.Job_Type__c = 'Project - 360';
        job.Start_Date__c = System.today();
        job.End_Date__c = System.today().addDays(30);
        job.Project_Lead__c = userId;    
        job.Opportunity__c = opportunityRecord.Id;
        job.Account__c = accountRecord.Id;
        job.InternalContact__c = UserInfo.getUserId();      
        job.External_Contact_Others__c = 'External Contact';
        job.External_Contact_Other_Email_Address__c='test@test.com';
        job.Candidate_Username_Prefix__c = '';
        job.ShortFall_Manager__c = 1;
        job.Shortfall_Peer__c = 2;
        job.Shortfall_Subordinate__c = 3;
        job.ShortFall_Customer__c = 2;
        job.Shortfall_Client__c = 2;
        job.ShortFall_Other__c = 2;
        job.PurchaseOrderNo__c='rtertr';
        job.Generic_BS_Field_One__c='Bureau Service';
        job.Generic_Field_MS_One__c='Managed Service';
        job.Generic_Field_Pipeline_One__c = 'MS Pipeline';
        job.Is_Redirect_To_Task__c=true;
        job.System_Used__c = 'MFS;SODA / MFS;SODA / S2P;SODA / PD360;SHL ONLINE;';
        job.System_Used__c ='SHL ONLINE';
        job.RecordTypeId = RecordTypeIdJob1;  
        job.MS_Line_of_Business__c='Talent Management';
        job.Job_Region__c='Non China';
        job.Sender_Email__c = 'noreply@shl.com';
        job.Client_Report_Password__c = 'rApJxWl3kouqSxzsODi+c3Z7fcqt8uQTi0wI3VacIOQ=';
        job.Client_Report_Mail_Ids__c = 'abc@abc.com';
        job.Contact_Details__c = '[{"name":"Supriya Kakaraddi","email":"supriya.kakaraddi@shl.com","role":"Project Sponsor"}]';
        job.Solution_Cap__c = 10;
        
       // job.System_Field__c = job1.id;  
        //job.Managed_Services_Pipeline__c = job1.id;
        insert job;
        
    }

    @isTest
    static void testInitiatePasswordGeneration() {
        // Fetch test job record
        Job__c job = [SELECT Id FROM Job__c LIMIT 1];
        List<String> updatedEmails = new List<String>{'user2@example.com', 'user3@example.com'};

        Test.startTest();
        JobPasswordController.initiatePasswordGeneration(job.Id, updatedEmails);
        Test.stopTest();

        // Verify that the password is generated and emails updated
        job = [SELECT Client_Report_Password__c, Client_Report_Mail_Ids__c FROM Job__c WHERE Id = :job.Id];
        //System.assertNotEquals(null, job.Client_Report_Password__c, 'Password should be set');
        //System.assertEquals('user2@example.com,user3@example.com', job.Client_Report_Mail_Ids__c, 'Emails should be updated');
    }

    @isTest
    static void testGetEmailList() {
        Job__c job = [SELECT Id FROM Job__c LIMIT 1];
        List<String> emailList = JobPasswordController.getEmailList(job.Id);
        //System.assertEquals(1, emailList.size(), 'Email list should return one email');
        //System.assertEquals('user1@example.com', emailList[0], 'Email should match');
    }

    @isTest
    static void testSendExistingPasswordEmail() {
        Job__c job = [SELECT Id FROM Job__c LIMIT 1];
        List<String> updatedEmails = new List<String>{'newuser@example.com'};
        
        Test.startTest();
        try {
            JobPasswordController.sendExistingPasswordEmail(job.Id, updatedEmails);
        } catch (Exception e) {
            //System.assert(e.getMessage().contains('No password found for this Job record.'), 'Exception should be thrown if password is missing');
        }
        Test.stopTest();
    }

    @isTest
    static void testAuthenticateUser() {
        Job__c job = [SELECT Id FROM Job__c LIMIT 1];
        String encryptedPassword = JobPasswordController.generateSecurePassword();
        job.Client_Report_Password__c = JobPasswordController.encryptPassword(encryptedPassword);
        update job;
        
        Boolean isAuthenticated = JobPasswordController.authenticateUser('user1@example.com', encryptedPassword, job.Id);
        //System.assertEquals(true, isAuthenticated, 'User should be authenticated');
    }
    @isTest
    static void testgetDashboardData() {
        Job__c job = [SELECT Id FROM Job__c LIMIT 1];
        Account accountRecord = [select id from account limit 1];
        Work_Request__c generatedRequest = TestDataUtility.getGeneratedWRF(accountRecord.Id, job.Id);
        
        /*ContentVersion cv3 = new ContentVersion();
        String encoded2 = EncodingUtil.urlEncode('Base 64 String', 'UTF-8');
        String decoded2=  EncodingUtil.urlDecode(encoded2,'UTF-8');
        cv3.VersionData = Blob.valueOf('\uFEFF'+decoded2);
        cv3.Title = '_CandidateWRFImportSheet';
        cv3.PathOnClient = 'TestDocument.csv';
        System.debug('Content Version cv '+cv3);
        insert cv3;*/
        
        
        
        Work_Request__c submittedRequest = TestDataUtility.getSubmittedWRF(generatedRequest.Id,null);
       /*  ContentDocumentLink cdl3 = new ContentDocumentLink();
        cdl3.ContentDocumentId = [SELECT ContentDocumentId FROM ContentVersion WHERE Id =: cv3.id].ContentDocumentId;
        cdl3.LinkedEntityId = submittedRequest.Id;
        cdl3.ShareType = 'V';
        insert cdl3;*/
        
        Map<String, Object> dashboardata = ProjectDashboardController.getDashboardData(job.Id);
        
    }
}