force-app/main/objects/AutomaticJobCreation__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>MS_Line_of_Business__c</fullName>
        <label>MS - Line of Business</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>AutomaticJobCreation</label>
</CustomObject>

objects/Job__c.object
<CustomObject>
    <description>The entity used to identify a work request from a client to the Bureau.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Looks up existing SFDC accounts</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>R00N20000000oB15EAE</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Candidate_Username_Prefix__c</fullName>
        <description>This field is meant for specifying a 4-character text that shall be used as a prefix of the usernames generated for the candidates of a Job.</description>
        <inlineHelpText>Specify the username prefix for all candidates of this Job.</inlineHelpText>
        <label>Candidate Username Prefix</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <description>This field represents the date on which the Project Job shall end</description>
        <inlineHelpText>This project shall end on this date</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>External_Contact_Other_Email_Address__c</fullName>
        <label>External Contact (Others) Email Address</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>External_Contact_Others__c</fullName>
        <description>This field is meant for entering the External Contact if it does not exist on the system</description>
        <inlineHelpText>If the external contact exists on Salesforce, then select the contact from External Contact field above otherwise enter the Contact name in this field as it is mandatory to enter the External Contact.</inlineHelpText>
        <label>External Contact (Others)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Generic_BS_Field_One__c</fullName>
        <label>Generic Bureau Field One</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Generic_Field_MS_One__c</fullName>
        <label>Generic Field MS One</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Generic_Field_Pipeline_One__c</fullName>
        <label>Generic Field Pipeline One</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>InternalContact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is meant for looking a Salesforce User who is the internal contact for this project.</description>
        <inlineHelpText>Select the Salesforce User who shall be the Internal Contact for this project.</inlineHelpText>
        <label>Internal Contact</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Is_Redirect_To_Task__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is used to redirect user to Task tab when user create a new Job for the first time.</description>
        <label>Is Redirect To Task</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Job_Type__c</fullName>
        <description>To be selected when a Job is added</description>
        <label>Job Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Bureau Task</fullName>
                </value>
                <value>
                    <fullName>Express Bureau</fullName>
                </value>
                <value>
                    <fullName>Offline Express</fullName>
                </value>
                <value>
                    <fullName>Offline Project</fullName>
                </value>
                <value>
                    <fullName>Offline Task</fullName>
                </value>
                <value>
                    <fullName>OLB</fullName>
                    <default>true</default>
                    <label>OLB</label>
                </value>
                <value>
                    <fullName>Online Express</fullName>
                </value>
                <value>
                    <fullName>Online Task</fullName>
                </value>
                <value>
                    <fullName>Premier Bureau</fullName>
                </value>
                <value>
                    <fullName>Project - 360</fullName>
                </value>
                <value>
                    <fullName>Project - 360 Managed Serv</fullName>
                </value>
                <value>
                    <fullName>Project - Managed Serv</fullName>
                </value>
                <value>
                    <fullName>Project - Other</fullName>
                </value>
                <value>
                    <fullName>Offline</fullName>
                </value>
                <value>
                    <fullName>Online</fullName>
                </value>
                <value>
                    <fullName>SHL Online</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MS_Line_of_Business__c</fullName>
        <description>This field stores the MS- Line of business selected by the user</description>
        <label>MS - Line of Business</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>TA - Corporate</fullName>
                </value>
                <value>
                    <fullName>TA - Credentialing</fullName>
                </value>
                <value>
                    <fullName>Talent Management</fullName>
                </value>
                <value>
                    <fullName>Talent Management (Dashboards)</fullName>
                </value>
                <value>
                    <fullName>TA - Vocational (Analytics)</fullName>
                </value>
                <value>
                    <fullName>TA - Vocational (Batch)</fullName>
                </value>
                <value>
                    <fullName>TA - Vocational (School)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Jobs</relationshipLabel>
        <relationshipName>Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PurchaseOrderNo__c</fullName>
        <label>Purchase Order Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ShortFall_Customer__c</fullName>
        <description>This field represents the Shortfall Parameter for the rater type &apos;Internal/External Customer&apos;</description>
        <inlineHelpText>This field represents the Shortfall Parameter for the rater type &apos;Internal/External Customer&apos;</inlineHelpText>
        <label>Internal/External Customer</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ShortFall_Manager__c</fullName>
        <description>This field represents the Shortfall Parameter for the rater type &apos;Manager/Supervisor&apos;</description>
        <inlineHelpText>Specify the Shortfall parameter for the rater type &apos;Manager/Supervisor&apos;</inlineHelpText>
        <label>Manager/Supervisor</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ShortFall_Other__c</fullName>
        <description>This field represents the Shortfall Parameter for the rater type &apos;Stakeholder/Other/Others&apos;</description>
        <inlineHelpText>Specify the Shortfall parameter for the rater type &apos;Stakeholder/Other/Others&apos;</inlineHelpText>
        <label>Stakeholder/Other</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Shortfall_Client__c</fullName>
        <description>This field represents the Shortfall Parameter for the rater type &apos;Internal/External Client&apos;</description>
        <inlineHelpText>Specify the Shortfall parameter for the rater type &apos;Internal/External Client&apos;</inlineHelpText>
        <label>Internal/External Client</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Shortfall_Peer__c</fullName>
        <description>This field represents the Shortfall Parameter for the rater type &apos;Peer/Colleague&apos;</description>
        <inlineHelpText>Specify the Shortfall parameter for the rater type &apos;Peer/Colleague&apos;</inlineHelpText>
        <label>Peer/Colleague</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Shortfall_Subordinate__c</fullName>
        <description>This field represents the Shortfall Parameter for the rater type &apos;DirectReport/Report/Subordinate&apos;</description>
        <inlineHelpText>Specify the Shortfall parameter for the rater type &apos;Direct Report/Report/Subordinate&apos;</inlineHelpText>
        <label>Direct Report/Report/Subordinate</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>This field represents the date on which the Project Job is started</description>
        <inlineHelpText>This project started on this date</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>System_Used__c</fullName>
        <description>For bureau job record</description>
        <label>System Used</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>TalentCentral+</fullName>
                </value>
                <value>
                    <fullName>MFS</fullName>
                </value>
                <value>
                    <fullName>Insights</fullName>
                </value>
                <value>
                    <fullName>VADC</fullName>
                </value>
                <value>
                    <fullName>Dashboard</fullName>
                </value>
                <value>
                    <fullName>SHL ONLINE</fullName>
                </value>
                <value>
                    <fullName>NSDC-MIS</fullName>
                </value>
                <value>
                    <fullName>TalentCentral</fullName>
                </value>
                <value>
                    <fullName>iAssess</fullName>
                </value>
                <value>
                    <fullName>OFFLINE</fullName>
                </value>
                <value>
                    <fullName>DSPS</fullName>
                </value>
                <value>
                    <fullName>Client System</fullName>
                </value>
                <value>
                    <fullName>WPS</fullName>
                </value>
                <value>
                    <fullName>Manufacturing Toolbox - MTB</fullName>
                </value>
                <value>
                    <fullName>Scansys</fullName>
                </value>
                <value>
                    <fullName>DM Desktop Profiler</fullName>
                </value>
                <value>
                    <fullName>Online Competency Profiler</fullName>
                </value>
                <value>
                    <fullName>JCF Creator</fullName>
                </value>
                <value>
                    <fullName>Career Guidance</fullName>
                </value>
                <value>
                    <fullName>OnDemand</fullName>
                </value>
                <value>
                    <fullName>S2P System</fullName>
                </value>
                <value>
                    <fullName>Tableau Dashboard</fullName>
                </value>
                <value>
                    <fullName>Automation</fullName>
                </value>
                <value>
                    <fullName>IGB</fullName>
                </value>
                <value>
                    <fullName>OA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Job</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Job Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <recordTypes>
        <fullName>Managed_Service_Pipeline</fullName>
        <active>true</active>
        <label>Managed Service Pipeline</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/MS_Task__c.object
<CustomObject>
    <description>Object to accommodate Task information related to Managed Services</description>
    <fields>
        <fullName>Job__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Job</label>
        <referenceTo>Job__c</referenceTo>
        <relationshipLabel>MS Tasks</relationshipLabel>
        <relationshipName>MS_Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>MS Task</label>
    <nameField>
        <displayFormat>TSK-{00000}</displayFormat>
        <label>MS Task Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MS Tasks</pluralLabel>
    <recordTypes>
        <fullName>Talent_Management</fullName>
        <active>true</active>
        <label>Talent Management</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/TaskManagerController_Test.cls
@isTest
public class TaskManagerController_Test {
    
    @TestSetup
    static void makeData(){

        String valueFV = 'XTRAE-EMP,XTRAE-ASSOC,XTREL,DEB,FREIGHT';
        createFieldValueCustomSettingRecords(valueFV, 'Credit Note IM Codes');

        createTriggerActivationCustomSettingRecords('Account', 'Account_Trigger');
        createTriggerActivationCustomSettingRecords('Contact', 'Contact_Trigger');
        createTriggerActivationCustomSettingRecords('Opportunity', 'Opportunity_Trigger');
        createTriggerActivationCustomSettingRecords('OpportunityContactRole', 'OpportunityContactRoleTrigger');
        createTriggerActivationCustomSettingRecords('Job__c', 'Job_Trigger');
        createTriggerActivationCustomSettingRecords('User', 'User_Trigger');
        createTriggerActivationCustomSettingRecords('MS_Task__c', 'MS_Task_Trigger');

        AutomaticJobCreation__c autoJobCreation = new AutomaticJobCreation__c();
        autoJobCreation.Name = 'Values';
        autoJobCreation.MS_Line_of_Business__c = 'TA - Corporate,Talent Management,TA - Credentialing';
        Insert autoJobCreation;
        

        Account accountRecord = TestDataUtility.getAccount();
        INSERT accountRecord;
        
        Contact contactRecord = TestDataUtility.getContact(accountRecord.Id);
        INSERT contactRecord;
        
        Opportunity opportunityRecord = TestDataUtility.getOpportunity(accountRecord.id, contactRecord.id, UserInfo.getUserId());
        INSERT opportunityRecord;

        Id RecordTypeIdJob1 = Schema.SObjectType.Job__c.getRecordTypeInfosByDeveloperName().get('Managed_Service_Pipeline').getRecordTypeId();
        
        Job__c job = new Job__c();
        job.Opportunity__c = opportunityRecord.Id;
        job.Account__c = accountRecord.Id;
        job.MS_Line_of_Business__c = 'Talent Management';
        job.Job_Type__c = 'Project - 360';
        job.Start_Date__c = System.today();
        job.End_Date__c = System.today().addDays(30);
        job.InternalContact__c = UserInfo.getUserId();
        job.External_Contact_Others__c = 'External Contact';
        job.External_Contact_Other_Email_Address__c='test@test.com';
        job.Candidate_Username_Prefix__c = 'Test';
        job.ShortFall_Manager__c = 1;
        job.Shortfall_Peer__c = 2;
        job.Shortfall_Subordinate__c = 3;
        job.ShortFall_Customer__c = 2;
        job.Shortfall_Client__c = 2;
        job.ShortFall_Other__c = 2;
        job.PurchaseOrderNo__c='rtertr';
        job.Generic_BS_Field_One__c='Bureau Service';
        job.Generic_Field_MS_One__c='Managed Service';
        job.Generic_Field_Pipeline_One__c = 'MS Pipeline';
        job.Is_Redirect_To_Task__c=true;
        job.System_Used__c = 'MFS;SODA / MFS;SODA / S2P;SODA / PD360;SHL ONLINE;';
        job.System_Used__c ='SHL ONLINE';
        job.RecordTypeId = RecordTypeIdJob1;
        job.Job_Region__c='China';
        insert job;

        Id RecordTypeIdTask = Schema.SObjectType.MS_Task__c.getRecordTypeInfosByDeveloperName().get('Talent_Management').getRecordTypeId();

        MS_Task__c msTask = new MS_Task__c();
        msTask.RecordTypeId = RecordTypeIdTask;
        msTask.Task_Category__c = 'Pre Launch';
        msTask.Task_Type__c = 'Other';
        msTask.Task_Date__c = System.today();
        msTask.Scheduled_Time__c = Time.newInstance(10, 0, 0, 0);
        msTask.Estimated_Time_Required__c = 10;
        msTask.UnScheduled__c = false; 
        msTask.Task_Status__c = 'Not Started';
        insert msTask;

        TestDataUtility.insertQueue();

    }

    public static void createTriggerActivationCustomSettingRecords(String objectName, String customSettingName){
        Trigger_Activation__c recordToInsert = TestDataUtility.getTriggerActivation(objectName, customSettingName);
        INSERT recordToInsert;
    }

    public static void createFieldValueCustomSettingRecords(String values, String customSettingName){
        Field_Value_Setting__c fVS = TestDataUtility.getFieldValueSetting(values, customSettingName);
        INSERT fVS;
    }

    @isTest
    static void testGetTaskList() {
        Job__c job = [SELECT Id FROM Job__c LIMIT 1];
        TaskManagerController.getTaskList(UserInfo.getUserId(), 'Not Started', job.Id);
        TaskManagerController.getTaskList('Prabhat', null, job.Id);
        TaskManagerController.getTaskList(null, null, job.Id);
    }

    @isTest
    static void testAssignTaskToCurrentUser() {
        Group queueRecord = [SELECT Id FROM Group WHERE Type = 'Queue' AND Name = 'group name' LIMIT 1];
        MS_Task__c msTask = [SELECT Id FROM MS_Task__c LIMIT 1];
        msTask.OwnerId = queueRecord.Id;
        update msTask;
        TaskManagerController.assignTaskToCurrentUser(msTask.Id);
    }

    @isTest
    static void testAssignTaskToCurrentUserException() {
        MS_Task__c msTask = [SELECT Id FROM MS_Task__c LIMIT 1];
        msTask.OwnerId = UserInfo.getUserId();
        update msTask;
        try{
            TaskManagerController.assignTaskToCurrentUser(msTask.Id);
        } catch (Exception ex) {
            System.assert(ex.getMessage().contains('Script-thrown exception'), 'Unexpected Error');
        }
    }

    @isTest
    static void testCompleteTask() {
        // '2022-11-09T06:26:55.000Z'
        MS_Task__c msTask = [SELECT Id FROM MS_Task__c LIMIT 1];
        TaskManagerController.completeTask(msTask.Id, '2022-11-09T06:26:55.000Z', '2022-11-09T06:28:00.000Z', '2022-11-09T06:28:00.000Z');
        try {
            TaskManagerController.completeTask(msTask.Id, null, null, null);
        } catch(Exception ex) {
            System.assert(ex.getMessage().containsIgnoreCase('Script-thrown exception'), 'Unexpected Error');
        }
    }

    @isTest
    static void testCancelTask() {
        MS_Task__c msTask = [SELECT Id FROM MS_Task__c LIMIT 1];
        TaskManagerController.cancelTask(msTask.Id);
    }

    @isTest
    static void testStartTaskTimer() {
        MS_Task__c msTask = [SELECT Id FROM MS_Task__c LIMIT 1];
        TaskManagerController.startTaskTimer(msTask.Id, '2022-11-09T06:26:55.000Z');
        try {
            TaskManagerController.startTaskTimer(msTask.Id, null);
        } catch(Exception ex) {
            System.assert(ex.getMessage().containsIgnoreCase('Script-thrown exception'), 'Unexpected Error');
        }
    }

    @isTest
    static void testStopTaskTimer() {
        MS_Task__c msTask = [SELECT Id FROM MS_Task__c LIMIT 1];
        TaskManagerController.stopTaskTimer(msTask.Id, '2022-11-09T06:26:55.000Z');
        try {
            TaskManagerController.stopTaskTimer(msTask.Id, null);
        } catch(Exception ex) {
            System.assert(ex.getMessage().containsIgnoreCase('Script-thrown exception'), 'Unexpected Error');
        }
    }

    @isTest
    static void testResumeTaskTimer() {
        MS_Task__c msTask = [SELECT Id FROM MS_Task__c LIMIT 1];
        TaskManagerController.resumeTaskTimer(msTask.Id, '2022-11-09T06:26:55.000Z', '1000');
        try {
            TaskManagerController.resumeTaskTimer(msTask.Id, null, '1000');
        } catch(Exception ex) {
            System.assert(ex.getMessage().containsIgnoreCase('Script-thrown exception'), 'Unexpected Error');
        }
    }

    @isTest
    static void testUpdateTaskPriority() {
        MS_Task__c msTask = [SELECT Id FROM MS_Task__c LIMIT 1];
        TaskManagerController.updateTaskPriority(new List<MS_Task__c> {msTask});
    }

    @isTest
    static void testUpdateTaskRowData() {
        MS_Task__c msTask = [SELECT Id FROM MS_Task__c LIMIT 1];
        msTask.Comments__c = 'Test';
        TaskManagerController.updateTaskRowData(new List<MS_Task__c> {msTask});
    }

    @isTest
    static void testCloneTasks() {
        Job__c job = [SELECT Id FROM Job__c LIMIT 1];
        MS_Task__c msTask = [SELECT Id, Task_Category__c, Task_Type__c, Task_Status__c, RecordTypeId FROM MS_Task__c LIMIT 1];
        msTask.Id = null;
        TaskManagerController.cloneTasks(JSON.serialize(new List<MS_Task__c>{msTask}), job.Id);
    }

    @isTest
    static void testCloneTasksException() {
        Job__c job = [SELECT Id FROM Job__c LIMIT 1];
        MS_Task__c msTask = [SELECT Id, Task_Category__c, Task_Type__c, Task_Status__c FROM MS_Task__c LIMIT 1];
        msTask.Id = null;
        try {
            TaskManagerController.cloneTasks(JSON.serialize(new List<MS_Task__c>{msTask}), job.Id);
        } catch(Exception ex) {
            System.assert(ex.getMessage().containsIgnoreCase('Insert Failed'), 'Unexpected Error');
        }
    }
}