force-app/main/objects/AutomaticJobCreation__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>MS_Line_of_Business__c</fullName>
        <label>MS - Line of Business</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>AutomaticJobCreation</label>
</CustomObject>

objects/Bureau_Candidate__c.object
<CustomObject>
    <description>Managed Services module</description>
    <fields>
        <fullName>Work_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Work Request</label>
        <referenceTo>Work_Request__c</referenceTo>
        <relationshipLabel>Managed Services Candidates</relationshipLabel>
        <relationshipName>Managed_Services_Candidates</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Managed Services Candidate</label>
    <nameField>
        <displayFormat>BC{000000000}</displayFormat>
        <label>Candidate Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Managed Services Candidates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/objects/Course_Booking__c.object
<CustomObject>
    <description>Public and Incompany course bookings to replace Big Sky Courses &amp; Bookings module</description>
    <label>Course Booking</label>
    <nameField>
        <displayFormat>CB{000000}</displayFormat>
        <label>Booking Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Bookings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/objects/Courses__c.object
<CustomObject>
    <description>Area to keep list of all course types, codes, costs and venues</description>
    <label>Courses</label>
    <nameField>
        <displayFormat>C{000000}</displayFormat>
        <label>Course Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <recordTypes>
        <fullName>Public</fullName>
        <active>true</active>
        <label>Public</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Field_Value_Setting__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Field value setting to avoid the hard coding of values in Apex triggers or Classes.</description>
    <label>Field Value Setting</label>
</CustomObject>

force-app/main/objects/India_GST__c.object
<CustomObject>
    <label>Address &amp; Tax Information</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Address &amp; Tax Information</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Job__c.object
<CustomObject>
    <description>The entity used to identify a work request from a client to the Bureau.</description>
    <fields>
        <fullName>MS_Line_of_Business__c</fullName>
        <description>This field stores the MS- Line of business selected by the user</description>
        <label>MS - Line of Business</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>TA - Corporate</fullName>
                </value>
                <value>
                    <fullName>TA - Credentialing</fullName>
                </value>
                <value>
                    <fullName>Talent Management</fullName>
                </value>
                <value>
                    <fullName>Talent Management (Dashboards)</fullName>
                </value>
                <value>
                    <fullName>TA - Vocational (Analytics)</fullName>
                </value>
                <value>
                    <fullName>TA - Vocational (Batch)</fullName>
                </value>
                <value>
                    <fullName>TA - Vocational (School)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Job</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Job Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/objects/Order.object
<CustomObject>
    <fields>
        <fullName>Course_Booking__c</fullName>
        <formula>IF(CONTAINS(Opportunity.Opportunity_Nickname__c,&apos;Opportunity for Course Booking&apos;),
			RIGHT(Opportunity.Opportunity_Nickname__c, 9), &apos;&apos; )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Course Booking</label>
        <type>Text</type>
    </fields>
</CustomObject>

force-app/main/objects/Trigger_Activation__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This List is used to activate/deactivate trigger while deployment.</description>
    <label>Trigger Activation</label>
</CustomObject>

objects/Work_Request__c.object
<CustomObject>
    <description>Module to store work request generated by managed services team and submitted by client back to managed services team</description>
    <fields>
        <fullName>Job__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>System Use: To link job from where the work requests will be processed</description>
        <inlineHelpText>System Use: To link job from where the work requests will be processed</inlineHelpText>
        <label>Job</label>
        <referenceTo>Job__c</referenceTo>
        <relationshipLabel>Work Requests Submitted</relationshipLabel>
        <relationshipName>Work_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Work Request</label>
    <nameField>
        <displayFormat>WR-{0000}</displayFormat>
        <label>Work Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TestDataUtility_Test.cls
@isTest
public class TestDataUtility_Test {
    
    @TestSetup
    static void makeData(){
        
        
        String valueFV = 'XTRAE-EMP,XTRAE-ASSOC,XTREL,DEB,FREIGHT';
       
        createTriggerActivationCustomSettingRecords('Account', 'Account_Trigger');
        createTriggerActivationCustomSettingRecords('Contact', 'Contact_Trigger');
        createTriggerActivationCustomSettingRecords('Opportunity', 'Opportunity_Trigger');
        createTriggerActivationCustomSettingRecords('OpportunityContactRole', 'OpportunityContactRoleTrigger');
        createTriggerActivationCustomSettingRecords('Job__c', 'Job_Trigger');
        createTriggerActivationCustomSettingRecords('Contract', 'Contract_Trigger');
        createTriggerActivationCustomSettingRecords('Order', 'Order_Trigger');
        createTriggerActivationCustomSettingRecords('Courses__c', 'Course_Trigger');
        createTriggerActivationCustomSettingRecords('User', 'User_Trigger');
        createFieldValueCustomSettingRecords(valueFV, 'Credit Note IM Codes');
        TestDataUtility.insertProjectManagerUser('Talent Management'); 
        AutomaticJobCreation__c autoJobCreation = new AutomaticJobCreation__c();
        autoJobCreation.Name = 'Values';
        autoJobCreation.MS_Line_of_Business__c = 'TA - Corporate,Talent Management,TA - Credentialing';
        Insert autoJobCreation;
        

        Account accountRecord = TestDataUtility.getAccount();
        INSERT accountRecord;
        
        Contact contactRecord = TestDataUtility.getContact(accountRecord.Id);
        INSERT contactRecord;
        
        Opportunity opportunityRecord = TestDataUtility.getOpportunity(accountRecord.id, contactRecord.id, UserInfo.getUserId());
        INSERT opportunityRecord;

        Opportunity opportunityRecord2 = TestDataUtility.getOpportunity(accountRecord.Id, contactRecord.Id);

        Contract contractRecord = TestDataUtility.getContract(accountRecord.Id, opportunityRecord.Id);
        Insert contractRecord;

        Product2 productRecord = TestDataUtility.getProduct2();
        Insert productRecord;

        List<Product2> productList = TestDataUtility.getProduct2List(2);

        PricebookEntry pbeRecord = TestDataUtility.getPricebookEntry(productRecord.Id, 'INR', Test.getStandardPricebookId());
        Insert pbeRecord;

        Order orderRecord = TestDataUtility.getOrder(contractRecord.Id, accountRecord.Id);
        Insert orderRecord;

        AutomaticJobCreation__c autoJobCreationRecord = TestDataUtility.getAutomaticJobCreation('Values', 'TA - Corporate,Talent Management,TA - Credentialing');

        OrderItem orderItemRecord = TestDataUtility.getOrderItem(orderRecord.Id, pbeRecord.Id);

        Campaign campaignRecord = TestDataUtility.getCampaign();

        India_GST__c indiaGSTRecord = TestDataUtility.getIndiaGST(accountRecord.Id);

        Courses__c courseRecord = TestDataUtility.getCourse(contactRecord);
        Insert courseRecord;

        Course_Booking__c courseBookingRecord = TestDataUtility.getCourseBooking(courseRecord, opportunityRecord, contactRecord);

        Job__c jobRecord = TestDataUtility.getManualJob(opportunityRecord.Id, UserInfo.getUserId());
        
        Bureau_Candidate__c candidateRecord = TestDataUtility.getCandidate(jobRecord.Id, 'Pass', 'candidate1@test.com');
        
        Work_Request__c generatedRequest = TestDataUtility.getGeneratedWRF(accountRecord.Id, jobRecord.Id);
        
    }

    @isTest
    static void testMethod1() {
        User testUser = TestDataUtility.getUser('Standard User');

        TestDataUtility.insertQueue();

    }

    public static void createTriggerActivationCustomSettingRecords(String objectName, String customSettingName){
        Trigger_Activation__c recordToInsert = TestDataUtility.getTriggerActivation(objectName, customSettingName);
        INSERT recordToInsert;
    }

    public static void createFieldValueCustomSettingRecords(String values, String customSettingName){
        Field_Value_Setting__c fVS = TestDataUtility.getFieldValueSetting(values, customSettingName);
        INSERT fVS;
    }
}