force-app/main/objects/Bureau_Invoice__c.object
<CustomObject>
    <description>To link to the Job object for OLB jobs.</description>
    <fields>
        <fullName>InvoiceStatus__c</fullName>
        <label>Invoice Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Created</fullName>
                    <default>true</default>
                    <label>Created</label>
                </value>
                <value>
                    <fullName>Ready</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Completed – SHL Online</fullName>
                </value>
                <value>
                    <fullName>SOE Complete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>InvoiceType__c</fullName>
        <label>Invoice Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Invoice</fullName>
                </value>
                <value>
                    <fullName>Free of Charge</fullName>
                </value>
                <value>
                    <fullName>SOE Query</fullName>
                </value>
                <value>
                    <fullName>Credit</fullName>
                </value>
                <value>
                    <fullName>Reissue</fullName>
                </value>
                <value>
                    <fullName>Generic Log In</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Job__c</fullName>
        <label>Job</label>
        <referenceTo>Job__c</referenceTo>
        <relationshipName>Bureau_Invoices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Managed Services Invoice</label>
    <nameField>
        <displayFormat>BInv{00000}</displayFormat>
        <label>Managed Services Invoice</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Managed Services Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Job__c.object
<CustomObject>
    <description>The entity used to identify a work request from a client to the Bureau.</description>
    <fields>
        <fullName>CurrencyToBeBilled__c</fullName>
        <formula>TEXT(Account__r.CurrencyIsoCode)</formula>
        <label>Currency To Be Billed</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Managed_Service_Commenced__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Legacy MS Commenced</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Job__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Managed Service Commenced</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Job__c</referenceTo>
        <relationshipLabel>Jobs (Managed Service Commenced)</relationshipLabel>
        <relationshipName>Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Managed_Services_Pipeline__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field will be used on MS Commenced Project.</description>
        <label>Legacy MS Pipeline</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Job__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Managed Service Pipeline</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Job__c</referenceTo>
        <relationshipLabel>Commenced Projects</relationshipLabel>
        <relationshipName>Commenced_Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Pipeline_Status__c</fullName>
        <label>Pipeline Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pipeline Job</fullName>
                    <default>true</default>
                    <label>Pipeline Job</label>
                </value>
                <value>
                    <fullName>Pipeline - Converted</fullName>
                </value>
                <value>
                    <fullName>Pipeline - Not Converted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>System_Field__c</fullName>
        <description>This field is used to store Job Id in case of clone functionality</description>
        <inlineHelpText>This is a system field. Please do not change value.</inlineHelpText>
        <label>System Field</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Job</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Job Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <recordTypes>
        <fullName>Bureau_Service</fullName>
        <active>true</active>
        <label>Managed Services Standard</label>
    </recordTypes>
    <recordTypes>
        <fullName>Managed_Service_Commenced</fullName>
        <active>true</active>
        <label>Managed Service Commenced</label>
    </recordTypes>
    <recordTypes>
        <fullName>Managed_Service_Pipeline</fullName>
        <active>true</active>
        <label>Managed Service Pipeline</label>
    </recordTypes>
    <recordTypes>
        <fullName>Project_Job</fullName>
        <active>true</active>
        <description>This record is meant for creating the Bureau Projects</description>
        <label>Project Job</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/JobTriggerManager_3.cls
/**************************************************************************************************************************************
CREATED BY :- PANKHURI JAIN
CREATED DATE :- 29-07-2019
DESCRIPTION :- This class contains Job trigger related functionalities : after Insert (Creation of Managed Services Invoices for Job,Creating Managed Services System for System type Job records,
Upsert task fields for Not started type tasks related to Pipeline Job, Migrating MS Pipeline Open Task to MS Commenced Task)
***************************************************************************************************************************************/ 

global class JobTriggerManager_3{
   public static void Job_AfterInsert(List<Job__c> JobNewList){    
   List<Bureau_Invoice__c> bureauInvoiceList = new List<Bureau_Invoice__c>();
    List<Task> defaultTask = new List<Task>();
    Map<Id,Set<Job__c>> CloneJobMap = new Map<Id,Set<Job__c>>();
    Map<Id,RecordType> recordTypeMap = new Map<Id,RecordType>();
    for(RecordType rt:[Select Id,Name,DeveloperName from RecordType where IsActive= true AND SobjectType = 'Job__c' AND DeveloperName IN('Managed_Service_Commenced','Project_Job','Bureau_Service','Managed_Service_Pipeline')]){
        recordTypeMap.put(rt.Id,rt);
    }
    Map<Id,Id> PipelineCommencedMap = new Map<Id,Id>();
    for(Integer i=0; i< JobNewList.size();i++){
        //If Record type if either Project Job or Bureau Service
        if(recordTypeMap.containsKey(JobNewList[i].RecordTypeId)){          
            // Added new condition to create an invoice for the Managed Service Commenced Record Type SSE-106
           // if(recordTypeMap.get(JobNewList[i].RecordTypeId).DeveloperName=='Bureau_Service' || recordTypeMap.get(JobNewList[i].RecordTypeId).DeveloperName=='Project_Job' || recordTypeMap.get(JobNewList[i].RecordTypeId).DeveloperName=='Managed_Service_Commenced'){    
            if(recordTypeMap.get(JobNewList[i].RecordTypeId).DeveloperName=='Managed_Service_Commenced'){
                Bureau_Invoice__c bureauInvoice = new Bureau_Invoice__c();
                bureauInvoice.Job__c = JobNewList[i].id;
                bureauInvoice.InvoiceType__c = 'Invoice';               
                bureauInvoice.InvoiceStatus__c = 'Created';              
                bureauInvoice.CurrencyIsoCode = JobNewList[i].CurrencyToBeBilled__c;
                bureauInvoiceList.add(bureauInvoice);
               
                System.debug('the first condition is being called');
            }
            // SSE-863  The Managed Service Commenced Record Type needs to have both - Invoice and update to the original Job from which is created. Removed the else if part with the above if and created a standalone if condition.
            if(recordTypeMap.get(JobNewList[i].RecordTypeId).DeveloperName=='Managed_Service_Commenced'){
                 System.debug('map is forming');
                PipelineCommencedMap.put(JobNewList[i].Managed_Services_Pipeline__c,JobNewList[i].Id);
               
            }
            
        }
        //create system in case of cloned job for Managed Commenced Job
       // if(trigger.isInsert){
            //if(JobNewList[i].System_Field__c != null && (recordTypeMap.get(JobNewList[i].RecordTypeId).DeveloperName=='Bureau_Service' || recordTypeMap.get(JobNewList[i].RecordTypeId).DeveloperName=='Managed_Service_Commenced')){
             if(JobNewList[i].System_Field__c != null && (recordTypeMap.get(JobNewList[i].RecordTypeId).DeveloperName=='Managed_Service_Commenced')){
                if(CloneJobMap.containsKey(JobNewList[i].System_Field__c))
                    CloneJobMap.get(JobNewList[i].System_Field__c).add(JobNewList[i]);
                else{
                    Set<Job__c> newJob=new Set<Job__c>();
                    newJob.add(JobNewList[i]);
                    CloneJobMap.put(JobNewList[i].System_Field__c,newJob);
                }
            }
        }
   // }
    //Insert System in case of Clone Job
    if(CloneJobMap.size()>0) 
    ManageJobTask_Controller.createBureauSystem(CloneJobMap);
        
    if(PipelineCommencedMap.size()>0){
    System.debug('The if condition works');
        List<Job__c> updatePipelineJObList = new List<Job__c>();
        for(Job__c job :[Select id,Pipeline_Status__c,(SELECT Id,Subject,WhatId,OwnerId,ActivityDate,Status,Priority,EstimatedDurationInMinutes__c,UnScheduled__c,Description FROM Tasks where Status='Not Started' order by ActivityDate desc) from Job__c where Id IN: PipelineCommencedMap.keySet()]){
            job.Pipeline_Status__c = 'Pipeline - Converted';
            job.Managed_Service_Commenced__c = PipelineCommencedMap.get(job.Id);
            updatePipelineJObList.add(job);
            for(Task  tsk : job.Tasks){               
                tsk.whatId = PipelineCommencedMap.get(job.Id);
                defaultTask.add(tsk);
            }
        }
        //Update status of converted MS Pipeline Job
        if(updatePipelineJObList.size()>0)
            update updatePipelineJObList;
    }
    //Insert default task or migrated MS Pipeline Open Task to MS Commenced Task
    if(defaultTask.size()>0)
        upsert defaultTask;
               
    //Insert bureau invoice for Commenced Job
    if(bureauInvoiceList.size()>0)
        insert bureauInvoiceList;
        
   }
}