force-app/main/objects/Bureau_System__c.object
<CustomObject>
    <description>This object represents a relation between a Bureau Job and a System.</description>
    <fields>
        <fullName>Bureau_Job__c</fullName>
        <description>This field represents the Bureau Job to which is the parent of this record.</description>
        <label>Managed Services Job</label>
        <referenceTo>Job__c</referenceTo>
        <relationshipLabel>Managed Services Systems</relationshipLabel>
        <relationshipName>Bureau_Systems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Is_Client_System__c</fullName>
        <description>This field shows whether the selected system is a Client System or not.</description>
        <formula>IF(System__r.Is_Client_System__c,&quot;Yes&quot;, &quot;No&quot;)</formula>
        <inlineHelpText>Specify whether the selected System is a Client System.</inlineHelpText>
        <label>Is Client System</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Id__c</fullName>
        <description>This field represents the Project Id for this Job on the selected system.</description>
        <inlineHelpText>Specify Project Id for this Job on the selected system.</inlineHelpText>
        <label>Project Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Report_Language__c</fullName>
        <description>This field represents the language in which reports shall be generated for the selected system.</description>
        <inlineHelpText>Specify the language in which reports shall be generated for the selected system.</inlineHelpText>
        <label>Report Language</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>English (International)</fullName>
                </value>
                <value>
                    <fullName>English (United States)</fullName>
                </value>
                <value>
                    <fullName>Arabic</fullName>
                </value>
                <value>
                    <fullName>Chinese (Simplified)</fullName>
                </value>
                <value>
                    <fullName>Chinese (Traditional)</fullName>
                </value>
                <value>
                    <fullName>Czech</fullName>
                </value>
                <value>
                    <fullName>Danish</fullName>
                </value>
                <value>
                    <fullName>Dutch</fullName>
                </value>
                <value>
                    <fullName>Dutch (Belgian)</fullName>
                </value>
                <value>
                    <fullName>English (South Africa)</fullName>
                </value>
                <value>
                    <fullName>Estonian</fullName>
                </value>
                <value>
                    <fullName>Finnish</fullName>
                </value>
                <value>
                    <fullName>French</fullName>
                </value>
                <value>
                    <fullName>French (Belgian)</fullName>
                </value>
                <value>
                    <fullName>French (Canda)</fullName>
                </value>
                <value>
                    <fullName>German</fullName>
                </value>
                <value>
                    <fullName>Greek</fullName>
                </value>
                <value>
                    <fullName>Hungarian</fullName>
                </value>
                <value>
                    <fullName>Icelandic</fullName>
                </value>
                <value>
                    <fullName>Indonesian</fullName>
                </value>
                <value>
                    <fullName>Italian</fullName>
                </value>
                <value>
                    <fullName>Japanese</fullName>
                </value>
                <value>
                    <fullName>Korean</fullName>
                </value>
                <value>
                    <fullName>Latvian</fullName>
                </value>
                <value>
                    <fullName>Lithuanian</fullName>
                </value>
                <value>
                    <fullName>Norwegian</fullName>
                </value>
                <value>
                    <fullName>Polish</fullName>
                </value>
                <value>
                    <fullName>Portuguese</fullName>
                </value>
                <value>
                    <fullName>Portuguese (Brazil)</fullName>
                </value>
                <value>
                    <fullName>Russian</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>System_Login__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The field represents the System Login to be used by the Bureau Job to access the selected system.</description>
        <inlineHelpText>Specify the System Login to be used to access the selected system.</inlineHelpText>
        <label>System Login</label>
        <referenceTo>System_Login__c</referenceTo>
        <relationshipName>Bureau_Systems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>System_Type__c</fullName>
        <description>This field shows the System Type of the selected System</description>
        <formula>TEXT(System__r.System_Type__c)</formula>
        <inlineHelpText>This is the System Type of the selected System</inlineHelpText>
        <label>System Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>System_URL__c</fullName>
        <formula>System__r.System_URL__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>System URL</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>System__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field represents the System that is used by the Bureau Job</description>
        <inlineHelpText>Select the System to be used</inlineHelpText>
        <label>System</label>
        <referenceTo>System__c</referenceTo>
        <relationshipName>Bureau_Systems</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Managed Services System</label>
    <nameField>
        <displayFormat>BJS{000000}</displayFormat>
        <label>Managed Services System Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Managed Services Systems</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Job__c.object
<CustomObject>
    <description>The entity used to identify a work request from a client to the Bureau.</description>
    <fields>
        <fullName>Report_Language__c</fullName>
        <label>Report Language</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Language</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>System_Client_Id__c</fullName>
        <description>This field is used to store System client ID linked to Job</description>
        <label>System Client Id</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>System_URL__c</fullName>
        <description>This field is used to store System URL which is linked to Job</description>
        <label>System URL</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <label>Job</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Job Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/objects/System__c.object
<CustomObject>
    <description>For customer systems to be logged for external clients</description>
    <fields>
        <fullName>Is_Client_System__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is meant for specifying whether a System is a client system or not.</description>
        <inlineHelpText>Tick this box if the System is a Client System.</inlineHelpText>
        <label>Is Client System</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>System_Client_ID__c</fullName>
        <label>System Client ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>System_Client_Name__c</fullName>
        <label>System Client Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>System_Name__c</fullName>
        <description>This field is meant for storing the name of the System</description>
        <inlineHelpText>Specify the Unique Name of the System</inlineHelpText>
        <label>System Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>System_Type__c</fullName>
        <label>System Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>TalentCentral</fullName>
                </value>
                <value>
                    <fullName>TalentCentral+</fullName>
                </value>
                <value>
                    <fullName>iAssess/Amcatglobal</fullName>
                </value>
                <value>
                    <fullName>iAssess</fullName>
                </value>
                <value>
                    <fullName>BrainBench</fullName>
                </value>
                <value>
                    <fullName>Data Warehouse</fullName>
                </value>
                <value>
                    <fullName>Elearning</fullName>
                </value>
                <value>
                    <fullName>Insights via TC</fullName>
                </value>
                <value>
                    <fullName>Insights via TC+</fullName>
                </value>
                <value>
                    <fullName>Legacy System</fullName>
                </value>
                <value>
                    <fullName>MFS</fullName>
                </value>
                <value>
                    <fullName>NVM/Phone</fullName>
                </value>
                <value>
                    <fullName>Partner Portal</fullName>
                </value>
                <value>
                    <fullName>Practice site</fullName>
                </value>
                <value>
                    <fullName>SFDC</fullName>
                </value>
                <value>
                    <fullName>SHL Online</fullName>
                </value>
                <value>
                    <fullName>Website</fullName>
                </value>
                <value>
                    <fullName>VADC</fullName>
                </value>
                <value>
                    <fullName>VADC Dedicated Support</fullName>
                </value>
                <value>
                    <fullName>ASO</fullName>
                </value>
                <value>
                    <fullName>DSPS</fullName>
                </value>
                <value>
                    <fullName>Kwiz</fullName>
                </value>
                <value>
                    <fullName>Leader Edge</fullName>
                </value>
                <value>
                    <fullName>Nacho</fullName>
                </value>
                <value>
                    <fullName>Offline</fullName>
                </value>
                <value>
                    <fullName>S2P</fullName>
                </value>
                <value>
                    <fullName>SODA</fullName>
                </value>
                <value>
                    <fullName>Talent Analytics</fullName>
                </value>
                <value>
                    <fullName>Valtera</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>System_URL__c</fullName>
        <label>System URL</label>
        <type>Url</type>
    </fields>
    <label>System</label>
    <nameField>
        <displayFormat>SYS{00000}</displayFormat>
        <label>SFDC Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Systems</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/System_Login__c.object
<CustomObject>
    <description>Link to Systems module</description>
    <fields>
        <fullName>System_Client_ID__c</fullName>
        <formula>System__r.System_Client_ID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>System Client ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>System__c</fullName>
        <label>System</label>
        <referenceTo>System__c</referenceTo>
        <relationshipLabel>System Logins</relationshipLabel>
        <relationshipName>System_Logins</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>System Login</label>
    <nameField>
        <displayFormat>SYSL{00000}</displayFormat>
        <label>System Login ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>System Logins</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

globalValueSets/Language.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Arabic</fullName>
    </customValue>
    <customValue>
        <fullName>Chinese (Simplified)</fullName>
    </customValue>
    <customValue>
        <fullName>Chinese (Traditional)</fullName>
    </customValue>
    <customValue>
        <fullName>Czech</fullName>
    </customValue>
    <customValue>
        <fullName>Danish</fullName>
    </customValue>
    <customValue>
        <fullName>Dutch</fullName>
    </customValue>
    <customValue>
        <fullName>Dutch (Belgian)</fullName>
    </customValue>
    <customValue>
        <fullName>English (International)</fullName>
    </customValue>
    <customValue>
        <fullName>English (South Africa)</fullName>
    </customValue>
    <customValue>
        <fullName>English (United States)</fullName>
    </customValue>
    <customValue>
        <fullName>Estonian</fullName>
    </customValue>
    <customValue>
        <fullName>Finnish</fullName>
    </customValue>
    <customValue>
        <fullName>French</fullName>
    </customValue>
    <customValue>
        <fullName>French (Belgian)</fullName>
    </customValue>
    <customValue>
        <fullName>French (Canda)</fullName>
    </customValue>
    <customValue>
        <fullName>German</fullName>
    </customValue>
    <customValue>
        <fullName>Greek</fullName>
    </customValue>
    <customValue>
        <fullName>Hungarian</fullName>
    </customValue>
    <customValue>
        <fullName>Icelandic</fullName>
    </customValue>
    <customValue>
        <fullName>Indonesian</fullName>
    </customValue>
    <customValue>
        <fullName>Italian</fullName>
    </customValue>
    <customValue>
        <fullName>Japanese</fullName>
    </customValue>
    <customValue>
        <fullName>Korean</fullName>
    </customValue>
    <customValue>
        <fullName>Latvian</fullName>
    </customValue>
    <customValue>
        <fullName>Lithuanian</fullName>
    </customValue>
    <customValue>
        <fullName>Norwegian</fullName>
    </customValue>
    <customValue>
        <fullName>Polish</fullName>
    </customValue>
    <customValue>
        <fullName>Portuguese</fullName>
    </customValue>
    <customValue>
        <fullName>Portuguese (Brazil)</fullName>
    </customValue>
    <customValue>
        <fullName>Russian</fullName>
    </customValue>
    <masterLabel>Language</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

classes/SystemManagerController.cls
public without sharing class SystemManagerController {
    
    @AuraEnabled
    public static List<Bureau_System__c> getBureauSystemDetails(String jobId,Integer limitSize,Integer offset) {
        System.debug('jobId ###'+jobId);
        try {
            list<Bureau_System__c> bureauSystemList = new list<Bureau_System__c>();
            bureauSystemList = [SELECT 	Id, 
                                System__r.Name,
                                System_Type__c,
                                System__r.System_Name__c, 
                                System__r.System_Client_ID__c,
                                System__r.System_Client_Name__c,
                                System__r.Is_Client_System__c,
                                System_URL__c,
                                System_Login__r.Name, 
                                Report_Language__c, 
                                Project_Id__c
                                FROM 	Bureau_System__c
                                WHERE	Bureau_Job__c = :jobId
                                LIMIT :limitSize
                                OFFSET :offset];
            System.debug('bureauSystemList #####'+bureauSystemList);
            return bureauSystemList;
        } 
        catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
    
    @AuraEnabled
    public static List<System__c> getAllSystems(String jobId, Integer limitSize, Integer offset) {
        
        System.debug('jobId ###'+jobId);
        try {
            list<System__c> systemList = new list<System__c>();
            
            Job__c jobRec = new Job__c();
            
            jobRec = [SELECT Id,
                      System_Used__c,
                      Opportunity__r.Account.Id 
                      FROM 	Job__c 
                      WHERE Id = :jobId
                      LIMIT 1];
            
            List<String> systemUsedList = jobRec.System_Used__c.split(';');
            
            systemList = [SELECT Id, 
                          Name,
                          System_Type__c,
                          System_Client_ID__c,
                          System_Name__c, 
                          System_Client_Name__c,
                          Is_Client_System__c,
                          System_URL__c
                          FROM 	System__c
                          WHERE (Account__c = :jobRec.Opportunity__r.Account.Id
                                 OR	RecordType.Name = 'SHL System')
                          AND 	System_Type__c IN :systemUsedList
                          Order by Account__c NULLS LAST
                          LIMIT :limitSize
                          OFFSET :offset];
            System.debug('systemList ###'+systemList);
            return systemList;
            
        } 
        catch (Exception e) {
            System.debug('e.getMessage() ###'+e.getMessage());
            throw new AuraHandledException(e.getMessage());
        }
    }
    
    @AuraEnabled
    public static List<System__c> getPreselectedSystem(List<String> systemNameList, String jobId) {
        System.debug('systemNameList ####'+systemNameList);
        List<System__c> systemList = [SELECT Id, Name FROM System__c WHERE Name IN :systemNameList];
        return systemList;
    }
    
    @AuraEnabled
    public static String createBureauSystem(List<System__c> systemList, String bureauSystem,
                                            String projectIdMap, String jobId) 
    {
        System.debug('projectIdMap ###'+projectIdMap);
        System.debug('System List from LWC ###'+systemList);
        String message = '';
        Map<String, String> nameprojectIdMap = new Map<String, String>();
        Map<String, Bureau_System__c> existingSystem = new Map<String, Bureau_System__c>();
        List<String> newSysList = new List<String>();
        List<Bureau_System__c> sysToDelete = new List<Bureau_System__c>();
        List<Bureau_System__c> sysToInsert = new List<Bureau_System__c>();
        List<Bureau_System__c> sysToUpdate = new List<Bureau_System__c>();
        
        List<BureauSystemData> bureauList  = (List<BureauSystemData>)System.JSON.deserialize(bureauSystem, List<BureauSystemData>.class);
        List<ProjectIdData> projectIdList  = (List<ProjectIdData>)System.JSON.deserialize(projectIdMap, List<ProjectIdData>.class);                                        
        Job__c jobRec = new Job__c();
        
        jobRec = [SELECT Id, (Select Id, Name, Report_Language__c, Project_Id__c,
                              System__r.Name FROM Bureau_Systems__r),System_Used__c
                  FROM 	Job__c 
                  WHERE Id = :jobId
                  LIMIT 1];
        
        for(Bureau_System__c bObj : jobRec.Bureau_Systems__r) {
            existingSystem.put(bObj.System__r.Name, bObj);
        }
        for(ProjectIdData obj : projectIdList) {
            System.debug('obj.name ###'+obj.name);
            System.debug('obj.projectId ###'+obj.projectId);
            nameprojectIdMap.put(obj.name, obj.projectId);
        }
        
        for(System__c sysObj : systemList) {
            
            if(!existingSystem.containsKey(sysObj.Name)) {
                System.debug('Record can be inserted');
                Bureau_System__c bureauObj = new Bureau_System__c();
                bureauObj.Bureau_Job__c = jobId;
                bureauObj.System__c = sysObj.Id;
                bureauObj.Project_Id__c = nameprojectIdMap.get(sysObj.Name);
                //Insert bureauObj;
                sysToInsert.add(bureauObj);
                if(sysObj.System_Type__c == jobRec.System_Used__c) {
                    jobRec.System_Client_ID__c = sysObj.System_Client_ID__c;
                    jobRec.System_URL__c = sysObj.System_URL__c;
                } 
                   
            }
            if(existingSystem.containsKey(sysObj.Name)) {
                System.debug('Record can be updated');
                Bureau_System__c bureauRec = existingSystem.get(sysObj.Name);
                if(bureauRec.Project_Id__c != nameprojectIdMap.get(sysObj.Name)) 
                {
                    System.debug('Reporting language or Project Id Updated');
                    Bureau_System__c bureauObj = new Bureau_System__c();
                    bureauObj.Id = bureauRec.Id;
                    bureauObj.Project_Id__c = nameprojectIdMap.get(sysObj.Name);
                    UPDATE bureauObj;
                }
            }
            
            newSysList.add(sysObj.Name);
        }
        try {
            INSERT sysToInsert;
            update jobRec;
        }
        catch(DMLException exp) {
            System.debug('Exception ####'+exp.getMessage());
            message = exp.getDmlMessage(0);
        }
        
        for(Bureau_System__c existing : existingSystem.values()) {
            if(!newSysList.contains(existing.System__r.Name)) {
                sysToDelete.add(existing);
            }
        }
        if(!sysToDelete.isEmpty()) {
            try {
                DELETE sysToDelete;
            }
            catch(Exception exp) {
                System.debug('Exception ####'+exp.getMessage());
            }
        }
        return message;
    }
    
    class BureauSystemData {
        String name;
        String lang;
    }
    
    class projectIdData {
        String name;
        String projectId;
    }
}