force-app/main/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Original_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Original Order(Legacy)</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Variation Orders</relationshipLabel>
        <relationshipName>Contracts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Variation_Order__c</fullName>
        <formula>text(Opportunity__r.Variation_Opportunity__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Variation Opportunity(Legacy)</label>
        <type>Text</type>
    </fields>
</CustomObject>

objects/Contract_Line__c.object
<CustomObject>
    <description>Order Management</description>
    <fields>
        <fullName>Contract__c</fullName>
        <label>Order</label>
        <referenceTo>Contract</referenceTo>
        <relationshipName>Contract_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>IM_Lookup_Code__c</fullName>
        <label>Order Line Item</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Order_Method__c</controllingField>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>360 Platform Set up</fullName>
                </value>
                <value>
                    <fullName>360 Subscription</fullName>
                </value>
                <value>
                    <fullName>Advisory Services Subscription</fullName>
                </value>
                <value>
                    <fullName>AM Aptitude (In Arrears)</fullName>
                </value>
                <value>
                    <fullName>AM Coding (In Arrears)</fullName>
                </value>
                <value>
                    <fullName>AM Generic (In Arrears)</fullName>
                </value>
                <value>
                    <fullName>AM Language (In Arrears)</fullName>
                </value>
                <value>
                    <fullName>AM Personal &amp; Behavioural (In Arrears)</fullName>
                </value>
                <value>
                    <fullName>AM Pool Hiring (In Arrears)</fullName>
                </value>
                <value>
                    <fullName>AM Proctoring (In Arrears)</fullName>
                </value>
                <value>
                    <fullName>AM Product Subscription</fullName>
                </value>
                <value>
                    <fullName>AM Professional Services</fullName>
                </value>
                <value>
                    <fullName>AM Skills: Analytics (In Arrears)</fullName>
                </value>
                <value>
                    <fullName>AM Skills: Banking and Financial Serv (In Arrears)</fullName>
                </value>
                <value>
                    <fullName>AM Skills: Customer Service, Contact Center and BPO (In Arrears)</fullName>
                </value>
                <value>
                    <fullName>AM Skills: Engineering (In Arrears)</fullName>
                </value>
                <value>
                    <fullName>AM Skills: Finance and Accounting (In Arrears)</fullName>
                </value>
                <value>
                    <fullName>AM Skills: Healthcare, Pharma and Life Sciences (In Arrears)</fullName>
                </value>
                <value>
                    <fullName>AM Skills: Human Resources, Marketing and Operations (In Arrears)</fullName>
                </value>
                <value>
                    <fullName>AM Skills: MS Office (In Arrears)</fullName>
                </value>
                <value>
                    <fullName>AM Skills: Sales and Business Development (In Arrears)</fullName>
                </value>
                <value>
                    <fullName>AM Skills: Sciences (In Arrears)</fullName>
                </value>
                <value>
                    <fullName>AM Skills: Technology (In Arrears)</fullName>
                </value>
                <value>
                    <fullName>AM Skills: Tourism and Hospitality (In Arrears)</fullName>
                </value>
                <value>
                    <fullName>AM Video (In Arrears)</fullName>
                </value>
                <value>
                    <fullName>Application Analytics Subscription</fullName>
                </value>
                <value>
                    <fullName>Bureau</fullName>
                </value>
                <value>
                    <fullName>Candidate Support – Bronze</fullName>
                </value>
                <value>
                    <fullName>Candidate Support for Subscription</fullName>
                </value>
                <value>
                    <fullName>Candidate Support –  Gold</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Original_Order_Line__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Original Order Line</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Original_Order__c</field>
                <operation>equals</operation>
                <valueField>Contract_Line__c.Contract__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contract_Line__c</referenceTo>
        <relationshipLabel>Variation Order Lines</relationshipLabel>
        <relationshipName>Order_Line</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Original_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Original Order</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Order Line (Original Order)</relationshipLabel>
        <relationshipName>Order_Line</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Line Price</label>
        <precision>11</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>ProjectObject__c</referenceTo>
        <relationshipName>Order_Line</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Running_Total__c</fullName>
        <description>This field will be sum of price on original order line and price of related/linked variation order lines.</description>
        <label>Running Total</label>
        <precision>11</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Variation_Order__c</fullName>
        <formula>Contract__r.Variation_Order__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Variation Order</label>
        <type>Text</type>
    </fields>
    <label>Order Line</label>
    <nameField>
        <displayFormat>CLN{0000000}</displayFormat>
        <label>Order Line</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Line</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Milestone__c.object
<CustomObject>
    <description>An object to record Milestones that can be signed by the PM Agent for revenue recognition</description>
    <fields>
        <fullName>Is_Signed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Signed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PM_Agent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>PM Agent</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Milestones</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>ProjectObject__c</referenceTo>
        <relationshipLabel>Milestones</relationshipLabel>
        <relationshipName>Milestones</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Milestone</label>
    <nameField>
        <displayFormat>MS{00000}</displayFormat>
        <label>Milestone Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Milestones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/objects/Order.object
<CustomObject>
    <fields>
        <fullName>Original_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Original Order</label>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Reduction/Variation Orders</relationshipLabel>
        <relationshipName>OriginalOrders</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

objects/Project_Invoice__c.object
<CustomObject>
    <description>Represents the invoice generated for the Time &amp; Expenses of a Project.</description>
    <fields>
        <fullName>Approved_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Represents the user who approved this invoice</description>
        <label>Approved By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <description>Project to which this invoice belongs</description>
        <label>Project</label>
        <referenceTo>ProjectObject__c</referenceTo>
        <relationshipLabel>Invoice Requests</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Invoice Request Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>In Progress</fullName>
                    <default>true</default>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>Submitted for Processing</fullName>
                </value>
                <value>
                    <fullName>Processed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Invoice Request</label>
    <nameField>
        <displayFormat>Inv{000000}</displayFormat>
        <label>Invoice Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ProjectObject__c.object
<CustomObject>
    <description>Used for PSA work</description>
    <label>Project</label>
    <nameField>
        <displayFormat>P{000000}</displayFormat>
        <label>Project Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <recordTypes>
        <fullName>Project</fullName>
        <active>true</active>
        <label>Project</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/ContractLineTriggerManager_1.cls
/**************************************************************************************************************************************
CREATED BY :- Virendra Kumar
CREATED DATE :- 25-07-2019
DESCRIPTION :-  This class contains ContractLine trigger related functionalities for before update event:
1. Line price update condition.
2. IM lookup code update condition.
3. Update the Running total.
4. Validation error on disassociating project.     
   

***************************************************************************************************************************************/
public class ContractLineTriggerManager_1{
    
    /*This method contains below functionalities:
    1. If Related  order is in complete status  then IM Lookup Code cannot be edited 
    2. If IM Lookup code has specific values(defined in custom setting - Field Value Setting) then Line price cannot be  changed  from >0 to 0
    3. if variation order is 'NO' & old and new line price are different Update the Running total.
    4. Apart from admin & if project !=null & Milestones related to project >0 & invoice related to project >0 then error to be:     
              "You cannot disassociate Project: Name from its order line, as there is either a signed milestone/Submitted for Processing invoice request for this project"""
    
    
    */
    public static void runningtotalUpdate_validationErrors(list<Contract_Line__c> ContractlineNewlist, list<Contract_Line__c> Contractlineoldlist)
    {
        Set<Id> profileIdsSet = new Set<Id>();
        Boolean isAdmin = false;    
        // getting logged in user's profile ID
        Id profileId=userinfo.getProfileId();  
        list<id> contractlist=new list<id>();
        List<profile> OATProfile = [Select id,name from profile where name =:'OAT' limit 1];
        //edited  by saloni chhabra  on 2/25/2015 starts here
        //SSE-25: 1. Related  order is in complete status  then IM Lookup Code cannot be edited  and 
        //2. if IM Lookup code has specific values(defined in custom setting - Field Value Setting) then Line price cannot be  changed  from >0 to 0
        //check logged in user is OAT profile except Ulyana Ferreira and Adien Ware added as part of SSE-4273 and SSE-3816 
        Set<string> UlyanaFerreiraUserID = Utility.getUlyanaFerreria();
        system.debug('--->UlyanaFerreiraUserID<----'+UlyanaFerreiraUserID);
        if(OATProfile.size()>0 && OATProfile[0].id == profileId && UlyanaFerreiraUserID.contains(UserInfo.getUserId()) == false)
        {
            /******************************************** LINE PRICE UPDATE CONDITIONS********************************************************/
            for(Contract_Line__c contractline:ContractlineNewlist)
            {
            contractlist.add(contractline.Contract__c);
            }
            List<Contract> Lcontract = [Select id,name,status from Contract where id IN:contractlist limit 1];
                   
            for(Integer i = 0;i<ContractlineNewlist.size();i++)
            {
                //check Order related to Order line should be in "Complete" status.
                if(ContractlineNewlist[i].Contract__c!=null)
                {
                    If(Lcontract.size()>0 && Lcontract[0].status == 'Complete')
                    {
                        // getting  IM lookup code predefined values via Utility  class from a custom setting(Field Value Setting)
                        Set<string> IMlookupCode = Utility.getIMLookupCode();
                        
                        //setting boolean IMLookupcheck with true/false whether IM lookup code is one of the defined values in custom setting
                        boolean IMLookupcheck ;
                        if(IMlookupCode.size()>0 && ContractlineNewlist[i].IM_Lookup_Code__c != '' )
                        {
                            IMLookupcheck = IMlookupCode.contains(ContractlineNewlist[i].IM_Lookup_Code__c);
                        }
                        
                        //IM in the list and Line price and running total any value or both 0 then update on Line price to value>0 is allowed
                        if(IMLookupcheck == true)
                        {
                            //check LINE PRICE or RUNNING TOTAL any value is zero
                            if((ContractlineNewlist[i].Price__c == 0 && (ContractlineNewlist[i].Running_Total__c == 0 || ContractlineNewlist[i].Running_Total__c == null ))
                               || (ContractlineNewlist[i].Price__c != 0 || (ContractlineNewlist[i].Running_Total__c != 0 && ContractlineNewlist[i].Running_Total__c != null)))
                            {
                                //Checking line price is changed to 0 from >0 
                                if(Contractlineoldlist[i].Price__c != 0 && ContractlineNewlist[i].Price__c == 0)
                                {
                                    ContractlineNewlist[i].addError(System.Label.ContractLine_BeforeUpdate_ModificationOnCompleteOrder);
                                }
                            }
                        }
                        else if(IMLookupcheck == false)
                        {
                            //Checking line price is changed to 0 from >0 
                            if(ContractlineNewlist[i].Price__c != Contractlineoldlist[i].Price__c)
                            {
                                ContractlineNewlist[i].addError(System.Label.ContractLine_BeforeUpdate_ModificationOnCompleteOrder);
                            }
                        }
                    }
                }
            }   
            
            
            /******************************************* IM LOOKUP CODE UPDATE CONDITIONS********************************************************/
            
            for(Integer i = 0;i<ContractlineNewlist.size();i++)
            {
                //check Order related to Order line should be in "Complete" status.
                if(ContractlineNewlist[i].Contract__c!=null)
                {
                    IF(Lcontract.size()>0 && Lcontract[0].status == 'Complete')
                    {
                        // getting  IM lookup code predefined values via Utility  class from a custom setting(Field Value Setting)
                        Set<string> IMlookupCode = Utility.getIMLookupCode();
                        
                        //setting boolean IMLookupcheck with true/false whether IM lookup code is one of the defined values in custom setting
                        boolean IMLookupcheck ;
                        if(IMlookupCode.size()>0 && ContractlineNewlist[i].IM_Lookup_Code__c != '' )
                        {
                            IMLookupcheck = IMlookupCode.contains(ContractlineNewlist[i].IM_Lookup_Code__c);
                        }
                        //IM in the list and Line price and running total any value or both 0 then update on Line price to value>0 is allowed
                        if(IMLookupcheck == true)
                        {
                            //check LINE PRICE or RUNNING TOTAL both is zero
                            if(ContractlineNewlist[i].Price__c != 0 || (ContractlineNewlist[i].Running_Total__c != 0 && ContractlineNewlist[i].Running_Total__c != null))
                            {
                                if((ContractlineNewlist[i].IM_Lookup_Code__c != Contractlineoldlist[i].IM_Lookup_Code__c) && (IMlookupCode.contains(Contractlineoldlist[i].IM_Lookup_Code__c) == false))
                                {
                                    ContractlineNewlist[i].addError('Order Line Item cannot be modified');
                                }
                            }
                        }
                        else
                        {
                            if(IMlookupCode.contains(Contractlineoldlist[i].IM_Lookup_Code__c ) == true)
                            {
                                if(ContractlineNewlist[i].Price__c != 0|| (ContractlineNewlist[i].Running_Total__c != 0 && ContractlineNewlist[i].Running_Total__c != null))
                                {
                                    if(ContractlineNewlist[i].IM_Lookup_Code__c != Contractlineoldlist[i].IM_Lookup_Code__c)
                                    {
                                        ContractlineNewlist[i].addError('Order Line Item cannot be modified');
                                    }
                                }
                            }
                            else if(IMlookupCode.contains(Contractlineoldlist[i].IM_Lookup_Code__c ) == false)
                            {
                                if(ContractlineNewlist[i].Price__c != 0 || (ContractlineNewlist[i].Running_Total__c != 0 && ContractlineNewlist[i].Running_Total__c != null))
                                {
                                    if(ContractlineNewlist[i].IM_Lookup_Code__c != Contractlineoldlist[i].IM_Lookup_Code__c)
                                    {
                                        ContractlineNewlist[i].addError('Order Line Item cannot  be modified');
                                    }
                                }
                                
                            }
                        }
                    }
                    
                }
            }       
        }
        
        //edited  by saloni chhabra  on 2/25/2015 ends here
        //Below code has been added for the requirement requested in the CRI - 1203
        Set<Id> orderIdsSet = new Set<Id>();
        for(Integer i=0;i<Trigger.new.size();i++)
        {
            if(ContractlineNewlist[i].Original_Order__c!=Contractlineoldlist[i].Original_Order__c || ContractlineNewlist[i].Original_Order_Line__c==null)
                orderIdsSet.add(ContractlineNewlist[i].Contract__c);
        }
        Map<Id,Contract> contractMap = new Map<Id,Contract>([Select id,Original_Order__c,Variation_Order__c,Status from Contract where id in :orderIdsSet]);
        for(Integer i=0;i<ContractlineNewlist.size();i++)
        {
            if(ContractlineNewlist[i].Variation_Order__c == 'No' && ContractlineNewlist[i].Price__c != Contractlineoldlist[i].Price__c)
            {
                if(ContractlineNewlist[i].Running_Total__c==null)
                    ContractlineNewlist[i].Running_Total__c = 0;
                if(Contractlineoldlist[i].Price__c!=null)
                    ContractlineNewlist[i].Running_Total__c = ContractlineNewlist[i].Running_Total__c - Contractlineoldlist[i].Price__c;
                ContractlineNewlist[i].Running_Total__c = ContractlineNewlist[i].Running_Total__c + ContractlineNewlist[i].Price__c;
            }
             
        }
        //End Code change requested in CRI - 1203
        
        for(Profile prf : [Select id,Name from Profile where Name like '%System Admin%']){
            if(prf.Id == UserInfo.getProfileId()){
                isAdmin = true;
                break;
            }
        }   
        if(!isAdmin)
        {        
            Set<Id> projectIdsSet = new Set<Id>();
            for(Integer i=0;i<ContractlineNewlist.size();i++)
            {
                if(ContractlineNewlist[i].Project__c != Contractlineoldlist[i].Project__c)
                    projectIdsSet.add(Contractlineoldlist[i].Project__c);
            }
            Map<Id,ProjectObject__c> projectsMap = new Map<Id,ProjectObject__c>([Select id, Name,(SELECT id FROM Milestones__r WHERE Is_Signed__c = True limit 1),(SELECT id FROM Invoices__r WHERE Status__c = 'Submitted for Processing' or Status__c = 'Processed' limit 1) from ProjectObject__c where id in :projectIdsSet]);
            for(Integer i=0;i<ContractlineNewlist.size();i++)
            {    
                if(projectsMap!=null && projectsMap.get(Contractlineoldlist[i].Project__c)!= null && (projectsMap.get(Contractlineoldlist[i].Project__c).Milestones__r.size()>0 || projectsMap.get(Contractlineoldlist[i].Project__c).Invoices__r.size()>0))
                    ContractlineNewlist[i].addError('You cannot disassociate Project:'+projectsMap.get(Contractlineoldlist[i].Project__c).Name+' from its order line, as there is either a signed milestone/Submitted for Processing invoice request for this project');
                
            }
        }
    }      
}