force-app/main/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Annual_Contract_Value__c</fullName>
        <label>ACV1(Legacy)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Billing_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Billing Contact(Legacy)</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contracts (Billing Contact)</relationshipLabel>
        <relationshipName>Contracts2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Booked_Elsewhere__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Booked Elsewhere(Legacy)</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Booking_Date__c</fullName>
        <label>SHL Signed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CSVCount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>CSVCount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Invoicing_Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Primary Contact(Legacy)</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contracts (Invoicing Contact)</relationshipLabel>
        <relationshipName>Contracts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NVM_Credit_Card_ID__c</fullName>
        <label>NVM Payment ID(Legacy)</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity(Legacy)</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PDFCount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>PDFCount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Subscription_Start_Date__c</fullName>
        <inlineHelpText>This date should be the same as the Contract Start Date unless delay has been approved in CLM.</inlineHelpText>
        <label>Product Subscription Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TCV__c</fullName>
        <defaultValue>0.00</defaultValue>
        <label>Total Contract Value(Legacy)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Contract_Value__c</fullName>
        <label>Total Contract Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Unconfirmed_Sun_Order_Number__c</fullName>
        <label>Unconfirmed Sun Order Number(Legacy)</label>
        <length>11</length>
        <type>Text</type>
    </fields>
</CustomObject>

force-app/main/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Annual_Contract_Value__c</fullName>
        <label>Annual Contract Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Billing_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Billing Contact</label>
        <lookupFilter>
            <active>false</active>
            <errorMessage>Billing Contact should be part of the account linked to the opportunity.</errorMessage>
            <filterItems>
                <field>$Source.AccountId</field>
                <operation>equals</operation>
                <valueField>Contact.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Business_Type__c</fullName>
        <description>Choose the Opportunity Type that best describes the type of business pursued.  
Reboost should only be used with In-Advance clients. 
Cross-sell is simply New Business with a client that has a current commercial relationship.</description>
        <label>Opportunity Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Expansion</fullName>
                </value>
                <value>
                    <fullName>Renewal</fullName>
                </value>
                <value>
                    <fullName>Debooking</fullName>
                    <label>Debooking / Adjustment</label>
                </value>
                <value>
                    <fullName>Extension</fullName>
                </value>
                <value>
                    <fullName>In Arrears</fullName>
                </value>
                <value>
                    <fullName>In Advance</fullName>
                </value>
                <value>
                    <fullName>Managed Services</fullName>
                </value>
                <value>
                    <fullName>Professional Services: non-subscription</fullName>
                </value>
                <value>
                    <fullName>Top Up / Addition</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Eligible_for_Auto_Close__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Eligible for Auto-Close?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Future_Product_Total_Price__c</fullName>
        <label>Future Product Total Price</label>
        <summarizedField>Future_Product__c.Total_Price__c</summarizedField>
        <summaryForeignKey>Future_Product__c.Opportunity__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>GCSC__c</fullName>
        <label>GCSC Method</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Phone</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>NVM_Credit_Card_ID__c</fullName>
        <label>NVM Payment ID</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity_Deal_Year__c</fullName>
        <defaultValue>1</defaultValue>
        <description>Current Deal Year of Opportunity</description>
        <label>Opportunity Year</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Primary_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities (Primary Contact)</relationshipLabel>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Unconfirmed_Sun_Order_Number__c</fullName>
        <label>Unconfirmed Sun Order Number</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>For opportunity owners to assign a primary and secondary sales person to an opportunity</description>
        <label>Pre-Sales Attributed to (1)</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunity</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

force-app/main/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Contract_Year__c</fullName>
        <label>Contract Year</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                    <default>true</default>
                    <label>1</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

force-app/main/objects/Order.object
<CustomObject>
    <fields>
        <fullName>Booked_Elsewhere__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Booked Elsewhere</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Booking_Date__c</fullName>
        <label>Booking Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Order_Year__c</fullName>
        <label>Order Year</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unconfirmed_Sun_Order_Number__c</fullName>
        <label>Unconfirmed Sun Order Number</label>
        <length>11</length>
        <type>Text</type>
    </fields>
</CustomObject>

classes/ContractTriggerManagerNew.cls
/**************************************************************************************************************************************
CREATED BY :- Saloni Chhabra
CREATED DATE :- 12-08-2020
DESCRIPTION :- This class contains Contract trigger related functionalities : before update,after update
***************************************************************************************************************************************/ 
global class ContractTriggerManagerNew{

    //Contract cannot be marked as cancelled if have any related Order activated
    public static void ContractCancel(List<Contract> contractlistnew,List<Contract> contractlistold){
			 System.debug('Number of Queries used -- ContractTriggerManagerNew.ContractCancel START ------- ' + Limits.getQueries());
            set<id> contractid = new set<id>();
            for(integer i=0; i<contractlistnew.size(); i++){
                if( contractlistnew[i].RecordType.DeveloperName != 'MSA_Contract' && ( //add check to exclude MSA Contract
                    contractlistnew[i].Status=='Cancelled' && contractlistold[i].Status != 'Cancelled') ){
                        contractid.add(contractlistnew[i].id);
                        
                    }
                }
        system.debug('---->contractid<---'+contractid);
        if(!contractid.isEmpty()){
            List<Order> ActvOrderList = [Select id,name,Status,Contractid,Order_Year__c from Order where Contractid in: contractid AND Status ='Activated' AND Order_Year__c>1];
            if(ActvOrderList.size()>0){
                for(Contract contr:contractlistnew){
                contr.addError('Contract cannot be marked as cancelled as linked Renewal Order is already activated');
                }
            }
        }
        System.debug('Number of Queries used -- ContractTriggerManagerNew.ContractCancel END ------- ' + Limits.getQueries());
        }
        
    //Contract can only be accepted until linked opportunity billing contact is null or not a part of same Account.
    //Contract can only be accepted until linked opportunity is moved to verbal
    public static void ContractActvOpptyVerbal(List<Contract> contractlistnew,List<Contract> contractlistold){
        System.debug('Number of Queries used -- ContractTriggerManagerNew.ContractActvOpptyVerbal START ------- ' + Limits.getQueries());
        set<id> contractid = new set<id>();
            for(integer i=0; i<contractlistnew.size(); i++){
                if( contractlistnew[i].RecordType.DeveloperName != 'MSA_Contract' && ( //add check to exclude MSA Contract
                    contractlistnew[i].Status=='Accepted' && contractlistold[i].Status != 'Accepted') ){
                        contractid.add(contractlistnew[i].id);
                        
                    }
                }
        system.debug('----> contractid second method--'+contractid);
           if(!contractid.isEmpty()){                                 
            List<Opportunity> OrgOpptyList2 = [Select id,name,StageName,Contractid,Business_Type__c,Billing_Contact__c from Opportunity where Billing_Contact__c = null AND Contractid in: contractid];
            if(OrgOpptyList2.size()>0){
                for(Contract contr:contractlistnew){
                contr.addError('Contract cannot be marked as Accepted as associated Opportunity does not have a Billing Contact');
                }
            }
            
            set<id> accountids = new set<id>();            
            Set<id> contractids = new set<id>();   // set of contract ids where contact is a part of account.
            Map<Id,List<Contact>> mapAccountContact = new Map<Id,List<Contact>>();
            
            List<Opportunity> OrgOpptyList3 = [Select id,name,AccountId,StageName,Contractid,Business_Type__c,Billing_Contact__c from Opportunity where Billing_Contact__c != null AND Contractid in: contractid]; 
            if(OrgOpptyList3.size()>0){
               for(Opportunity olist : OrgOpptyList3){
                   accountids.add(olist.AccountId);
               }
            }
            
            if(accountids != null){
               List<Account> acclist = [Select id,(Select Id from Contacts) from Account where Id IN: accountids];
                   for(Account acc: acclist){                
                      mapAccountContact.put(acc.Id, acc.contacts);
                   }
               
            }
                         
            for(Opportunity olist : OrgOpptyList3){ 
                for(Contact con: mapAccountContact.get(olist.AccountId)) {
                    if(olist.Billing_Contact__c == con.id)
                      contractids.add(olist.ContractId);   // positive contracts where combination of contact and account is right on opp
                } 
             } 
             
             if(OrgOpptyList3.size()>0){ 
                 for(Contract contr:contractlistnew){
                    if(!contractids.contains(contr.id)){ // if contract is not a part of positive combination of contact and account set.
                       contr.addError('Contract cannot be marked as Accepted as associated Opportunity Billing Contact is not a part of Account');
                    }
                 }
             } 
           } 
            /*List<Opportunity> OrgOpptyList = [Select id,name,StageName,Opportunity_Deal_Year__c,Contractid,Business_Type__c from Opportunity where StageName!='Verbal' AND Contractid in: contractid];
            if(OrgOpptyList.size()>0){
                for(Contract contr:contractlistnew){
                contr.addError('Contract cannot be marked as Accepted as Opportunity is not in Verbal');
                }
            }*/
        System.debug('Number of Queries used -- ContractTriggerManagerNew.ContractActvOpptyVerbal END ------- ' + Limits.getQueries());
        
    }
    
     // This method is responsible for PDF and CSV checks/errors on Contract when User is trying to attach files/attachment.
      public static void OrderPdfCsvChecks(List<Contract> ContractsNewList, List<Contract> ContractsOldList){
          System.debug('Number of Queries used -- ContractTriggerManagerNew.OrderPdfCsvChecks START ------- ' + Limits.getQueries());
         Boolean isAdmin = false;
         Boolean statusIsSubmitted = false;
         Set<Id> contractIdsSet = new Set<Id>(); 
         String oppRecordType = System.Label.GCSCRecordType;
         String oppRecordTypeIgnite = System.Label.IgniteRecordType; 
         
        for(Profile prf : [Select id,Name from Profile where Name like '%System Admin%']){
            if(prf.Id == UserInfo.getProfileId()){
              isAdmin = true;
              break;
            }
        }
        
         for(Integer i=0;i<ContractsNewList.size();i++){
            if( ContractsNewList[i].RecordType.DeveloperName != 'MSA_Contract' && ( //add check to exclude MSA Contract
                (ContractsNewList[i].status=='Under Customer Review' && ContractsOldList[i].status!='Under Customer Review') ||
                (ContractsNewList[i].status=='Accepted' && ContractsOldList[i].status!='Accepted') )
            ){
                statusIsSubmitted = true;
                contractIdsSet.add(ContractsNewList[i].id);
            }        
        }
        
        if(statusIsSubmitted == true && !contractIdsSet.isEmpty()){            
            Map<id,Contract> contractMap = new Map<Id,Contract>([Select id, OwnerId,PDFCount__c,CSVCount__c, Accountid,Billing_Contact__c,Booking_Date__c,Invoicing_Contact__c,TCV__c,
                                                            Annual_Contract_Value__c,Unconfirmed_Sun_Order_Number__c, NVM_Credit_Card_ID__c,
                                                            Opportunity__r.Annual_Contract_Value__c,Opportunity__r.Amount,Opportunity__r.ownerId,Opportunity__r.Eligible_for_Auto_Close__c,
                                                            Opportunity__r.AccountId,Opportunity__r.Billing_Contact__c,Opportunity__r.Closedate,Opportunity__r.StageName,
                                                            Opportunity__r.Primary_Contact__c,Opportunity__r.CurrencyIsoCode,Opportunity__r.Unconfirmed_Sun_Order_Number__c,
                                                            Opportunity__r.NVM_Credit_Card_ID__c,Opportunity__r.GCSC__c,Opportunity__r.RecordTypeId,
                                                            (Select id,ParentID from Attachments where contenttype='application/pdf') 
                                                            from Contract where id in :contractIdsSet]);
            
             //Added Eligible Auto- Close condition by Prachi - SSE-16342
            List<opportunity> oppList = new List<opportunity>([Select id ,Eligible_for_Auto_Close__c ,RecordTypeId, ContractId from opportunity where ContractId in :contractIdsSet ]);
            Map<string,opportunity> oppMap = new Map<string,opportunity>();
            for(Opportunity o: oppList){
                oppMap.put(o.ContractId , o);
            }
            //Change End SSE-16342
          //  Map<string, Opportunity> oppMap = new Map<
             for(Contract contract : ContractsNewList){
                if(!isAdmin){
                      if((contract.status=='Under Customer Review' || contract.status=='Accepted')){
                           /*if(contractMap.get(contract.id).Opportunity__r.RecordTypeId !=oppRecordTypeIgnite){
                                if(contractMap!= null  && contract.Booked_Elsewhere__c == false && contractMap.get(contract.id).Opportunity__r.RecordTypeId != oppRecordType){  
                                    if(contractMap.get(contract.id).PDFCount__c==0 ||contractMap.get(contract.id).PDFCount__c==null){
                                        contract.adderror('Contract status cannot be changed to "'+ contract.status + '" as it does not have a signed Order PDF attached');
                                    }
                                }
                            }*/
                            
                            //Added Eligible Auto- Close condition by Prachi - SSE-16342
                            if(contractMap!= null  && contract.Booked_Elsewhere__c == false && contractMap.containsKey(contract.id) && oppMap.get(contract.id).Eligible_for_Auto_Close__c == false && contractMap.get(contract.id).Opportunity__r.RecordTypeId != oppRecordType){  
                                if((contractMap.get(contract.id).PDFCount__c==null)||(contractMap.get(contract.id).CSVCount__c ==null)||(contractMap.get(contract.id).CSVCount__c ==0) || (contractMap.get(contract.id).PDFCount__c<1)){
                                    contract.adderror('Contract status cannot be changed to "'+ contract.status + '" as it does not have both  \'Signed Order Form PDF\' and \'Pricing Configurator\'');  
                                }
                            }
                      }
                }
             }              
        }
          System.debug('Number of Queries used -- ContractTriggerManagerNew.OrderPdfCsvChecks END ------- ' + Limits.getQueries());
      }
    
    //This method is to update total contract value on contract activation.
     public static void ContractValue(List<Contract> contractlistnew,List<Contract> contractlistold){
         System.debug('Number of Queries used -- ContractTriggerManagerNew.ContractValue START ------- ' + Limits.getQueries());
        System.debug('Hello***');
        
        
        set<id> contractid = new set<id>();
        List< Contract> contList = new List <Contract>();
        List<Contract> conlist2 = new List<Contract>();
        double count =0;
        for(integer i=0; i<contractlistnew.size(); i++){
            if( contractlistnew[i].RecordType.DeveloperName != 'MSA_Contract' && ( //add check to exclude MSA Contract
                contractlistnew[i].Status=='Accepted' && contractlistold[i].Status != 'Accepted' ) 
              ){
                contractid.add(contractlistnew[i].id);
                
            }
            
            
        }
        System.debug('count*****'+ contractid);
        
        if(!contractid.isEmpty())
        {
            contList = [Select id,(Select id,Future_Product_Total_Price__c,Amount,Contractid from Opportunities) from Contract where id in: contractid];
            
            for( contract c :contList){
                if(c.Opportunities.size()>0){
                    for(Opportunity opp :c.Opportunities){
                        count =  opp.Future_Product_Total_Price__c + opp.Amount;
                        System.debug('count'+count);
                    }
                    c.Total_Contract_Value__c = count;
                    System.debug('count***'+ c.Total_Contract_Value__c);
                    
                }
                conlist2.add(c);
                
                
                
                
                
            }     
        }
        update conlist2;
        
        System.debug('Number of Queries used -- ContractTriggerManagerNew.ContractValue END ------- ' + Limits.getQueries());
        
        
    }
      
      // This method is responsible for adding zero year product as susbcription does not start on same day of contract start date.
      /*public static void SubscriptionValidations(List<Contract> ContractsNewList, List<Contract> ContractsOldList){
        Boolean validationtrue = false;
        Boolean isAdmin = false;
        Set<id> OpptyIdSet = new Set<id>();
        Set<Id> ContractIDSet = new Set<id>();
        List<Opportunity> ListOpportunity  = new List<Opportunity>();
        List<OpportunityLineItem> OpptyProductList = new List<OpportunityLineItem>();
        
        for(Profile prf : [Select id,Name from Profile where Name like '%System Admin%']){
            if(prf.Id == UserInfo.getProfileId()){
              isAdmin = true;
              break;
            }
        }
        if(!isAdmin){
            for(Integer i=0;i<ContractsNewList.size();i++){
                ContractIDSet.add(ContractsNewList[i].id);               
                    if(ContractsOldList[i].status !='Accepted' && ContractsNewList[i].status=='Accepted'){
                        validationtrue = true;
                    }
                }
        
        
            if(validationtrue == true){
                ListOpportunity = [Select id,name,ContractID,Opportunity_Deal_Year__c from Opportunity where ContractId in:ContractIDSet AND Opportunity_Deal_Year__c =1];
            }
            
            if(ListOpportunity.size()>0){
                for(Opportunity OppObj:ListOpportunity){
                    OpptyIdSet.add(OppObj.id);
                }
            }
            OpptyProductList = [Select id,Contract_Year__c,OpportunityId from OpportunityLineItem where Contract_Year__c = '0' AND OpportunityId IN: OpptyIdSet];
        
        
            for(Integer i=0;i<ContractsNewList.size();i++){
                    if(OpptyProductList.isEmpty() == true && ContractsNewList[i].Subscription_Start_Date__c > ContractsNewList[i].StartDate && ContractsOldList[i].status !='Accepted' && ContractsNewList[i].status=='Accepted'){
                    ContractsNewList[i].addError('Please add Zero year product to Opportunity as product subscription starts after contract start date.');
                }
                else if(OpptyProductList.size() > 0 && ContractsNewList[i].Subscription_Start_Date__c == ContractsNewList[i].StartDate && ContractsOldList[i].status !='Accepted' && ContractsNewList[i].status=='Accepted'){
                    ContractsNewList[i].addError('Please mark Product subscription start date after Contract start date as opportunity has zero year products or delete zero year product & services');
                }
            }
        }
          
    }*/
     
}