force-app/main/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Billing_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Billing Contact(Legacy)</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contracts (Billing Contact)</relationshipLabel>
        <relationshipName>Contracts2</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

force-app/main/objects/Project_Deliverables__c.object
<CustomObject>
    <fields>
        <fullName>Additional_Comments__c</fullName>
        <label>Additional Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Complexity__c</fullName>
        <label>Complexity</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Deal_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Configured</fullName>
                </value>
                <value>
                    <fullName>Tailored</fullName>
                </value>
                <value>
                    <fullName>Complex</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Deal_Type__c</fullName>
        <label>Deal Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <controllingField>PS_Offering__c</controllingField>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>1:1 Assessment</fullName>
                </value>
                <value>
                    <fullName>1:1 Assessment Feedback Session</fullName>
                </value>
                <value>
                    <fullName>1:1 Developmental Feedback Session</fullName>
                </value>
                <value>
                    <fullName>1:1 Development Assessment</fullName>
                </value>
                <value>
                    <fullName>360</fullName>
                </value>
                <value>
                    <fullName>360 System</fullName>
                </value>
                <value>
                    <fullName>Advisory Services</fullName>
                </value>
                <value>
                    <fullName>Aspiring Minds</fullName>
                </value>
                <value>
                    <fullName>Assessment Centre</fullName>
                </value>
                <value>
                    <fullName>Assessment For Development</fullName>
                </value>
                <value>
                    <fullName>Assessment For Selection</fullName>
                </value>
                <value>
                    <fullName>Business Impact Study</fullName>
                </value>
                <value>
                    <fullName>Business Outcome Studies</fullName>
                </value>
                <value>
                    <fullName>Business Outcome Study</fullName>
                </value>
                <value>
                    <fullName>Business Value Summary</fullName>
                </value>
                <value>
                    <fullName>CEB Enterprise Leadership Academy</fullName>
                </value>
                <value>
                    <fullName>CEB Enterprise Leadership Activation</fullName>
                </value>
                <value>
                    <fullName>CEB Enterprise Leadership Solution</fullName>
                </value>
                <value>
                    <fullName>CEB HiPo Solution</fullName>
                </value>
                <value>
                    <fullName>CEB HiPo Solution With Nomination Survey</fullName>
                </value>
                <value>
                    <fullName>Client Custom Assessment</fullName>
                </value>
                <value>
                    <fullName>Coaching</fullName>
                </value>
                <value>
                    <fullName>Competency Design</fullName>
                </value>
                <value>
                    <fullName>Competency Design / Job Analysis</fullName>
                </value>
                <value>
                    <fullName>Custom Norm</fullName>
                </value>
                <value>
                    <fullName>Custom Report</fullName>
                </value>
                <value>
                    <fullName>Dashboards</fullName>
                </value>
                <value>
                    <fullName>Development Centre</fullName>
                </value>
                <value>
                    <fullName>Development Coach</fullName>
                </value>
                <value>
                    <fullName>Digital Readiness</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Number__c</fullName>
        <label>Number</label>
        <precision>16</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PS_Offering__c</fullName>
        <label>PS Offering</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Outsourced Assessment</fullName>
                </value>
                <value>
                    <fullName>Training</fullName>
                </value>
                <value>
                    <fullName>Product Consulting</fullName>
                </value>
                <value>
                    <fullName>Solutions Consulting</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Solution Analytics</fullName>
                    <isActive>false</isActive>
                    <label>Solution Analytics</label>
                </value>
                <value>
                    <fullName>Subscription Support</fullName>
                    <isActive>false</isActive>
                    <label>Subscription Support</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>ProjectObject__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Project</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>ProjectObject__c</referenceTo>
        <relationshipLabel>Project Deliverables</relationshipLabel>
        <relationshipName>Project_Deliverables</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Project Deliverable</label>
    <nameField>
        <displayFormat>PD-{0000000}</displayFormat>
        <label>Project Deliverables</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Deliverables</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ProjectObject__c.object
<CustomObject>
    <description>Used for PSA work</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Billing_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Projects (Billing Contact)</relationshipLabel>
        <relationshipName>Projects1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <lookupFilter>
            <active>false</active>
            <errorMessage>Contact with this name either does not exist or does not belong to the selected Account.</errorMessage>
            <filterItems>
                <field>Contact.Account.Id</field>
                <operation>equals</operation>
                <valueField>$Source.Account__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Deliverables__c</fullName>
        <label>Project Deliverables</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Manager</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>User.Is_Project_Manager__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>$User.Id</field>
                <operation>equals</operation>
                <value>0054G00000CSIBq</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Name__c</fullName>
        <label>Project Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Status__c</fullName>
        <label>Project Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Initiation</fullName>
                </value>
                <value>
                    <fullName>Planning</fullName>
                </value>
                <value>
                    <fullName>Executing</fullName>
                </value>
                <value>
                    <fullName>Closing</fullName>
                </value>
                <value>
                    <fullName>Closed/Delivered</fullName>
                </value>
                <value>
                    <fullName>Closed/Cancelled</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Live</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project</label>
    <nameField>
        <displayFormat>P{000000}</displayFormat>
        <label>Project Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <recordTypes>
        <fullName>Project</fullName>
        <active>true</active>
        <label>Project</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/RevenueAttribution__c.object
<CustomObject>
    <description>T&amp;E module</description>
    <fields>
        <fullName>Attribution_Days__c</fullName>
        <inlineHelpText>Maximum two digits allowed</inlineHelpText>
        <label>Attribution Days</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Attribution_Month2__c</fullName>
        <formula>Attribution_Period__r.Month__c</formula>
        <label>Attribution Month</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Attribution_Month_Number__c</fullName>
        <formula>CASE(Attribution_Month2__c ,&apos;Jan&apos;,1,&apos;Feb&apos;,2,&apos;Mar&apos;,3,&apos;Apr&apos;,4,&apos;May&apos;,5,&apos;Jun&apos;,6,&apos;Jul&apos;,7,&apos;Aug&apos;,8,&apos;Sep&apos;,9,&apos;Oct&apos;,10,&apos;Nov&apos;,11,&apos;Dec&apos;,12,&apos;null&apos;,0,0)</formula>
        <label>Attribution Month Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Attribution_Rate__c</fullName>
        <label>Attribution Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Attribution_Value__c</fullName>
        <formula>(Attribution_Days__c ) * ( Attribution_Rate__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Attribution Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Attribution_Year2__c</fullName>
        <formula>Attribution_Period__r.Year__c</formula>
        <label>Attribution Year</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Consultant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Consultant</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Attributions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>ProjectObject__c</referenceTo>
        <relationshipLabel>Attributions</relationshipLabel>
        <relationshipName>Attributions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Timesheet_Hours__c</fullName>
        <label>Timesheet Hours</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Attribution</label>
    <nameField>
        <displayFormat>ATTR1{00000}</displayFormat>
        <label>Attribution Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attributions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/Attribution_Tester.cls
@isTest(seeAllData=True)
private class Attribution_Tester {

  static testmethod void testTriggers()
  {
    List<RevenueAttribution__c> attributions;
    
    attributions = insertAttributions(null);
            
    updateAttributions(attributions);
        
    //deleteAttributions(attributions);
    
    //testAttributionListViewController();
  }
  static testmethod void testTriggers1()
  {
    List<RevenueAttribution__c> attributions;
    
    attributions = insertAttributions(null);
    updateAttributions(attributions);
     Test.startTest();   
    deleteAttributions(attributions);
    testAttributionListViewController();
      RevenueAttribution__c rec = [SELECT Id ,Name,Attribution_Month_Number__c,Project__c, Consultant__c,  Project__r.Name,Project__r.Project_Name__c,Attribution_Month2__c,CurrencyIsoCode,Attribution_Year2__c,Attribution_Days__c,Attribution_Rate__c,Attribution_Value__c,Timesheet_Hours__c FROM RevenueAttribution__c WHERE Consultant__c ='005D0000008jUdpIAE' AND Attribution_Year2__c='2024' AND Attribution_Month2__c='Sep' ORDER BY Attribution_Year2__c DESC, Attribution_Month_Number__c DESC, Project__r.Name DESC limit 1];
     Attribution_ListView_Controller cls = new Attribution_ListView_Controller();
      cls.TotalAttributionValue = 0;
      cls.TotalAttributionDays = 0;
      system.debug('Priyank'+rec.Attribution_Value__c);
       cls.UpdateTotals(rec);
    Test.stopTest();
  }
  
  static void testAttributionListViewController()
  {
    Attribution_ListView_Controller controller = new Attribution_ListView_Controller();
    controller.selectMonth = 9;
    controller.selectYear = 2024;
    controller.getAttributions();
    controller.selectMonth = 0;
    controller.Go();
    controller.getAttributions();
    controller.selectYear = 0;
    controller.Go();
    controller.getAttributions();
  }
      
  static List<RevenueAttribution__c> insertAttributions(String projectId)
   {
     system.debug('Attribution: Insert Started');
     Id userId = userinfo.getUserId(); 
     if(projectId==null)
     {
        //ProjectObject__c project = [SELECT Id,Contact__r.AccountId,Contact__r.ID from ProjectObject__c WHERE Project_Manager__c=:userId LIMIT 1 ];
        //edited by saloni chhabra on 4/9/2015
       ProjectObject__c project = [SELECT Id,Contact__r.AccountId,Contact__r.ID from ProjectObject__c WHERE Project_Status__c =: 'In Progress' LIMIT 1 ];
       Project_Deliverables__c objPD = new Project_Deliverables__c();
        objPD.PS_Offering__c = 'Outsourced Assessment';
        objPD.Project__c=project.id;
        objPD.Number__c=10;
        objPD.Deal_Type__c='Assessment for Selection';
        objPD.Complexity__c= 'Tailored';
        objPD.Additional_Comments__c= 'Test Comments';
        insert objPD;
       project.Account__c = project.Contact__r.AccountId;
       project.Contact__c = project.Contact__r.ID;
       project.Billing_Contact__c = project.Contact__r.ID;
       update project;
       projectId = project.Id; 
     }
     Id consultantId = [SELECT Id FROM User WHERE PSA_Role__c='PSA Lead' and Name='Tracy Shen' LIMIT 1].Id;
     
     List<RevenueAttribution__c> attributions = new List<RevenueAttribution__c>();
     List<Milestone_Period__c> MPlist = [Select id,name from Milestone_Period__c where Financial_Period_Closed__c=false limit 1]; //edited by saloni chhabra on 4/9/2015
      for(Integer i=0;i<20;i++)
      {
        RevenueAttribution__c attribution = new RevenueAttribution__c();
        attribution.Project__c = projectId;
       // attribution.Attribution_Month2__c = 'Jan';
       // attribution.Attribution_Year2__c = '2009';
        attribution.Attribution_Days__c = 12;
        attribution.Attribution_Rate__c = 50;
        attribution.Consultant__c = '005D0000008jUdpIAE';
        attribution.CurrencyIsoCode = 'INR';
        //edited by saloni chhabra on 4/9/2015 starts here
        if(MPlist.size()>0)    
        attribution.Attribution_Period__c = MPlist[0].id;
        //edited by saloni chhabra on 4/9/2015 ends here
        attributions.add(attribution);
      }
      
      insert attributions;
      return attributions;
   }
   
   static void updateAttributions(List<RevenueAttribution__c> attributions)
   {
     
     for(RevenueAttribution__c attribution: attributions)
     attribution.Attribution_Rate__c = 60;
     update attributions;
       
   }
   
   static void deleteAttributions(List<RevenueAttribution__c> attributions)
   {
       delete attributions;
   }
   
    static testmethod void ContractAccountHelpertester(){
        List<Id> ids = new List<Id>();
        for (Contract c : [SELECT Id FROM Contract LIMIT 10]) ids.add(c.Id);
        ContractAccountHelper.getAccountNames(ids);
    }
}