force-app/main/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Original_Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Variation Contracts</relationshipLabel>
        <relationshipName>Variation_Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

objects/Milestone__c.object
<CustomObject>
    <description>An object to record Milestones that can be signed by the PM Agent for revenue recognition</description>
    <fields>
        <fullName>Is_Signed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Signed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>ProjectObject__c</referenceTo>
        <relationshipLabel>Milestones</relationshipLabel>
        <relationshipName>Milestones</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Milestone</label>
    <nameField>
        <displayFormat>MS{00000}</displayFormat>
        <label>Milestone Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Milestones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/objects/Order.object
<CustomObject>
    <fields>
        <fullName>Order_Year__c</fullName>
        <label>Order Year</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

force-app/main/objects/OrderItem.object
<CustomObject>
    <fields>
        <fullName>Basis_of_Fees__c</fullName>
        <label>Basis of Fees</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Applications</fullName>
                </value>
                <value>
                    <fullName>Assessments and Reports</fullName>
                </value>
                <value>
                    <fullName>Candidates</fullName>
                </value>
                <value>
                    <fullName>Full-Time Equivalents (FTEs)</fullName>
                </value>
                <value>
                    <fullName>Participants</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Units</fullName>
                </value>
                <value>
                    <fullName>CPS Days</fullName>
                </value>
                <value>
                    <fullName>LPS Days</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Invoice_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Invoice Request #</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Project__c</field>
                <operation>equals</operation>
                <valueField>Project_Invoice__c.Project__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Project_Invoice__c</referenceTo>
        <relationshipLabel>Order Products</relationshipLabel>
        <relationshipName>Order_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Number_of_Services__c</fullName>
        <label>Number of Service Deliveries</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Order_Status__c</fullName>
        <description>This formula is used in OrderProduct Related List on the Project</description>
        <formula>IF(TEXT(Order.Status) = &apos;In Approval&apos;, &apos;Under Review&apos;, TEXT(Order.Status))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Order Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Package__c</fullName>
        <label>Offering Details</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Graduate Essential</fullName>
                </value>
                <value>
                    <fullName>Graduate Advanced</fullName>
                </value>
                <value>
                    <fullName>Graduate Ultimate</fullName>
                </value>
                <value>
                    <fullName>Volume Essential</fullName>
                </value>
                <value>
                    <fullName>Volume Advanced</fullName>
                </value>
                <value>
                    <fullName>Apprentice Essential</fullName>
                </value>
                <value>
                    <fullName>Tech Essential</fullName>
                </value>
                <value>
                    <fullName>Tech Advanced</fullName>
                </value>
                <value>
                    <fullName>Managerial Essential</fullName>
                </value>
                <value>
                    <fullName>Managerial Advanced</fullName>
                </value>
                <value>
                    <fullName>Managerial Ultimate</fullName>
                </value>
                <value>
                    <fullName>Video Essential</fullName>
                </value>
                <value>
                    <fullName>Video Advanced</fullName>
                </value>
                <value>
                    <fullName>Video Ultimate</fullName>
                </value>
                <value>
                    <fullName>Professional Essential</fullName>
                </value>
                <value>
                    <fullName>Professional Advanced</fullName>
                </value>
                <value>
                    <fullName>Professional Ultimate</fullName>
                </value>
                <value>
                    <fullName>Product</fullName>
                </value>
                <value>
                    <fullName>Mobilize Essential</fullName>
                </value>
                <value>
                    <fullName>Mobilize Advanced</fullName>
                </value>
                <value>
                    <fullName>Mobilize Ultimate</fullName>
                </value>
                <value>
                    <fullName>Sales Transformation Hiring Essential</fullName>
                </value>
                <value>
                    <fullName>Sales Transformation Hiring Advanced</fullName>
                </value>
                <value>
                    <fullName>Sales Transformation Hiring Ultimate</fullName>
                </value>
                <value>
                    <fullName>Sales Transformation Review Essential</fullName>
                </value>
                <value>
                    <fullName>Sales Transformation Review Advanced</fullName>
                </value>
                <value>
                    <fullName>Sales Transformation Review Ultimate</fullName>
                </value>
                <value>
                    <fullName>Service</fullName>
                </value>
                <value>
                    <fullName>OA 1:1 Essential</fullName>
                </value>
                <value>
                    <fullName>OA 1:1 Advanced</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Platform__c</fullName>
        <label>Platform</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>iAssess</fullName>
                </value>
                <value>
                    <fullName>MFS</fullName>
                </value>
                <value>
                    <fullName>Talent Central</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>ProjectObject__c</referenceTo>
        <relationshipLabel>Order Products</relationshipLabel>
        <relationshipName>Order_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Proposition__c</fullName>
        <label>Use-case</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Volume Hiring</fullName>
                </value>
                <value>
                    <fullName>Technology Hiring</fullName>
                </value>
                <value>
                    <fullName>Managerial Hiring</fullName>
                </value>
                <value>
                    <fullName>Senior Leadership / Executive Hiring </fullName>
                </value>
                <value>
                    <fullName>Professional Hiring</fullName>
                </value>
                <value>
                    <fullName>Talent Management</fullName>
                </value>
                <value>
                    <fullName>Early Careers Hiring</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Service_End_Date__c</fullName>
        <label>PS Service End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Source_of_PS_Scoping__c</fullName>
        <label>Source of PS Scoping</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>E2E Scoping Tool</fullName>
                </value>
                <value>
                    <fullName>Other Existing Pricing Calculator</fullName>
                </value>
                <value>
                    <fullName>Other Scoping Template</fullName>
                </value>
                <value>
                    <fullName>None Available</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Total_Price_PS_Items__c</fullName>
        <formula>IF(ISPICKVAL(Order.Status, &apos;Cancelled&apos;) ,0,Total_Price__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Price (PS Items)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
</CustomObject>

objects/Project_Invoice__c.object
<CustomObject>
    <description>Represents the invoice generated for the Time &amp; Expenses of a Project.</description>
    <fields>
        <fullName>Project__c</fullName>
        <description>Project to which this invoice belongs</description>
        <label>Project</label>
        <referenceTo>ProjectObject__c</referenceTo>
        <relationshipLabel>Invoice Requests</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Invoice Request</label>
    <nameField>
        <displayFormat>Inv{000000}</displayFormat>
        <label>Invoice Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ProjectObject__c.object
<CustomObject>
    <description>Used for PSA work</description>
    <fields>
        <fullName>Order_Status__c</fullName>
        <formula>TEXT( Order_Header_Number__r.Status )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Contract Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Platform__c</fullName>
        <label>Platform</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>P41</fullName>
                </value>
                <value>
                    <fullName>SODA</fullName>
                </value>
                <value>
                    <fullName>DSPS</fullName>
                </value>
                <value>
                    <fullName>Nacho</fullName>
                </value>
                <value>
                    <fullName>MFS</fullName>
                </value>
                <value>
                    <fullName>OAS</fullName>
                </value>
                <value>
                    <fullName>ORS</fullName>
                </value>
                <value>
                    <fullName>Values@work</fullName>
                </value>
                <value>
                    <fullName>CCQ</fullName>
                </value>
                <value>
                    <fullName>ASO Stand-alone</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project</label>
    <nameField>
        <displayFormat>P{000000}</displayFormat>
        <label>Project Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <recordTypes>
        <fullName>Project</fullName>
        <active>true</active>
        <label>Project</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/objects/PS_Order_Product__c.object
<CustomObject>
    <fields>
        <fullName>Invoice_Request__c</fullName>
        <label>Invoice Request</label>
        <referenceTo>Project_Invoice__c</referenceTo>
        <relationshipLabel>PS Order Products</relationshipLabel>
        <relationshipName>PS_Order_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Order_Product__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Order Product</label>
        <referenceTo>OrderItem</referenceTo>
        <relationshipLabel>PS Order Products</relationshipLabel>
        <relationshipName>PS_Order_Products</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Package__c</fullName>
        <formula>TEXT( Order_Product__r.Package__c)</formula>
        <label>Solution</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Platform__c</fullName>
        <formula>TEXT(Order_Product__r.Platform__c)</formula>
        <label>Platform</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Proposition__c</fullName>
        <formula>TEXT( Order_Product__r.Proposition__c)</formula>
        <label>Use-case</label>
        <type>Text</type>
    </fields>
    <label>PS Order Product</label>
    <nameField>
        <displayFormat>PS-OP-{0000}</displayFormat>
        <label>PS Order Product Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PS Order Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/OrderProductsOnProjectController.cls
public class OrderProductsOnProjectController {
    public List<orderitem> orderItemList{get;set;}
    public boolean selected{get;set;}
    public String Projectid{get;set;}
    public boolean MilestoneSigned{get;set;}
    public List<wrapOrderItem> wrapOrderItemList {get; set;}
    public List<orderitem> selectedOrderItem{get;set;}
    public List<orderitem> ordelinesToAdd{get;set;}
    public List<orderitem> ordelinesToDelete{get;set;}
    public List<PS_Order_Product__c> RelatedPSOrderProducts{get;set;}
    public List<Order> OrderList{get;set;}
    public List<Contract> ContractList{get;set;}
    public Contract OriginalContract{get;set;}
    public boolean HasAccess{get;set;}
    public OrderProductsOnProjectController() {
        Projectid=ApexPages.currentPage().getParameters().get('Project');
        System.debug('This is project id: '+ApexPages.currentPage().getParameters().get('Project'));
        if(ApexPages.currentPage().getParameters().get('Contract')=='')
        {
            wrapOrderItemList=null;
        }
        else{
            OriginalContract = [Select id from Contract where ContractNumber=:ApexPages.currentPage().getParameters().get('Contract')];
            List<Milestone__c> SignedMilestones = [select id from Milestone__c where Project__c=:ApexPages.currentPage().getParameters().get('Project') and Is_Signed__c=True];
            System.debug('This is count '+SignedMilestones.size());
            if(SignedMilestones.size()>0)
                MilestoneSigned=True;
            else
                MilestoneSigned=False;
            
            if(wrapOrderItemList==null){
                wrapOrderItemList=new List<wrapOrderItem>();
                System.debug('This is original contract'+OriginalContract);
                try{
                    ContractList = [select id from contract where Original_Contract__r.id=:OriginalContract.id];
                }
                catch(DmlException e){
                }
                ContractList.add(OriginalContract);
                System.debug('This is contract list '+ContractList);
                if(ContractList!=null){
                    OrderList=[select id from Order where Contract.id In :ContractList];
                }
                System.debug('Orders are '+OrderList.size());
                if(OrderList!=null){
                    orderItemList=[select id,Project__c,Product2.name,Quantity,UnitPrice,Source_of_PS_Scoping__c,Order.OrderNumber,Invoice_Request__r.Name,
                                   Platform__c,Proposition__c,Package__c,TotalPrice,Basis_of_Fees__c,Service_End_Date__c,Order.Order_year__c,
                                   Number_of_Services__c,
                                   Total_Price_PS_Items__c,
                                   Order_Status__c,
                                   Order_Form_Category__c,
                                   Solution__c//Changes added by Joana (SSE-16464)
                                   from OrderItem where OrderID IN :OrderList and Product2.Revenue_Category__c='Professional Services' AND
                                   ((Order_Form_Category__c !='Advisory Services' AND Project__c=null) OR Project__c=:ApexPages.currentPage().getParameters().get('Project'))];
                }
                System.debug('Size is '+orderItemList.size());
                System.debug('Is null '+orderItemList);
                if(orderItemList.size()!=0)
                {
                    For(orderitem op:orderItemList)
                        wrapOrderItemList.add(new wrapOrderItem(op));  
                } 
                else
                    wrapOrderItemList=null;  
            }
        }
        Id profileId=userinfo.getProfileId();
            id userid = UserInfo.getUserId();
            String GCSCCXTS;
            String profileName=[Select Id,Name from Profile where Id=:profileId].Name;
            List<PermissionSetAssignment> assignmentRecord = [SELECT PermissionSetGroup.DeveloperName FROM PermissionSetAssignment WHERE PermissionSetGroup.DeveloperName = 'GCSC_CXTS' AND Assignee.id=: userid];

            if(profileName=='Professional Services'){
                HasAccess = true;
                system.debug('has access '+HasAccess);
            }
            else if(!assignmentRecord.isEmpty())
            {
                HasAccess = false;
                system.debug('has access GCSC '+HasAccess);
            }
            else{
                HasAccess = schema.sObjectType.Order.isUpdateable();
            }
            system.debug('has access '+HasAccess);
    }
    public PageReference AddProducts(){
        selectedOrderItem = new List<orderitem>();
        ordelinesToAdd= new List<orderitem>();
        ordelinesToDelete= new List<orderitem>(); 
        RelatedPSOrderProducts=new List<PS_Order_Product__c>();
        Boolean showerror=false;
        For(wrapOrderItem rec:wrapOrderItemList)
        {
            if(rec.selected==true){
                rec.Orderitemrec.Project__c=Projectid;
                ordelinesToAdd.add(rec.Orderitemrec);
            }
            else
            {
                rec.Orderitemrec.Project__c=null;
                rec.Orderitemrec.Invoice_Request__c=null;
                ordelinesToDelete.add(rec.Orderitemrec);
            }
        }
        if(ordelinesToDelete.size()>0)
        {
            RelatedPSOrderProducts=[select Id,Invoice_Request__r.Status__c,Order_Product__c from PS_Order_Product__c where Order_Product__c IN :ordelinesToDelete];
            /*for(PS_Order_Product__c psprod:RelatedPSOrderProducts)
{
if(psprod.Invoice_Request__r.Status__c=='Processed')
{
showerror=true;
break;
}
else 
continue;  
}*/
        }
        if(RelatedPSOrderProducts.size()>0)
        {
            ApexPages.AddMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'One of the order product is linked to an associated invoice request, so it cant be removed from the Project.'));
            return null;
        }
        else
        {
            if(ordelinesToAdd.size()>0)
                update ordelinesToAdd;
            update ordelinesToDelete;
            UpdateProjectRollUpFields();
            ApexPages.AddMessage(new ApexPages.Message(ApexPages.Severity.CONFIRM,'Order Products added Successfully.Thank you!'));
            PageReference pg = new PageReference('/'+ApexPages.currentPage().getParameters().get('Project'));
            pg.setRedirect(true);
            return pg;
        }
        
    }
    
    public void UpdateProjectRollUpFields(){
        ProjectObject__c Prj=[select id,Order_Products_Count__c,Scoped_CPS_days_RollUp__c,
                              Scoped_LPS_days_RollUp__c,Total_Orderline_Value_RollUp__c from ProjectObject__c where Id=:Projectid];
        List<OrderItem> OrdProdLst=[select id,TotalPrice,Basis_of_Fees__c,Quantity from OrderItem where Project__c=:Prj.Id and Order.Status != 'Cancelled'];
        System.debug('This is order product list '+OrdProdLst.size());   
        if(OrdProdLst!=null && !OrdProdLst.isEmpty()){
            Prj.Order_Products_Count__c=OrdProdLst.size();
        }else{
            Prj.Order_Products_Count__c=0;
        }
        Prj.Scoped_CPS_days_RollUp__c=0;
        Prj.Scoped_LPS_days_RollUp__c=0;
        Prj.LPS_scoped_value__c=0;
        Prj.CPS_scoped_value__c=0;
        Prj.Total_Orderline_Value_RollUp__c=0;
        //update Prj;
        for(OrderItem Op:OrdProdLst){
            if(op.Basis_of_Fees__c=='CPS Days')
            {
                Prj.Scoped_CPS_days_RollUp__c = Prj.Scoped_CPS_days_RollUp__c+ Op.Quantity;
                Prj.CPS_scoped_value__c = Prj.CPS_scoped_value__c + Op.TotalPrice;
            }
            if(op.Basis_of_Fees__c=='LPS Days'){
                Prj.Scoped_LPS_days_RollUp__c = Prj.Scoped_LPS_days_RollUp__c+ Op.Quantity;  
                Prj.LPS_scoped_value__c = Prj.LPS_scoped_value__c + Op.TotalPrice; 
            }
            Prj.Total_Orderline_Value_RollUp__c =Prj.Total_Orderline_Value_RollUp__c+ Op.TotalPrice;
            
        }
        update Prj;
    }
    
    public class wrapOrderItem {
        public OrderItem Orderitemrec {get; set;}
        public Boolean selected {get; set;}
        public wrapOrderItem(OrderItem a) {
            Orderitemrec = a;
            if(a.Project__c==null)
                selected = false;
            else
                selected = true;
        }
    }
}