force-app/main/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Days_remaining_from_annual_subscription__c</fullName>
        <label>Days remaining from annual sub(Legacy)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Earliest_Start_Date_Plus_Leap_Year__c</fullName>
        <label>Earliest StartDate Plus LeapYear(Legacy)</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Earliest_Start_Date__c</fullName>
        <label>Earliest Start Date(Legacy)</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Renewal_Date__c</fullName>
        <label>Renewal Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Renewal_Opportunity__c</fullName>
        <description>Link  to Renewal Opportunity  for this order.</description>
        <label>Renewal Opportunity(Legacy)</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Running_total_of_non_subscription_amount__c</fullName>
        <label>Running total of non-sub amount(Legacy)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Running_total_of_subscription_amount__c</fullName>
        <label>Running total of sub amt(Legacy)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Running_total_of_subscription_days__c</fullName>
        <label>Running total of sub days(Legacy)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

objects/Contract_Line__c.object
<CustomObject>
    <description>Order Management</description>
    <fields>
        <fullName>Contract__c</fullName>
        <label>Order</label>
        <referenceTo>Contract</referenceTo>
        <relationshipName>Contract_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Duration_Day_Amount__c</fullName>
        <formula>IF(  ISPICKVAL(Price_per__c , &quot;One-off&quot;) , Price__c /  Duration_days__c,0 )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Duration Day Amount</label>
        <precision>18</precision>
        <scale>12</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Duration_days__c</fullName>
        <formula>(End_Date__c -  Start_Date__c) + 1</formula>
        <label>Duration days</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IM_Lookup_Code__c</fullName>
        <label>Order Line Item</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Order_Method__c</controllingField>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>360 Platform Set up</fullName>
                </value>
                <value>
                    <fullName>360 Subscription</fullName>
                </value>
                <value>
                    <fullName>Advisory Services Subscription</fullName>
                </value>
                <value>
                    <fullName>AM Aptitude (In Arrears)</fullName>
                </value>
                <value>
                    <fullName>AM Coding (In Arrears)</fullName>
                </value>
                <value>
                    <fullName>AM Generic (In Arrears)</fullName>
                </value>
                <value>
                    <fullName>AM Language (In Arrears)</fullName>
                </value>
                <value>
                    <fullName>AM Personal &amp; Behavioural (In Arrears)</fullName>
                </value>
                <value>
                    <fullName>AM Pool Hiring (In Arrears)</fullName>
                </value>
                <value>
                    <fullName>AM Proctoring (In Arrears)</fullName>
                </value>
                <value>
                    <fullName>AM Product Subscription</fullName>
                </value>
                <value>
                    <fullName>AM Professional Services</fullName>
                </value>
                <value>
                    <fullName>AM Skills: Analytics (In Arrears)</fullName>
                </value>
                <value>
                    <fullName>AM Skills: Banking and Financial Serv (In Arrears)</fullName>
                </value>
                <value>
                    <fullName>AM Skills: Customer Service, Contact Center and BPO (In Arrears)</fullName>
                </value>
                <value>
                    <fullName>AM Skills: Engineering (In Arrears)</fullName>
                </value>
                <value>
                    <fullName>AM Skills: Finance and Accounting (In Arrears)</fullName>
                </value>
                <value>
                    <fullName>AM Skills: Healthcare, Pharma and Life Sciences (In Arrears)</fullName>
                </value>
                <value>
                    <fullName>AM Skills: Human Resources, Marketing and Operations (In Arrears)</fullName>
                </value>
                <value>
                    <fullName>AM Skills: MS Office (In Arrears)</fullName>
                </value>
                <value>
                    <fullName>AM Skills: Sales and Business Development (In Arrears)</fullName>
                </value>
                <value>
                    <fullName>AM Skills: Sciences (In Arrears)</fullName>
                </value>
                <value>
                    <fullName>AM Skills: Technology (In Arrears)</fullName>
                </value>
                <value>
                    <fullName>AM Skills: Tourism and Hospitality (In Arrears)</fullName>
                </value>
                <value>
                    <fullName>AM Video (In Arrears)</fullName>
                </value>
                <value>
                    <fullName>Application Analytics Subscription</fullName>
                </value>
                <value>
                    <fullName>Bureau</fullName>
                </value>
                <value>
                    <fullName>Candidate Support – Bronze</fullName>
                </value>
                <value>
                    <fullName>Candidate Support for Subscription</fullName>
                </value>
                <value>
                    <fullName>Candidate Support –  Gold</fullName>
                </value>
                <value>
                    <fullName>Consulting</fullName>
                </value>
                <value>
                    <fullName>Royalties</fullName>
                </value>
                <value>
                    <fullName>Site set up</fullName>
                </value>
                <value>
                    <fullName>Units in advance</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Line Price</label>
        <precision>11</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Price_per__c</fullName>
        <label>Price per</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Unit</fullName>
                </value>
                <value>
                    <fullName>Applicant</fullName>
                </value>
                <value>
                    <fullName>Sitting</fullName>
                </value>
                <value>
                    <fullName>Job</fullName>
                </value>
                <value>
                    <fullName>One-off</fullName>
                </value>
                <value>
                    <fullName>Assessment</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Order Line</label>
    <nameField>
        <displayFormat>CLN{0000000}</displayFormat>
        <label>Order Line</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Line</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Business_Type__c</fullName>
        <description>Choose the Opportunity Type that best describes the type of business pursued.  
Reboost should only be used with In-Advance clients. 
Cross-sell is simply New Business with a client that has a current commercial relationship.</description>
        <label>Opportunity Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Expansion</fullName>
                </value>
                <value>
                    <fullName>Renewal</fullName>
                </value>
                <value>
                    <fullName>Debooking</fullName>
                    <label>Debooking / Adjustment</label>
                </value>
                <value>
                    <fullName>Extension</fullName>
                </value>
                <value>
                    <fullName>In Arrears</fullName>
                </value>
                <value>
                    <fullName>In Advance</fullName>
                </value>
                <value>
                    <fullName>Managed Services</fullName>
                </value>
                <value>
                    <fullName>Professional Services: non-subscription</fullName>
                </value>
                <value>
                    <fullName>Top Up / Addition</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Days_remaining_from_annual_subscription__c</fullName>
        <label>Days remaining from annual subs (Legacy)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Earliest_Start_Date_Plus_Leap_Year__c</fullName>
        <label>Earliest Start Date Plus Leap Year</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Earliest_Start_Date__c</fullName>
        <label>Earliest Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Renewal_Date__c</fullName>
        <inlineHelpText>This date is calculated from the Contract End Date + 1 day and signifies the true date that the next Renewal is due to start on.</inlineHelpText>
        <label>Renewal Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Renewal_Opportunity__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Auto-Created Renewal</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Running_total_of_non_subscription_amount__c</fullName>
        <label>Running total of non-subs amount(Legacy)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Running_total_of_subscription_amount__c</fullName>
        <label>Running total of subs amount (Legacy)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
</CustomObject>

classes/ContractLineTriggerManager_3.cls
/**************************************************************************************************************************************
CREATED BY :- Virendra Kumar
CREATED DATE :- 29-07-2019
DESCRIPTION :-  This class contains ContractLine trigger related functionalities :  after delete, after undelete(Renewable date logic and subscription field update)
***************************************************************************************************************************************/
public class ContractLineTriggerManager_3{
  // This method helps to calcualte renewale date and running total subscription field updates when respective field values are present in Custom setting.
  public static void Subscriptionfieldupdate_RenewabledateLogic(Set<Id> ContractLineNewList)
  {
   try{  
    //EACV order line items value
    Set<String> EACVvalues = Utility.getEACVvaluesforOrder();    
    List<string> subsIMCodeValues = Utility.getSubscriptionProductSequence();
    Date RenewalDate;
    Map<id,date> OpptyRenewalDate = new Map<id,date>();
    Set<id> OpptyId = new Set<id>();    
   
    //edited by Dimpy for SSE-2290 starts here
    Set<String> OliValuseFilter1 = Utility.getOrderLineItemValuesFilter1();
    Set<String> OliValuseFilter1_1 = Utility.getOrderLineItemValuesFilter1_1();
    Set<String> OliValuesFilter2= Utility.getOrderLineItemValuesFilter2();
    //edited by Dimpy for SSE-2290 ends here
    Map<Id,Contract> contractVsSubscriptionContractLineMap = new Map<Id,Contract>([SELECT id,Renewal_Opportunity__c,Days_remaining_from_annual_subscription__c,Running_total_of_non_subscription_amount__c,
                                                            Running_total_of_subscription_amount__c,Running_total_of_subscription_days__c,Earliest_Start_Date__c,Earliest_Start_Date_Plus_Leap_Year__c,
                                                            (Select id,Price_per__c ,Duration_days__c, Duration_Day_Amount__c,End_Date__c,Start_Date__c,Price__c,IM_Lookup_Code__c 
                                                            FROM Contract_Line_Items__r ORDER BY Start_Date__c asc) 
                                                            from Contract where id in :ContractLineNewList]);               
    
    if(contractVsSubscriptionContractLineMap!=null && contractVsSubscriptionContractLineMap.size()>0)
    {
        
        for(Contract contract:contractVsSubscriptionContractLineMap.values())
        {
            Map<string,List<date>> IMCodevalueandEndDateMap = new Map<string,List<date>>();
            
            contract.Days_remaining_from_annual_subscription__c = 365;
            Boolean isEarliestStartDateCalculated = false;
            contract.Running_total_of_subscription_amount__c = 0;
            contract.Running_total_of_subscription_days__c = 0;
            contract.Running_total_of_non_subscription_amount__c = 0;
            for(Contract_Line__c contractLine:contract.Contract_Line_Items__r)
            {
                //edited by Dimpy for SSE-2290
               // if(contractLine.IM_Lookup_Code__c=='Limited Subscription'  || contractLine.IM_Lookup_Code__c=='Unlimited Subscription')
               if(EACVvalues.contains(contractLine.IM_Lookup_Code__c) || contractLine.IM_Lookup_Code__c.contains('Subscription'))
                {
                    if(contractLine.Start_Date__c == null || contractLine.End_Date__c == null)
                        continue;
                        
                    if(contractLine.Duration_Days__c >=365)// edited by saloni chhabra on 4/24/2015
                    isEarliestStartDateCalculated = false;
                    if(!isEarliestStartDateCalculated)
                    {
                        contract.Earliest_Start_Date__c = contractLine.Start_Date__c;
                        contract.Earliest_Start_Date_Plus_Leap_Year__c = contractLine.Start_Date__c.addDays(366);
                        if(contract.Earliest_Start_Date__c.month() <= 2)
                        {
                            if(Date.isLeapYear(contract.Earliest_Start_Date__c.Year()))
                            {
                                contract.Days_remaining_from_annual_subscription__c = 366;
                            }
                        }
                        else if(contract.Earliest_Start_Date__c.month() > 2)
                        {
                            if(Date.isLeapYear(contract.Earliest_Start_Date_Plus_Leap_Year__c.Year()))
                            {
                                contract.Days_remaining_from_annual_subscription__c = 366;
                            }
                        }
                        isEarliestStartDateCalculated = true;
                    }
                    Double durationDaysAmount = 0;
                    if(contractLine.Price__c!=null && contractLine.Price_per__c == 'One-off')
                        durationDaysAmount = contractLine.Price__c / contractLine.Duration_days__c;
                    if(contract.Days_remaining_from_annual_subscription__c>0)
                    {
                        if(contract.Days_remaining_from_annual_subscription__c - contractLine.Duration_days__c >0 || contract.Days_remaining_from_annual_subscription__c - contractLine.Duration_days__c == 0)
                        {
                            contract.Running_total_of_subscription_amount__c+=contractLine.Duration_days__c*durationDaysAmount;
                            contract.Running_total_of_subscription_days__c+=contractLine.Duration_days__c;
                            contract.Days_remaining_from_annual_subscription__c = contract.Days_remaining_from_annual_subscription__c-contractLine.Duration_days__c;
                        }
                        else
                        {
                            contract.Running_total_of_subscription_amount__c+=contract.Days_remaining_from_annual_subscription__c*durationDaysAmount;
                            contract.Running_total_of_subscription_days__c+=contract.Days_remaining_from_annual_subscription__c;
                            contract.Days_remaining_from_annual_subscription__c = 0;
                            
                        }
                    }
                    else // edited by saloni chhabra on 4/24/2015
                    {
                        contract.Running_total_of_subscription_amount__c+=contractLine.Price__c;
                    }
                }
               // else if(contractLine.IM_Lookup_Code__c=='Units in advance' ||  contractLine.IM_Lookup_Code__c=='Other units'|| contractLine.IM_Lookup_Code__c=='Site set up'|| contractLine.IM_Lookup_Code__c=='LSI' || contractLine.IM_Lookup_Code__c=='P&P Materials' || contractLine.IM_Lookup_Code__c=='PCX units' || contractLine.IM_Lookup_Code__c=='SMH' || contractLine.IM_Lookup_Code__c=='SXH' || contractLine.IM_Lookup_Code__c=='Consulting' || contractLine.IM_Lookup_Code__c=='Royalties' || contractLine.IM_Lookup_Code__c=='Please refer to T&E invoice request' || contractLine.IM_Lookup_Code__c=='In-Company Training')
               ///edited by Dimpy for SSE-2290
               else if (OliValuseFilter1.contains(contractLine.IM_Lookup_Code__c) || OliValuseFilter1_1.contains(contractLine.IM_Lookup_Code__c))
               
                {
                    if(contractLine.Price__c!=null)
                        contract.Running_total_of_non_subscription_amount__c+=contractLine.Price__c;
                }
                
            }
            
            //Renewal Date Logic as per SSE-2720 starts here
            for(Contract_Line__c contractLine:contract.Contract_Line_Items__r)
                {
                    
                    if(subsIMCodeValues.contains(contractLine.IM_Lookup_Code__c))
                           {
                            if(IMCodevalueandEndDateMap.containsKey(contractLine.IM_Lookup_Code__c))
                            {
                                
                                IMCodevalueandEndDateMap.get(contractLine.IM_Lookup_Code__c).add(contractLine.End_Date__c);
                            }
                            else
                            {
                                List<date> orderLineEndDateList = new List<date>();
                                orderLineEndDateList.add(contractLine.End_Date__c);
                                IMCodevalueandEndDateMap.put(contractLine.IM_Lookup_Code__c,orderLineEndDateList);
                            }
                                
                        
                    }
                }
                
            RenewalDate = Renewal_Date_from_OrderLines.RenewalDate(IMCodevalueandEndDateMap);
            if(RenewalDate!= null)
            {
                if(contract.Renewal_Opportunity__c != null)
                {
                    
                    Integer lengthRemove = contract.Renewal_Opportunity__c.length()-18;
                    id Opptyidvalue = contract.Renewal_Opportunity__c.right(18);
                    if(Opptyidvalue != null)
                    {
                        OpptyRenewalDate.put(Opptyidvalue,RenewalDate);
                        OpptyId.add(Opptyidvalue);
                    }
                  }
            }
            //ends here
        }
        
        update contractVsSubscriptionContractLineMap.values();
    }
    
    //Renewal Date Logic as per SSE-2720 starts here
    if(OpptyId != null && OpptyRenewalDate != null)
    {
        List<Opportunity> LOppty = [Select id,Renewal_Opportunity__c,Business_Type__c,Renewal_Date__c from Opportunity where id in:OpptyId];
        for(Opportunity Opp:LOppty)
        {
            if(Opp.Renewal_Opportunity__c == true && Opp.Business_Type__c == 'Renewal')
            {
                if(Opp.Renewal_Date__c!= null) 
                {
                    if(Opp.Renewal_Date__c != OpptyRenewalDate.get(Opp.id))
                    {
                        Opp.Renewal_Date__c = OpptyRenewalDate.get(Opp.id);
                    }
                }
                else
                Opp.Renewal_Date__c = OpptyRenewalDate.get(Opp.id); 
            }
            system.debug('-->Opp.Renewal_Date__c <----'+Opp.Renewal_Date__c );
        }
        
        update LOppty;
    }
    }
    Catch(Exception e)
{
}
    
}


}