force-app/main/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Account_Region__c</fullName>
        <formula>Account.Region__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Region</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Final_Submission_Date_EST__c</fullName>
        <label>Submitted to OATs(Legacy)</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Last_Possible_Submission_Date_Daylight__c</fullName>
        <description>Calculates Final submission date with adding daylight saving value and used in calculating Last possible submission date field.</description>
        <label>Last Possible Submission Date Daylight</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Offering__c</fullName>
        <formula>BillingCity</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Offering</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity(Legacy)</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reboost_Opp_Error__c</fullName>
        <label>Reboost Opp Error</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Reboost_Opportunity__c</fullName>
        <label>Reboost Opportunity(Legacy)</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Renewal_Opp_Error__c</fullName>
        <description>Field is created to capture the error message which comes from back end Renewal Opp creation process.</description>
        <label>Renewal Opp Error</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Renewal_Opportunity__c</fullName>
        <description>Link  to Renewal Opportunity  for this order.</description>
        <label>Renewal Opportunity(Legacy)</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Submission_Offset__c</fullName>
        <label>Submission Offset</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

objects/Contract_Line__c.object
<CustomObject>
    <description>Order Management</description>
    <fields>
        <fullName>Contract__c</fullName>
        <label>Order</label>
        <referenceTo>Contract</referenceTo>
        <relationshipName>Contract_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IM_Lookup_Code__c</fullName>
        <label>Order Line Item</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Order_Method__c</controllingField>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>360 Platform Set up</fullName>
                </value>
                <value>
                    <fullName>360 Subscription</fullName>
                </value>
                <value>
                    <fullName>Advisory Services Subscription</fullName>
                </value>
                <value>
                    <fullName>AM Aptitude (In Arrears)</fullName>
                </value>
                <value>
                    <fullName>AM Coding (In Arrears)</fullName>
                </value>
                <value>
                    <fullName>AM Generic (In Arrears)</fullName>
                </value>
                <value>
                    <fullName>AM Language (In Arrears)</fullName>
                </value>
                <value>
                    <fullName>AM Personal &amp; Behavioural (In Arrears)</fullName>
                </value>
                <value>
                    <fullName>AM Pool Hiring (In Arrears)</fullName>
                </value>
                <value>
                    <fullName>AM Proctoring (In Arrears)</fullName>
                </value>
                <value>
                    <fullName>AM Product Subscription</fullName>
                </value>
                <value>
                    <fullName>AM Professional Services</fullName>
                </value>
                <value>
                    <fullName>AM Skills: Analytics (In Arrears)</fullName>
                </value>
                <value>
                    <fullName>AM Skills: Banking and Financial Serv (In Arrears)</fullName>
                </value>
                <value>
                    <fullName>AM Skills: Customer Service, Contact Center and BPO (In Arrears)</fullName>
                </value>
                <value>
                    <fullName>AM Skills: Engineering (In Arrears)</fullName>
                </value>
                <value>
                    <fullName>AM Skills: Finance and Accounting (In Arrears)</fullName>
                </value>
                <value>
                    <fullName>AM Skills: Healthcare, Pharma and Life Sciences (In Arrears)</fullName>
                </value>
                <value>
                    <fullName>AM Skills: Human Resources, Marketing and Operations (In Arrears)</fullName>
                </value>
                <value>
                    <fullName>AM Skills: MS Office (In Arrears)</fullName>
                </value>
                <value>
                    <fullName>AM Skills: Sales and Business Development (In Arrears)</fullName>
                </value>
                <value>
                    <fullName>AM Skills: Sciences (In Arrears)</fullName>
                </value>
                <value>
                    <fullName>AM Skills: Technology (In Arrears)</fullName>
                </value>
                <value>
                    <fullName>AM Skills: Tourism and Hospitality (In Arrears)</fullName>
                </value>
                <value>
                    <fullName>AM Video (In Arrears)</fullName>
                </value>
                <value>
                    <fullName>Application Analytics Subscription</fullName>
                </value>
                <value>
                    <fullName>Bureau</fullName>
                </value>
                <value>
                    <fullName>Candidate Support – Bronze</fullName>
                </value>
                <value>
                    <fullName>Candidate Support for Subscription</fullName>
                </value>
                <value>
                    <fullName>Candidate Support –  Gold</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Order Line</label>
    <nameField>
        <displayFormat>CLN{0000000}</displayFormat>
        <label>Order Line</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Line</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Offering__c</fullName>
        <description>This field has been created as a part of Nomenclature (SSE--113)</description>
        <inlineHelpText>Select the Offering(s) or Solution(s) that best define the product the client is buying.</inlineHelpText>
        <label>Offerings</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cognitive (Verify, G+ etc)</fullName>
                </value>
                <value>
                    <fullName>Cognitive Interactive (Verify Interactive)</fullName>
                </value>
                <value>
                    <fullName>OPQ</fullName>
                </value>
                <value>
                    <fullName>APTA</fullName>
                </value>
                <value>
                    <fullName>MQ</fullName>
                </value>
                <value>
                    <fullName>PJM</fullName>
                </value>
                <value>
                    <fullName>Language</fullName>
                </value>
                <value>
                    <fullName>Skills: Technology</fullName>
                </value>
                <value>
                    <fullName>Skills: non-Technology</fullName>
                </value>
                <value>
                    <fullName>JFA Standard</fullName>
                </value>
                <value>
                    <fullName>JFA Custom</fullName>
                </value>
                <value>
                    <fullName>SJT Standard</fullName>
                </value>
                <value>
                    <fullName>SJT Custom</fullName>
                </value>
                <value>
                    <fullName>Remote WorkQ</fullName>
                </value>
                <value>
                    <fullName>Coding Simulation (Automata)</fullName>
                </value>
                <value>
                    <fullName>Contact Center Simulation</fullName>
                </value>
                <value>
                    <fullName>Simulation - Others</fullName>
                </value>
                <value>
                    <fullName>Smart Interview: On Demand (Async Video Interview, AutoView)</fullName>
                </value>
                <value>
                    <fullName>Smart Interview: Live (Smart Meet, Live Interview)</fullName>
                </value>
                <value>
                    <fullName>Smart Interview: Live Coding</fullName>
                </value>
                <value>
                    <fullName>SHL Experiences</fullName>
                </value>
                <value>
                    <fullName>Candidate Engagement Portal</fullName>
                </value>
                <value>
                    <fullName>In person Assessment Centre</fullName>
                </value>
                <value>
                    <fullName>In person Development Centre</fullName>
                </value>
                <value>
                    <fullName>Virtual Assessment Centre</fullName>
                </value>
                <value>
                    <fullName>Virtual Development Centre</fullName>
                </value>
                <value>
                    <fullName>HiPo</fullName>
                </value>
                <value>
                    <fullName>Leader Edge</fullName>
                </value>
                <value>
                    <fullName>360</fullName>
                </value>
                <value>
                    <fullName>Surveys</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Renewal_Opportunity__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Auto-Created Renewal</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

force-app/main/objects/Order.object
<CustomObject>
    <fields>
        <fullName>Submission_Offset__c</fullName>
        <label>Submission Offset</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

classes/ContractTriggerManager_3.cls
/**************************************************************************************************************************************
CREATED BY :- PANKHURI JAIN
CREATED DATE :- 11-06-2019
DESCRIPTION :- This class contains Contract trigger related functionalities : before update (Renewal,Reboost,MTVR Logic)
***************************************************************************************************************************************/ 
global class ContractTriggerManager_3{
    
    //This method is responsible for Creating Renewal and Reboost Opportunity with MTVR Logic check..
    public static void RenewalReboostOppCreation(List<Contract> ContractsNewList, List<Contract> ContractsOldList){    
    //edited by saloni chhabra on 19/3/2015 as per SSE-148 starts  here
    date CloseDate;
    date ReboostMTVRStartDate;
    date earliestenddate;
    date earliestenddateMTVR;
    datetime earlieststartdate ;
    List<Date> EndDateList=new List<Date> ();
    boolean IsSubscriptionOrderLine=false;
    string oppID;
    List<string> ErrorMessage = new List<string>();
    List<string> ErrorMessagereboost = new List<string>();
    
    set<ID> OrderId  = new set<ID>();
    List<Contract_Line__c> OLlist;
    List<Contract_Line__c> OLlist1;
    List<Contract> Orderlistupdate;
    integer OLsubscription;
    List<date> OLstartdate = new List<date>();
    
    Set<String> AutoRenewalValues = Utility.getAutoRenewalfromOrder();
    List<string> subsIMCodeValues = Utility.getSubscriptionProductSequence();
    set<string> subsIMlookupValueSet = new set<string>();
    Set<string> ReboostProducts = Utility.getreboostProducts();
    system.debug('---->subsIMCodeValues <----'+subsIMCodeValues );
    
    for(String subsProdName : subsIMCodeValues){
        subsIMlookupValueSet.add(subsProdName);
    }
    for(Integer i=0;i<ContractsNewList.size();i++){
        OrderId.add(ContractsNewList[i].id);
    }
    if(OrderId.size()>0){ 
        OLlist = [Select id,name,CreatedDate,End_Date__c,Start_Date__c,IM_Lookup_Code__c,Contract__c from Contract_Line__c where Contract__c in:OrderId  ORDER BY Start_Date__c DESC,CreatedDate DESC];
    }
    
    list<Contract_Line__c> OLlistRenewal = new List<Contract_Line__c> ();
    list<Contract_Line__c> OLlistReeboost = new List<Contract_Line__c> ();
    
    for(Contract_Line__c OL : OLlist){
        if(OL.IM_Lookup_Code__c.contains('Subscription') || AutoRenewalValues.contains(OL.IM_Lookup_Code__c)){
            OLlistRenewal.add(OL);
        }
        if(ReboostProducts.contains(OL.IM_Lookup_Code__c)){
            OLlistReeboost.add(OL);
        }                           
    }
    for(Integer i=0;i<ContractsNewList.size();i++){
        Map<string,List<string>> IMCodevalueandDateMap = new Map<string,List<string>>();
        Map<string,List<date>> IMCodevalueandEndDateMap = new Map<string,List<date>>();
        Date OLStDate = null;
        Date OLEndDate = null;
        string orderLineDates = '';
            
        if(ContractsNewList[i].status=='Complete' && ContractsOldList[i].status !='Complete'){
            if(OLlistRenewal.size()>0){
                OLsubscription = OLlistRenewal.size();                               
                for(Contract_Line__c OL:OLlistRenewal){  
                    //added by Anjali to get the priority of IMLookupcode field values as per SSE-5112
                    for(integer j=0;j<subsIMCodeValues.size();j++){
                        if(OL.IM_Lookup_Code__c == subsIMCodeValues[j]) {
                            if(OL.End_Date__c != null){
                                orderLineDates = string.valueof(DateTime.valueof(OL.CreatedDate)).trim()+'@'+string.valueof(OL.Start_Date__c).trim()+'@'+string.valueof(OL.End_Date__c).trim();
                                system.debug('orderLineDates ---'+orderLineDates );
                            }
                            if(IMCodevalueandDateMap != null && IMCodevalueandDateMap.containsKey(OL.IM_Lookup_Code__c)){
                                IMCodevalueandDateMap.get(OL.IM_Lookup_Code__c).add(orderLineDates);
                                //added by saloni chhabra for creating map of IM lookup code adn end dates as per SSE-2720
                                IMCodevalueandEndDateMap.get(OL.IM_Lookup_Code__c).add(OL.End_Date__c);
                            }
                            else{
                                List<string> orderLineDateList = new List<string>();
                                orderLineDateList.add(orderLineDates);
                                
                                List<date> orderLineEndDateList = new List<date>();
                                orderLineEndDateList.add(OL.End_Date__c);
                                
                                IMCodevalueandDateMap.put(OL.IM_Lookup_Code__c,orderLineDateList);
                                //added by saloni chhabra for creating map of IM lookup code adn end dates as per SSE-2720
                                IMCodevalueandEndDateMap.put(OL.IM_Lookup_Code__c,orderLineEndDateList);
                            }                                                   
                         }                                              
                    }
                    
                    if(OL.End_Date__c !=NULL){
                        EndDateList.add(OL.End_Date__c); 
                    }
                            
                    if(AutoRenewalValues.contains(OL.IM_Lookup_Code__c) || OL.IM_Lookup_Code__c.contains('Subscription')){
                        IsSubscriptionOrderLine=true;
                    }
                }
                
              
                if(EndDateList.size()>0){
                    date dt=EndDateList[0];
                    closedate = dt;
                }
                if(ContractsNewList[i].Opportunity__c != null){
                    OppID = ContractsNewList[i].Opportunity__c;
                }            
                if(IsSubscriptionOrderLine == true && OppID != '' && ContractsNewList[0].Renewal_Opp_Error__c == null && ContractsNewList[0].Renewal_Opportunity__c == null){
                    ErrorMessage = Contract_BeforeUpdate_cls.RenewalOpportunity(IsSubscriptionOrderLine,closedate,OppID,OLsubscription,IMCodevalueandEndDateMap,IMCodevalueandDateMap);
                } 
            }
            
            else if(OLlistRenewal.size()==0 && OLlistReeboost.size()>0 && ContractsNewList[i].Offering__c== 'Assessments (Consumption-Based)' && ContractsNewList[i].Account_Region__c !='Distributors' &&  ContractsNewList[0].Reboost_Opp_Error__c == null &  ContractsNewList[0].Reboost_Opportunity__c == null){
                system.debug('inside rebosst logic');
                IsSubscriptionOrderLine= false;
                if(ContractsNewList[i].Opportunity__c != null){
                    OppID = ContractsNewList[i].Opportunity__c;
                }               
                for (Contract_Line__c OL : OLlistReeboost){
                    if (earliestenddate ==null){
                         closedate= OL.End_Date__c+ 1;
                         earliestenddate = closedate;   
                    }
                    else if(earliestenddate!= null){
                        if(earliestenddate >OL.End_Date__c){
                            closedate= OL.End_Date__c+ 1;
                            earliestenddate =OL.End_Date__c;  
                        }
                    }
                    /*MTVR dates*/
                    if (earliestenddateMTVR ==null){
                         ReboostMTVRStartDate= OL.Start_Date__c;
                         earliestenddateMTVR = ReboostMTVRStartDate;   
                    }
                    else if(earliestenddate!= null){
                        if(earliestenddateMTVR >OL.Start_Date__c){
                            ReboostMTVRStartDate= OL.Start_Date__c;
                            earliestenddateMTVR =OL.Start_Date__c;  
                        }
                    }                                     
                }
                ErrorMessagereboost = Contract_BeforeUpdate_cls.ReboostOpportunity(IsSubscriptionOrderLine,closedate,OppID,ReboostProducts,ReboostMTVRStartDate);
                system.debug('ErrorMessagereboost' + ErrorMessagereboost);               
            }  // end else-if
        } // end if
       } // end for
       
        if(ErrorMessage.size()>0){
            if(ErrorMessage.size()>1){
                ContractsNewList[0].Renewal_Opp_Error__c  = ErrorMessage.get(1);
            }
            if(ErrorMessage.get(0).contains('006')){
                ContractsNewList[0].Renewal_Opportunity__c  = URL.getSalesforceBaseUrl().toExternalForm() + '/'+ErrorMessage.get(0);
            }
        }
         if(ErrorMessagereboost.size()>0){
            if(ErrorMessagereboost.size()>1){
                ContractsNewList[0].Reboost_Opp_Error__c  = ErrorMessagereboost.get(1);
            }
            if(ErrorMessagereboost.get(0).contains('006')){
                ContractsNewList[0].Reboost_Opportunity__c  = URL.getSalesforceBaseUrl().toExternalForm() + '/'+ErrorMessagereboost.get(0);
            }
        }
      
        //edited by saloni chhabra on 19/3/2015 as per SSE-148 ends here        
        //edited by saloni chhabra on 01/06/2016 as per SSE-2544 to update last possible submission date daylight saving formula value to be used in last possible submission date field
        for(Integer i=0;i<trigger.new.size();i++){
            if((ContractsNewList[i].Final_Submission_Date_EST__c != null && ContractsNewList[i].Final_Submission_Date_EST__c!= ContractsOldList[i].Final_Submission_Date_EST__c )  && ContractsNewList[i].Submission_Offset__c != null){
                ContractsNewList[i].Last_Possible_Submission_Date_Daylight__c = (ContractsNewList[i].Final_Submission_Date_EST__c+ ((ContractsNewList[i].Submission_Offset__c/3600000)/24));               
            }
            else if(ContractsNewList[i].Final_Submission_Date_EST__c == null){
                ContractsNewList[i].Last_Possible_Submission_Date_Daylight__c = null;
            }
        }
        //edited by saloni chhabra on 01/06/2016 as per SSE-2544 ends here
    }
}