force-app/main/objects/Course_Booking__c.object
<CustomObject>
    <description>Public and Incompany course bookings to replace Big Sky Courses &amp; Bookings module</description>
    <fields>
        <fullName>Course_Booking_BU__c</fullName>
        <description>Business Unit from the course on the course booking</description>
        <label>Course Country</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Course_Description__c</fullName>
        <description>From the course record</description>
        <label>Course Description</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Course_Director__c</fullName>
        <description>Created for Qualtrics and is being used in Outbound message.</description>
        <formula>Course_Number__r.Course_Director__r.Contact_Full_Name__c</formula>
        <label>Course Director</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Course_End_Date__c</fullName>
        <label>Course End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Course_Name__c</fullName>
        <description>Course Name from Course Object</description>
        <label>Course Name</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Course_Number__c</fullName>
        <label>Course Number</label>
        <referenceTo>Courses__c</referenceTo>
        <relationshipLabel>Course Bookings</relationshipLabel>
        <relationshipName>Course_Booking</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Course_Start_Date__c</fullName>
        <label>Course Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Course_Type__c</fullName>
        <description>Course Type from Course object</description>
        <label>Course Type</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Course_Venue__c</fullName>
        <label>Course Venue</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SSC_Email__c</fullName>
        <label>SSC Email</label>
        <type>Email</type>
    </fields>
    <label>Course Booking</label>
    <nameField>
        <displayFormat>CB{000000}</displayFormat>
        <label>Booking Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Bookings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/objects/Courses__c.object
<CustomObject>
    <description>Area to keep list of all course types, codes, costs and venues</description>
    <fields>
        <fullName>Course_BU__c</fullName>
        <description>Business Unit which the course relates to</description>
        <inlineHelpText>Where the course is run</inlineHelpText>
        <label>Course Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Abu Dhabi</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Brazil</fullName>
                </value>
                <value>
                    <fullName>Bulgaria</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>China</fullName>
                </value>
                <value>
                    <fullName>Czech Republic</fullName>
                </value>
                <value>
                    <fullName>Denmark</fullName>
                </value>
                <value>
                    <fullName>Egypt</fullName>
                </value>
                <value>
                    <fullName>Finland</fullName>
                </value>
                <value>
                    <fullName>France</fullName>
                </value>
                <value>
                    <fullName>Georgia</fullName>
                </value>
                <value>
                    <fullName>Germany</fullName>
                </value>
                <value>
                    <fullName>Greece</fullName>
                </value>
                <value>
                    <fullName>Hong Kong</fullName>
                </value>
                <value>
                    <fullName>Hungary</fullName>
                </value>
                <value>
                    <fullName>India</fullName>
                </value>
                <value>
                    <fullName>Indonesia</fullName>
                </value>
                <value>
                    <fullName>Ireland</fullName>
                </value>
                <value>
                    <fullName>Italy</fullName>
                </value>
                <value>
                    <fullName>Japan</fullName>
                </value>
                <value>
                    <fullName>Kenya</fullName>
                </value>
                <value>
                    <fullName>Kuwait</fullName>
                </value>
                <value>
                    <fullName>Luxembourg</fullName>
                </value>
                <value>
                    <fullName>Malaysia</fullName>
                </value>
                <value>
                    <fullName>Mexico</fullName>
                </value>
                <value>
                    <fullName>Morocco</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Course_Description__c</fullName>
        <description>Full name of the course which can be translated and appears on templates.</description>
        <label>Course Description</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Course_Director__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Course Director</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Courses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Course_End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Course_Name__c</fullName>
        <label>Course Name</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Course_Type__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>360</fullName>
                </value>
                <value>
                    <fullName>360 Feedback half day</fullName>
                </value>
                <value>
                    <fullName>A&amp;DC</fullName>
                </value>
                <value>
                    <fullName>ADVC</fullName>
                </value>
                <value>
                    <fullName>ADVTS</fullName>
                </value>
                <value>
                    <fullName>ASST</fullName>
                </value>
                <value>
                    <fullName>BESPOKE</fullName>
                </value>
                <value>
                    <fullName>BPOA</fullName>
                </value>
                <value>
                    <fullName>BS</fullName>
                </value>
                <value>
                    <fullName>CBI</fullName>
                </value>
                <value>
                    <fullName>CBI Train the Trainer</fullName>
                </value>
                <value>
                    <fullName>CF</fullName>
                </value>
                <value>
                    <fullName>Coaching Essentials</fullName>
                </value>
                <value>
                    <fullName>COMBO</fullName>
                </value>
                <value>
                    <fullName>COMPD</fullName>
                </value>
                <value>
                    <fullName>CORESELL</fullName>
                </value>
                <value>
                    <fullName>Creating IDP’s</fullName>
                </value>
                <value>
                    <fullName>CUSTSV</fullName>
                </value>
                <value>
                    <fullName>Dev High Perf Teams</fullName>
                </value>
                <value>
                    <fullName>Diversity and Disability Confidence in Assessment</fullName>
                </value>
                <value>
                    <fullName>Effective Succession Plans</fullName>
                </value>
                <value>
                    <fullName>Employee Motivation</fullName>
                </value>
                <value>
                    <fullName>Enhancing Workforce Performance</fullName>
                </value>
                <value>
                    <fullName>Exec Leadership</fullName>
                </value>
                <value>
                    <fullName>FC</fullName>
                </value>
                <value>
                    <fullName>GS</fullName>
                </value>
                <value>
                    <fullName>HR Pioneer Series</fullName>
                </value>
                <value>
                    <fullName>Implementing and Facilitating a robust 360 Feedback process</fullName>
                </value>
                <value>
                    <fullName>Interviewing Techniques</fullName>
                </value>
                <value>
                    <fullName>LAMP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Course_Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Course_Type__c</fullName>
        <label>Course Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Ability</fullName>
                </value>
                <value>
                    <fullName>Personality</fullName>
                </value>
                <value>
                    <fullName>Ability/Personality</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Job Profiling</fullName>
                </value>
                <value>
                    <fullName>Internal</fullName>
                </value>
                <value>
                    <fullName>System Training</fullName>
                </value>
                <value>
                    <fullName>System Demo</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Course_Venue__c</fullName>
        <label>Course Venue</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Course_BU__c</controllingField>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Adelaide</fullName>
                </value>
                <value>
                    <fullName>Amersfoort</fullName>
                </value>
                <value>
                    <fullName>Atlanta</fullName>
                </value>
                <value>
                    <fullName>Auckland</fullName>
                </value>
                <value>
                    <fullName>Bangalore</fullName>
                </value>
                <value>
                    <fullName>Barony Castle, Scotland</fullName>
                </value>
                <value>
                    <fullName>Beaumont Estate, Berkshire</fullName>
                </value>
                <value>
                    <fullName>Beijing</fullName>
                </value>
                <value>
                    <fullName>Boulder, Colorado</fullName>
                </value>
                <value>
                    <fullName>Brisbane</fullName>
                </value>
                <value>
                    <fullName>Bristol</fullName>
                </value>
                <value>
                    <fullName>Brussels</fullName>
                </value>
                <value>
                    <fullName>Cairo</fullName>
                </value>
                <value>
                    <fullName>Camden Court, Dublin</fullName>
                </value>
                <value>
                    <fullName>Canary Wharf, London</fullName>
                </value>
                <value>
                    <fullName>Canberra</fullName>
                </value>
                <value>
                    <fullName>Cape Town</fullName>
                </value>
                <value>
                    <fullName>Caracas, Venezuela</fullName>
                </value>
                <value>
                    <fullName>CEO Suites KL</fullName>
                </value>
                <value>
                    <fullName>Cheadle House, Cheshire</fullName>
                </value>
                <value>
                    <fullName>Chennai</fullName>
                </value>
                <value>
                    <fullName>Cheshire</fullName>
                </value>
                <value>
                    <fullName>Chicago, Illinois</fullName>
                </value>
                <value>
                    <fullName>Christchurch</fullName>
                </value>
                <value>
                    <fullName>Client Site</fullName>
                </value>
                <value>
                    <fullName>Clifton’s Singapore</fullName>
                </value>
                <value>
                    <fullName>Colmore Gate, Birmingham</fullName>
                </value>
                <value>
                    <fullName>Concorde Hotel Kuala Lumpur</fullName>
                </value>
                <value>
                    <fullName>Copenhagen</fullName>
                </value>
                <value>
                    <fullName>Cotswold, Gloucestershire</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SSC_Email__c</fullName>
        <label>SSC Email</label>
        <type>Email</type>
    </fields>
    <label>Courses</label>
    <nameField>
        <displayFormat>C{000000}</displayFormat>
        <label>Course Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <recordTypes>
        <fullName>Public</fullName>
        <active>true</active>
        <label>Public</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/objects/Order.object
<CustomObject>
    <fields>
        <fullName>Course_Booking__c</fullName>
        <formula>IF(CONTAINS(Opportunity.Opportunity_Nickname__c,&apos;Opportunity for Course Booking&apos;),
			RIGHT(Opportunity.Opportunity_Nickname__c, 9), &apos;&apos; )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Course Booking</label>
        <type>Text</type>
    </fields>
</CustomObject>

classes/CourseTriggerManager.cls
/**************************************************************************************************************************************
CREATED BY :- PRIYANK ANAND 
CREATED DATE :- 08-06-2019
DESCRIPTION :- This class contains various validations and assignments on fields of Course object, this class is called in Course_Trigger.
***************************************************************************************************************************************/ 

Global class CourseTriggerManager {
    
    //This method is assigning Course Director field with Generic User id, If course director field is null.
    public static void assignCourseDirector(List<Courses__c> newCourses){
        System.debug('Number of Queries used -- Course TM assignCourseDirector START ------- ' + Limits.getQueries());
        for(Courses__c course:newCourses){
            if(course.Course_Director__c == null)
                course.Course_Director__c=System.label.GenericUserContactId;
            
        }
        System.debug('Number of Queries used -- Course TM  assignCourseDirector END ------- ' + Limits.getQueries());
    }
    
    //This method is copying data from course to course booking after any update on course.
    //used in CourseBookingTriggerManager.updateDeligateAccount
    public static void copyDataFromCourse(List<Course_Booking__c> courseBookings, List<Courses__c> courses) {
        System.debug('Number of Queries used -- Course TM copyDataFromCourse START ------- ' + Limits.getQueries());
        map<id,Courses__c> courseMap = new map<id,Courses__c>();
        for(Courses__c course:courses)
            courseMap.put(course.id,course);
        for(Course_Booking__c courseBooking:courseBookings)
        {
            if(courseMap.get(courseBooking.Course_Number__c)!=null)
            {
                courseBooking.Course_Name__c = courseMap.get(courseBooking.Course_Number__c).Course_Name__c; 
                courseBooking.Course_Booking_BU__c =  courseMap.get(courseBooking.Course_Number__c).Course_BU__c; 
                courseBooking.Course_Description__c = courseMap.get(courseBooking.Course_Number__c).Course_Description__c; 
                courseBooking.Course_Start_Date__c =  courseMap.get(courseBooking.Course_Number__c).Course_Start_Date__c; 
                courseBooking.Course_End_Date__c = courseMap.get(courseBooking.Course_Number__c).Course_End_Date__c; 
                courseBooking.Course_Type__c = courseMap.get(courseBooking.Course_Number__c).Course_Type__c; 
                courseBooking.Course_Venue__c = courseMap.get(courseBooking.Course_Number__c).Course_Venue__c; 
                courseBooking.SSC_Email__c = courseMap.get(courseBooking.Course_Number__c).SSC_Email__c;
                courseBooking.Profit_Centre__c=courseMap.get(courseBooking.Course_Number__c).Profit_Centre__c;
            }
        }
        System.debug('Number of Queries used -- Course TM copyDataFromCourse END ------- ' + Limits.getQueries());
    }
    
    //This method is calling copydatafromcourse method when certain fields are updated on course.
    public static void updateDataInCourseBookings(List<Courses__c> oldCourses, List<Courses__c> newCourses) {
        System.debug('Number of Queries used -- Course TM updateDataInCourseBookings START ------- ' + Limits.getQueries());        
        
        map<id,Courses__c> oldCourseMap = new map<id,Courses__c>();   
        for(Courses__c oldCourse : oldCourses){
            oldCourseMap.put(oldCourse.id,oldCourse);
        }
        
        List<Course_Booking__c> courseBookingsList = [SELECT Id,Course_Number__c, Booking_Status__c, Send_Survey__c, Course_Name__c,Course_Booking_BU__c, Course_Description__c, Course_Start_Date__c, Course_End_Date__c, Course_Type__c, Course_Venue__c, SSC_Email__c, Profit_Centre__c
                                                   	  FROM Course_Booking__c 
                                                      WHERE Course_Number__c IN: oldCourseMap.keySet() Order By Course_Number__c ];
        
        if( courseBookingsList.size() > 0){
            List<Course_Booking__c> cbListToUpdate = new List<Course_Booking__c>();
            for(Courses__c newCourse :newCourses)
            {
                if(newCourse.Course_Name__c != oldCourseMap.get(newCourse.id).Course_Name__c || 
                   newCourse.Course_BU__c != oldCourseMap.get(newCourse.id).Course_BU__c || 
                   newCourse.Course_Description__c != oldCourseMap.get(newCourse.id).Course_Description__c ||
                   newCourse.Course_Start_Date__c != oldCourseMap.get(newCourse.id).Course_Start_Date__c || 
                   newCourse.Course_End_Date__c != oldCourseMap.get(newCourse.id).Course_End_Date__c || 
                   newCourse.Course_Type__c != oldCourseMap.get(newCourse.id).Course_Type__c ||
                   newCourse.Course_Venue__c != oldCourseMap.get(newCourse.id).Course_Venue__c || 
                   newCourse.SSC_Email__c != oldCourseMap.get(newCourse.id).SSC_Email__c ||
                   newCourse.Profit_Centre__c != oldCourseMap.get(newCourse.id).Profit_Centre__c)
                {
                    for(Course_Booking__c cb1: courseBookingsList)
                    {
                        if(cb1.Course_Number__c!=null && cb1.Course_Number__c == newCourse.Id)
                        { 
                            cb1.Course_Name__c = newCourse.Course_Name__c; 
                            cb1.Course_Booking_BU__c =  newCourse.Course_BU__c; 
                            cb1.Course_Description__c = newCourse.Course_Description__c; 
                            cb1.Course_Start_Date__c =  newCourse.Course_Start_Date__c; 
                            cb1.Course_End_Date__c = newCourse.Course_End_Date__c; 
                            cb1.Course_Type__c = newCourse.Course_Type__c; 
                            cb1.Course_Venue__c = newCourse.Course_Venue__c; 
                            cb1.SSC_Email__c = newCourse.SSC_Email__c;
                            cb1.Profit_Centre__c = newCourse.Profit_Centre__c;
     
                            cbListToUpdate.add(cb1);  
                        } 
                    }
                    if(!cbListToUpdate.isEmpty()){
                       update cbListToUpdate; 
                    }
                    
                    
                }
                
                if(newCourse.Course_Status__c == 'Completed'){
                    List<Course_Booking__c> cbSurveyListToUpdate = new List<Course_Booking__c>();
                    for(Course_Booking__c cb2: courseBookingsList)
                    {
                        if(cb2.Course_Number__c!=null && cb2.Course_Number__c == newCourse.Id  && cb2.Booking_Status__c =='Confirmed')
                        { 
                        	cb2.Send_Survey__c=True;
                            cbSurveyListToUpdate.add(cb2);
                        }
                    }
                    if(!cbSurveyListToUpdate.isEmpty()){
                        update cbSurveyListToUpdate;
                    }
                    
                }
                
            }
            
        }
        
        // Below code was refactored and replaced by above code as per SSE-14356, to remove Queries from inside FOR loops
 		/*       
        map<id,Courses__c> newCourseMap = new map<id,Courses__c>();
        for(Courses__c newCourse:newCourses)
            newCourseMap.put(newCourse.id,newCourse);
        for(Courses__c oldCourse:oldCourses)
        {
            if(newCourseMap.get(oldCourse.id)!=null)
            {
                if(oldCourse.Course_Name__c != newCourseMap.get(oldCourse.id).Course_Name__c
                   || oldCourse.Course_BU__c != newCourseMap.get(oldCourse.id).Course_BU__c
                   || oldCourse.Course_Description__c != newCourseMap.get(oldCourse.id).Course_Description__c
                   || oldCourse.Course_Start_Date__c != newCourseMap.get(oldCourse.id).Course_Start_Date__c
                   || oldCourse.Course_End_Date__c != newCourseMap.get(oldCourse.id).Course_End_Date__c
                   || oldCourse.Course_Type__c != newCourseMap.get(oldCourse.id).Course_Type__c
                   || oldCourse.Course_Venue__c != newCourseMap.get(oldCourse.id).Course_Venue__c
                   || oldCourse.SSC_Email__c != newCourseMap.get(oldCourse.id).SSC_Email__c
                   || oldCourse.Profit_Centre__c != newCourseMap.get(oldCourse.id).Profit_Centre__c)
                {
                    List<Course_Booking__c> courseBookings = [SELECT Id,Course_Number__c  FROM Course_Booking__c WHERE Course_Number__c = :newCourseMap.get(oldCourse.id).Id];
                    copyDataFromCourse(courseBookings , newCourses);
                    update courseBookings;
                    
                }
            }

            for(Courses__c newCourse:newCourses)
            {
                if(newCourse.Course_Status__c == 'Completed'){
                    List<Course_Booking__c> courseBookingsforsurvey = [SELECT Id,Course_Number__c,Booking_Status__c,Do_not_Contact_Delegates__c 
																		FROM Course_Booking__c 
																		WHERE Course_Number__c = :newCourseMap.get(oldCourse.id).Id];    
                    List<Course_Booking__c> courseBookingstoUpdate = new List<Course_Booking__c>() ;
                    for(Course_Booking__c courseBooking:courseBookingsforsurvey)
                    {
                        if(courseBooking.Course_Number__c!=null && courseBooking.Booking_Status__c =='Confirmed')
                        {
                            courseBooking.Send_Survey__c=True;
                            courseBookingstoUpdate.add(courseBooking);
                        }
                        
                    }
                    update courseBookingstoUpdate;
                }
            } 
            
        }
		*/
        System.debug('Number of Queries used -- Course TM updateDataInCourseBookings END ------- ' + Limits.getQueries());
    }
    
    
}