force-app/main/objects/Course_Booking__c.object
<CustomObject>
    <description>Public and Incompany course bookings to replace Big Sky Courses &amp; Bookings module</description>
    <fields>
        <fullName>Course_Category__c</fullName>
        <description>Created for Qualtrics and is being used in Outbound message.</description>
        <formula>TEXT(Course_Number__r.Course_Category__c)</formula>
        <label>Course Category</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Course_Director__c</fullName>
        <description>Created for Qualtrics and is being used in Outbound message.</description>
        <formula>Course_Number__r.Course_Director__r.Contact_Full_Name__c</formula>
        <label>Course Director</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Course_End_Date__c</fullName>
        <label>Course End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Course_Name__c</fullName>
        <description>Course Name from Course Object</description>
        <label>Course Name</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Course_Number__c</fullName>
        <label>Course Number</label>
        <referenceTo>Courses__c</referenceTo>
        <relationshipLabel>Course Bookings</relationshipLabel>
        <relationshipName>Course_Booking</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Course_Price__c</fullName>
        <description>Course price with no discount and no extras</description>
        <inlineHelpText>Prices are now fixed in Sun based on agreed price.</inlineHelpText>
        <label>Public Course Price</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Course_Start_Date__c</fullName>
        <label>Course Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Course_Type__c</fullName>
        <description>Course Type from Course object</description>
        <label>Course Type</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Delegate_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Delegate Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>R00N20000000pPXoEAM</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Course Booking</label>
    <nameField>
        <displayFormat>CB{000000}</displayFormat>
        <label>Booking Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Bookings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/objects/Courses__c.object
<CustomObject>
    <description>Area to keep list of all course types, codes, costs and venues</description>
    <fields>
        <fullName>Course_Category__c</fullName>
        <description>Course category to identify internal, public, partner or in company.</description>
        <label>Course Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Public</fullName>
                    <default>true</default>
                    <label>Public</label>
                </value>
                <value>
                    <fullName>In Company</fullName>
                </value>
                <value>
                    <fullName>Internal</fullName>
                </value>
                <value>
                    <fullName>Partner</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Course_Director__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Course Director</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Courses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Course_End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Course_Free_Spaces__c</fullName>
        <description>Calculated field to get the free/available spaces for a Course.</description>
        <formula>Maximum_Delegates__c -( Course_Provisional_Total__c + Course_Confirmed_Total__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Free Spaces</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Course_Name__c</fullName>
        <label>Course Name</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Course_Type__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>360</fullName>
                </value>
                <value>
                    <fullName>360 Feedback half day</fullName>
                </value>
                <value>
                    <fullName>A&amp;DC</fullName>
                </value>
                <value>
                    <fullName>ADVC</fullName>
                </value>
                <value>
                    <fullName>ADVTS</fullName>
                </value>
                <value>
                    <fullName>ASST</fullName>
                </value>
                <value>
                    <fullName>BESPOKE</fullName>
                </value>
                <value>
                    <fullName>BPOA</fullName>
                </value>
                <value>
                    <fullName>BS</fullName>
                </value>
                <value>
                    <fullName>CBI</fullName>
                </value>
                <value>
                    <fullName>CBI Train the Trainer</fullName>
                </value>
                <value>
                    <fullName>CF</fullName>
                </value>
                <value>
                    <fullName>Coaching Essentials</fullName>
                </value>
                <value>
                    <fullName>COMBO</fullName>
                </value>
                <value>
                    <fullName>COMPD</fullName>
                </value>
                <value>
                    <fullName>CORESELL</fullName>
                </value>
                <value>
                    <fullName>Creating IDP’s</fullName>
                </value>
                <value>
                    <fullName>CUSTSV</fullName>
                </value>
                <value>
                    <fullName>Dev High Perf Teams</fullName>
                </value>
                <value>
                    <fullName>Diversity and Disability Confidence in Assessment</fullName>
                </value>
                <value>
                    <fullName>Effective Succession Plans</fullName>
                </value>
                <value>
                    <fullName>Employee Motivation</fullName>
                </value>
                <value>
                    <fullName>Enhancing Workforce Performance</fullName>
                </value>
                <value>
                    <fullName>Exec Leadership</fullName>
                </value>
                <value>
                    <fullName>FC</fullName>
                </value>
                <value>
                    <fullName>GS</fullName>
                </value>
                <value>
                    <fullName>HR Pioneer Series</fullName>
                </value>
                <value>
                    <fullName>Implementing and Facilitating a robust 360 Feedback process</fullName>
                </value>
                <value>
                    <fullName>Interviewing Techniques</fullName>
                </value>
                <value>
                    <fullName>LAMP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Course_Price__c</fullName>
        <inlineHelpText>Prices are now fixed in Sun based on agreed price.</inlineHelpText>
        <label>Public Course Price</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Course_Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Course_Type__c</fullName>
        <label>Course Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Ability</fullName>
                </value>
                <value>
                    <fullName>Personality</fullName>
                </value>
                <value>
                    <fullName>Ability/Personality</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Job Profiling</fullName>
                </value>
                <value>
                    <fullName>Internal</fullName>
                </value>
                <value>
                    <fullName>System Training</fullName>
                </value>
                <value>
                    <fullName>System Demo</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Maximum_Delegates__c</fullName>
        <inlineHelpText>This can be a maximum of 2 digits</inlineHelpText>
        <label>Max Delegates</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Courses</label>
    <nameField>
        <displayFormat>C{000000}</displayFormat>
        <label>Course Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <recordTypes>
        <fullName>Public</fullName>
        <active>true</active>
        <label>Public</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/CourseBookingBulkImplementor.cls
/*************This Component is used to handle the creation of Bulk Course Booking from the Courses. ************************
*             Created By: Prachi Gupta(prachi.gupta@shl.com)                                                                *                      
*             Created Date: 20-04-2022                                                                                      *
*****************************************************************************************************************************/

public class CourseBookingBulkImplementor {

    @AuraEnabled
        public static Courses__c getCourseData(Id CourseId){
        system.debug('Course Id '+CourseId);
        return [select Id, Name,Course_Type__c,Course_Category__c,Course_Price__c,CurrencyIsoCode,
                Course_Name__c,Course_Director__c, Course_Free_Spaces__c,Maximum_Delegates__c, Course_Start_Date__c,Course_End_Date__c 
                from Courses__c where Id=:CourseId];
    }
     @AuraEnabled
    public static CBResultWrapper saveCourseBookings(List<Course_Booking__c> CBList, Decimal fs){
         Integer CBCreated ; 
         CBResultWrapper CBR = new CBResultWrapper();
         CBR.Message = '';
         CBR.MessageType = 'Success';
         CBR.duplicateCB = new List<Course_Booking__c>();
        try{
        Decimal fsTemp = fs;    
        List<Course_Booking__c> cbListOfDuplicates = new List<Course_Booking__c>();
            Set<Id> CBDelegateIds = new Set<Id>();
            Set<Id> existingCBDelegateIds = new Set<Id>();
            List<Course_Booking__c> cbListToInsert = new List<Course_Booking__c>();
            List<Course_Booking__c> cbListWithoutDup = new List<Course_Booking__c>();
           
         
            
            for(Course_Booking__c cb : CBList){
                if(!CBDelegateIds.contains(cb.Delegate_Contact__c)){
                    CBDelegateIds.add(cb.Delegate_Contact__c);
                    cbListWithoutDup.add(cb);
                }
                else{
                      
                     CBR.MessageType = 'Error';
                     CBR.Message = 'Duplicate Course Booking! This Course already has a Course Booking with this Delegate Contact.';
                     CBR.duplicateCB.add(cb);
                }
            }
            
            List<Course_Booking__c> existingCBList = [SELECT Id, Delegate_Contact__c 
                                                      FROM Course_Booking__c  
                                                      WHERE Course_Number__c  =: cbListWithoutDup[0].Course_Number__c];
            //Course has no CB
            if(existingCBList.size() <= 0 ){
               
               Insert cbListWithoutDup;
               CBCreated =  cbListWithoutDup.size();
               CBR.MessageType = 'Success';
               CBR.Message =  CBCreated + ' Course Bookings records saved successfully'; } 
            //Course has CB
            else {
                
                for(Course_Booking__c cb : existingCBList){
                    //Course CB have Delegate Contact value
                    if(cb.Delegate_Contact__c != null){
                        
                        existingCBDelegateIds.add(cb.Delegate_Contact__c);
                    }
                }
                
                if (existingCBDelegateIds.size() <= 0 ) {
                    //Course has CB with Delegate Contact == null
                    
                    Insert cbListWithoutDup;
                    CBCreated =  cbListWithoutDup.size(); 
                    CBR.MessageType = 'Success';
                    CBR.Message = CBCreated + ' Course Bookings records saved successfully';}
                //Course has CB with Delegate Contact
                else {
                    
                    for(Course_Booking__c cb2 : cbListWithoutDup){
                       
                        if(existingCBDelegateIds.contains(cb2.Delegate_Contact__c)){
                           
                            cbListOfDuplicates.add(cb2); //CB and Contact exist in system. Return Contact
                             CBR.duplicateCB.add(cb2);
                            CBR.MessageType = 'Error';
                            CBR.Message = 'Duplicate Course Booking! This Course already has a Course Booking with this Delegate Contact.';
                        } else {
                            
                            cbListToInsert.add(cb2);//CB doesn't exist but Contact exist in system. Insert CB
                        }
                    }
                    
                    if( cbListToInsert.size()> 0){
                    
                        insert cbListToInsert;
                        CBCreated =  cbListToInsert.size();
                        CBR.MessageType = 'Success';
                        CBR.Message = CBCreated+ ' Course Bookings records saved successfully';
                    }
      }
            }
            
        return CBR;
        }
        catch(Exception e)
        {
            //return e.getMessage();
            system.debug('In catch' + e.getMessage());
            throw new AuraHandledException('Error while inserting Course Booking' + e.getMessage());
        }}
    
     public class CBResultWrapper{
       
        @AuraEnabled
        public List<Course_Booking__c> duplicateCB { get; set;} 
        @AuraEnabled
        public String Message { get; set;}
        
        @AuraEnabled
         public String MessageType { get; set;}}
    
}