force-app/main/objects/Course_Resources__c.object
<CustomObject>
    <description>To log details of associates and tutors used for course
		resourcing.</description>
    <fields>
        <fullName>Course_Name__c</fullName>
        <label>Resource Course Name</label>
        <referenceTo>Courses__c</referenceTo>
        <relationshipLabel>Course Resources</relationshipLabel>
        <relationshipName>R00N20000001IBf6EAG</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Resource_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Resource Name</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>R00N20000001IBY4EAO</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Resource_Role__c</fullName>
        <label>Resource Role</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Course Director</fullName>
                </value>
                <value>
                    <fullName>Tutor 1</fullName>
                </value>
                <value>
                    <fullName>Tutor 2</fullName>
                </value>
                <value>
                    <fullName>Tutor 3</fullName>
                </value>
                <value>
                    <fullName>Tutor 4</fullName>
                </value>
                <value>
                    <fullName>Tutor 5</fullName>
                </value>
                <value>
                    <fullName>Tutor 6</fullName>
                </value>
                <value>
                    <fullName>Volunteer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Resource_Status__c</fullName>
        <label>Resource Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Provisional</fullName>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Course Resource</label>
    <nameField>
        <displayFormat>R{00000}</displayFormat>
        <label>Course Resources Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Resources</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/objects/Courses__c.object
<CustomObject>
    <description>Area to keep list of all course types, codes, costs and venues</description>
    <fields>
        <fullName>Course_Director__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Course Director</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Courses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Course_Name__c</fullName>
        <label>Course Name</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Course_Type__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>360</fullName>
                </value>
                <value>
                    <fullName>360 Feedback half day</fullName>
                </value>
                <value>
                    <fullName>A&amp;DC</fullName>
                </value>
                <value>
                    <fullName>ADVC</fullName>
                </value>
                <value>
                    <fullName>ADVTS</fullName>
                </value>
                <value>
                    <fullName>ASST</fullName>
                </value>
                <value>
                    <fullName>BESPOKE</fullName>
                </value>
                <value>
                    <fullName>BPOA</fullName>
                </value>
                <value>
                    <fullName>BS</fullName>
                </value>
                <value>
                    <fullName>CBI</fullName>
                </value>
                <value>
                    <fullName>CBI Train the Trainer</fullName>
                </value>
                <value>
                    <fullName>CF</fullName>
                </value>
                <value>
                    <fullName>Coaching Essentials</fullName>
                </value>
                <value>
                    <fullName>COMBO</fullName>
                </value>
                <value>
                    <fullName>COMPD</fullName>
                </value>
                <value>
                    <fullName>CORESELL</fullName>
                </value>
                <value>
                    <fullName>Creating IDP’s</fullName>
                </value>
                <value>
                    <fullName>CUSTSV</fullName>
                </value>
                <value>
                    <fullName>Dev High Perf Teams</fullName>
                </value>
                <value>
                    <fullName>Diversity and Disability Confidence in Assessment</fullName>
                </value>
                <value>
                    <fullName>Effective Succession Plans</fullName>
                </value>
                <value>
                    <fullName>Employee Motivation</fullName>
                </value>
                <value>
                    <fullName>Enhancing Workforce Performance</fullName>
                </value>
                <value>
                    <fullName>Exec Leadership</fullName>
                </value>
                <value>
                    <fullName>FC</fullName>
                </value>
                <value>
                    <fullName>GS</fullName>
                </value>
                <value>
                    <fullName>HR Pioneer Series</fullName>
                </value>
                <value>
                    <fullName>Implementing and Facilitating a robust 360 Feedback process</fullName>
                </value>
                <value>
                    <fullName>Interviewing Techniques</fullName>
                </value>
                <value>
                    <fullName>LAMP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Courses</label>
    <nameField>
        <displayFormat>C{000000}</displayFormat>
        <label>Course Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <recordTypes>
        <fullName>Public</fullName>
        <active>true</active>
        <label>Public</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/CourseResourcesTriggerManager.cls
/**************************************************************************************************************************************
CREATED BY :- RISHABH KANOTRA
CREATED DATE :- 22/08/2019
DESCRIPTION :- This class contains various validations and restrictions to modify CourseResources and its fields and refered from Course_Resources_Trigger triggers : after insert,after update,after delete
***************************************************************************************************************************************/ 
 
Global class CourseResourcesTriggerManager{
    
    //Handling of custom validations when Account is updated
    //If Resource_Role__c  = Course Director then update the related course -> Course_Director__c to the Resource_Name__c of the course resource.
    public static void CRafterInsert(List<Course_Resources__c> newCourseResource){ 
        
        List<Courses__c> CRtoupdate = New List<Courses__c>();
        for (integer i=0;i<newCourseResource.size();i++)
        {  
            Courses__c course = new Courses__c(Id = newCourseResource[i].Course_Name__c);
            if(newCourseResource[i].Resource_Role__c == 'Course Director')
            {  
                course.Course_Director__c =  newCourseResource[i].Resource_Name__c;
                //update course;
                CRtoupdate.add(course);   
            }  
        }
        update CRtoupdate;
    }//CRafterInsert
    
    //Update the related course->Course_Director__c based on different conditions.
    public static void CRafterUpdate(List<Course_Resources__c> oldCourseResource, List<Course_Resources__c> newCourseResource){ 
        
        Set<Courses__c> CRtoupdate2 = New Set<Courses__c>();
        for (integer i=0;i<newCourseResource.size();i++)
        {
            Courses__c course = new Courses__c(Id = newCourseResource[i].Course_Name__c);
            Boolean CourseUpdatedRequired = false;
            if(newCourseResource[i].Resource_Role__c != oldCourseResource[i].Resource_Role__c)
            {
                if(newCourseResource[i].Resource_Role__c == 'Course Director')
                    course.Course_Director__c =  newCourseResource[i].Resource_Name__c;
                else if(oldCourseResource[i].Resource_Role__c == 'Course Director')
                    course.Course_Director__c =  null;
                CourseUpdatedRequired = true; 
            }
            if (newCourseResource[i].Resource_Status__c!= oldCourseResource[i].Resource_Status__c)
            {
                if ((newCourseResource[i].Resource_Role__c == 'Course Director')&& (newCourseResource[i].Resource_Status__c=='Cancelled'))
                {
                    course.Course_Director__c = null;  
                    CourseUpdatedRequired = true;
                } 
            }  
            if(newCourseResource[i].Resource_Name__c != oldCourseResource[i].Resource_Name__c)
            {
                if(newCourseResource[i].Resource_Role__c == 'Course Director')
                {
                    course.Course_Director__c =  newCourseResource[i].Resource_Name__c;
                    CourseUpdatedRequired = true; 
                }
            }
            if(CourseUpdatedRequired)
                CRtoupdate2.add(course);
                //update course;
        }  
        List<Courses__c> CRtoupdate2List = New List<Courses__c>();
        CRtoupdate2List.addAll(CRtoupdate2);
        update CRtoupdate2List;
    }//afterUpdate
    
    //update the related course->Course_Director__c to NULL 
    public static void CRafterDelete(List<Course_Resources__c> oldCourseResource){ 
        
        List<Courses__c> CRtoupdate = New List<Courses__c>();
        for (integer i=0;i<oldCourseResource.size();i++)
        {
            if(oldCourseResource[i].Resource_Role__c == 'Course Director')
            {
                Courses__c course = new Courses__c(Id = oldCourseResource[i].Course_Name__c);
                course.Course_Director__c = null;
                CRtoupdate.add(course);
                //update course;  
            }
        }
        update CRtoupdate;
    }//CRafterDelete
 }