force-app/main/objects/Course_Booking__c.object
<CustomObject>
    <description>Public and Incompany course bookings to replace Big Sky Courses &amp; Bookings module</description>
    <fields>
        <fullName>Course_Description__c</fullName>
        <description>From the course record</description>
        <label>Course Description</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Course_Name__c</fullName>
        <description>Course Name from Course Object</description>
        <label>Course Name</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Course_Number__c</fullName>
        <label>Course Number</label>
        <referenceTo>Courses__c</referenceTo>
        <relationshipLabel>Course Bookings</relationshipLabel>
        <relationshipName>Course_Booking</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Course_Start_Date__c</fullName>
        <label>Course Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Delegate_Account_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Delegate Account Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Delegate_Account_Owner</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Delegate_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Delegate Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Course Bookings (Delegate Account)</relationshipLabel>
        <relationshipName>Course_Bookings1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Delegate_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Delegate Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>R00N20000000pPXoEAM</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Profit_Centre__c</fullName>
        <label>Profit Centre</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Australia - AU1</fullName>
                </value>
                <value>
                    <fullName>Belgium - BE5</fullName>
                </value>
                <value>
                    <fullName>Canada - CA1</fullName>
                </value>
                <value>
                    <fullName>China - CN1</fullName>
                </value>
                <value>
                    <fullName>Denmark - DK1</fullName>
                </value>
                <value>
                    <fullName>Finland - FI1</fullName>
                </value>
                <value>
                    <fullName>France - FR1</fullName>
                </value>
                <value>
                    <fullName>Germany - DE1</fullName>
                </value>
                <value>
                    <fullName>Hong Kong - HK1</fullName>
                </value>
                <value>
                    <fullName>India - IN1</fullName>
                </value>
                <value>
                    <fullName>Ireland - IE1</fullName>
                </value>
                <value>
                    <fullName>Italy - IT1</fullName>
                </value>
                <value>
                    <fullName>Middle East - ME1</fullName>
                </value>
                <value>
                    <fullName>Netherlands - NL5</fullName>
                </value>
                <value>
                    <fullName>New Zealand - NZ1</fullName>
                </value>
                <value>
                    <fullName>Norway - NO1</fullName>
                </value>
                <value>
                    <fullName>Philippines - PH1</fullName>
                </value>
                <value>
                    <fullName>Poland - PL1</fullName>
                </value>
                <value>
                    <fullName>Singapore - SG1</fullName>
                </value>
                <value>
                    <fullName>South Africa - ZA1</fullName>
                </value>
                <value>
                    <fullName>Spain - ES1</fullName>
                </value>
                <value>
                    <fullName>Sweden - SE1</fullName>
                </value>
                <value>
                    <fullName>Switzerland - CH1</fullName>
                </value>
                <value>
                    <fullName>UK - UK1</fullName>
                </value>
                <value>
                    <fullName>US - US1</fullName>
                </value>
                <value>
                    <fullName>US - US5</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SSC_Email__c</fullName>
        <label>SSC Email</label>
        <type>Email</type>
    </fields>
    <label>Course Booking</label>
    <nameField>
        <displayFormat>CB{000000}</displayFormat>
        <label>Booking Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Bookings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/objects/Courses__c.object
<CustomObject>
    <description>Area to keep list of all course types, codes, costs and venues</description>
    <fields>
        <fullName>Course_BU__c</fullName>
        <description>Business Unit which the course relates to</description>
        <inlineHelpText>Where the course is run</inlineHelpText>
        <label>Course Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Abu Dhabi</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Brazil</fullName>
                </value>
                <value>
                    <fullName>Bulgaria</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>China</fullName>
                </value>
                <value>
                    <fullName>Czech Republic</fullName>
                </value>
                <value>
                    <fullName>Denmark</fullName>
                </value>
                <value>
                    <fullName>Egypt</fullName>
                </value>
                <value>
                    <fullName>Finland</fullName>
                </value>
                <value>
                    <fullName>France</fullName>
                </value>
                <value>
                    <fullName>Georgia</fullName>
                </value>
                <value>
                    <fullName>Germany</fullName>
                </value>
                <value>
                    <fullName>Greece</fullName>
                </value>
                <value>
                    <fullName>Hong Kong</fullName>
                </value>
                <value>
                    <fullName>Hungary</fullName>
                </value>
                <value>
                    <fullName>India</fullName>
                </value>
                <value>
                    <fullName>Indonesia</fullName>
                </value>
                <value>
                    <fullName>Ireland</fullName>
                </value>
                <value>
                    <fullName>Italy</fullName>
                </value>
                <value>
                    <fullName>Japan</fullName>
                </value>
                <value>
                    <fullName>Kenya</fullName>
                </value>
                <value>
                    <fullName>Kuwait</fullName>
                </value>
                <value>
                    <fullName>Luxembourg</fullName>
                </value>
                <value>
                    <fullName>Malaysia</fullName>
                </value>
                <value>
                    <fullName>Mexico</fullName>
                </value>
                <value>
                    <fullName>Morocco</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Course_Description__c</fullName>
        <description>Full name of the course which can be translated and appears on templates.</description>
        <label>Course Description</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Course_Name__c</fullName>
        <label>Course Name</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Course_Type__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>360</fullName>
                </value>
                <value>
                    <fullName>360 Feedback half day</fullName>
                </value>
                <value>
                    <fullName>A&amp;DC</fullName>
                </value>
                <value>
                    <fullName>ADVC</fullName>
                </value>
                <value>
                    <fullName>ADVTS</fullName>
                </value>
                <value>
                    <fullName>ASST</fullName>
                </value>
                <value>
                    <fullName>BESPOKE</fullName>
                </value>
                <value>
                    <fullName>BPOA</fullName>
                </value>
                <value>
                    <fullName>BS</fullName>
                </value>
                <value>
                    <fullName>CBI</fullName>
                </value>
                <value>
                    <fullName>CBI Train the Trainer</fullName>
                </value>
                <value>
                    <fullName>CF</fullName>
                </value>
                <value>
                    <fullName>Coaching Essentials</fullName>
                </value>
                <value>
                    <fullName>COMBO</fullName>
                </value>
                <value>
                    <fullName>COMPD</fullName>
                </value>
                <value>
                    <fullName>CORESELL</fullName>
                </value>
                <value>
                    <fullName>Creating IDP’s</fullName>
                </value>
                <value>
                    <fullName>CUSTSV</fullName>
                </value>
                <value>
                    <fullName>Dev High Perf Teams</fullName>
                </value>
                <value>
                    <fullName>Diversity and Disability Confidence in Assessment</fullName>
                </value>
                <value>
                    <fullName>Effective Succession Plans</fullName>
                </value>
                <value>
                    <fullName>Employee Motivation</fullName>
                </value>
                <value>
                    <fullName>Enhancing Workforce Performance</fullName>
                </value>
                <value>
                    <fullName>Exec Leadership</fullName>
                </value>
                <value>
                    <fullName>FC</fullName>
                </value>
                <value>
                    <fullName>GS</fullName>
                </value>
                <value>
                    <fullName>HR Pioneer Series</fullName>
                </value>
                <value>
                    <fullName>Implementing and Facilitating a robust 360 Feedback process</fullName>
                </value>
                <value>
                    <fullName>Interviewing Techniques</fullName>
                </value>
                <value>
                    <fullName>LAMP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Course_Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SSC_Email__c</fullName>
        <label>SSC Email</label>
        <type>Email</type>
    </fields>
    <label>Courses</label>
    <nameField>
        <displayFormat>C{000000}</displayFormat>
        <label>Course Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <recordTypes>
        <fullName>Public</fullName>
        <active>true</active>
        <label>Public</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/CourseBookingTriggerManager.cls
/**************************************************************************************************************************************
CREATED BY :- PRIYANK ANAND 
CREATED DATE :- 09-06-2019
DESCRIPTION :- This class contains assignments of fields of Course Booking object, this class is called in CourseBooking_Trigger.
***************************************************************************************************************************************/ 
 
Global class CourseBookingTriggerManager {
    //This method is updating delegate account field of course booking and calling copydatafromcourse method. 
    public static void updateDeligateAccount(List<Course_Booking__c> newCourseBooking){
       
        List<Course_Booking__c> cbListWithoutDup = new List<Course_Booking__c>();
        
        System.debug('Number of Queries used -- CB TM updateDeligateAccount START ------- ' + Limits.getQueries());
        Set<Id> contactIds = new Set<Id>();
        Set<Id> courseIds = new Set<Id>();
        
       cbListWithoutDup= getExistingCBForSameCourse(newCourseBooking);
        for(Course_Booking__c booking:cbListWithoutDup)
        {
            if(!contactIds.contains(booking.Delegate_Contact__c))
                contactIds.add(booking.Delegate_Contact__c);
            if(!courseIds.contains(booking.Course_Number__c))
                courseIds.add(booking.Course_Number__c);
        }
        Map<Id,Contact> contactsMap = new Map<Id,Contact> ([SELECT Id,AccountId, Account.OwnerId from Contact WHERE Id IN:contactIds]);
        if(cbListWithoutDup.size()>0){
        for(Course_Booking__c booking :cbListWithoutDup)
        {
            booking.Delegate_Account__c = contactsMap.get(booking.Delegate_Contact__c).Accountid; 
            booking.Delegate_Account_Owner__c = contactsMap.get(booking.Delegate_Contact__c).Account.OwnerId;
        }
        List<Courses__c> courses= new List<Courses__c>([SELECT Course_Name__c, Course_BU__c, Course_Description__c, SSC_Email__c, Course_Start_Date__c,Profit_Centre__c,Course_End_Date__c, Course_Price__c, Course_Type__c, Course_Venue__c, Course_Residential_Price__c ,Extra_night_price__c FROM Courses__c  WHERE Id IN:courseIds]);  
        CourseTriggerManager.copyDataFromCourse(Trigger.new,courses);
        System.debug('Number of Queries used -- CB TM updateDeligateAccount END ------- ' + Limits.getQueries());
        }}
    
    //This method is updating delegate account field of course booking if delegate contact is updated.
    public static void updateDeligateAccountBeforeUpdate(List<Course_Booking__c> newCourseBooking,List<Course_Booking__c> oldCourseBooking){
        System.debug('Number of Queries used -- CB TM updateDeligateAccountBeforeUpdate START ------- ' + Limits.getQueries());
        
        Set<Id> ContactIds = new Set<Id>();
        List<Course_Booking__c> cbListWithoutDup = new List<Course_Booking__c>();
        integer j = 0;
        
        for(Course_Booking__c Coursebookings:newCourseBooking)  
        {   if(Coursebookings.Delegate_Contact__c != oldCourseBooking[j].Delegate_Contact__c ){
            	ContactIds.add(Coursebookings.Delegate_Contact__c);  
        	}
         j++;
        }
        if(ContactIds.size()!=0 && !ContactIds.isEmpty() ){
            Map<Id,Contact> ContactsMap =new Map<Id,Contact> ([SELECT Id,AccountId,Account.OwnerId from Contact WHERE Id IN:ContactIds]);
            List<Course_Booking__c> cbList = new List<Course_Booking__c>();
            
            for(integer i=0;i<newCourseBooking.size();i++)
            {    
                if( newCourseBooking[i].Delegate_Account__c !=null)
                { 
                    if(newCourseBooking[i].Delegate_Contact__c != oldCourseBooking[i].Delegate_Contact__c)
                    {  
                       
                        cbList.add(newCourseBooking[i]);
                     }
                    
                  
                }
                else
                {
                    newCourseBooking[i].Delegate_Account__c = ContactsMap.get(newCourseBooking[i].Delegate_Contact__c).Accountid;
                    newCourseBooking[i].Delegate_Account_Owner__c = ContactsMap.get(newCourseBooking[i].Delegate_Contact__c).Account.OwnerId;
                }     
            } 
            
              if(cbList.size() > 0){
                 
                        cbListWithoutDup = getExistingCBForSameCourse(cbList);
                  for(integer i=0;i<cbListWithoutDup.size();i++){
                       system.debug('Inside for');
                        cbListWithoutDup[i].Delegate_Account__c = ContactsMap.get(cbListWithoutDup[i].Delegate_Contact__c).Accountid;
                        cbListWithoutDup[i].Delegate_Account_Owner__c = ContactsMap.get(cbListWithoutDup[i].Delegate_Contact__c).Account.OwnerId;
                  }}
        }
        System.debug('Number of Queries used -- CB TM updateDeligateAccountBeforeUpdate END ------- ' + Limits.getQueries());
    }
    
    //This method is used to get all the Course Bookings related to a Course -- SSE-15464.
    public static List<Course_Booking__c> getExistingCBForSameCourse(List<Course_Booking__c> newCourseBooking){
        
        List<Course_Booking__c> cbList = new List<Course_Booking__c>();
        List<Courses__c> newCourseList = new List<Courses__c>();
        List<Course_Booking__c> cbListWithoutDup = new List<Course_Booking__c>();
        Map<id , List<Course_Booking__c>> newCBMap = new Map<id , List<Course_Booking__c>>();
        Set<Id> contactIds = new Set<Id>();
        Set<Id> courseIds = new Set<Id>();
        
          for(Course_Booking__c booking:newCourseBooking)
        {
            if(!contactIds.contains(booking.Delegate_Contact__c))
                contactIds.add(booking.Delegate_Contact__c);
            if(!courseIds.contains(booking.Course_Number__c))
                courseIds.add(booking.Course_Number__c);
        }
        newCourseList = [SELECT Id ,name, (Select Id ,Course_Number__c, Delegate_Contact__c from Course_Booking__r) 
                         FROM Courses__c  WHERE Id IN:courseIds]; 
        
        if(newCourseList.size() > 0){
        for(Courses__c cb : newCourseList){
         newCBMap.put(cb.id , cb.Course_Booking__r);
        }}
        
        if(!newCBMap.isEmpty()){
            for(id cb2 :newCBMap.keyset() ){      
             cbListWithoutDup=   dupCBCheck(cb2,newCBMap.get(cb2),newCourseBooking);
                
            }
        }
        
        return cbListWithoutDup;
        
        
       
    }
      //This method is used to Check that Duplicate CB are not created under a Course -- SSE-15464.
    public static List<Course_Booking__c> dupCBCheck(id courseId, List<Course_Booking__c> relatedCB ,List<Course_Booking__c> newCourseBooking ){
          
        Set<Id> existingCBDelegateIds = new Set<Id>();
        List<Course_Booking__c> cbListWithoutDup = new List<Course_Booking__c>();
        for(Course_Booking__c cb1 :relatedCB ){
            existingCBDelegateIds.add(cb1.Delegate_Contact__c);
        }
        for(Course_Booking__c cb2 :newCourseBooking ){
       
            if(cb2.Course_Number__c == courseId && existingCBDelegateIds.contains(cb2.Delegate_Contact__c)){
                
                 
                cb2.addError('The Course Booking for this Delegate Contact already Exists on the Course.');
            }
            else{
                cbListWithoutDup.add(cb2);
            }
        }
        return cbListWithoutDup;
    }
    
}