force-app/main/objects/Courses__c.object
<CustomObject>
    <description>Area to keep list of all course types, codes, costs and venues</description>
    <fields>
        <fullName>Course_Confirmed_Total__c</fullName>
        <description>Roll up summary field for Confirmed Bookings</description>
        <label>Confirmed Total</label>
        <summaryFilterItems>
            <field>Course_Booking__c.Booking_Status__c</field>
            <operation>equals</operation>
            <value>Confirmed, Ready to be confirmed</value>
        </summaryFilterItems>
        <summaryForeignKey>Course_Booking__c.Course_Number__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Date_JI_First_Sent__c</fullName>
        <label>Date JI first sent</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Lead_Source__c</fullName>
        <description>Lead source for Sun SOE data entry</description>
        <label>Lead Source</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>L01 - Advertisement</fullName>
                </value>
                <value>
                    <fullName>L02 - News story / article</fullName>
                </value>
                <value>
                    <fullName>L03 - SHL newsletter</fullName>
                </value>
                <value>
                    <fullName>L04 - Promotional campaign email</fullName>
                </value>
                <value>
                    <fullName>L05 - Promotional campaign direct mail</fullName>
                </value>
                <value>
                    <fullName>L06 - Promotional campaign call</fullName>
                </value>
                <value>
                    <fullName>L07 - SHL Sales / Account Manager / Consultant discussion</fullName>
                </value>
                <value>
                    <fullName>L08 - SHL Duty Consultant</fullName>
                </value>
                <value>
                    <fullName>L09 - SHL Partner</fullName>
                </value>
                <value>
                    <fullName>L10 - SHL website promotion</fullName>
                </value>
                <value>
                    <fullName>L11 - Other (non-SHL) website promotion</fullName>
                </value>
                <value>
                    <fullName>L12 - Reputation / referral</fullName>
                </value>
                <value>
                    <fullName>L13 - Conference / seminar attendance</fullName>
                </value>
                <value>
                    <fullName>L14 - SHL training course attendance</fullName>
                </value>
                <value>
                    <fullName>L15 - Exhibition / trade show attendance</fullName>
                </value>
                <value>
                    <fullName>LZZ - No specified source (eg. simple repeat order)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Courses</label>
    <nameField>
        <displayFormat>C{000000}</displayFormat>
        <label>Course Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <recordTypes>
        <fullName>Public</fullName>
        <active>true</active>
        <label>Public</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/EmailTemplate_Selection.cls
public class EmailTemplate_Selection
{
    List<Folder> folderList = [SELECT Id,Name FROM Folder WHERE type = 'Email'];
    public List<EmailTemplate> emailTemplatesList{get;set;}
    public string folderId{get;set;}
    public string emailTemplateId {get;set;}
    public string courseId {get;set;}
    public string message{get;set;}
    
    public string actionString = '%'+ApexPages.currentPage().getParameters().get('foldername')+'%';
    public string success {get;set;}
    
    //This method checks Is there any email template exist for the passed query or not
    public Boolean getIsTemplateExist()
    {
        if(emailTemplateslist != null && emailTemplatesList.size()>0)
        return false;
        else
        return true;
    }
    //This method creates emailtemplatelist and show this list in detail page at time of page load as folderid and actionstring passed
    public EmailTemplate_Selection()
    {
        if(folderList.size()>0)
            emailTemplatesList = [SELECT Id, Name,TemplateType,Description FROM EmailTemplate where FolderId=:folderList[0].id and Name like :actionString];
    }
    //This method is used to populate folder names in Folder picklist
    public List<SelectOption> getItems()
    {
        List<SelectOption> options = new List<SelectOption>();
        for(Folder folder:folderList)
        {
            options.add(new SelectOption(folder.id,folder.Name));
        }
        return options;
    }
    // This method creates emailtemplatelist to show in detail page as folder name gets changed
    public PageReference changeFolder()
    {
        emailTemplatesList = [SELECT Id, Name,TemplateType,Description FROM EmailTemplate where FolderId=:folderId and Name like :actionString];
        System.debug('*******emailTemplatesList.size()*******'+emailTemplatesList.size());
        return null;
    }
    // This method is used to send emails to delegate contacts of course bookings 
    public PageReference executeAction()
    {
        String actionResult;
        String action = ApexPages.currentPage().getParameters().get('action');
        if(action == 'Course_sendJoiningInstructions')
            actionResult = Course_Manager.sendJoiningInstructions(this.courseId, this.emailTemplateId); 
        /*else if(action == 'Course_SendSurvey')
            actionResult = Course_Manager.sendSurvey(this.courseId, this.emailTemplateId);*/
        if(actionResult.startsWith('SUCCESS:'))
        {
            message = actionResult.substring(8);
            success = 'true';
        }
        else if (actionResult.startsWith('FAILURE:')) 
        {
            message = actionResult.substring(8);
            success = 'false';
        }
        System.debug('*********success********'+success);
        return null;
    }
    /*static testMethod void testSendSurvey()     
    {    
            Courses__c course = [SELECT Id FROM Courses__c WHERE Course_Confirmed_Total__c>0 AND Date_JI_First_Sent__c=:null AND Lead_Source__c!=:null LIMIT 1];  
            ApexPages.standardController controller = new ApexPages.standardController(course); 
            Course_SendSurvey classSC = new Course_SendSurvey(controller);
            classSC.emailTemplateId = [SELECT Id, Name,TemplateType,Description FROM EmailTemplate LIMIT 1].Id;
            classSC.getIsTemplateExist();
            classSC.changeFolder();
            classSC.getItems();
            classSC.sendJIEmail();
    } */  
    
}