force-app/main/objects/Discount_Summary__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Discount Summary</relationshipLabel>
        <relationshipName>Discount_Summaries</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Discount Summary</label>
    <nameField>
        <displayFormat>FD{00000}</displayFormat>
        <label>Discount Summary Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Discount Summaries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/redirect_discount_Ext.cls
/*
Created By: Rishabh Kanotra, for SSE-7079, 
Purpose: Overiding Functionality of OLI standard "EDIT & DELETE" actions 
*/
public class redirect_discount_Ext {
    
    
    Public String OpptyIddiscount{get;set;}
    public Discount_Summary__c Discountrec;
    
    
    public redirect_discount_Ext (ApexPages.StandardController controller) {
        
        Discountrec= [select id, Opportunity__c from Discount_Summary__c where id =: System.currentPageReference().getParameters().get('id')];
        OpptyIddiscount=Discountrec.Opportunity__c ;
    }
}