force-app/main/objects/Future_Product__c.object
<CustomObject>
    <fields>
        <fullName>Add_On__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Add-On</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Basis_of_Fees__c</fullName>
        <inlineHelpText>Select the usage type that the subscription is based on.  If “other” is chosen, text box must be populated.</inlineHelpText>
        <label>Basis of Fees</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Assessments and Reports</fullName>
                </value>
                <value>
                    <fullName>Candidates</fullName>
                </value>
                <value>
                    <fullName>Full-Time Equivalents (FTEs)</fullName>
                </value>
                <value>
                    <fullName>Units</fullName>
                </value>
                <value>
                    <fullName>CPS Days</fullName>
                </value>
                <value>
                    <fullName>LPS Days</fullName>
                </value>
                <value>
                    <fullName>Employees</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Participants</fullName>
                </value>
                <value>
                    <fullName>Applications</fullName>
                    <isActive>false</isActive>
                    <label>Applications</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ListPrice__c</fullName>
        <label>List Price/Basis of Fees</label>
        <precision>18</precision>
        <scale>8</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Opportunity_Product_Id__c</fullName>
        <label>Opportunity Product Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Package__c</fullName>
        <label>Offering Details</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Proposition__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Graduate Essential</fullName>
                </value>
                <value>
                    <fullName>Graduate Advanced</fullName>
                </value>
                <value>
                    <fullName>Graduate Ultimate</fullName>
                </value>
                <value>
                    <fullName>Volume Essential</fullName>
                </value>
                <value>
                    <fullName>Volume Advanced</fullName>
                </value>
                <value>
                    <fullName>Tech Essential</fullName>
                </value>
                <value>
                    <fullName>Tech Advanced</fullName>
                </value>
                <value>
                    <fullName>Managerial Essential</fullName>
                </value>
                <value>
                    <fullName>Managerial Advanced</fullName>
                </value>
                <value>
                    <fullName>Managerial Ultimate</fullName>
                </value>
                <value>
                    <fullName>Video Essential</fullName>
                </value>
                <value>
                    <fullName>Video Advanced</fullName>
                </value>
                <value>
                    <fullName>Video Ultimate</fullName>
                </value>
                <value>
                    <fullName>VACDC Essential</fullName>
                </value>
                <value>
                    <fullName>VACDC Advanced</fullName>
                </value>
                <value>
                    <fullName>VACDC Ultimate</fullName>
                </value>
                <value>
                    <fullName>Professional Essential</fullName>
                </value>
                <value>
                    <fullName>Professional Advanced</fullName>
                </value>
                <value>
                    <fullName>Professional Ultimate</fullName>
                </value>
                <value>
                    <fullName>Product</fullName>
                </value>
                <value>
                    <fullName>Assessment Centre Essential</fullName>
                </value>
                <value>
                    <fullName>Assessment Centre Advanced</fullName>
                </value>
                <value>
                    <fullName>Assessment Centre Ultimate</fullName>
                </value>
                <value>
                    <fullName>Development Center Advanced</fullName>
                </value>
                <value>
                    <fullName>Development Center Ultimate</fullName>
                </value>
                <value>
                    <fullName>Mobilize Essential</fullName>
                </value>
                <value>
                    <fullName>Mobilize Advanced</fullName>
                </value>
                <value>
                    <fullName>Mobilize Ultimate</fullName>
                </value>
                <value>
                    <fullName>Service</fullName>
                </value>
                <value>
                    <fullName>TMReview Talent Advanced</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Platform__c</fullName>
        <label>Platform</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Talent Central</fullName>
                </value>
                <value>
                    <fullName>Insights</fullName>
                </value>
                <value>
                    <fullName>iAssess</fullName>
                </value>
                <value>
                    <fullName>MFS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product &amp; Assessment</label>
        <referenceTo>Product2</referenceTo>
        <relationshipName>Future_Year_Opportunity_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sales_Price__c</fullName>
        <label>Sales Price/Basis of Fees</label>
        <precision>18</precision>
        <scale>8</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Solution_Cap__c</fullName>
        <label>Solution Cap</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Usage_Allowance__c</fullName>
        <inlineHelpText>Select if usage is capped or uncapped.</inlineHelpText>
        <label>Usage Allowance</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Capped</fullName>
                </value>
                <value>
                    <fullName>Uncapped</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Usage_Cap_or_Estimation__c</fullName>
        <inlineHelpText>If Basis of Fees is Candidates, Applications, Assessments, Units - enter the usage cap or usage estimate. If FTEs - enter FTE number used in calculator</inlineHelpText>
        <label>Total Equivalent Units</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Product &amp; Service (Future Period)</label>
    <nameField>
        <displayFormat>P&amp;S(FY)-{0000}</displayFormat>
        <label>Future OppLine Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Products &amp; Services (Future Period)</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Add_On__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Add-On</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Basis_of_Fees__c</fullName>
        <description>Outdated helptext: Select the usage type that the subscription is based on.  If “other” is chosen, text box must be populated.</description>
        <label>Basis of Fees</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Candidates</fullName>
                </value>
                <value>
                    <fullName>Units</fullName>
                </value>
                <value>
                    <fullName>Employees</fullName>
                </value>
                <value>
                    <fullName>Full-Time Equivalents (FTEs)</fullName>
                </value>
                <value>
                    <fullName>Participants</fullName>
                </value>
                <value>
                    <fullName>Assessments and Reports</fullName>
                </value>
                <value>
                    <fullName>CPS Days</fullName>
                </value>
                <value>
                    <fullName>LPS Days</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>List_Price__c</fullName>
        <description>New custom List Price field</description>
        <label>List Price/Basis of Fees</label>
        <precision>18</precision>
        <scale>8</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Package__c</fullName>
        <label>Offering Details</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Proposition__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Graduate Essential</fullName>
                </value>
                <value>
                    <fullName>Graduate Advanced</fullName>
                </value>
                <value>
                    <fullName>Graduate Ultimate</fullName>
                </value>
                <value>
                    <fullName>Volume Essential</fullName>
                </value>
                <value>
                    <fullName>Volume Advanced</fullName>
                </value>
                <value>
                    <fullName>Apprentice Essential</fullName>
                </value>
                <value>
                    <fullName>Tech Essential</fullName>
                    <label>Technology Essential</label>
                </value>
                <value>
                    <fullName>Tech Advanced</fullName>
                    <label>Technology Advanced</label>
                </value>
                <value>
                    <fullName>Technology Ultimate</fullName>
                </value>
                <value>
                    <fullName>Managerial Essential</fullName>
                </value>
                <value>
                    <fullName>Managerial Advanced</fullName>
                </value>
                <value>
                    <fullName>Managerial Ultimate</fullName>
                </value>
                <value>
                    <fullName>Video Essential</fullName>
                </value>
                <value>
                    <fullName>Video Advanced</fullName>
                </value>
                <value>
                    <fullName>Video Ultimate</fullName>
                </value>
                <value>
                    <fullName>Professional Essential</fullName>
                </value>
                <value>
                    <fullName>Professional Advanced</fullName>
                </value>
                <value>
                    <fullName>Professional Ultimate</fullName>
                </value>
                <value>
                    <fullName>Core Essential</fullName>
                </value>
                <value>
                    <fullName>Core Advanced</fullName>
                </value>
                <value>
                    <fullName>Core Unit Essential</fullName>
                </value>
                <value>
                    <fullName>Review Essential</fullName>
                </value>
                <value>
                    <fullName>Review Advanced</fullName>
                </value>
                <value>
                    <fullName>Review Ultimate</fullName>
                </value>
                <value>
                    <fullName>Mobilize Essential</fullName>
                </value>
                <value>
                    <fullName>Mobilize Advanced</fullName>
                </value>
                <value>
                    <fullName>Mobilize Ultimate</fullName>
                </value>
                <value>
                    <fullName>Product</fullName>
                </value>
                <value>
                    <fullName>Sales Transformation Review Essential</fullName>
                </value>
                <value>
                    <fullName>Sales Transformation Review Advanced</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Platform__c</fullName>
        <label>Platform</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Talent Central</fullName>
                </value>
                <value>
                    <fullName>Insights</fullName>
                </value>
                <value>
                    <fullName>iAssess</fullName>
                </value>
                <value>
                    <fullName>MFS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Solution_Cap__c</fullName>
        <label>Solution Cap</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Usage_Allowance__c</fullName>
        <inlineHelpText>Select if usage is capped or uncapped.</inlineHelpText>
        <label>Usage Allowance</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Capped</fullName>
                </value>
                <value>
                    <fullName>Uncapped</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Usage_Cap_or_Estimation__c</fullName>
        <inlineHelpText>If Basis of Fees is Candidates, Applications, Assessments, Units - enter the usage cap or usage estimate.  If FTEs - enter FTE number used in calculator</inlineHelpText>
        <label>Usage Cap or Estimation</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

classes/Opportunity_RecordType_change.cls
public class Opportunity_RecordType_change {
    @InvocableMethod
    public static List<OutputValues> createProducts_On_OppRecordTypeChange( List<InputValues> inputValuesList ){
        List<Future_Product__c> futureProductsList = inputValuesList.get(0).FutureProducts;
        List<OpportunityLineItem> opportunityProducts = inputValuesList.get(0).OpportunityProducts;

        List<Future_Product__c> futureProductsList_To_Update = new List<Future_Product__c>();
        
        OutputValues outputValues = new OutputValues();
        outputValues.FutureProductsUpdated = futureProductsList_To_Update;
        List<OutputValues> outputValuesList = new List<OutputValues>();
        outputValuesList.add(outputValues); 
        
        if(futureProductsList != null && !futureProductsList.isEmpty()){
            
            for(Future_Product__c futureProd : futureProductsList ){
                System.debug('futureProd.Product__r.Id  --->' + futureProd.Product__r.Id );
                
                if(futureProd.Opportunity_Product_Id__c == null){
                    if(opportunityProducts != null ){
                        for(OpportunityLineItem oppProd: opportunityProducts){
                            System.debug('oppProd.Product2.Id   --->' + oppProd.Product2.Id );
                            /*if(futureProd.Product__r.Id == oppProd.Product2.Id 
                               && futureProd.Add_On__c == oppProd.Add_On__c 
                               && futureProd.Basis_of_Fees__c == oppProd.Basis_of_Fees__c 
                               && futureProd.ListPrice__c == oppProd.List_Price__c
                               && futureProd.Package__c == oppProd.Package__c 
                               && futureProd.Platform__c == oppProd.Platform__c 
                               && futureProd.Quantity__c == oppProd.Quantity 
                               && futureProd.Sales_Price__c == oppProd.UnitPrice 
                               && futureProd.Solution_Cap__c == oppProd.Solution_Cap__c 
                               && futureProd.Usage_Allowance__c == oppProd.Usage_Allowance__c 
                               && futureProd.Usage_Cap_or_Estimation__c == oppProd.Usage_Cap_or_Estimation__c 
                               && futureProd.Opportunity_Product_Id__c == null) {
                                   
                                futureProd.Opportunity_Product_Id__c = oppProd.Id;
                                
                            } else if (futureProd.Product__r.Id == oppProd.Product2.Id 
                                       && futureProd.Add_On__c == oppProd.Add_On__c 
                                       && futureProd.Basis_of_Fees__c == oppProd.Basis_of_Fees__c 
                                       && futureProd.Package__c == oppProd.Package__c 
                                       && futureProd.Platform__c == oppProd.Platform__c  
                                       && futureProd.Solution_Cap__c == oppProd.Solution_Cap__c
                                       && futureProd.Usage_Allowance__c == oppProd.Usage_Allowance__c 
                                       && futureProd.Usage_Cap_or_Estimation__c == oppProd.Usage_Cap_or_Estimation__c  
                                       && ( futureProd.ListPrice__c == oppProd.List_Price__c
                                       || futureProd.Sales_Price__c == oppProd.UnitPrice       
                                       || futureProd.Quantity__c == oppProd.Quantity )
                                       && futureProd.Opportunity_Product_Id__c == null) {
                                   
                                futureProd.Opportunity_Product_Id__c = oppProd.Id;
                                   
                            } else */ 
                            if (futureProd.Product__r.Id == oppProd.Product2.Id ) {
                                           
                                futureProd.Opportunity_Product_Id__c = oppProd.Id;
                            }
                        }
                        futureProductsList_To_Update.add(futureProd);
                    }
                }
            }
            
            if(!futureProductsList_To_Update.isEmpty()){
                update futureProductsList_To_Update;
            }
        }
        return outputValuesList;
    }
    
    public class InputValues{
        @invocableVariable
        public List<Future_Product__c> FutureProducts;
        
        @invocableVariable
        public List<OpportunityLineItem> OpportunityProducts;
        
    }
    
    public class OutputValues{
        @invocableVariable
        public List<Future_Product__c> FutureProductsUpdated;
    }
}