force-app/main/objects/India_GST__c.object
<CustomObject>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>GST</fullName>
                </value>
                <value>
                    <fullName>VAT</fullName>
                </value>
                <value>
                    <fullName>Sales Tax</fullName>
                </value>
                <value>
                    <fullName>Billing Address</fullName>
                </value>
                <value>
                    <fullName>Shipping Address</fullName>
                </value>
                <value>
                    <fullName>PAN</fullName>
                </value>
                <value>
                    <fullName>TAN</fullName>
                </value>
                <value>
                    <fullName>Headquarters Address</fullName>
                </value>
                <value>
                    <fullName>Home Address</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Address &amp; Tax Information</label>
    <nameField>
        <label>Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Address &amp; Tax Information</pluralLabel>
    <recordTypes>
        <fullName>Address</fullName>
        <active>true</active>
        <label>Address</label>
    </recordTypes>
    <recordTypes>
        <fullName>Tax</fullName>
        <active>true</active>
        <label>Tax</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/MarkInactiveAddressAndTaxController.cls
public without sharing class MarkInactiveAddressAndTaxController {

    @AuraEnabled(cacheable=true)
    public static String getAddressAndTaxType(Id recordId){
        try {
            List<India_GST__c> addressAndTaxRecord = [SELECT Id,Type__c,RecordType.Name FROM India_GST__c WHERE Id=:recordId];
            String message = addressAndTaxRecord[0].Type__c!=null?'Are you sure you want to deactivate the '+addressAndTaxRecord[0].Type__c + ' record? ': 'Are you sure you want to deactivate the Address and tax record?';
            if(!addressAndTaxRecord.isEmpty()){
                if(addressAndTaxRecord[0].RecordType.Name == 'Tax'){
                    message += 'The same will not be available for further process and selection in Infor10.';
                }
            }

            return message;

        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static String markInactive(Id recordId){
        try {
            India_GST__c addressAndTaxRecord = new India_GST__c();
            addressAndTaxRecord.Id = recordId;
            addressAndTaxRecord.Is_Active__c = false;

            update addressAndTaxRecord;

            return 'Success';

        } catch (DMLException e) {
            return e.getDMLMessage(0);
        }
    }
}