force-app/main/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Lead_Country__c</fullName>
        <label>Lead Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Afghanistan</fullName>
                </value>
                <value>
                    <fullName>Albania</fullName>
                </value>
                <value>
                    <fullName>Alderney</fullName>
                </value>
                <value>
                    <fullName>Algeria</fullName>
                </value>
                <value>
                    <fullName>American Samoa</fullName>
                </value>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Angola</fullName>
                </value>
                <value>
                    <fullName>Anguilla</fullName>
                </value>
                <value>
                    <fullName>Antigua and Barbuda</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Armenia</fullName>
                </value>
                <value>
                    <fullName>Aruba</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Azerbaijan</fullName>
                </value>
                <value>
                    <fullName>Bahamas</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Bangladesh</fullName>
                </value>
                <value>
                    <fullName>Barbados</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Benin</fullName>
                </value>
                <value>
                    <fullName>Bermuda</fullName>
                </value>
                <value>
                    <fullName>Bhutan</fullName>
                </value>
                <value>
                    <fullName>Bolivia</fullName>
                </value>
                <value>
                    <fullName>Bosnia and Herzegowina</fullName>
                </value>
                <value>
                    <fullName>Botswana</fullName>
                </value>
                <value>
                    <fullName>Brazil</fullName>
                </value>
                <value>
                    <fullName>Brunei</fullName>
                </value>
                <value>
                    <fullName>India</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

force-app/main/objects/Trigger_Activation__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This List is used to activate/deactivate trigger while deployment.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Object_Name__c</fullName>
        <label>Object Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Trigger Activation</label>
</CustomObject>

classes/LeadCreationControllerTest.cls
@isTest
public class LeadCreationControllerTest {
    
    static testMethod void leadConversionController_TestMethod_1(){
        
        Trigger_Activation__c obj = new Trigger_Activation__c();
        obj.Active__c = true;
        obj.Name = 'Campaign_Trigger';
        obj.Object_Name__c = 'Campaign';
        insert obj;
        
        Trigger_Activation__c obj2 = new Trigger_Activation__c();
        obj2.Active__c = true;
        obj2.Name = 'LeadTrigger';
        obj2.Object_Name__c = 'Lead';
        insert obj2;
        
        List<Lead> leadList=new List<Lead>();
        Lead lead = new Lead();
        lead.Lastname= 'testLead';
        lead.LeadSource = 'Partner';
        lead.company= 'test company';
        lead.Status = 'New';
        lead.Email = 'test99999@test.com';
        lead.Lead_Country__c = 'India';
        leadList.add(lead);
        
        Campaign campaignRec = new Campaign(Name='GCSC-SYS-New Lead Form Addition');
        insert campaignRec;
        LeadCreationController.createLeadRecords(leadList,'GCSC General');
   }
    
    static testMethod void getAppDefination_Negative(){
        try{
           LeadCreationController.getAppDefination();
        }catch(Exception ex){
            
        }
   }
    
    @istest(seealldata=true)
    public static void leadConversionController_TestMethod_Negative(){
        List<Lead> leadList=new List<Lead>();
        Lead lead = new Lead();
        lead.Lastname= 'testLead';
        lead.LeadSource = 'Partner';
        lead.company= 'test company';
        lead.Status = 'New';
        lead.Email = 'test99999@test.com';
        lead.Lead_Country__c = 'India';
        leadList.add(lead);
        Account account =createtestdata.GetAccount();
        Contact contact =createtestdata.getContact(account.Id);
        LeadCreationController.updateContactRecord(contact);
        contact.LID__LinkedIn_Company_Id__c='Test';
        
        try{
        LeadCreationController.createLeadRecords(leadList,'GCSC General');
        LeadCreationController.updateContactRecord(contact);    
        }catch(Exception ex){
            
        }
   }

}