force-app/main/objects/Milestone_Period__c.object
<CustomObject>
    <description>New object for the FC Agent to manage the financial closure of the Project.</description>
    <fields>
        <fullName>FC_Agent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>FC Agent</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Milestone_Period</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Financial_Period_Closed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Financial Period Closed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Signature_Date__c</fullName>
        <label>Signature Date</label>
        <type>Date</type>
    </fields>
    <label>Milestone Period</label>
    <nameField>
        <label>Milestone Period Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Milestone Period</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/RevenueAttribution__c.object
<CustomObject>
    <description>T&amp;E module</description>
    <fields>
        <fullName>Attribution_Period__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Attribution Period</label>
        <referenceTo>Milestone_Period__c</referenceTo>
        <relationshipLabel>Attributions</relationshipLabel>
        <relationshipName>Attributions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Financial_Period_Closed__c</fullName>
        <formula>Attribution_Period__r.Financial_Period_Closed__c</formula>
        <label>Financial Period Closed</label>
        <type>Checkbox</type>
    </fields>
    <label>Attribution</label>
    <nameField>
        <displayFormat>ATTR1{00000}</displayFormat>
        <label>Attribution Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attributions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/MilestonePeriod_Manager.cls
global class MilestonePeriod_Manager{
     // This method updates the Signature_Date__c ,FC_Agent__c field on Milestone Period object when Financial_Period_Closed__c is changed/updated.
     // It also updates the record type of dependent RevenueAttributions depending upon Financial_Period_Closed__c value
     public static void MilestonePeriodUpdateChecks(List<Milestone_Period__c> MilestonePeriodNewList,List<Milestone_Period__c> MilestonePeriodOldList){
        
        List<RecordType> recordTypeLockedList = new List<RecordType>();
        List<RecordType> recordTypeUnLockedList = new List<RecordType>(); 
               
        List<RevenueAttribution__c> raList = new List<RevenueAttribution__c>();
        
        recordTypeLockedList = [select id,name from RecordType where name ='Attribution ReadOnly Record Type'];
        recordTypeUnLockedList = [select id,name from RecordType where name ='Attribution Master RecordType'];  
              
        List<Milestone_Period__c> milestonePeriodLockedList = new List<Milestone_Period__c>();
        List<Milestone_Period__c> milestonePeriodUnLockedList = new List<Milestone_Period__c>();
        
        for(Integer i=0;i<MilestonePeriodNewList.size();i++){
            if(MilestonePeriodNewList[i].Financial_Period_Closed__c != MilestonePeriodOldList[i].Financial_Period_Closed__c && MilestonePeriodNewList[i].Financial_Period_Closed__c==true){
               MilestonePeriodNewList[i].Signature_Date__c = System.today();
               MilestonePeriodNewList[i].FC_Agent__c = UserInfo.getUserId();
            }
            if(MilestonePeriodNewList[i].Financial_Period_Closed__c==true){
                milestonePeriodLockedList.add(MilestonePeriodNewList[i]);
            }
            if(MilestonePeriodNewList[i].Financial_Period_Closed__c==false){
                milestonePeriodUnLockedList.add(MilestonePeriodNewList[i]);
            }
        }
        
        for(RevenueAttribution__c ra : [select id,name from RevenueAttribution__c where Attribution_Period__r.id IN : milestonePeriodLockedList]){
            ra.recordTypeId=recordTypeLockedList[0].id;
            raList.add(ra);      
        }
        for(RevenueAttribution__c ra : [select id,name from RevenueAttribution__c where Attribution_Period__r.id IN : milestonePeriodUnLockedList]){
            ra.recordTypeId=recordTypeUnLockedList[0].id;
            raList.add(ra);      
        }      
        update raList;
      
     }  // end method
     
     // This method results in updating the Signature Date and FC Agent value before Milestone Period record is inserted and if Financial Period Closed value is true
      public static void MilestonePeriodInsertChecks(List<Milestone_Period__c> MilestonePeriodNewList){
        for(Integer i=0;i<MilestonePeriodNewList.size();i++){
            if(MilestonePeriodNewList[i].Financial_Period_Closed__c==true){
                MilestonePeriodNewList[i].Signature_Date__c = System.today();
                MilestonePeriodNewList[i].FC_Agent__c = UserInfo.getUserId();
            }
        }
      }
     
}