force-app/main/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Variation_Opportunity__c</fullName>
        <label>Variation Opportunity</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                    <default>true</default>
                    <label>No</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

objects/ProjectObject__c.object
<CustomObject>
    <description>Used for PSA work</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR (2 AND 3) OR 4</booleanFilter>
            <errorMessage>Project Cannot be created from a Variation Opportunity.</errorMessage>
            <filterItems>
                <field>Opportunity.Variation_Opportunity__c</field>
                <operation>equals</operation>
                <value>No</value>
            </filterItems>
            <filterItems>
                <field>Opportunity.Variation_Opportunity__c</field>
                <operation>equals</operation>
                <value>Yes</value>
            </filterItems>
            <filterItems>
                <field>Opportunity.CreatedDate</field>
                <operation>lessOrEqual</operation>
                <value>4/6/2021, 9:00 AM</value>
            </filterItems>
            <filterItems>
                <field>$User.Id</field>
                <operation>equals</operation>
                <value>0054G00000CSIBq</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Status__c</fullName>
        <label>Project Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Initiation</fullName>
                </value>
                <value>
                    <fullName>Planning</fullName>
                </value>
                <value>
                    <fullName>Executing</fullName>
                </value>
                <value>
                    <fullName>Closing</fullName>
                </value>
                <value>
                    <fullName>Closed/Delivered</fullName>
                </value>
                <value>
                    <fullName>Closed/Cancelled</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Live</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project</label>
    <nameField>
        <displayFormat>P{000000}</displayFormat>
        <label>Project Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <recordTypes>
        <fullName>Project</fullName>
        <active>true</active>
        <label>Project</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/objects/Timesheet_Line__c.object
<CustomObject>
    <description>Time recording in T&amp;E module</description>
    <fields>
        <fullName>Date_Invoiced__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Hours__c</fullName>
        <label>Hours</label>
        <precision>4</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>ProjectObject__c</referenceTo>
        <relationshipLabel>Timesheets</relationshipLabel>
        <relationshipName>Timesheets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Resource__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Resource</label>
        <referenceTo>User</referenceTo>
        <relationshipName>R00N20000001Jpa3EAC</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Task_Category__c</fullName>
        <label>Task Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1:1 Assessment</fullName>
                </value>
                <value>
                    <fullName>1:1 Assessment Feedback Session</fullName>
                </value>
                <value>
                    <fullName>1:1 Developmental Feedback Session</fullName>
                </value>
                <value>
                    <fullName>1:1 Development Assessment</fullName>
                </value>
                <value>
                    <fullName>360 System</fullName>
                </value>
                <value>
                    <fullName>Account Specific</fullName>
                </value>
                <value>
                    <fullName>Admin</fullName>
                </value>
                <value>
                    <fullName>Advisory Services</fullName>
                </value>
                <value>
                    <fullName>Aspiring Minds</fullName>
                </value>
                <value>
                    <fullName>Assessment Centre</fullName>
                </value>
                <value>
                    <fullName>Business Outcome Study / Validation Study</fullName>
                </value>
                <value>
                    <fullName>Client and End-User Support and Consulting</fullName>
                </value>
                <value>
                    <fullName>Client Custom Assessment</fullName>
                </value>
                <value>
                    <fullName>Client Support</fullName>
                </value>
                <value>
                    <fullName>Coaching</fullName>
                </value>
                <value>
                    <fullName>Competency Design</fullName>
                </value>
                <value>
                    <fullName>Competency Mapping</fullName>
                </value>
                <value>
                    <fullName>Coordination of Intra SHL Purchase of Services</fullName>
                </value>
                <value>
                    <fullName>Custom Norm</fullName>
                </value>
                <value>
                    <fullName>Custom Report</fullName>
                </value>
                <value>
                    <fullName>Custom Report - Configured</fullName>
                </value>
                <value>
                    <fullName>Dashboards</fullName>
                </value>
                <value>
                    <fullName>Development Centre</fullName>
                </value>
                <value>
                    <fullName>Development Coach</fullName>
                </value>
                <value>
                    <fullName>Digital Readiness</fullName>
                </value>
                <value>
                    <fullName>Enablement</fullName>
                </value>
                <value>
                    <fullName>Engagement</fullName>
                </value>
                <value>
                    <fullName>Enterprise Leadership</fullName>
                </value>
                <value>
                    <fullName>Generic</fullName>
                </value>
                <value>
                    <fullName>Graduate Solution</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Task__c</fullName>
        <label>Task</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Time_Category__c</controllingField>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>1:1</fullName>
                </value>
                <value>
                    <fullName>Account / Opportunity Specific</fullName>
                </value>
                <value>
                    <fullName>Account Review and Preparation &amp; Facilitation</fullName>
                </value>
                <value>
                    <fullName>Additional Consultancy Coordination</fullName>
                </value>
                <value>
                    <fullName>Ad-hoc Advisory Support</fullName>
                </value>
                <value>
                    <fullName>Admin, Management and Meetings</fullName>
                </value>
                <value>
                    <fullName>Admin for projects – e.g. spec doc creation, JIRA ticket creation, issue management</fullName>
                    <label>Admin for projects - e.g. spec doc creation, JIRA ticket creation, issue management</label>
                </value>
                <value>
                    <fullName>Advisory</fullName>
                </value>
                <value>
                    <fullName>Advisory Program Initiation</fullName>
                </value>
                <value>
                    <fullName>Analysis</fullName>
                </value>
                <value>
                    <fullName>Analytics</fullName>
                </value>
                <value>
                    <fullName>Application Analytics Consulting</fullName>
                </value>
                <value>
                    <fullName>Assessment / Development Centre</fullName>
                </value>
                <value>
                    <fullName>Assessment and Development Delivery</fullName>
                </value>
                <value>
                    <fullName>Assessment Solution Updates</fullName>
                </value>
                <value>
                    <fullName>Associate Contracting</fullName>
                </value>
                <value>
                    <fullName>Associate Payment</fullName>
                </value>
                <value>
                    <fullName>Attending Company Training</fullName>
                </value>
                <value>
                    <fullName>Automation</fullName>
                </value>
                <value>
                    <fullName>BOS/Validation</fullName>
                </value>
                <value>
                    <fullName>Build</fullName>
                </value>
                <value>
                    <fullName>Client Changes</fullName>
                </value>
                <value>
                    <fullName>Client Support</fullName>
                </value>
                <value>
                    <fullName>Coaching</fullName>
                </value>
                <value>
                    <fullName>Company Holiday</fullName>
                </value>
                <value>
                    <fullName>Compassionate Leave</fullName>
                </value>
                <value>
                    <fullName>Competency Framework</fullName>
                </value>
                <value>
                    <fullName>Configuration and Implementation</fullName>
                </value>
                <value>
                    <fullName>Configuration Forms</fullName>
                </value>
                <value>
                    <fullName>Consulting Travel</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Timesheet</label>
    <nameField>
        <displayFormat>TSL{000000}</displayFormat>
        <label>Timesheet Line Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Timesheets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TimeSheetLogMultiProjectControllerTester.cls
@isTest(seeAllData = true)
private class TimeSheetLogMultiProjectControllerTester {
    static testMethod void CoverMethods(){
        Date Date1 = Date.today();
        Date Date2 = Date.Today() +5;  
        String startDate = Date1.format();
        String EndDate = Date2.format();
        TimeSheetLogMultiProjectControllerTester.CreateTimesheetTestRecords();
        TimeSheetLogMultiProjectController.getUserName();
        ProjectObject__c project = [select id from ProjectObject__c where Project_Status__c='In Progress' and opportunity__r.Variation_Opportunity__c='No' limit 1 ];
        TimeSheetLogMultiProjectController.ProjectData(project.Id);
        TimeSheetLogMultiProjectController.ReturnTimeSheets(startDate,EndDate );
        TimeSheetLogMultiProjectController.ReturnCurrentTimeSheets(startDate, EndDate);
        TimeSheetLogMultiProjectController.saveTimesheets(TimeSheetLogMultiProjectControllerTester.CreateTimesheetTestRecords(), new List<Timesheet_Line__c>());
        TimeSheetLogMultiProjectController.saveTimesheets(new List<Timesheet_Line__c>(), TimeSheetLogMultiProjectControllerTester.CreateTimesheetTestRecords());
        
    }
    static testMethod List<Timesheet_Line__c> CreateTimesheetTestRecords(){
        Date timesheetdate = date.Today();
        List<Timesheet_Line__c> TempTimesheets = new List<Timesheet_Line__c>();
        ProjectObject__c project = [select id from ProjectObject__c where Project_Status__c='In Progress' and opportunity__r.Variation_Opportunity__c='No' limit 1];
        for(integer i=0;i<5;i++){
            Timesheet_Line__c timesheet = new Timesheet_Line__c();
            timesheet.Date_Invoiced__c = timesheetdate + i;
            timesheet.Hours__c = 8;
            timesheet.Project__c = project.Id;
            timesheet.Resource__c = userinfo.getUserId();
            //Changes for SSE-17628 start (Added by Jai Khandelwal)
            timesheet.Task__c = 'Other';
            timesheet.Task_Category__c = 'Other';
            timesheet.Time_Category__c = 'Delivery - Other';
            //Changes for SSE-17628 end (Added by Jai Khandelwal)
            TempTimesheets.add(timesheet);
        }
        insert TempTimesheets;
        //Changes for SSE-17628 start (Added by Jai Khandelwal)
        Timesheet_Line__c timesheet = new Timesheet_Line__c();
            timesheet.Date_Invoiced__c = timesheetdate + 6;
            timesheet.Hours__c = 8;
            timesheet.Project__c = project.Id;
            timesheet.Resource__c = userinfo.getUserId();
            timesheet.Task__c = 'Other';
            timesheet.Task_Category__c = 'Other';
            timesheet.Time_Category__c = 'Delivery - Other';
            TempTimesheets.add(timesheet);
        //Changes for SSE-17628 end (Added by Jai Khandelwal)
        return TempTimesheets;
    }
}