force-app/main/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Business_Type__c</fullName>
        <description>Choose the Opportunity Type that best describes the type of business pursued.  
Reboost should only be used with In-Advance clients. 
Cross-sell is simply New Business with a client that has a current commercial relationship.</description>
        <label>Opportunity Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Expansion</fullName>
                </value>
                <value>
                    <fullName>Renewal</fullName>
                </value>
                <value>
                    <fullName>Debooking</fullName>
                    <label>Debooking / Adjustment</label>
                </value>
                <value>
                    <fullName>Extension</fullName>
                </value>
                <value>
                    <fullName>In Arrears</fullName>
                </value>
                <value>
                    <fullName>In Advance</fullName>
                </value>
                <value>
                    <fullName>Managed Services</fullName>
                </value>
                <value>
                    <fullName>Professional Services: non-subscription</fullName>
                </value>
                <value>
                    <fullName>Top Up / Addition</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Order_Status__c</fullName>
        <formula>IF(TEXT(Contract.Status) = &apos;Accepted&apos;,&apos;Client Accepted&apos;,TEXT(Contract.Status))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Contract Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Original_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Original Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Variation / Renewal Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Proposition_Detail__c</fullName>
        <label>Solution</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Call Centre/Customer Service</fullName>
                </value>
                <value>
                    <fullName>Clerical Skills</fullName>
                </value>
                <value>
                    <fullName>Essential [Business] Skills</fullName>
                </value>
                <value>
                    <fullName>Front Line Manager/Supervisors</fullName>
                </value>
                <value>
                    <fullName>IT Skills</fullName>
                </value>
                <value>
                    <fullName>Other (to cover generic/custom ones)</fullName>
                </value>
                <value>
                    <fullName>Retail</fullName>
                </value>
                <value>
                    <fullName>SHL Volume Recruitment Solution</fullName>
                </value>
                <value>
                    <fullName>Previsor Volume Recruitment Solution</fullName>
                </value>
                <value>
                    <fullName>Leadership</fullName>
                </value>
                <value>
                    <fullName>Business Transformation</fullName>
                </value>
                <value>
                    <fullName>Review</fullName>
                </value>
                <value>
                    <fullName>Director</fullName>
                </value>
                <value>
                    <fullName>Senior Manager</fullName>
                </value>
                <value>
                    <fullName>Front Line Manager</fullName>
                </value>
                <value>
                    <fullName>Professional</fullName>
                </value>
                <value>
                    <fullName>Graduate</fullName>
                </value>
                <value>
                    <fullName>Call Centre</fullName>
                </value>
                <value>
                    <fullName>Bank Teller</fullName>
                </value>
                <value>
                    <fullName>HiPo</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Leadership Audit</fullName>
                </value>
                <value>
                    <fullName>Leadership Readiness</fullName>
                </value>
                <value>
                    <fullName>Enterprise Leadership</fullName>
                </value>
                <value>
                    <fullName>Sales Audit</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Proposition__c</fullName>
        <inlineHelpText>Select the closest use-case(s) that best defines client requirements.</inlineHelpText>
        <label>Use-case</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <controllingField>TM_Phase__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Early Careers Hiring</fullName>
                </value>
                <value>
                    <fullName>Graduate Hiring</fullName>
                </value>
                <value>
                    <fullName>Volume Hiring</fullName>
                </value>
                <value>
                    <fullName>Apprentice Hiring</fullName>
                </value>
                <value>
                    <fullName>Technology Hiring</fullName>
                </value>
                <value>
                    <fullName>Sales Transformation Hiring</fullName>
                </value>
                <value>
                    <fullName>Managerial Hiring</fullName>
                </value>
                <value>
                    <fullName>Senior Leadership / Executive  Hiring</fullName>
                </value>
                <value>
                    <fullName>Professional</fullName>
                </value>
                <value>
                    <fullName>Mobilize: Leadership &amp; Succession Planning</fullName>
                </value>
                <value>
                    <fullName>Mobilize: Potential</fullName>
                </value>
                <value>
                    <fullName>Sales Transformation Review</fullName>
                </value>
                <value>
                    <fullName>Review: Digital Readiness</fullName>
                </value>
                <value>
                    <fullName>Review: Remote Work</fullName>
                </value>
                <value>
                    <fullName>Review: Custom / Others</fullName>
                </value>
                <value>
                    <fullName>Develop Talent</fullName>
                </value>
                <value>
                    <fullName>TMReview</fullName>
                </value>
                <value>
                    <fullName>TMMobilise</fullName>
                </value>
                <value>
                    <fullName>Talent Management</fullName>
                </value>
                <value>
                    <fullName>Professional Hiring</fullName>
                </value>
                <value>
                    <fullName>HiPo</fullName>
                </value>
                <value>
                    <fullName>Enterprise Leadership</fullName>
                </value>
                <value>
                    <fullName>Succession Planning</fullName>
                </value>
                <value>
                    <fullName>Manager Development</fullName>
                </value>
                <value>
                    <fullName>Sales Transformation</fullName>
                </value>
                <value>
                    <fullName>Skills Development</fullName>
                </value>
                <value>
                    <fullName>Talent Mobility</fullName>
                </value>
                <value>
                    <fullName>Manager Development &amp; Sales Transformation &amp; HiPo</fullName>
                </value>
                <value>
                    <fullName>HiPo &amp; Succession Planning &amp; ELD</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TM_Phase__c</fullName>
        <description>This field is used to replace the existing proposition field.</description>
        <inlineHelpText>Select the Client Interest that best defines the scope of the client’s project, or Combined if the project is mixed.</inlineHelpText>
        <label>Client Interest</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Talent Acquisition</fullName>
                </value>
                <value>
                    <fullName>Talent Management</fullName>
                </value>
                <value>
                    <fullName>TAandTMCombined</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Talent_Level__c</fullName>
        <description>This field is created as a part of Nomenclature(SSE--113)</description>
        <inlineHelpText>Select the level(s) of employee that best defines the scope of the client’s project.</inlineHelpText>
        <label>Talent Level</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Vocational</fullName>
                </value>
                <value>
                    <fullName>Entry Level / Associate</fullName>
                </value>
                <value>
                    <fullName>Graduate and Intern</fullName>
                </value>
                <value>
                    <fullName>Professional / Individual Contributor</fullName>
                </value>
                <value>
                    <fullName>Supervisor</fullName>
                </value>
                <value>
                    <fullName>Manager</fullName>
                </value>
                <value>
                    <fullName>Individual Contributor Leader</fullName>
                </value>
                <value>
                    <fullName>Senior leadership</fullName>
                </value>
                <value>
                    <fullName>All Levels</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Talent_Segment__c</fullName>
        <description>This is new field, created as a part of nomenclature change(SSE--113)</description>
        <inlineHelpText>Select the overall talent segment or population that the client is focused on.</inlineHelpText>
        <label>Talent Segment</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Graduate / Apprentice</fullName>
                </value>
                <value>
                    <fullName>High Potential</fullName>
                </value>
                <value>
                    <fullName>Functional / Professional</fullName>
                </value>
                <value>
                    <fullName>Manager / Leader</fullName>
                </value>
                <value>
                    <fullName>Volume</fullName>
                </value>
                <value>
                    <fullName>Other / Unknown</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Variation_Opportunity__c</fullName>
        <label>Variation Opportunity</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                    <default>true</default>
                    <label>No</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

force-app/main/objects/Order.object
<CustomObject>
    <fields>
        <fullName>Variation_Opportunity__c</fullName>
        <formula>Text(Opportunity.Variation_Opportunity__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Variation Order</label>
        <type>Text</type>
    </fields>
</CustomObject>

classes/CreateVariation.cls
public class CreateVariation{

public boolean Showbutton{get;set;}
public Opportunity opportunity{get;set;}
public string OppName{get;set;}
public string CloseDate{get;set;}
public list<Opportunity> OriginalOpportunity=new list<opportunity>();
Public string Recordtype{get;set;}
public String oppId{get;set;}
    public boolean orderstatus {get;set;}
       public String RecordType1 {get;set;}
  
    public list <Order> originalorder = new list <Order>();
//Added by--Starts--Prabhat Arora: for SSE-7065
List<SelectOption> options = new List<SelectOption>(); 
String UpdRecType;
//Added by--Ends--Prabhat Arora: for SSE-7065

public CreateVariation(apexpages.standardcontroller stdController){
    
    this.opportunity = (Opportunity)stdController.getRecord();
    //oppId = ApexPages.currentPage().getParameters().get('opportunity.id');
    oppId = opportunity.id;
    system.debug('OptyId before TT=*>'+oppId);
    if(oppId==null){
        oppId = ApexPages.currentPage().getParameters().get('OptyId');
        }
    system.debug('RecordType Id==*>'+Recordtype);
    system.debug('OptyId after TT=*>'+oppId);
    
//OriginalOpportunity=[select id, name, Original_Opportunity__c,StageName,Business_Type__c,Order_Status__c,Variation_Opportunity__c,Proposition__c,Proposition_Detail__c,TM_Phase__c,Talent_Level__c,Talent_Segment__c,Offering__c,Client_Business_Function__c from opportunity where StageName='Closed/Won' AND Variation_Opportunity__c = 'No' AND  Order_Status__c= 'Complete' AND id =: oppId limit 1]; //Changes added by Apoorva for SSE-113  Added "TM Phase, Talent_Level__c,Talent_Segment__c,Offering__c,Client_Business_Function__c".
originalorder = [Select id, Status, OpportunityId,Order_Year__c from Order where Status =:'Activated'and Order_Year__c != 0 and OpportunityId =: oppId];
    System.debug('originalorder');
    if(originalorder.size()>0)
           

        orderstatus = true;
        else 
        {
            orderstatus = false;
        }
           System.debug('orderstatus');
    OriginalOpportunity=[select id, name, Original_Opportunity__c,StageName,RecordType.Name,Client_Business_Function__c,Business_Type__c,Order_Status__c,Variation_Opportunity__c,Proposition_Detail__c,TM_Phase__c,Talent_Segment__c,Previous_Record_Type__c from opportunity where StageName='Closed/Won' AND Variation_Opportunity__c = 'No' AND  Order_activated_and_greater_than_zero__c   ='TRUE' AND id =: oppId limit 1]; // Edited by Priyank on 14/7/2020
    if(OriginalOpportunity.size()>0)
        {
            oppId = OriginalOpportunity[0].id;
            system.debug('oppId:===>'+oppId);
            date dt=System.today();
            closedate=dt.format();
            ApexPages.currentPage().getParameters().put('RFPTender', 'false');
            //closedate= String.valueOf(dt);
            
            ApexPages.currentPage().getParameters().put('OppName', OriginalOpportunity[0].name);
            if(OriginalOpportunity[0].TM_Phase__c != null){
                            system.debug('TM_Phase__c:===>'+OriginalOpportunity[0].TM_Phase__c);
            ApexPages.currentPage().getParameters().put('Proposition',EncodingUtil.urlEncode(OriginalOpportunity[0].TM_Phase__c,'UTF-8'));
            }
            system.debug('TM_Phase__c:===>'+OriginalOpportunity[0].TM_Phase__c);            
          //ApexPages.currentPage().getParameters().put('PropositionDetail',OriginalOpportunity[0].Proposition_Detail__c ); Changes added by Apoorva for SSE-113 Commented this line of code to remove reference of Proposition Details field.
            ApexPages.currentPage().getparameters().put('CloseDate',closedate);
			  ApexPages.currentPage().getparameters().put('Function',OriginalOpportunity[0].Client_Business_Function__c);            
            ApexPages.currentPage().getparameters().put('UserName',UserInfo.getName());
            ApexPages.currentPage().getparameters().put('BusinessType',OriginalOpportunity[0].Business_Type__c);
           // ApexPages.currentPage().getparameters().put('RecordType1',OriginalOpportunity[0].Previous_Record_Type__c  );
  // ApexPages.currentPage().getparameters().put('BusinessType',OriginalOpportunity[0].Business_Type__c);
            
            //Added--Start by Apoorva Gautam For SSE-113---Date--22June-2015
           /* if(OriginalOpportunity[0].Talent_Level__c!=null ){
            ApexPages.currentPage().getParameters().put('TalentLevel',OriginalOpportunity[0].Talent_Level__c  );
            }
            //if(OriginalOpportunity[0].Talent_Segment__c!=null){
            //ApexPages.currentPage().getParameters().put('TalentSegment',OriginalOpportunity[0].Talent_Segment__c );
            //}
            if(OriginalOpportunity[0].Offering__c!=null){
            ApexPages.currentPage().getParameters().put('Offerings',OriginalOpportunity[0].Offering__c );
            }
            if(OriginalOpportunity[0].Client_Business_Function__c!=null){
            ApexPages.currentPage().getParameters().put('Function',EncodingUtil.urlEncode(OriginalOpportunity[0].Client_Business_Function__c,'UTF-8' ));
            } */ // commented by Priyank on 14/7/2020
            //Added---Ended by Apoorva Gautam For SSE-113---Date--22June-2015
           
            ShowButton =true;
        }
            else
        {
            ShowButton =false;}
        }
    
    
        
//Added by--Starts--Prabhat Arora: for SSE-7065     
   
        
    
        Public String getRecordtype()
            {
            
            return Recordtype;
            }
        
        
        
        public PageReference RecSelPage() 
            {            
            string id = ApexPages.currentPage().getParameters().get('id');            
            system.debug('Opporty ID===>'+oppId);    
            PageReference secondPage = new PageReference('/apex/IgniteRecTypeSel_vfpage?OptyId='+id);
            secondPage.setRedirect(true);
            return secondPage;
            }
            
        public List<SelectOption> getItems(){
            String ConfiguratorLabel = System.label.IgniteRecordType;
            String StandardLabel = System.label.StandardRecordType; 
                options.add(new SelectOption(ConfiguratorLabel ,'Configurator')); 
                options.add(new SelectOption(StandardLabel ,'Standard'));
            Recordtype = 'Configurator'; 
            return options; 
            }
            
        public void setRecordtype(String Recordtype)
            {
            this.Recordtype = Recordtype;
            system.debug('Oppty ID 3==>'+Recordtype);
            }
            
        public pageReference cancel() {
        string id = ApexPages.currentPage().getParameters().get('OptyId');
        PageReference opptyRecPage = new PageReference('/apex/IgnniteCreateVariation_vfpage?id='+id);
        opptyRecPage.setRedirect(true);
        return opptyRecPage ;    
    }         
//Added by--Ends--Prabhat Arora: for SSE-7065

}