force-app/main/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Business_Type__c</fullName>
        <description>Choose the Opportunity Type that best describes the type of business pursued.  
Reboost should only be used with In-Advance clients. 
Cross-sell is simply New Business with a client that has a current commercial relationship.</description>
        <label>Opportunity Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Expansion</fullName>
                </value>
                <value>
                    <fullName>Renewal</fullName>
                </value>
                <value>
                    <fullName>Debooking</fullName>
                    <label>Debooking / Adjustment</label>
                </value>
                <value>
                    <fullName>Extension</fullName>
                </value>
                <value>
                    <fullName>In Arrears</fullName>
                </value>
                <value>
                    <fullName>In Advance</fullName>
                </value>
                <value>
                    <fullName>Managed Services</fullName>
                </value>
                <value>
                    <fullName>Professional Services: non-subscription</fullName>
                </value>
                <value>
                    <fullName>Top Up / Addition</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Eligible_for_Auto_Close__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Eligible for Auto-Close?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Original_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Original Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Variation / Renewal Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Qualified_for_Auto_Close__c</fullName>
        <description>This formula describes, which all records are ready to update &quot;Eligible for Auto Close&quot; field on Opp</description>
        <formula>AND(
    NOT(IsClosed),
    Can_be_Auto_renewed__c = TRUE,
    ISPICKVAL(Business_Type__c, &quot;Renewal&quot;),
    ISPICKVAL(Account.Status__c, &quot;Approved&quot;),
    Eligible_for_Auto_Close__c = FALSE,
    Renewal_Opportunity__c = TRUE,
    Opportunity_Deal_Year__c = 1,
    NOT(ISBLANK(Original_Opportunity__c)),
    ISPICKVAL(Actual_Record_Type_Name__c, &quot;Configurator Opportunity&quot;),
    ISBLANK(Rejected_Order_IDs__c),
    Total_Product_Count__c &gt; 0,
    ISBLANK(TEXT(CLM_Contract_Status__c)),
    NOT(ISBLANK(Renewal_Date__c)),
    Days_left_to_Close_Opp__c&gt; 31,
    Days_left_to_Close_Opp__c&lt; 365
)</formula>
        <label>Qualified for Auto Close?</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

force-app/main/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <formula>TEXT(PricebookEntry.Product2.Status__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
</CustomObject>

classes/EligibleOppBatch.cls
/**
* ----------------------------------------------------------------------------------------
* Class Name     : EligibleOppBatch
* Author         : Prabhat Arora
* Created Date   : 29-08-2025
* Purpose        : 
*   - This batch job identifies Opportunities eligible for auto-close
*   - Criteria:
*        1. Qualified_for_Auto_Close__c = TRUE  (Boolean formula field covering all conditions)       
*        2. Exclude Opportunities having any OpportunityLineItem:
*             a. With Status__c = 'End of Life'
*             b. OR created by the Excel Connector API User
*   - If eligible, sets Eligible_for_Auto_Close__c = TRUE
*
* Usage          : Scheduled via EligibleOppScheduler to run daily at specific time.
* ----------------------------------------------------------------------------------------
*/

public with sharing class EligibleOppBatch implements Database.Batchable<SObject> {
    
    //Start Method: Defines the query to collect all Opportunities that are potentially Eligible.
    public Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator([
            SELECT Id
            FROM Opportunity
            WHERE Qualified_for_Auto_Close__c = true
        ]);
    }
    
    /*
* Execute method
* Called for each batch "scope" of Opportunities.
*  - Collects Opportunity Ids in current scope
*  - Queries related OpportunityLineItems
*  - Marks Opportunities with disqualifying OLIs (End of Life OR created by Excel Connector)
*  - Updates only Opportunities that remain eligible
*/
    public void execute(Database.BatchableContext bc, List<Opportunity> scope) {
        Set<Id> oppIds = new Set<Id>();
        for (Opportunity opp : scope) {
            oppIds.add(opp.Id);
        }
        
        // Find disqualified Opps based on OLI conditions
        Set<Id> disqualifiedOpps = new Set<Id>();
        for (OpportunityLineItem oli : [
            SELECT OpportunityId
            FROM OpportunityLineItem
            WHERE OpportunityId IN :oppIds
            AND (Status__c = 'End of Life' OR CreatedById = :Label.ExcelConnectorUserId)
        ]) {
            disqualifiedOpps.add(oli.OpportunityId);
        }
        
        //JIRA : SSE-28977 Changes START
        // Find disqualified Opps based on If original opp is extension then not allow for auto close 
        for (Opportunity opp : [
            SELECT Id
            FROM Opportunity
            WHERE Id IN :oppIds
            AND Original_Opportunity__c != null
            AND Original_Opportunity__r.Business_Type__c = 'Extension'
        ]) {
            disqualifiedOpps.add(opp.Id);
        }
        
        //JIRA : SSE-28977 Changes END
        
        
        // Update only qualifying Opps
        List<Opportunity> updates = new List<Opportunity>();
        for (Opportunity opp : scope) {
            if (!disqualifiedOpps.contains(opp.Id)) {
                opp.Eligible_for_Auto_Close__c = true;
                updates.add(opp);
            }
        }
        
        if (!updates.isEmpty()) {
            update updates;
        }
    }
    
    public void finish(Database.BatchableContext bc) {
        // Optional: logging, notifications, chaining
    }
}