force-app/main/objects/Order.object
<CustomObject>
    <fields>
        <fullName>Original_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Original Order</label>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Reduction/Variation Orders</relationshipLabel>
        <relationshipName>OriginalOrders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reduction_Order__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checkbox to define whether order is reduction or not.</description>
        <label>Reduction order</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

classes/RecallCancelledOrders.cls
public class RecallCancelledOrders {
    @InvocableMethod
    public static void recallOrders(list<order> orderlist){
        //Object record id to recall the approval process
        for(order ord : [select id,status from order where Reduction_order__c = true and Original_Order__c = :orderlist.get(0).id]){
            system.debug('gcscreductionorder'+ord);
            if(ord.status == 'In Approval')
                orderlist.add(ord);
        }
        //user u = [select id from user where profile.name = 'System Administrator' limit 1];
        //system.runAs(u){
        for(order ord : orderlist){
            String recordId = ord.id;
            //Get Process Instance Work Items
            ProcessInstanceWorkitem[] piWorkItems = [SELECT Id FROM ProcessInstanceWorkItem WHERE ProcessInstance.TargetObjectId = :recordId AND ProcessInstance.Status = 'Pending']; 
            if(piWorkItems.size() > 0){
                //Create Process Work Item Request
                Approval.ProcessWorkItemRequest pwiRequest = new Approval.ProcessWorkItemRequest();
                pwiRequest.setAction('Removed');
                pwiRequest.setWorkItemId(piWorkItems[0].Id);
                Approval.ProcessResult result = Approval.process(pwiRequest);
            }
        }
        //}
    }
}