force-app/main/objects/Order.object
<CustomObject>
    <fields>
        <fullName>Order_Year__c</fullName>
        <label>Order Year</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Reduction_Order__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checkbox to define whether order is reduction or not.</description>
        <label>Reduction order</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Variation_Opportunity__c</fullName>
        <formula>Text(Opportunity.Variation_Opportunity__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Variation Order</label>
        <type>Text</type>
    </fields>
</CustomObject>

classes/ReductionOrderLEXClass.cls
public with sharing  class ReductionOrderLEXClass {
    @AuraEnabled 
	public static string relatedOrderRecord(String OrderId){
        List<Order> ord = [Select id,name,status,Reduction_Order__c,Variation_Opportunity__c,OpportunityId from Order where OpportunityId=:OrderId AND Order_Year__c!= 0 AND Reduction_Order__c=:false AND Variation_Opportunity__c=:'No'];
        String ordId = ord[0].id;
        return ordId;
	}
}